// California Angels Broadcast — 1984
// Radio: Dave Niehaus & Don Drysdale (KRLA/KMPC) / TV: Dick Enberg & Joe Garagiola
// Anaheim Stadium — home of the Angels
// All stats cutoff: end of 1983 season

export function pickAngelsLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickAngelsPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Rod Carew": {
    lines: [
      "Rod Carew's full name is Rodney Cline Carew.",
      "Rod Carew was born in the Panama Canal Zone on October 1, 1945.",
      "Rod Carew was born aboard a train while his mother was being taken to a hospital.",
      "Rod Carew was named after Dr. Rodney Cline, who helped complete his delivery.",
      "Rod Carew moved with his family to New York while he was a teenager.",
      "Minnesota signed Rod Carew after he impressed the Twins during a tryout at Yankee Stadium.",
      "Rod Carew made his major-league debut on April 11, 1967.",
      "Rod Carew singled off Dave McNally during his first major-league at-bat.",
      "Rod Carew won the 1967 American League Rookie of the Year Award.",
      "Rod Carew was selected to the All-Star team during each of his first 17 major-league seasons through 1983.",
      "Rod Carew began his career as a second baseman before eventually moving to first base.",
      "Rod Carew stole home seven times during the 1969 season.",
      "Five of Carew's seven steals of home in 1969 occurred during the first inning.",
      "Rod Carew has won seven American League batting championships.",
      "Carew's batting-title seasons were 1969, 1972, 1973, 1974, 1975, 1977 and 1978.",
      "Rod Carew batted .388 with 239 hits during the 1977 season.",
      "Rod Carew won the 1977 American League Most Valuable Player Award.",
      "Rod Carew received the Roberto Clemente Award in 1977 for his play and charitable activities.",
      "Minnesota traded Rod Carew to California before the 1979 season.",
      "Rod Carew entered 1983 having batted at least .300 in 14 consecutive seasons.",
      "Rod Carew extended that streak to 15 seasons by batting .339 in 1983.",
      "Rod Carew collected 160 hits, 24 doubles and 57 walks during the 1983 season.",
      "Rod Carew recorded a .409 on-base percentage in 1983.",
      "Rod Carew struck out only 48 times in 536 plate appearances during the 1983 season.",
      "Rod Carew's bat control allows him to direct pitches into nearly any open portion of the field.",
      "Rod Carew frequently changes his stance and position in the batter's box according to the pitcher and defensive alignment.",
      "Rod Carew remains one of baseball's most difficult hitters to strike out entering the 1984 season.",
    ],
  },
  "Brian Downing": {
    lines: [
      "Brian Downing's full name is Brian Jay Downing.",
      "Brian Downing was born in Los Angeles, California.",
      "Brian Downing developed in the Chicago White Sox organization.",
      "Brian Downing made his major-league debut during the 1973 season.",
      "Brian Downing began his major-league career primarily as a catcher.",
      "Brian Downing was acquired by California from the White Sox before the 1978 season.",
      "Brian Downing became the Angels' regular catcher immediately after joining the club.",
      "Brian Downing enjoyed a breakthrough season in 1979.",
      "Brian Downing batted .326 with a .418 on-base percentage during the 1979 season.",
      "Brian Downing was selected to the 1979 American League All-Star team as a catcher.",
      "Brian Downing later shifted from catcher to left field to reduce the physical wear on his body.",
      "Brian Downing became one of baseball's most dedicated weight-training enthusiasts.",
      "His unusually muscular build helped make him a source of power from the leadoff position.",
      "Brian Downing hit a career-high 28 home runs during the 1982 season.",
      "Brian Downing helped California win the American League West in both 1979 and 1982.",
      "Brian Downing appeared in 113 games during the 1983 season.",
      "Brian Downing hit 19 home runs and drove in 53 runs in 1983.",
      "Brian Downing scored 68 runs during the 1983 season.",
      "Brian Downing drew 62 walks and recorded a .352 on-base percentage in 1983.",
      "Downing's patience makes him dangerous even when his batting average is relatively low.",
      "Brian Downing can work a long at-bat, reach base and still supply middle-of-the-order power.",
      "Brian Downing's catching background gives him additional knowledge of how opposing pitchers approach hitters.",
    ],
  },
  "Fred Lynn": {
    lines: [
      "Fred Lynn's full name is Fredric Michael Lynn.",
      "Fred Lynn was born in Chicago but moved to Southern California as a small child.",
      "Fred Lynn played college baseball at the University of Southern California.",
      "Fred Lynn began his major-league career with the Boston Red Sox.",
      "Fred Lynn and Jim Rice were known as Boston's \"Gold Dust Twins.\"",
      "Fred Lynn produced one of baseball's greatest rookie seasons in 1975.",
      "Fred Lynn batted .331 with 47 doubles, 21 home runs and 105 RBI in 1975.",
      "Fred Lynn led the American League in runs, doubles, slugging percentage and OPS during his rookie season.",
      "Fred Lynn became the first player to win Rookie of the Year and Most Valuable Player honors during the same season.",
      "Fred Lynn helped Boston reach the 1975 World Series.",
      "Fred Lynn hit a three-run home run in Game Seven of the 1975 World Series.",
      "Lynn crashed into Fenway Park's outfield wall while pursuing a Ken Griffey triple during that game.",
      "Fred Lynn hit three home runs, a triple and a single against Detroit on June 18, 1975.",
      "Lynn drove in 10 runs during that performance.",
      "Fred Lynn won Gold Glove Awards in 1975, 1978, 1979 and 1980.",
      "Fred Lynn won the American League batting championship by hitting .333 in 1979.",
      "He also hit 39 home runs, drove in 122 and slugged .637 during the 1979 season.",
      "Fred Lynn joined the Angels before the 1981 season.",
      "Fred Lynn helped California win the 1982 American League West championship.",
      "Fred Lynn hit the first grand slam in All-Star Game history during the 1983 game.",
      "Lynn's grand slam helped the American League earn its first All-Star victory since 1971.",
      "Fred Lynn appeared in 117 games during the 1983 season.",
      "Fred Lynn batted .272 with 20 doubles, three triples and 22 home runs in 1983.",
      "Fred Lynn drove in 74 runs and recorded a .352 on-base percentage in 1983.",
      "Fred Lynn is capable of playing any of the three outfield positions.",
      "His smooth defensive style can make difficult catches appear routine.",
      "Fred Lynn remains a dangerous left-handed power hitter when healthy.",
    ],
  },
  "Reggie Jackson": {
    lines: [
      "Reggie Jackson's full name is Reginald Martinez Jackson.",
      "Reggie Jackson is commonly known as \"Mr. October.\"",
      "Reggie Jackson was born in Abington, Pennsylvania.",
      "Reggie Jackson was a standout football and baseball player while growing up.",
      "Reggie Jackson attended Arizona State University.",
      "Kansas City selected Reggie Jackson with the second overall pick of the 1966 amateur draft.",
      "Reggie Jackson remained with the franchise when the Athletics moved from Kansas City to Oakland.",
      "Reggie Jackson hit 47 home runs during the 1969 season.",
      "Reggie Jackson helped Oakland reach the postseason in five consecutive seasons from 1971 through 1975.",
      "Reggie Jackson injured his leg during the 1972 American League Championship Series.",
      "The injury prevented him from playing in Oakland's 1972 World Series victory.",
      "Reggie Jackson helped Oakland win additional World Series championships in 1973 and 1974.",
      "Reggie Jackson won the 1973 American League Most Valuable Player Award.",
      "Reggie Jackson was also named Most Valuable Player of the 1973 World Series.",
      "Reggie Jackson played for Baltimore in 1976 before signing with the New York Yankees.",
      "Reggie Jackson helped the Yankees win consecutive World Series championships in 1977 and 1978.",
      "Reggie Jackson hit three home runs on three consecutive pitches during Game Six of the 1977 World Series.",
      "That performance firmly established the nickname \"Mr. October.\"",
      "Reggie Jackson was named the 1977 World Series Most Valuable Player.",
      "Reggie Jackson tied for the American League lead with 41 home runs in 1980.",
      "Reggie Jackson joined the Angels as a free agent before the 1982 season.",
      "Reggie Jackson led the American League with 39 home runs during his first season with California.",
      "Reggie Jackson helped the Angels win the 1982 American League West championship.",
      "Reggie Jackson entered 1983 with 464 career home runs.",
      "Reggie Jackson appeared in 116 games during the 1983 season.",
      "Reggie Jackson hit 14 home runs and drove in 49 runs in 1983.",
      "Reggie Jackson drew 52 walks but struck out 140 times during the 1983 season.",
      "Reggie Jackson enters 1984 with 478 career home runs.",
      "Reggie Jackson has already played on five World Series championship clubs.",
      "Reggie Jackson's combination of power, confidence and postseason history makes every important at-bat feel like an event.",
    ],
  },
  "Doug DeCinces": {
    lines: [
      "Doug DeCinces' full name is Douglas Vernon DeCinces.",
      "Doug DeCinces was born in Burbank, California.",
      "Doug DeCinces played college baseball at Los Angeles Pierce College.",
      "Baltimore selected Doug DeCinces during the 1970 amateur draft.",
      "Doug DeCinces reached the major leagues with the Orioles during the 1973 season.",
      "Doug DeCinces faced the difficult task of succeeding Brooks Robinson at third base.",
      "DeCinces gradually became one of Baltimore's primary power hitters.",
      "Doug DeCinces hit a dramatic walk-off home run against Detroit on June 22, 1979.",
      "That victory became closely associated with the rise of the phrase \"Orioles Magic.\"",
      "Doug DeCinces helped Baltimore reach the 1979 World Series.",
      "California acquired Doug DeCinces before the 1982 season.",
      "Doug DeCinces enjoyed the finest season of his career during his first year with the Angels.",
      "Doug DeCinces batted .301 with 42 doubles and 30 home runs in 1982.",
      "Doug DeCinces drove in 97 runs and scored 94 times during the 1982 season.",
      "Doug DeCinces finished third in the 1982 American League Most Valuable Player voting.",
      "Doug DeCinces helped California win the 1982 American League West.",
      "A foul ball broke DeCinces' nose during the 1982 American League Championship Series.",
      "DeCinces remained in the series despite the injury.",
      "Doug DeCinces began the 1983 season strongly and earned his first All-Star selection.",
      "Injuries limited Doug DeCinces to 95 games during the 1983 season.",
      "Doug DeCinces batted .281 with 19 doubles, three triples and 18 home runs in 1983.",
      "Doug DeCinces drove in 65 runs despite missing more than two months.",
      "Doug DeCinces slugged .495 during the 1983 season.",
      "DeCinces has established a reputation for improving offensively as the season progresses.",
      "A healthy Doug DeCinces gives California a proven power hitter and experienced defensive third baseman.",
    ],
  },
  "Bobby Grich": {
    lines: [
      "Bobby Grich's full name is Robert Anthony Grich.",
      "Bobby Grich was born in Muskegon, Michigan.",
      "Bobby Grich spent much of his youth in Southern California.",
      "Baltimore selected Bobby Grich in the first round of the 1967 amateur draft.",
      "Bobby Grich reached the major leagues with the Orioles during the 1970 season.",
      "Bobby Grich became Baltimore's regular second baseman in 1972.",
      "Bobby Grich made his first All-Star team during the 1972 season.",
      "Bobby Grich developed into one of baseball's finest combinations of power, patience and infield defense.",
      "Bobby Grich won four consecutive Gold Glove Awards from 1973 through 1976.",
      "Bobby Grich helped Baltimore win the American League East in 1973 and 1974.",
      "Bobby Grich signed with California as a free agent before the 1977 season.",
      "A serious back injury interrupted Grich's first season with the Angels.",
      "Bobby Grich returned to become a central part of California's first division championship in 1979.",
      "Bobby Grich hit 30 home runs and drove in 101 runs during the 1979 season.",
      "Bobby Grich tied for the American League lead with 22 home runs during the strike-shortened 1981 season.",
      "Grich batted .304 with a .378 on-base percentage and a .543 slugging percentage in 1981.",
      "Bobby Grich received a Silver Slugger Award in 1981.",
      "Bobby Grich helped California return to the postseason in 1982.",
      "Bobby Grich appeared in 120 games during the 1983 season.",
      "Bobby Grich batted .292 with 17 doubles and 16 home runs in 1983.",
      "Bobby Grich drove in 62 runs and scored 65 times during the 1983 season.",
      "Bobby Grich drew 76 walks and recorded a .414 on-base percentage in 1983.",
      "Grich's .414 on-base percentage was the highest among California's regular players.",
      "Bobby Grich can contribute through power, plate discipline and dependable middle-infield defense.",
      "Grich is willing to absorb pitches, turn double plays and work deep counts.",
      "Bobby Grich remains one of California's most complete players entering 1984.",
    ],
  },
  "Gary Pettis": {
    lines: [
      "Gary Pettis' full name is Gary George Pettis.",
      "Gary Pettis was born in Oakland, California.",
      "Gary Pettis attended Castlemont High School in Oakland.",
      "Gary Pettis is a switch-hitter who throws right-handed.",
      "California selected Gary Pettis in the sixth round of the 1979 amateur draft.",
      "Gary Pettis developed as a center fielder in the Angels' farm system.",
      "Pettis' speed and defensive range quickly became his most noticeable tools.",
      "Gary Pettis made his major-league debut during the 1982 season.",
      "Gary Pettis spent most of the 1983 season with Triple-A Edmonton.",
      "Gary Pettis appeared in 132 games for Edmonton during the 1983 season.",
      "Gary Pettis batted .285 with 151 hits for Edmonton.",
      "Pettis collected 27 doubles, eight triples and 11 home runs in Triple-A.",
      "Gary Pettis scored 138 runs during the 1983 minor-league season.",
      "Gary Pettis stole 52 bases for Edmonton.",
      "Gary Pettis also drew 81 walks and recorded a .382 on-base percentage.",
      "Pettis joined California late in the 1983 season.",
      "Gary Pettis appeared in 22 major-league games in 1983.",
      "Gary Pettis batted .294 with two doubles, three triples and three home runs.",
      "Gary Pettis scored 19 runs in only 22 games.",
      "Gary Pettis stole eight bases during his brief major-league opportunity.",
      "Pettis' speed allows him to pressure defenses as a hitter, runner and center fielder.",
      "Gary Pettis enters 1984 as an exciting but still relatively inexperienced major-league player.",
    ],
  },
  "Bob Boone": {
    lines: [
      "Bob Boone's full name is Robert Raymond Boone.",
      "Bob Boone was born in San Diego, California.",
      "Bob Boone is the son of former major-league infielder Ray Boone.",
      "Bob Boone played college baseball at Stanford University.",
      "Philadelphia selected Bob Boone during the 1969 amateur draft.",
      "Bob Boone reached the major leagues with the Phillies during the 1972 season.",
      "Bob Boone became Philadelphia's regular catcher shortly after reaching the majors.",
      "Bob Boone was selected to the National League All-Star team in 1976, 1978 and 1979.",
      "Bob Boone helped Philadelphia win three consecutive National League East titles from 1976 through 1978.",
      "Bob Boone caught for the Phillies during the 1980 World Series.",
      "Bob Boone was behind the plate when Philadelphia won the first World Series championship in franchise history.",
      "California acquired Bob Boone before the 1982 season.",
      "Bob Boone won an American League Gold Glove during his first season with the Angels.",
      "Bob Boone helped California win the 1982 American League West championship.",
      "Bob Boone was selected to his fourth All-Star team in 1983.",
      "Bob Boone appeared in 142 games during the 1983 season.",
      "Boone played more games than any other California player in 1983.",
      "Bob Boone batted .256 with 120 hits and 18 doubles.",
      "Bob Boone hit nine home runs and drove in 52 runs during the 1983 season.",
      "Bob Boone caught more than 1,200 innings during the 1983 season.",
      "Bob Boone's durability allows the Angels to use the same catcher almost every day.",
      "Boone is highly regarded for preparing pitchers and controlling the pace of a game.",
      "Bob Boone uses a quick release and accurate throwing arm against opposing base stealers.",
      "Bob Boone's baseball family background gives him experience with the game from several generations.",
      "Bob Boone provides defensive stability behind a pitching staff containing both young prospects and longtime veterans.",
    ],
  },
  "Dick Schofield": {
    lines: [
      "Dick Schofield's full name is Richard Craig Schofield.",
      "Dick Schofield is the son of longtime major-league infielder John \"Ducky\" Schofield.",
      "Dick Schofield attended Griffin High School in Springfield, Illinois.",
      "California selected Dick Schofield with the third overall pick of the 1981 amateur draft.",
      "Dick Schofield was drafted directly out of high school.",
      "Dick Schofield developed primarily as a shortstop in the Angels' farm system.",
      "Schofield's defensive ability helped him advance quickly through the organization.",
      "Dick Schofield spent part of the 1983 season with Triple-A Edmonton.",
      "Dick Schofield made his major-league debut on September 8, 1983.",
      "Dick Schofield was only 20 years old at the time of his debut.",
      "Dick Schofield appeared in 21 games for California during the 1983 season.",
      "Dick Schofield collected 11 hits in 54 at-bats.",
      "Schofield recorded two doubles and three home runs during his first major-league trial.",
      "Dick Schofield drove in four runs and scored four times.",
      "Dick Schofield drew six walks in 62 plate appearances.",
      "Schofield's three home runs accounted for more than half of his total bases during his brief trial.",
      "Dick Schofield is one of the least experienced players on California's roster.",
      "His family background gives him access to a lifetime of major-league instruction.",
      "Dick Schofield enters 1984 attempting to establish himself as the Angels' regular shortstop.",
    ],
  },
  "Rob Wilfong": {
    lines: [
      "Rob Wilfong's full name is Robert Donald Wilfong.",
      "Rob Wilfong is a left-handed hitter who throws right-handed.",
      "Rob Wilfong began his major-league career with the Minnesota Twins.",
      "Rob Wilfong made his major-league debut during the 1977 season.",
      "Wilfong developed into Minnesota's regular second baseman.",
      "Rob Wilfong enjoyed his strongest offensive season with the Twins in 1979.",
      "Rob Wilfong batted .313 during the 1979 season.",
      "Wilfong also displayed occasional power and speed from the second-base position.",
      "California acquired Rob Wilfong from Minnesota during the 1982 season.",
      "Wilfong joined the Angels in the same transaction as relief pitcher Doug Corbett.",
      "Rob Wilfong gives California an experienced alternative to Bobby Grich at second base.",
      "Rob Wilfong appeared in 65 games during the 1983 season.",
      "Rob Wilfong batted .254 with 45 hits in 1983.",
      "Wilfong recorded seven doubles, one triple and two home runs.",
      "Rob Wilfong drove in 17 runs and scored 17 times during the 1983 season.",
      "Rob Wilfong struck out only 25 times in 177 at-bats.",
      "Wilfong can start against selected right-handed pitchers or enter for defense.",
      "His experience as a regular makes him more valuable than a typical reserve infielder.",
    ],
  },
  "Juan Beniquez": {
    lines: [
      "Juan Beniquez's full name is Juan Jose Beniquez.",
      "Juan Beniquez was born in San Sebastian, Puerto Rico.",
      "Juan Beniquez began his professional career as an infielder.",
      "Beniquez reached the major leagues with the Boston Red Sox during the 1971 season.",
      "Juan Beniquez appeared at shortstop early in his major-league career.",
      "Boston later converted Beniquez primarily into an outfielder.",
      "Juan Beniquez played alongside Fred Lynn, Rick Burleson and several other future Angels in Boston.",
      "Beniquez was traded from Boston to Texas before the 1976 season.",
      "Juan Beniquez won an American League Gold Glove as a Texas outfielder in 1977.",
      "Juan Beniquez later played for the Yankees and Mariners.",
      "Beniquez joined California as a free agent before the 1981 season.",
      "Juan Beniquez can handle all three outfield positions.",
      "Juan Beniquez appeared in 92 games during the 1983 season.",
      "Juan Beniquez batted .305 with 96 hits in 1983.",
      "Beniquez recorded 15 doubles and three home runs.",
      "Juan Beniquez drove in 34 runs and scored 44 times during the 1983 season.",
      "Juan Beniquez stole 15 bases while being caught only four times.",
      "Beniquez recorded a .343 on-base percentage in 1983.",
      "Juan Beniquez can serve as a pinch-hitter, pinch-runner or defensive replacement.",
      "His ability to hit above .300 while filling several roles gives California exceptional outfield depth.",
    ],
  },
  "Daryl Sconiers": {
    lines: [
      "Daryl Sconiers' full name is Daryl Anthony Sconiers.",
      "Daryl Sconiers is a left-handed hitter and first baseman.",
      "Daryl Sconiers developed entirely within the California organization.",
      "Daryl Sconiers made his major-league debut during the 1981 season.",
      "Sconiers received only limited major-league playing time during his first two seasons.",
      "Daryl Sconiers received a much larger opportunity during the 1983 season.",
      "Daryl Sconiers appeared in 106 games in 1983.",
      "Daryl Sconiers batted .274 with 86 hits.",
      "Sconiers collected 19 doubles and three triples during the 1983 season.",
      "Daryl Sconiers hit eight home runs and drove in 46 runs.",
      "Daryl Sconiers scored 49 times in 1983.",
      "Sconiers slugged .430 during his first extended major-league opportunity.",
      "Daryl Sconiers can replace Rod Carew at first base.",
      "Sconiers can also serve as the designated hitter against right-handed pitching.",
      "His left-handed power gives California another option beyond Carew, Lynn and Jackson.",
      "Daryl Sconiers is still only 25 years old entering the 1984 season.",
      "Sconiers enters the season attempting to build upon his first productive major-league campaign.",
    ],
  },
  "Rick Burleson": {
    lines: [
      "Rick Burleson's full name is Richard Paul Burleson.",
      "Rick Burleson is commonly known by the nickname \"Rooster.\"",
      "Rick Burleson was born in Lynwood, California.",
      "Boston selected Rick Burleson in the first round of the 1970 amateur draft.",
      "Rick Burleson reached the major leagues with the Red Sox during the 1974 season.",
      "Burleson quickly became Boston's regular shortstop.",
      "Rick Burleson played with Fred Lynn, Juan Beniquez and several other future Angels in Boston.",
      "Rick Burleson earned a reputation as an intense and vocal field leader.",
      "Rick Burleson was selected to four American League All-Star teams through 1981.",
      "Rick Burleson won an American League Gold Glove at shortstop in 1979.",
      "Burleson was particularly respected for his range, throwing accuracy and ability to turn double plays.",
      "California acquired Rick Burleson from Boston before the 1981 season.",
      "The trade sent Carney Lansford, Rick Miller and Mark Clear to Boston.",
      "Rick Burleson batted .294 during his first season with the Angels.",
      "Burleson was selected to the 1981 All-Star team.",
      "Rick Burleson received a Silver Slugger Award in 1981.",
      "Serious arm and shoulder problems greatly reduced his playing time beginning in 1982.",
      "Rick Burleson appeared in only 33 games during the 1983 season.",
      "Burleson batted .286 with seven doubles and 11 RBI.",
      "Rick Burleson scored 22 runs and drew 12 walks in 1983.",
      "Burleson recorded a .348 on-base percentage in his limited playing time.",
      "Rick Burleson's placement on the bench reflects his physical condition rather than his former level of ability.",
      "A healthy Burleson gives California an experienced shortstop and clubhouse leader behind Dick Schofield.",
    ],
  },
  "Derrel Thomas": {
    lines: [
      "Derrel Thomas' full name is Derrel Osborn Thomas.",
      "Derrel Thomas was born in Los Angeles, California.",
      "Derrel Thomas is a switch-hitter who throws right-handed.",
      "Derrel Thomas began his major-league career with the San Diego Padres.",
      "Thomas made his major-league debut during the 1971 season.",
      "Derrel Thomas has played for San Diego, San Francisco, Los Angeles, Montreal and Philadelphia before joining California.",
      "Derrel Thomas has appeared at every non-battery defensive position.",
      "Thomas can play second base, shortstop, third base and all three outfield positions.",
      "Derrel Thomas' versatility has allowed teams to carry fewer specialized reserves.",
      "Derrel Thomas enjoyed one of his strongest seasons with San Francisco in 1978.",
      "Thomas later became an important utility player for the Los Angeles Dodgers.",
      "Derrel Thomas helped the Dodgers win the 1981 World Series.",
      "Thomas can switch-hit, pinch-run and enter almost anywhere defensively.",
      "Derrel Thomas spent the 1983 season with the Dodgers.",
      "Thomas was used in the outfield, in the infield and as a pinch-hitter.",
      "Derrel Thomas has more than 1,000 major-league hits entering 1984.",
      "Thomas' speed and experience make him useful during late-inning substitutions.",
      "Derrel Thomas allows the Angels to replace an injured player without rearranging the entire defensive alignment.",
      "Few reserves in baseball can legitimately cover as many positions as Derrel Thomas.",
    ],
  },
  "Mike Witt": {
    lines: [
      "Mike Witt's full name is Michael Atwater Witt.",
      "Mike Witt was born in Fullerton, California.",
      "Mike Witt attended Servite High School in Anaheim.",
      "Mike Witt stands approximately 6-foot-7.",
      "California selected Mike Witt during the 1978 amateur draft.",
      "Witt developed within the Angels' minor-league system.",
      "Mike Witt made his major-league debut on April 11, 1981.",
      "Mike Witt was only 20 years old when he reached the major leagues.",
      "Mike Witt began his career as both a starter and reliever.",
      "His height allows him to deliver the baseball from a steep downward angle.",
      "Mike Witt's curveball is regarded as his best breaking pitch.",
      "Witt has also shown the stamina needed to work deep into games.",
      "Mike Witt appeared in 43 games during the 1983 season.",
      "Mike Witt made 19 starts and 15 relief finishes.",
      "Witt went 7-14 with a 4.91 ERA in 1983.",
      "Mike Witt worked 154 innings during the 1983 season.",
      "Mike Witt struck out 77 hitters.",
      "Witt completed two games during the 1983 season.",
      "Mike Witt also recorded five saves while shifting between the rotation and bullpen.",
      "Mike Witt allowed 14 home runs in 154 innings.",
      "Control remains an important area of development after Witt walked 75 hitters in 1983.",
      "Mike Witt is only 23 years old entering the 1984 season.",
      "California is giving Witt the opportunity to establish himself permanently in the starting rotation.",
    ],
  },
  "Ron Romanick": {
    lines: [
      "Ron Romanick's full name is Ronald James Romanick.",
      "Ron Romanick was born in Burley, Idaho.",
      "Ron Romanick attended Newport High School in Bellevue, Washington.",
      "Ron Romanick played college baseball at Arizona State University.",
      "Toronto selected Romanick in the third round of the 1979 amateur draft, but he did not sign.",
      "San Diego selected Romanick during the first round of a 1980 secondary draft, but he again remained in school.",
      "California selected Ron Romanick with the fourth pick of the January 1981 secondary draft.",
      "Ron Romanick is a 6-foot-4 right-handed pitcher.",
      "Romanick began his professional career with Class-A Redwood in 1981.",
      "Ron Romanick went 15-10 with a 2.91 ERA during his first professional season.",
      "Romanick threw 207 innings and completed 11 games in 1981.",
      "Ron Romanick recorded three shutouts and 178 strikeouts.",
      "Romanick advanced to Double-A Holyoke during the 1982 season.",
      "Ron Romanick went 6-3 with a 4.26 ERA in 16 starts for Holyoke.",
      "Romanick pitched for Double-A Nashua during the 1983 season.",
      "Ron Romanick made 27 starts and threw 174 innings in 1983.",
      "Romanick went 9-12 with a 4.86 ERA.",
      "Ron Romanick completed 10 games and recorded two shutouts.",
      "Romanick struck out 112 hitters during the 1983 season.",
      "Ron Romanick has not yet appeared in a major-league game entering 1984.",
      "He is the only member of this California rotation without major-league experience.",
      "Romanick enters 1984 attempting to move directly from Double-A into the Angels' rotation.",
    ],
  },
  "Geoff Zahn": {
    lines: [
      "Geoff Zahn's full name is Geoffrey Clayton Zahn.",
      "Geoff Zahn is a veteran left-handed pitcher.",
      "Geoff Zahn began his professional career in the Los Angeles Dodgers organization.",
      "Zahn reached the major leagues with the Dodgers during the 1973 season.",
      "Geoff Zahn also pitched for the Chicago Cubs before joining Minnesota.",
      "Zahn became a regular member of the Twins' starting rotation.",
      "Geoff Zahn developed a reputation as a durable pitcher who relied on control and movement.",
      "Zahn generally attempts to induce ground balls rather than overpower hitters.",
      "Geoff Zahn signed with California before the 1981 season.",
      "Zahn won 10 games and completed nine during his first season with the Angels.",
      "Geoff Zahn enjoyed an excellent 1982 season.",
      "Zahn went 18-8 during California's division-championship season.",
      "Geoff Zahn's 18 victories established a career high.",
      "Zahn remained one of California's most reliable pitchers during the 1983 season.",
      "Geoff Zahn went 9-11 with a 3.33 ERA in 1983.",
      "Zahn's 3.33 ERA was the best among California's regular starting pitchers.",
      "Geoff Zahn threw 203 innings during the 1983 season.",
      "Zahn completed 11 games.",
      "Geoff Zahn recorded three shutouts in 1983.",
      "Zahn struck out 81 hitters while walking only 51.",
      "Geoff Zahn allowed 22 home runs but generally limited walks and extended rallies.",
      "Zahn's left-handed delivery gives the rotation a contrast to Witt and Romanick.",
      "Geoff Zahn remains capable of finishing games when his control and sinker are working properly.",
    ],
  },
  "Tommy John": {
    lines: [
      "Tommy John's full name is Thomas Edward John.",
      "Tommy John was born in Terre Haute, Indiana.",
      "Tommy John was an outstanding high-school basketball player.",
      "John received interest from major college basketball programs, including Kentucky.",
      "Cleveland signed Tommy John directly out of high school in 1961.",
      "Tommy John made his major-league debut with Cleveland during the 1963 season.",
      "John later became a dependable starting pitcher for the Chicago White Sox.",
      "Tommy John joined the Los Angeles Dodgers before the 1972 season.",
      "John suffered a severe injury to the ligament in his pitching elbow during the 1974 season.",
      "Dr. Frank Jobe performed an experimental operation in which a tendon was used to reconstruct the damaged elbow ligament.",
      "Tommy John missed the entire 1975 season while recovering.",
      "At the time, there was no guarantee that he would ever pitch in the major leagues again.",
      "Tommy John returned to the Dodgers' rotation in 1976.",
      "John won 20 games during the 1977 season.",
      "Tommy John later signed with the New York Yankees.",
      "John won 21 games in 1979 and 22 in 1980.",
      "Tommy John became one of the first pitchers to demonstrate that a player could return successfully from major elbow reconstruction.",
      "John joined the Angels during the 1982 season.",
      "Tommy John helped California win the 1982 American League West.",
      "Tommy John made 34 starts during the 1983 season.",
      "John went 11-13 with a 4.33 ERA.",
      "Tommy John threw 234 and two-thirds innings in 1983.",
      "John completed nine games.",
      "Tommy John walked only 49 hitters during the 1983 season.",
      "John relies upon a sinking fastball, control and the ability to change speeds.",
      "Tommy John generally attempts to make hitters drive the ball into the ground.",
      "Tommy John enters 1984 at age 40 with more than 20 years of professional experience.",
      "No pitcher on California's staff has overcome more serious physical adversity than Tommy John.",
    ],
  },
  "Luis Sanchez": {
    lines: [
      "Luis Sanchez's full name is Luis Mercedes Escoba Sanchez.",
      "Luis Sanchez is a right-handed pitcher from Venezuela.",
      "Sanchez spent several years pitching professionally before reaching the major leagues.",
      "Luis Sanchez made his major-league debut with California during the 1981 season.",
      "Sanchez was already 27 years old when he first appeared in the majors.",
      "Luis Sanchez has been used primarily as a relief pitcher.",
      "Sanchez is capable of working more than one inning in a close game.",
      "Luis Sanchez recorded his first major-league saves during the 1981 season.",
      "Sanchez became increasingly important to the California bullpen in 1982.",
      "Luis Sanchez appeared in 56 games during the 1983 season.",
      "Sanchez went 10-8 with a 3.66 ERA.",
      "Luis Sanchez's 10 victories were unusually high for a relief pitcher.",
      "Sanchez recorded seven saves during the 1983 season.",
      "Luis Sanchez worked 98 and two-thirds innings despite making only one start.",
      "Sanchez allowed 92 hits in those innings.",
      "Luis Sanchez struck out 49 hitters and walked 40.",
      "Sanchez finished 34 games during the 1983 season.",
      "Luis Sanchez can enter before the ninth inning and remain through the end of a game.",
      "His ability to work extended relief makes him more than a one-inning closer.",
      "California enters 1984 with Sanchez as the primary option to protect a late lead.",
    ],
  },
  "Don Aase": {
    lines: [
      "Don Aase's full name is Donald William Aase.",
      "Don Aase is a right-handed pitcher.",
      "Boston selected Don Aase during the 1972 amateur draft.",
      "Don Aase made his major-league debut with the Red Sox during the 1977 season.",
      "Aase began his major-league career as a starting pitcher.",
      "Don Aase pitched well enough as a rookie to earn a regular place in Boston's rotation.",
      "California acquired Don Aase from Boston following the 1977 season.",
      "The Red Sox received second baseman Jerry Remy in the transaction.",
      "Don Aase continued to work primarily as a starter during his early California seasons.",
      "Aase later shifted into the bullpen.",
      "Don Aase's fastball made him suitable for important late-inning assignments.",
      "Aase could also pitch several innings because of his starting background.",
      "Don Aase appeared in 39 games during the 1981 season.",
      "Aase recorded 11 saves during that strike-shortened campaign.",
      "Don Aase helped California win the American League West in 1979 and 1982.",
      "Arm trouble prevented Don Aase from pitching during the entire 1983 season.",
      "Aase enters 1984 attempting to return after a full year without a major-league appearance.",
      "His effectiveness will depend upon the strength and durability of his recovering arm.",
      "A healthy Don Aase gives California another experienced late-inning right-hander.",
      "Aase can be used either to set up Luis Sanchez or to finish a game himself.",
    ],
  },
  "Doug Corbett": {
    lines: [
      "Doug Corbett's full name is Douglas Mitchell Corbett.",
      "Doug Corbett is a right-handed relief pitcher.",
      "Corbett spent several seasons in the minor leagues before receiving a major-league opportunity.",
      "Doug Corbett was 27 years old when he debuted with Minnesota in 1980.",
      "Corbett immediately became one of the American League's most effective relief pitchers.",
      "Doug Corbett went 8-6 with a 1.98 ERA during his rookie season.",
      "Corbett recorded 23 saves in 1980.",
      "Doug Corbett finished third in the 1980 American League Rookie of the Year voting.",
      "Corbett's unusual delivery and sharp breaking pitches made him difficult for hitters to follow.",
      "Doug Corbett continued as Minnesota's primary late-inning reliever during the 1981 season.",
      "California acquired Doug Corbett and Rob Wilfong from Minnesota during the 1982 season.",
      "Corbett gave the Angels an experienced relief ace during their division-championship season.",
      "Doug Corbett's workload declined during the 1983 season.",
      "Corbett appeared in 11 major-league games for California in 1983.",
      "Doug Corbett went 1-1 with a 3.63 ERA.",
      "Corbett worked 17 and a third innings.",
      "Doug Corbett struck out 18 hitters in those innings.",
      "Corbett allowed 26 hits but only one home run.",
      "Doug Corbett enters 1984 trying to regain the form that made him a dominant Minnesota reliever.",
      "His previous closing experience allows him to work in any late-inning role.",
    ],
  },
  "Bruce Kison": {
    lines: [
      "Bruce Kison's full name is Bruce Eugene Kison.",
      "Bruce Kison is commonly known by the nickname \"The Assassin.\"",
      "The nickname reflects Kison's reputation for pitching aggressively inside.",
      "Pittsburgh selected Bruce Kison during the 1968 amateur draft.",
      "Bruce Kison made his major-league debut during the 1971 season.",
      "Kison reached the majors in time to contribute to Pittsburgh's championship run.",
      "Bruce Kison delivered 6 and a third scoreless relief innings in Game Four of the 1971 World Series.",
      "The rookie earned the victory as Pittsburgh defeated Baltimore.",
      "Bruce Kison remained with the Pirates for most of the 1970s.",
      "Kison worked as both a starter and reliever.",
      "Bruce Kison helped Pittsburgh win another World Series championship in 1979.",
      "Kison signed with California before the 1980 season.",
      "Bruce Kison helped the Angels win the American League West in 1982.",
      "Kison was effective as both a starter and occasional reliever during that season.",
      "Bruce Kison appeared in 26 games during the 1983 season.",
      "Kison went 11-5 with a 4.05 ERA.",
      "His .688 winning percentage was the best among California pitchers with at least 10 decisions.",
      "Bruce Kison threw 126 and two-thirds innings in 1983.",
      "Kison struck out 83 hitters.",
      "Bruce Kison's 83 strikeouts led the Angels' pitching staff.",
      "Kison's willingness to pitch inside can make hitters uncomfortable near the plate.",
      "His experience in both roles makes him useful as a long reliever or emergency starter.",
      "Bruce Kison enters 1984 with two World Series championship rings and more than a decade of major-league experience.",
    ],
  },
  "Curt Kaufman": {
    lines: [
      "Curt Kaufman's full name is Curt Gerrard Kaufman.",
      "Curt Kaufman is a right-handed pitcher.",
      "Kaufman developed in the New York Yankees organization.",
      "Curt Kaufman worked primarily as a relief pitcher in the minor leagues.",
      "Kaufman pitched for Triple-A Columbus during the 1982 season.",
      "Curt Kaufman went 6-3 with a 3.46 ERA for Columbus in 1982.",
      "Kaufman recorded 10 saves and struck out 103 hitters in 91 innings.",
      "Curt Kaufman made his major-league debut with the Yankees on September 10, 1982.",
      "Kaufman appeared in seven games during his first major-league trial.",
      "Curt Kaufman returned to Columbus for most of the 1983 season.",
      "Kaufman went 6-3 with a 2.75 ERA in 50 Triple-A appearances.",
      "Curt Kaufman recorded 25 saves during the 1983 minor-league season.",
      "His 25 saves led the International League.",
      "Kaufman struck out 93 hitters in only 78 and two-thirds innings.",
      "Curt Kaufman allowed only 60 hits during the Triple-A season.",
      "Kaufman also made four appearances for the Yankees in 1983.",
      "Curt Kaufman posted a 3.12 ERA in 8 and two-thirds major-league innings.",
      "Kaufman struck out eight hitters during that brief opportunity.",
      "Curt Kaufman enters 1984 with only 11 previous major-league appearances.",
      "His minor-league strikeout and save totals suggest that he is most comfortable in relief.",
      "Kaufman gives California another hard-throwing right-handed option in the bullpen.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive — base hit.\"",
    "\"Long drive to left field — way back — gone. Home run!\"",
    "\"Ground ball to short — over to first — in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub has talent up and down the lineup — the Angels can hit with anybody.\"",
    "\"California baseball is alive and well — the fans here in Anaheim love their Angels.\"",
    "\"This team has power, speed and defense — the Angels are built to win.\"",
    "\"The Angels won the West just two years ago — they know what it takes.\"",
    "\"Rod Carew, Reggie Jackson, Fred Lynn — that's a Hall of Fame lineup right there.\"",
    "\"There's talent everywhere you look in this lineup — the Angels can hurt you in so many ways.\"",
    "\"This club plays hard for nine innings — that's the Angels way.\"",
    "\"California has one of the most dangerous lineups in the American League.\"",
    "\"The fans in Anaheim have been waiting for a winner — and this team is getting closer.\"",
    "\"There's a buzz around the Angels this year — people can feel something building.\"",
    "\"This is a team with championship pedigree — they've been to the postseason twice in the last four years.\"",
    "\"Anaheim baseball — there's nothing quite like a night at the Big A.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Rod Carew is one of the greatest pure hitters baseball has ever seen — seven batting titles.\"",
    "\"Reggie Jackson is Mr. October — five World Series rings — he's a legend.\"",
    "\"Fred Lynn can change a game with one swing — and he's one of the best center fielders I've ever seen.\"",
    "\"Bobby Grich might be the most underrated player in baseball — power, defense, plate discipline.\"",
    "\"Doug DeCinces is a proven run producer — he was tremendous in '82.\"",
    "\"Bob Boone is a Gold Glove catcher — he handles this staff as well as anybody.\"",
    "\"Brian Downing is one of the strongest men in baseball — and he gets on base.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Anaheim Stadium.\"",
    "\"The lights are on at the Big A — Angels baseball tonight.\"",
    "Anaheim Stadium — home of the Angels since 1966.",
    "\"The warm Southern California air is perfect for baseball tonight.\"",
    "\"The artificial turf plays fast tonight — ground balls will scoot through the infield.\"",
    "\"The stands are filling up nicely — the fans in Anaheim are excited about this club.\"",
    "\"You can see the Santa Ana Mountains beyond the outfield — a beautiful backdrop on a clear night.\"",
    "\"The Big A has been home to some great moments — the Angels won the West right here in '79 and '82.\"",
    "\"There's a festive atmosphere at the ballpark tonight — Southern California loves its baseball.\"",
    "\"The breeze off the Pacific keeps things comfortable on a warm evening.\"",
    "\"The faithful at the Big A are some of the most passionate fans in baseball.\"",
    "\"A crisp evening in Orange County — there's nothing better than baseball at Anaheim Stadium.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here in Anaheim is into this ballgame.\"",
    "\"Angels fans are making some noise tonight at the Big A.\"",
    "\"The fans in California have waited a long time for a winner — they're fired up tonight.\"",
    "\"Anaheim Stadium is rocking tonight.\"",
    "\"California fans are among the most loyal in baseball — they show up every night.\"",
    "\"The crowd is on its feet — they can feel something building here.\"",
    "\"A great turnout at the Big A tonight.\"",
    "\"These fans can see the talent on this club — they're excited about the season.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Anaheim Stadium, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball on a Southern California evening.\"",
    "\"From all of us here in Anaheim, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story — that's the beauty of this sport.\"",
    "\"Baseball in Anaheim — it's a tradition that runs deep in Orange County.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone — into the seats at the Big A!\"",
    "\"Oh, my goodness — what a ballgame!\"",
    "\"The Angels are making their move here at Anaheim Stadium.\"",
    "\"That one is long gone — souvenir for a fan in the bleachers.\"",
    "\"You won't see many better than that one.\"",
    "\"And the crowd goes crazy — what a finish!\"",
  ]},
};