// Arcade & Video Game interactive popups for the 1984 game experience
// 25 entries matching the arcade/videogame banner ads in broadcastAds.js (#651-675)

const ENTRIES = [
  {
    id: 'marble_madness',
    type: 'arcade',
    game: 'Marble Madness',
    icon: '🔴',
    publisher: 'Atari Games',
    year: '1984',
    matchText: 'Challenge your friends to a game of Marble Madness.',
    tagline: 'Easy to learn. Nearly impossible to master.',
    description: 'Can you guide your marble through twisting ramps, narrow pathways, deadly obstacles, and impossible jumps before time runs out?',
    features: ['Isometric 3D Perspective', 'Trackball Controls', 'Time-based Gameplay', 'Multiple Levels'],
    funFact: 'Marble Madness was one of the first arcade games to use a true isometric 3D perspective.',
    highScore: '47,830 at Al\'s Arcade',
    quote: 'Easy to learn. Nearly impossible to master.',
  },
  {
    id: 'new_arcades',
    type: 'bulletin',
    game: 'New Arcade Machines Arriving Weekly!',
    icon: '🎮',
    publisher: 'Industry',
    year: '1984',
    matchText: 'New arcade machines are arriving weekly at locations nationwide.',
    tagline: 'America\'s arcades have never been busier.',
    description: 'Recent arrivals include Marble Madness, Spy Hunter, Punch-Out!!, Dragon\'s Lair, Track & Field, and Pole Position II.',
    features: ['Marble Madness', 'Spy Hunter', 'Punch-Out!!', 'Dragon\'s Lair', 'Track & Field', 'Pole Position II'],
    funFact: 'The arcade industry is expected to generate over $5 billion this year. Most machines cost 25 cents per play.',
    quote: 'The next great game may already be waiting.',
  },
  {
    id: 'xevious',
    type: 'arcade',
    game: 'Xevious',
    icon: '✈️',
    publisher: 'Namco',
    year: '1983',
    matchText: 'Test your skills in Xevious.',
    tagline: 'One quarter. One ship. One chance.',
    description: 'The alien forces of Xevious are attacking. Pilot the Solvalou fighter, destroy enemy aircraft, and bomb hidden ground installations as you battle wave after wave of attackers.',
    features: ['Scrolling Shooter', 'Two-Layer Combat', 'Wave-Based Gameplay', 'High Score Tracking'],
    funFact: 'Xevious became one of Japan\'s biggest arcade hits and helped define the scrolling shooter genre.',
    quote: 'One quarter. One ship. One chance.',
  },
  {
    id: 'dig_dug',
    type: 'arcade',
    game: 'Dig Dug',
    icon: '🕳️',
    publisher: 'Namco',
    year: '1982',
    matchText: 'Can you survive a game of Dig Dug?',
    tagline: 'If you stop digging, you\'re probably dead.',
    description: 'The underground challenge continues. Inflate enemies until they burst or crush them with falling rocks as you tunnel through an ever-changing maze.',
    features: ['Maze Gameplay', 'Enemy Types: Pooka & Fygar', 'Rock Crushing', 'Power-ups'],
    funFact: 'Fygar can breathe fire. World record scores continue to rise nationwide.',
    quote: 'If you stop digging, you\'re probably dead.',
  },
  {
    id: 'track_field',
    type: 'arcade',
    game: 'Track & Field',
    icon: '🏃',
    publisher: 'Konami',
    year: '1983',
    matchText: 'The action never stops in Track & Field.',
    tagline: 'Speed. Strength. Endurance.',
    description: 'Can you break the world record? Compete in 100 Meter Dash, Long Jump, Javelin, Hurdles, and Hammer Throw.',
    features: ['5 Olympic Events', 'Rapid Button Mashing', 'World Records', 'Progressive Difficulty'],
    funFact: 'Players routinely pounded buttons so hard that arcade operators had to replace them weekly.',
    quote: 'Speed. Strength. Endurance.',
  },
  {
    id: 'moon_patrol',
    type: 'arcade',
    game: 'Moon Patrol',
    icon: '🌙',
    publisher: 'Irem',
    year: '1982',
    matchText: 'Try your hand at Moon Patrol.',
    tagline: 'The moon is not safe.',
    description: 'Jump craters. Destroy alien attackers. Survive the moon. Can you patrol the lunar surface?',
    features: ['Parallax Scrolling', 'Obstacle Jumping', 'Alien Combat', 'Lunar Hazards'],
    funFact: 'Moon Patrol was among the first arcade games to feature parallax scrolling backgrounds.',
    quote: 'The moon is not safe.',
  },
  {
    id: 'rally_x',
    type: 'arcade',
    game: 'Rally-X',
    icon: '🏎️',
    publisher: 'Namco',
    year: '1980',
    matchText: 'Rally-X continues to challenge players.',
    tagline: 'Drive fast. Think faster.',
    description: 'Collect all the flags before fuel runs out. Avoid enemy cars. Use smoke screens wisely.',
    features: ['Large Scrolling Map', 'Flag Collection', 'Fuel Management', 'Enemy Avoidance'],
    funFact: 'Rally-X was one of the first games to feature a scrolling map larger than a single screen.',
    quote: 'Drive fast. Think faster.',
  },
  {
    id: 'pole_position',
    type: 'arcade',
    game: 'Pole Position',
    icon: '🏁',
    publisher: 'Namco',
    year: '1982',
    matchText: 'The race is on in Pole Position.',
    tagline: 'Prepare to qualify.',
    description: 'The checkered flag awaits. Qualify for the race, then battle for victory at over 180 miles per hour.',
    features: ['Racing Simulation', 'Qualification Round', 'Multiple Tracks', 'Pedal & Wheel Controls'],
    funFact: 'Pole Position became one of the highest-grossing arcade racing games ever made.',
    quote: 'Prepare to qualify.',
  },
  {
    id: 'donkey_kong',
    type: 'arcade',
    game: 'Donkey Kong',
    icon: '🦍',
    publisher: 'Nintendo',
    year: '1981',
    matchText: 'Donkey Kong challenges await at your local arcade.',
    tagline: 'It all started here.',
    description: 'Jump. Climb. Survive. Mario faces his greatest challenge yet as he attempts to rescue Pauline from the giant ape Donkey Kong.',
    features: ['Platforming', 'Jumping Obstacles', 'Climbing Sequences', 'Boss Battle'],
    funFact: 'This was the first appearance of Mario, the most iconic video game character ever.',
    quote: 'It all started here.',
  },
  {
    id: 'pac_man',
    type: 'arcade',
    game: 'Pac-Man',
    icon: '👾',
    publisher: 'Namco',
    year: '1980',
    matchText: 'Join the Pac-Man revolution.',
    tagline: 'Waka waka waka.',
    description: 'Over 300,000 Pac-Man machines have been sold worldwide. Guide Pac-Man through the maze while avoiding Blinky, Pinky, Inky, and Clyde.',
    features: ['Maze Chase', 'Ghost AI', 'Power Pellets', 'Escalating Difficulty'],
    funFact: 'Pac-Man remains the most recognizable video game character in the world.',
    quote: 'Waka waka waka.',
  },
  {
    id: 'galaga',
    type: 'arcade',
    game: 'Galaga',
    icon: '🛸',
    publisher: 'Namco',
    year: '1981',
    matchText: 'Galaga is taking over arcades everywhere.',
    tagline: 'One of the greatest shooters ever made.',
    description: 'Alien forces attack in massive formations. Destroy them before they capture your fighter.',
    features: ['Formation Shooting', 'Capture Mechanic', 'Double-Fighter Power-up', 'Wave Progression'],
    funFact: 'Skilled players intentionally allowed their ships to be captured to create double-fighter formations.',
    quote: 'One of the greatest shooters ever made.',
  },
  {
    id: 'defender',
    type: 'arcade',
    game: 'Defender',
    icon: '🎯',
    publisher: 'Williams',
    year: '1980',
    matchText: 'Defender will test your reflexes.',
    tagline: 'Most players never survive long enough to understand everything.',
    description: 'Defender remains one of the most difficult arcade games ever created. Protect astronauts. Destroy alien invaders. Master one of gaming\'s steepest learning curves.',
    features: ['Rapid Action', 'Astronaut Protection', 'Alien Waves', 'Complex Controls'],
    funFact: 'Defender is famously difficult—most players never master its complex control scheme.',
    quote: 'Not for beginners.',
  },
  {
    id: 'asteroids',
    type: 'arcade',
    game: 'Asteroids',
    icon: '💫',
    publisher: 'Atari',
    year: '1979',
    matchText: 'Asteroids continues to attract players.',
    tagline: 'The rocks never stop coming.',
    description: 'Rotate. Fire. Survive. The simple formula that changed arcades forever continues to attract crowds.',
    features: ['Vector Graphics', 'Asteroid Breaking', 'Flying Saucer Enemies', 'Endless Waves'],
    funFact: 'Asteroids became Atari\'s best-selling arcade game and a classic of the arcade age.',
    quote: 'The rocks never stop coming.',
  },
  {
    id: 'atari_2600',
    type: 'home',
    game: 'Atari 2600',
    icon: '📦',
    publisher: 'Atari',
    year: '1977',
    matchText: 'The Atari 2600 home console brings arcade action to your living room.',
    tagline: 'The arcade in your living room.',
    description: 'The Atari 2600 remains America\'s best-selling home video game system. Popular games include Pac-Man, Pitfall!, Frogger, Missile Command, and Space Invaders.',
    features: ['Cartridge-Based', 'Joystick Controller', 'Arcade Ports', 'Expandable Library'],
    funFact: 'The Atari 2600 revolutionized home gaming and remains beloved by millions of players.',
    price: '$99-$129',
    quote: 'The arcade in your living room.',
  },
  {
    id: 'intellivision',
    type: 'home',
    game: 'Intellivision',
    icon: '🎮',
    publisher: 'Mattel Electronics',
    year: '1979',
    matchText: 'Intellivision offers advanced graphics and gameplay.',
    tagline: 'The thinking person\'s video game system.',
    description: 'Intellivision offers realistic sports, strategy games, and advanced graphics. Popular titles include Major League Baseball, NFL Football, and Utopia.',
    features: ['Advanced Graphics', 'Sports Games', 'Strategic Gameplay', 'Keypad Controller'],
    funFact: 'Many sports fans consider Intellivision baseball the best home baseball game available.',
    price: 'Around $199',
    quote: 'Intelligent Television.',
  },
  {
    id: 'colecovision',
    type: 'home',
    game: 'ColecoVision',
    icon: '🕹️',
    publisher: 'Coleco',
    year: '1982',
    matchText: 'Coleco Vision features arcade-quality games at home.',
    tagline: 'The next best thing to the arcade.',
    description: 'ColecoVision delivers some of the closest arcade conversions available. Popular games include Donkey Kong, Zaxxon, and Turbo.',
    features: ['Arcade Accuracy', 'Advanced Cartridges', 'Super Action Controller', 'Packed Games'],
    funFact: 'Donkey Kong was packed with many ColecoVision systems as a launch title.',
    price: 'Around $199',
    quote: 'The next best thing to the arcade.',
  },
  {
    id: 'commodore_64',
    type: 'home',
    game: 'Commodore 64',
    icon: '💾',
    publisher: 'Commodore',
    year: '1982',
    matchText: 'The Commodore 64 is coming soon.',
    tagline: '64K of possibilities.',
    description: 'The Commodore 64 isn\'t just for school and business. Popular games include Summer Games, Impossible Mission, Jumpman, and Wizard of Wor.',
    features: ['64K RAM', 'Graphics Processor', 'Sound Synthesis', 'Massive Game Library'],
    funFact: 'It may become the best-selling computer in history. Already a gaming powerhouse.',
    price: 'Around $199-$250',
    quote: '64K of possibilities.',
  },
  {
    id: 'apple_ii',
    type: 'home',
    game: 'Apple II',
    icon: '🍎',
    publisher: 'Apple Computer',
    year: '1977',
    matchText: 'Apple computers offer educational gaming experiences.',
    tagline: 'Education meets entertainment.',
    description: 'The Apple II remains the king of educational software. Popular programs include Oregon Trail, Lemonade Stand, and Number Munchers.',
    features: ['Educational Focus', 'Color Graphics', 'Disk Drive Support', 'Vast Software Library'],
    funFact: 'Schools nationwide continue adopting Apple computers for both education and gaming.',
    price: 'Around $1,300+',
    quote: 'Education meets entertainment.',
  },
  {
    id: 'game_watch',
    type: 'handheld',
    game: 'Nintendo Game & Watch',
    icon: '⌚',
    publisher: 'Nintendo',
    year: '1980',
    matchText: 'Nintendo\'s Game & Watch handhelds are pocket-sized fun.',
    tagline: 'Video games beyond the arcade.',
    description: 'Nintendo\'s Game & Watch series lets players take games anywhere. Popular models include Donkey Kong, Mario Bros., Fire, and Oil Panic.',
    features: ['Portable', 'LCD Display', 'Battery Powered', 'Pocket-Sized'],
    funFact: 'Game & Watch became one of the best-selling toy lines of all time, with millions sold worldwide.',
    price: 'Around $20-$30',
    quote: 'Video games beyond the arcade.',
  },
  {
    id: 'home_computers',
    type: 'platform',
    game: 'Home Computers Revolutionize Gaming',
    icon: '🖥️',
    publisher: 'Industry',
    year: '1984',
    matchText: 'Home computers are revolutionizing gaming.',
    tagline: 'The next generation of gaming has arrived.',
    description: 'Millions of Americans are discovering computer gaming. Leading systems include Commodore 64, Apple II, Atari 800XL, and TRS-80 Color Computer.',
    features: ['Deeper Stories', 'Better Graphics', 'Endless Possibilities', 'Diverse Platforms'],
    funFact: 'Games now feature deeper stories, better graphics, and endless possibilities beyond arcade ports.',
    quote: 'The next generation of gaming has arrived.',
  },
  {
    id: 'frogger',
    type: 'arcade',
    game: 'Frogger',
    icon: '🐸',
    publisher: 'Konami',
    year: '1981',
    matchText: 'Frogger hops into arcades this summer.',
    tagline: 'Hop to it.',
    description: 'Why did the frog cross the road? To become an arcade legend. Guide Frogger across busy highways and dangerous rivers while avoiding disaster.',
    features: ['River Crossing', 'Traffic Avoidance', 'Time Pressure', 'Multiple Obstacles'],
    funFact: 'Frogger became one of the most recognizable games ever created and inspired countless variations.',
    quote: 'Hop to it.',
  },
  {
    id: 'centipede',
    type: 'arcade',
    game: 'Centipede',
    icon: '🐛',
    publisher: 'Atari',
    year: '1981',
    matchText: 'Centipede brings insects and action to arcades.',
    tagline: 'Shoot fast. Think faster.',
    description: 'Defend yourself against Centipedes, Fleas, Spiders, and Scorpions in this bug-busting arcade classic.',
    features: ['Insect Enemies', 'Rapid Shooting', 'Power-ups', 'Escalating Waves'],
    funFact: 'Centipede attracted more female players than most arcade games, helping broaden the gaming audience.',
    quote: 'Shoot fast. Think faster.',
  },
  {
    id: 'tempest',
    type: 'arcade',
    game: 'Tempest',
    icon: '🌀',
    publisher: 'Atari',
    year: '1981',
    matchText: 'Tempest spirals into arcades.',
    tagline: 'Nothing else looks like Tempest.',
    description: 'Welcome to the Web. Battle enemies crawling through geometric tunnels in one of the most visually unique games ever created.',
    features: ['Vector Graphics', 'Tunnel Shooting', 'Geometric Design', 'Color Vector Display'],
    funFact: 'Tempest became famous for its color vector graphics and revolutionary visual style designed by Dave Theurer.',
    quote: 'Nothing else looks like Tempest.',
  },
  {
    id: 'zaxxon',
    type: 'arcade',
    game: 'Zaxxon',
    icon: '✈️',
    publisher: 'Sega',
    year: '1982',
    matchText: 'Zaxxon introduces isometric graphics.',
    tagline: 'See arcade gaming from a new angle.',
    description: 'Zaxxon introduced isometric graphics to arcades, creating the illusion of true depth. Pilot your spacecraft through heavily defended enemy fortresses.',
    features: ['Isometric Perspective', 'Altitude Judging', 'Fortress Raids', 'Innovative Graphics'],
    funFact: 'Zaxxon revolutionized arcade graphics with isometric perspective, a concept players had to learn to judge altitude.',
    quote: 'See arcade gaming from a new angle.',
  },
  {
    id: 'robotron',
    type: 'arcade',
    game: 'Robotron: 2084',
    icon: '🤖',
    publisher: 'Williams',
    year: '1982',
    matchText: 'Robotron 2084 offers non-stop arcade action.',
    tagline: 'Humanity needs you.',
    description: 'The machines have taken over. You are humanity\'s final hope. Destroy endless robotic enemies while rescuing survivors.',
    features: ['Dual Joystick Controls', 'Massive Action', 'Rescue Mechanics', 'Intensity Overload'],
    funFact: 'Robotron is considered one of the most intense arcade games ever created with nonstop action.',
    quote: 'Humanity needs you.',
  },
];

// Tracking for viewed arcade/videogame ads
const VIEWED_ADS = new Set();

/**
 * Find the arcade entry matching a given ad text.
 * @param {string} adText
 * @returns {object|null}
 */
export function findArcadeEntry(adText) {
  return ENTRIES.find(e => e.matchText === adText) || null;
}

/**
 * Track a view of an arcade/videogame ad. Returns newly unlocked achievement IDs.
 * @param {string} entryId
 * @returns {string[]}
 */
export function trackArcadeView(entryId) {
  VIEWED_ADS.add(entryId);
  const unlocked = [];

  if (VIEWED_ADS.size >= 5) {
    unlocked.push('arcade_enthusiast');
  }
  if (VIEWED_ADS.size >= 15) {
    unlocked.push('high_score_hunter');
  }
  if (VIEWED_ADS.size >= 25) {
    unlocked.push('arcade_master');
  }

  return unlocked;
}

/**
 * Get count of viewed arcade/videogame ads.
 * @returns {number}
 */
export function getArcadeViewCount() {
  return VIEWED_ADS.size;
}