// Houston Astros Broadcast - 1984
// Radio: Gene Elston, Milo Hamilton, Harry Kalas
// Astrodome - home of the Astros since 1965
// All stats cutoff: end of 1983 season

export function pickAstrosLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickAstrosPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Bill Doran": {
    lines: [
      "Bill Doran's full name is William Donald Doran.",
      "Doran was born in Cincinnati, Ohio.",
      "Bill Doran attended Mount Healthy High School in Cincinnati.",
      "Doran played college baseball at Miami University in Oxford, Ohio.",
      "Houston selected Bill Doran in the sixth round of the 1979 amateur draft.",
      "Doran developed as a switch-hitting second baseman in the Astros' farm system.",
      "Bill Doran made his major-league debut on September 6, 1982.",
      "Doran entered 1983 with only a brief amount of major-league experience.",
      "Bill Doran quickly won Houston's regular second-base position.",
      "Doran appeared in 154 games during his first full major-league season.",
      "Bill Doran collected 145 hits in 535 official at-bats.",
      "Doran batted .271.",
      "Bill Doran recorded 12 doubles and seven triples.",
      "Doran hit eight home runs and drove in 39 runs.",
      "Bill Doran scored 70 times.",
      "Doran stole 12 bases in 24 attempts.",
      "Bill Doran drew 86 walks.",
      "Doran posted an excellent .371 on-base percentage.",
      "Bill Doran finished fifth in the 1983 National League Rookie of the Year voting.",
      "His switch-hitting prevents opposing managers from neutralizing him with a simple pitching change.",
      "Doran's patience is especially useful in the leadoff position.",
      "He is willing to work deep counts and force a pitcher to reveal his repertoire early.",
      "Once aboard, Doran has enough speed to distract the pitcher and create openings for Terry Puhl and Jose Cruz.",
      "His quickness and range are valuable on the Astrodome's artificial turf.",
      "Doran enters 1984 as one of Houston's most promising young everyday players.",
    ],
  },
  "Terry Puhl": {
    lines: [
      "Terry Puhl's full name is Terry Stephen Puhl.",
      "Puhl was born in Melville, Saskatchewan, Canada.",
      "Terry Puhl grew up playing baseball in a region better known for hockey.",
      "Houston signed Puhl as an amateur free agent in 1973.",
      "Puhl developed in the Astros' minor-league system as a left-handed-hitting outfielder.",
      "Terry Puhl made his major-league debut during July 1977.",
      "Puhl quickly established himself as one of Houston's regular outfielders.",
      "Terry Puhl was selected to the National League All-Star team in 1978.",
      "Puhl helped the Astros win their first division title in 1980.",
      "Terry Puhl batted .526 during the five-game 1980 National League Championship Series against Philadelphia.",
      "Puhl collected ten hits during that series.",
      "Terry Puhl also helped Houston reach the postseason during the strike-shortened 1981 season.",
      "Puhl appeared in 137 games during 1983.",
      "Terry Puhl collected 136 hits.",
      "Puhl batted .292.",
      "Terry Puhl recorded 25 doubles and seven triples.",
      "Puhl hit eight home runs and drove in 44 runs.",
      "Terry Puhl scored 66 times.",
      "Puhl stole 24 bases.",
      "Terry Puhl possesses a strong and accurate throwing arm.",
      "His speed allows him to cover considerable territory in the Astrodome outfield.",
      "Puhl's left-handed line-drive swing is designed more for gaps than towering home runs.",
      "He can bat near the top of the order, move runners or drive a ball over an outfielder's head.",
      "Puhl and Jose Cruz give Houston two experienced left-handed hitters with both speed and extra-base ability.",
      "Puhl's calm style often disguises how many different ways he can affect a game.",
    ],
  },
  "Jose Cruz": {
    lines: [
      "Jose Cruz's full name is Jose Cruz Dilan.",
      "Cruz was born in Arroyo, Puerto Rico.",
      "Jose Cruz is commonly known by the nickname \"Cheo.\"",
      "Cruz comes from a prominent Puerto Rican baseball family.",
      "His brothers Hector and Tommy also became major-league players.",
      "The St. Louis Cardinals signed Jose Cruz as an amateur free agent.",
      "Cruz made his major-league debut with St. Louis during the 1970 season.",
      "Houston acquired Jose Cruz from the Cardinals before the 1975 season.",
      "Cruz gradually developed into one of the most popular players in Astros history.",
      "Astrodome public-address announcer J. Fred Duckett's extended call of \"Jose Cruuuuuuz\" became a familiar Houston sound.",
      "Cruz helped Houston reach the postseason in both 1980 and 1981.",
      "Jose Cruz was selected to the National League All-Star team in 1980.",
      "Cruz appeared in 156 games during the 1983 season.",
      "Jose Cruz collected 189 hits.",
      "Cruz batted .318.",
      "Jose Cruz recorded 28 doubles and seven triples.",
      "Cruz hit 14 home runs and drove in 92 runs.",
      "Jose Cruz scored 83 times.",
      "Cruz stole 30 bases.",
      "Jose Cruz drew 73 walks and posted a .385 on-base percentage.",
      "Cruz received the 1983 National League Silver Slugger Award.",
      "He finished third in the National League Most Valuable Player voting.",
      "Cruz uses a distinctive high leg kick as part of his left-handed swing.",
      "His speed turns hits into the Astrodome gaps into doubles and triples.",
      "Cruz can hit for average, draw walks, steal bases and drive in runs.",
      "He remains dangerous against left-handed pitching despite batting from the left side.",
      "Cruz's ability to produce without relying on home runs makes him ideally suited for the spacious Astrodome.",
      "He enters 1984 as the most accomplished all-around position player in Houston's lineup.",
    ],
  },
  "Enos Cabell": {
    lines: [
      "Enos Cabell's full name is Enos Milton Cabell.",
      "Cabell was born in Fort Riley, Kansas.",
      "Enos Cabell attended Gardena High School in California.",
      "The Baltimore Orioles signed Cabell as an amateur free agent in 1968.",
      "Cabell made his major-league debut with Baltimore during the 1972 season.",
      "Houston acquired Enos Cabell before the 1975 season.",
      "Cabell became a regular at third base for the Astros.",
      "Enos Cabell is capable of playing first base, third base and the outfield.",
      "Cabell played a fast, aggressive style suited to Houston's artificial turf.",
      "Enos Cabell stole 33 bases during the 1976 season.",
      "Cabell recorded 42 stolen bases in 1977.",
      "Enos Cabell collected 195 hits and stole 37 bases in 1978.",
      "Cabell played for San Francisco during the 1981 season.",
      "Enos Cabell then joined the Detroit Tigers.",
      "Cabell appeared in 121 games for Detroit during 1983.",
      "Enos Cabell collected 122 hits in 392 official at-bats.",
      "Cabell!batted .311.",
      "Enos Cabell recorded 23 doubles and five triples.",
      "Cabell hit five home runs and drove in 46 runs.",
      "Enos Cabell scored 62 times.",
      "Cabell struck out only 41 times.",
      "His return to Houston reunites him with several former Astros teammates.",
      "Cabell's versatility allows him to handle first base without sacrificing speed.",
      "He is an aggressive hitter who prefers attacking a hittable pitch to waiting for a walk.",
      "Cabell's contact ability can keep an inning moving behind Cruz.",
      "His familiarity with the Astrodome should make the transition back to Houston easier.",
    ],
  },
  "Phil Garner": {
    lines: [
      "Phil Garner's full name is Philip Mason Garner.",
      "Garner was born in Jefferson City, Tennessee.",
      "Phil Garner attended Bearden High School in Knoxville.",
      "Garner played college baseball at the University of Tennessee.",
      "Oakland selected Phil Garner with the third overall pick of the 1971 amateur draft.",
      "Garner made his major-league debut with the Athletics during 1973.",
      "Phil Garner became Oakland's regular second baseman.",
      "Garner was selected to the American League All-Star team in 1976.",
      "His stocky build and aggressive play earned him the nickname \"Scrap Iron.\"",
      "Pittsburgh acquired Phil Garner before the 1977 season.",
      "Garner became a key member of the Pirates' infield.",
      "Phil Garner helped Pittsburgh win the 1979 World Series.",
      "Garner batted .500 during the seven-game World Series against Baltimore.",
      "Phil Garner collected 12 hits and drove in five runs during the Series.",
      "Garner was selected to the National League All-Star team in 1980 and 1981.",
      "Houston acquired Phil Garner during the 1981 season.",
      "Garner has experience at second base, third base and shortstop.",
      "Phil Garner appeared in 150 games during 1983.",
      "Garner batted .238 with one home run and 26 RBI.",
      "Phil Garner scored 52 runs and stole 13 bases.",
      "Garner's offensive value extends beyond his batting average.",
      "He can bunt, run, hit behind runners and handle several infield positions.",
      "Garner plays with visible intensity and is not hesitant to challenge an opponent.",
      "His championship experience gives Houston a veteran who has already succeeded in pressure games.",
      "At third base, Garner's quick reactions are particularly important on artificial turf.",
      "\"Scrap Iron\" is the sort of player whose uniform rarely remains clean for nine innings.",
    ],
  },
  "Jerry Mumphrey": {
    lines: [
      "Jerry Mumphrey's full name is Jerry Wayne Mumphrey.",
      "Mumphrey was born in Tyler, Texas.",
      "Jerry Mumphrey attended Chapel Hill High School in Tyler.",
      "The St. Louis Cardinals selected Mumphrey in the fourth round of the 1971 amateur draft.",
      "Mumphrey made his major-league debut with St. Louis during 1974.",
      "Jerry Mumphrey developed into a switch-hitting outfielder.",
      "Mumphrey later played for the San Diego Padres.",
      "Jerry Mumphrey stole 52 bases for San Diego during the 1980 season.",
      "Mumphrey then joined the New York Yankees.",
      "Jerry Mumphrey batted .307 for New York in 1981.",
      "Houston acquired Mumphrey during the 1983 season.",
      "Jerry Mumphrey appeared in 44 games for the Astros.",
      "Mumphrey collected 48 hits in 143 official at-bats.",
      "Jerry Mumphrey batted .336.",
      "Mumphrey recorded ten doubles, two triples and one home run.",
      "Jerry Mumphrey drove in 17 runs and scored 17.",
      "Mumphrey drew 22 walks.",
      "Jerry Mumphrey posted a .425 on-base percentage.",
      "He can bat from either side of the plate.",
      "Mumphrey's experience in center field allows Houston to shift its other outfielders as needed.",
      "His speed remains useful even though he no longer steals bases at his earlier rate.",
      "Mumphrey can bunt for a hit, shoot a ball through an opening or drive it into a gap.",
      "His switch-hitting gives the lower half of the lineup additional flexibility.",
      "Mumphrey's excellent performance after joining Houston gives him a strong case for regular playing time.",
    ],
  },
  "Mark Bailey": {
    lines: [
      "Mark Bailey's full name is John Mark Bailey.",
      "Bailey was born in Springfield, Missouri.",
      "Mark Bailey attended Kickapoo High School in Springfield.",
      "Bailey played college baseball at Southwest Missouri State University.",
      "Houston selected Mark Bailey in the sixth round of the 1982 amateur draft.",
      "Bailey entered professional baseball as a third baseman.",
      "The Astros converted Bailey into a catcher.",
      "His quick progress behind the plate allowed him to advance rapidly through the farm system.",
      "Bailey's nickname is \"Beetle.\"",
      "The nickname refers to the Beetle Bailey comic strip.",
      "Mark Bailey spent the 1983 season developing in Houston's minor-league organization.",
      "Bailey reached Double-A with very limited professional experience.",
      "Mark Bailey had not appeared in a major-league game by the end of 1983.",
      "National League pitchers therefore possess no major-league scouting history against him.",
      "Bailey is a switch-hitter.",
      "His ability to bat from both sides makes him unusual for a catcher.",
      "Mark Bailey's offensive background is stronger than that of many players developed solely as defensive catchers.",
      "He must still learn the tendencies of Houston's veteran pitching staff.",
      "Catching Nolan Ryan requires handling exceptional velocity.",
      "Catching Joe Niekro requires reacting to an unpredictable knuckleball.",
      "Those two pitchers present almost opposite challenges for a young catcher.",
      "Bailey's inclusion in the starting lineup represents a commitment to his long-term potential.",
      "Alan Ashby remains available to provide experienced catching and game-calling from the bench.",
      "Bailey enters 1984 attempting to prove that his rapid minor-league rise was justified.",
    ],
  },
  "Craig Reynolds": {
    lines: [
      "Craig Reynolds' full name is Gordon Craig Reynolds.",
      "Reynolds was born in Houston, Texas.",
      "Craig Reynolds attended Reagan High School in Houston.",
      "The Pittsburgh Pirates selected Reynolds in the first round of the 1971 amateur draft.",
      "Reynolds made his major-league debut with Pittsburgh during 1975.",
      "Craig Reynolds became the Seattle Mariners' regular shortstop during their inaugural 1977 season.",
      "Reynolds was selected to the American League All-Star team in both 1978 and 1979.",
      "Houston acquired Craig Reynolds before the 1979 season.",
      "Reynolds returned to his hometown to play for the Astros.",
      "Craig Reynolds helped Houston reach the postseason in 1980 and 1981.",
      "Reynolds bats left-handed and throws right-handed.",
      "Craig Reynolds has experience at shortstop, second base and in the outfield.",
      "Reynolds appeared in 65 games during the 1983 season.",
      "Craig Reynolds collected 21 hits in 98 official at-bats.",
      "Reynolds batted .214.",
      "Craig Reynolds recorded three doubles and one home run.",
      "Reynolds lost most of the shortstop playing time to Dickie Thon.",
      "His experience nevertheless makes him an excellent late-inning replacement.",
      "Craig Reynolds is a contact hitter rather than a power threat.",
      "Reynolds has enough bat control to bunt or advance a runner.",
      "His left-handed bat can be useful against a difficult right-handed reliever.",
      "Reynolds' familiarity with the Astrodome infield helps him anticipate the speed of ground balls.",
      "Starting Reynolds allows Houston to keep Dickie Thon available as an exceptionally dangerous bench option.",
      "His two All-Star selections demonstrate that he was once regarded among the league's better shortstops.",
    ],
  },
  "Alan Ashby": {
    lines: [
      "Alan Ashby's full name is Alan Dean Ashby.",
      "Ashby was born in Long Beach, California.",
      "Alan Ashby grew up as a Los Angeles Dodgers fan.",
      "Ashby particularly admired left-handed pitcher Sandy Koufax.",
      "Cleveland selected Alan Ashby in the third round of the 1969 amateur draft.",
      "Ashby made his major-league debut with the Indians during 1973.",
      "Alan Ashby later played for the Toronto Blue Jays.",
      "Houston acquired Ashby before the 1979 season.",
      "Ashby is a switch-hitting catcher.",
      "Alan Ashby became Houston's primary receiver.",
      "Ashby caught Ken Forsch's no-hitter on April 7, 1979.",
      "Alan Ashby helped Houston win its first division championship in 1980.",
      "Ashby hit a two-run home run in the 11th inning of Game One of the 1980 National League Championship Series.",
      "The home run gave Houston a victory over Philadelphia.",
      "Alan Ashby caught Nolan Ryan's fifth career no-hitter on September 26, 1981.",
      "Ashby therefore has experience receiving both power pitchers and knuckleball pitchers.",
      "Alan Ashby appeared in 87 games during 1983.",
      "Ashby hit eight home runs and drove in 34 runs.",
      "His offensive production is strongest against right-handed pitching.",
      "Ashby's greatest value comes from receiving, preparation and knowledge of opposing hitters.",
      "A young catcher such as Mark Bailey can learn Houston's pitching staff from Ashby.",
      "Alan Ashby can enter late to handle a difficult save situation.",
      "His switch-hitting also makes him useful as a pinch-hitter.",
      "Ashby's history with Ryan and Niekro makes him the safest catching option when a game must be protected.",
    ],
  },
  "Dickie Thon": {
    lines: [
      "Dickie Thon's full name is Richard William Thon.",
      "Thon was born in South Bend, Indiana.",
      "Dickie Thon grew up in Puerto Rico.",
      "Thon comes from a family with extensive baseball connections.",
      "The California Angels signed Dickie Thon as an amateur free agent in 1975.",
      "Thon made his major-league debut during the 1979 season.",
      "Houston acquired Dickie Thon from the Angels before the 1981 season.",
      "Thon gradually took over the regular shortstop position.",
      "Dickie Thon emerged as one of baseball's best young shortstops during 1982.",
      "Thon enjoyed an exceptional season in 1983.",
      "Dickie Thon appeared in 154 games.",
      "Thon collected 177 hits.",
      "Dickie Thon batted .286.",
      "Thon recorded 28 doubles and ten triples.",
      "Dickie Thon hit 20 home runs.",
      "Thon drove in 79 runs and scored 81.",
      "Dickie Thon stole 34 bases.",
      "Thon was selected to the 1983 National League All-Star team.",
      "Dickie Thon received the Silver Slugger Award at shortstop.",
      "Thon finished seventh in the National League Most Valuable Player voting.",
      "He combines shortstop defense with power rarely seen at the position.",
      "Thon can steal a base, stretch a hit into a triple or drive a pitch over the fence.",
      "His quick release allows him to complete plays from deep in the hole.",
      "Thon is far more dangerous offensively than a conventional reserve infielder.",
      "Using him from the bench gives Houston a pinch-hitter, pinch-runner and defensive replacement in one player.",
      "He can replace Reynolds at shortstop or enter elsewhere and immediately change the complexion of the game.",
      "Based solely on his 1983 performance, Thon is one of the strongest bench weapons on any roster in your game.",
    ],
  },
  "Denny Walling": {
    lines: [
      "Denny Walling's full name is Dennis Martin Walling.",
      "Walling was born in Neptune, New Jersey.",
      "Denny Walling attended Clemson University.",
      "The Oakland Athletics selected Walling in the first round of the 1975 amateur draft.",
      "Walling made his major-league debut with Oakland during the same year.",
      "Denny Walling later played for the Houston Astros.",
      "Walling bats left-handed and throws right-handed.",
      "Denny Walling can play first base, third base and all three outfield positions.",
      "His versatility has allowed Houston to use him without providing a permanent starting position.",
      "Walling appeared in 100 games during the 1983 season.",
      "Denny Walling received only 135 official at-bats.",
      "Walling collected 40 hits.",
      "Denny Walling batted .296.",
      "Walling recorded five doubles and three triples.",
      "Denny Walling hit three home runs and drove in 19 runs.",
      "Walling posted a .364 on-base percentage.",
      "His .444 slugging percentage demonstrates useful extra-base ability.",
      "Denny Walling is particularly valuable against right-handed pitching.",
      "Walling can pinch-hit and then remain in the game at several positions.",
      "He can replace Garner at third, Cabell at first or one of the corner outfielders.",
      "Walling's ability to stay productive despite irregular playing time is an important bench skill.",
      "He gives Houston a professional left-handed at-bat during the late innings.",
    ],
  },
  "Kevin Bass": {
    lines: [
      "Kevin Bass's full name is Kevin Charles Bass.",
      "Bass was born in Redwood City, California.",
      "Kevin Bass attended Menlo School in Atherton, California.",
      "The Milwaukee Brewers selected Bass in the second round of the 1977 amateur draft.",
      "Bass developed as a switch-hitting outfielder.",
      "Kevin Bass made his major-league debut with Milwaukee on April 9, 1982.",
      "Houston acquired Bass as part of the trade involving pitcher Don Sutton.",
      "Kevin Bass appeared in 58 games for the Astros during 1983.",
      "Bass remained a young player still attempting to establish himself.",
      "Kevin Bass can play any of the three outfield positions.",
      "Bass combines running speed with a strong throwing arm.",
      "Kevin Bass is capable of batting from either side of the plate.",
      "His switch-hitting gives Houston flexibility against opposing bullpens.",
      "Bass's athleticism makes him useful as either a pinch-runner or defensive replacement.",
      "Kevin Bass possesses more power than his early major-league totals might indicate.",
      "His minor-league development suggested the possibility of becoming an everyday outfielder.",
      "Bass can replace Mumphrey in center without forcing Houston to move Cruz or Puhl.",
      "He can also enter in right field when a stronger late-inning arm is needed.",
      "Opposing teams have only limited major-league experience from which to construct a scouting report.",
      "Bass enters 1984 attempting to turn his physical tools into consistent major-league production.",
    ],
  },
  "Ray Knight": {
    lines: [
      "Ray Knight's full name is Charles Ray Knight.",
      "Knight was born in Albany, Georgia.",
      "Ray Knight attended Dougherty High School.",
      "The Cincinnati Reds selected Knight in the tenth round of the 1970 amateur draft.",
      "Knight developed in Cincinnati's farm system behind established star Pete Rose.",
      "Ray Knight made his major-league debut during 1974.",
      "Knight became Cincinnati's regular third baseman after Rose left the club.",
      "Ray Knight enjoyed his best season to that point in 1980.",
      "Knight batted .318 with 176 hits.",
      "Ray Knight recorded 37 doubles during that season.",
      "Knight was selected to the 1980 National League All-Star team.",
      "Houston acquired Ray Knight before the 1982 season.",
      "Knight can play both third base and first base.",
      "Ray Knight appeared in 146 games during the 1983 season.",
      "Knight collected 138 hits.",
      "Ray Knight batted .304.",
      "Knight recorded 36 doubles.",
      "Ray Knight hit nine home runs and drove in 70 runs.",
      "Knight struck out only 42 times.",
      "Ray Knight uses a line-drive swing and is difficult to overpower.",
      "He is especially effective when a runner needs to be moved without sacrificing an out.",
      "Knight's experience at both corner-infield positions gives Houston valuable flexibility.",
      "He can replace Garner at third or Cabell at first.",
      "Knight's .304 average and 36 doubles make him an unusually accomplished player to have available from the bench.",
      "His competitive temperament fits well in close, physical games.",
      "A pitcher who assumes Knight is merely a defensive replacement risks facing one of Houston's best pure contact hitters.",
    ],
  },
  "Nolan Ryan": {
    lines: [
      "Nolan Ryan's full name is Lynn Nolan Ryan Jr.",
      "Ryan was born in Refugio, Texas.",
      "Nolan Ryan grew up in Alvin, Texas.",
      "The New York Mets selected Ryan in the 12th round of the 1965 amateur draft.",
      "Ryan made his major-league debut with the Mets during 1966.",
      "Nolan Ryan was a member of New York's 1969 World Series championship club.",
      "The Mets traded Ryan to the California Angels after the 1971 season.",
      "Nolan Ryan developed into baseball's most overpowering strikeout pitcher with California.",
      "Ryan threw two no-hitters during the 1973 season.",
      "Nolan Ryan threw a third no-hitter in 1974.",
      "Ryan tied Sandy Koufax's career record by throwing his fourth no-hitter in 1975.",
      "Nolan Ryan struck out 383 hitters in 1973.",
      "That total established a modern major-league single-season record.",
      "Ryan led the American League in strikeouts seven times during the 1970s.",
      "Nolan Ryan became baseball's first player to sign a contract averaging one million dollars per season when he joined Houston.",
      "Ryan made his Astros debut in 1980.",
      "Nolan Ryan helped Houston win its first division championship that season.",
      "On September 26, 1981, Ryan threw his fifth career no-hitter.",
      "The performance broke the career record he had shared with Koufax.",
      "Nolan Ryan led the National League with a 1.69 ERA during the 1981 season.",
      "On April 27, 1983, Ryan struck out Montreal's Brad Mills.",
      "The strikeout made Ryan the first pitcher in major-league history to reach 3,500 career strikeouts.",
      "Ryan made 29 starts during the 1983 season.",
      "Nolan Ryan finished with a 14-9 record.",
      "Ryan posted a 2.98 ERA.",
      "Nolan Ryan worked 196 and a third innings.",
      "Ryan struck out 183 hitters.",
      "Nolan Ryan allowed only 138 hits.",
      "His fastball can reach extraordinary velocity even late in a game.",
      "Ryan also throws a devastating curveball.",
      "His improved changeup gives hitters another speed to consider.",
      "Ryan's wildness can sometimes create walks, but it also prevents hitters from becoming comfortable.",
      "A hitter facing Ryan must decide whether to protect against a fastball near 100 miles per hour or a curveball diving through the zone.",
      "Ryan's conditioning program includes extensive weight training, unusual for pitchers of his generation.",
    ],
  },
  "Joe Niekro": {
    lines: [
      "Joe Niekro's full name is Joseph Franklin Niekro.",
      "Niekro was born in Martins Ferry, Ohio.",
      "Joe Niekro is the younger brother of pitcher Phil Niekro.",
      "The brothers learned the knuckleball from their father.",
      "The Cleveland Indians signed Joe Niekro as an amateur free agent in 1966.",
      "Niekro made his major-league debut with the Chicago Cubs during 1967.",
      "Joe Niekro originally relied more heavily upon conventional pitches.",
      "He later pitched for San Diego, Detroit and Atlanta.",
      "Houston acquired Joe Niekro during the 1975 season.",
      "Niekro increasingly relied upon the knuckleball as his career progressed.",
      "Joe Niekro enjoyed his breakthrough season in 1979.",
      "Niekro finished 21-11.",
      "His 21 victories tied brother Phil for the National League lead.",
      "Joe Niekro finished second in the 1979 National League Cy Young Award voting.",
      "Niekro won 20 games in 1980.",
      "Joe Niekro helped pitch Houston to its first division championship.",
      "Niekro won the deciding playoff game against the Los Angeles Dodgers.",
      "Joe Niekro then pitched ten scoreless innings in Game Three of the National League Championship Series.",
      "Niekro made 38 starts during the 1983 season.",
      "Joe Niekro finished with a 15-14 record.",
      "Niekro worked 263 and two-thirds innings.",
      "Joe Niekro completed 11 games.",
      "Niekro recorded two shutouts.",
      "Joe Niekro relies upon movement and durability rather than overpowering velocity.",
      "His knuckleball may flutter, dive or move sideways near the plate.",
      "Catchers cannot always predict where the pitch will finish.",
      "The lack of spin makes the ball highly sensitive to air movement.",
      "Niekro can throw the knuckleball repeatedly without placing the same stress on his arm as a hard fastball.",
      "A hitter may receive several consecutive knuckleballs that move in entirely different directions.",
      "Niekro provides the sharpest possible contrast to Nolan Ryan's overwhelming fastball.",
    ],
  },
  "Bob Knepper": {
    lines: [
      "Bob Knepper's full name is Robert Wesley Knepper.",
      "Knepper was born in Akron, Ohio.",
      "Bob Knepper attended Calistoga High School in California.",
      "The San Francisco Giants selected Knepper in the second round of the 1972 amateur draft.",
      "Knepper made his major-league debut with San Francisco during 1976.",
      "Bob Knepper is a left-handed pitcher.",
      "Knepper won 17 games for the Giants during the 1978 season.",
      "Bob Knepper recorded six shutouts that year.",
      "Houston acquired Knepper before the 1981 season.",
      "Knepper immediately became a regular member of the Astros' rotation.",
      "Bob Knepper helped Houston reach the 1981 postseason.",
      "Knepper made 32 starts during the 1983 season.",
      "Bob Knepper finished with a 6-13 record.",
      "Knepper posted a 4.18 ERA.",
      "Bob Knepper worked 193 and two-thirds innings.",
      "Knepper completed four games.",
      "Bob Knepper recorded one shutout.",
      "Knepper struck out 94 hitters.",
      "His record was affected by Houston's limited offensive support as well as his own inconsistency.",
      "Knepper relies upon location, movement and changing speeds.",
      "His curveball is particularly effective when he gets ahead in the count.",
      "Knepper's left-handed delivery provides a necessary contrast in a rotation featuring Ryan, Niekro and Scott.",
      "He is capable of working deep into a game when his command is sharp.",
      "Knepper's previous 17-win season proves that he can dominate for extended stretches.",
      "His challenge entering 1984 is rediscovering that consistency.",
    ],
  },
  "Mike Scott": {
    lines: [
      "Mike Scott's full name is Michael Warren Scott.",
      "Scott was born in Santa Monica, California.",
      "Mike Scott attended Pepperdine University.",
      "The New York Mets selected Scott in the second round of the 1976 amateur draft.",
      "Scott made his major-league debut with New York during 1979.",
      "Mike Scott moved between the Mets' rotation and bullpen.",
      "Houston acquired Scott before the 1983 season.",
      "Mike Scott entered the Astros' rotation during his first year with the club.",
      "Scott made 24 starts and five relief appearances in 1983.",
      "Mike Scott finished with a 10-6 record.",
      "Scott posted a 3.72 ERA.",
      "Mike Scott worked 145 innings.",
      "Scott completed four games.",
      "Mike Scott recorded one shutout.",
      "Scott struck out 73 hitters.",
      "He relies primarily upon a fastball, slider and change of speeds.",
      "Mike Scott is a large right-handed pitcher capable of generating a good downward angle.",
      "His fastball can become difficult to lift when located near the knees.",
      "Scott's 1983 winning record suggests that leaving New York benefited him.",
      "He still seeks a truly dominant out pitch.",
      "Scott can challenge hitters inside before expanding the strike zone with his breaking ball.",
      "His control is generally more predictable than Ryan's but his raw power is less overwhelming.",
      "Mike Scott gives Houston a younger right-handed starter behind three established veterans.",
      "He enters 1984 attempting to establish that his successful first Astros season was the beginning of a breakthrough.",
    ],
  },
  "Frank DiPino": {
    lines: [
      "Frank DiPino's full name is Frank Michael DiPino.",
      "DiPino was born in Syracuse, New York.",
      "Frank DiPino is a left-handed pitcher.",
      "The Milwaukee Brewers selected DiPino in the third round of the 1977 amateur draft.",
      "Houston acquired Frank DiPino while he was still a minor-league pitcher.",
      "DiPino made his major-league debut during the 1981 season.",
      "Frank DiPino moved permanently into Houston's bullpen.",
      "DiPino uses a deceptive delivery that can be particularly troublesome for left-handed hitters.",
      "Frank DiPino appeared in 53 games during the 1983 season.",
      "DiPino finished with a 3-4 record.",
      "Frank DiPino posted a 2.65 ERA.",
      "DiPino recorded 20 saves.",
      "Frank DiPino led the Astros in saves.",
      "DiPino worked 71 and a third innings.",
      "Frank DiPino allowed only 52 hits.",
      "DiPino surrendered only two home runs.",
      "Frank DiPino struck out 67 hitters.",
      "DiPino walked only 20.",
      "Frank DiPino posted a 1.009 WHIP.",
      "DiPino finished sixth in the National League Rookie of the Year voting.",
      "His strikeout total nearly matched his innings pitched.",
      "DiPino is capable of entering before the ninth inning and recording more than three outs.",
      "His left-handed delivery can neutralize a dangerous left-handed power hitter.",
      "He is not limited to matchup work and can remain against right-handed batters.",
      "DiPino's ability to avoid home runs is especially valuable when protecting a narrow lead.",
      "Your designation of DiPino as closer accurately reflects his breakout 1983 performance.",
    ],
  },
  "Dave Smith": {
    lines: [
      "Dave Smith's full name is David Stanley Smith.",
      "Smith was born in Richmond, California.",
      "Dave Smith attended San Diego State University.",
      "Houston selected Smith in the eighth round of the 1976 amateur draft.",
      "Smith made his major-league debut during the 1980 season.",
      "Dave Smith became a regular member of Houston's bullpen.",
      "Smith is a right-handed pitcher.",
      "Dave Smith relies upon movement and command more than exceptional velocity.",
      "Smith appeared in 42 games during the 1983 season.",
      "Dave Smith finished with a 3-1 record.",
      "Smith posted a 3.10 ERA.",
      "Dave Smith recorded six saves.",
      "Smith worked 72 and two-thirds innings.",
      "Dave Smith allowed 72 hits.",
      "Smith surrendered only two home runs.",
      "Dave Smith struck out 41 hitters.",
      "Smith's ability to avoid the home-run ball makes him useful in close games.",
      "He can pitch more than one inning when required.",
      "Smith is comfortable entering with runners already on base.",
      "His right-handed delivery provides a contrast to closer Frank DiPino.",
      "Smith can handle the ninth inning when DiPino is unavailable.",
      "He can also work the seventh and eighth innings before turning a lead over to the closer.",
      "Smith's calm mound presence suits a reliever who frequently inherits difficult situations.",
      "His sink and control encourage ground balls on the Astrodome turf.",
    ],
  },
  "Bill Dawley": {
    lines: [
      "Bill Dawley's full name is William Chester Dawley.",
      "Dawley was born in Norwich, Connecticut.",
      "Bill Dawley is a large right-handed pitcher.",
      "The Cincinnati Reds signed Dawley as an amateur free agent.",
      "Houston later acquired Dawley before he reached the majors.",
      "Bill Dawley made his major-league debut on April 15, 1983.",
      "Dawley immediately became one of Houston's most effective relievers.",
      "Bill Dawley appeared in 48 games during his rookie season.",
      "Dawley finished with a 6-6 record.",
      "Bill Dawley posted a 2.82 ERA.",
      "Dawley recorded 14 saves.",
      "Bill Dawley worked 79 and two-thirds innings.",
      "Dawley allowed only 51 hits.",
      "Bill Dawley struck out 60 hitters.",
      "Dawley held opposing hitters to an extremely low batting average.",
      "Bill Dawley was selected to the 1983 National League All-Star team.",
      "He became an All-Star during his first major-league season.",
      "Dawley's size allows him to create a steep angle toward the plate.",
      "His fastball gives Houston a harder-throwing relief option.",
      "Dawley can enter during the middle innings and remain for an extended assignment.",
      "He can also close when DiPino is unavailable.",
      "His 14 saves demonstrate that Houston trusted him in late, close games.",
      "Dawley's unfamiliarity can work to his advantage because many hitters have seen him only a few times.",
      "His combination of rookie status and All-Star recognition makes him one of the bullpen's most intriguing pitchers.",
    ],
  },
  "Vern Ruhle": {
    lines: [
      "Vern Ruhle's full name is Vernon Gerald Ruhle.",
      "Ruhle was born in Coleman, Michigan.",
      "Vern Ruhle attended Olivet College.",
      "The Detroit Tigers selected Ruhle in the 17th round of the 1972 amateur draft.",
      "Ruhle made his major-league debut with Detroit during 1974.",
      "Vern Ruhle later joined the Houston Astros.",
      "Ruhle became an important member of Houston's starting rotation.",
      "Vern Ruhle enjoyed an outstanding season in 1980.",
      "Ruhle finished 12-4 with a 2.37 ERA.",
      "He helped the Astros win their first division championship.",
      "Vern Ruhle started Game Four of the 1980 National League Championship Series.",
      "Ruhle has experience as both a starter and reliever.",
      "Vern Ruhle appeared in 41 games during 1983.",
      "Ruhle made nine starts.",
      "Vern Ruhle finished with an 8-5 record.",
      "Ruhle posted a 3.69 ERA.",
      "Vern Ruhle worked 114 and two-thirds innings.",
      "Ruhle recorded three saves.",
      "Vern Ruhle struck out 43 hitters and walked 36.",
      "Ruhle's starting experience makes him Houston's natural long reliever.",
      "He can enter during the early innings and remain through multiple trips around the batting order.",
      "Ruhle relies upon command and movement rather than strikeouts.",
      "He can also make an emergency start without changing his basic preparation.",
      "Ruhle's postseason and pennant-race experience provide stability behind the younger relievers.",
      "His ability to shift roles gives Houston greater freedom when removing a struggling starter.",
    ],
  },
  "Julio Solano": {
    lines: [
      "Julio Solano's full name is Julio Cesar Solano.",
      "Solano was born in Agua Blanca in the Dominican Republic.",
      "Julio Solano is a right-handed pitcher.",
      "Houston signed Solano as an amateur free agent.",
      "Solano developed in the Astros' minor-league system.",
      "Julio Solano made his major-league debut during 1983.",
      "Solano appeared in four games.",
      "Julio Solano worked exclusively from the bullpen.",
      "Solano finished with an 0-2 record.",
      "Julio Solano posted a 6.00 ERA.",
      "Solano worked six innings.",
      "Julio Solano allowed five hits.",
      "Solano surrendered four earned runs.",
      "Julio Solano walked four hitters.",
      "Solano struck out three.",
      "Julio Solano faced only a very small number of major-league hitters.",
      "His six-inning sample is too limited to establish his true ability.",
      "National League opponents possess almost no firsthand experience against him.",
      "Solano's relative unfamiliarity can benefit him during a short exhibition appearance.",
      "He must control his fastball to avoid creating trouble with walks.",
      "Solano provides a younger power arm behind Houston's more established relievers.",
      "He can be used when the Astros need several outs without exhausting DiPino, Dawley or Smith.",
      "Solano enters 1984 attempting to demonstrate that his difficult first trial was not representative of his potential.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive - base hit.\"",
    "\"Long drive to center field - way back - gone. Home run!\"",
    "\"Ground ball to short - over to first - in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub has some real talent - Cruz, Puhl, Ryan - the Astros can play with anybody.\"",
    "\"Houston baseball is alive and well - the fans here at the Astrodome love their Astros.\"",
    "\"This team has speed, defense and pitching - Jose Cruz is one of the best all-around players in the league.\"",
    "\"The Astrodome is home - and the Astros are ready to make some noise in the NL West.\"",
    "\"Jose Cruz is the heart of this lineup - .318, 92 RBI, 30 steals - he does everything.\"",
    "\"Nolan Ryan is the most intimidating pitcher in baseball - five no-hitters and 3,500 strikeouts.\"",
    "\"Dickie Thon is one of the most dangerous shortstops in baseball - 20 homers, 34 steals.\"",
    "\"There's talent everywhere you look in this lineup - the Astros can hurt you.\"",
    "\"This club won the division in 1980 - Houston believes it can contend again.\"",
    "\"The fans in Houston have been waiting for another winner - they got a taste in '80.\"",
    "\"There's a buzz around the Astros this year - people can feel something building.\"",
    "\"From Cheo to the Ryan Express to Scrap Iron - the Astros have characters at every position.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Jose Cruz finished third in the MVP voting - .318, 14 homers, 92 RBI, 30 steals. He's the complete package.\"",
    "\"Nolan Ryan was baseball's first million-dollar player - and he's worth every penny.\"",
    "\"Dickie Thon hit 20 home runs from shortstop - that's extraordinary power for the position.\"",
    "\"Joe Niekro and his knuckleball - there's nothing else quite like it in baseball.\"",
    "\"Terry Puhl batted .526 in the 1980 NLCS - that's an incredible performance under pressure.\"",
    "\"Bill Dawley became an All-Star as a rookie - 14 saves and a 2.82 ERA.\"",
    "\"Phil Garner won a World Series with Pittsburgh in '79 - he knows how to win.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at the Astrodome.\"",
    "\"The lights are on at the Dome - Astros baseball tonight.\"",
    "The Astrodome - the Eighth Wonder of the World - home of the Astros since 1965.",
    "\"The air conditioning is humming tonight - always 72 degrees inside the Dome.\"",
    "\"The white roof stretched above the field - there's nothing else like it in baseball.\"",
    "\"The artificial turf plays fast tonight - ground balls will scoot through the infield.\"",
    "\"The stands are filling up nicely - Houston fans are excited about this club.\"",
    "\"You can hear the ballgame echoing off the roof tonight - the Dome has its own sound.\"",
    "\"A comfortable evening inside the Astrodome - no rain delays here, ever.\"",
    "\"The Dome is hopping tonight - the crowd is into this one.\"",
    "\"Baseball indoors in the Gulf Coast - the Astrodome is home.\"",
    "\"The spacious dimensions here make it tough on home-run hitters.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here at the Astrodome is into this ballgame.\"",
    "\"Astros fans are making some noise tonight.\"",
    "\"The fans in Houston are fired up tonight - they love their Astros.\"",
    "\"The Astrodome is rocking tonight.\"",
    "\"Houston fans are among the most knowledgeable in the South - they appreciate good fundamental play.\"",
    "\"The crowd is on its feet - they can feel something building here.\"",
    "\"A great turnout at the Dome tonight.\"",
    "\"These fans love their Astros - from Cheo to the Ryan Express to Scrap Iron.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to the Astrodome, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball indoors in Houston.\"",
    "\"From all of us here in Space City, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story - that's the beauty of this sport.\"",
    "\"Baseball in Houston - it's a Gulf Coast tradition.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone - into the seats at the Astrodome!\"",
    "\"Jose Cruuuuuuz! Touch 'em all, Cheo!\"",
    "\"The Astros are making their move here at the Dome.\"",
    "\"And Houston wins it - what a finish at the Astrodome!\"",
    "\"You won't see many better than that one.\"",
    "\"Holy cow, what a ballgame!\"",
  ]},
};