// Oakland Athletics Broadcast — 1984
// Radio: Bill King & Lon Simmons (KLX) / TV: Reggie Gatewood & Ernie Harwell (fill-in)
// Oakland-Alameda County Coliseum — home of the Athletics
// All stats cutoff: end of 1983 season

export function pickAthleticsLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickAthleticsPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Rickey Henderson": {
    lines: [
      "Rickey Henderson's full name is Rickey Nelson Henley Henderson.",
      "Rickey Henderson was born on Christmas Day in 1958.",
      "Rickey Henderson was born in Chicago but grew up in Oakland.",
      "Rickey Henderson attended Oakland Technical High School.",
      "Rickey Henderson was an outstanding baseball and football player during his youth.",
      "Rickey Henderson preferred football as a youngster, but his mother encouraged him to pursue baseball because she believed it offered a longer career.",
      "Rickey Henderson bats right-handed but throws left-handed.",
      "Oakland selected Rickey Henderson in the fourth round of the 1976 amateur draft.",
      "Rickey Henderson made his major-league debut on June 24, 1979.",
      "Rickey Henderson stole 33 bases in only 89 games during his rookie season.",
      "Rickey Henderson established an American League record by stealing 100 bases in 1980.",
      "Rickey Henderson won an American League Gold Glove Award in 1981.",
      "Rickey Henderson stole a major-league-record 130 bases during the 1982 season.",
      "Rickey Henderson broke Lou Brock's previous single-season record of 118 stolen bases.",
      "Rickey Henderson followed his record season by stealing 108 bases in 1983.",
      "Rickey Henderson has stolen 427 bases during his first five major-league seasons.",
      "Rickey Henderson appeared in 145 games during the 1983 season.",
      "Rickey Henderson batted .292 with a .414 on-base percentage in 1983.",
      "Rickey Henderson collected 150 hits, 25 doubles, seven triples and nine home runs during the 1983 season.",
      "Rickey Henderson scored 105 runs and drew 103 walks in 1983.",
      "Rickey Henderson has already been selected to three American League All-Star teams.",
      "Rickey Henderson is still only 25 years old entering the 1984 season.",
      "Rickey Henderson can turn a walk or a single into a scoring opportunity before the next hitter completes his at-bat.",
    ],
  },
  "Joe Morgan": {
    lines: [
      "Joe Morgan's full name is Joseph Leonard Morgan.",
      "Joe Morgan is commonly known by the nickname \"Little Joe.\"",
      "Joe Morgan was born in Bonham, Texas.",
      "Joe Morgan moved to Oakland with his family when he was five years old.",
      "Joe Morgan attended Castlemont High School in Oakland.",
      "Joe Morgan stands approximately 5-foot-7 but has spent his career producing power numbers uncommon for a player of his size.",
      "Joe Morgan began his major-league career with the Houston Colt .45s.",
      "Joe Morgan developed into an All-Star second baseman while playing for Houston.",
      "Joe Morgan was traded to Cincinnati following the 1971 season.",
      "Joe Morgan became a central member of Cincinnati's \"Big Red Machine.\"",
      "Joe Morgan won the National League Most Valuable Player Award in both 1975 and 1976.",
      "Joe Morgan helped Cincinnati win consecutive World Series championships in 1975 and 1976.",
      "Joe Morgan delivered the ninth-inning single that drove home the deciding run in Game Seven of the 1975 World Series.",
      "Joe Morgan has won five Gold Glove Awards at second base.",
      "Joe Morgan has been selected to ten All-Star teams through the 1983 season.",
      "Joe Morgan's distinctive movement of his left elbow helps him maintain rhythm and timing at the plate.",
      "Joe Morgan won a Silver Slugger Award with San Francisco during the 1982 season.",
      "Joe Morgan batted .289 with 14 home runs and 24 stolen bases for the Giants in 1982.",
      "Joe Morgan helped Philadelphia reach the World Series during the 1983 season.",
      "Joe Morgan hit 16 home runs, stole 18 bases and drew 89 walks for Philadelphia in 1983.",
      "Joe Morgan entered 1984 with 2,428 hits, 262 home runs and 681 stolen bases.",
      "Joe Morgan has drawn 1,799 career walks and owns a .394 career on-base percentage through 1983.",
      "Joe Morgan's arrival in Oakland represents a homecoming near the end of an extraordinary career.",
      "Joe Morgan and Rickey Henderson give Oakland two of the most accomplished base stealers in baseball history at the top of the lineup.",
    ],
  },
  "Carney Lansford": {
    lines: [
      "Carney Lansford's full name is Carney Ray Lansford.",
      "Carney Lansford was born in San Jose, California.",
      "Carney Lansford attended Wilcox High School in Santa Clara.",
      "California selected Carney Lansford in the third round of the 1975 amateur draft.",
      "Carney Lansford made his major-league debut with the Angels during the 1978 season.",
      "Carney Lansford immediately became California's regular third baseman.",
      "Carney Lansford finished third in the 1978 American League Rookie of the Year voting.",
      "Carney Lansford was later traded from California to Boston.",
      "Carney Lansford won the American League batting championship in 1981.",
      "Carney Lansford batted .336 during that strike-shortened season.",
      "Carney Lansford received a Silver Slugger Award in 1981.",
      "Carney Lansford batted .301 for Boston during the 1982 season.",
      "Oakland acquired Carney Lansford following the 1982 season.",
      "The trade sent outfielder Tony Armas and catcher Jeff Newman to Boston.",
      "An injury limited Carney Lansford to 80 games during his first season with Oakland.",
      "Carney Lansford still batted .308 during the 1983 season.",
      "Carney Lansford collected 92 hits, 16 doubles and 10 home runs in 1983.",
      "Carney Lansford drove in 45 runs and scored 43 times during the 1983 season.",
      "Carney Lansford recorded a .357 on-base percentage and a .475 slugging percentage in 1983.",
      "Carney Lansford enters 1984 with a .294 career batting average.",
      "Carney Lansford's brother Joe has also appeared in the major leagues.",
      "Carney Lansford is still only 27 years old entering the 1984 season.",
      "A healthy Carney Lansford gives Oakland a proven batting champion in the middle of the order.",
    ],
  },
  "Dave Kingman": {
    lines: [
      "Dave Kingman's full name is David Arthur Kingman.",
      "Dave Kingman is approximately 6-foot-6.",
      "Dave Kingman is commonly known by the nicknames \"Kong,\" \"King Kong\" and \"Sky King.\"",
      "Dave Kingman was born in Pendleton, Oregon.",
      "Dave Kingman played college baseball at the University of Southern California.",
      "San Francisco selected Dave Kingman with the second overall pick of the 1970 amateur draft.",
      "Dave Kingman reached the major leagues with the Giants during the 1971 season.",
      "Dave Kingman played first base, third base and the outfield early in his career.",
      "Dave Kingman also made several pitching appearances before becoming a full-time slugger.",
      "Dave Kingman hit for the cycle against Houston on April 16, 1972.",
      "Dave Kingman hit 36 home runs for the New York Mets during the 1975 season.",
      "Dave Kingman followed with 37 home runs for the Mets in 1976.",
      "Dave Kingman hit three home runs in one game against Los Angeles on June 4, 1976.",
      "Dave Kingman played for the Mets, Padres, Angels and Yankees during the unusual 1977 season.",
      "Dave Kingman enjoyed the finest offensive season of his career with the Cubs in 1979.",
      "Dave Kingman hit 48 home runs, drove in 115 runs and slugged .613 in 1979.",
      "Dave Kingman hit three home runs and drove in eight runs during Chicago's famous 23-22 loss to Philadelphia in 1979.",
      "Dave Kingman led the National League with 37 home runs for the Mets in 1982.",
      "Dave Kingman has been selected to three All-Star teams.",
      "Dave Kingman enters the 1984 season with 342 career home runs.",
      "Dave Kingman appeared in 100 games for the Mets during the 1983 season.",
      "Dave Kingman hit 13 home runs but batted .198 in 1983.",
      "Oakland signed Dave Kingman after the Mets released him following the 1983 season.",
      "Dave Kingman's enormous power makes every fly ball to the outfield a potential home run.",
    ],
  },
  "Dwayne Murphy": {
    lines: [
      "Dwayne Murphy's full name is Dwayne Keith Murphy.",
      "Dwayne Murphy was born in Merced, California.",
      "Dwayne Murphy attended Antelope Valley High School in California.",
      "Dwayne Murphy received an opportunity to play college football at Arizona State.",
      "Dwayne Murphy instead chose professional baseball.",
      "Oakland selected Dwayne Murphy in the 15th round of the 1973 amateur draft.",
      "Dwayne Murphy made his major-league debut during the 1978 season.",
      "Dwayne Murphy developed into Oakland's regular center fielder.",
      "Dwayne Murphy has won four consecutive Gold Glove Awards from 1980 through 1983.",
      "Dwayne Murphy led the American League with 22 sacrifice hits during the 1980 season.",
      "Dwayne Murphy combines exceptional outfield range with a strong throwing arm.",
      "Dwayne Murphy enjoyed his finest offensive season to date in 1982.",
      "Dwayne Murphy hit 27 home runs and drove in 94 runs during the 1982 season.",
      "Dwayne Murphy stole 26 bases and drew 94 walks in 1982.",
      "Dwayne Murphy became one of the relatively few players capable of producing both 20 home runs and 20 stolen bases in the same season.",
      "Dwayne Murphy appeared in 130 games during the 1983 season.",
      "Dwayne Murphy hit 17 home runs and drove in 75 runs in 1983.",
      "Dwayne Murphy drew 62 walks during the 1983 season.",
      "Dwayne Murphy recorded seven outfield assists in ! 1983.",
      "Dwayne Murphy bats and throws left-handed.",
      "Dwayne Murphy's walk totals often make his on-base percentage considerably better than his batting average.",
      "Dwayne Murphy and Rickey Henderson give Oakland exceptional defensive range in two-thirds of the outfield.",
    ],
  },
  "Mike Davis": {
    lines: [
      "Mike Davis was born in San Diego, California.",
      "Mike Davis attended Herbert Hoover High School in San Diego.",
      "Oakland selected Mike Davis in the third round of the 1977 amateur draft.",
      "Mike Davis bats and throws left-handed.",
      "Mike Davis made his major-league debut with Oakland during the 1980 season.",
      "Mike Davis received only limited major-league playing time during his first two seasons.",
      "Mike Davis made a strong impression late in the 1982 season.",
      "Mike Davis collected 30 hits in 75 at-bats during his 23-game trial in 1982.",
      "Mike Davis batted .400 during that late-season opportunity.",
      "Mike Davis established himself as Oakland's regular right fielder during the 1983 season.",
      "Mike Davis appeared in 128 games in 1983.",
      "Mike Davis batted .275 with 122 hits during the 1983 season.",
      "Mike Davis recorded 24 doubles and four triples in 1983.",
      "Mike Davis hit eight home runs and drove in 62 runs during the 1983 season.",
      "Mike Davis scored 61 runs in 1983.",
      "Mike Davis stole 32 bases during his first full major-league season.",
      "Mike Davis was caught stealing 15 times in 1983.",
      "Mike Davis gives Oakland another dangerous runner behind Rickey Henderson.",
      "Mike Davis has enough speed to cover considerable territory in right field.",
      "Mike Davis gives Oakland a young left-handed hitter with developing power.",
    ],
  },
  "Bruce Bochte": {
    lines: [
      "Bruce Bochte's full name is Bruce Anton Bochte.",
      "Bruce Bochte was born in Santa Monica, California.",
      "California selected Bruce Bochte in the second round of the 1972 amateur draft.",
      "Bruce Bochte reached the major leagues with the Angels during the 1974 season.",
      "Bruce Bochte later played for Cleveland before joining the expansion Seattle Mariners.",
      "Bruce Bochte developed into one of Seattle's most dependable hitters.",
      "Bruce Bochte enjoyed his finest season in 1979.",
      "Bruce Bochte batted .316 with 38 doubles during the 1979 season.",
      "Bruce Bochte hit 16 home runs and drove in 100 runs in 1979.",
      "Bruce Bochte was selected to the American League All-Star team in 1979.",
      "Bruce Bochte followed by batting .300 during the 1980 season.",
      "Bruce Bochte appeared in 144 games for Seattle during the 1982 season.",
      "Bruce Bochte batted .297 with 151 hits in 1982.",
      "Bruce Bochte hit 12 home runs and drove in 70 runs during the 1982 season.",
      "Bruce Bochte drew 67 walks and recorded a .380 on-base percentage in 1982.",
      "Bruce Bochte voluntarily sat out the entire 1983 season.",
      "Bruce Bochte had become dissatisfied with the business side of professional baseball.",
      "Bruce Bochte also wanted time to consider environmental, social and personal concerns away from the sport.",
      "Bruce Bochte enters 1984 with a .286 career batting average.",
      "Bruce Bochte is primarily a first baseman but can also play left field or serve as the designated hitter.",
      "Bruce Bochte uses a smooth left-handed swing and generally emphasizes line drives rather than home-run distance.",
      "Bruce Bochte's principal question entering 1984 is how quickly his timing will return after a full season away.",
    ],
  },
  "Mike Heath": {
    lines: [
      "Mike Heath's full name is Michael Thomas Heath.",
      "Mike Heath was born in Tampa, Florida.",
      "Mike Heath began his professional career in the New York Yankees organization.",
      "Mike Heath made his major-league debut with the Yankees during the 1978 season.",
      "Mike Heath was included in the large trade that sent relief pitcher Sparky Lyle from New York to Texas.",
      "The Yankees received a package in that transaction that included future pitcher Dave Righetti.",
      "Mike Heath moved to Oakland before playing a regular-season game for Texas.",
      "Mike Heath has appeared at catcher, third base and both corner-outfield positions.",
      "Mike Heath's athleticism is unusual for a player who spends most of his time behind the plate.",
      "Mike Heath appeared in 96 games during the 1983 season.",
      "Mike Heath batted a career-high .281 in 1983.",
      "Mike Heath collected 97 hits and 17 doubles during the 1983 season.",
      "Mike Heath hit six home runs and drove in 33 runs in 1983.",
      "Mike Heath scored 45 runs during the 1983 season.",
      "Mike Heath caught Mike Warren's no-hitter against the Chicago White Sox on September 29, 1983.",
      "Mike Warren's no-hitter came in only his ninth major-league start.",
      "Mike Heath handled the Oakland staff throughout that historic game.",
      "Mike Heath possesses a strong throwing arm behind the plate.",
      "Mike Heath can remain in the lineup at another position when Oakland wants to use a different catcher.",
      "Mike Heath gives Oakland both a regular catcher and an emergency option at several other positions.",
    ],
  },
  "Tony Phillips": {
    lines: [
      "Tony Phillips' full name is Keith Anthony Phillips.",
      "Tony Phillips was born in Atlanta, Georgia.",
      "Tony Phillips attended Roswell High School in Georgia.",
      "Tony Phillips participated in baseball, football, basketball and track during his youth.",
      "Tony Phillips is a switch-hitter who throws right-handed.",
      "Tony Phillips developed in the San Diego Padres organization.",
      "Oakland acquired Tony Phillips before he reached the major leagues.",
      "Tony Phillips made his major-league debut on May 10, 1982.",
      "Tony Phillips appeared in 40 games during his first major-league season.",
      "Tony Phillips received his first full season of major-league playing time in 1983.",
      "Tony Phillips appeared in 148 games during the 1983 season.",
      "Tony Phillips collected 102 hits and scored 54 runs in 1983.",
      "Tony Phillips recorded 12 doubles, three triples and four home runs during the 1983 season.",
      "Tony Phillips drove in 35 runs in 1983.",
      "Tony Phillips stole 16 bases during the 1983 season.",
      "Tony Phillips drew 48 walks and recorded a .327 on-base percentage.",
      "Tony Phillips recorded 11 sacrifice hits in 1983.",
      "Tony Phillips played primarily at shortstop but also appeared at second and third base.",
      "Tony Phillips can move around the infield without requiring Oakland to make several other defensive changes.",
      "Tony Phillips is still only 24 years old entering the 1984 season.",
      "Tony Phillips' switch-hitting and versatility make him useful against either right-handed or left-handed pitching.",
    ],
  },
  "Dave Lopes": {
    lines: [
      "Dave Lopes' full name is David Earl Lopes.",
      "Dave Lopes is commonly called \"Davey.\"",
      "Dave Lopes was born in East Providence, Rhode Island.",
      "Dave Lopes played college baseball at Washburn University.",
      "Los Angeles selected Dave Lopes in the second round of the 1968 amateur draft.",
      "Dave Lopes reached the major leagues with the Dodgers during the 1972 season.",
      "Dave Lopes became Los Angeles' regular second baseman in 1973.",
      "Dave Lopes played alongside Steve Garvey, Bill Russell and Ron Cey in the famous Dodgers infield.",
      "That group remained intact from 1973 through 1981.",
      "Dave Lopes led the National League with 77 stolen bases during the 1975 season.",
      "Dave Lopes again led the league with 63 stolen bases in 1976.",
      "Dave Lopes successfully stole 38 consecutive bases without being caught, establishing a major-league record at the time.",
      "Dave Lopes was selected to four consecutive All-Star teams from 1978 through 1981.",
      "Dave Lopes won a Gold Glove Award in 1978.",
      "Dave Lopes hit a career-high 28 home runs during the 1979 season.",
      "Dave Lopes helped Los Angeles win the 1981 World Series.",
      "Dave Lopes joined Oakland before the 1982 season.",
      "Dave Lopes appeared in 147 games during the 1983 season despite being 38 years old.",
      "Dave Lopes batted .277 with 137 hits in 1983.",
      "Dave Lopes hit 17 home runs and drove in 67 runs during the 1983 season.",
      "Dave Lopes stole 22 bases while being caught only four times in 1983.",
      "Dave Lopes can play second base, third base and the outfield.",
      "Dave Lopes gives Oakland an extraordinarily experienced pinch-runner and late-game replacement.",
    ],
  },
  "Donnie Hill": {
    lines: [
      "Donnie Hill's full name is Donald Earl Hill.",
      "Donnie Hill was born in Pomona, California.",
      "Donnie Hill attended Edison High School in California.",
      "Donnie Hill also played baseball at Orange Coast College and Arizona State University.",
      "Donnie Hill was selected several times during the amateur draft process before signing professionally.",
      "Oakland selected Donnie Hill first overall in the secondary phase of the June 1981 draft.",
      "Donnie Hill is a switch-hitter.",
      "Donnie Hill can play shortstop, second base and third base.",
      "Donnie Hill spent most of the 1983 season with Triple-A Tacoma.",
      "Donnie Hill batted .314 in 93 games for Tacoma.",
      "Donnie Hill collected 19 doubles and hit 14 home runs during his Triple-A season.",
      "Donnie Hill drove in 63 runs and stole nine bases for Tacoma.",
      "Donnie Hill made his major-league debut on July 25, 1983.",
      "Donnie Hill appeared in 53 games for Oakland during his first major-league trial.",
      "Donnie Hill batted .266 with 42 hits in 1983.",
      "Donnie Hill recorded seven doubles, two home runs and 15 RBI.",
      "Donnie Hill scored 20 runs during his first major-league season.",
      "Donnie Hill enters 1984 as a young switch-hitting alternative at either middle-infield position.",
    ],
  },
  "Jim Essian": {
    lines: [
      "Jim Essian's full name is James Sarkis Essian.",
      "Jim Essian was born in Detroit, Michigan.",
      "Jim Essian is of Armenian family heritage.",
      "Jim Essian signed with Philadelphia as an undrafted amateur free agent in 1969.",
      "Jim Essian made his major-league debut with the Phillies during the 1973 season.",
      "Jim Essian later became a regular catcher for the Chicago White Sox.",
      "Jim Essian enjoyed his strongest offensive season in 1977.",
      "Jim Essian batted .273 with 18 doubles and 10 home runs during the 1977 season.",
      "Jim Essian drove in 44 runs and drew 52 walks in 1977.",
      "Jim Essian recorded a .374 on-base percentage during that season.",
      "Jim Essian previously played for Oakland from 1978 through 1980.",
      "Jim Essian later spent time with Seattle and Cleveland.",
      "Jim Essian appeared in 48 games for Cleveland during the 1983 season.",
      "Jim Essian hit two home runs, drove in 11 runs and drew 16 walks in 1983.",
      "Jim Essian has occasionally appeared at first base or third base in addition to catcher.",
      "Jim Essian's return to Oakland gives the Athletics an experienced second catcher.",
      "Jim Essian's principal value is his ability to prepare pitchers and handle a game from behind the plate.",
    ],
  },
  "Jeff Burroughs": {
    lines: [
      "Jeff Burroughs' full name is Jeffrey Alan Burroughs.",
      "Jeff Burroughs was born in Long Beach, California.",
      "The Washington Senators selected Jeff Burroughs with the first overall pick of the 1969 amateur draft.",
      "Jeff Burroughs made his major-league debut during the 1970 season.",
      "Jeff Burroughs remained with the franchise when the Senators moved to Texas.",
      "Jeff Burroughs won the 1974 American League Most Valuable Player Award.",
      "Jeff Burroughs batted .301 with 25 home runs during his MVP season.",
      "Jeff Burroughs led the American League with 118 RBI in 1974.",
      "Jeff Burroughs was selected to the All-Star team in 1974 and 1978.",
      "Jeff Burroughs joined Atlanta and hit a career-high 41 home runs during the 1977 season.",
      "Jeff Burroughs drove in 114 runs during that 1977 season.",
      "Jeff Burroughs drew 117 walks for Atlanta in 1978.",
      "Jeff Burroughs later played for the Seattle Mariners.",
      "Jeff Burroughs batted .277 with a .372 on-base percentage for Oakland in 1982.",
      "Jeff Burroughs hit 16 home runs and slugged .505 during the 1982 season.",
      "Jeff Burroughs appeared in 121 games during the 1983 season.",
      "Jeff Burroughs batted .269 with 10 home runs and 56 RBI in 1983.",
      "Jeff Burroughs drew 47 walks and recorded a .341 on-base percentage in 1983.",
      "Jeff Burroughs enters 1984 with 232 career home runs.",
      "Jeff Burroughs gives Oakland a former MVP and proven right-handed power hitter from the bench.",
    ],
  },
  "Dan Meyer": {
    lines: [
      "Dan Meyer's full name is Daniel Thomas Meyer.",
      "Dan Meyer played college baseball at Santa Ana College.",
      "Detroit selected Dan Meyer in the fourth round of the 1972 amateur draft.",
      "Dan Meyer made his major-league debut with the Tigers during the 1974 season.",
      "Dan Meyer was selected by Seattle before the Mariners' first season.",
      "Dan Meyer became one of the original members of the expansion Mariners in 1977.",
      "Dan Meyer appeared in 159 games during Seattle's inaugural season.",
      "Dan Meyer batted .273 with 159 hits in 1977.",
      "Dan Meyer recorded 24 doubles, four triples and 22 home runs during that season.",
      "Dan Meyer drove in 90 runs and scored 75 times in 1977.",
      "Dan Meyer also stole 11 bases during Seattle's first season.",
      "Dan Meyer has played first base, third base and both corner-outfield positions.",
      "Dan Meyer can also serve as the designated hitter.",
      "Dan Meyer joined Oakland following the 1981 season.",
      "Dan Meyer appeared in 69 games during the 1983 season.",
      "Dan Meyer collected nine doubles, one home run and 13 RBI in 1983.",
      "Dan Meyer drew 19 walks while striking out only 11 times during the 1983 season.",
      "Dan Meyer provides Oakland with an experienced left-handed pinch-hitter and corner-position reserve.",
    ],
  },
  "Ray Burris": {
    lines: [
      "Ray Burris' full name is Bertram Ray Burris.",
      "Ray Burris played college baseball at Southwestern Oklahoma State University.",
      "The Chicago Cubs selected Ray Burris in the 17th round of the 1972 amateur draft.",
      "Ray Burris made his major-league debut with the Cubs during the 1973 season.",
      "Ray Burris became a regular member of Chicago's starting rotation.",
      "Ray Burris won 15 games during the 1975 season.",
      "Ray Burris again won 15 games for the Cubs in 1976.",
      "Ray Burris led the Chicago staff in several major pitching categories during his strongest seasons.",
      "Ray Burris later pitched for the Yankees, Mets and Expos.",
      "Ray Burris helped Montreal reach the postseason during the 1981 season.",
      "Ray Burris appeared in 40 games for Montreal during the 1983 season.",
      "Ray Burris made 17 starts and also worked extensively from the bullpen.",
      "Ray Burris went 4-7 with a 3.68 ERA in 1983.",
      "Ray Burris threw 154 innings during the 1983 season.",
      "Ray Burris struck out 100 hitters and completed two games.",
      "Ray Burris recorded one shutout during the 1983 season.",
      "Ray Burris enters 1984 with an 80-104 career record and a 4.15 ERA.",
      "Ray Burris has already worked more than 1,700 major-league innings.",
      "Ray Burris stands approximately 6-foot-5.",
      "Ray Burris gives Oakland's rotation a veteran who has experience both starting and relieving.",
    ],
  },
  "Steve McCatty": {
    lines: [
      "Steve McCatty's full name is Steven Earl McCatty.",
      "Steve McCatty made his major-league debut with Oakland during the 1977 season.",
      "Steve McCatty has spent his entire major-league career with the Athletics through 1983.",
      "Steve McCatty became one of Oakland's celebrated \"Five Aces.\"",
      "The group also included Rick Langford, Mike Norris, Matt Keough and Brian Kingman.",
      "Steve McCatty threw more than 220 innings during the 1980 season.",
      "Steve McCatty completed 11 games in 1980.",
      "Steve McCatty enjoyed the finest season of his career during the strike-shortened 1981 campaign.",
      "Steve McCatty went 14-7 during the 1981 season.",
      "Steve McCatty led the American League with a 2.33 ERA.",
      "Steve McCatty also led the league with four shutouts.",
      "Steve McCatty completed 16 of his starts during the shortened season.",
      "Steve McCatty finished second to Rollie Fingers in the 1981 American League Cy Young Award voting.",
      "Steve McCatty appeared in 38 games during the 1983 season.",
      "Steve McCatty made 24 starts but also worked from the bullpen.",
      "Steve McCatty went 6-9 with a 3.99 ERA in 1983.",
      "Steve McCatty threw 167 innings, completed three games and recorded two shutouts.",
      "Steve McCatty also recorded five saves during the 1983 season.",
      "Steve McCatty enters 1984 with 45 career complete games.",
      "Steve McCatty's breaking ball remains one of his most important weapons.",
      "Steve McCatty is trying to regain the form that made him the American League ERA champion three seasons earlier.",
    ],
  },
  "Bill Krueger": {
    lines: [
      "Bill Krueger's full name is William Culp Krueger.",
      "Bill Krueger is a left-handed pitcher.",
      "Bill Krueger stands approximately 6-foot-5.",
      "Oakland signed Bill Krueger as an amateur free agent in 1980.",
      "Bill Krueger reached the major leagues during the 1983 season.",
      "Bill Krueger made his major-league debut on April 10, 1983.",
      "Bill Krueger earned a victory in his first major-league appearance.",
      "Bill Krueger appeared in 17 games during his rookie season.",
      "Bill Krueger made 16 starts for Oakland.",
      "Bill Krueger went 7-6 with a 3.61 ERA in 1983.",
      "Bill Krueger worked 109 and two-thirds innings during the 1983 season.",
      "Bill Krueger allowed 104 hits in those innings.",
      "Bill Krueger struck out 58 hitters during his rookie season.",
      "Bill Krueger completed two games in 1983.",
      "Bill Krueger allowed only seven home runs during the season.",
      "Bill Krueger gives Oakland a young left-handed contrast to the rotation's veteran right-handers.",
      "American League hitters are still becoming familiar with Bill Krueger entering his second season.",
    ],
  },
  "Chris Codiroli": {
    lines: [
      "Chris Codiroli's full name is Christopher Anthony Codiroli.",
      "Chris Codiroli grew up in the San Jose area.",
      "Chris Codiroli attended Archbishop Mitty High School.",
      "Chris Codiroli played college baseball at San Jose State University.",
      "Oakland selected Chris Codiroli in the 11th round of the 1978 amateur draft.",
      "Chris Codiroli made his major-league debut during the 1982 season.",
      "Chris Codiroli received his first full season in the major-league rotation in 1983.",
      "Chris Codiroli appeared in 37 games during the 1983 season.",
      "Chris Codiroli made 31 starts.",
      "Chris Codiroli went 12-12 with a 4.46 ERA in 1983.",
      "Chris Codiroli's 12 victories led the Oakland pitching staff.",
      "Chris Codiroli threw 205 and two-thirds innings during the 1983 season.",
      "Chris Codiroli completed seven games.",
      "Chris Codiroli recorded two shutouts in 1983.",
      "Chris Codiroli also recorded one relief save.",
      "Chris Codiroli struck out 85 hitters while walking 72.",
      "Chris Codiroli allowed 208 hits in his 205 and two-thirds innings.",
      "Chris Codiroli relies more upon durability, movement and changing speeds than overpowering strikeout totals.",
      "Chris Codiroli gives Oakland a Bay Area pitcher developed entirely within the organization.",
    ],
  },
  "Bill Caudill": {
    lines: [
      "Bill Caudill's full name is William Holland Caudill.",
      "Bill Caudill is commonly known by the nicknames \"The Inspector\" and \"Cuffs.\"",
      "Bill Caudill earned \"The Inspector\" nickname while pitching for Seattle.",
      "Bill Caudill jokingly examined teammates' bats to determine whether they had any unused hits remaining in them.",
      "Bill Caudill sometimes performed the inspections while wearing a Sherlock Holmes-style cap.",
      "Bill Caudill's entrance music in Seattle was associated with the theme from The Pink Panther.",
      "Bill Caudill began his major-league career as both a starter and reliever.",
      "Bill Caudill pitched for the Cubs and Yankees before joining Seattle.",
      "Bill Caudill developed into one of the American League's most effective relief pitchers during the 1982 season.",
      "Bill Caudill appeared in 70 games in 1982.",
      "Bill Caudill went 12-9 with a 2.35 ERA.",
      "Bill Caudill recorded 26 saves during the 1982 season.",
      "Bill Caudill struck out 111 hitters in 95 and two-thirds innings.",
      "Bill Caudill allowed only 65 hits during that season.",
      "Bill Caudill again recorded exactly 26 saves for Seattle in 1983.",
      "Bill Caudill appeared in 63 games and struck out 73 hitters during the 1983 season.",
      "Oakland acquired Bill Caudill from Seattle following the 1983 season.",
      "Oakland sent reliever Dave Beard and catcher Bob Kearney to the Mariners in the transaction.",
      "Bill Caudill arrives in Oakland with 53 career saves.",
      "Bill Caudill attacks hitters with a hard fastball and an aggressive late-inning approach.",
      "Bill Caudill's personality is nearly as noticeable as his pitching style.",
      "Oakland acquired Bill Caudill specifically to handle the most important outs at the end of close games.",
    ],
  },
  "Keith Atherton": {
    lines: [
      "Keith Atherton's full name is Keith Rowe Atherton.",
      "Keith Atherton attended Mathews High School in Virginia.",
      "Oakland selected Keith Atherton in the second round of the 1978 amateur draft.",
      "Keith Atherton developed primarily as a relief pitcher.",
      "Keith Atherton made his major-league debut on July 14, 1983.",
      "Keith Atherton earned his first major-league victory two days after making his debut.",
      "Keith Atherton recorded his first major-league save later that same month.",
      "Keith Atherton appeared in 29 games during his rookie season.",
      "Keith Atherton went 2-5 with a 2.77 ERA.",
      "Keith Atherton recorded four saves in 1983.",
      "Keith Atherton worked 68 and two-thirds innings without making a start.",
      "Keith Atherton allowed only 53 hits in those innings.",
      "Keith Atherton recorded a 1.11 WHIP during his first major-league season.",
      "Keith Atherton quickly became one of Oakland's most dependable relievers.",
      "Keith Atherton enters 1984 with only half a season of major-league experience.",
      "Opposing hitters are still learning Keith Atherton's delivery and pitch selection.",
    ],
  },
  "Tom Burgmeier": {
    lines: [
      "Tom Burgmeier's full name is Thomas Henry Burgmeier.",
      "Tom Burgmeier is a veteran left-handed relief pitcher.",
      "Tom Burgmeier uses a low, deceptive delivery.",
      "Tom Burgmeier made his major-league debut during the 1968 season.",
      "Tom Burgmeier has pitched for the Angels, Royals, Twins, Red Sox and Athletics.",
      "Tom Burgmeier has made only a handful of starts during a career spent almost entirely in relief.",
      "Tom Burgmeier enjoyed the finest season of his career with Boston in 1980.",
      "Tom Burgmeier went 5-4 with a 2.00 ERA during the 1980 season.",
      "Tom Burgmeier recorded 24 saves in 1980.",
      "Tom Burgmeier was selected to the American League All-Star team that season.",
      "Boston once temporarily moved Tom Burgmeier from the mound to left field during the ninth inning of a game.",
      "Tom Burgmeier later returned from the outfield to resume pitching.",
      "Tom Burgmeier appeared in 49 games for Oakland during the 1983 season.",
      "Tom Burgmeier went 6-7 with a 2.81 ERA.",
      "Tom Burgmeier threw 96 innings despite making no starts.",
      "Tom Burgmeier allowed only two home runs during the 1983 season.",
      "Tom Burgmeier recorded four saves in 1983.",
      "Tom Burgmeier enters 1984 with more than 700 major-league appearances.",
      "Tom Burgmeier also enters the season with exactly 100 career saves.",
      "Tom Burgmeier remains effective through movement, changing angles and extensive knowledge of hitters.",
      "Tom Burgmeier gives Oakland an experienced left-handed alternative in a predominantly right-handed bullpen.",
    ],
  },
  "Rick Langford": {
    lines: [
      "Rick Langford's full name is James Rick Langford.",
      "Rick Langford began his major-league career with the Pittsburgh Pirates.",
      "Rick Langford later developed into a durable starting pitcher with Oakland.",
      "Rick Langford was one of the Athletics' celebrated \"Five Aces.\"",
      "Rick Langford enjoyed the finest season of his career in 1980.",
      "Rick Langford went 19-12 with a 3.26 ERA during the 1980 season.",
      "Rick Langford threw 290 innings in 1980.",
      "Rick Langford completed an extraordinary 28 games during that season.",
      "Rick Langford led the American League in complete games in 1980.",
      "Rick Langford continued his heavy workload during the strike-shortened 1981 season.",
      "Rick Langford posted a 2.99 ERA and completed 18 games in 1981.",
      "Rick Langford made 31 starts and threw 237 and a third innings during the 1982 season.",
      "Rick Langford completed 15 games and recorded two shutouts in 1982.",
      "Rick Langford walked only 49 hitters in those 237 and a third innings.",
      "Injuries and ineffectiveness limited Rick Langford to seven starts in 1983.",
      "Rick Langford went 0-4 and worked only 20 innings during the 1983 season.",
      "Rick Langford's bullpen role represents a major change from his years as Oakland's workhorse.",
      "Rick Langford understands the Oakland Coliseum mound as well as almost any pitcher on the staff.",
      "Rick Langford and Steve McCatty are the remaining links to the heavily worked Five Aces rotation.",
      "Oakland hopes a reduced role will allow Rick Langford to contribute without carrying his former starting workload.",
    ],
  },
  "Chuck Rainey": {
    lines: [
      "Chuck Rainey's full name is Charles David Rainey.",
      "Chuck Rainey began his major-league career with the Boston Red Sox.",
      "Chuck Rainey made his major-league debut during the 1979 season.",
      "Chuck Rainey worked both as a starter and reliever early in his career.",
      "Chuck Rainey went 8-3 for Boston during the 1980 season.",
      "Chuck Rainey joined the Chicago Cubs before the 1983 season.",
      "Chuck Rainey received the largest starting workload of his career with Chicago.",
      "Chuck Rainey made 34 starts during the 1983 season.",
      "Chuck Rainey went 14-13 with a 4.48 ERA.",
      "Chuck Rainey's 14 victories established a career high.",
      "Chuck Rainey threw 191 innings during the 1983 season.",
      "Chuck Rainey defeated Fernando Valenzuela and the Dodgers on April 30, 1983.",
      "Chuck Rainey came within one out of pitching a no-hitter against Cincinnati on August 24, 1983.",
      "Chuck Rainey retired the first two hitters in the ninth inning before Eddie Milner singled.",
      "Chuck Rainey completed the one-hit shutout as Chicago defeated Cincinnati 3-0.",
      "Chuck Rainey's near no-hitter was the closest a Cubs pitcher had come since Milt Pappas completed one in 1972.",
      "Chuck Rainey completed only one game during the 1983 season, but that game was his near no-hitter.",
      "Chuck Rainey's recent starting experience makes him capable of pitching several innings from the bullpen.",
      "Chuck Rainey can enter early when an Oakland starter is removed or remain through the middle innings.",
      "Chuck Rainey enters 1984 immediately after the most productive season of his major-league career.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive — base hit.\"",
    "\"Long drive to left field — way back — gone. Home run!\"",
    "\"Ground ball to short — over to first — in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub has speed, power and defense — the A's are an exciting team to watch.\"",
    "\"Oakland baseball is back — the fans here in the East Bay love their Athletics.\"",
    "\"Rickey Henderson changes the game every time he reaches base — there's nobody like him.\"",
    "\"This team has been rebuilt from the ground up — and the young talent is starting to show.\"",
    "\"Joe Morgan brings a winner's pedigree — two MVPs, two World Series rings — that's invaluable.\"",
    "\"There's talent everywhere you look in this lineup — the A's can hurt you in so many ways.\"",
    "\"This club plays hard for nine innings — that's the Oakland way.\"",
    "\"The Athletics have one of the most athletic rosters in the American League.\"",
    "\"The fans in Oakland have been through some lean years — but this team is giving them something to cheer about.\"",
    "\"There's a buzz around the A's this year — people can feel something building.\"",
    "\"This is a team on the rise — the young players are starting to come together.\"",
    "\"Oakland baseball — there's nothing quite like a night at the Coliseum.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Rickey Henderson is the most exciting player in baseball — bar none.\"",
    "\"Dave Kingman can hit the ball out of any part of this ballpark — or any other ballpark.\"",
    "\"Joe Morgan is a future Hall of Famer — and he's still going strong.\"",
    "\"Dwayne Murphy might be the best center fielder nobody talks about — four Gold Gloves.\"",
    "\"Carney Lansford is a batting champion — he knows how to hit.\"",
    "\"Bill Caudill brings fire to the back of that bullpen — he's the closer this team needed.\"",
    "\"Tony Phillips does a little bit of everything — switch-hit, play anywhere — he's invaluable.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at the Oakland-Alameda County Coliseum.\"",
    "\"The lights are on at the Coliseum — Athletics baseball tonight.\"",
    "The Oakland Coliseum — home of the Athletics since 1968.",
    "\"The warm East Bay air is perfect for baseball tonight.\"",
    "\"The artificial turf plays fast tonight — ground balls will scoot through the infield.\"",
    "\"The stands are filling up nicely — Oakland fans are excited about this club.\"",
    "\"You can see the Oakland hills beyond the outfield — a beautiful backdrop on a clear night.\"",
    "\"The Coliseum has been home to some of baseball's greatest moments — three straight World Series in the '70s.\"",
    "\"There's plenty of room out there in the outfield — this is one big ballpark.\"",
    "\"The breeze off the bay keeps things comfortable on a warm evening.\"",
    "\"The faithful at the Coliseum are some of the most passionate fans in baseball.\"",
    "\"A crisp evening in the East Bay — there's nothing better than baseball at the Coliseum.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here in Oakland is into this ballgame.\"",
    "\"A's fans are making some noise tonight at the Coliseum.\"",
    "\"The fans in Oakland have waited a long time for a winner — they're fired up tonight.\"",
    "\"The Coliseum is rocking tonight.\"",
    "\"Oakland fans are among the most loyal in baseball — they've been through some tough years.\"",
    "\"The crowd is on its feet — they can feel something building here.\"",
    "\"A great turnout at the Coliseum tonight.\"",
    "\"These fans can see the talent on this club — they're excited about the future.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to the Oakland Coliseum, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball on an East Bay evening.\"",
    "\"From all of us here in Oakland, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story — that's the beauty of this sport.\"",
    "\"Baseball in Oakland — it's a tradition that runs deep in the East Bay.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone — into the seats at the Coliseum!\"",
    "\"Holy toledo — what a ballgame!\"",
    "\"The A's are making their move here at the Coliseum.\"",
    "\"That one is long gone — souvenir for a fan in the bleachers.\"",
    "\"You won't see many better than that one.\"",
    "\"And the crowd goes crazy — what a finish!\"",
  ]},
};