// Rosters for the 15 new teams + Manager cards for all 26 teams

export const EXTRA_ROSTERS = {

  bluejays: [
    { id: 1,  name: 'Dave Stieb',       position: 'SP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '2.83', role: 'Ace Pitcher',          rarity: 'rare'     },
    { id: 2,  name: 'George Bell',      position: 'LF',  number: 11, ba: '.292', hr: 26, rbi: 87,  era: '-',    role: 'Left Field/Power',     rarity: 'rare'     },
    { id: 3,  name: 'Jesse Barfield',   position: 'RF',  number: 29, ba: '.271', hr: 22, rbi: 68,  era: '-',    role: 'Right Field/Arm',      rarity: 'uncommon' },
    { id: 4,  name: 'Lloyd Moseby',     position: 'CF',  number: 15, ba: '.280', hr: 18, rbi: 92,  era: '-',    role: 'Center Field',         rarity: 'uncommon' },
    { id: 5,  name: 'Willie Upshaw',    position: '1B',  number: 26, ba: '.278', hr: 19, rbi: 84,  era: '-',    role: 'First Base',           rarity: 'uncommon' },
    { id: 6,  name: 'Damaso Garcia',    position: '2B',  number: 14, ba: '.284', hr: 5,  rbi: 46,  era: '-',    role: 'Second Base/Leadoff',  rarity: 'common'   },
    { id: 7,  name: 'Rance Mulliniks',  position: '3B',  number: 22, ba: '.324', hr: 12, rbi: 42,  era: '-',    role: 'Third Base/Platoon',   rarity: 'uncommon' },
    { id: 8,  name: 'Ernie Whitt',      position: 'C',   number: 12, ba: '.271', hr: 15, rbi: 46,  era: '-',    role: 'Catcher',              rarity: 'common'   },
    { id: 9,  name: 'Alfredo Griffin',  position: 'SS',  number: 4,  ba: '.241', hr: 4,  rbi: 30,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 10, name: 'Cliff Johnson',    position: 'DH',  number: 37, ba: '.304', hr: 16, rbi: 61,  era: '-',    role: 'Designated Hitter',    rarity: 'common'   },
    { id: 11, name: 'Doyle Alexander', position: 'SP',  number: 33, ba: '-',    hr: '-', rbi: '-', era: '3.13', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 12, name: 'Jim Clancy',       position: 'SP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '5.12', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 13, name: 'Luis Leal',        position: 'SP',  number: 46, ba: '-',    hr: '-', rbi: '-', era: '3.89', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Jimmy Key',        position: 'RP',  number: 22, ba: '-',    hr: '-', rbi: '-', era: '4.65', role: 'Relief Pitcher/Future Ace', rarity: 'uncommon' },
    { id: 15, name: 'Roy Lee Jackson',  position: 'CL',  number: 28, ba: '-',    hr: '-', rbi: '-', era: '4.39', role: 'Closer',               rarity: 'common'   },
    { id: 16, name: 'Dennis Lamp',      position: 'RP',  number: 35, ba: '-',    hr: '-', rbi: '-', era: '3.32', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Jim Acker',        position: 'RP',  number: 43, ba: '-',    hr: '-', rbi: '-', era: '4.38', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Bryan Clark',      position: 'RP',  number: 49, ba: '-',    hr: '-', rbi: '-', era: '4.66', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Tony Fernandez',   position: 'SS',  number: 1,  ba: '.270', hr: 4,  rbi: 19,  era: '-',    role: 'Future Star/Shortstop',rarity: 'uncommon' },
    { id: 20, name: 'Dave Collins',     position: 'OF',  number: 17, ba: '.272', hr: 2,  rbi: 22,  era: '-',    role: 'Bench/Speed',          rarity: 'common'   },
    { id: 21, name: 'Buck Martinez',    position: 'C',   number: 10, ba: '.218', hr: 4,  rbi: 15,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 22, name: 'Garth Iorg',       position: '3B',  number: 18, ba: '.261', hr: 6,  rbi: 32,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
    { id: 23, name: 'Willie Aikens',    position: '1B',  number: 27, ba: '.205', hr: 11, rbi: 29,  era: '-',    role: 'Bench/Power',          rarity: 'common'   },
    { id: 24, name: 'Rick Leach',      position: 'OF',  number: 25, ba: '.261', hr: 0,  rbi: 7,   era: '-',    role: 'Bench/Pinch Hitter',   rarity: 'common'   },
    { id: 25, name: 'Jim Gott',        position: 'RP',  number: 35, ba: '-',    hr: '-', rbi: '-', era: '4.02', role: 'Relief/Swingman',       rarity: 'uncommon' },
  ],

  indians: [
    { id: 1,  name: 'Bert Blyleven',    position: 'SP',  number: 28, ba: '-',    hr: '-', rbi: '-', era: '2.87', role: 'Ace/Future HOF',       rarity: 'rare'     },
    { id: 2,  name: 'Andre Thornton',   position: 'DH',  number: 29, ba: '.271', hr: 33, rbi: 99,  era: '-',    role: 'Designated Hitter',    rarity: 'rare'     },
    { id: 3,  name: 'Julio Franco',     position: 'SS',  number: 12, ba: '.290', hr: 8,  rbi: 79,  era: '-',    role: 'Shortstop',            rarity: 'uncommon' },
    { id: 4,  name: 'Brett Butler',     position: 'CF',  number: 5,  ba: '.269', hr: 3,  rbi: 49,  era: '-',    role: 'Center Field/Leadoff', rarity: 'uncommon' },
    { id: 5,  name: 'Joe Carter',       position: 'LF',  number: 30, ba: '.275', hr: 13, rbi: 41,  era: '-',    role: 'Left Field/Future Star',rarity: 'uncommon' },
    { id: 6,  name: 'Pat Tabler',       position: 'INF', number: 22, ba: '.290', hr: 10, rbi: 68,  era: '-',    role: 'Utility/Clutch Hitter',rarity: 'uncommon' },
    { id: 7,  name: 'Mel Hall',         position: 'OF',  number: 38, ba: '.282', hr: 17, rbi: 49,  era: '-',    role: 'Outfield',             rarity: 'common'   },
    { id: 8,  name: 'Tony Bernazard',   position: '2B',  number: 4,  ba: '.221', hr: 5,  rbi: 38,  era: '-',    role: 'Second Base',          rarity: 'common'   },
    { id: 9,  name: 'Brook Jacoby',     position: '3B',  number: 27, ba: '.252', hr: 7,  rbi: 40,  era: '-',    role: 'Third Base',           rarity: 'common'   },
    { id: 10, name: 'Mike Hargrove',    position: '1B',  number: 21, ba: '.269', hr: 3,  rbi: 44,  era: '-',    role: 'First Base/Patience',  rarity: 'common'   },
    { id: 11, name: 'George Vukovich',  position: 'RF',  number: 19, ba: '.254', hr: 5,  rbi: 36,  era: '-',    role: 'Right Field',          rarity: 'common'   },
    { id: 12, name: 'Chris Bando',      position: 'C',   number: 14, ba: '.238', hr: 5,  rbi: 28,  era: '-',    role: 'Catcher',              rarity: 'common'   },
    { id: 13, name: 'Neal Heaton',      position: 'SP',  number: 40, ba: '-',    hr: '-', rbi: '-', era: '5.21', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Steve Comer',      position: 'SP',  number: 44, ba: '-',    hr: '-', rbi: '-', era: '4.48', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 15, name: 'Steve Farr',       position: 'SP',  number: 35, ba: '-',    hr: '-', rbi: '-', era: '4.58', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 16, name: 'Ernie Camacho',    position: 'CL',  number: 29, ba: '-',    hr: '-', rbi: '-', era: '2.43', role: 'Closer',               rarity: 'uncommon' },
    { id: 17, name: 'Tom Waddell',      position: 'RP',  number: 48, ba: '-',    hr: '-', rbi: '-', era: '4.87', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Luis Aponte',      position: 'RP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '4.32', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Jamie Easterly',   position: 'RP',  number: 50, ba: '-',    hr: '-', rbi: '-', era: '5.06', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 20, name: 'Mike Jeffcoat',    position: 'RP',  number: 52, ba: '-',    hr: '-', rbi: '-', era: '4.99', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 21, name: 'Jerry Willard',    position: 'C',   number: 26, ba: '.224', hr: 6,  rbi: 37,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 22, name: 'Carmen Castillo',  position: 'OF',  number: 33, ba: '.249', hr: 10, rbi: 39,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 23, name: 'Otis Nixon',       position: 'OF',  number: 45, ba: '.154', hr: 0,  rbi: 2,   era: '-',    role: 'Speed/Future Star',    rarity: 'common'   },
    { id: 24, name: 'Mike Fischlin',   position: 'INF', number: 16, ba: '.226', hr: 1,  rbi: 14,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
    { id: 25, name: 'Roy Smith',       position: 'RP',  number: 30, ba: '-',    hr: '-', rbi: '-', era: '4.59', role: 'Rookie/Swingman',       rarity: 'common'   },
  ],

  brewers: [
    { id: 1,  name: 'Robin Yount',      position: 'SS',  number: 19, ba: '.298', hr: 16, rbi: 80,  era: '-',    role: 'Shortstop/HOF',        rarity: 'rare'     },
    { id: 2,  name: 'Cecil Cooper',     position: '1B',  number: 15, ba: '.275', hr: 11, rbi: 67,  era: '-',    role: 'First Base',           rarity: 'rare'     },
    { id: 3,  name: 'Rollie Fingers',   position: 'CL',  number: 34, ba: '-',    hr: '-', rbi: '-', era: '1.96', role: 'Closer/Hall of Fame',  rarity: 'rare'     },
    { id: 4,  name: 'Ben Oglivie',      position: 'LF',  number: 14, ba: '.262', hr: 12, rbi: 61,  era: '-',    role: 'Left Field/Power',     rarity: 'uncommon' },
    { id: 5,  name: 'Paul Molitor',     position: '3B',  number: 4,  ba: '.217', hr: 1,  rbi: 6,   era: '-',    role: 'Future HOF/Comeback',  rarity: 'rare'     },
    { id: 6,  name: 'Ted Simmons',      position: 'DH',  number: 23, ba: '.254', hr: 10, rbi: 72,  era: '-',    role: 'Designated Hitter',    rarity: 'uncommon' },
    { id: 7,  name: 'Jim Gantner',      position: '2B',  number: 17, ba: '.282', hr: 3,  rbi: 56,  era: '-',    role: 'Second Base',          rarity: 'common'   },
    { id: 8,  name: 'Jim Sundberg',     position: 'C',   number: 10, ba: '.261', hr: 3,  rbi: 43,  era: '-',    role: 'Catcher/Gold Glove',   rarity: 'uncommon' },
    { id: 9,  name: 'Rick Manning',     position: 'CF',  number: 8,  ba: '.243', hr: 4,  rbi: 22,  era: '-',    role: 'Center Field',         rarity: 'common'   },
    { id: 10, name: 'Dion James',       position: 'RF',  number: 24, ba: '.251', hr: 1,  rbi: 14,  era: '-',    role: 'Right Field',          rarity: 'common'   },
    { id: 11, name: 'Ed Romero',        position: '3B',  number: 18, ba: '.241', hr: 2,  rbi: 21,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
    { id: 12, name: 'Don Sutton',       position: 'SP',  number: 20, ba: '-',    hr: '-', rbi: '-', era: '3.77', role: 'Starting Pitcher/HOF', rarity: 'rare'     },
    { id: 13, name: 'Mike Caldwell',    position: 'SP',  number: 29, ba: '-',    hr: '-', rbi: '-', era: '4.62', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Moose Haas',       position: 'SP',  number: 42, ba: '-',    hr: '-', rbi: '-', era: '4.26', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 15, name: 'Jaime Cocanower',  position: 'SP',  number: 39, ba: '-',    hr: '-', rbi: '-', era: '4.63', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 16, name: 'Pete Ladd',        position: 'RP',  number: 40, ba: '-',    hr: '-', rbi: '-', era: '3.72', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Ray Searage',      position: 'RP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '3.86', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Tom Tellmann',     position: 'RP',  number: 48, ba: '-',    hr: '-', rbi: '-', era: '4.01', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Rick Waits',       position: 'RP',  number: 33, ba: '-',    hr: '-', rbi: '-', era: '5.15', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 20, name: 'Charlie Moore',    position: 'C',   number: 21, ba: '.239', hr: 2,  rbi: 16,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 21, name: 'Randy Ready',      position: '3B',  number: 26, ba: '.234', hr: 3,  rbi: 17,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
    { id: 22, name: 'Mark Brouhard',    position: 'OF',  number: 35, ba: '.249', hr: 9,  rbi: 34,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 23, name: 'Roy Howell',       position: '3B',  number: 7,  ba: '.235', hr: 4,  rbi: 22,  era: '-',    role: 'Bench/Power',          rarity: 'common'   },
    { id: 24, name: 'Bill Schroeder',   position: 'C',   number: 10, ba: '.257', hr: 14, rbi: 25,  era: '-',    role: 'Backup Catcher/Power', rarity: 'uncommon' },
  ],

  twins: [
    { id: 1,  name: 'Kent Hrbek',       position: '1B',  number: 14, ba: '.311', hr: 27, rbi: 107, era: '-',    role: 'First Base/Hometown Hero', rarity: 'rare'   },
    { id: 2,  name: 'Kirby Puckett',    position: 'CF',  number: 34, ba: '.296', hr: 0,  rbi: 31,  era: '-',    role: 'Center Field/Future HOF',  rarity: 'rare'   },
    { id: 3,  name: 'Tom Brunansky',    position: 'RF',  number: 24, ba: '.264', hr: 32, rbi: 85,  era: '-',    role: 'Right Field/Power',    rarity: 'uncommon' },
    { id: 4,  name: 'Gary Gaetti',      position: '3B',  number: 8,  ba: '.271', hr: 25, rbi: 65,  era: '-',    role: 'Third Base',           rarity: 'uncommon' },
    { id: 5,  name: 'Frank Viola',      position: 'SP',  number: 16, ba: '-',    hr: '-', rbi: '-', era: '3.21', role: 'Starting Pitcher/Future HOF', rarity: 'uncommon' },
    { id: 6,  name: 'Randy Bush',       position: 'DH',  number: 12, ba: '.264', hr: 11, rbi: 43,  era: '-',    role: 'Designated Hitter',    rarity: 'common'   },
    { id: 7,  name: 'Tim Teufel',       position: '2B',  number: 11, ba: '.264', hr: 14, rbi: 61,  era: '-',    role: 'Second Base',          rarity: 'common'   },
    { id: 8,  name: 'Mickey Hatcher',   position: 'LF',  number: 17, ba: '.281', hr: 5,  rbi: 37,  era: '-',    role: 'Left Field/Hustle',    rarity: 'common'   },
    { id: 9,  name: 'Dave Engle',       position: 'C',   number: 22, ba: '.250', hr: 4,  rbi: 34,  era: '-',    role: 'Catcher',              rarity: 'common'   },
    { id: 10, name: 'Houston Jimenez',  position: 'SS',  number: 28, ba: '.215', hr: 2,  rbi: 19,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 11, name: 'Ron Davis',        position: 'CL',  number: 30, ba: '-',    hr: '-', rbi: '-', era: '7.07', role: 'Closer',               rarity: 'common'   },
    { id: 12, name: 'Mike Smithson',    position: 'SP',  number: 44, ba: '-',    hr: '-', rbi: '-', era: '4.77', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 13, name: 'Ken Schrom',       position: 'SP',  number: 38, ba: '-',    hr: '-', rbi: '-', era: '4.54', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'John Butcher',     position: 'SP',  number: 50, ba: '-',    hr: '-', rbi: '-', era: '4.74', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 15, name: 'Pete Filson',      position: 'RP',  number: 43, ba: '-',    hr: '-', rbi: '-', era: '3.64', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Rick Lysander',    position: 'RP',  number: 45, ba: '-',    hr: '-', rbi: '-', era: '4.60', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Curt Wardle',      position: 'RP',  number: 47, ba: '-',    hr: '-', rbi: '-', era: '5.24', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Len Whitehouse',   position: 'RP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '5.41', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Tim Laudner',      position: 'C',   number: 15, ba: '.219', hr: 10, rbi: 35,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 20, name: 'Ron Washington',   position: 'SS',  number: 6,  ba: '.239', hr: 3,  rbi: 18,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
    { id: 21, name: 'Greg Gagne',       position: 'SS',  number: 7,  ba: '.240', hr: 2,  rbi: 12,  era: '-',    role: 'Backup Shortstop',     rarity: 'common'   },
    { id: 22, name: 'Lenny Faedo',      position: 'SS',  number: 9,  ba: '.228', hr: 2,  rbi: 15,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
    { id: 23, name: 'Jim Eisenreich',   position: 'OF',  number: 23, ba: '.304', hr: 0,  rbi: 5,   era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 24, name: 'Darrell Brown',    position: 'OF',  number: 26, ba: '.273', hr: 1,  rbi: 19,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 25, name: 'Albert Williams',  position: 'SP',  number: 35, ba: '-',    hr: '-', rbi: '-', era: '3.92', role: 'Starting Pitcher',     rarity: 'common'   },
  ],

  athletics: [
    { id: 1,  name: 'Rickey Henderson', position: 'LF',  number: 35, ba: '.293', hr: 16, rbi: 58,  era: '-',    role: 'Leadoff/Greatest Ever', rarity: 'rare'    },
    { id: 2,  name: 'Dave Kingman',     position: 'DH',  number: 17, ba: '.268', hr: 35, rbi: 118, era: '-',    role: 'Designated Hitter/Power', rarity: 'rare'   },
    { id: 3,  name: 'Carney Lansford',  position: '3B',  number: 8,  ba: '.300', hr: 14, rbi: 74,  era: '-',    role: 'Third Base',           rarity: 'uncommon' },
    { id: 4,  name: 'Joe Morgan',       position: '2B',  number: 8,  ba: '.244', hr: 6,  rbi: 43,  era: '-',    role: 'Second Base/HOF',      rarity: 'rare'     },
    { id: 5,  name: 'Dwayne Murphy',    position: 'CF',  number: 21, ba: '.256', hr: 13, rbi: 68,  era: '-',    role: 'Center Field/Gold Glove', rarity: 'uncommon' },
    { id: 6,  name: 'Mike Davis',       position: 'RF',  number: 24, ba: '.252', hr: 9,  rbi: 46,  era: '-',    role: 'Right Field',          rarity: 'common'   },
    { id: 7,  name: 'Bruce Bochte',     position: '1B',  number: 10, ba: '.276', hr: 6,  rbi: 52,  era: '-',    role: 'First Base',           rarity: 'common'   },
    { id: 8,  name: 'Mike Heath',       position: 'C',   number: 22, ba: '.248', hr: 8,  rbi: 44,  era: '-',    role: 'Catcher',              rarity: 'common'   },
    { id: 9,  name: 'Tony Phillips',    position: 'SS',  number: 2,  ba: '.266', hr: 4,  rbi: 35,  era: '-',    role: 'Shortstop/Utility',    rarity: 'common'   },
    { id: 10, name: 'Bill Caudill',     position: 'CL',  number: 27, ba: '-',    hr: '-', rbi: '-', era: '2.71', role: 'Closer',               rarity: 'uncommon' },
    { id: 11, name: 'Ray Burris',       position: 'SP',  number: 40, ba: '-',    hr: '-', rbi: '-', era: '3.15', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 12, name: 'Steve McCatty',    position: 'SP',  number: 38, ba: '-',    hr: '-', rbi: '-', era: '4.10', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 13, name: 'Bill Krueger',     position: 'SP',  number: 42, ba: '-',    hr: '-', rbi: '-', era: '4.75', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Chris Codiroli',   position: 'SP',  number: 43, ba: '-',    hr: '-', rbi: '-', era: '4.46', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 15, name: 'Keith Atherton',   position: 'RP',  number: 44, ba: '-',    hr: '-', rbi: '-', era: '3.00', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Tom Burgmeier',    position: 'RP',  number: 45, ba: '-',    hr: '-', rbi: '-', era: '2.53', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Rick Langford',    position: 'RP',  number: 29, ba: '-',    hr: '-', rbi: '-', era: '3.40', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Chuck Rainey',     position: 'RP',  number: 48, ba: '-',    hr: '-', rbi: '-', era: '5.34', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Dave Lopes',       position: '2B',  number: 15, ba: '.224', hr: 7,  rbi: 26,  era: '-',    role: 'Bench/Veteran',        rarity: 'common'   },
    { id: 20, name: 'Donnie Hill',      position: 'SS',  number: 3,  ba: '.243', hr: 2,  rbi: 15,  era: '-',    role: 'Backup Infielder',     rarity: 'common'   },
    { id: 21, name: 'Jeff Burroughs',   position: 'DH',  number: 30, ba: '.245', hr: 8,  rbi: 31,  era: '-',    role: 'Bench/Power',          rarity: 'common'   },
    { id: 22, name: 'Jim Essian',       position: 'C',   number: 9,  ba: '.219', hr: 4,  rbi: 16,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 23, name: 'Dan Meyer',        position: '1B',  number: 25, ba: '.235', hr: 4,  rbi: 18,  era: '-',    role: 'Utility/Bench',        rarity: 'common'   },
    { id: 24, name: 'Bill Almon',      position: 'UT',  number: 34, ba: '.223', hr: 7,  rbi: 16,  era: '-',    role: 'Utility Player',       rarity: 'common'   },
  ],

  angels: [
    { id: 1,  name: 'Reggie Jackson',   position: 'DH',  number: 44, ba: '.237', hr: 25, rbi: 81,  era: '-',    role: 'Mr. October/Legend',   rarity: 'rare'     },
    { id: 2,  name: 'Rod Carew',        position: '1B',  number: 29, ba: '.295', hr: 3,  rbi: 31,  era: '-',    role: 'First Base/HOF',       rarity: 'rare'     },
    { id: 3,  name: 'Mike Witt',        position: 'SP',  number: 36, ba: '-',    hr: '-', rbi: '-', era: '3.47', role: 'Ace/Perfect Game',     rarity: 'rare'     },
    { id: 4,  name: 'Fred Lynn',        position: 'RF',  number: 19, ba: '.271', hr: 23, rbi: 79,  era: '-',    role: 'Right Field',          rarity: 'uncommon' },
    { id: 5,  name: 'Brian Downing',    position: 'LF',  number: 5,  ba: '.250', hr: 23, rbi: 91,  era: '-',    role: 'Left Field',           rarity: 'uncommon' },
    { id: 6,  name: 'Doug DeCinces',    position: '3B',  number: 11, ba: '.269', hr: 20, rbi: 82,  era: '-',    role: 'Third Base',           rarity: 'uncommon' },
    { id: 7,  name: 'Bobby Grich',      position: '2B',  number: 4,  ba: '.256', hr: 18, rbi: 56,  era: '-',    role: 'Second Base/Gold Glove', rarity: 'uncommon' },
    { id: 8,  name: 'Bob Boone',        position: 'C',   number: 8,  ba: '.212', hr: 4,  rbi: 35,  era: '-',    role: 'Catcher/Gold Glove',   rarity: 'uncommon' },
    { id: 9,  name: 'Gary Pettis',      position: 'CF',  number: 17, ba: '.257', hr: 2,  rbi: 29,  era: '-',    role: 'Center Field/Speed',   rarity: 'common'   },
    { id: 10, name: 'Dick Schofield',   position: 'SS',  number: 3,  ba: '.193', hr: 5,  rbi: 21,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 11, name: 'Tommy John',       position: 'SP',  number: 25, ba: '-',    hr: '-', rbi: '-', era: '4.52', role: 'Starting Pitcher/Legend', rarity: 'uncommon' },
    { id: 12, name: 'Geoff Zahn',       position: 'SP',  number: 27, ba: '-',    hr: '-', rbi: '-', era: '4.28', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 13, name: 'Ron Romanick',     position: 'SP',  number: 43, ba: '-',    hr: '-', rbi: '-', era: '3.76', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Luis Sanchez',     position: 'CL',  number: 31, ba: '-',    hr: '-', rbi: '-', era: '2.93', role: 'Closer',               rarity: 'common'   },
    { id: 15, name: 'Don Aase',         position: 'RP',  number: 40, ba: '-',    hr: '-', rbi: '-', era: '4.20', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Doug Corbett',     position: 'RP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '3.16', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Bruce Kison',      position: 'RP',  number: 32, ba: '-',    hr: '-', rbi: '-', era: '3.38', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Curt Kaufman',     position: 'RP',  number: 48, ba: '-',    hr: '-', rbi: '-', era: '4.97', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Juan Beniquez',    position: 'OF',  number: 7,  ba: '.336', hr: 6,  rbi: 32,  era: '-',    role: 'Bench/Speedster',      rarity: 'uncommon' },
    { id: 20, name: 'Rob Wilfong',      position: '2B',  number: 14, ba: '.259', hr: 5,  rbi: 29,  era: '-',    role: 'Backup Infielder',     rarity: 'common'   },
    { id: 21, name: 'Rick Burleson',    position: 'SS',  number: 1,  ba: '.230', hr: 2,  rbi: 12,  era: '-',    role: 'Backup Shortstop',     rarity: 'common'   },
    { id: 22, name: 'Daryl Sconiers',   position: '1B',  number: 21, ba: '.240', hr: 4,  rbi: 19,  era: '-',    role: 'Backup First Base',    rarity: 'common'   },
    { id: 23, name: 'Derrel Thomas',    position: 'UT',  number: 6,  ba: '.239', hr: 3,  rbi: 14,  era: '-',    role: 'Utility Player',       rarity: 'common'   },
    { id: 24, name: 'Jerry Narron',    position: 'C',   number: 14, ba: '.247', hr: 3,  rbi: 17,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 25, name: 'Jim Slaton',      position: 'RP',  number: 30, ba: '-',    hr: '-', rbi: '-', era: '4.97', role: 'Relief/Veteran',        rarity: 'uncommon' },
  ],

  whitesox: [
    { id: 1,  name: 'Carlton Fisk',     position: 'C',   number: 72, ba: '.231', hr: 21, rbi: 43,  era: '-',    role: 'Catcher/HOF',          rarity: 'rare'     },
    { id: 2,  name: 'Harold Baines',    position: 'RF',  number: 3,  ba: '.304', hr: 29, rbi: 94,  era: '-',    role: 'Right Field/Clutch',   rarity: 'rare'     },
    { id: 3,  name: 'Tom Seaver',       position: 'SP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '3.95', role: 'Starting Pitcher/HOF', rarity: 'rare'     },
    { id: 4,  name: 'LaMarr Hoyt',      position: 'SP',  number: 29, ba: '-',    hr: '-', rbi: '-', era: '4.47', role: 'Ace/Cy Young',         rarity: 'uncommon' },
    { id: 5,  name: 'Greg Walker',      position: '1B',  number: 29, ba: '.294', hr: 24, rbi: 75,  era: '-',    role: 'First Base',           rarity: 'uncommon' },
    { id: 6,  name: 'Ron Kittle',       position: 'LF',  number: 45, ba: '.215', hr: 32, rbi: 74,  era: '-',    role: 'Left Field/Power',     rarity: 'uncommon' },
    { id: 7,  name: 'Greg Luzinski',    position: 'DH',  number: 19, ba: '.238', hr: 13, rbi: 58,  era: '-',    role: 'Designated Hitter/Bull', rarity: 'uncommon' },
    { id: 8,  name: 'Vance Law',        position: '3B',  number: 11, ba: '.252', hr: 7,  rbi: 59,  era: '-',    role: 'Third Base',           rarity: 'common'   },
    { id: 9,  name: 'Scott Fletcher',   position: 'SS',  number: 22, ba: '.261', hr: 3,  rbi: 35,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 10, name: 'Rudy Law',         position: 'CF',  number: 8,  ba: '.251', hr: 3,  rbi: 37,  era: '-',    role: 'Center Field/Leadoff', rarity: 'common'   },
    { id: 11, name: 'Julio Cruz',       position: '2B',  number: 12, ba: '.222', hr: 1,  rbi: 23,  era: '-',    role: 'Second Base/Speed',    rarity: 'common'   },
    { id: 12, name: 'Richard Dotson',   position: 'SP',  number: 30, ba: '-',    hr: '-', rbi: '-', era: '3.59', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 13, name: 'Floyd Bannister',  position: 'SP',  number: 43, ba: '-',    hr: '-', rbi: '-', era: '4.83', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Ron Reed',         position: 'CL',  number: 38, ba: '-',    hr: '-', rbi: '-', era: '4.00', role: 'Closer',               rarity: 'common'   },
    { id: 15, name: 'Juan Agosto',      position: 'RP',  number: 36, ba: '-',    hr: '-', rbi: '-', era: '2.36', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Gene Nelson',      position: 'RP',  number: 48, ba: '-',    hr: '-', rbi: '-', era: '3.99', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Salome Barojas',   position: 'RP',  number: 44, ba: '-',    hr: '-', rbi: '-', era: '4.26', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Dan Spillner',     position: 'RP',  number: 34, ba: '-',    hr: '-', rbi: '-', era: '4.33', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Tom Paciorek',     position: '1B',  number: 6,  ba: '.281', hr: 8,  rbi: 49,  era: '-',    role: 'Bench/First Base',     rarity: 'common'   },
    { id: 20, name: 'Jerry Hairston',   position: 'OF',  number: 15, ba: '.267', hr: 2,  rbi: 22,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 22, name: 'Marc Hill',        position: 'C',   number: 16, ba: '.219', hr: 4,  rbi: 14,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 23, name: 'Joel Skinner',     position: 'C',   number: 7,  ba: '.194', hr: 2,  rbi: 8,   era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 24, name: 'Mike Squires',      position: '1B',  number: 25, ba: '.183', hr: 1,  rbi: 6,   era: '-',    role: 'Bench/Defensive Specialist', rarity: 'common' },
    { id: 25, name: 'Jerry Dybzinski',   position: 'SS',  number: 14, ba: '.235', hr: 1,  rbi: 10,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
    { id: 26, name: 'Britt Burns',       position: 'RP',  number: 23, ba: '-',    hr: '-', rbi: '-', era: '5.00', role: 'Relief/Swingman',       rarity: 'uncommon' },
  ],

  mariners: [
    { id: 1,  name: 'Mark Langston',    position: 'SP',  number: 12, ba: '-',    hr: '-', rbi: '-', era: '3.40', role: 'Ace/Future Phenom',    rarity: 'rare'     },
    { id: 2,  name: 'Alvin Davis',      position: '1B',  number: 14, ba: '.284', hr: 27, rbi: 116, era: '-',    role: 'Rookie of the Year',   rarity: 'rare'     },
    { id: 3,  name: 'Phil Bradley',     position: 'LF',  number: 11, ba: '.301', hr: 14, rbi: 52,  era: '-',    role: 'Left Field',           rarity: 'uncommon' },
    { id: 4,  name: 'Dave Henderson',   position: 'CF',  number: 40, ba: '.280', hr: 14, rbi: 58,  era: '-',    role: 'Center Field',         rarity: 'uncommon' },
    { id: 5,  name: 'Ken Phelps',       position: 'DH',  number: 22, ba: '.241', hr: 24, rbi: 54,  era: '-',    role: 'Designated Hitter/Power', rarity: 'uncommon' },
    { id: 6,  name: 'Jack Perconte',    position: '2B',  number: 15, ba: '.294', hr: 1,  rbi: 27,  era: '-',    role: 'Second Base/Leadoff',  rarity: 'common'   },
    { id: 7,  name: 'Jim Presley',      position: '3B',  number: 36, ba: '.227', hr: 10, rbi: 36,  era: '-',    role: 'Third Base/Future Star', rarity: 'common'  },
    { id: 8,  name: 'Al Cowens',        position: 'RF',  number: 24, ba: '.268', hr: 6,  rbi: 51,  era: '-',    role: 'Right Field',          rarity: 'common'   },
    { id: 9,  name: 'Bob Kearney',      position: 'C',   number: 18, ba: '.211', hr: 8,  rbi: 34,  era: '-',    role: 'Catcher',              rarity: 'common'   },
    { id: 10, name: 'Spike Owen',       position: 'SS',  number: 3,  ba: '.245', hr: 3,  rbi: 37,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 11, name: 'Mike Moore',       position: 'SP',  number: 17, ba: '-',    hr: '-', rbi: '-', era: '4.97', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 12, name: 'Jim Beattie',      position: 'SP',  number: 30, ba: '-',    hr: '-', rbi: '-', era: '4.42', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 13, name: 'Matt Young',       position: 'SP',  number: 33, ba: '-',    hr: '-', rbi: '-', era: '4.91', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Mike Stanton',     position: 'CL',  number: 39, ba: '-',    hr: '-', rbi: '-', era: '4.00', role: 'Closer',               rarity: 'common'   },
    { id: 15, name: 'Edwin Nunez',      position: 'RP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '4.98', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Dave Beard',       position: 'RP',  number: 45, ba: '-',    hr: '-', rbi: '-', era: '4.72', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Paul Mirabella',   position: 'RP',  number: 47, ba: '-',    hr: '-', rbi: '-', era: '5.02', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Bob Stoddard',     position: 'RP',  number: 48, ba: '-',    hr: '-', rbi: '-', era: '5.31', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Ed Vande Berg',    position: 'RP',  number: 50, ba: '-',    hr: '-', rbi: '-', era: '3.02', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 20, name: 'Gorman Thomas',    position: 'DH',  number: 20, ba: '.215', hr: 32, rbi: 87,  era: '-',    role: 'Bench/Power',          rarity: 'uncommon' },
    { id: 21, name: 'Barry Bonnell',    position: 'OF',  number: 16, ba: '.265', hr: 4,  rbi: 21,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 22, name: 'Steve Henderson',  position: 'OF',  number: 25, ba: '.259', hr: 4,  rbi: 22,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 23, name: 'Orlando Mercado',  position: 'C',   number: 8,  ba: '.209', hr: 1,  rbi: 6,   era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 24, name: 'Domingo Ramos',    position: 'SS',  number: 6,  ba: '.218', hr: 1,  rbi: 9,   era: '-',    role: 'Backup Infielder',     rarity: 'common'   },
    { id: 25, name: 'Larry Milbourne',  position: '3B',  number: 10, ba: '.265', hr: 1,  rbi: 22,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
  ],

  rangers: [
    { id: 1,  name: 'Charlie Hough',    position: 'SP',  number: 49, ba: '-',    hr: '-', rbi: '-', era: '3.79', role: 'Ace/Knuckleballer',    rarity: 'rare'     },
    { id: 2,  name: 'Buddy Bell',       position: '3B',  number: 25, ba: '.315', hr: 11, rbi: 83,  era: '-',    role: 'Third Base/Gold Glove', rarity: 'rare'    },
    { id: 3,  name: 'Larry Parrish',    position: 'DH',  number: 14, ba: '.285', hr: 22, rbi: 80,  era: '-',    role: 'Designated Hitter/Power', rarity: 'uncommon' },
    { id: 4,  name: 'Gary Ward',        position: 'RF',  number: 12, ba: '.284', hr: 21, rbi: 79,  era: '-',    role: 'Right Field',           rarity: 'uncommon' },
    { id: 5,  name: 'Pete O\'Brien',    position: '1B',  number: 23, ba: '.287', hr: 18, rbi: 80,  era: '-',    role: 'First Base',           rarity: 'uncommon' },
    { id: 6,  name: 'Mickey Rivers',    position: 'DH',  number: 7,  ba: '.279', hr: 3,  rbi: 35,  era: '-',    role: 'Designated Hitter',    rarity: 'common'   },
    { id: 7,  name: 'Wayne Tolleson',   position: '2B',  number: 2,  ba: '.213', hr: 1,  rbi: 24,  era: '-',    role: 'Second Base',          rarity: 'common'   },
    { id: 8,  name: 'Billy Sample',     position: 'LF',  number: 19, ba: '.265', hr: 8,  rbi: 45,  era: '-',    role: 'Left Field',           rarity: 'common'   },
    { id: 9,  name: 'Donnie Scott',     position: 'C',   number: 5,  ba: '.229', hr: 4,  rbi: 23,  era: '-',    role: 'Catcher',              rarity: 'common'   },
    { id: 10, name: 'Curtis Wilkerson', position: 'SS',  number: 26, ba: '.236', hr: 1,  rbi: 26,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 11, name: 'Frank Tanana',     position: 'SP',  number: 32, ba: '-',    hr: '-', rbi: '-', era: '3.25', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 12, name: 'Danny Darwin',     position: 'SP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '3.94', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 13, name: 'Mike Mason',       position: 'SP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '3.61', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Dave Schmidt',     position: 'CL',  number: 28, ba: '-',    hr: '-', rbi: '-', era: '3.13', role: 'Closer',               rarity: 'common'   },
    { id: 15, name: 'Dave Stewart',     position: 'RP',  number: 36, ba: '-',    hr: '-', rbi: '-', era: '4.73', role: 'Relief Pitcher/Future Ace', rarity: 'uncommon' },
    { id: 16, name: 'Tom Henke',        position: 'RP',  number: 47, ba: '-',    hr: '-', rbi: '-', era: '6.35', role: 'Relief Pitcher/Future Closer', rarity: 'uncommon' },
    { id: 17, name: 'Odell Jones',      position: 'RP',  number: 35, ba: '-',    hr: '-', rbi: '-', era: '3.86', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Dave Tobik',       position: 'RP',  number: 44, ba: '-',    hr: '-', rbi: '-', era: '5.30', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Jim Bibby',        position: 'SP',  number: 31, ba: '-',    hr: '-', rbi: '-', era: '4.09', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 20, name: 'George Wright',    position: 'CF',  number: 9,  ba: '.246', hr: 5,  rbi: 35,  era: '-',    role: 'Center Field',          rarity: 'common'   },
    { id: 20, name: 'Tommy Dunbar',     position: 'OF',  number: 16, ba: '.252', hr: 6,  rbi: 24,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 21, name: 'Ned Yost',         position: 'C',   number: 34, ba: '.182', hr: 2,  rbi: 7,   era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 23, name: 'Dave Hostetler',   position: '1B',  number: 21, ba: '.209', hr: 8,  rbi: 22,  era: '-',    role: 'Bench/Power',          rarity: 'common'   },
    { id: 24, name: 'Bob Jones',        position: 'OF',  number: 34, ba: '.259', hr: 4,  rbi: 22,  era: '-',    role: 'Bench/Utility',        rarity: 'common'   },
    { id: 25, name: 'Jeff Kunkel',      position: 'C',   number: 10, ba: '.221', hr: 2,  rbi: 7,   era: '-',    role: 'Bench/Rookie Catcher', rarity: 'uncommon' },
  ],

  expos: [
    { id: 1,  name: 'Tim Raines',       position: 'CF',  number: 30, ba: '.309', hr: 8,  rbi: 60,  era: '-',    role: 'Leadoff/Rock Solid',   rarity: 'rare'     },
    { id: 2,  name: 'Gary Carter',      position: 'C',   number: 8,  ba: '.294', hr: 27, rbi: 106, era: '-',    role: 'Catcher/HOF/Kid',      rarity: 'rare'     },
    { id: 3,  name: 'Andre Dawson',     position: 'RF',  number: 10, ba: '.255', hr: 17, rbi: 86,  era: '-',    role: 'Right Field/HOF',      rarity: 'rare'     },
    { id: 4,  name: 'Jeff Reardon',     position: 'CL',  number: 42, ba: '-',    hr: '-', rbi: '-', era: '2.90', role: 'Closer/The Terminator',rarity: 'uncommon' },
    { id: 5,  name: 'Tim Wallach',      position: '3B',  number: 29, ba: '.246', hr: 18, rbi: 72,  era: '-',    role: 'Third Base',           rarity: 'uncommon' },
    { id: 6,  name: 'Terry Francona',   position: '1B',  number: 12, ba: '.346', hr: 1,  rbi: 18,  era: '-',    role: 'First Base/Future Mgr',rarity: 'uncommon' },
    { id: 7,  name: 'Bryn Smith',       position: 'SP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '2.91', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 8,  name: 'Jim Wohlford',     position: 'LF',  number: 26, ba: '.285', hr: 2,  rbi: 20,  era: '-',    role: 'Left Field',           rarity: 'common'   },
    { id: 9,  name: 'Doug Flynn',       position: '2B',  number: 15, ba: '.237', hr: 3,  rbi: 25,  era: '-',    role: 'Second Base',          rarity: 'common'   },
    { id: 10, name: 'Angel Salazar',    position: 'SS',  number: 14, ba: '.205', hr: 0,  rbi: 16,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 11, name: 'Charlie Lea',      position: 'SP',  number: 31, ba: '-',    hr: '-', rbi: '-', era: '2.89', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 12, name: 'Steve Rogers',     position: 'SP',  number: 45, ba: '-',    hr: '-', rbi: '-', era: '4.31', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 13, name: 'Bill Gullickson',  position: 'SP',  number: 33, ba: '-',    hr: '-', rbi: '-', era: '3.61', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Gary Lucas',       position: 'RP',  number: 35, ba: '-',    hr: '-', rbi: '-', era: '3.83', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 15, name: 'Bob James',        position: 'RP',  number: 40, ba: '-',    hr: '-', rbi: '-', era: '2.90', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Andy McGaffigan',  position: 'RP',  number: 38, ba: '-',    hr: '-', rbi: '-', era: '4.00', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Joe Hesketh',      position: 'RP',  number: 44, ba: '-',    hr: '-', rbi: '-', era: '1.80', role: 'Relief Pitcher',       rarity: 'uncommon' },
    { id: 18, name: 'Chris Speier',     position: 'SS',  number: 6,  ba: '.253', hr: 9,  rbi: 45,  era: '-',    role: 'Backup Shortstop',     rarity: 'common'   },
    { id: 19, name: 'Mike Stenhouse',   position: '1B',  number: 17, ba: '.230', hr: 4,  rbi: 16,  era: '-',    role: 'Bench/First Base',     rarity: 'common'   },
    { id: 20, name: 'Tony Scott',       position: 'OF',  number: 18, ba: '.240', hr: 1,  rbi: 10,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 21, name: 'Bryan Little',     position: '2B',  number: 11, ba: '.248', hr: 1,  rbi: 11,  era: '-',    role: 'Backup Infielder',     rarity: 'common'   },
    { id: 22, name: 'Razor Shines',     position: '1B',  number: 27, ba: '.220', hr: 2,  rbi: 9,   era: '-',    role: 'Bench/First Base',     rarity: 'common'   },
    { id: 23, name: 'Miguel Dilone',    position: 'OF',  number: 6,  ba: '.278', hr: 1,  rbi: 15,  era: '-',    role: 'Bench Outfielder/Speed',rarity: 'common'   },
    { id: 24, name: 'David Palmer',     position: 'RP',  number: 46, ba: '-',    hr: '-', rbi: '-', era: '3.84', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 25, name: 'Dan Schatzeder',   position: 'RP',  number: 45, ba: '-',    hr: '-', rbi: '-', era: '2.71', role: 'Relief Pitcher/Starter', rarity: 'common'   },
  ],

  cardinals: [
    { id: 1,  name: 'Ozzie Smith',      position: 'SS',  number: 1,  ba: '.257', hr: 1,  rbi: 44,  era: '-',    role: 'Shortstop/The Wizard', rarity: 'rare'     },
    { id: 2,  name: 'Bruce Sutter',     position: 'CL',  number: 42, ba: '-',    hr: '-', rbi: '-', era: '1.54', role: 'Closer/HOF Splitter',  rarity: 'rare'     },
    { id: 3,  name: 'Joaquin Andujar',  position: 'SP',  number: 47, ba: '-',    hr: '-', rbi: '-', era: '3.34', role: 'Ace/One Tough Dominican', rarity: 'rare'  },
    { id: 4,  name: 'Willie McGee',     position: 'CF',  number: 51, ba: '.291', hr: 6,  rbi: 50,  era: '-',    role: 'Center Field/MVP',     rarity: 'rare'     },
    { id: 5,  name: 'George Hendrick',  position: '1B',  number: 25, ba: '.277', hr: 9,  rbi: 69,  era: '-',    role: 'First Base',           rarity: 'common'   },
    { id: 7,  name: 'Ken Oberkfell',    position: '3B',  number: 26, ba: '.293', hr: 5,  rbi: 50,  era: '-',    role: 'Third Base',           rarity: 'common'   },
    { id: 8,  name: 'Tom Herr',         position: '2B',  number: 28, ba: '.281', hr: 4,  rbi: 49,  era: '-',    role: 'Second Base',          rarity: 'common'   },
    { id: 9,  name: 'Lonnie Smith',     position: 'RF',  number: 27, ba: '.250', hr: 4,  rbi: 30,  era: '-',    role: 'Right Field/Skates',   rarity: 'common'   },
    { id: 10, name: 'Darrell Porter',   position: 'C',   number: 15, ba: '.232', hr: 11, rbi: 68,  era: '-',    role: 'Catcher/WS Hero',      rarity: 'uncommon' },
    { id: 11, name: 'Kurt Kepshire',    position: 'SP',  number: 40, ba: '-',    hr: '-', rbi: '-', era: '3.99', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 12, name: 'Dave LaPoint',     position: 'SP',  number: 43, ba: '-',    hr: '-', rbi: '-', era: '4.03', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 13, name: 'Neil Allen',       position: 'RP',  number: 39, ba: '-',    hr: '-', rbi: '-', era: '4.50', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 14, name: 'Jeff Lahti',       position: 'RP',  number: 34, ba: '-',    hr: '-', rbi: '-', era: '2.93', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 15, name: 'Ralph Citarella',  position: 'RP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '5.40', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Mike Jorgensen',   position: '1B',  number: 13, ba: '.248', hr: 5,  rbi: 22,  era: '-',    role: 'Bench/First Base',     rarity: 'common'   },
    { id: 17, name: 'Tom Nieto',        position: 'C',   number: 8,  ba: '.217', hr: 2,  rbi: 10,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 18, name: 'Terry Pendleton',  position: '3B',  number: 18, ba: '.244', hr: 5,  rbi: 32,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
    { id: 19, name: 'Tito Landrum',     position: 'OF',  number: 20, ba: '.253', hr: 3,  rbi: 18,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 20, name: 'Andy Van Slyke',   position: 'OF',  number: 21, ba: '.261', hr: 6,  rbi: 31,  era: '-',    role: 'Bench/Future Star',    rarity: 'uncommon' },
    { id: 21, name: 'David Green',      position: '1B',  number: 22, ba: '.259', hr: 4,  rbi: 19,  era: '-',    role: 'Bench/First Base',     rarity: 'common'   },
    { id: 22, name: 'Bob Forsch',       position: 'SP',  number: 32, ba: '-',    hr: '-', rbi: '-', era: '4.03', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 23, name: 'John Stuper',      position: 'SP',  number: 38, ba: '-',    hr: '-', rbi: '-', era: '4.18', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 24, name: 'Danny Cox',        position: 'SP',  number: 31, ba: '-',    hr: '-', rbi: '-', era: '3.92', role: 'Starting Pitcher',     rarity: 'common'   },
  ],

  pirates: [
    { id: 1,  name: 'Tony Pena',        position: 'C',   number: 6,  ba: '.286', hr: 15, rbi: 78,  era: '-',    role: 'Catcher/One-Knee Legend', rarity: 'rare'   },
    { id: 2,  name: 'Bill Madlock',     position: '3B',  number: 26, ba: '.253', hr: 10, rbi: 44,  era: '-',    role: 'Third Base/Batting Champ', rarity: 'rare'  },
    { id: 3,  name: 'Kent Tekulve',     position: 'CL',  number: 27, ba: '-',    hr: '-', rbi: '-', era: '2.54', role: 'Closer/Submarine',     rarity: 'uncommon' },
    { id: 4,  name: 'Rick Rhoden',      position: 'SP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '2.72', role: 'Ace Pitcher',          rarity: 'uncommon' },
    { id: 5,  name: 'Johnny Ray',       position: '2B',  number: 2,  ba: '.292', hr: 5,  rbi: 67,  era: '-',    role: 'Second Base',          rarity: 'uncommon' },
    { id: 6,  name: 'Lee Lacy',         position: 'LF',  number: 14, ba: '.321', hr: 12, rbi: 70,  era: '-',    role: 'Left Field',           rarity: 'uncommon' },
    { id: 7,  name: 'John Candelaria',  position: 'SP',  number: 45, ba: '-',    hr: '-', rbi: '-', era: '2.72', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 8,  name: 'Jason Thompson',   position: '1B',  number: 15, ba: '.213', hr: 14, rbi: 62,  era: '-',    role: 'First Base',           rarity: 'common'   },
    { id: 9,  name: 'Marvell Wynne',    position: 'CF',  number: 22, ba: '.243', hr: 6,  rbi: 39,  era: '-',    role: 'Center Field',         rarity: 'common'   },
    { id: 10, name: 'Doug Frobel',      position: 'RF',  number: 33, ba: '.235', hr: 12, rbi: 28,  era: '-',    role: 'Right Field',          rarity: 'common'   },
    { id: 11, name: 'Dale Berra',       position: 'SS',  number: 3,  ba: '.245', hr: 10, rbi: 52,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 12, name: 'John Tudor',       position: 'SP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '3.27', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 13, name: 'Jose DeLeon',      position: 'SP',  number: 49, ba: '-',    hr: '-', rbi: '-', era: '3.74', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Don Robinson',     position: 'RP',  number: 43, ba: '-',    hr: '-', rbi: '-', era: '3.03', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 15, name: 'Rod Scurry',       position: 'RP',  number: 30, ba: '-',    hr: '-', rbi: '-', era: '4.91', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Cecilio Guante',   position: 'RP',  number: 35, ba: '-',    hr: '-', rbi: '-', era: '2.53', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Lee Tunnell',      position: 'RP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '4.76', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Lee Mazzilli',     position: 'OF',  number: 16, ba: '.260', hr: 5,  rbi: 26,  era: '-',    role: 'Bench/Outfield',       rarity: 'common'   },
    { id: 19, name: 'Brian Harper',     position: 'C',   number: 11, ba: '.265', hr: 4,  rbi: 22,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 20, name: 'Jim Morrison',     position: 'IF',  number: 13, ba: '.252', hr: 11, rbi: 39,  era: '-',    role: 'Utility Infielder',    rarity: 'common'   },
    { id: 21, name: 'Joe Orsulak',      position: 'OF',  number: 17, ba: '.249', hr: 1,  rbi: 15,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 22, name: 'Benny Distefano',  position: '1B',  number: 28, ba: '.235', hr: 2,  rbi: 10,  era: '-',    role: 'Bench/First Base',     rarity: 'common'   },
    { id: 23, name: 'Amos Otis',        position: 'OF',  number: 26, ba: '.245', hr: 8,  rbi: 35,  era: '-',    role: 'Bench Outfielder/Veteran', rarity: 'common' },
    { id: 24, name: 'Bob Walk',         position: 'SP',  number: 38, ba: '-',    hr: '-', rbi: '-', era: '3.76', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 25, name: 'Larry McWilliams', position: 'SP',  number: 49, ba: '-',    hr: '-', rbi: '-', era: '4.22', role: 'Starting Pitcher',     rarity: 'common'   },
  ],

  braves: [
    { id: 1,  name: 'Dale Murphy',      position: 'CF',  number: 3,  ba: '.290', hr: 36, rbi: 100, era: '-',    role: 'Center Field/Back-to-Back MVP', rarity: 'rare' },
    { id: 2,  name: 'Bob Horner',       position: '3B',  number: 5,  ba: '.271', hr: 24, rbi: 70,  era: '-',    role: 'Third Base/Power',     rarity: 'uncommon' },
    { id: 3,  name: 'Rafael Ramirez',   position: 'SS',  number: 27, ba: '.269', hr: 2,  rbi: 52,  era: '-',    role: 'Shortstop',            rarity: 'uncommon' },
    { id: 4,  name: 'Chris Chambliss',  position: '1B',  number: 10, ba: '.275', hr: 11, rbi: 44,  era: '-',    role: 'First Base/Veteran',   rarity: 'uncommon' },
    { id: 5,  name: 'Claudell Washington', position: 'RF', number: 13, ba: '.280', hr: 17, rbi: 61, era: '-', role: 'Right Field',          rarity: 'uncommon' },
    { id: 6,  name: 'Glenn Hubbard',    position: '2B',  number: 18, ba: '.240', hr: 8,  rbi: 43,  era: '-',    role: 'Second Base',          rarity: 'common'   },
    { id: 7,  name: 'Gerald Perry',     position: 'LF',  number: 30, ba: '.238', hr: 7,  rbi: 26,  era: '-',    role: 'Left Field',           rarity: 'common'   },
    { id: 8,  name: 'Randy Johnson',    position: '3B',  number: 4,  ba: '.260', hr: 5,  rbi: 34,  era: '-',    role: 'Third Base/Utility',   rarity: 'common'   },
    { id: 9,  name: 'Bruce Benedict',   position: 'C',   number: 22, ba: '.220', hr: 2,  rbi: 25,  era: '-',    role: 'Catcher',              rarity: 'common'   },
    { id: 10, name: 'Pascual Perez',    position: 'SP',  number: 34, ba: '-',    hr: '-', rbi: '-', era: '3.74', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 11, name: 'Rick Mahler',      position: 'SP',  number: 36, ba: '-',    hr: '-', rbi: '-', era: '3.12', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 12, name: 'Craig McMurtry',   position: 'SP',  number: 40, ba: '-',    hr: '-', rbi: '-', era: '4.32', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 13, name: 'Len Barker',       position: 'SP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '4.01', role: 'Starting Pitcher/Perfect Game', rarity: 'common' },
    { id: 14, name: 'Donnie Moore',     position: 'CL',  number: 27, ba: '-',    hr: '-', rbi: '-', era: '2.94', role: 'Closer',               rarity: 'uncommon' },
    { id: 15, name: 'Steve Bedrosian',  position: 'RP',  number: 45, ba: '-',    hr: '-', rbi: '-', era: '4.42', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Gene Garber',      position: 'RP',  number: 26, ba: '-',    hr: '-', rbi: '-', era: '3.53', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Terry Forster',    position: 'RP',  number: 29, ba: '-',    hr: '-', rbi: '-', era: '4.50', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Jeff Dedmon',      position: 'RP',  number: 46, ba: '-',    hr: '-', rbi: '-', era: '4.62', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Alex Trevino',     position: 'C',   number: 11, ba: '.229', hr: 4,  rbi: 18,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 20, name: 'Jerry Royster',    position: 'UT',  number: 6,  ba: '.260', hr: 2,  rbi: 19,  era: '-',    role: 'Utility Player',       rarity: 'common'   },
    { id: 21, name: 'Brad Komminsk',    position: 'OF',  number: 21, ba: '.202', hr: 8,  rbi: 28,  era: '-',    role: 'Outfield/Future Star', rarity: 'common'   },
    { id: 22, name: 'Milt Thompson',    position: 'OF',  number: 23, ba: '.257', hr: 2,  rbi: 14,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 23, name: 'Albert Hall',      position: 'OF',  number: 24, ba: '.267', hr: 1,  rbi: 12,  era: '-',    role: 'Bench Outfielder/Speed', rarity: 'common' },
    { id: 24, name: 'Pete Falcone',     position: 'SP',  number: 38, ba: '-',    hr: '-', rbi: '-', era: '4.76', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 25, name: 'Rick Camp',        position: 'RP',  number: 42, ba: '-',    hr: '-', rbi: '-', era: '4.09', role: 'Relief Pitcher',       rarity: 'common'   },
  ],

  astros: [
    { id: 1,  name: 'Nolan Ryan',       position: 'SP',  number: 34, ba: '-',    hr: '-', rbi: '-', era: '3.04', role: 'The Ryan Express/HOF', rarity: 'rare'     },
    { id: 2,  name: 'Jose Cruz',        position: 'LF',  number: 25, ba: '.312', hr: 12, rbi: 95,  era: '-',    role: 'Left Field/Fan Favorite', rarity: 'rare'   },
    { id: 3,  name: 'Joe Niekro',       position: 'SP',  number: 36, ba: '-',    hr: '-', rbi: '-', era: '3.04', role: 'Starting Pitcher/Knuckler', rarity: 'uncommon' },
    { id: 4,  name: 'Enos Cabell',      position: '1B',  number: 15, ba: '.310', hr: 8,  rbi: 44,  era: '-',    role: 'First Base',           rarity: 'uncommon' },
    { id: 5,  name: 'Terry Puhl',       position: 'RF',  number: 21, ba: '.301', hr: 9,  rbi: 55,  era: '-',    role: 'Right Field',          rarity: 'uncommon' },
    { id: 6,  name: 'Bill Doran',       position: '2B',  number: 20, ba: '.271', hr: 9,  rbi: 41,  era: '-',    role: 'Second Base',          rarity: 'common'   },
    { id: 7,  name: 'Phil Garner',      position: '3B',  number: 13, ba: '.278', hr: 11, rbi: 53,  era: '-',    role: 'Third Base/Scrap Iron', rarity: 'uncommon' },
    { id: 8,  name: 'Jerry Mumphrey',   position: 'CF',  number: 18, ba: '.290', hr: 9,  rbi: 83,  era: '-',    role: 'Center Field',         rarity: 'common'   },
    { id: 9,  name: 'Mark Bailey',      position: 'C',   number: 16, ba: '.211', hr: 5,  rbi: 34,  era: '-',    role: 'Catcher',              rarity: 'common'   },
    { id: 10, name: 'Craig Reynolds',   position: 'SS',  number: 12, ba: '.249', hr: 3,  rbi: 33,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 11, name: 'Mike Scott',       position: 'SP',  number: 33, ba: '-',    hr: '-', rbi: '-', era: '4.68', role: 'Starting Pitcher/Future Cy Young', rarity: 'uncommon' },
    { id: 12, name: 'Bob Knepper',      position: 'SP',  number: 40, ba: '-',    hr: '-', rbi: '-', era: '3.20', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 13, name: 'Frank DiPino',     position: 'CL',  number: 32, ba: '-',    hr: '-', rbi: '-', era: '3.35', role: 'Closer',               rarity: 'common'   },
    { id: 14, name: 'Dave Smith',       position: 'RP',  number: 38, ba: '-',    hr: '-', rbi: '-', era: '2.21', role: 'Relief Pitcher',       rarity: 'uncommon' },
    { id: 15, name: 'Bill Dawley',      position: 'RP',  number: 35, ba: '-',    hr: '-', rbi: '-', era: '3.84', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Vern Ruhle',       position: 'RP',  number: 27, ba: '-',    hr: '-', rbi: '-', era: '3.40', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Julio Solano',     position: 'RP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '3.77', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Alan Ashby',       position: 'C',   number: 14, ba: '.255', hr: 10, rbi: 43,  era: '-',    role: 'Backup Catcher',       rarity: 'common'   },
    { id: 19, name: 'Kevin Bass',       position: 'OF',  number: 16, ba: '.272', hr: 16, rbi: 68,  era: '-',    role: 'Outfield/Future Star', rarity: 'uncommon' },
    { id: 20, name: 'Denny Walling',    position: '3B',  number: 11, ba: '.286', hr: 6,  rbi: 30,  era: '-',    role: 'Bench/Utility',        rarity: 'common'   },
    { id: 21, name: 'Dickie Thon',      position: 'SS',  number: 5,  ba: '.251', hr: 6,  rbi: 29,  era: '-',    role: 'Shortstop/Recovery',   rarity: 'uncommon' },
    { id: 22, name: 'Ray Knight',       position: '3B',  number: 7,  ba: '.250', hr: 4,  rbi: 24,  era: '-',    role: 'Bench/Utility',        rarity: 'common'   },
    { id: 23, name: 'Jim Pankovits',    position: 'OF',  number: 19, ba: '.245', hr: 3,  rbi: 18,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
    { id: 24, name: 'Mike Madden',      position: 'SP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '4.52', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 25, name: 'Mike LaCoss',      position: 'SP',  number: 42, ba: '-',    hr: '-', rbi: '-', era: '4.01', role: 'Starting Pitcher',     rarity: 'common'   },
  ],

  giants: [
    { id: 1,  name: 'Jack Clark',       position: 'RF',  number: 22, ba: '.320', hr: 11, rbi: 44,  era: '-',    role: 'Right Field/Jack the Ripper', rarity: 'rare' },
    { id: 2,  name: 'Chili Davis',      position: 'CF',  number: 3,  ba: '.315', hr: 21, rbi: 81,  era: '-',    role: 'Center Field',         rarity: 'rare'     },
    { id: 3,  name: 'Jeff Leonard',     position: 'LF',  number: 28, ba: '.288', hr: 21, rbi: 86,  era: '-',    role: 'Left Field/Hackman',   rarity: 'uncommon' },
    { id: 4,  name: 'Bob Brenly',       position: 'C',   number: 14, ba: '.291', hr: 20, rbi: 80,  era: '-',    role: 'Catcher/Underrated',   rarity: 'uncommon' },
    { id: 5,  name: 'Al Oliver',        position: '1B',  number: 29, ba: '.279', hr: 12, rbi: 57,  era: '-',    role: 'First Base/PH Legend', rarity: 'uncommon' },
    { id: 6,  name: 'Joel Youngblood',  position: '3B',  number: 8,  ba: '.280', hr: 8,  rbi: 31,  era: '-',    role: 'Third Base/Versatile', rarity: 'common'   },
    { id: 7,  name: 'Manny Trillo',     position: '2B',  number: 7,  ba: '.254', hr: 4,  rbi: 36,  era: '-',    role: 'Second Base',          rarity: 'common'   },
    { id: 8,  name: 'Johnnie LeMaster', position: 'SS',  number: 9,  ba: '.210', hr: 3,  rbi: 24,  era: '-',    role: 'Shortstop',            rarity: 'common'   },
    { id: 9,  name: 'Dan Gladden',      position: 'OF',  number: 11, ba: '.351', hr: 4,  rbi: 31,  era: '-',    role: 'Bench/Future Star',    rarity: 'uncommon' },
    { id: 10, name: 'Greg Minton',      position: 'CL',  number: 39, ba: '-',    hr: '-', rbi: '-', era: '3.76', role: 'Closer',               rarity: 'uncommon' },
    { id: 11, name: 'Mike Krukow',      position: 'SP',  number: 34, ba: '-',    hr: '-', rbi: '-', era: '4.56', role: 'Starting Pitcher',     rarity: 'uncommon' },
    { id: 12, name: 'Mark Davis',       position: 'SP',  number: 33, ba: '-',    hr: '-', rbi: '-', era: '3.58', role: 'Starting Pitcher/Future CY', rarity: 'uncommon' },
    { id: 13, name: 'Bill Laskey',      position: 'SP',  number: 43, ba: '-',    hr: '-', rbi: '-', era: '4.33', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 14, name: 'Jeff Robinson',    position: 'SP',  number: 37, ba: '-',    hr: '-', rbi: '-', era: '4.56', role: 'Starting Pitcher',     rarity: 'common'   },
    { id: 15, name: 'Gary Lavelle',     position: 'RP',  number: 46, ba: '-',    hr: '-', rbi: '-', era: '2.76', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 16, name: 'Scott Garrelts',   position: 'RP',  number: 47, ba: '-',    hr: '-', rbi: '-', era: '3.56', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 17, name: 'Frank Williams',   position: 'RP',  number: 48, ba: '-',    hr: '-', rbi: '-', era: '3.00', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 18, name: 'Bob Lacey',        position: 'RP',  number: 41, ba: '-',    hr: '-', rbi: '-', era: '4.95', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 19, name: 'Dusty Baker',      position: 'OF',  number: 12, ba: '.260', hr: 5,  rbi: 29,  era: '-',    role: 'Bench/Veteran',        rarity: 'uncommon' },
    { id: 20, name: 'Chris Brown',      position: '3B',  number: 5,  ba: '.271', hr: 7,  rbi: 31,  era: '-',    role: 'Bench/Future Star',    rarity: 'common'   },
    { id: 21, name: 'Brad Wellman',     position: 'IF',  number: 17, ba: '.214', hr: 2,  rbi: 11,  era: '-',    role: 'Backup Infielder',     rarity: 'common'   },
    { id: 22, name: 'Dan Driessen',     position: '1B',  number: 19, ba: '.265', hr: 7,  rbi: 25,  era: '-',    role: 'Bench/First Base',     rarity: 'common'   },
    { id: 23, name: 'Mark Grant',       position: 'RP',  number: 44, ba: '-',    hr: '-', rbi: '-', era: '3.84', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 24, name: 'Randy Lerch',      position: 'RP',  number: 42, ba: '-',    hr: '-', rbi: '-', era: '4.15', role: 'Relief Pitcher',       rarity: 'common'   },
    { id: 25, name: 'Gene Richards',    position: 'OF',  number: 16, ba: '.275', hr: 3,  rbi: 22,  era: '-',    role: 'Bench Outfielder',     rarity: 'common'   },
  ],

};

// Manager cards for all 26 teams
export const MANAGER_CARDS = {
  tigers:   { name: 'Sparky Anderson',  number: 11, role: 'Manager',  desc: 'Papa Sparky - led DET to 104 wins & WS title in 1984', rarity: 'rare',     icon: '🐯' },
  padres:   { name: 'Dick Williams',    number: 3,  role: 'Manager',  desc: 'Series veteran - three WS titles across his career',    rarity: 'rare',     icon: '⚾' },
  cubs:     { name: 'Jim Frey',         number: 5,  role: 'Manager',  desc: 'Guided Cubs to their first division title in 39 years',  rarity: 'uncommon', icon: '🐻' },
  mets:     { name: 'Davey Johnson',    number: 5,  role: 'Manager',  desc: 'Analytics pioneer - built the Mets dynasty',            rarity: 'uncommon', icon: '🗽' },
  redsox:   { name: 'Ralph Houk',       number: 2,  role: 'Manager',  desc: 'The Major - 3x pennant winner with the Yankees',         rarity: 'uncommon', icon: '🧦' },
  yankees:  { name: 'Yogi Berra',       number: 8,  role: 'Manager',  desc: 'Yogi-isms and all - back in the dugout for 1984',        rarity: 'rare',     icon: '🏟' },
  orioles:  { name: 'Joe Altobelli',    number: 32, role: 'Manager',  desc: 'Led Baltimore to the 1983 World Series title',           rarity: 'uncommon', icon: '🐦' },
  dodgers:  { name: 'Tommy Lasorda',    number: 2,  role: 'Manager',  desc: 'Bleeds Dodger Blue - Hall of Fame skipper',              rarity: 'rare',     icon: '💙' },
  reds:     { name: 'Pete Rose',        number: 14, role: 'Player-Manager', desc: 'Charlie Hustle - chasing the hit record',          rarity: 'rare',     icon: '🔴' },
  royals:   { name: 'Dick Howser',      number: 7,  role: 'Manager',  desc: 'Calm tactician who would win the 1985 Series',          rarity: 'uncommon', icon: '👑' },
  phillies: { name: 'Paul Owens',       number: 2,  role: 'Manager',  desc: 'The Pope - veteran baseball mind in Philadelphia',       rarity: 'common',   icon: '🔔' },
  cardinals:{ name: 'Whitey Herzog',    number: 24, role: 'Manager',  desc: 'The White Rat - master of Whitey Ball',                 rarity: 'rare',     icon: '🐦' },
  bluejays: { name: 'Bobby Cox',        number: 7,  role: 'Manager',  desc: 'Future HOF skipper - building Toronto\'s foundation',   rarity: 'uncommon', icon: '🍁' },
  indians:  { name: 'Pat Corrales',     number: 4,  role: 'Manager',  desc: 'Fiery competitor in the Cleveland dugout',              rarity: 'common',   icon: '🔴' },
  brewers:  { name: 'Rene Lachemann',   number: 12, role: 'Manager',  desc: 'Known for developing young pitchers in Milwaukee',       rarity: 'common',   icon: '🍺' },
  twins:    { name: 'Billy Gardner',    number: 25, role: 'Manager',  desc: 'Steady hand as Minnesota rebuilt in the Metrodome',     rarity: 'common',   icon: '⭐' },
  athletics:{ name: 'Steve Boros',      number: 5,  role: 'Manager',  desc: 'Oversaw a transitional Oakland squad in 1984',           rarity: 'common',   icon: '🐘' },
  angels:   { name: 'John McNamara',    number: 8,  role: 'Manager',  desc: 'Led California through the Reggie Jackson era',          rarity: 'common',   icon: '🌟' },
  whitesox: { name: 'Tony LaRussa',     number: 10, role: 'Manager',  desc: 'Future HOF - pioneer of the modern bullpen',            rarity: 'rare',     icon: '⚾' },
  mariners: { name: 'Del Crandall',     number: 3,  role: 'Manager',  desc: 'Former All-Star catcher managing in Seattle',           rarity: 'common',   icon: '🌧️' },
  rangers:  { name: 'Doug Rader',       number: 7,  role: 'Manager',  desc: 'The Rooster - intense competitor in Arlington',         rarity: 'common',   icon: '🤠' },
  expos:    { name: 'Bill Virdon',       number: 4,  role: 'Manager',  desc: 'Steady hand guiding Montreal\'s talented squad',         rarity: 'common',   icon: '⚾' },
  pirates:  { name: 'Chuck Tanner',     number: 3,  role: 'Manager',  desc: 'Won the 1979 World Series with the We Are Family Bucs', rarity: 'uncommon', icon: '🏴‍☠️' },
  braves:   { name: 'Joe Torre',        number: 6,  role: 'Manager',  desc: 'Future dynasty builder - managing Atlanta in 1984',     rarity: 'uncommon', icon: '🗡️' },
  astros:   { name: 'Bob Lillis',       number: 11, role: 'Manager',  desc: 'Led Houston with Nolan Ryan anchoring the staff',        rarity: 'common',   icon: '🌟' },
  giants:   { name: 'Frank Robinson',   number: 12, role: 'Manager',  desc: 'Hall of Famer - one of baseball\'s greatest players',   rarity: 'rare',     icon: '🔥' },
};