// Toronto Blue Jays Broadcast - 1984
// Don Chevrier & Tony Kubek (TV) / Tom Cheek & Jerry Howarth (radio)
// Exhibition Stadium - home of the Blue Jays since 1977
// All stats cutoff: end of 1983 season

export function pickBlueJaysLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickBlueJaysPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Damaso Garcia": {
    lines: [
      "Damaso Garcia began his major-league career with the New York Yankees before joining Toronto.",
      "Damaso Garcia developed into the Blue Jays' regular second baseman during the early 1980s.",
      "Damaso Garcia won the American League Silver Slugger Award at second base in 1982.",
      "Damaso Garcia batted .310 with 185 hits during the 1982 season.",
      "Damaso Garcia collected 32 doubles and scored 89 runs in 1982.",
      "Damaso Garcia stole 54 bases in 1982, becoming the first Blue Jay to reach 50 in a season.",
      "Damaso Garcia followed with a .307 batting average in 1983.",
      "Damaso Garcia collected 161 hits and scored 84 runs during the 1983 season.",
      "Damaso Garcia recorded 23 doubles and six triples in 1983.",
      "Damaso Garcia stole 31 bases during Toronto's first winning season.",
      "Damaso Garcia gives the Blue Jays speed near the top of the batting order.",
      "Damaso Garcia is especially dangerous when he reaches base with nobody out.",
      "Damaso Garcia and Alfredo Griffin form one of the fastest middle-infield combinations in the league.",
    ],
  },
  "Rance Mulliniks": {
    lines: [
      "Rance Mulliniks was selected by the California Angels in the third round of the 1974 draft.",
      "Rance Mulliniks reached the major leagues with California in 1977.",
      "Rance Mulliniks also played for Kansas City before joining Toronto.",
      "Rance Mulliniks came to the Blue Jays before the 1982 season.",
      "Rance Mulliniks was originally developed as a shortstop before seeing more action at third base.",
      "Rance Mulliniks batted .275 with a .373 on-base percentage in 1983.",
      "Rance Mulliniks slugged .467 during the 1983 season.",
      "Rance Mulliniks led Toronto with 34 doubles in 1983.",
      "Rance Mulliniks hit 10 home runs during the 1983 season.",
      "Rance Mulliniks was regarded as one of the American League's most effective pinch-hitters in 1983.",
      "Rance Mulliniks supplies a patient left-handed bat against right-handed pitching.",
      "Rance Mulliniks often shares third-base duties with the right-handed-hitting Garth Iorg.",
      "Rance Mulliniks can fill in at third base, shortstop or designated hitter.",
      "Rance Mulliniks is willing to work deep counts and accept a walk.",
    ],
  },
  "Lloyd Moseby": {
    lines: [
      "Lloyd Moseby's nickname is \"Shaker.\"",
      "Lloyd Moseby was selected second overall by Toronto in the 1978 amateur draft.",
      "Lloyd Moseby reached the major leagues at the age of 20 during the 1980 season.",
      "Lloyd Moseby developed into Toronto's regular center fielder.",
      "Lloyd Moseby enjoyed a breakout season in 1983, batting .315.",
      "Lloyd Moseby recorded a .376 on-base percentage and a .499 slugging percentage in 1983.",
      "Lloyd Moseby collected 170 hits, including 31 doubles and seven triples, in 1983.",
      "Lloyd Moseby hit 18 home runs and drove in 81 runs during the 1983 season.",
      "Lloyd Moseby scored 104 runs in 1983, the first 100-run season in Blue Jays history.",
      "Lloyd Moseby stole 27 bases during the 1983 season.",
      "Lloyd Moseby collected 47 hits in August 1983, a Toronto record for one calendar month.",
      "Lloyd Moseby hit a two-run homer in the bottom of the ninth to beat Cleveland on April 19, 1983.",
      "Lloyd Moseby earned a Silver Slugger Award for his performance in 1983.",
      "Lloyd Moseby combines power, speed, patience and center-field range.",
      "Lloyd Moseby is capable of producing an extra-base hit without pulling the baseball.",
      "Lloyd Moseby can change a game at the plate, on the bases or in the outfield.",
    ],
  },
  "Willie Upshaw": {
    lines: [
      "Willie Upshaw was drafted by the New York Yankees in the fifth round in 1975.",
      "Willie Upshaw came to Toronto through the Rule 5 Draft.",
      "Willie Upshaw became Toronto's regular first baseman during the 1982 season.",
      "Willie Upshaw hit 21 home runs and drove in 75 runs in 1982.",
      "Willie Upshaw produced his finest season to date in 1983.",
      "Willie Upshaw batted .306 with a .373 on-base percentage in 1983.",
      "Willie Upshaw slugged .515 during the 1983 season.",
      "Willie Upshaw collected 177 hits, 26 doubles and seven triples in 1983.",
      "Willie Upshaw tied Jesse Barfield for the team lead with 27 home runs in 1983.",
      "Willie Upshaw drove in 104 runs in 1983.",
      "Willie Upshaw became the first player in Blue Jays history to drive in 100 runs in one season.",
      "Willie Upshaw scored 99 runs during the 1983 season.",
      "Willie Upshaw drew 61 walks while striking out 98 times in 1983.",
      "Willie Upshaw gives Toronto left-handed power in the middle of the lineup.",
      "Willie Upshaw is capable of driving the ball to either outfield gap.",
      "Willie Upshaw is more athletic on the bases than many traditional first basemen.",
    ],
  },
  "Cliff Johnson": {
    lines: [
      "Cliff Johnson's full name is Clifford Johnson Jr.",
      "Cliff Johnson has also been known by the nickname \"Heathcliff.\"",
      "Cliff Johnson began his major-league career with the Houston Astros.",
      "Cliff Johnson also played for the Yankees, Indians, Cubs and Athletics before joining Toronto.",
      "Cliff Johnson was a member of the Yankees' 1977 and 1978 championship clubs.",
      "Cliff Johnson can serve as a designated hitter, first baseman or emergency catcher.",
      "Cliff Johnson appeared in 142 games for Toronto during the 1983 season.",
      "Cliff Johnson batted .265 with a .373 on-base percentage in 1983.",
      "Cliff Johnson slugged .489 during the 1983 season.",
      "Cliff Johnson hit 22 home runs and drove in 76 runs in 1983.",
      "Cliff Johnson collected 23 doubles during his first Toronto season.",
      "Cliff Johnson drew 67 walks in 1983.",
      "Cliff Johnson provides veteran right-handed power in the designated-hitter position.",
      "Cliff Johnson is especially dangerous against a pitcher who falls behind in the count.",
      "Cliff Johnson has enough catching experience to understand how pitchers try to attack him.",
    ],
  },
  "Jesse Barfield": {
    lines: [
      "Jesse Barfield was selected by Toronto in the ninth round of the 1977 amateur draft.",
      "Jesse Barfield attended Joliet Central High School in Illinois.",
      "Jesse Barfield made his major-league debut on September 3, 1981.",
      "Jesse Barfield became Toronto's regular right fielder during the early 1980s.",
      "Jesse Barfield is known for one of the strongest throwing arms in the American League.",
      "Jesse Barfield played 128 games for Toronto in 1983.",
      "Jesse Barfield hit 27 home runs during the 1983 season.",
      "Jesse Barfield tied Willie Upshaw for the Toronto home-run lead in 1983.",
      "Jesse Barfield drove in 68 runs and scored 58 times in 1983.",
      "Jesse Barfield slugged .510 during the 1983 season.",
      "Jesse Barfield produced 49 extra-base hits in only 388 at-bats during 1983.",
      "Jesse Barfield can throw out a runner who underestimates his arm in right field.",
      "Jesse Barfield's power makes him dangerous even when he bats in the lower half of the order.",
      "Jesse Barfield can change an inning with either his bat or his throwing arm.",
      "Jesse Barfield is still only 24 years old entering the 1984 season.",
    ],
  },
  "George Bell": {
    lines: [
      "George Bell was born in San Pedro de Macoris in the Dominican Republic.",
      "George Bell was originally signed by the Philadelphia Phillies organization in 1978.",
      "George Bell was selected by Toronto from Philadelphia in the 1980 Rule 5 Draft.",
      "George Bell spent the strike-shortened 1981 season on Toronto's major-league roster.",
      "George Bell made his major-league debut on April 9, 1981.",
      "George Bell appeared in 60 games and hit five home runs during his 1981 rookie season.",
      "George Bell returned to the major leagues during the second half of 1983.",
      "George Bell appeared in 39 games for Toronto during the 1983 season.",
      "George Bell batted .268 with 30 hits in 112 at-bats in 1983.",
      "George Bell collected five doubles, four triples and two home runs in 1983.",
      "George Bell drove in 17 runs during his brief 1983 opportunity.",
      "George Bell has the bat speed to handle a good major-league fastball.",
      "George Bell gives Toronto another young right-handed power prospect in the outfield.",
      "George Bell is aggressive at the plate and capable of driving an early-count pitch.",
      "George Bell must compete for playing time in a crowded and talented Toronto outfield.",
    ],
  },
  "Ernie Whitt": {
    lines: [
      "Ernie Whitt's full name is Leo Ernest Whitt.",
      "Ernie Whitt grew up in Michigan and hoped that Detroit would draft him.",
      "Ernie Whitt was selected by Boston in the 15th round of the 1972 amateur draft.",
      "Ernie Whitt made his major-league debut with Boston in September 1976.",
      "Ernie Whitt was selected by Toronto for its original expansion roster.",
      "Ernie Whitt developed into Toronto's regular left-handed-hitting catcher.",
      "Ernie Whitt hit 11 home runs in 1982 after hitting only one the previous season.",
      "Ernie Whitt improved again in 1983, batting .256 with a .346 on-base percentage.",
      "Ernie Whitt hit 17 home runs and drove in 56 runs during the 1983 season.",
      "Ernie Whitt slugged .459 in 1983.",
      "Ernie Whitt scored 53 runs and collected 15 doubles in 1983.",
      "Ernie Whitt and Buck Martinez combined for 27 home runs from the catching position in 1983.",
      "Ernie Whitt uses an aggressive pull swing designed to reach the right-field seats.",
      "Ernie Whitt sometimes finishes his swing down on one knee.",
      "Ernie Whitt supplies unusual left-handed power for a catcher.",
      "Ernie Whitt has become familiar with Toronto's young pitching staff through years behind the plate.",
      "Ernie Whitt was part owner of a Mother's Pizza restaurant operation in Ontario by 1983.",
    ],
  },
  "Alfredo Griffin": {
    lines: [
      "Alfredo Griffin was signed by Cleveland as a 15-year-old amateur free agent in 1973.",
      "Alfredo Griffin originally played second base before moving to shortstop.",
      "Alfredo Griffin began experimenting with switch-hitting in the minor leagues.",
      "Alfredo Griffin made his major-league debut with Cleveland in September 1976.",
      "Alfredo Griffin was traded to Toronto before the 1979 season.",
      "Alfredo Griffin shared the 1979 American League Rookie of the Year Award with John Castino.",
      "Alfredo Griffin is known primarily for his range, speed and durability at shortstop.",
      "Alfredo Griffin played in all 162 Toronto games during the 1983 season.",
      "Alfredo Griffin batted .250 with 132 hits in 1983.",
      "Alfredo Griffin collected 22 doubles and nine triples during the 1983 season.",
      "Alfredo Griffin set a career high with four home runs in 1983.",
      "Alfredo Griffin drove in 47 runs and scored 62 times in 1983.",
      "Alfredo Griffin stole 11 bases during the 1983 season.",
      "Alfredo Griffin is willing to attempt difficult plays deep in the shortstop hole.",
      "Alfredo Griffin and Damaso Garcia give Toronto speed on both sides of second base.",
      "Alfredo Griffin was only 18 years old when he collected his first major-league hit.",
    ],
  },
  "Dave Collins": {
    lines: [
      "Dave Collins is a switch-hitting outfielder with outstanding speed.",
      "Dave Collins began his major-league career with the California Angels.",
      "Dave Collins also played for Seattle, Cincinnati and the Yankees before joining Toronto.",
      "Dave Collins enjoyed his finest season with Cincinnati in 1980.",
      "Dave Collins batted .303 with 167 hits and 94 runs scored in 1980.",
      "Dave Collins stole 79 bases for Cincinnati during the 1980 season.",
      "Dave Collins appeared in 118 games during his first Toronto season in 1983.",
      "Dave Collins batted .271 with a .343 on-base percentage in 1983.",
      "Dave Collins scored 55 runs and collected 109 hits in 1983.",
      "Dave Collins stole 31 bases during the 1983 season.",
      "Dave Collins can play all three outfield positions and fill in at first base.",
      "Dave Collins can serve as a leadoff hitter, pinch-runner or defensive replacement.",
      "Dave Collins forces the defense to hurry whenever he hits a ground ball.",
      "Dave Collins remains one of the fastest veteran players in the American League.",
    ],
  },
  "Tony Fernandez": {
    lines: [
      "Tony Fernandez's full name is Octavio Antonio Fernandez.",
      "Tony Fernandez was born in San Pedro de Macoris in the Dominican Republic.",
      "Tony Fernandez signed with Toronto as a teenager.",
      "Tony Fernandez reached Class A baseball at the age of 18.",
      "Tony Fernandez advanced through the Toronto farm system to Triple-A Syracuse.",
      "Tony Fernandez made his major-league debut on September 2, 1983.",
      "Tony Fernandez entered his first major-league game as a pinch-runner for Cliff Johnson.",
      "Tony Fernandez scored his first major-league run after advancing on two wild pitches.",
      "Tony Fernandez appeared in 15 games during his September 1983 trial.",
      "Tony Fernandez batted .265 with nine hits in 34 at-bats.",
      "Tony Fernandez collected one double and one triple during his first major-league month.",
      "Tony Fernandez is a switch-hitting shortstop with a long, lean build.",
      "Tony Fernandez is being developed as a possible successor to Alfredo Griffin.",
      "Tony Fernandez has the range to reach balls that many shortstops cannot approach.",
      "Tony Fernandez is only 21 years old entering the 1984 season.",
    ],
  },
  "Buck Martinez": {
    lines: [
      "Buck Martinez's given first name is John.",
      "Buck Martinez began his major-league career with Kansas City in 1969.",
      "Buck Martinez also played for Milwaukee before joining Toronto.",
      "Buck Martinez was traded from Milwaukee to Toronto in May 1981.",
      "Buck Martinez provides experienced right-handed catching behind Ernie Whitt.",
      "Buck Martinez hit 10 home runs in both 1982 and 1983.",
      "Buck Martinez appeared in 88 games for Toronto during the 1983 season.",
      "Buck Martinez batted .253 with a .337 on-base percentage in 1983.",
      "Buck Martinez slugged .452 during the 1983 season.",
      "Buck Martinez collected 14 doubles, 10 home runs and 33 RBI in 1983.",
      "Buck Martinez drew 29 walks in 221 at-bats during the 1983 season.",
      "Buck Martinez and Ernie Whitt combined for 27 home runs and 89 RBI in 1983.",
      "Buck Martinez gives Toronto a veteran catcher against left-handed pitching.",
      "Buck Martinez has caught in the major leagues for parts of 15 seasons entering 1984.",
      "Buck Martinez is comfortable handling veteran pitchers and young prospects alike.",
    ],
  },
  "Garth Iorg": {
    lines: [
      "Garth Iorg was selected by the Yankees in the eighth round of the 1973 draft.",
      "Garth Iorg was chosen by Toronto from the Yankees organization in the 1976 expansion draft.",
      "Garth Iorg made his major-league debut with Toronto in 1978.",
      "Garth Iorg has spent his entire major-league career with the Blue Jays.",
      "Garth Iorg can play third base, second base, shortstop and several other positions.",
      "Garth Iorg appeared in 122 games during the 1983 season.",
      "Garth Iorg batted .275 with 103 hits in 1983.",
      "Garth Iorg collected 22 doubles and five triples during the 1983 season.",
      "Garth Iorg scored 40 runs and drove in 39 runs in 1983.",
      "Garth Iorg stole seven bases during the 1983 season.",
      "Garth Iorg is the right-handed half of Toronto's third-base platoon with Rance Mulliniks.",
      "Garth Iorg and Rance Mulliniks are sometimes combined under the nickname \"Mullinorg.\"",
      "Garth Iorg's brother Dane has also reached the major leagues.",
      "Garth Iorg gives manager Bobby Cox flexibility when facing a left-handed pitcher.",
    ],
  },
  "Willie Aikens": {
    lines: [
      "Willie Aikens' full name is Willie Mays Aikens.",
      "Willie Aikens was born in Seneca, South Carolina.",
      "Willie Aikens began his major-league career with the California Angels.",
      "Willie Aikens was traded from California to Kansas City before the 1980 season.",
      "Willie Aikens helped Kansas City reach the 1980 World Series.",
      "Willie Aikens hit two home runs in Game One of the 1980 World Series.",
      "Willie Aikens hit two more home runs in Game Four of the 1980 World Series.",
      "Willie Aikens became the first player with two separate two-homer games in one World Series.",
      "Willie Aikens delivered the winning run in the tenth inning of Game Three of the 1980 World Series.",
      "Willie Aikens batted .281 with 17 home runs and 74 RBI in 1982.",
      "Willie Aikens produced an excellent 1983 season for Kansas City.",
      "Willie Aikens batted .302 with a .373 on-base percentage in 1983.",
      "Willie Aikens slugged .539 during the 1983 season.",
      "Willie Aikens collected 26 doubles, 23 home runs and 72 RBI in 1983.",
      "Willie Aikens provides another powerful left-handed option at first base or designated hitter.",
      "Willie Aikens enters Toronto after four productive seasons with Kansas City.",
    ],
  },
  "Dave Stieb": {
    lines: [
      "Dave Stieb was originally an outfielder rather than a full-time pitcher.",
      "Dave Stieb batted .394 with 12 home runs at Southern Illinois University in 1978.",
      "Dave Stieb pitched only 17 college innings during that 1978 season.",
      "Dave Stieb was selected by Toronto in the fifth round of the 1978 draft.",
      "Dave Stieb agreed to become a pitcher because Toronto believed it was his quickest route to the majors.",
      "Dave Stieb pitched only 128 minor-league innings before reaching Toronto.",
      "Dave Stieb made his major-league debut in 1979 and finished 8-8 as a rookie.",
      "Dave Stieb became Toronto's first true pitching star.",
      "Dave Stieb was selected to the American League All-Star team in 1980 and 1981.",
      "Dave Stieb went 17-14 with 19 complete games in 1982.",
      "Dave Stieb threw 288 and a third innings during the 1982 season.",
      "Dave Stieb finished fourth in the 1982 American League Cy Young voting.",
      "Dave Stieb was named The Sporting News American League Pitcher of the Year for 1982.",
      "Dave Stieb signed a six-year contract before the 1983 season.",
      "Dave Stieb started and won the 1983 All-Star Game for the American League.",
      "Dave Stieb went 17-12 with a 3.04 ERA in 1983.",
      "Dave Stieb made 36 starts and threw 278 innings in 1983.",
      "Dave Stieb completed 14 games and threw four shutouts in 1983.",
      "Dave Stieb struck out 187 hitters while allowing only 223 hits in 1983.",
      "Dave Stieb's slider is his most dangerous finishing pitch.",
      "Dave Stieb also throws a lively fastball and several different breaking balls.",
      "Dave Stieb is an intense competitor who does not hide his frustration.",
      "Dave Stieb is capable of dominating even when Toronto provides little run support.",
    ],
  },
  "Doyle Alexander": {
    lines: [
      "Doyle Alexander's full name is Doyle Lafayette Alexander.",
      "Doyle Alexander began his major-league career with the Los Angeles Dodgers in 1971.",
      "Doyle Alexander was sent to Baltimore as part of the trade that brought Frank Robinson to Los Angeles.",
      "Doyle Alexander also pitched for the Yankees, Rangers, Braves and Giants before joining Toronto.",
      "Doyle Alexander won 17 games for Texas during the 1977 season.",
      "Doyle Alexander pitched in the postseason with both Baltimore and New York.",
      "Doyle Alexander struggled with the Yankees early in 1983 and was released.",
      "Doyle Alexander signed with Toronto on June 21, 1983.",
      "Doyle Alexander made 17 appearances and 15 starts for Toronto in 1983.",
      "Doyle Alexander went 7-8 with a 3.93 ERA after joining the Blue Jays.",
      "Doyle Alexander completed five of his 15 Toronto starts in 1983.",
      "Doyle Alexander walked only 26 hitters in 116 and two-thirds Toronto innings.",
      "Doyle Alexander relies on command, movement and changing speeds.",
      "Doyle Alexander does not require a high strikeout total to work deep into a game.",
      "Doyle Alexander gives a young Toronto club valuable postseason and pennant-race experience.",
    ],
  },
  "Jim Clancy": {
    lines: [
      "Jim Clancy was selected by Texas in the fourth round of the 1974 amateur draft.",
      "Jim Clancy was chosen by Toronto in the 1976 expansion draft.",
      "Jim Clancy reached the major leagues during Toronto's inaugural 1977 season.",
      "Jim Clancy went 4-9 in 13 starts during his rookie season.",
      "Jim Clancy developed into one of the Blue Jays' most durable starting pitchers.",
      "Jim Clancy made the American League All-Star team in 1982.",
      "Jim Clancy made 40 starts during the 1982 season.",
      "Jim Clancy went 16-14 with a 3.71 ERA in 1982.",
      "Jim Clancy struck out 139 hitters during his All-Star season.",
      "Jim Clancy followed with a 15-11 record in 1983.",
      "Jim Clancy posted a 3.91 ERA during the 1983 season.",
      "Jim Clancy has won at least 15 games in consecutive seasons.",
      "Jim Clancy supplies innings and stability behind Dave Stieb.",
      "Jim Clancy attacks hitters with a power pitcher's approach.",
      "Jim Clancy is one of the remaining original members of the Toronto franchise.",
    ],
  },
  "Luis Leal": {
    lines: [
      "Luis Leal was born in Barquisimeto, Venezuela.",
      "Luis Leal made his major-league debut with Toronto in 1980.",
      "Luis Leal has spent his entire major-league career with the Blue Jays.",
      "Luis Leal became a full-time member of Toronto's rotation during the early 1980s.",
      "Luis Leal went 12-15 with a 3.93 ERA during the 1982 season.",
      "Luis Leal made 35 starts during the 1983 season.",
      "Luis Leal went 13-12 with a 4.31 ERA in 1983.",
      "Luis Leal threw 217 and a third innings during the 1983 season.",
      "Luis Leal completed seven games and recorded one shutout in 1983.",
      "Luis Leal struck out 116 hitters while walking 65 in 1983.",
      "Luis Leal provides Toronto with another durable right-handed starting pitcher.",
      "Luis Leal can remain effective deep into a game when his command is sharp.",
      "Luis Leal was one of three Toronto pitchers to win at least 13 games in 1983.",
    ],
  },
  "Roy Lee Jackson": {
    lines: [
      "Roy Lee Jackson began his major-league career with the New York Mets.",
      "Roy Lee Jackson pitched for the Mets from 1977 through 1980.",
      "Roy Lee Jackson later joined the Toronto pitching staff.",
      "Roy Lee Jackson was used exclusively in relief during the 1983 season.",
      "Roy Lee Jackson appeared in 49 games for Toronto in 1983.",
      "Roy Lee Jackson went 8-3 during the 1983 season.",
      "Roy Lee Jackson recorded seven saves in 1983.",
      "Roy Lee Jackson worked 92 innings despite making no starts.",
      "Roy Lee Jackson allowed 92 hits and struck out 48 hitters in 1983.",
      "Roy Lee Jackson can work more than one inning at the end of a game.",
      "Roy Lee Jackson was Toronto's most frequently used late-inning option in 1983.",
      "Roy Lee Jackson gives Bobby Cox a reliever who can enter before the ninth inning and finish the game.",
    ],
  },
  "Dennis Lamp": {
    lines: [
      "Dennis Lamp was selected by the Chicago Cubs in the third round of the 1971 draft.",
      "Dennis Lamp began his major-league career as a starting pitcher with the Cubs.",
      "Dennis Lamp was traded across Chicago to the White Sox before the 1981 season.",
      "Dennis Lamp has worked as a starter, long reliever and closer.",
      "Dennis Lamp carried a no-hitter into the ninth inning against Milwaukee in 1981.",
      "Dennis Lamp lost that no-hit bid when Robin Yount delivered a ninth-inning double.",
      "Dennis Lamp made 27 starts and threw 189 and two-thirds innings for Chicago in 1982.",
      "Dennis Lamp moved primarily into relief during the 1983 season.",
      "Dennis Lamp appeared in 49 games for the division-winning White Sox in 1983.",
      "Dennis Lamp went 7-7 with a 3.71 ERA in 1983.",
      "Dennis Lamp led the White Sox with 15 saves during the 1983 season.",
      "Dennis Lamp worked 116 and a third innings despite starting only five games in 1983.",
      "Dennis Lamp was the winning pitcher when Chicago clinched its 1983 division championship.",
      "Dennis Lamp gives Toronto a reliever capable of handling short or extended assignments.",
      "Dennis Lamp has already pitched in both Chicago leagues and in a pennant race.",
    ],
  },
  "Jimmy Key": {
    lines: [
      "Jimmy Key was born in Huntsville, Alabama.",
      "Jimmy Key was an outstanding pitcher and hitter in high school.",
      "Jimmy Key went 10-0 with nine shutouts and a 0.30 ERA during his senior high-school season.",
      "Jimmy Key also batted .410 with 11 home runs during that senior season.",
      "Jimmy Key was selected by the White Sox in the tenth round of the 1979 draft.",
      "Jimmy Key chose to attend Clemson University rather than sign with Chicago.",
      "Jimmy Key became a two-way standout at Clemson as a pitcher and designated hitter.",
      "Jimmy Key posted a 2.79 ERA as a Clemson sophomore.",
      "Jimmy Key batted .359 with a school-record 21 doubles during that college season.",
      "Jimmy Key became the first Clemson player named first-team All-ACC at two positions in one season.",
      "Jimmy Key earned the honors as both a pitcher and designated hitter in 1982.",
      "Jimmy Key was selected by Toronto in the third round of the 1982 amateur draft.",
      "Jimmy Key was drafted one round after fellow Toronto prospect David Wells.",
      "Jimmy Key advanced through four Toronto minor-league affiliates during 1982 and 1983.",
      "Jimmy Key has not yet appeared in a major-league regular-season game entering 1984.",
      "Jimmy Key gives Toronto a polished young left-handed option for the pitching staff.",
      "Jimmy Key's athletic background allows him to field his position and handle the bat better than many pitchers.",
    ],
  },
  "Jim Acker": {
    lines: [
      "Jim Acker pitched collegiately at the University of Texas.",
      "Jim Acker was selected 21st overall by Atlanta in the first round of the 1980 draft.",
      "Jim Acker developed in the Atlanta farm system before Toronto acquired him.",
      "Jim Acker was selected by Toronto in the December 1982 Rule 5 Draft.",
      "Jim Acker had to remain on Toronto's major-league roster throughout 1983 under Rule 5 regulations.",
      "Jim Acker made his major-league debut on April 7, 1983.",
      "Jim Acker appeared in 38 games and made five starts during his rookie season.",
      "Jim Acker went 5-1 with one save in 1983.",
      "Jim Acker posted a 4.33 ERA over 97 and two-thirds innings in 1983.",
      "Jim Acker struck out 44 hitters and walked 38 during his rookie season.",
      "Jim Acker can serve as a starter, long reliever or middle reliever.",
      "Jim Acker gave Toronto useful innings despite making the jump directly onto the major-league roster.",
      "Jim Acker is still only 25 years old entering the 1984 season.",
    ],
  },
  "Bryan Clark": {
    lines: [
      "Bryan Clark is a left-handed pitcher from Madera, California.",
      "Bryan Clark reached the major leagues with the Seattle Mariners.",
      "Bryan Clark has experience as both a starting pitcher and a reliever.",
      "Bryan Clark appeared in 41 games for Seattle during the 1983 season.",
      "Bryan Clark made 17 starts during the 1983 season.",
      "Bryan Clark went 7-10 with a 3.94 ERA in 1983.",
      "Bryan Clark worked 162 and a third innings for Seattle during the 1983 season.",
      "Bryan Clark completed two games in 1983.",
      "Bryan Clark struck out 76 hitters while walking 72 in 1983.",
      "Bryan Clark allowed 160 hits in 162 and a third innings during the 1983 season.",
      "Bryan Clark gives Toronto another left-handed option capable of pitching several innings.",
      "Bryan Clark's starting experience makes him useful when a starter leaves early.",
      "Bryan Clark enters Toronto after one of the strongest seasons of his major-league career.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive - base hit.\"",
    "\"Long drive to left field - way back - gone. Home run!\"",
    "\"Ground ball to short - over to first - in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This is a ballclub on the rise - the Blue Jays are turning heads around the league.\"",
    "\"A young team that's learning how to win. You can see it night after night.\"",
    "\"Toronto baseball has arrived. The fans up here have been waiting for this.\"",
    "\"This club plays with energy. They're fun to watch and they're only getting better.\"",
    "\"Bobby Cox has this team believing in itself. That goes a long way.\"",
    "\"The Blue Jays had their first winning season in 1983 - and they're hungry for more.\"",
    "\"There's talent up and down this roster, and it's starting to come together.\"",
    "\"Expansion club, yes - but nobody's calling them newcomers anymore.\"",
    "\"The Blue Jays are building something special up here in Toronto.\"",
    "\"From the top of the order to the bottom - this lineup can hurt you.\"",
    "\"Toronto baseball is alive and well. What a crowd, what a ballclub.\"",
    "\"This team doesn't quit. They play all nine innings - that's the Blue Jays way.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Damaso Garcia and Alfredo Griffin give the Blue Jays tremendous speed up the middle.\"",
    "\"Willie Upshaw became the first Blue Jay to drive in 100 runs - that's franchise history.\"",
    "\"Lloyd Moseby became the first Blue Jay to score 100 runs - what a talent in center.\"",
    "\"Dave Stieb is the ace of this staff, no question about it.\"",
    "\"Jesse Barfield's arm is as good as any in the American League.\"",
    "\"The catching tandem of Whitt and Martinez gives Bobby Cox options on both sides.\"",
    "\"Tony Fernandez is a young shortstop with enormous potential - keep an eye on him.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Exhibition Stadium, right on the lakeshore.\"",
    "\"The lights are on at Exhibition Stadium - the CNE grounds are lit up tonight.\"",
    "\"A cool breeze coming in off Lake Ontario - that's baseball in Toronto.\"",
    "\"The seagulls are circling the outfield - they know it's game time at the Ex.\"",
    "\"Exhibition Stadium - home of Blue Jays baseball since 1977.\"",
    "\"The artificial turf is playing fast tonight - ground balls will scoot through.\"",
    "\"A crisp Canadian evening - perfect for baseball down by the lake.\"",
    "\"The stands are filling up nicely - Toronto fans are showing their support.\"",
    "\"You can see the skyline of the city beyond the outfield - a beautiful backdrop.\"",
    "\"The breeze off the lake can really knock a fly ball down - outfielders have to be alert.\"",
    "\"The football configuration here at the Ex gives it a unique feel - the seats in left are a long way from home plate.\"",
    "\"It may not be the prettiest ballpark in the league, but the fans here make it feel like home.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here in Toronto is into this ballgame.\"",
    "\"Blue Jays fans are making some noise tonight.\"",
    "\"The fans up here in Canada love their baseball - listen to that.\"",
    "\"The stands at the Ex are rocking tonight.\"",
    "\"Toronto fans have embraced this team - and why not?\"",
    "\"The crowd is on its feet - Blue Jays baseball is alive and well.\"",
    "\"A great turnout tonight at Exhibition Stadium.\"",
    "\"These fans have watched this team grow from day one - they've earned this.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Exhibition Stadium, everyone. A wonderful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's something special about baseball by the lake on a summer night.\"",
    "\"From all of us up here in Toronto, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story - that's the beauty of this sport.\"",
    "\"Baseball in Canada - it's been growing on folks, and you can see why.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone - into the seats at the Ex!\"",
    "\"A magnificent piece of hitting. Simply magnificent.\"",
    "\"The Blue Jays are making their move here at Exhibition Stadium.\"",
    "\"That one is long gone - souvenir for a fan in the bleachers.\"",
    "\"You won't see many better than that one.\"",
    "\"He stood there like the house by the side of the road.\"",
  ]},
};