// Atlanta Braves Broadcast - 1984
// Radio/TV: Skip Caray, Pete Van Wieren, Ernie Johnson Sr.
// Atlanta-Fulton County Stadium - home of the Braves since 1966
// All stats cutoff: end of 1983 season

export function pickBravesLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickBravesPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Claudell Washington": {
    lines: [
      "Claudell Washington was born in Los Angeles, California.",
      "Washington attended Berkeley High School in Berkeley, California.",
      "The Oakland Athletics signed Washington as an amateur free agent in 1972.",
      "Claudell Washington was only 19 years old when he made his major-league debut in 1974.",
      "Washington joined an Oakland club that was attempting to win its third consecutive World Series.",
      "Claudell Washington appeared in the 1974 American League Championship Series against Baltimore.",
      "Washington also appeared in the 1974 World Series against the Los Angeles Dodgers.",
      "Claudell Washington collected five hits during Oakland's five-game World Series victory.",
      "Washington became a regular outfielder for the Athletics during the 1975 season.",
      "Claudell Washington batted .308 with 182 hits in 1975.",
      "Washington was selected to the American League All-Star team that season.",
      "Claudell Washington later played for the Texas Rangers, Chicago White Sox and New York Mets.",
      "Atlanta signed Washington as a free agent before the 1981 season.",
      "Washington bats and throws left-handed.",
      "Claudell Washington appeared in 134 games during the 1983 season.",
      "Washington batted .278 with 138 hits.",
      "Claudell Washington collected 24 doubles and eight triples.",
      "Washington hit nine home runs and drove in 44 runs.",
      "Claudell Washington scored 75 times.",
      "Washington stole 31 bases while being caught nine times.",
      "His eight triples demonstrate the danger he presents once the ball reaches an outfield gap.",
      "Washington possesses enough speed to bat first and enough power to drive the ball beyond an outfielder.",
      "His strong throwing arm makes runners cautious about taking an extra base on hits to right field.",
      "Washington's combination of speed, power and defensive athleticism gives Atlanta a genuine five-tool threat when he is playing well.",
    ],
  },
  "Glenn Hubbard": {
    lines: [
      "Glenn Hubbard's full name is Glenn Dee Hubbard.",
      "Hubbard was born in Hahn, West Germany, while his father was serving in the United States military.",
      "Glenn Hubbard attended Wheatland High School in California.",
      "Atlanta selected Hubbard in the 20th round of the 1975 amateur draft.",
      "Hubbard developed as a second baseman in the Braves' minor-league system.",
      "Glenn Hubbard made his major-league debut during the 1978 season.",
      "Hubbard became Atlanta's regular second baseman by 1980.",
      "Glenn Hubbard played an important role on the Braves' 1982 National League West championship club.",
      "Hubbard appeared in all three games of the 1982 National League Championship Series.",
      "Glenn Hubbard is known for his full beard and energetic style of play.",
      "Hubbard appeared in 148 games during the 1983 season.",
      "Glenn Hubbard collected 136 hits.",
      "Hubbard batted .263.",
      "Glenn Hubbard recorded 24 doubles and six triples.",
      "Hubbard hit 12 home runs and drove in 70 runs.",
      "Glenn Hubbard scored 65 times.",
      "Hubbard drew 55 walks.",
      "Glenn Hubbard was selected to the 1983 National League All-Star team.",
      "Hubbard provides more power than teams normally expect from a second baseman.",
      "His ability to turn the double play is important behind Atlanta's contact-oriented pitchers.",
      "Hubbard is willing to sacrifice himself to advance a runner.",
      "He recorded nine sacrifice hits during the 1983 season.",
      "Hubbard and Rafael Ramirez give Atlanta an experienced middle-infield combination.",
      "His compact build and aggressive style make him especially popular with Braves fans.",
    ],
  },
  "Dale Murphy": {
    lines: [
      "Dale Murphy's full name is Dale Bryan Murphy.",
      "Murphy was born in Portland, Oregon.",
      "Dale Murphy attended Woodrow Wilson High School in Portland.",
      "Murphy was an outstanding high-school catcher.",
      "Dale Murphy batted .465 during his senior season.",
      "Atlanta selected Murphy with the fifth overall choice of the 1974 amateur draft.",
      "Murphy originally signed with the Braves as a catcher.",
      "Dale Murphy made his major-league debut at Dodger Stadium on September 13, 1976.",
      "Murphy collected two hits and drove in two runs during his debut.",
      "Dale Murphy experienced serious throwing difficulties while attempting to remain a catcher.",
      "Atlanta experimented with Murphy at first base before moving him to center field.",
      "The move to the outfield allowed Murphy's athleticism and strong arm to become defensive assets.",
      "Dale Murphy became Atlanta's regular center fielder during the 1980 season.",
      "Murphy was selected to his first National League All-Star team that year.",
      "Dale Murphy played all 162 games during the 1982 season.",
      "Murphy hit 36 home runs and led the National League with 109 RBI.",
      "Dale Murphy was named the 1982 National League Most Valuable Player.",
      "Murphy also received his first Gold Glove Award in 1982.",
      "Dale Murphy again appeared in all 162 games during the 1983 season.",
      "Murphy batted approximately .300 with 178 hits.",
      "Dale Murphy hit 36 home runs for the second consecutive season.",
      "Murphy led the National League with 121 RBI.",
      "Dale Murphy also led the league in slugging percentage.",
      "Murphy scored 131 runs and stole 30 bases.",
      "Dale Murphy received another Gold Glove Award.",
      "Murphy was named National League Most Valuable Player for the second consecutive year.",
      "He became the youngest player to that point to win consecutive National League MVP awards.",
      "Dale Murphy combines middle-of-the-order power with legitimate base-stealing speed.",
      "His strong arm dates back to his original development as a catcher.",
      "Murphy's reputation for sportsmanship and clean living makes him especially popular with families and young fans.",
      "He does not smoke, drink or use profanity.",
      "Murphy's ability to produce home runs, stolen bases and Gold Glove defense makes him one of baseball's most complete players entering 1984.",
    ],
  },
  "Chris Chambliss": {
    lines: [
      "Chris Chambliss' full name is Carroll Christopher Chambliss.",
      "Chambliss was born in Dayton, Ohio.",
      "Chris Chambliss attended Oceanside High School in California.",
      "Chambliss later attended MiraCosta College and the University of California, Los Angeles.",
      "Cleveland selected Chris Chambliss with the first overall pick of the 1970 amateur draft.",
      "Chambliss reached the major leagues during the same season in which he was drafted.",
      "Chris Chambliss was named the 1971 American League Rookie of the Year.",
      "Cleveland traded Chambliss to the New York Yankees during the 1974 season.",
      "Chris Chambliss became the regular first baseman for a powerful Yankees club.",
      "Chambliss hit the pennant-winning home run in the ninth inning of Game Five of the 1976 American League Championship Series.",
      "The home run sent the Yankees to their first World Series since 1964.",
      "Chris Chambliss won a Gold Glove Award at first base in 1978.",
      "Chambliss played on the Yankees' 1977 and 1978 World Series championship teams.",
      "Atlanta acquired Chris Chambliss from Toronto before the 1980 season.",
      "Chambliss' arrival allowed the Braves to move Dale Murphy permanently to center field.",
      "Chris Chambliss appeared in 131 games during the 1983 season.",
      "Chambliss batted .280 with 125 hits.",
      "Chris Chambliss collected 24 doubles and three triples.",
      "Chambliss hit 20 home runs.",
      "Chris Chambliss drove in 78 runs.",
      "Chambliss drew 63 walks and posted a .366 on-base percentage.",
      "His left-handed swing provides balance behind the right-handed Dale Murphy.",
      "Chambliss is comfortable hitting with runners in scoring position.",
      "His postseason experience gives Atlanta a veteran presence in the middle of the lineup.",
      "Chambliss remains a dependable defensive first baseman with soft hands around the bag.",
    ],
  },
  "Gerald Perry": {
    lines: [
      "Gerald Perry's full name is Gerald June Perry.",
      "Perry was born in Savannah, Georgia.",
      "Gerald Perry attended McCracken High School in Hilton Head, South Carolina.",
      "Atlanta selected Perry in the 11th round of the 1978 amateur draft.",
      "Perry bats left-handed and throws right-handed.",
      "Gerald Perry developed primarily as a first baseman in the Braves' farm system.",
      "Perry also gained experience in the outfield.",
      "Gerald Perry spent most of the 1983 season with Triple-A Richmond.",
      "Perry appeared in 113 games for the Richmond Braves.",
      "Gerald Perry collected 133 hits in 423 official at-bats.",
      "Perry batted .314.",
      "Gerald Perry recorded 21 doubles and eight triples.",
      "Perry hit 13 home runs and drove in 71 runs.",
      "Gerald Perry stole 26 bases.",
      "Perry drew 73 walks and posted a .414 on-base percentage.",
      "Gerald Perry made his major-league debut on August 11, 1983.",
      "Perry appeared in 27 games for Atlanta.",
      "Gerald Perry collected 14 hits in 39 official at-bats.",
      "Perry batted .359 during his first major-league trial.",
      "Gerald Perry hit one home run and drove in six runs.",
      "Perry's speed is unusual for a player who developed primarily at first base.",
      "His left-handed bat gives Atlanta another option against right-handed pitching.",
      "Perry's limited major-league exposure means opposing pitchers have very little firsthand experience against him.",
      "His minor-league performance suggests a player capable of reaching base, stealing bases and driving the ball into the gaps.",
      "Playing left field on your roster keeps Chris Chambliss at first base while still placing Perry's bat and speed in the lineup.",
    ],
  },
  "Randy Johnson": {
    lines: [
      "This Randy Johnson is an infielder and should not be confused with any pitcher sharing the same name.",
      "Johnson was born in Miami, Florida.",
      "Randy Johnson bats and throws right-handed.",
      "Johnson developed as a second baseman and third baseman.",
      "Randy Johnson made his major-league debut with Atlanta during the 1982 season.",
      "Johnson appeared in 66 games as a rookie.",
      "Randy Johnson provided the Braves with defensive depth at several infield positions.",
      "Johnson appeared in 86 games during the 1983 season.",
      "Randy Johnson received 144 official at-bats.",
      "Johnson collected 36 hits.",
      "Randy Johnson batted .250.",
      "Johnson recorded three doubles.",
      "Randy Johnson hit one home run and drove in 17 runs.",
      "Johnson scored 22 times.",
      "Randy Johnson drew 20 walks.",
      "Johnson posted a .345 on-base percentage.",
      "His walk total is impressive relative to his limited number of at-bats.",
      "Randy Johnson can fill in at either second base or third base.",
      "His ability to play multiple positions gives Atlanta flexibility when using Bob Horner as a pinch-hitter.",
      "Johnson's offensive approach emphasizes reaching base rather than swinging for home runs.",
      "He gives the lineup a less powerful but more mobile defensive option at third base.",
    ],
  },
  "Bruce Benedict": {
    lines: [
      "Bruce Benedict was born in Birmingham, Alabama.",
      "Benedict attended the University of Nebraska at Omaha.",
      "Atlanta selected Bruce Benedict in the fifth round of the 1976 amateur draft.",
      "Benedict made his major-league debut during the 1978 season.",
      "Bruce Benedict became Atlanta's primary catcher during the 1980 season.",
      "Benedict developed a reputation as a skilled receiver and defensive catcher.",
      "Bruce Benedict handled Phil Niekro's unpredictable knuckleball.",
      "Catching Niekro required Benedict to remain prepared for pitches that changed direction near the plate.",
      "Bruce Benedict helped Atlanta win the 1982 National League West championship.",
      "Benedict appeared in 134 games during the 1983 season.",
      "Bruce Benedict collected 126 hits in 423 official at-bats.",
      "Benedict batted .298.",
      "Bruce Benedict recorded 13 doubles and one triple.",
      "Benedict hit two home runs and drove in 43 runs.",
      "Bruce Benedict drew 61 walks.",
      "Benedict posted an excellent .385 on-base percentage.",
      "Bruce Benedict was selected to the 1983 National League All-Star team.",
      "He struck out only 24 times during the season.",
      "Benedict's patience makes him more valuable offensively than his home-run total suggests.",
      "His knowledge of the pitching staff is particularly important with several young pitchers on the roster.",
      "Benedict provides a steady target and communicates well with pitchers.",
      "His ability to control the strike zone makes him a difficult out near the bottom of the lineup.",
      "A pitcher who treats Benedict like an automatic out risks giving Atlanta another baserunner ahead of Rafael Ramirez and the top of the order.",
    ],
  },
  "Rafael Ramirez": {
    lines: [
      "Rafael Ramirez's full name is Rafael Emilio Ramirez Peguero.",
      "Ramirez was born in San Pedro de Macoris in the Dominican Republic.",
      "Rafael Ramirez bats and throws right-handed.",
      "Atlanta signed Ramirez as an amateur free agent.",
      "Ramirez made his major-league debut during the 1980 season.",
      "Rafael Ramirez became the Braves' regular shortstop.",
      "Ramirez played an important role on Atlanta's 1982 division-winning club.",
      "Rafael Ramirez appeared in 152 games during the 1983 season.",
      "Ramirez accumulated 622 official at-bats.",
      "Rafael Ramirez collected 185 hits.",
      "Ramirez batted .297.",
      "Rafael Ramirez scored 82 runs.",
      "Ramirez recorded 13 doubles and five triples.",
      "Rafael Ramirez hit seven home runs and drove in 58 runs.",
      "Ramirez stole 16 bases.",
      "Rafael Ramirez struck out only 48 times.",
      "His 185 hits were the highest total on the Braves.",
      "Ramirez uses a line-drive swing and is capable of hitting behind runners.",
      "His speed allows him to take an extra base when an outfielder is slow to retrieve the ball.",
      "Ramirez and Glenn Hubbard have extensive experience working together around second base.",
      "His ability to make contact gives Atlanta an effective second leadoff hitter at the bottom of the order.",
      "Once Ramirez reaches base, Claudell Washington and the top of the lineup can immediately place the defense under pressure.",
    ],
  },
  "Bob Horner": {
    lines: [
      "Bob Horner's full name is James Robert Horner.",
      "Horner was born in Junction City, Kansas.",
      "Bob Horner grew up in Arizona.",
      "Horner attended Apollo High School in Glendale, Arizona.",
      "Bob Horner became one of the greatest college hitters of his generation at Arizona State University.",
      "Horner helped Arizona State win the 1977 College World Series.",
      "Bob Horner received the inaugural Golden Spikes Award in 1978.",
      "Atlanta selected Horner with the first overall pick of the 1978 amateur draft.",
      "Bob Horner went directly from college baseball to the major leagues.",
      "Horner did not play a minor-league game before joining Atlanta.",
      "Bob Horner made his major-league debut on June 16, 1978.",
      "Horner hit a home run during his first major-league game.",
      "Bob Horner hit 23 home runs in only 89 games as a rookie.",
      "Horner was named the 1978 National League Rookie of the Year.",
      "Bob Horner hit 35 home runs during the 1980 season.",
      "Horner helped Atlanta win the 1982 National League West championship.",
      "Bob Horner was selected to the 1982 National League All-Star team.",
      "Horner hit 32 home runs and drove in 97 runs that season.",
      "Bob Horner appeared in 104 games during the 1983 season.",
      "Horner batted above .300.",
      "Bob Horner hit 20 home runs despite missing a substantial portion of the season.",
      "Horner drove in 68 runs.",
      "Injuries have repeatedly prevented Horner from playing a complete schedule.",
      "When healthy, Horner possesses some of the most dangerous right-handed power in the National League.",
      "His compact swing allows him to reach pitches that many power hitters cannot handle.",
      "Horner can play either third base or first base.",
      "A tired pitcher must choose between challenging Horner's power and putting another runner on base ahead of Dale Murphy.",
    ],
  },
  "Alex Trevino": {
    lines: [
      "Alex Trevino's full name is Alejandro Trevino Castro.",
      "Trevino was born in Monterrey, Mexico.",
      "Alex Trevino bats and throws right-handed.",
      "Trevino signed with the New York Mets as an amateur free agent.",
      "Alex Trevino made his major-league debut during the 1978 season.",
      "Trevino became one of the Mets' primary catchers.",
      "Alex Trevino gained experience catching several young New York pitching staffs.",
      "Trevino was traded to the Cincinnati Reds before the 1982 season.",
      "Alex Trevino served as Cincinnati's primary catcher during much of 1982.",
      "Trevino possesses experience at third base in addition to catcher.",
      "Alex Trevino's versatility makes him more than a conventional backup catcher.",
      "Trevino is regarded more for receiving and defensive flexibility than home-run power.",
      "Alex Trevino can enter late in a game without forcing Atlanta to remove Bruce Benedict permanently from consideration.",
      "Trevino provides a veteran alternative when a pitcher prefers a different target or game-calling style.",
      "His ability to play third base is useful on a roster that includes the injury-prone Bob Horner.",
      "Trevino gives Atlanta enough catching depth to use Benedict as a pinch-hitter without leaving the club exposed behind the plate.",
    ],
  },
  "Jerry Royster": {
    lines: [
      "Jerry Royster's full name is Jeron Kennis Royster.",
      "Royster was born in Sacramento, California.",
      "Jerry Royster attended Sacramento High School.",
      "The Los Angeles Dodgers selected Royster in the 14th round of the 1970 amateur draft.",
      "Royster made his major-league debut with Los Angeles during the 1973 season.",
      "Atlanta acquired Jerry Royster before the 1976 season.",
      "Royster became one of the Braves' most versatile players.",
      "Jerry Royster has played second base, third base, shortstop and all three outfield positions.",
      "Royster stole 28 bases during the 1976 season.",
      "Jerry Royster recorded 27 stolen bases in 1977.",
      "Royster played an important supporting role on the 1982 division-winning Braves.",
      "Jerry Royster appeared in 91 games during the 1983 season.",
      "Royster collected 63 hits in 268 official at-bats.",
      "Jerry Royster batted .235.",
      "Royster recorded 10 doubles and three triples.",
      "Jerry Royster hit three home runs and drove in 30 runs.",
      "Royster stole 11 bases.",
      "Jerry Royster can replace almost any position player without forcing manager Joe Torre to reorganize the entire defense.",
      "His speed makes him useful as a pinch-runner.",
      "His experience at several positions makes him a logical late-inning defensive replacement.",
      "Royster's willingness to accept a changing role is especially valuable on a compact exhibition roster.",
    ],
  },
  "Brad Komminsk": {
    lines: [
      "Brad Komminsk's full name is Brad Lynn Komminsk.",
      "Komminsk was born in Lima, Ohio.",
      "Brad Komminsk attended Shawnee High School in Lima.",
      "Atlanta selected Komminsk with the fourth overall pick of the 1979 amateur draft.",
      "Komminsk was one of the most highly regarded prospects in professional baseball.",
      "Brad Komminsk was considered capable of hitting for average, hitting for power, running, throwing and fielding.",
      "Hank Aaron described Komminsk as a future major-league star.",
      "Brad Komminsk appeared on the cover of Baseball America while still in the minor leagues.",
      "Komminsk spent most of the 1983 season with Triple-A Richmond.",
      "Brad Komminsk appeared in 117 games for Richmond.",
      "Komminsk collected 138 hits in 413 official at-bats.",
      "Brad Komminsk batted .334.",
      "Komminsk recorded 24 doubles and six triples.",
      "Brad Komminsk hit 24 home runs.",
      "Komminsk drove in 103 runs.",
      "Brad Komminsk scored 94 times.",
      "Komminsk stole 26 bases while being caught only five times.",
      "Brad Komminsk drew 78 walks.",
      "Komminsk posted a .433 on-base percentage and a .596 slugging percentage.",
      "Brad Komminsk made his major-league debut on August 14, 1983.",
      "His first major-league trial was brief.",
      "Opposing pitchers therefore possess very little major-league experience against him.",
      "Komminsk has enough speed to pinch-run and enough power to pinch-hit.",
      "He can play any of the three outfield positions.",
      "Komminsk enters 1984 carrying enormous expectations based upon his minor-league dominance.",
    ],
  },
  "Milt Thompson": {
    lines: [
      "Milt Thompson's full name is Milton Bernard Thompson.",
      "Thompson was born in Washington, D.C.",
      "Milt Thompson bats left-handed and throws right-handed.",
      "Atlanta selected Thompson in the second round of the January 1979 amateur draft.",
      "Thompson developed as a center fielder in the Braves' minor-league system.",
      "Milt Thompson possesses excellent running speed.",
      "Thompson spent most of the 1983 season with Double-A Savannah.",
      "Milt Thompson appeared in 115 games for Savannah.",
      "Thompson collected 117 hits in 386 official at-bats.",
      "Milt Thompson batted .303.",
      "Thompson recorded 21 doubles and four triples.",
      "Milt Thompson hit five home runs and drove in 46 runs.",
      "Thompson scored 84 times.",
      "Milt Thompson stole 30 bases.",
      "Thompson drew 83 walks.",
      "Milt Thompson posted an outstanding .429 on-base percentage.",
      "Thompson also received a brief promotion to Triple-A Richmond.",
      "Milt Thompson had not yet appeared in a major-league game entering 1984.",
      "Opposing major-league pitchers possess no firsthand scouting history against him.",
      "Thompson's speed makes him immediately useful as a pinch-runner.",
      "His patience suggests that he can contribute even without hitting for significant home-run power.",
      "Thompson provides a second young, athletic outfielder alongside Brad Komminsk.",
      "His combination of walks and stolen bases makes him a natural candidate for eventual leadoff work.",
    ],
  },
  "Pascual Perez": {
    lines: [
      "Pascual Perez's full name is Pascual Gross Perez.",
      "Perez was born in San Cristobal in the Dominican Republic.",
      "Pascual Perez is a right-handed pitcher.",
      "Pittsburgh signed Perez as an amateur free agent.",
      "Perez made his major-league debut with the Pirates during the 1980 season.",
      "Atlanta acquired Pascual Perez during the 1982 season.",
      "Perez became an important member of the Braves' division-winning rotation.",
      "Pascual Perez is known for his animated personality and distinctive celebrations.",
      "Perez sometimes points his finger like a pistol after recording an important strikeout.",
      "Pascual Perez throws from several different arm angles.",
      "His delivery can include hesitations and changes of rhythm designed to disrupt a hitter's timing.",
      "Pascual Perez made national headlines in August 1982 when he missed a scheduled start after becoming lost while driving on Interstate 285 around Atlanta.",
      "The incident earned him the nickname \"Perimeter Pascual.\"",
      "Pascual Perez made 33 starts during the 1983 season.",
      "Perez finished with 15 victories.",
      "Pascual Perez worked more than 200 innings.",
      "Perez recorded a respectable earned-run average while pitching at the top of Atlanta's rotation.",
      "Pascual Perez relies upon movement, deception and changing a hitter's eye level.",
      "His unpredictable mound behavior can energize teammates and irritate opponents.",
      "Perez is not afraid to challenge hitters inside.",
      "When his command is sharp, his changing deliveries make it difficult for hitters to establish comfortable timing.",
      "His personality makes every start feel different from a conventional pitching performance.",
      "Perez and Craig McMurtry tied for the Atlanta staff lead with 15 victories in 1983.",
    ],
  },
  "Craig McMurtry": {
    lines: [
      "Craig McMurtry's full name is Joe Craig McMurtry.",
      "McMurtry was born in Temple, Texas.",
      "Craig McMurtry attended McLennan Community College.",
      "Atlanta selected McMurtry in the first round of the January 1980 secondary draft.",
      "McMurtry developed quickly through the Braves' farm system.",
      "Craig McMurtry entered Atlanta's starting rotation as a rookie in 1983.",
      "McMurtry made 35 starts.",
      "Craig McMurtry appeared in 36 games overall.",
      "McMurtry finished with a 15-9 record.",
      "Craig McMurtry posted a 3.08 ERA.",
      "McMurtry worked 224 and two-thirds innings.",
      "Craig McMurtry completed six games.",
      "McMurtry recorded three shutouts.",
      "Craig McMurtry allowed only 13 home runs.",
      "McMurtry struck out 105 hitters.",
      "Craig McMurtry finished second in the 1983 National League Rookie of the Year voting.",
      "McMurtry also received votes in the National League Cy Young Award balloting.",
      "Craig McMurtry's success depends upon location and changing speeds more than overwhelming velocity.",
      "His ability to keep the ball in the park is particularly valuable at Atlanta-Fulton County Stadium.",
      "McMurtry showed unusual durability for a first-year pitcher.",
      "He enters 1984 with the expectations normally placed upon an established veteran rather than a second-year player.",
      "A hitter who becomes too aggressive against McMurtry can produce an easy fly ball or ground ball early in the count.",
    ],
  },
  "Rick Mahler": {
    lines: [
      "Rick Mahler's full name is Richard Keith Mahler.",
      "Mahler was born in Austin, Texas.",
      "Rick Mahler attended Trinity University.",
      "Atlanta selected Mahler in the seventh round of the 1975 amateur draft.",
      "Mahler is a right-handed pitcher.",
      "Rick Mahler made his major-league debut during the 1979 season.",
      "Mahler's younger brother Mickey also became a major-league pitcher.",
      "Rick Mahler has worked as both a starter and reliever for Atlanta.",
      "Mahler made 33 starts during the 1982 season.",
      "Rick Mahler pitched more than 200 innings that year.",
      "Mahler was part of the rotation that helped Atlanta win the National League West.",
      "Rick Mahler's role was greatly reduced during the 1983 season.",
      "Mahler appeared in 10 major-league games.",
      "Rick Mahler worked 14 and a third innings.",
      "Mahler posted a 5.02 ERA.",
      "Rick Mahler spent a substantial portion of the season with Triple-A Richmond.",
      "His previous workload proves that he can handle a regular starting assignment.",
      "Mahler relies upon control, changing speeds and inducing contact.",
      "Rick Mahler does not require large strikeout totals to pitch effectively.",
      "His experience starting important games makes him a useful fourth member of this exhibition rotation.",
      "Mahler enters 1984 attempting to regain the form and regular role he held during Atlanta's 1982 championship season.",
    ],
  },
  "Len Barker": {
    lines: [
      "Len Barker's full name is Leonard Harold Barker III.",
      "Barker was born at Fort Knox, Kentucky.",
      "Len Barker stands approximately six feet five inches tall.",
      "The Texas Rangers selected Barker in the third round of the 1973 amateur draft.",
      "Barker made his major-league debut with Texas during the 1976 season.",
      "Len Barker later joined the Cleveland Indians.",
      "Barker developed into one of the American League's leading strikeout pitchers.",
      "Len Barker led the American League with 187 strikeouts in 1980.",
      "Barker again led the league with 127 strikeouts during the shortened 1981 season.",
      "On May 15, 1981, Len Barker pitched a perfect game against the Toronto Blue Jays.",
      "Barker retired all 27 hitters he faced.",
      "Len Barker struck out 11 during the perfect game.",
      "No Toronto hitter reached a three-ball count.",
      "Barker was selected to the 1981 American League All-Star team.",
      "Len Barker won 15 games and struck out 187 hitters during the 1982 season.",
      "Atlanta acquired Barker from Cleveland on August 28, 1983.",
      "The Braves sent young outfielder Brett Butler and third baseman Brook Jacoby to Cleveland.",
      "Len Barker made six starts for Atlanta after the trade.",
      "Barker went 1-3 with a 3.82 ERA for the Braves.",
      "Len Barker finished the complete 1983 season with a 9-16 record and 4.88 ERA.",
      "Barker worked 182 and two-thirds innings between Cleveland and Atlanta.",
      "Len Barker struck out 126 hitters.",
      "Barker was affected by elbow trouble during the season.",
      "When healthy, his high fastball can overpower hitters at the top of the strike zone.",
      "His height allows him to deliver the ball on a steep downward plane.",
      "Barker's perfect game gives him the most celebrated single pitching performance on the Atlanta staff.",
    ],
  },
  "Donnie Moore": {
    lines: [
      "Donnie Moore's full name is Donnie Ray Moore.",
      "Moore was born in Lubbock, Texas.",
      "Donnie Moore attended Paris Junior College in Texas.",
      "The Chicago Cubs selected Moore in the first round of the January 1973 secondary draft.",
      "Moore made his major-league debut with the Cubs during the 1975 season.",
      "Donnie Moore later pitched for the St. Louis Cardinals and Milwaukee Brewers.",
      "Atlanta acquired Moore before the 1982 season.",
      "Donnie Moore is a right-handed pitcher.",
      "Moore relies heavily upon a hard slider.",
      "Donnie Moore's slider can move sharply away from a right-handed hitter.",
      "Moore can work more than one inning when necessary.",
      "Donnie Moore appeared in 43 games during the 1983 season.",
      "Moore provided middle- and late-inning relief rather than!serving as Atlanta's exclusive closer.",
      "Donnie Moore's experience in several organizations has exposed him to both leagues and many different hitters.",
      "His fastball-slider combination gives Atlanta a potential strikeout option in the ninth inning.",
      "Moore is capable of entering with runners already on base.",
      "Donnie Moore's ability to work extended relief makes him suitable for a 1984-style closer role rather than a modern one-inning assignment.",
      "A sharp slider beneath the strike zone is his best weapon when he needs a swing and miss.",
      "Your roster's designation of Moore as closer places his hard breaking ball at the center of Atlanta's late-game strategy.",
    ],
  },
  "Steve Bedrosian": {
    lines: [
      "Steve Bedrosian's full name is Stephen Wayne Bedrosian.",
      "Bedrosian was born in Methuen, Massachusetts.",
      "Steve Bedrosian is commonly known by the nickname \"Bedrock.\"",
      "Atlanta selected Bedrosian in the third round of the 1978 amateur draft.",
      "Bedrosian is a right-handed pitcher.",
      "Steve Bedrosian made his major-league debut during the 1981 season.",
      "Bedrosian became one of Atlanta's primary relievers.",
      "Steve Bedrosian worked in 64 games during the 1982 division-winning season.",
      "Bedrosian appeared in 70 games during the 1983 season.",
      "Steve Bedrosian finished with a 9-10 record.",
      "Bedrosian posted a 3.60 ERA.",
      "Steve Bedrosian recorded 19 saves.",
      "Bedrosian worked 120 innings despite making only one start.",
      "Steve Bedrosian struck out 114 hitters.",
      "Bedrosian allowed only 100 hits.",
      "His strikeout total approached one batter per inning.",
      "Steve Bedrosian led Atlanta in saves during the 1983 season.",
      "His ability to pitch multiple innings reflects the bullpen usage of the period.",
      "Bedrosian's fastball gives Atlanta a power arm before Donnie Moore.",
      "He can also close a game when Moore is unavailable.",
      "Bedrosian's nickname and aggressive delivery suit a pitcher used to attack the middle of an opposing lineup.",
      "He is capable of entering during the seventh inning and remaining through the final out.",
    ],
  },
  "Terry Forster": {
    lines: [
      "Terry Forster's full name is Terry Jay Forster.",
      "Forster was born in Sioux Falls, South Dakota.",
      "The Chicago White Sox selected Forster in the second round of the 1970 amateur draft.",
      "Terry Forster reached the major leagues at only 19 years old.",
      "Forster is a left-handed pitcher.",
      "Terry Forster became the White Sox closer early in his career.",
      "Forster led the American League with 24 saves during the 1974 season.",
      "He later pitched for the Pittsburgh Pirates and Los Angeles Dodgers.",
      "Terry Forster was a member of the Dodgers' 1981 World Series championship team.",
      "Forster is unusually accomplished as a hitter for a relief pitcher.",
      "Terry Forster had recorded a remarkably high career batting average through 1983.",
      "Atlanta signed Forster as a free agent before the 1983 season.",
      "Terry Forster appeared in 56 games during his first season with the Braves.",
      "Forster finished with a 3-2 record.",
      "Terry Forster posted an outstanding 2.16 ERA.",
      "Forster recorded 13 saves.",
      "Terry Forster worked 79 and a third innings.",
      "Forster allowed only 60 hits.",
      "Terry Forster struck out 54 hitters.",
      "He surrendered only three home runs.",
      "Forster can be used for a single dangerous left-handed hitter or remain for several innings.",
      "His previous closing experience makes him comfortable pitching in the ninth inning.",
      "Forster's hitting ability can occasionally allow Atlanta to avoid using a pinch-hitter during an extended relief appearance.",
      "His left-handed power arm gives the bullpen an important contrast to Moore and Bedrosian.",
    ],
  },
  "Gene Garber": {
    lines: [
      "Gene Garber's full name is Henry Eugene Garber.",
      "Garber was born in Elizabethtown, Pennsylvania.",
      "Gene Garber grew up working on his family's dairy farm.",
      "Garber attended Elizabethtown High School.",
      "Gene Garber played both shortstop and pitcher in high school.",
      "Garber once recorded 27 strikeouts during an 11-inning high-school game.",
      "Pittsburgh selected Gene Garber in the 20th round of the inaugural 1965 amateur draft.",
      "Garber later pitched for the Kansas City Royals and Philadelphia Phillies.",
      "Atlanta acquired Gene Garber from Philadelphia during the 1978 season.",
      "Garber uses an unusual delivery that includes a hesitation before releasing the ball.",
      "Gene Garber's changeup is especially effective because hitters must wait through the hesitation.",
      "On August 1, 1978, Garber struck out Pete Rose to end Rose's 44-game hitting streak.",
      "Gene Garber recorded 25 saves for Atlanta during the 1979 season.",
      "Garber became the Braves' primary closer again during the 1982 season.",
      "Gene Garber recorded a career-high 30 saves in 1982.",
      "He received votes in both the Cy Young and Most Valuable Player balloting.",
      "Garber battled inflammation around the ulnar nerve in his elbow during 1983.",
      "Gene Garber appeared in 43 games.",
      "Garber finished 4-5 with a 4.60 ERA.",
      "Gene Garber recorded nine saves.",
      "Garber worked 60 and two-thirds innings.",
      "Gene Garber struck out 45 hitters.",
      "Garber is comfortable pitching several innings rather than waiting only for the ninth.",
      "His hesitation delivery gives hitters a completely different visual challenge from Atlanta's harder throwers.",
      "Garber's closing experience makes him another legitimate ninth-inning option.",
      "His competitive intensity is demonstrated by his determination to personally face Rose with the historic hitting streak at stake.",
    ],
  },
  "Jeff Dedmon": {
    lines: [
      "Jeff Dedmon's full name is Jeffrey Linden Dedmon.",
      "Dedmon was born in Torrance, California.",
      "Jeff Dedmon attended West Los Angeles College.",
      "Dedmon was selected four different times during the amateur draft process.",
      "The Houston Astros selected Jeff Dedmon during the January 1979 draft.",
      "Oakland selected Dedmon during the June 1979 secondary draft.",
      "San Francisco selected Jeff Dedmon during the January 1980 secondary draft.",
      "Atlanta finally selected Dedmon with the fifth overall choice of the June 1980 secondary draft.",
      "Jeff Dedmon is a right-handed pitcher.",
      "Dedmon originally worked as a starting pitcher in the minor leagues.",
      "Atlanta later began developing Jeff Dedmon as a reliever.",
      "Dedmon pitched for both Double-A Savannah and Triple-A Richmond during the 1983 season.",
      "Jeff Dedmon made his major-league debut on September 2, 1983.",
      "Dedmon appeared in five games for Atlanta.",
      "Jeff Dedmon worked four innings.",
      "Dedmon allowed 10 hits and six earned runs.",
      "Jeff Dedmon posted a 13.50 ERA during the extremely brief trial.",
      "Dedmon did not issue a walk.",
      "Jeff Dedmon struck out three hitters.",
      "His four-inning sample is far too small to establish his true major-league ability.",
      "Opposing hitters possess almost no firsthand experience against him.",
      "Dedmon's minor-league starting background allows him to pitch more than one inning.",
      "He enters 1984 attempting to prove that his difficult September trial was not representative of his actual ability.",
      "Dedmon gives Atlanta a young relief arm behind a bullpen filled with experienced veterans.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive - base hit.\"",
    "\"Long drive to center field - way back - gone. Home run!\"",
    "\"Ground ball to short - over to first - in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub has some real talent - Murphy, Chambliss, Horner - the Braves can play with anybody.\"",
    "\"Atlanta baseball is alive and well - the fans here at Fulton County Stadium love their Braves.\"",
    "\"This team has power and pitching - Dale Murphy is the two-time MVP.\"",
    "\"Atlanta-Fulton County Stadium is home - and the Braves are ready to make some noise in the NL West.\"",
    "\"Dale Murphy is the most complete player in baseball - back-to-back MVPs.\"",
    "\"Bob Horner has some of the most dangerous right-handed power in the National League.\"",
    "\"Chris Chambliss brings a World Series pedigree to the middle of this lineup.\"",
    "\"There's talent everywhere you look in this lineup - the Braves can hurt you.\"",
    "\"This club won the West in '82 - Atlanta believes it can contend again.\"",
    "\"The fans in Atlanta have been waiting for another winner - they got a taste in '82.\"",
    "\"There's a buzz around the Braves this year - people can feel something building.\"",
    "\"From Murph to Horner to Perimeter Pascual - the Braves have characters at every position.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Dale Murphy won back-to-back MVPs - that's extraordinary. He's the best player in baseball right now.\"",
    "\"Bob Horner went straight from Arizona State to the major leagues - no minor-league games at all.\"",
    "\"Chris Chambliss hit the pennant-winning home run for the Yankees in '76 - he knows October baseball.\"",
    "\"Len Barker pitched a perfect game in 1981 - 27 up, 27 down, 11 strikeouts.\"",
    "\"Pascual Perez throws from every angle - and once got lost on I-285 trying to find the ballpark.\"",
    "\"Gene Garber struck out Pete Rose to end his 44-game hitting streak - that takes guts.\"",
    "\"Steve Bedrosian struck out 114 hitters in 120 innings - that's electric stuff.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Atlanta-Fulton County Stadium.\"",
    "\"The lights are on at Fulton County - Braves baseball tonight.\"",
    "Atlanta-Fulton County Stadium - home of the Braves since 1966.",
    "\"The warm Southern air is perfect for baseball tonight.\"",
    "\"The stands are filling up nicely - Atlanta loves its Braves.\"",
    "\"You can feel the energy in this ballpark - the fans are into this one.\"",
    "\"Fulton County Stadium is rocking tonight - the crowd is fired up.\"",
    "\"The Atlanta skyline is visible beyond the outfield - a beautiful backdrop on a clear night.\"",
    "\"The faithful at Fulton County are some of the most passionate fans in baseball.\"",
    "\"A perfect evening for baseball in the Deep South.\"",
    "\"The humidity is thick tonight - the ball should carry well in this air.\"",
    "\"Baseball in the South - there's nothing quite like a summer night at Fulton County.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here at Fulton County is into this ballgame.\"",
    "\"Braves fans are making some noise tonight.\"",
    "\"The fans in Atlanta are fired up tonight - they love their Braves.\"",
    "\"Fulton County Stadium is rocking tonight.\"",
    "\"Atlanta fans are among the most passionate in the South - they've been waiting for a winner.\"",
    "\"The crowd is on its feet - they can feel something building here.\"",
    "\"A great turnout at Fulton County tonight.\"",
    "\"These fans love their Braves - from Murph to Horner to Chambliss.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Atlanta-Fulton County Stadium, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball in Atlanta.\"",
    "\"From all of us here in the Deep South, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story - that's the beauty of this sport.\"",
    "\"Baseball in Atlanta - it's a tradition that's growing every year.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone - into the night at Fulton County!\"",
    "\"Touch 'em all, Murph!\"",
    "\"The Braves are making their move here at Fulton County.\"",
    "\"And Atlanta wins it - what a finish!\"",
    "\"You won't see many better than that one.\"",
    "\"Holy cow, what a ballgame!\"",
  ]},
};