// Milwaukee Brewers Broadcast — 1984
// Radio: Bob Uecker & Pat Hughes (WTMJ) / TV: Merle Harmon & Dwayne Mosley
// County Stadium — home of the Brewers
// All stats cutoff: end of 1983 season

export function pickBrewersLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickBrewersPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Robin Yount": {
    lines: [
      "Robin Yount's full name is Robin R. Yount.",
      "Robin Yount is commonly known by the nickname \"The Kid.\"",
      "Robin Yount batted .455 during his final high-school season in California.",
      "Robin Yount was selected by Milwaukee with the third overall pick of the 1973 amateur draft.",
      "Robin Yount signed with Milwaukee shortly after graduating from high school.",
      "Robin Yount made his major-league debut during the 1974 season at only 18 years old.",
      "Robin Yount quickly became Milwaukee's regular shortstop.",
      "Robin Yount won the 1982 American League Most Valuable Player Award.",
      "Robin Yount batted .331 with 210 hits during his MVP season.",
      "Robin Yount recorded 46 doubles, 12 triples and 29 home runs in 1982.",
      "Robin Yount drove in 114 runs and scored 129 times during the 1982 season.",
      "Robin Yount hit two home runs in Milwaukee's division-clinching victory over Baltimore on the final day of the 1982 regular season.",
      "Robin Yount collected 11 hits during the 1982 World Series.",
      "Robin Yount followed his MVP season by batting .308 in 1983.",
      "Robin Yount recorded 178 hits, 42 doubles and 10 triples during the 1983 season.",
      "Robin Yount hit 17 home runs and drove in 80 runs in 1983.",
      "Robin Yount scored 102 runs and drew 72 walks during the 1983 season.",
      "Robin Yount combines the range of a shortstop with the offensive production of a middle-of-the-order hitter.",
      "Robin Yount can hit for average, power or extra bases into either outfield gap.",
      "Robin Yount is still only 28 years old entering the 1984 season.",
      "Robin Yount has already played ten major-league seasons despite being younger than many recent rookies.",
      "Robin Yount remains the player around whom Milwaukee's lineup is built.",
    ],
  },
  "Jim Gantner": {
    lines: [
      "Jim Gantner's full name is James Elmer Gantner.",
      "Jim Gantner was born in Fond du Lac, Wisconsin.",
      "Jim Gantner grew up in nearby Eden as one of nine children.",
      "Jim Gantner listened to the Milwaukee Braves on the radio while growing up.",
      "Jim Gantner pretended to be Eddie Mathews, Hank Aaron and Johnny Logan while practicing with a rubber ball.",
      "Jim Gantner played college baseball at the University of Wisconsin-Oshkosh.",
      "Jim Gantner's first trip in an airplane came when his college team traveled to an NAIA tournament.",
      "Milwaukee selected Jim Gantner in the 12th round of the 1974 amateur draft.",
      "Jim Gantner originally played shortstop but learned second and third base because Robin Yount occupied shortstop.",
      "Jim Gantner's first major-league at-bat came against Mark \"The Bird\" Fidrych.",
      "Jim Gantner collected his first major-league hit off Fidrych.",
      "Jim Gantner had the opportunity to play alongside his childhood hero, Hank Aaron, in Milwaukee.",
      "Jim Gantner is commonly known by the nickname \"Gumby.\"",
      "Jim Gantner was regarded as the heart and soul of Milwaukee's 1982 pennant-winning club.",
      "Jim Gantner scored one of the go-ahead runs in Game Five of the 1982 American League Championship Series.",
      "Jim Gantner played 161 games during the 1983 season.",
      "Jim Gantner batted .282 with 170 hits in 1983.",
      "Jim Gantner collected 23 doubles and eight triples during the 1983 season.",
      "Jim Gantner established career highs with 11 home runs and 74 RBI in 1983.",
      "Jim Gantner scored 85 runs during the 1983 season.",
      "Jim Gantner gives Milwaukee a dependable left-handed hitter in the middle infield.",
      "Jim Gantner is willing to dive, take an extra base and play through minor injuries.",
      "Jim Gantner is one of the rare Wisconsin natives to become a regular for the Brewers.",
    ],
  },
  "Cecil Cooper": {
    lines: [
      "Cecil Cooper's full name is Cecil Celester Cooper.",
      "Cecil Cooper was born in Brenham, Texas.",
      "Cecil Cooper began his major-league career with the Boston Red Sox.",
      "Cecil Cooper appeared in the 1975 World Series with Boston.",
      "Cecil Cooper was traded to Milwaukee after the 1976 season.",
      "Milwaukee acquired Cecil Cooper in a deal involving George Scott and Bernie Carbo.",
      "Cecil Cooper developed into one of the American League's most productive first basemen.",
      "Cecil Cooper batted .352 with 219 hits during the 1980 season.",
      "Cecil Cooper drove in more than 100 runs in four consecutive seasons from 1980 through 1983.",
      "Cecil Cooper delivered the go-ahead two-run single in Game Five of the 1982 American League Championship Series.",
      "Cecil Cooper helped send Milwaukee to its first World Series.",
      "Cecil Cooper appeared in 160 games during the 1983 season.",
      "Cecil Cooper batted .307 with 203 hits in 1983.",
      "Cecil Cooper recorded 37 doubles and three triples during the 1983 season.",
      "Cecil Cooper hit 30 home runs and drove in 126 runs in 1983.",
      "Cecil Cooper scored 106 runs during the 1983 season.",
      "Cecil Cooper was selected to the American League All-Star team in 1983.",
      "Cecil Cooper is a line-drive hitter who can drive the ball from foul line to foul line.",
      "Cecil Cooper uses a smooth left-handed swing rather than an exaggerated uppercut.",
      "Cecil Cooper is capable of hitting a difficult pitch into the opposite-field gap.",
      "Cecil Cooper's quiet personality contrasts with the damage he can do at the plate.",
      "Cecil Cooper remains one of Milwaukee's most reliable hitters with runners in scoring position.",
    ],
  },
  "Ben Oglivie": {
    lines: [
      "Ben Oglivie was born in Colon, Panama.",
      "Ben Oglivie studied music, philosophy and several other subjects away from baseball.",
      "Ben Oglivie has read extensively about philosophy and Zen Buddhism.",
      "Ben Oglivie played soccer while growing up in Panama.",
      "Ben Oglivie began his major-league career with the Boston Red Sox.",
      "Ben Oglivie also played for Detroit before joining Milwaukee.",
      "Ben Oglivie was sometimes called \"Spiderman\" because of his long arms and thin build.",
      "Ben Oglivie was also known as \"Banana Man\" after teammates noticed how many bananas he ate on a road trip.",
      "Ben Oglivie is frequently called \"Benji\" by Milwaukee teammates and fans.",
      "Ben Oglivie enjoyed his finest season in 1980.",
      "Ben Oglivie batted .304 with 41 home runs and 118 RBI during the 1980 season.",
      "Ben Oglivie's 41 home runs tied for the American League lead in 1980.",
      "Ben Oglivie won a Silver Slugger Award in 1980.",
      "Ben Oglivie was an American League All-Star in 1980, 1982 and 1983.",
      "Ben Oglivie hit three home runs in one game against Detroit on June 20, 1982.",
      "Ben Oglivie made a crucial diving catch during Milwaukee's 1982 division-clinching victory in Baltimore.",
      "Ben Oglivie appeared in 125 games during the 1983 season.",
      "Ben Oglivie batted .280 with a .371 on-base percentage in 1983.",
      "Ben Oglivie hit 13 home runs and drove in 66 runs during the 1983 season.",
      "Ben Oglivie drew 60 walks in 1983.",
      "Ben Oglivie uses an unusual stance and a powerful left-handed swing.",
      "Ben Oglivie's calm, thoughtful personality can make his intensity easy to underestimate.",
      "Ben Oglivie has enough power to reach the seats even when he does not appear to swing especially hard.",
    ],
  },
  "Ted Simmons": {
    lines: [
      "Ted Simmons' full name is Ted Lyle Simmons.",
      "Ted Simmons is commonly known by the nickname \"Simba.\"",
      "Ted Simmons was born in Highland Park, Michigan.",
      "Ted Simmons was an outstanding baseball, basketball and football player in high school.",
      "Ted Simmons received offers to play college football from several major universities.",
      "Ted Simmons began learning to switch-hit at approximately 13 years old.",
      "Ted Simmons was selected by St. Louis in the first round of the 1967 amateur draft.",
      "Ted Simmons reached the major leagues with the Cardinals while still a teenager.",
      "Ted Simmons developed into one of baseball's finest offensive catchers.",
      "Ted Simmons batted at least .300 in seven different seasons through 1983.",
      "Ted Simmons was acquired by Milwaukee in the December 1980 trade that also brought Rollie Fingers and Pete Vuckovich.",
      "Ted Simmons helped Milwaukee reach the postseason in both 1981 and 1982.",
      "Ted Simmons divided his 1983 playing time between catcher and designated hitter.",
      "Ted Simmons batted .308 during the 1983 season.",
      "Ted Simmons drove in a career-high 108 runs in 1983.",
      "Ted Simmons collected his 2,000th major-league hit with a double against the Yankees on June 12, 1983.",
      "Ted Simmons was selected to his eighth All-Star team in 1983.",
      "Ted Simmons is capable of driving the ball from either side of the plate.",
      "Ted Simmons is particularly difficult to pitch around because he protects the plate with two strikes.",
      "Ted Simmons brings extensive knowledge of American and National League pitchers.",
      "Ted Simmons can remain in the lineup as the designated hitter when he needs a rest from catching.",
      "Ted Simmons provides Milwaukee with a veteran run producer behind Yount, Cooper and Oglivie.",
    ],
  },
  "Dion James": {
    lines: [
      "Dion James was born in Philadelphia and attended high school in Sacramento, California.",
      "Dion James attended McClatchy High School in Sacramento.",
      "Milwaukee selected Dion James in the first round of the 1980 amateur draft.",
      "Dion James was the 25th overall selection in that draft.",
      "Dion James bats left-handed and throws left-handed.",
      "Dion James advanced to Triple-A Vancouver at only 20 years old.",
      "Dion James played 129 games for Vancouver during the 1983 season.",
      "Dion James batted .336 with a .413 on-base percentage for Vancouver in 1983.",
      "Dion James collected 157 hits, including 29 doubles and five triples, in 1983.",
      "Dion James hit eight home runs and drove in 68 runs for Vancouver.",
      "Dion James scored 84 runs and stole 22 bases during his Triple-A season.",
      "Dion James made his major-league debut on September 16, 1983.",
      "Dion James was 20 years old when he first appeared for Milwaukee.",
      "Dion James appeared in 11 games during his first major-league trial.",
      "Dion James collected two hits, scored one run and drove in one run in 1983.",
      "Dion James gives Milwaukee a young left-handed hitter with speed and plate discipline.",
      "Dion James can play both center field and a corner-outfield position.",
      "Dion James enters 1984 as one of the youngest players on the Milwaukee roster.",
      "Dion James is still learning major-league pitching after spending nearly all of 1983 in Triple-A.",
    ],
  },
  "Rick Manning": {
    lines: [
      "Rick Manning's full name is Richard Eugene Manning.",
      "Rick Manning was selected by Cleveland with the second overall pick of the 1972 amateur draft.",
      "Rick Manning reached the major leagues with Cleveland during the 1975 season.",
      "Rick Manning quickly became Cleveland's regular center fielder.",
      "Rick Manning won an American League Gold Glove Award in 1976.",
      "Rick Manning is known primarily for speed, range and defensive instincts.",
      "Rick Manning spent more than eight seasons in the Cleveland organization.",
      "Rick Manning was traded from Cleveland to Milwaukee on June 6, 1983.",
      "Rick Manning came to Milwaukee with pitcher Rick Waits.",
      "Milwaukee sent Gorman Thomas, Ernie Camacho and Jamie Easterly to Cleveland in the transaction.",
      "Rick Manning appeared in 108 games between Cleveland and Milwaukee during the 1983 season.",
      "Rick Manning collected 86 hits, including 14 doubles and four triples, in 1983.",
      "Rick Manning stole 11 bases during the 1983 season.",
      "Rick Manning can cover both outfield gaps from center field.",
      "Rick Manning is capable of reaching fly balls that appear destined to fall safely.",
      "Rick Manning can be used near the top or bottom of the batting order.",
      "Rick Manning gives Milwaukee an experienced defensive center fielder behind a powerful infield.",
      "Rick Manning's ability to run down fly balls can help pitchers who allow considerable contact.",
    ],
  },
  "Jim Sundberg": {
    lines: [
      "Jim Sundberg is commonly known by the nickname \"Sunny.\"",
      "Jim Sundberg played college baseball at the University of Iowa.",
      "Texas selected Jim Sundberg during the 1973 secondary draft.",
      "Jim Sundberg reached the major leagues with the Rangers during the 1974 season.",
      "Jim Sundberg became Texas' regular catcher almost immediately.",
      "Jim Sundberg was selected to two American League All-Star teams before joining Milwaukee.",
      "Jim Sundberg won six consecutive Gold Glove Awards from 1976 through 1981.",
      "Jim Sundberg is regarded as one of the finest defensive catchers in baseball.",
      "Jim Sundberg is especially skilled at blocking pitches in the dirt.",
      "Jim Sundberg has a quick release when throwing to second base.",
      "Jim Sundberg is comfortable directing veteran and inexperienced pitchers.",
      "Jim Sundberg appeared in 131 games for Texas during the 1983 season.",
      "Jim Sundberg collected 76 hits, 14 doubles, two home runs and 28 RBI in 1983.",
      "Jim Sundberg drew 35 walks during the 1983 season.",
      "Jim Sundberg was acquired by Milwaukee following the 1983 season.",
      "Jim Sundberg allows Ted Simmons to spend more time at designated hitter.",
      "Jim Sundberg's defensive reputation can discourage opponents from attempting stolen bases.",
      "Jim Sundberg provides Milwaukee's pitching staff with an experienced game caller.",
      "Jim Sundberg is willing to absorb foul tips, block the plate and work in the dirt throughout a game.",
    ],
  },
  "Ed Romero": {
    lines: [
      "Ed Romero's full name is Edgardo Ralph Romero.",
      "Ed Romero was born in Santurce, Puerto Rico.",
      "Ed Romero began his professional career in Milwaukee's farm system.",
      "Ed Romero played for the Class A Burlington Bees during the 1976 season.",
      "Ed Romero first reached the major leagues with Milwaukee in 1977.",
      "Ed Romero returned to Milwaukee's major-league roster during the 1980 season.",
      "Ed Romero can play shortstop, second base and third base.",
      "Ed Romero has also appeared at first base and in the outfield when needed.",
      "Ed Romero appeared in 59 games during the 1983 season.",
      "Ed Romero batted a career-high .317 in 1983.",
      "Ed Romero collected 46 hits in 145 at-bats during the 1983 season.",
      "Ed Romero recorded seven doubles, one home run and 18 RBI in 1983.",
      "Ed Romero scored 17 runs during the 1983 season.",
      "Ed Romero struck out only eight times in 145 at-bats in 1983.",
      "Ed Romero is valuable because he can move around the infield without disrupting the lineup.",
      "Ed Romero is a contact hitter who usually puts the ball in play.",
      "Ed Romero can start for an injured infielder or enter late for defensive purposes.",
      "Ed Romero's versatility allows Milwaukee to carry an additional specialist on the bench.",
    ],
  },
  "Charlie Moore": {
    lines: [
      "Charlie Moore's full name is Charles William Moore.",
      "Charlie Moore was born in Birmingham, Alabama.",
      "Charlie Moore has played his entire major-league career with Milwaukee through 1983.",
      "Charlie Moore began his career primarily as a catcher.",
      "Charlie Moore later learned to play right field to create additional playing opportunities.",
      "Charlie Moore has one of the stronger throwing arms among Milwaukee's outfielders.",
      "Charlie Moore can catch, play right field and serve as the designated hitter.",
      "Charlie Moore became an important part of Milwaukee's 1982 postseason run.",
      "Charlie Moore batted .462 in the 1982 American League Championship Series.",
      "Charlie Moore collected six hits in 13 at-bats against the California Angels.",
      "Charlie Moore batted .346 with three doubles during the 1982 World Series.",
      "Charlie Moore appeared in a career-high 151 games during the 1983 season.",
      "Charlie Moore received a career-high 605 plate appearances in 1983.",
      "Charlie Moore batted .284 during the 1983 season.",
      "Charlie Moore gives Milwaukee a third experienced catcher behind Sundberg and Simmons.",
      "Charlie Moore is capable of replacing an injured player at several positions.",
      "Charlie Moore's speed is better than might be expected from a player with extensive catching experience.",
      "Charlie Moore can be used as a pinch-hitter, defensive replacement or occasional starter.",
    ],
  },
  "Randy Ready": {
    lines: [
      "Randy Ready's full name is Randy Max Ready.",
      "Randy Ready was born in Fremont, California.",
      "Randy Ready played college baseball at Mesa State College in Colorado.",
      "Milwaukee selected Randy Ready in the sixth round of the 1980 amateur draft.",
      "Randy Ready was the 155th overall selection in that draft.",
      "Randy Ready batted .308 with a .439 on-base percentage for Burlington in 1981.",
      "Randy Ready hit 17 home runs and scored 74 runs during that 1981 minor-league season.",
      "Randy Ready developed as a second baseman and third baseman.",
      "Randy Ready made his major-league debut on September 4, 1983.",
      "Randy Ready appeared in 12 games during his first major-league trial.",
      "Randy Ready collected 15 hits in 37 at-bats during the 1983 season.",
      "Randy Ready batted .405 with a .488 on-base percentage in 1983.",
      "Randy Ready recorded three doubles, two triples and one home run in 1983.",
      "Randy Ready scored eight runs and drove in six during his first major-league month.",
      "Randy Ready drew six walks while striking out only three times in 1983.",
      "Randy Ready gives Milwaukee a young right-handed option at second or third base.",
      "Randy Ready's strong September performance has earned him a serious opportunity entering 1984.",
      "Randy Ready's last name naturally lends itself to scoreboard and announcer wordplay.",
    ],
  },
  "Mark Brouhard": {
    lines: [
      "Mark Brouhard's full name is Mark Steven Brouhard.",
      "Mark Brouhard was born in Burbank, California.",
      "Mark Brouhard played catcher during portions of his amateur career.",
      "Mark Brouhard was converted primarily into an outfielder after turning professional.",
      "Mark Brouhard was selected by the California Angels in the fourth round of the January 1976 draft.",
      "Mark Brouhard once hit a minor-league home run estimated at more than 500 feet.",
      "The enormous home run helped earn Mark Brouhard the nickname \"Mad Bomber.\"",
      "Mark Brouhard is also affectionately known as \"Big Bro.\"",
      "Mark Brouhard batted .350 with 28 home runs and 107 RBI at Double-A El Paso in 1979.",
      "Milwaukee selected Mark Brouhard from the Angels organization in the 1979 Rule 5 Draft.",
      "Mark Brouhard had to remain on Milwaukee's major-league roster throughout the 1980 season.",
      "Mark Brouhard started Game Four of the 1982 American League Championship Series with Milwaukee facing elimination.",
      "Mark Brouhard went 3-for-4 with a double and a two-run home run in that game.",
      "Mark Brouhard drove in three runs and scored four times as Milwaukee defeated California.",
      "Mark Brouhard appeared in 56 games for Milwaukee during the 1983 season.",
      "Mark Brouhard batted .276 with 10 doubles and seven home runs in 1983.",
      "Mark Brouhard drove in 23 runs during the 1983 season.",
      "Mark Brouhard provides right-handed power from the bench.",
      "Mark Brouhard can play either corner-outfield position and fill in at first base.",
      "Mark Brouhard is capable of changing a game despite receiving only one or two plate appearances.",
    ],
  },
  "Roy Howell": {
    lines: [
      "Roy Howell's full name is Roy Lee Howell.",
      "Roy Howell was born in Lompoc, California.",
      "Texas selected Roy Howell with the fourth overall pick of the 1972 amateur draft.",
      "Roy Howell reached the major leagues with the Rangers during the 1974 season.",
      "Roy Howell was traded from Texas to Toronto during the 1977 season.",
      "Roy Howell became the Blue Jays' regular third baseman.",
      "Roy Howell was selected to the 1978 American League All-Star team.",
      "Roy Howell joined Milwaukee as a free agent before the 1981 season.",
      "Roy Howell has played third base, first base and designated hitter for Milwaukee.",
      "Roy Howell appeared in 69 games during the 1983 season.",
      "Roy Howell batted .278 with a .330 on-base percentage in 1983.",
      "Roy Howell collected 54 hits, including nine doubles and six triples, in 1983.",
      "Roy Howell hit four home runs and drove in 25 runs during the 1983 season.",
      "Roy Howell slugged .448 in 1983.",
      "Roy Howell provides an experienced left-handed hitter from the bench.",
      "Roy Howell can start against a difficult right-handed pitcher.",
      "Roy Howell is capable of driving a pitch into either outfield gap.",
      "Roy Howell's ability to play both corner-infield positions adds flexibility to Milwaukee's bench.",
    ],
  },
  "Paul Molitor": {
    lines: [
      "Paul Molitor's full name is Paul Leo Molitor.",
      "Paul Molitor was born in St. Paul, Minnesota.",
      "Paul Molitor is commonly called \"Paulie\" or \"Mollie\" by teammates.",
      "Paul Molitor is also known by the nickname \"The Ignitor.\"",
      "Paul Molitor played college baseball at the University of Minnesota.",
      "Milwaukee selected Paul Molitor with the third overall pick of the 1977 amateur draft.",
      "Paul Molitor reached the major leagues during the 1978 season.",
      "Paul Molitor finished second in the 1978 American League Rookie of the Year voting.",
      "Paul Molitor has played shortstop, second base, center field and third base.",
      "Paul Molitor is considered one of baseball's most instinctive baserunners.",
      "Paul Molitor stole 41 bases during Milwaukee's 1982 pennant-winning season.",
      "Paul Molitor collected five hits in Game One of the 1982 World Series.",
      "Paul Molitor's five-hit performance established a World Series single-game record.",
      "Paul Molitor batted .355 during the 1982 World Series.",
      "Paul Molitor appeared in 152 games during the 1983 season despite suffering a wrist injury.",
      "Paul Molitor batted .270 with 164 hits in 1983.",
      "Paul Molitor recorded 28 doubles, six triples and 15 home runs during the 1983 season.",
      "Paul Molitor scored 95 runs and stole 41 bases in 1983.",
      "Paul Molitor can enter as a pinch-hitter, pinch-runner or defensive replacement at several positions.",
      "Paul Molitor's speed can change the game immediately when he reaches base.",
      "Paul Molitor's placement on the bench reflects his physical condition entering 1984, not a lack of ability.",
      "A healthy Paul Molitor remains one of Milwaukee's most dangerous all-around players.",
    ],
  },
  "Mike Caldwell": {
    lines: [
      "Mike Caldwell's full name is Ralph Michael Caldwell.",
      "Mike Caldwell is a left-handed pitcher from Tarboro, North Carolina.",
      "Mike Caldwell is commonly known by the ironic nickname \"Mr. Warmth.\"",
      "Mike Caldwell earned the nickname partly because of his intense and sometimes fiery mound personality.",
      "Mike Caldwell began his major-league career with the San Diego Padres.",
      "Mike Caldwell also pitched briefly for San Francisco and Cincinnati before joining Milwaukee.",
      "Mike Caldwell produced the finest season of his career in 1978.",
      "Mike Caldwell went 22-9 with a 2.36 ERA during the 1978 season.",
      "Mike Caldwell led the American League with 23 complete games in 1978.",
      "Mike Caldwell finished second in the 1978 American League Cy Young Award voting.",
      "Mike Caldwell was named the American League Comeback Player of the Year in 1978.",
      "Mike Caldwell went 16-6 with a 3.29 ERA in 1979.",
      "Mike Caldwell won Game One and Game Five of the 1982 World Series.",
      "Mike Caldwell pitched a complete-game shutout in the opening game of that World Series.",
      "Mike Caldwell made 32 starts during the 1983 season.",
      "Mike Caldwell went 12-11 with a 4.53 ERA in 1983.",
      "Mike Caldwell threw 228 and a third innings during the 1983 season.",
      "Mike Caldwell completed 10 games and recorded two shutouts in 1983.",
      "Mike Caldwell relies on movement, control and changing speeds rather than pure velocity.",
      "Mike Caldwell works quickly and challenges hitters inside.",
      "Mike Caldwell remains one of Milwaukee's most experienced postseason pitchers.",
    ],
  },
  "Moose Haas": {
    lines: [
      "Moose Haas' full name is Bryan Edmund Haas.",
      "Moose Haas was born in Baltimore, Maryland.",
      "Milwaukee selected Moose Haas in the second round of the 1974 amateur draft.",
      "Moose Haas reached the major leagues with Milwaukee during the 1976 season.",
      "Moose Haas has spent his entire major-league career with the Brewers through 1983.",
      "Moose Haas developed into one of Milwaukee's most dependable starting pitchers.",
      "Moose Haas struck out 14 hitters in a game during the 1978 season.",
      "Reggie Jackson struck out four times against Moose Haas in that performance.",
      "Moose Haas started Game Four of the 1982 American League Championship Series.",
      "Moose Haas helped Milwaukee avoid elimination with a strong performance against California.",
      "Moose Haas made 25 starts during the 1983 season.",
      "Moose Haas went 13-3 with a 3.27 ERA in 1983.",
      "Moose Haas' .813 winning percentage led the American League in 1983.",
      "Moose Haas threw 179 innings during the 1983 season.",
      "Moose Haas completed seven games and recorded three shutouts in 1983.",
      "Moose Haas allowed only 12 home runs during the 1983 season.",
      "Moose Haas recorded consecutive shutouts during August 1983.",
      "Moose Haas won at least 10 games in five consecutive seasons through 1983.",
      "Moose Haas attacks hitters with a mixture of fastballs, breaking pitches and changing speeds.",
      "Moose Haas is capable of working efficiently deep into a game.",
      "Moose Haas gives Milwaukee a right-handed contrast to left-hander Mike Caldwell.",
    ],
  },
  "Don Sutton": {
    lines: [
      "Don Sutton's full name is Donald Howard Sutton.",
      "Don Sutton was born in Clio, Alabama.",
      "Don Sutton grew up in Florida and signed with the Los Angeles Dodgers.",
      "Don Sutton reached the major leagues with Los Angeles during the 1966 season.",
      "Don Sutton spent 15 seasons in the Dodgers' starting rotation.",
      "Don Sutton won at least 10 games in each of his first 17 major-league seasons.",
      "Don Sutton pitched in four World Series with the Dodgers.",
      "Don Sutton later pitched for Houston before joining Milwaukee.",
      "Milwaukee acquired Don Sutton during the 1982 pennant race.",
      "Don Sutton joined the Brewers on August 30, 1982.",
      "Don Sutton pitched a complete game in Milwaukee's division-clinching victory over Baltimore.",
      "Don Sutton defeated Jim Palmer in that decisive final regular-season game.",
      "Don Sutton entered the 1983 season with more than 250 major-league victories.",
      "Don Sutton made 31 starts for Milwaukee during the 1983 season.",
      "Don Sutton went 8-13 with a 4.08 ERA in 1983.",
      "Don Sutton threw 220 and a third innings during the 1983 season.",
      "Don Sutton completed four games and struck out 134 hitters in 1983.",
      "Don Sutton walked only 54 hitters during the 1983 season.",
      "Don Sutton relies on command, preparation and the ability to change speeds.",
      "Don Sutton is comfortable pitching to a hitter's weaknesses rather than relying on one overpowering pitch.",
      "Don Sutton gives Milwaukee considerable experience at the front of the rotation.",
    ],
  },
  "Jaime Cocanower": {
    lines: [
      "Jaime Cocanower's full name is James Stanley Cocanower.",
      "Jaime Cocanower was born in San Juan, Puerto Rico.",
      "Jaime Cocanower is a tall right-handed pitcher.",
      "Milwaukee selected Jaime Cocanower during the 1978 amateur draft.",
      "Jaime Cocanower went 17-5 with a 2.18 ERA for Class A Stockton in 1980.",
      "Jaime Cocanower made 27 starts and threw 198 innings during that 1980 season.",
      "Jaime Cocanower allowed only 143 hits in 198 innings for Stockton.",
      "Jaime Cocanower advanced to Triple-A Vancouver.",
      "Jaime Cocanower made 23 starts for Vancouver during the 1983 season.",
      "Jaime Cocanower went 10-10 with a 4.81 ERA in 1983.",
      "Jaime Cocanower threw 153 and a third innings and completed five games for Vancouver.",
      "Jaime Cocanower struck out 79 hitters during the 1983 minor-league season.",
      "Jaime Cocanower made his major-league debut on September 7, 1983.",
      "Jaime Cocanower enters 1984 seeking his first full major-league season.",
      "Jaime Cocanower's height allows him to release the baseball from a steep angle.",
      "Jaime Cocanower is most effective when he keeps his fastball near the bottom of the strike zone.",
      "Jaime Cocanower's primary challenge is maintaining consistent control.",
      "Jaime Cocanower gives Milwaukee a younger alternative to its veteran starters.",
    ],
  },
  "Rollie Fingers": {
    lines: [
      "Rollie Fingers' full name is Roland Glen Fingers.",
      "Rollie Fingers was born in Steubenville, Ohio.",
      "Rollie Fingers is instantly recognizable because of his curled handlebar mustache.",
      "Rollie Fingers developed the mustache while playing for Oakland owner Charlie Finley.",
      "Rollie Fingers helped Oakland win three consecutive World Series from 1972 through 1974.",
      "Rollie Fingers was named the Most Valuable Player of the 1974 World Series.",
      "Rollie Fingers later pitched for the San Diego Padres.",
      "Milwaukee acquired Rollie Fingers from St. Louis in December 1980.",
      "Rollie Fingers recorded 28 saves during the strike-shortened 1981 season.",
      "Rollie Fingers won both the American League Cy Young Award and Most Valuable Player Award in 1981.",
      "Rollie Fingers preserved nearly half of Milwaukee's victories during that 1981 season.",
      "Rollie Fingers recorded the final out when Milwaukee clinched its first postseason berth.",
      "Rollie Fingers relies heavily on a sharp slider in late-inning situations.",
      "Rollie Fingers tore a muscle in his right forearm during September 1982.",
      "The injury prevented Rollie Fingers from pitching in the 1982 postseason.",
      "Rollie Fingers did not appear in a regular-season game during 1983 while recovering.",
      "Rollie Fingers enters 1984 attempting to reclaim Milwaukee's closer position.",
      "Rollie Fingers has more experience in championship games than any other Milwaukee reliever.",
      "Rollie Fingers is accustomed to entering with runners on base rather than beginning a clean ninth inning.",
      "Rollie Fingers helped redefine the relief ace as a major part of a championship pitching staff.",
    ],
  },
  "Pete Ladd": {
    lines: [
      "Pete Ladd's full name is Peter Linwood Ladd.",
      "Pete Ladd was born in Portland, Maine.",
      "Boston selected Pete Ladd in the 25th round of the 1977 amateur draft.",
      "Pete Ladd was traded to Houston during the 1979 season.",
      "Pete Ladd made his major-league debut with the Astros in August 1979.",
      "Milwaukee acquired Pete Ladd before the 1982 season.",
      "Pete Ladd received an expanded late-inning role after Rollie Fingers was injured.",
      "Pete Ladd recorded the final outs of Milwaukee's 1982 American League Championship Series victory.",
      "Pete Ladd helped protect Milwaukee's one-run lead in the decisive fifth game.",
      "Pete Ladd became Milwaukee's primary closer during the 1983 season.",
      "Pete Ladd appeared in 44 games in 1983.",
      "Pete Ladd went 3-4 with a 2.55 ERA during the 1983 season.",
      "Pete Ladd recorded 25 saves in 1983.",
      "Pete Ladd allowed only 30 hits in 49 and a third innings during the 1983 season.",
      "Pete Ladd struck out 41 hitters while walking 16 in 1983.",
      "Pete Ladd posted a 0.93 WHIP during the 1983 season.",
      "Pete Ladd attacks hitters with a hard fastball and late-breaking pitches.",
      "Pete Ladd can continue as closer if Rollie Fingers is unavailable.",
      "Pete Ladd has already demonstrated that he can record important postseason outs.",
    ],
  },
  "Ray Searage": {
    lines: [
      "Ray Searage's full name is Raymond Mark Searage.",
      "Ray Searage was born in Freeport, New York.",
      "Ray Searage is a left-handed relief pitcher.",
      "Ray Searage developed in the New York Mets organization.",
      "Ray Searage made his major-league debut on June 11, 1981.",
      "Ray Searage's debut came only hours before the beginning of the 1981 players strike.",
      "Ray Searage appeared in 26 games for the Mets during the 1981 season.",
      "Ray Searage went 1-0 with one save and a 3.68 ERA in 1981.",
      "Ray Searage pitched 36 and two-thirds innings during his first major-league season.",
      "Ray Searage was traded from the Mets to Cleveland before the 1982 season.",
      "Ray Searage pitched primarily at Triple-A while in the Cleveland organization.",
      "Ray Searage worked as both a starter and reliever in the minor leagues.",
      "Ray Searage gives Milwaukee a left-handed bullpen option entering 1984.",
      "Ray Searage can be used against a difficult left-handed hitter or remain for a full inning.",
      "Ray Searage's path back to the majors depends upon improved control.",
      "Ray Searage is most effective when he keeps the ball away from right-handed hitters.",
    ],
  },
  "Tom Tellmann": {
    lines: [
      "Tom Tellmann's full name is Thomas John Tellmann.",
      "Tom Tellmann was born in Warren, Pennsylvania.",
      "Tom Tellmann played college baseball at Grand Canyon University.",
      "San Diego selected Tom Tellmann in the 11th round of the 1976 amateur draft.",
      "Tom Tellmann developed as a starting pitcher in the Padres farm system.",
      "Tom Tellmann went 13-5 with a 3.23 ERA for Triple-A Hawaii in 1980.",
      "Tom Tellmann threw 170 innings and completed five games during that minor-league season.",
      "Tom Tellmann reached the major leagues with San Diego.",
      "Tom Tellmann later joined Milwaukee and moved primarily into relief.",
      "Tom Tellmann appeared in 44 games during the 1983 season.",
      "Tom Tellmann went 9-4 with a 2.80 ERA in 1983.",
      "Tom Tellmann recorded eight saves during the 1983 season.",
      "Tom Tellmann pitched 99 and two-thirds innings despite making no starts in 1983.",
      "Tom Tellmann allowed 95 hits and struck out 48 hitters during the 1983 season.",
      "Tom Tellmann can enter early and pitch several innings.",
      "Tom Tellmann's nine relief victories led Milwaukee's bullpen in 1983.",
      "Tom Tellmann gives the manager an alternative when the starting pitcher leaves before the middle innings.",
      "Tom Tellmann's starting background helps him conserve pitches during an extended relief appearance.",
    ],
  },
  "Rick Waits": {
    lines: [
      "Rick Waits' full name is Michael Richard Waits.",
      "Rick Waits is a left-handed pitcher from Georgia.",
      "Rick Waits began his major-league career with the Texas Rangers.",
      "Rick Waits later became a regular member of Cleveland's starting rotation.",
      "Rick Waits won 13 games for Cleveland during the 1978 season.",
      "Rick Waits went 16-15 and threw more than 200 innings during the 1979 season.",
      "Rick Waits has experience as a starter, long reliever and situational left-hander.",
      "Rick Waits was traded from Cleveland to Milwaukee on June 6, 1983.",
      "Rick Waits came to Milwaukee in the same transaction as center fielder Rick Manning.",
      "Rick Waits appeared in 18 games between Cleveland and Milwaukee during the 1983 season.",
      "Rick Waits made two starts and worked 49 and two-thirds innings in 1983.",
      "Rick Waits struck out 33 hitters during the 1983 season.",
      "Rick Waits allowed only two home runs in 49 and two-thirds innings in 1983.",
      "Rick Waits gives Milwaukee another experienced left-handed pitcher.",
      "Rick Waits can remain in the game for several innings if a starter is removed early.",
      "Rick Waits can also be used for a specific matchup against a dangerous left-handed batter.",
      "Rick Waits' ability to start makes him useful during doubleheaders or periods of rotation injury.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive — base hit.\"",
    "\"Long drive to left field — way back — gone. Home run!\"",
    "\"Ground ball to short — over to first — in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This is a ballclub that can hit with anybody in baseball — the Brewers can flat-out rake.\"",
    "\"Milwaukee baseball is alive and well — the fans here love their Brewers.\"",
    "\"This team has power up and down the lineup — you can't relax against any hitter.\"",
    "\"The Brewers went to the World Series just two years ago — they know how to win.\"",
    "\"Robin Yount, Cecil Cooper, Ted Simmons — that's a murderer's row right there.\"",
    "\"County Stadium is rocking tonight — there's nothing like Brewers baseball in Milwaukee.\"",
    "\"This club plays hard for nine innings — that's the Brewers way.\"",
    "\"Milwaukee has one of the most dangerous lineups in the American League.\"",
    "\"The fans in Wisconsin love their baseball — and this team gives them plenty to cheer about.\"",
    "\"There's talent everywhere you look in this lineup — the Brewers can hurt you in so many ways.\"",
    "\"This is a team that's been through the wars — they've been to the top and they want to get back.\"",
    "\"Milwaukee baseball — there's nothing quite like a summer night at County Stadium.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Robin Yount is the heart and soul of this ballclub — the MVP of the league just two years ago.\"",
    "\"Cecil Cooper is one of the most productive first basemen in all of baseball.\"",
    "\"Paul Molitor is one of the most instinctive baserunners you'll ever see.\"",
    "\"Ted Simmons gives this lineup a switch-hitting run producer right in the middle.\"",
    "\"Rollie Fingers has more big-game experience than anyone in this bullpen.\"",
    "\"Jim Gantner is the heart and soul of this ballclub — a Wisconsin kid living the dream.\"",
    "\"Ben Oglivie has power that you don't see very often from a left-handed hitter.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at County Stadium, right on the Wisconsin state fairgrounds.\"",
    "\"The lights are on at County Stadium — Milwaukee baseball tonight.\"",
    "County Stadium — home of the Brewers since 1970, and the fans here love their baseball.",
    "\"The bratwursts are sizzling on the grill behind the bleachers — that's the smell of Brewers baseball.\"",
    "\"A cool Wisconsin evening — perfect baseball weather at County Stadium.\"",
    "\"The artificial turf plays fast tonight — ground balls will scoot through the infield.\"",
    "\"The bleachers are packed tonight — Milwaukee fans know how to enjoy a ballgame.\"",
    "\"You can see the Milwaukee skyline beyond the outfield walls on a clear night.\"",
    "\"The faithful at County Stadium are some of the most knowledgeable fans in baseball.\"",
    "\"A crisp summer night in Wisconsin — there's nothing better than baseball at County Stadium.\"",
    "\"This ballpark has seen some great moments — the 1982 pennant clincher right here on this field.\"",
    "\"The stands are filling up nicely — Wisconsin loves its Brewers.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here in Milwaukee is into this ballgame.\"",
    "\"Brewers fans are making some noise tonight.\"",
    "\"The fans in Wisconsin love their baseball — listen to that.\"",
    "\"County Stadium is rocking tonight.\"",
    "\"Milwaukee fans are among the most loyal in baseball — they show up every night.\"",
    "\"The crowd is on its feet — they can feel something building here.\"",
    "\"A great turnout at County Stadium tonight.\"",
    "\"These fans were here for the '82 pennant — they know what winning baseball sounds like.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to County Stadium, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball on a Wisconsin summer night.\"",
    "\"From all of us here in Milwaukee, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story — that's the beauty of this sport.\"",
    "\"Baseball in Milwaukee — it's a tradition that runs deep in this city.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone — into the seats at County Stadium!\"",
    "\"A magnificent piece of hitting. Simply magnificent.\"",
    "\"The Brewers are making their move here at County Stadium.\"",
    "\"That one is long gone — souvenir for a fan in the bleachers.\"",
    "\"You won't see many better than that one.\"",
    "\"Get up! Get up! Get outta here! Gone!\"",
  ]},
};