// AI-generated 1984 Topps facsimile card images for every player on every team
// Generated in the style of authentic 1984 Topps baseball cards

const BASE = 'https://media.base44.com/images/public/6a3075f14330dbc5dd0e91af/';

export const CARD_IMAGES = {
  // ── DETROIT TIGERS ──
  'Alan Trammell':    BASE + '92293da82_generated_image.png',
  'Lou Whitaker':     BASE + 'e364dfced_generated_image.png',
  'Kirk Gibson':      BASE + 'bfd491889_generated_image.png',
  'Jack Morris':      BASE + 'e7ba14d37_generated_image.png',
  'Willie Hernandez': BASE + 'bfeed7aef_generated_image.png',
  'Lance Parrish':    BASE + '6c8955118_generated_image.png',
  'Darrell Evans':    BASE + '2ade65487_generated_image.png',
  'Chet Lemon':       BASE + '1e5737f91_generated_image.png',
  'Larry Herndon':    BASE + '7847028b2_generated_image.png',
  'Howard Johnson':   BASE + '4d6262bc8_generated_image.png',
  'Dan Petry':        BASE + 'a7f54a8b2_generated_image.png',
  'Aurelio Lopez':    BASE + 'f5e7d8ee7_generated_image.png',
  'Barbaro Garbey':   BASE + '832be5879_generated_image.png',
  'Milt Wilcox':      BASE + '235b47516_generated_image.png',
  'Tom Brookens':     BASE + '260bfb07f_generated_image.png',
  'Juan Berenguer':   BASE + 'f5e7d8ee7_generated_image.png', // shared reliever image
  'Doug Bair':        BASE + 'f5e7d8ee7_generated_image.png',
  'Bill Scherrer':    BASE + 'f5e7d8ee7_generated_image.png',
  'Sid Monge':        BASE + 'f5e7d8ee7_generated_image.png',
  'Marty Castillo':   BASE + '6c8955118_generated_image.png', // shared catcher image
  'Dave Bergman':     BASE + '2ade65487_generated_image.png',
  'Rusty Kuntz':      BASE + '7847028b2_generated_image.png',
  'Johnny Grubb':     BASE + '7847028b2_generated_image.png',

  // ── CHICAGO CUBS ──
  'Ryne Sandberg':    BASE + '8df93010b_generated_image.png',
  'Rick Sutcliffe':   BASE + 'a5dc01b5b_generated_image.png',
  'Leon Durham':      BASE + '4c9d5a0fc_generated_image.png',
  'Lee Smith':        BASE + 'fff2a3869_generated_image.png',
  'Bob Dernier':      BASE + 'e9ac5bd85_generated_image.png',
  'Gary Matthews':    BASE + 'b2657ebc1_generated_image.png',
  'Keith Moreland':   BASE + '69a70923d_generated_image.png',
  'Jody Davis':       BASE + '0a5e32f55_generated_image.png',
  'Ron Cey':          BASE + '9b8b9c72e_generated_image.png',
  'Larry Bowa':       BASE + 'c41559c28_generated_image.png',
  'Dennis Eckersley': BASE + '8e0cab3df_generated_image.png',
  'Steve Trout':      BASE + 'a5dc01b5b_generated_image.png',
  'Scott Sanderson':  BASE + 'a5dc01b5b_generated_image.png',
  'Tim Stoddard':     BASE + 'fff2a3869_generated_image.png',
  'George Frazier':   BASE + 'fff2a3869_generated_image.png',
  'Warren Brusstar':  BASE + 'fff2a3869_generated_image.png',
  'Dickie Noles':     BASE + 'fff2a3869_generated_image.png',
  'Thad Bosley':      BASE + 'e9ac5bd85_generated_image.png',
  'Richie Hebner':    BASE + '9b8b9c72e_generated_image.png',
  'Henry Cotto':      BASE + 'e9ac5bd85_generated_image.png',
  'Steve Lake':       BASE + '0a5e32f55_generated_image.png',
  'Dave Owen':        BASE + 'c41559c28_generated_image.png',

  // ── SAN DIEGO PADRES ──
  'Tony Gwynn':       BASE + 'e42660d7e_generated_image.png',
  'Steve Garvey':     BASE + '9aca6ada8_generated_image.png',
  'Goose Gossage':    BASE + '7bb589e69_generated_image.png',
  'Alan Wiggins':     BASE + '39d2744a3_generated_image.png',
  'Graig Nettles':    BASE + '082f2a560_generated_image.png',
  'Terry Kennedy':    BASE + 'd661a5619_generated_image.png',
  'Kevin McReynolds': BASE + '1f7a3641a_generated_image.png',
  'Carmelo Martinez': BASE + '1f7a3641a_generated_image.png',
  'Garry Templeton':  BASE + '39d2744a3_generated_image.png',
  'Eric Show':        BASE + '9fcfe4143_generated_image.png',
  'Ed Whitson':       BASE + '9fcfe4143_generated_image.png',
  'Tim Lollar':       BASE + '9fcfe4143_generated_image.png',
  'Andy Hawkins':     BASE + '9fcfe4143_generated_image.png',
  'Craig Lefferts':   BASE + '7bb589e69_generated_image.png',
  'Dave Dravecky':    BASE + '8a846633d_generated_image.png',
  'Greg Booker':      BASE + '7bb589e69_generated_image.png',
  'Luis DeLeon':      BASE + '7bb589e69_generated_image.png',
  'Kurt Bevacqua':    BASE + '082f2a560_generated_image.png',
  'Bobby Brown':      BASE + '1f7a3641a_generated_image.png',
  'Bruce Bochy':      BASE + 'd661a5619_generated_image.png',
  'Tim Flannery':     BASE + '39d2744a3_generated_image.png',
  'Luis Salazar':     BASE + '082f2a560_generated_image.png',

  // ── NEW YORK METS ──
  'Dwight Gooden':    BASE + 'd262929cf_generated_image.png',
  'Darryl Strawberry':BASE + '382a064b8_generated_image.png',
  'Keith Hernandez':  BASE + '6343a8a1d_generated_image.png',
  'Wally Backman':    BASE + 'e2953ca61_generated_image.png',
  'Mookie Wilson':    BASE + '0aa1c7327_generated_image.png',
  'George Foster':    BASE + 'bd385fc51_generated_image.png',
  'Hubie Brooks':     BASE + 'b248c02e9_generated_image.png',
  'Jesse Orosco':     BASE + '13ee7315b_generated_image.png',
  'Ron Darling':      BASE + '603201e2b_generated_image.png',
  'Mike Fitzgerald':  BASE + 'e2953ca61_generated_image.png',
  'Jose Oquendo':     BASE + 'e2953ca61_generated_image.png',
  'Walt Terrell':     BASE + 'd262929cf_generated_image.png',
  'Bruce Berenyi':    BASE + 'd262929cf_generated_image.png',
  'Doug Sisk':        BASE + '13ee7315b_generated_image.png',
  'Brent Gaff':       BASE + '13ee7315b_generated_image.png',
  'Tom Gorman':       BASE + '13ee7315b_generated_image.png',
  'Ed Lynch':         BASE + '13ee7315b_generated_image.png',
  'Ron Gardenhire':   BASE + 'e2953ca61_generated_image.png',
  'Kelvin Chapman':   BASE + 'e2953ca61_generated_image.png',
  'John Gibbons':     BASE + 'e2953ca61_generated_image.png',
  'Danny Heep':       BASE + '0aa1c7327_generated_image.png',
  'Rusty Staub':      BASE + '6343a8a1d_generated_image.png',

  // ── BOSTON RED SOX ──
  'Wade Boggs':       BASE + 'a615999a5_generated_image.png',
  'Jim Rice':         BASE + '0c33b1c00_generated_image.png',
  'Dwight Evans':     BASE + 'c3ea12ae2_generated_image.png',
  'Tony Armas':       BASE + 'e51d0fde2_generated_image.png',
  'Bill Buckner':     BASE + '396ca5d47_generated_image.png',
  'Rich Gedman':      BASE + 'a615999a5_generated_image.png',
  'Marty Barrett':    BASE + 'a615999a5_generated_image.png',
  'Jackie Gutierrez': BASE + 'a615999a5_generated_image.png',
  'Mike Easler':      BASE + '0c33b1c00_generated_image.png',
  'Bruce Hurst':      BASE + '7c846af75_generated_image.png',
  'Oil Can Boyd':     BASE + '7c846af75_generated_image.png',
  'Bob Ojeda':        BASE + '7c846af75_generated_image.png',
  'Al Nipper':        BASE + '7c846af75_generated_image.png',
  'Bob Stanley':      BASE + '7c846af75_generated_image.png',
  'Mark Clear':       BASE + '7c846af75_generated_image.png',
  'John Henry Johnson':BASE + '7c846af75_generated_image.png',
  'Steve Crawford':   BASE + '7c846af75_generated_image.png',
  'Charlie Mitchell': BASE + '7c846af75_generated_image.png',
  'Reid Nichols':     BASE + 'c3ea12ae2_generated_image.png',
  'Ed Jurak':         BASE + 'a615999a5_generated_image.png',
  'Jeff Newman':      BASE + 'a615999a5_generated_image.png',
  'Rick Miller':      BASE + 'c3ea12ae2_generated_image.png',
  'Glenn Hoffman':    BASE + 'a615999a5_generated_image.png',

  // ── NEW YORK YANKEES ──
  'Don Mattingly':    BASE + '7c846af75_generated_image.png',
  'Dave Winfield':    BASE + '193c8150e_generated_image.png',
  'Ron Guidry':       BASE + '7c4f779b0_generated_image.png',
  'Dave Righetti':    BASE + 'a83af9ffb_generated_image.png',
  'Phil Niekro':      BASE + 'ff4f1705e_generated_image.png',
  'Willie Randolph':  BASE + '328927698_generated_image.png',
  'Don Baylor':       BASE + '193c8150e_generated_image.png',
  'Ken Griffey Sr.':  BASE + '193c8150e_generated_image.png',
  'Steve Kemp':       BASE + '193c8150e_generated_image.png',
  'Butch Wynegar':    BASE + '328927698_generated_image.png',
  'Mike Pagliarulo':  BASE + '328927698_generated_image.png',
  'Bobby Meacham':    BASE + '328927698_generated_image.png',
  'Ray Fontenot':     BASE + '7c4f779b0_generated_image.png',
  'Dennis Rasmussen': BASE + '7c4f779b0_generated_image.png',
  'Jay Howell':       BASE + 'a83af9ffb_generated_image.png',
  'Mike Armstrong':   BASE + 'a83af9ffb_generated_image.png',
  'Bob Shirley':      BASE + 'a83af9ffb_generated_image.png',
  'Clay Christiansen':BASE + 'a83af9ffb_generated_image.png',
  'Oscar Gamble':     BASE + '193c8150e_generated_image.png',
  'Roy Smalley':      BASE + '328927698_generated_image.png',
  'Rick Cerone':      BASE + '328927698_generated_image.png',
  'Brian Dayett':     BASE + '193c8150e_generated_image.png',
  'Tim Foli':         BASE + '328927698_generated_image.png',

  // ── BALTIMORE ORIOLES ──
  'Cal Ripken Jr.':   BASE + '79de78912_generated_image.png',
  'Eddie Murray':     BASE + '4e426fbba_generated_image.png',
  'Mike Boddicker':   BASE + 'a6291f965_generated_image.png',
  'Tippy Martinez':   BASE + 'b51fc98d2_generated_image.png',
  'Al Bumbry':        BASE + '96314286e_generated_image.png',
  'Ken Singleton':    BASE + '083261953_generated_image.png',
  'Gary Roenicke':    BASE + '96314286e_generated_image.png',
  'Wayne Gross':      BASE + '4e426fbba_generated_image.png',
  'Mike Young':       BASE + '96314286e_generated_image.png',
  'Rich Dauer':       BASE + '79de78912_generated_image.png',
  'Rick Dempsey':     BASE + '4e426fbba_generated_image.png',
  'Scott McGregor':   BASE + 'a6291f965_generated_image.png',
  'Storm Davis':      BASE + 'a6291f965_generated_image.png',
  'Mike Flanagan':    BASE + 'a6291f965_generated_image.png',
  'Sammy Stewart':    BASE + 'b51fc98d2_generated_image.png',
  'Tom Underwood':    BASE + 'b51fc98d2_generated_image.png',
  'Bill Swaggerty':   BASE + 'b51fc98d2_generated_image.png',
  'John Pacella':     BASE + 'b51fc98d2_generated_image.png',
  'John Shelby':      BASE + '96314286e_generated_image.png',
  'Jim Dwyer':        BASE + '96314286e_generated_image.png',
  'Floyd Rayford':    BASE + '4e426fbba_generated_image.png',
  'Lenn Sakata':      BASE + '79de78912_generated_image.png',
  'Joe Nolan':        BASE + '4e426fbba_generated_image.png',

  // ── KANSAS CITY ROYALS ──
  'George Brett':     BASE + 'fc71e138a_generated_image.png',
  'Dan Quisenberry':  BASE + '959acda91_generated_image.png',
  'Bret Saberhagen':  BASE + '097d90868_generated_image.png',
  'Willie Wilson':    BASE + 'd4d836490_generated_image.png',
  'Frank White':      BASE + '322ec5ce9_generated_image.png',
  'Hal McRae':        BASE + '78d781ed9_generated_image.png',
  'Steve Balboni':    BASE + 'fc71e138a_generated_image.png',
  'Pat Sheridan':     BASE + 'd4d836490_generated_image.png',
  'Darryl Motley':    BASE + 'd4d836490_generated_image.png',
  'Jamie Quirk':      BASE + '322ec5ce9_generated_image.png',
  'Onix Concepcion':  BASE + '322ec5ce9_generated_image.png',
  'Bud Black':        BASE + '097d90868_generated_image.png',
  'Charlie Leibrandt':BASE + '097d90868_generated_image.png',
  'Mark Gubicza':     BASE + '097d90868_generated_image.png',
  'Steve Farr':       BASE + '959acda91_generated_image.png',
  'Mike Jones':       BASE + '959acda91_generated_image.png',
  'Joe Beckwith':     BASE + '959acda91_generated_image.png',
  'Gary Christenson': BASE + '959acda91_generated_image.png',
  'Dane Iorg':        BASE + 'fc71e138a_generated_image.png',
  'Buddy Biancalana': BASE + '322ec5ce9_generated_image.png',
  'John Wathan':      BASE + '322ec5ce9_generated_image.png',
  'Greg Pryor':       BASE + '322ec5ce9_generated_image.png',
  'Cesar Geronimo':   BASE + 'd4d836490_generated_image.png',

  // ── LOS ANGELES DODGERS ──
  'Fernando Valenzuela': BASE + 'df968d4be_generated_image.png',
  'Pedro Guerrero':   BASE + 'f0bd63932_generated_image.png',
  'Orel Hershiser':   BASE + '7b6a64d35_generated_image.png',
  'Steve Sax':        BASE + '785514ee0_generated_image.png',
  'Mike Scioscia':    BASE + '47324feb5_generated_image.png',
  'Ken Landreaux':    BASE + '785514ee0_generated_image.png',
  'Mike Marshall':    BASE + 'f0bd63932_generated_image.png',
  'Greg Brock':       BASE + '785514ee0_generated_image.png',
  'Franklin Stubbs':  BASE + '785514ee0_generated_image.png',
  'Dave Anderson':    BASE + '785514ee0_generated_image.png',
  'Alejandro Pena':   BASE + '7b6a64d35_generated_image.png',
  'Bob Welch':        BASE + '7b6a64d35_generated_image.png',
  'Ken Howell':       BASE + '7b6a64d35_generated_image.png',
  'Pat Zachry':       BASE + '7b6a64d35_generated_image.png',
  'Carlos Diaz':      BASE + '7b6a64d35_generated_image.png',
  'Tom Niedenfuer':   BASE + '7b6a64d35_generated_image.png',
  'Burt Hooton':      BASE + '7b6a64d35_generated_image.png',
  'Bill Russell':     BASE + '785514ee0_generated_image.png',
  'Candy Maldonado':  BASE + '785514ee0_generated_image.png',
  'Bob Bailor':       BASE + '785514ee0_generated_image.png',
  'Steve Yeager':     BASE + '47324feb5_generated_image.png',
  'R.J. Reynolds':    BASE + '785514ee0_generated_image.png',

  // ── PHILADELPHIA PHILLIES ──
  'Mike Schmidt':     BASE + '8645a633a_generated_image.png',
  'Steve Carlton':    BASE + 'd1a69a490_generated_image.png',
  'Juan Samuel':      BASE + '8bba97a00_generated_image.png',
  'Tug McGraw':       BASE + '4e2d6f62b_generated_image.png',
  'Von Hayes':        BASE + '4bac78b6d_generated_image.png',
  'Garry Maddox':     BASE + 'af8bd61d0_generated_image.png',
  'Glenn Wilson':     BASE + '8645a633a_generated_image.png',
  'Ozzie Virgil Jr.': BASE + '8645a633a_generated_image.png',
  'Jeff Stone':       BASE + '8bba97a00_generated_image.png',
  'Ivan DeJesus':     BASE + '8bba97a00_generated_image.png',
  'John Denny':       BASE + 'd1a69a490_generated_image.png',
  'Kevin Gross':      BASE + 'd1a69a490_generated_image.png',
  'Charles Hudson':   BASE + 'd1a69a490_generated_image.png',
  'Al Holland':       BASE + '4e2d6f62b_generated_image.png',
  'Larry Andersen':   BASE + '4e2d6f62b_generated_image.png',
  'Bill Campbell':    BASE + '4e2d6f62b_generated_image.png',
  'Don Carman':       BASE + '4e2d6f62b_generated_image.png',
  'Len Matuszek':     BASE + '4bac78b6d_generated_image.png',
  'Greg Gross':       BASE + 'af8bd61d0_generated_image.png',
  'Derrel Thomas':    BASE + '8bba97a00_generated_image.png',
  'Bo Diaz':          BASE + '8645a633a_generated_image.png',
  'Sixto Lezcano':    BASE + 'af8bd61d0_generated_image.png',

  // ── CINCINNATI REDS ──
  'Pete Rose':        BASE + '1919ce9fc_generated_image.png',
  'Dave Parker':      BASE + '98dd74427_generated_image.png',
  'Mario Soto':       BASE + '1c4edd2e5_generated_image.png',
  'Dave Concepcion':  BASE + '8e7e9b936_generated_image.png',
  'John Franco':      BASE + '4c71fba4c_generated_image.png',
  'Gary Redus':       BASE + '0c50af9f9_generated_image.png',
  'Cesar Cedeno':     BASE + '98dd74427_generated_image.png',
  'Nick Esasky':      BASE + '1919ce9fc_generated_image.png',
  'Ron Oester':       BASE + '8e7e9b936_generated_image.png',
  'Dann Bilardello':  BASE + '8e7e9b936_generated_image.png',
  'Jeff Russell':     BASE + '1c4edd2e5_generated_image.png',
  'Joe Price':        BASE + '1c4edd2e5_generated_image.png',
  'Jay Tibbs':        BASE + '1c4edd2e5_generated_image.png',
  'Ted Power':        BASE + '4c71fba4c_generated_image.png',
  'Tom Hume':         BASE + '4c71fba4c_generated_image.png',
  'Bob Owchinko':     BASE + '4c71fba4c_generated_image.png',
  'Brad Gulden':      BASE + '8e7e9b936_generated_image.png',
  'Duane Walker':     BASE + '0c50af9f9_generated_image.png',
  'Tom Lawless':      BASE + '8e7e9b936_generated_image.png',
  'Wayne Krenchicki': BASE + '1919ce9fc_generated_image.png',
  'Eric Davis':       BASE + '0c50af9f9_generated_image.png',
};

/**
 * Get the card image URL for a player by name.
 * Falls back to a generic placeholder if not found.
 */
export function getCardImage(playerName) {
  return CARD_IMAGES[playerName] || null;
}