// St. Louis Cardinals Broadcast — 1984
// Radio: Jack Buck & Mike Shannon (KMOX)
// Busch Memorial Stadium — home of the Cardinals since 1966
// All stats cutoff: end of 1983 season

export function pickCardinalsLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickCardinalsPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Vince Coleman": {
    lines: [
      "Vince Coleman's full name is Vincent Maurice Coleman.",
      "Coleman was born in Jacksonville, Florida.",
      "Vince Coleman attended William M. Raines High School in Jacksonville.",
      "Coleman became an outstanding two-sport athlete at Florida A&M University.",
      "Vince Coleman played both baseball and football for the Rattlers.",
      "Coleman was a placekicker and punter on the Florida A&M football team.",
      "The Philadelphia Phillies selected Coleman in the 20th round of the 1981 amateur draft, but he did not sign.",
      "St. Louis selected Vince Coleman in the tenth round of the 1982 draft.",
      "Coleman began his professional career with the Erie Cardinals in 1982.",
      "Vince Coleman spent the 1983 season with Class-A Macon.",
      "Coleman appeared in 113 games for the Macon Redbirds.",
      "Vince Coleman batted .350 with 156 hits.",
      "Coleman scored 99 runs despite missing part of the season.",
      "Vince Coleman recorded eight doubles and seven triples.",
      "Coleman did not hit a home run but drove in 53 runs.",
      "Vince Coleman drew 56 walks and posted a .431 on-base percentage.",
      "Coleman stole an organized-baseball-record 145 bases.",
      "Vince Coleman was caught stealing 31 times.",
      "Coleman averaged more than one stolen base per game.",
      "Vince Coleman had not yet appeared in a major-league game entering 1984.",
      "Opposing major-league pitchers and catchers therefore have no previous experience controlling Coleman's running game.",
      "Coleman's acceleration allows him to steal on pitchers who appear to have short deliveries.",
      "Even a routine ground ball can become a close play when Coleman is leaving the batter's box.",
      "His presence at the top of the order immediately forces the defense to rush throws and alter positioning.",
    ],
  },
  "Willie McGee": {
    lines: [
      "Willie McGee's full name is Willie Dean McGee.",
      "McGee was born in San Francisco, California.",
      "Willie McGee grew up in Richmond, California.",
      "McGee played baseball, basketball and football as a youngster.",
      "Willie McGee attended Harry Ells High School.",
      "The Chicago White Sox selected McGee during the 1976 draft, but he did not sign.",
      "The New York Yankees later selected Willie McGee in the first round of the January 1977 secondary draft.",
      "St. Louis acquired McGee from New York before the 1982 season.",
      "The Cardinals sent pitcher Bob Sykes to the Yankees in the trade.",
      "Willie McGee made his major-league debut on May 10, 1982.",
      "McGee quickly became St. Louis' regular center fielder.",
      "Willie McGee batted .296 and stole 24 bases as a rookie.",
      "McGee finished third in the 1982 National League Rookie of the Year voting.",
      "Willie McGee helped St. Louis win the 1982 World Series.",
      "McGee hit two home runs during Game Three of the World Series.",
      "Willie McGee also made two outstanding catches against the outfield wall during that game.",
      "McGee appeared in 147 games during the 1983 season.",
      "Willie McGee batted .286 with 172 hits.",
      "McGee collected 22 doubles and eight triples.",
      "Willie McGee hit five home runs and drove in 75 runs.",
      "McGee scored 75 times and stole 39 bases.",
      "Willie McGee covers enormous territory in center field.",
      "McGee uses a quick, level swing to line pitches into the gaps.",
      "His speed can turn an ordinary single into a double whenever an outfielder hesitates.",
      "McGee's quiet personality contrasts with the excitement he creates on the field.",
    ],
  },
  "George Hendrick": {
    lines: [
      "George Hendrick's full name is George Andrew Hendrick Jr.",
      "Hendrick was born in Los Angeles, California.",
      "George Hendrick attended Fremont High School in Los Angeles.",
      "Oakland selected Hendrick with the first overall pick of the January 1968 amateur draft.",
      "Hendrick reached the major leagues with the Athletics during the 1971 season.",
      "George Hendrick later played for Cleveland and San Diego.",
      "Hendrick was selected to the American League All-Star team in 1974 and 1975.",
      "George Hendrick joined St. Louis during the 1978 season.",
      "Hendrick became one of the Cardinals' most dependable run producers.",
      "George Hendrick is sometimes known as \"Silent George\" because he prefers to avoid interviews and attention.",
      "Hendrick batted .302 with 25 home runs and 109 RBI during the 1980 season.",
      "George Hendrick was selected to the All-Star team and received a Silver Slugger that year.",
      "Hendrick helped St. Louis win the 1982 World Series.",
      "George Hendrick appeared in 144 games during the 1983 season.",
      "Hendrick led the Cardinals with a .318 batting average.",
      "George Hendrick collected 168 hits and 33 doubles.",
      "Hendrick hit 18 home runs and drove in 97 runs.",
      "George Hendrick scored 73 times.",
      "Hendrick recorded a .373 on-base percentage and a .493 slugging percentage.",
      "George Hendrick earned another All-Star selection and Silver Slugger in 1983.",
      "Hendrick has extensive experience at first base as well as both corner-outfield positions.",
      "His calm, balanced swing allows him to drive pitches to all fields.",
      "Hendrick rarely appears hurried, even when batting with runners in scoring position.",
    ],
  },
  "Ken Oberkfell": {
    lines: [
      "Ken Oberkfell's full name is Kenneth Ray Oberkfell.",
      "Oberkfell was born in Highland, Illinois.",
      "Ken Oberkfell grew up only a short distance from St. Louis.",
      "Oberkfell attended Collinsville High School.",
      "Ken Oberkfell later attended Southwestern Illinois College.",
      "St. Louis signed Oberkfell as an amateur free agent during the 1975 season.",
      "Ken Oberkfell made his major-league debut during August 1977.",
      "Oberkfell originally played primarily at second base.",
      "Ken Oberkfell gradually shifted to third base.",
      "Oberkfell became St. Louis' regular third baseman during the 1982 championship season.",
      "Ken Oberkfell collected two hits during Game Seven of the 1982 World Series.",
      "Oberkfell appeared in 151 games during the 1983 season.",
      "Ken Oberkfell batted .293 with 143 hits.",
      "Oberkfell collected 26 doubles and five triples.",
      "Ken Oberkfell hit three home runs and drove in 38 runs.",
      "Oberkfell scored 62 times and stole 12 bases.",
      "Ken Oberkfell drew 61 walks.",
      "Oberkfell struck out only 27 times in 488 official at-bats.",
      "Ken Oberkfell posted a .371 on-base percentage.",
      "Oberkfell's offensive game emphasizes contact, patience and advancing runners.",
      "His quick reactions are especially valuable on the fast artificial turf at Busch Stadium.",
      "Ken Oberkfell can shift back to second base when the Cardinals need additional infield flexibility.",
    ],
  },
  "Ozzie Smith": {
    lines: [
      "Ozzie Smith's full name is Osborne Earl Smith.",
      "Smith was born in Mobile, Alabama.",
      "Ozzie Smith grew up in the Los Angeles area.",
      "Smith attended Locke High School and California Polytechnic State University.",
      "Detroit selected Ozzie Smith in the 1976 draft, but he did not sign.",
      "San Diego selected Smith in the fourth round of the 1977 amateur draft.",
      "Ozzie Smith made his major-league debut during the 1978 season.",
      "Smith immediately became known for extraordinary range at shortstop.",
      "Ozzie Smith earned the nickname \"The Wizard of Oz.\"",
      "Smith began performing a backflip during pregame introductions.",
      "Ozzie Smith won his first National League Gold Glove in 1980.",
      "St. Louis acquired Smith from San Diego before the 1982 season.",
      "The principal players in the trade were Ozzie Smith and Garry Templeton.",
      "Ozzie Smith helped the Cardinals win the 1982 World Series.",
      "Smith appeared in 159 games during the 1983 season.",
      "Ozzie Smith collected 134 hits.",
      "Smith recorded 30 doubles and six triples.",
      "Ozzie Smith hit three home runs and drove in 50 runs.",
      "Smith scored 69 times and stole 34 bases.",
      "Ozzie Smith drew 64 walks while striking out only 36 times.",
      "Smith earned another All-Star selection and Gold Glove in 1983.",
      "Ozzie Smith has won four consecutive Gold Gloves through the end of 1983.",
      "Smith can reach ground balls that appear destined for the outfield.",
      "His body control allows him to throw accurately from unusual positions.",
      "Ozzie Smith and Tom Herr form one of the National League's quickest double-play combinations.",
    ],
  },
  "Tom Herr": {
    lines: [
      "Tom Herr's full name is Thomas Mitchell Herr.",
      "Herr was born in Lancaster, Pennsylvania.",
      "Tom Herr attended Hempfield High School.",
      "St. Louis signed Herr as an amateur free agent during the 1974 season.",
      "Tom Herr developed as a middle infielder in the Cardinals' farm system.",
      "Herr is a switch-hitter who throws right-handed.",
      "Tom Herr made his major-league debut during August 1979.",
      "Herr became St. Louis' regular second baseman during the 1981 season.",
      "Tom Herr helped the Cardinals win the 1982 World Series.",
      "Herr appeared in 135 games during the 1982 season.",
      "Tom Herr scored 83 runs and stole 25 bases during the championship season.",
      "Herr was limited to 89 games during the 1983 season.",
      "Tom Herr batted .323 with 101 hits.",
      "Herr collected 14 doubles and four triples.",
      "Tom Herr hit two home runs and drove in 31 runs.",
      "Herr scored 43 times and stole six bases.",
      "Tom Herr drew 43 walks.",
      "Herr recorded an excellent .403 on-base percentage.",
      "Tom Herr struck out only 27 times.",
      "Herr's switch-hitting allows Whitey Herzog to leave him in the lineup against either type of pitcher.",
      "His speed and bat control make him effective during hit-and-run plays.",
      "Herr combines with Ozzie Smith to give St. Louis outstanding range around second base.",
    ],
  },
  "Darrell Porter": {
    lines: [
      "Darrell Porter's full name is Darrell Ray Porter.",
      "Porter was born in Joplin, Missouri.",
      "Darrell Porter grew up in Oklahoma City.",
      "Milwaukee selected Porter with the fourth overall pick of the 1970 amateur draft.",
      "Porter made his major-league debut during the 1971 season.",
      "Darrell Porter became Milwaukee's regular catcher while still in his early twenties.",
      "Porter later joined the Kansas City Royals.",
      "Darrell Porter was selected to the All-Star team in 1974, 1978 and 1979.",
      "Porter enjoyed an exceptional offensive season with Kansas City in 1979.",
      "Darrell Porter hit 20 home runs and drove in 112 runs.",
      "Porter also drew 121 walks during that season.",
      "St. Louis signed Darrell Porter as a free agent before the 1981 season.",
      "Porter helped guide the Cardinals' pitching staff during the 1982 championship season.",
      "Darrell Porter was named Most Valuable Player of the 1982 National League Championship Series.",
      "Porter was also named Most Valuable Player of the 1982 World Series.",
      "Darrell Porter appeared in 145 games during the 1983 season.",
      "Porter batted .262 with 116 hits.",
      "Darrell Porter recorded 24 doubles, three triples and 15 home runs.",
      "Porter drove in 66 runs and scored 57 times.",
      "Darrell Porter drew 68 walks and posted a .363 on-base percentage.",
      "Porter is willing to absorb foul tips and block pitches in the dirt.",
      "Darrell Porter combines left-handed power with extensive knowledge of opposing hitters.",
      "His postseason experience is especially valuable during late, close games.",
    ],
  },
  "Lonnie Smith": {
    lines: [
      "Lonnie Smith was born in Chicago, Illinois.",
      "Smith attended Centennial High School in Compton, California.",
      "Philadelphia selected Lonnie Smith in the first round of the 1974 amateur draft.",
      "Smith made his major-league debut with the Phillies during September 1978.",
      "Lonnie Smith helped Philadelphia win the 1980 World Series.",
      "Smith's speed and sometimes adventurous defense earned him the nickname \"Skates.\"",
      "St. Louis acquired Lonnie Smith before the 1982 season.",
      "Smith became the Cardinals' primary leadoff hitter.",
      "Lonnie Smith batted .307 and led the National League with 120 runs in 1982.",
      "Smith also stole 68 bases during the championship season.",
      "Lonnie Smith finished second in the 1982 National League MVP voting.",
      "Smith appeared in 130 games during the 1983 season.",
      "Lonnie Smith batted .321 with 158 hits.",
      "Smith collected 31 doubles, five triples and eight home runs.",
      "Lonnie Smith scored 83 runs and drove in 45.",
      "Smith stole 43 bases.",
      "Lonnie Smith recorded a .381 on-base percentage and a .453 slugging percentage.",
      "Smith can play any of the three outfield positions.",
      "Lonnie Smith gives St. Louis proven speed and a .300-caliber bat from the bench.",
      "Using Smith as a pinch-runner places immediate pressure upon the pitcher and catcher.",
    ],
  },
  "Dane Iorg": {
    lines: [
      "Dane Iorg's full name is Dane Charles Iorg.",
      "Iorg was born in Eureka, California.",
      "Dane Iorg played college baseball at Brigham Young University.",
      "The Kansas City Royals selected Iorg during the 1968 amateur draft, but he did not sign.",
      "Philadelphia selected Dane Iorg in the first round of the January 1971 secondary draft.",
      "Iorg made his major-league debut with the Phillies during the 1977 season.",
      "St. Louis acquired Dane Iorg from Philadelphia during the 1977 season.",
      "Iorg bats left-handed and throws right-handed.",
      "Dane Iorg can play either corner-outfield position and first base.",
      "Iorg developed into one of Whitey Herzog's most dependable pinch-hitters.",
      "Dane Iorg appeared in the 1982 World Series against Milwaukee.",
      "Iorg collected nine hits in 17 World Series at-bats.",
      "Dane Iorg batted .529 during the Series.",
      "Iorg recorded two doubles and a triple during St. Louis' Game Six victory.",
      "Dane Iorg appeared in 58 games during the 1983 season.",
      "Iorg collected 31 hits in 116 official at-bats.",
      "Dane Iorg batted .267 with nine doubles and 11 RBI.",
      "Iorg is particularly useful against right-handed pitching.",
      "Dane Iorg's brother Garth has also appeared in the major leagues.",
      "Iorg's ability to remain prepared despite irregular playing time makes him an ideal bench player.",
    ],
  },
  "Mike Jorgensen": {
    lines: [
      "Mike Jorgensen's full name is Michael Jorgensen.",
      "Jorgensen was born in Passaic, New Jersey.",
      "Mike Jorgensen grew up in Queens, New York.",
      "The New York Mets selected Jorgensen in the fourth round of the 1966 amateur draft.",
      "Jorgensen made his major-league debut during September 1968.",
      "Mike Jorgensen was included in the trade that sent Rusty Staub from Montreal to New York.",
      "Jorgensen became Montreal's regular first baseman.",
      "Mike Jorgensen won a National League Gold Glove Award in 1973.",
      "Jorgensen hit 18 home runs and drove in 67 runs during the 1974 season.",
      "Mike Jorgensen later returned to the Mets.",
      "Jorgensen split the 1983 season between New York and Atlanta.",
      "Mike Jorgensen appeared in 84 total games.",
      "Jorgensen collected 18 hits in 72 official at-bats.",
      "Mike Jorgensen batted .250.",
      "Jorgensen recorded four doubles and two home runs.",
      "Mike Jorgensen can also play either corner-outfield position.",
      "Mike Jorgensen is especially useful as a left-handed pinch-hitter.",
      "His Gold Glove background makes him a dependable late-inning defensive replacement.",
    ],
  },
  "Ivan DeJesus": {
    lines: [
      "Ivan DeJesus' full name is Ivan Alvarez DeJesus.",
      "DeJesus was born in Santurce, Puerto Rico.",
      "Ivan DeJesus began his major-league career with the Los Angeles Dodgers.",
      "DeJesus later became the Chicago Cubs' regular shortstop.",
      "Ivan DeJesus led the National League with 104 runs during the 1978 season.",
      "DeJesus hit for the cycle against St. Louis on April 22, 1980.",
      "Ivan DeJesus was traded from Chicago to Philadelphia before the 1982 season.",
      "The transaction also sent Larry Bowa and young infielder Ryne Sandberg to Chicago.",
      "DeJesus became Philadelphia's regular shortstop.",
      "Ivan DeJesus appeared in 158 games during the 1983 season.",
      "DeJesus collected 126 hits.",
      "Ivan DeJesus recorded 15 doubles and seven triples.",
      "DeJesus hit four home runs and drove in 45 runs.",
      "Ivan DeJesus scored 60 times and stole 11 bases.",
      "DeJesus drew 53 walks and batted .254.",
      "Ivan DeJesus helped Philadelphia win the 1983 National League pennant.",
      "Ivan DeJesus gives your bench a durable, experienced defensive shortstop.",
      "His speed remains useful as either a pinch-runner or late-inning replacement.",
    ],
  },
  "Tom Nieto": {
    lines: [
      "Tom Nieto is a right-handed catcher.",
      "Nieto played college baseball at Oral Roberts University.",
      "Minnesota selected Tom Nieto in the 31st round of the 1979 amateur draft, but he did not sign.",
      "Pittsburgh later selected Nieto during the January 1980 secondary draft.",
      "St. Louis selected Tom Nieto in the third round of the 1981 amateur draft.",
      "Nieto developed in the Cardinals' minor-league system.",
      "Tom Nieto spent the 1983 season with Triple-A Louisville.",
      "Nieto appeared in 115 games for the Louisville Redbirds.",
      "Tom Nieto collected 104 hits in 383 official at-bats.",
      "Nieto batted .272.",
      "Tom Nieto recorded 17 doubles and one triple.",
      "Nieto hit five home runs and drove in 52 runs.",
      "Tom Nieto scored 44 times.",
      "Nieto drew 41 walks and recorded a .352 on-base percentage.",
      "Tom Nieto had not yet appeared in a major-league game entering 1984.",
      "Major-league opponents therefore possess no previous scouting history against him.",
      "Nieto's primary responsibilities are receiving, throwing and learning the pitching staff.",
      "Tom Nieto gives St. Louis a young catcher behind the experienced Darrell Porter.",
    ],
  },
  "Joaquin Andujar": {
    lines: [
      "Joaquin Andujar's full name is Joaquin Andujar Sabino.",
      "Andujar was born in San Pedro de Macoris in the Dominican Republic.",
      "Joaquin Andujar began his major-league career with the Houston Astros.",
      "Andujar made his major-league debut during the 1976 season.",
      "Joaquin Andujar was selected to the National League All-Star team in 1977 and 1979.",
      "Andujar possesses a lively fastball and an intense competitive personality.",
      "St. Louis acquired Joaquin Andujar from Houston during the 1981 season.",
      "Andujar moved between the rotation and bullpen during his first months with the Cardinals.",
      "Joaquin Andujar became a key member of the 1982 championship rotation.",
      "Andujar went 15-10 with a 2.47 ERA during the 1982 regular season.",
      "Joaquin Andujar started and won Game Seven of the 1982 World Series.",
      "Andujar became the first Dominican pitcher credited with the victory in a World Series-clinching game.",
      "Joaquin Andujar made 34 starts during the 1983 season.",
      "Andujar went 6-16 with a 4.16 ERA.",
      "Joaquin Andujar worked 225 innings.",
      "Andujar struck out 125 hitters.",
      "Joaquin Andujar completed three games and recorded two shutouts.",
      "Andujar also made five relief appearances and recorded one save.",
      "Joaquin Andujar's record was far less impressive than his championship performance one year earlier.",
      "Andujar's fastball can move sharply when he maintains a consistent release point.",
      "Joaquin Andujar is highly emotional on the mound and can become visibly energized by an important strikeout.",
      "Andujar's frequently repeated explanation of baseball is simple: \"You never know.\"",
    ],
  },
  "John Tudor": {
    lines: [
      "John Tudor's full name is John Francis Tudor.",
      "Tudor was born in Schenectady, New York.",
      "John Tudor is a left-handed pitcher.",
      "The New York Mets selected Tudor during the 1975 draft, but he did not sign.",
      "Boston selected John Tudor in the third round of the January 1976 secondary draft.",
      "Tudor developed in the Red Sox farm system.",
      "John Tudor made his major-league debut during August 1979.",
      "Tudor gradually earned a regular position in Boston's rotation.",
      "John Tudor relies upon control, changing speeds and keeping hitters off balance.",
      "Tudor made 34 starts for Boston during the 1983 season.",
      "John Tudor went 13-12 with a 4.09 ERA.",
      "Tudor worked 242 innings.",
      "John Tudor completed seven games.",
      "Tudor recorded two shutouts.",
      "John Tudor struck out 136 hitters.",
      "Tudor allowed 236 hits and walked 81.",
      "John Tudor surrendered 32 home runs during the season.",
      "Boston traded Tudor to Pittsburgh after the 1983 season.",
      "Tudor's changeup is particularly effective when hitters must also respect his fastball.",
      "His presence separates three right-handed starters and gives opponents a very different look.",
    ],
  },
  "Kurt Kepshire": {
    lines: [
      "Kurt Kepshire is a left-handed pitcher.",
      "Kepshire was born in Bridgeport, Connecticut.",
      "Kurt Kepshire attended the University of New Haven.",
      "Cincinnati selected Kepshire in the 25th round of the 1979 amateur draft.",
      "Kepshire later joined the St. Louis organization.",
      "Kurt Kepshire spent the 1983 season with Triple-A Louisville.",
      "Kepshire appeared in 21 games for the Redbirds.",
      "Kurt Kepshire made 10 starts.",
      "Kepshire went 6-2.",
      "Kurt Kepshire recorded a 3.67 ERA.",
      "Kepshire worked 83 and a third innings.",
      "Kurt Kepshire allowed 88 hits.",
      "Kepshire struck out 52 hitters and walked 24.",
      "Kurt Kepshire completed one game.",
      "Kepshire also recorded one shutout.",
      "Kurt Kepshire had not yet appeared in a major-league game entering 1984.",
      "Opposing National League teams therefore possess no major-league scouting history against him.",
      "Kepshire gives St. Louis a second left-handed starter alongside John Tudor.",
      "His Triple-A control suggests that he is willing to challenge hitters inside the strike zone.",
      "Kepshire enters the season trying to prove that his strong Louisville record can translate to the majors.",
    ],
  },
  "Dave LaPoint": {
    lines: [
      "Dave LaPoint's full name is David Jeffrey LaPoint.",
      "LaPoint was born in Glens Falls, New York.",
      "Dave LaPoint is a left-handed pitcher.",
      "Milwaukee selected LaPoint in the tenth round of the 1977 amateur draft.",
      "LaPoint made his major-league debut with the Brewers during the 1980 season.",
      "Dave LaPoint came to St. Louis in the large trade involving Rollie Fingers and Ted Simmons.",
      "LaPoint worked as both a starter and reliever early in his Cardinals career.",
      "Dave LaPoint helped St. Louis win the 1982 World Series.",
      "LaPoint went 9-3 during the 1982 regular season.",
      "Dave LaPoint started Game Four of the World Series.",
      "LaPoint became a full-time member of the rotation during 1983.",
      "Dave LaPoint appeared in 37 games.",
      "LaPoint made 29 starts.",
      "Dave LaPoint went 12-9 with a 3.95 ERA.",
      "LaPoint worked 191 and a third innings.",
      "Dave LaPoint completed one game.",
      "LaPoint struck out 113 hitters.",
      "Dave LaPoint allowed 191 hits.",
      "LaPoint surrendered only 12 home runs.",
      "Dave LaPoint's left-handed delivery provides a contrast to Andujar's hard right-handed approach.",
      "LaPoint can also return to the bullpen when the rotation requires rearrangement.",
      "His ability to change roles makes him particularly useful on a compact exhibition staff.",
    ],
  },
  "Bruce Sutter": {
    lines: [
      "Bruce Sutter's full name is Howard Bruce Sutter.",
      "Sutter was born in Lancaster, Pennsylvania.",
      "Bruce Sutter signed with the Chicago Cubs organization during the early 1970s.",
      "Sutter's professional career was nearly ended by arm trouble in the minor leagues.",
      "Minor-league instructor Fred Martin taught Bruce Sutter a forkball-like pitch that became the split-finger fastball.",
      "The pitch travels like a fastball before dropping sharply near the plate.",
      "Bruce Sutter made his major-league debut with the Cubs during 1976.",
      "Sutter was selected to the National League All-Star team during his first full season.",
      "Bruce Sutter recorded 31 saves with a 1.34 ERA in 1977.",
      "Sutter won the 1979 National League Cy Young Award.",
      "Bruce Sutter led the National League with 37 saves in 1979.",
      "St. Louis acquired Sutter from the Cubs after the 1980 season.",
      "Bruce Sutter tied the National League record with 36 saves during the 1982 season.",
      "Sutter recorded the final out of the 1982 World Series.",
      "Bruce Sutter struck out Milwaukee's Gorman Thomas to finish Game Seven.",
      "Sutter appeared in 60 games during the 1983 season.",
      "Bruce Sutter went 9-10 with a 4.23 ERA.",
      "Sutter recorded 21 saves.",
      "Bruce Sutter worked 89 and a third innings.",
      "Sutter finished 46 games.",
      "Bruce Sutter struck out 64 hitters while walking 30.",
      "Sutter has never made a major-league start.",
      "His splitter is especially dangerous because it resembles a strike until the hitter begins swinging.",
      "A well-executed splitter frequently produces a swing over the top or a sharply hit ground ball.",
      "Bruce Sutter can enter during the eighth inning and remain through the final out rather than working only one inning.",
    ],
  },
  "Neil Allen": {
    lines: [
      "Neil Allen is a right-handed pitcher.",
      "Allen began his major-league career with the New York Mets.",
      "Neil Allen initially reached the majors as a relief pitcher.",
      "Allen became the Mets' primary closer.",
      "Neil Allen recorded 22 saves during the 1980 season.",
      "Allen followed with 18 saves in 1981.",
      "Neil Allen recorded 19 more saves during the 1982 season.",
      "The Mets began converting Allen into a starting pitcher during 1983.",
      "St. Louis acquired Neil Allen and Rick Ownbey on June 15, 1983.",
      "The Cardinals sent first baseman Keith Hernandez to New York.",
      "Neil Allen immediately entered the St. Louis rotation.",
      "Allen appeared in 25 games for the Cardinals.",
      "Neil Allen made 18 starts.",
      "Allen went 10-6 with a 3.70 ERA for St. Louis.",
      "Neil Allen worked 121 and two-thirds innings as a Cardinal.",
      "Allen completed four games.",
      "Neil Allen recorded two shutouts.",
      "Allen struck out 74 hitters for St. Louis.",
      "Neil Allen finished the entire 1983 season with a 12-13 record and 3.94 ERA.",
      "Allen's previous closing experience makes him a logical relief option on your roster.",
      "Neil Allen can work one late inning or remain for several innings because of his starting background.",
      "His fastball and breaking ball give St. Louis a different right-handed look behind Sutter.",
    ],
  },
  "Jeff Lahti": {
    lines: [
      "Jeff Lahti's full name is Jeffrey Allen Lahti.",
      "Lahti is a right-handed pitcher.",
      "Jeff Lahti developed in the St. Louis minor-league system.",
      "Lahti made his major-league debut during the 1982 season.",
      "Jeff Lahti appeared in 33 games during his rookie year.",
      "Lahti worked exclusively from the bullpen in 1982.",
      "Jeff Lahti became one of Whitey Herzog's most frequently used relievers during 1983.",
      "Lahti appeared in 53 games.",
      "Jeff Lahti went 3-3.",
      "Lahti posted a 3.16 ERA.",
      "Jeff Lahti worked 74 innings.",
      "Lahti allowed only 64 hits.",
      "Jeff Lahti surrendered only two home runs.",
      "Lahti struck out 26 hitters and walked 29.",
      "Jeff Lahti finished 20 games.",
      "Lahti did not record a save because Sutter handled most formal save opportunities.",
      "Jeff Lahti relies more upon movement and inducing contact than accumulating strikeouts.",
      "Lahti can enter during the middle innings with runners already on base.",
      "His ability to limit home runs is particularly valuable in close games.",
      "Jeff Lahti gives the Cardinals a dependable bridge between the starter and Bruce Sutter.",
    ],
  },
  "Ralph Citarella": {
    lines: [
      "Ralph Citarella's full name is Ralph Alexander Citarella.",
      "Citarella was born in East Orange, New Jersey.",
      "Ralph Citarella is a right-handed pitcher.",
      "Citarella developed in the St. Louis minor-league system.",
      "Ralph Citarella spent much of the 1983 season with Triple-A Louisville.",
      "Citarella worked as both a starter and reliever in the minor leagues.",
      "Ralph Citarella was promoted to St. Louis late in the 1983 season.",
      "Citarella made his major-league debut on September 13, 1983.",
      "Ralph Citarella appeared in six games.",
      "All six of Citarella's appearances came in relief.",
      "Ralph Citarella worked 11 innings.",
      "Citarella allowed only eight hits.",
      "Ralph Citarella surrendered two earned runs.",
      "Citarella posted a 1.64 ERA.",
      "Ralph Citarella walked three hitters and struck out four.",
      "Citarella did not receive a win, loss or save.",
      "Ralph Citarella had faced only 42 major-league batters entering 1984.",
      "Opposing hitters therefore possess very little firsthand experience against him.",
      "Citarella can provide extended relief because of his minor-league starting background.",
      "Ralph Citarella enters the season attempting to prove that his strong September trial was not simply a small-sample performance.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive — base hit.\"",
    "\"Long drive to left field — way back — gone. Home run!\"",
    "\"Ground ball to short — over to first — in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub can fly — Whitey Ball at its finest — speed, defense and pitching.\"",
    "\"St. Louis baseball is alive and well — the best fans in baseball love their Cardinals.\"",
    "\"This team has speed and defense — Coleman, McGee, Ozzie Smith — the Cardinals can run.\"",
    "\"Busch Stadium is home — and the Cardinals are the defending World Series champions.\"",
    "\"Ozzie Smith is the best defensive shortstop who ever lived — bar none.\"",
    "\"Vince Coleman stole 145 bases in the minors last year — that's incredible.\"",
    "\"Willie McGee can fly — he covers more ground in center field than anybody.\"",
    "\"There's talent everywhere you look in this lineup — the Cardinals can hurt you.\"",
    "\"This club plays Whitey Ball — steal a base, move a runner, play defense.\"",
    "\"The fans in St. Louis have been waiting for another pennant — they got one in '82.\"",
    "\"There's a buzz around the Cardinals this year — the defending champs are ready.\"",
    "\"From the Wizard to Silent George to Darrell Porter — the Cardinals have stars at every position.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Ozzie Smith is the Wizard of Oz — he does things at shortstop that nobody else can.\"",
    "\"Vince Coleman stole 145 bases in the minors — wait until he gets to the big leagues.\"",
    "\"Willie McGee is the most exciting center fielder in the National League.\"",
    "\"George Hendrick doesn't say much, but he sure can hit — Silent George delivers.\"",
    "\"Bruce Sutter and that split-finger fastball — there's nothing more unhittable in baseball.\"",
    "\"Darrell Porter was the MVP of the '82 World Series — he's a clutch performer.\"",
    "\"Joaquin Andujar won Game Seven of the World Series — he's a competitor.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Busch Memorial Stadium.\"",
    "\"The lights are on at Busch Stadium — Cardinals baseball tonight.\"",
    "Busch Memorial Stadium — home of the Cardinals since 1966.",
    "\"The Gateway Arch is looming beyond the outfield wall — best backdrop in baseball.\"",
    "\"The artificial turf plays fast tonight — ground balls will scoot through the infield.\"",
    "\"The stands are filling up nicely — St. Louis loves its Cardinals.\"",
    "\"You can see the Mississippi River beyond the stadium — downtown St. Louis at its finest.\"",
    "\"Busch Stadium is rocking tonight — the best fans in baseball are here.\"",
    "\"The Cardinal Nation is out in force tonight — red as far as the eye can see.\"",
    "\"The Anheuser-Busch sign gleams above the stadium — this is St. Louis.\"",
    "\"The Steamboat is fired up behind the bleachers — Cardinals baseball is a St. Louis tradition.\"",
    "\"A perfect evening for baseball at the old ballpark on the river.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here at Busch Stadium is into this ballgame.\"",
    "\"Cardinals fans are making some noise tonight.\"",
    "\"The fans in St. Louis are the best in baseball — they know the game.\"",
    "\"Busch Stadium is rocking tonight.\"",
    "\"St. Louis fans are the most knowledgeable in baseball — they appreciate good fundamental play.\"",
    "\"The crowd is on its feet — they can feel something building here.\"",
    "\"A great turnout at Busch Stadium tonight.\"",
    "\"These fans love their Cardinals — red everywhere you look.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Busch Stadium, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball in St. Louis.\"",
    "\"From all of us here at KMOX, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story — that's the beauty of this sport.\"",
    "\"Baseball in St. Louis — it's a way of life in this city.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That's a winner!\"",
    "\"Go crazy, folks! Go crazy!\"",
    "\"The Cardinals are making their move here at Busch Stadium.\"",
    "\"That ball is gone — into the St. Louis night!\"",
    "\"I don't believe what I just saw!\"",
    "\"And the Cardinals win it — what a finish at Busch!\"",
  ]},
};