// Montreal Expos Broadcast - 1984
// Radio: Dave Van Horne (English) / TV: Duke Snider & Bill White
// Olympic Stadium - home of the Expos since 1977
// All stats cutoff: end of 1983 season

export function pickExposLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickExposPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Tim Raines": {
    lines: [
      "Tim Raines' full name is Timothy Raines.",
      "Raines was born in Sanford, Florida.",
      "Tim Raines is commonly known by the nickname \"Rock.\"",
      "Montreal selected Raines in the fifth round of the 1977 amateur draft.",
      "Raines began his professional career as a second baseman.",
      "Montreal moved him to the outfield to make better use of his exceptional speed.",
      "Tim Raines made his major-league debut during September 1979.",
      "Raines was used primarily as a pinch-runner during his first major-league opportunities.",
      "Tim Raines became an everyday player during the strike-shortened 1981 season.",
      "Raines batted .304 and stole 71 bases in only 88 games during 1981.",
      "Tim Raines finished second to Fernando Valenzuela in the 1981 National League Rookie of the Year voting.",
      "Raines led the National League with 78 stolen bases in 1982.",
      "Tim Raines appeared in 156 games during the 1983 season.",
      "Raines batted .298 with 183 hits.",
      "Tim Raines collected 32 doubles, eight triples and 11 home runs.",
      "Raines drove in 71 runs and scored 133 times.",
      "Tim Raines led the National League with 90 stolen bases.",
      "Raines was caught stealing only 14 times.",
      "Tim Raines drew 97 walks and posted a .393 on-base percentage.",
      "Raines finished fifth in the 1983 National League Most Valuable Player voting.",
      "Tim Raines has led the National League in stolen bases during each of his first three full seasons.",
      "Raines has been selected to three consecutive National League All-Star teams.",
      "Tim Raines is a switch-hitter capable of bunting, driving the gaps or working a walk.",
      "A routine single or walk can quickly become a scoring opportunity when Raines is involved.",
    ],
  },
  "Terry Francona": {
    lines: [
      "Terry Francona's full name is Terry Jon Francona.",
      "Francona was born in Aberdeen, South Dakota.",
      "Terry Francona is the son of longtime major-league outfielder Tito Francona.",
      "Francona grew up in New Brighton, Pennsylvania.",
      "Terry Francona played college baseball at the University of Arizona.",
      "Francona helped Arizona win the 1980 College World Series.",
      "Terry Francona was named the Most Outstanding Player of that College World Series.",
      "Francona also received the 1980 Golden Spikes Award as the country's leading amateur player.",
      "Montreal selected Terry Francona with the 22nd overall pick of the 1980 amateur draft.",
      "Francona made his major-league debut during the 1981 season.",
      "Terry Francona bats and throws left-handed.",
      "Francona has played first base and both corner-outfield positions.",
      "Terry Francona batted .321 in 46 games during the 1982 season.",
      "Francona appeared in 120 games during the 1983 season.",
      "Terry Francona collected 59 hits in 230 official at-bats.",
      "Francona recorded 11 doubles, one triple and three home runs.",
      "Terry Francona drove in 22 runs and scored 21 times.",
      "Francona batted .257 during the 1983 season.",
      "Terry Francona emphasizes contact and line drives rather than attempting to hit every pitch for power.",
      "Francona can shift between first base and the outfield without forcing several other defensive changes.",
      "His father's long professional career provided Terry with an early education in clubhouse life and major-league preparation.",
    ],
  },
  "Andre Dawson": {
    lines: [
      "Andre Dawson's full name is Andre Nolan Dawson.",
      "Dawson was born in Miami, Florida.",
      "Andre Dawson is commonly known by the nickname \"The Hawk.\"",
      "Dawson received the nickname because of the intense way he watched the baseball.",
      "Andre Dawson played college baseball at Florida A&M University.",
      "Montreal selected Dawson in the 11th round of the 1975 amateur draft.",
      "Dawson made his major-league debut during September 1976.",
      "Andre Dawson became Montreal's regular center fielder during the 1977 season.",
      "Dawson batted .282 with 19 home runs and 21 stolen bases as a rookie.",
      "Andre Dawson won the 1977 National League Rookie of the Year Award.",
      "Dawson possesses all five traditional tools: hitting, power, speed, throwing and fielding.",
      "Andre Dawson won his first Gold Glove and Silver Slugger awards in 1980.",
      "Dawson helped Montreal reach the postseason for the first time in 1981.",
      "Andre Dawson finished second in the 1981 National League Most Valuable Player voting.",
      "Dawson won another Gold Glove and Silver Slugger in 1982.",
      "Andre Dawson appeared in 159 games during the 1983 season.",
      "Dawson led the National League with 189 hits and 341 total bases.",
      "Andre Dawson batted .299 with 36 doubles and 10 triples.",
      "Dawson hit 32 home runs and drove in 113 runs.",
      "Andre Dawson scored 104 runs and stole 25 bases.",
      "Dawson surpassed 30 home runs and 100 RBI for the first time in 1983.",
      "Andre Dawson won another Gold Glove and Silver Slugger after the season.",
      "Dawson finished second to Dale Murphy in the 1983 National League MVP voting.",
      "The artificial turf at Olympic Stadium places considerable strain on Dawson's knees.",
      "Andre Dawson has already endured several knee operations but continues to play with exceptional intensity.",
      "Dawson's throwing arm can discourage a runner from attempting to take an extra base.",
      "The Hawk enters 1984 after one of the finest all-around seasons by any player in baseball.",
    ],
  },
  "Gary Carter": {
    lines: [
      "Gary Carter's full name is Gary Edmund Carter.",
      "Carter was born in Culver City, California.",
      "Gary Carter attended Sunny Hills High School in Fullerton, California.",
      "Montreal selected Carter in the third round of the 1972 amateur draft.",
      "Carter was only 19 when veteran teammates began calling him \"The Kid\" during spring training.",
      "Gary Carter made his major-league debut during September 1974.",
      "Carter appeared in the outfield as well as behind the plate early in his career.",
      "Gary Carter became Montreal's regular catcher during the 1975 season.",
      "Carter was selected to the National League All-Star team as a rookie.",
      "Gary Carter finished second in the 1975 National League Rookie of the Year voting.",
      "Carter developed into one of baseball's finest combinations of power hitting and defensive catching.",
      "Gary Carter won three consecutive Gold Glove Awards from 1980 through 1982.",
      "Carter also received Silver Slugger Awards in 1981 and 1982.",
      "Gary Carter hit two home runs during the 1981 All-Star Game.",
      "Carter was named the Most Valuable Player of that All-Star Game.",
      "Gary Carter helped Montreal win the 1981 National League Division Series.",
      "Carter has been selected to six All-Star teams through the 1983 season.",
      "Gary Carter appeared in 145 games during the 1983 season.",
      "Carter batted .270 with 146 hits.",
      "Gary Carter collected 37 doubles, three triples and 17 home runs.",
      "Carter drove in 79 runs and scored 63 times.",
      "Gary Carter drew 51 walks while striking out only 57 times.",
      "Carter's strong throwing arm places constant pressure upon opposing base stealers.",
      "Gary Carter is highly involved in planning how Montreal's pitchers attack opposing hitters.",
      "Carter's enthusiasm and willingness to play every day are major reasons teammates continue to call him \"The Kid.\"",
      "Gary Carter enters 1984 as one of the most complete catchers in either league.",
    ],
  },
  "Tim Wallach": {
    lines: [
      "Tim Wallach's full name is Timothy Charles Wallach.",
      "Wallach was born in Huntington Park, California.",
      "Tim Wallach played college baseball at California State University, Fullerton.",
      "Wallach became one of the leading college players in the country.",
      "Montreal selected Tim Wallach with the tenth overall pick of the 1979 amateur draft.",
      "Wallach made his major-league debut during the 1980 season.",
      "Tim Wallach hit a home run during his first major-league game.",
      "Wallach originally appeared at both first base and third base.",
      "Tim Wallach gradually established himself as Montreal's regular third baseman.",
      "Wallach's strong arm is particularly useful on Olympic Stadium's artificial turf.",
      "Tim Wallach appeared in 156 games during the 1983 season.",
      "Wallach collected 156 hits.",
      "Tim Wallach recorded 33 doubles and three triples.",
      "Wallach hit 19 home runs and drove in 70 runs.",
      "Tim Wallach scored 54 runs during the season.",
      "Wallach drew 55 walks.",
      "Tim Wallach batted .269 with a .335 on-base percentage.",
      "Wallach slugged .434 during the 1983 season.",
      "Tim Wallach supplies right-handed power behind Carter and Dawson.",
      "Wallach can drive the baseball toward right-center rather than relying entirely upon pulling pitches.",
      "Tim Wallach enters 1984 at only 26 years old and is still approaching his physical prime.",
    ],
  },
  "Jim Wohlford": {
    lines: [
      "Jim Wohlford's full name is James Eugene Wohlford.",
      "Wohlford was born in Visalia, California.",
      "Jim Wohlford attended Mount Whitney High School.",
      "Wohlford later attended College of the Sequoias.",
      "The California Angels selected Wohlford in the 11th round of the 1969 draft, but he did not sign.",
      "Kansas City selected Jim Wohlford in the third round of a 1970 secondary draft.",
      "Wohlford made his major-league debut with the Royals during September 1972.",
      "Jim Wohlford became a regular member of Kansas City's outfield during the mid-1970s.",
      "Wohlford stole a career-high 22 bases during the 1976 season.",
      "Jim Wohlford was part of Kansas City's first division-championship team in 1976.",
      "Wohlford later played for Milwaukee and San Francisco.",
      "Jim Wohlford batted .297 for Milwaukee during the 1978 season.",
      "Montreal acquired Wohlford from San Francisco before the 1983 season.",
      "Jim Wohlford appeared in 83 games for the Expos in 1983.",
      "Wohlford collected 39 hits in 141 official at-bats.",
      "Jim Wohlford batted .277 with one home run and 14 RBI.",
      "Wohlford has spent most of his career in left field but can cover any outfield position.",
      "Jim Wohlford gives Montreal an experienced right-handed hitter against left-handed pitching.",
      "Wohlford's speed has declined from his younger years, but his route-running and judgment remain useful.",
      "He is comfortable serving as a starter, pinch-hitter or late-game defensive replacement.",
    ],
  },
  "Doug Flynn": {
    lines: [
      "Doug Flynn's full name is Robert Douglas Flynn.",
      "Flynn was born in Lexington, Kentucky.",
      "Doug Flynn attended Bryan Station High School.",
      "Flynn also attended Somerset Community College and the University of Kentucky.",
      "Doug Flynn began his major-league career with Cincinnati.",
      "Flynn made his major-league debut during the 1975 season.",
      "Doug Flynn served as a reserve infielder for Cincinnati's \"Big Red Machine.\"",
      "Flynn earned World Series championship rings with the Reds in 1975 and 1976.",
      "Doug Flynn was one of the players sent to the Mets in the 1977 trade for Tom Seaver.",
      "Flynn became New York's regular second baseman.",
      "Doug Flynn won a National League Gold Glove Award in 1980.",
      "Flynn later played for Texas before Montreal purchased his contract in August 1982.",
      "Doug Flynn appeared in 143 games for Montreal during the 1983 season.",
      "Flynn collected 107 hits in 452 official at-bats.",
      "Doug Flynn recorded 18 doubles and four triples.",
      "Flynn drove in 26 runs and scored 44 times.",
      "Doug Flynn batted .237 and did not hit a home run.",
      "Flynn struck out only 38 times in 477 plate appearances.",
      "Doug Flynn's primary strengths are defense, contact and the ability to move runners.",
      "Flynn can play second base, shortstop or third base.",
      "He is more likely to shorten his swing and put the ball in play than attempt to hit for distance.",
    ],
  },
  "Angel Salazar": {
    lines: [
      "Angel Salazar's full name is Argenis Antonio Salazar.",
      "Salazar was born in Anaco, Venezuela.",
      "Angel Salazar bats and throws right-handed.",
      "Montreal signed Salazar as an amateur free agent in 1980.",
      "Salazar began his professional career with the Calgary Expos.",
      "Angel Salazar developed primarily as a shortstop.",
      "Salazar reached Triple-A Wichita at age 21 during the 1983 season.",
      "Angel Salazar batted .302 for Wichita.",
      "Salazar's minor-league value came primarily from contact and defense rather than walks or home-run power.",
      "Angel Salazar made his major-league debut on August 10, 1983.",
      "Salazar appeared in 36 games for Montreal.",
      "Angel Salazar collected eight hits in 37 official at-bats.",
      "Salazar recorded one double, one triple and one RBI.",
      "Angel Salazar batted .216 during his first major-league opportunity.",
      "Salazar drew one walk and struck out eight times.",
      "Angel Salazar is still only 22 years old entering the 1984 season.",
      "His quick hands and throwing arm give Montreal a young defensive option at shortstop.",
      "Salazar's limited major-league resume means most opposing pitchers have seen him only a handful of times.",
    ],
  },
  "Chris Speier": {
    lines: [
      "Chris Speier's full name is Chris Edward Speier.",
      "Speier was born in Alameda, California.",
      "Chris Speier attended Alameda and Encinal high schools.",
      "Speier later attended Laney College and the University of California, Santa Barbara.",
      "San Francisco selected Chris Speier with the second overall pick of the January 1970 secondary draft.",
      "Speier made his major-league debut on April 7, 1971.",
      "Chris Speier was only 20 years old when he reached the majors.",
      "Speier collected two hits and drove in two runs during his debut.",
      "Chris Speier became San Francisco's regular shortstop almost immediately.",
      "Speier was selected to three consecutive National League All-Star teams from 1972 through 1974.",
      "Montreal acquired Chris Speier from the Giants during the 1977 season.",
      "On July 20, 1978, Speier hit for the cycle against the Atlanta Braves at Olympic Stadium.",
      "Chris Speier became the first Montreal player to hit for the cycle at Olympic Stadium.",
      "Speier appeared in 156 games during the 1982 season.",
      "Chris Speier appeared in 88 games during the 1983 season.",
      "Speier batted .257 with 67 hits.",
      "Chris Speier recorded 12 doubles, two triples and two home runs.",
      "Speier drove in 22 runs and scored 24 times.",
      "Chris Speier can play shortstop, second base or third base.",
      "Speier gives Montreal an experienced defensive alternative behind Angel Salazar.",
      "His knowledge of National League hitters can be especially valuable to a young shortstop.",
    ],
  },
  "Mike Stenhouse": {
    lines: [
      "Mike Stenhouse's full name is Michael Steven Stenhouse.",
      "Stenhouse was born in Pueblo, Colorado.",
      "Mike Stenhouse attended Harvard University.",
      "Stenhouse was a two-time All-American and three-time All-Ivy League selection.",
      "Mike Stenhouse's father, Dave, pitched in the major leagues for the Washington Senators.",
      "Dave Stenhouse was selected to the American League All-Star team as a rookie in 1962.",
      "Oakland selected Mike Stenhouse with the 26th overall pick of the 1979 draft.",
      "Stenhouse chose to return to Harvard rather than immediately sign.",
      "Montreal selected Mike Stenhouse fourth overall in the January 1980 secondary draft.",
      "Stenhouse bats left-handed and throws right-handed.",
      "Mike Stenhouse can play first base and either corner-outfield position.",
      "Stenhouse dominated Triple-A pitching for Wichita during the 1983 season.",
      "Mike Stenhouse batted .355 with a .490 on-base percentage.",
      "Stenhouse slugged .681.",
      "Mike Stenhouse collected 33 doubles, five triples and 25 home runs.",
      "Stenhouse drove in 93 runs and scored 93 times.",
      "Mike Stenhouse led the American Association in batting average, on-base percentage and slugging percentage.",
      "Stenhouse was named the league's Most Valuable Player.",
      "Mike Stenhouse was also recognized as Montreal's top minor-league player.",
      "Stenhouse appeared in 24 major-league games during 1983.",
      "Mike Stenhouse collected five hits in 40 at-bats.",
      "Stenhouse enters 1984 with excellent minor-league numbers but very little established major-league success.",
    ],
  },
  "Tony Scott": {
    lines: [
      "Tony Scott's full name is Anthony Scott.",
      "Scott was born in Cincinnati, Ohio.",
      "Tony Scott attended Withrow High School in Cincinnati.",
      "Montreal selected Scott in the 71st round of the 1969 amateur draft.",
      "Scott was one of the latest selections in the entire draft.",
      "Tony Scott is a switch-hitter who throws right-handed.",
      "Scott made his major-league debut with Montreal during the 1973 season.",
      "Tony Scott played for the Expos through the 1975 season.",
      "Scott later became a regular outfielder for the St. Louis Cardinals.",
      "Tony Scott also played for the Houston Astros.",
      "Scott is capable of handling all three outfield positions.",
      "Tony Scott appeared in 80 games for Houston during the 1983 season.",
      "Scott collected 42 hits in 186 official at-bats.",
      "Tony Scott recorded six doubles, one triple and two home runs.",
      "Scott drove in 17 runs and scored 20 times.",
      "Tony Scott stole five bases.",
      "Scott batted .226 with a .264 on-base percentage.",
      "Tony Scott returns to Montreal as a veteran with considerable experience in center field.",
      "Scott can pinch-hit from either side of the plate.",
      "His speed and defensive experience make him useful as a late-inning outfield replacement.",
    ],
  },
  "Bryan Little": {
    lines: [
      "Bryan Little's full name is Richard Bryan Little.",
      "Little is a switch-hitter who throws right-handed.",
      "Bryan Little played college baseball at Texas A&M University.",
      "The Los Angeles Dodgers selected Little during the January 1978 draft.",
      "Montreal later selected Bryan Little in the ninth round of the 1980 amateur draft.",
      "Little developed primarily as a middle infielder.",
      "Bryan Little made his major-league debut during the 1982 season.",
      "Little entered the 1983 season with an opportunity to win Montreal's shortstop position.",
      "Bryan Little appeared at shortstop, second base and third base.",
      "Little played in 106 games during the 1983 season.",
      "Bryan Little collected 91 hits.",
      "Little recorded 15 doubles, three triples and one home run.",
      "Bryan Little drove in 36 runs and scored 41 times.",
      "Little drew 50 walks.",
      "Bryan Little struck out only 22 times in 350 official at-bats.",
      "Little batted .260 with a .352 on-base percentage.",
      "Bryan Little's low strikeout total demonstrates excellent bat control.",
      "Little is more likely to reach base or move a runner than to hit a long home run.",
      "Bryan Little provides Montreal with a switch-hitting alternative at either middle-infield position.",
    ],
  },
  "Razor Shines": {
    lines: [
      "Razor Shines' full name is Anthony Razor Shines.",
      "Razor is part of his actual name rather than merely a baseball nickname.",
      "Shines was born in Durham, North Carolina.",
      "Razor Shines attended Louisburg College and Saint Augustine's College.",
      "Montreal selected Shines in the 18th round of the 1978 amateur draft.",
      "Shines is a switch-hitter who throws right-handed.",
      "Razor Shines stands approximately 6-foot-1 and weighs more than 200 pounds.",
      "Shines was originally drafted as a catcher.",
      "Razor Shines has also played first base and the outfield.",
      "Shines split the 1983 minor-league season between Double-A Memphis and Triple-A Wichita.",
      "Razor Shines hit a combined 21 home runs during the minor-league season.",
      "Shines made his major-league debut on September 9, 1983.",
      "Razor Shines was announced as a pinch-hitter, but a pitching change caused Montreal to replace him before the at-bat was completed.",
      "Shines eventually received two official major-league at-bats during 1983.",
      "Razor Shines collected one hit and finished with a .500 batting average.",
      "Shines appeared in three major-league games.",
      "Razor Shines gives Montreal a strong switch-hitting option at first base.",
      "His unusual name and enthusiastic personality make him an especially natural player for announcer commentary.",
    ],
  },
  "Charlie Lea": {
    lines: [
      "Charlie Lea's full name is Charles William Lea.",
      "Lea is a right-handed pitcher.",
      "Charlie Lea played college baseball at Memphis State University.",
      "Montreal selected Lea in the ninth round of the 1978 amateur draft.",
      "Lea made his major-league debut during the 1980 season.",
      "Charlie Lea relies upon control and changing speeds rather than overwhelming velocity.",
      "On May 10, 1981, Lea pitched a no-hitter against the San Francisco Giants.",
      "The no-hitter came during the second game of a doubleheader.",
      "Charlie Lea allowed four walks but no hits during the victory.",
      "Lea helped Montreal reach the postseason during the 1981 season.",
      "Charlie Lea came within four outs of another no-hitter against St. Louis on April 16, 1983.",
      "Lea made 33 starts during the 1983 season.",
      "Charlie Lea went 16-11.",
      "Lea recorded a 3.12 ERA.",
      "Charlie Lea's ERA was the best among Montreal's regular starting pitchers.",
      "Lea threw 222 innings.",
      "Charlie Lea completed eight games.",
      "Lea recorded four shutouts.",
      "Charlie Lea struck out 137 hitters.",
      "Lea allowed only 195 hits.",
      "Charlie Lea gives Montreal a proven winner behind the more experienced Steve Rogers.",
      "Lea is most effective when hitters cannot distinguish his fastball from his change of speed.",
    ],
  },
  "Steve Rogers": {
    lines: [
      "Steve Rogers' full name is Stephen Douglas Rogers.",
      "Rogers was born in Jefferson City, Missouri.",
      "Steve Rogers played college baseball at the University of Tulsa.",
      "Montreal selected Rogers in the first round of the 1971 amateur draft.",
      "Rogers made his major-league debut during the 1973 season.",
      "Steve Rogers earned his first major-league victory with a one-hit shutout in only his second start.",
      "Rogers quickly developed into the most durable pitcher in franchise history.",
      "Steve Rogers relies upon a sinking fastball, slider, control and changing speeds.",
      "Rogers is more likely to induce a ground ball than pursue a strikeout total.",
      "Steve Rogers has been selected to five All-Star teams through 1983.",
      "Rogers led Montreal into the postseason during the 1981 season.",
      "Steve Rogers defeated Steve Carlton and Philadelphia in Game One of the 1981 Division Series.",
      "Rogers pitched a complete-game shutout in the deciding fifth game.",
      "Steve Rogers also drove in two runs with a single during that victory.",
      "Rogers then pitched a complete-game victory over Los Angeles in Game Three of the Championship Series.",
      "Steve Rogers went 19-8 with a 2.40 ERA during the 1982 season.",
      "Rogers led the National League in earned-run average.",
      "Steve Rogers made 36 starts during the 1983 season.",
      "Rogers went 17-12 with a 3.23 ERA.",
      "Steve Rogers threw 273 innings.",
      "Rogers completed 13 games and recorded five shutouts.",
      "Steve Rogers struck out 146 hitters.",
      "Rogers remains the unquestioned workhorse of Montreal's rotation.",
      "He is capable of finishing a game without requiring help from the bullpen.",
      "Few pitchers understand the unusual mound and artificial-turf conditions at Olympic Stadium better than Steve Rogers.",
    ],
  },
  "Bill Gullickson": {
    lines: [
      "Bill Gullickson's full name is William Lee Gullickson.",
      "Gullickson was born in Marshall, Minnesota.",
      "Bill Gullickson is a right-handed pitcher.",
      "Montreal selected Gullickson in the first round of the 1977 amateur draft.",
      "Gullickson reached the major leagues during the 1979 season.",
      "Bill Gullickson established himself in the rotation during 1980.",
      "Gullickson went 10-5 with a 3.00 ERA during that season.",
      "On September 10, 1980, Bill Gullickson struck out 18 Chicago Cubs.",
      "The 18 strikeouts established a major-league record for a rookie pitcher.",
      "Gullickson pitched all nine innings as Montreal won 4-2.",
      "Bill Gullickson combines a strong fastball with excellent control.",
      "Gullickson made 34 starts during the 1983 season.",
      "Bill Gullickson went 17-12.",
      "Gullickson posted a 3.75 ERA.",
      "Bill Gullickson threw 242 and a third innings.",
      "Gullickson completed 10 games.",
      "Bill Gullickson recorded one shutout.",
      "Gullickson struck out 120 hitters while walking only 59.",
      "Bill Gullickson's 17 victories tied Steve Rogers for the team lead.",
      "Gullickson enters 1984 as a proven 200-inning starter who rarely defeats himself with walks.",
    ],
  },
  "Bryn Smith": {
    lines: [
      "Bryn Smith's full name is Bryn Nelson Smith.",
      "Smith attended Santa Maria High School in California.",
      "St. Louis selected Bryn Smith in the 49th round of the 1973 amateur draft, but he did not sign.",
      "Smith eventually entered professional baseball in the Baltimore organization.",
      "Montreal acquired Bryn Smith during a six-player trade with Baltimore in December 1977.",
      "Smith made his major-league debut during the 1981 season.",
      "Bryn Smith was initially used primarily from the bullpen.",
      "Smith appeared in 49 games during the 1983 season.",
      "Bryn Smith made 12 starts.",
      "Smith went 6-11, but his record did not reflect how effectively he pitched.",
      "Bryn Smith recorded a 2.49 ERA.",
      "Smith's 2.49 ERA was the best among Montreal pitchers with substantial workloads.",
      "Bryn Smith threw 155 and a third innings.",
      "Smith allowed 142 hits.",
      "Bryn Smith struck out 101 hitters while walking only 43.",
      "Smith completed five games.",
      "Bryn Smith recorded three shutouts and three saves.",
      "Smith flourished after receiving regular starting opportunities during the final two months of 1983.",
      "Bryn Smith relies upon command, movement and changing speeds rather than pure velocity.",
      "His experience in both roles makes him especially useful on a four-man exhibition pitching staff.",
    ],
  },
  "Jeff Reardon": {
    lines: [
      "Jeff Reardon's full name is Jeffrey James Reardon.",
      "Reardon was born in Dalton, Massachusetts.",
      "Jeff Reardon played college baseball at the University of Massachusetts.",
      "Reardon began his major-league career with the New York Mets.",
      "Jeff Reardon made his major-league debut during the 1979 season.",
      "Montreal acquired Reardon and Dan Norman from the Mets during May 1981.",
      "The Expos sent outfielder Ellis Valentine to New York.",
      "Jeff Reardon gradually developed into Montreal's primary late-inning reliever.",
      "Reardon attacks hitters with a hard fastball.",
      "Jeff Reardon is willing to challenge hitters inside rather than nibble around the strike zone.",
      "Reardon appeared in 66 games during the 1983 season.",
      "Jeff Reardon went 7-9 with a 3.03 ERA.",
      "Reardon recorded 21 saves.",
      "Jeff Reardon worked 92 innings.",
      "Reardon struck out 78 hitters.",
      "Jeff Reardon finished 53 games.",
      "Reardon frequently entered before the ninth inning and remained for more than three outs.",
      "His workload reflects the early-1980s use of a relief ace rather than a one-inning closer.",
      "Jeff Reardon's calm appearance disguises an aggressive pitching style.",
      "Reardon is Montreal's first choice when the club carries a narrow lead into the late innings.",
    ],
  },
  "Bob James": {
    lines: [
      "Bob James was born on August 15, 1958.",
      "James attended Verdugo Hills High School in California.",
      "Bob James began high school as a catcher before being converted into a pitcher.",
      "Montreal selected James with the ninth overall pick of the 1976 amateur draft.",
      "Bob James was the Expos' first selection that year.",
      "James reached the major leagues during the 1978 season.",
      "Bob James was only 20 years old when he first appeared for Montreal.",
      "Arm problems and inconsistent control slowed his early development.",
      "Detroit obtained Bob James conditionally before the 1983 season.",
      "The Tigers returned him to Montreal in April.",
      "Bob James appeared in 27 games for the Expos during 1983.",
      "James went 1-0 with a 2.88 ERA.",
      "Bob James recorded seven saves.",
      "James worked 50 innings.",
      "Bob James allowed only 37 hits.",
      "James struck out 56 hitters.",
      "Bob James averaged more than 10 strikeouts for every nine innings.",
      "James gives Montreal another power right-hander behind Reardon.",
      "His fastball makes him particularly useful when Montreal needs a strikeout with runners on base.",
    ],
  },
  "Gary Lucas": {
    lines: [
      "Gary Lucas' full name is Gary Paul Lucas.",
      "Lucas is a left-handed pitcher.",
      "Cincinnati selected Lucas twice during 1973, but he did not sign.",
      "Gary Lucas attended Riverside City College and Chapman University.",
      "San Diego selected Lucas in the 19th round of the 1976 amateur draft.",
      "Lucas made his major-league debut during the 1980 season.",
      "Gary Lucas has worked almost entirely as a relief pitcher.",
      "Lucas developed into one of San Diego's principal late-inning options.",
      "Gary Lucas appeared in 62 games during the 1983 season.",
      "Lucas went 5-8 with a 2.87 ERA.",
      "Gary Lucas recorded 17 saves.",
      "Lucas worked 91 innings.",
      "Gary Lucas allowed 85 hits.",
      "Lucas struck out 60 hitters while walking 34.",
      "Gary Lucas finished 41 games.",
      "Lucas is capable of working more than a single inning.",
      "Gary Lucas gives Montreal an experienced left-handed alternative in the late innings.",
      "Lucas can set up Reardon or finish the game himself when the matchup favors a left-hander.",
    ],
  },
  "Andy McGaffigan": {
    lines: [
      "Andy McGaffigan's full name is Andrew Joseph McGaffigan.",
      "McGaffigan was born in West Palm Beach, Florida.",
      "Andy McGaffigan attended Twin Lakes High School.",
      "McGaffigan also attended Palm Beach Community College and Florida Southern College.",
      "Cincinnati selected him in the 36th round of the 1974 draft, but he did not sign.",
      "The White Sox selected Andy McGaffigan in 1976, but he again remained in school.",
      "The New York Yankees selected McGaffigan in the sixth round of the 1978 draft.",
      "Andy McGaffigan was named Southern League Pitcher of the Year in 1980.",
      "McGaffigan made his major-league debut with the Yankees during 1981.",
      "Andy McGaffigan later joined the San Francisco Giants.",
      "McGaffigan appeared in 43 games during the 1983 season.",
      "Andy McGaffigan made 16 starts.",
      "McGaffigan went 3-9 with a 4.29 ERA.",
      "Andy McGaffigan worked 134 and a third innings.",
      "McGaffigan struck out 93 hitters while walking 39.",
      "Andy McGaffigan completed two games.",
      "McGaffigan's starting experience allows him to work several innings from the bullpen.",
      "Andy McGaffigan can also provide an emergency start when Montreal's rotation requires rest.",
      "His fastball and slider give him the ability to miss bats when he is ahead in the count.",
    ],
  },
  "Joe Hesketh": {
    lines: [
      "Joe Hesketh's full name is Joseph Thomas Hesketh.",
      "Hesketh was born in Lackawanna, New York.",
      "Joe Hesketh attended Frontier Central High School.",
      "Hesketh played college baseball at the State University of New York at Buffalo.",
      "Montreal selected Joe Hesketh in the second round of the 1980 amateur draft.",
      "Hesketh was the 50th overall selection.",
      "Joe Hesketh is a left-handed pitcher.",
      "Hesketh developed primarily as a starting pitcher in Montreal's farm system.",
      "Joe Hesketh split the 1980 season between Class A and Double-A.",
      "Hesketh went 9-2 with a 2.37 ERA during that first professional season.",
      "Joe Hesketh spent the 1983 season with Triple-A Wichita.",
      "Hesketh made 15 starts.",
      "Joe Hesketh went 5-5 with a 5.09 ERA.",
      "Hesketh worked 88 and a third innings.",
      "Joe Hesketh struck out 41 hitters while walking 46.",
      "Hesketh had not yet appeared in a major-league game by the end of 1983.",
      "Joe Hesketh enters 1984 as a developing left-hander still working to improve his command.",
      "His starting background makes him suitable for long relief in your exhibition bullpen.",
      "Opposing hitters possess no major-league scouting history against him entering the season.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive - base hit.\"",
    "\"Long drive to left field - way back - gone. Home run!\"",
    "\"Ground ball to short - over to first - in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub has some real talent - Raines, Dawson, Carter, Wallach - the Expos can play with anybody.\"",
    "\"Montreal baseball is alive and well - the fans here at the Big O love their Expos.\"",
    "\"This team has speed, power and defense - Tim Raines, Andre Dawson, Gary Carter - that's a foundation.\"",
    "\"Olympic Stadium is home - and the Expos are ready to make some noise in the NL East.\"",
    "\"Andre Dawson is one of the most complete players in baseball - five tools, all of them plus.\"",
    "\"Tim Raines is the most exciting leadoff hitter in the National League - 90 steals last year.\"",
    "\"Gary Carter is the best all-around catcher in baseball - bar none.\"",
    "\"There's talent everywhere you look in this lineup - the Expos can hurt you.\"",
    "\"This club is building something - Montreal believes it can contend in the East.\"",
    "\"The fans in Montreal have been waiting for a winner - this team is getting closer every year.\"",
    "\"There's a buzz around the Expos this year - people can feel something building.\"",
    "\"From the Kid to the Hawk to Rock - the Expos have stars at every key position.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Tim Raines is the most exciting player in the National League - 90 stolen bases, that's incredible.\"",
    "\"Andre Dawson does everything - hit for average, hit for power, run, throw, field - The Hawk is the complete package.\"",
    "\"Gary Carter is the best catcher in baseball - Gold Gloves, Silver Sluggers, All-Star MVPs.\"",
    "\"Steve Rogers is the workhorse of this staff - he's been carrying the Expos for a decade.\"",
    "\"Tim Wallach is developing into a genuine power threat at third base.\"",
    "\"Jeff Reardon is one of the best late-inning relievers in the league - he's the man Montreal turns to.\"",
    "\"Charlie Lea threw a no-hitter in '81 - he's proven he can dominate when his changeup is working.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Olympic Stadium.\"",
    "\"The lights are on at the Big O - Expos baseball tonight.\"",
    "Olympic Stadium - home of the Expos since 1977.",
    "\"The artificial turf plays fast tonight - ground balls will scoot through the infield.\"",
    "\"The Montreal Tower looms above the stadium - the tallest inclined tower in the world.\"",
    "\"The cavernous dimensions here make it tough on home-run hitters.\"",
    "\"The stands are filling up nicely - the fans in Montreal are excited about this club.\"",
    "\"You can hear the bilingual announcements echoing through the stadium - Montreal baseball is unique.\"",
    "\"Youppi! is working the crowd into a frenzy - the fans love that orange furball.\"",
    "\"The roof situation at the Big O is still unresolved - but the baseball goes on.\"",
    "\"A comfortable evening at Olympic Stadium - the fans here are passionate about their Expos.\"",
    "\"The Big O is hopping tonight - the crowd is into this one.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here at the Big O is into this ballgame.\"",
    "\"Expos fans are making some noise tonight.\"",
    "\"The fans in Montreal have been waiting for a winner - they're fired up tonight.\"",
    "\"Olympic Stadium is rocking tonight.\"",
    "\"Montreal fans are among the most knowledgeable in baseball - they appreciate good fundamental play.\"",
    "\"The crowd is on its feet - they can feel something building here.\"",
    "\"A great turnout at the Big O tonight.\"",
    "\"These fans love their Expos - from the Kid to the Hawk to Rock, they've got stars to cheer for.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Olympic Stadium, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball at the Big O.\"",
    "\"From all of us here in Montreal, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story - that's the beauty of this sport.\"",
    "\"Baseball in Montreal - it's a bilingual love affair with the game.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone - into the seats at the Big O!\"",
    "\"Touch 'em all, Andre! The Hawk goes deep!\"",
    "\"The Expos are making their move here at Olympic Stadium.\"",
    "\"El grande! That one is out of here!\"",
    "\"You won't see many better than that one.\"",
    "\"And Montreal goes crazy - what a finish at the Big O!\"",
  ]},
};