// Fan chatter lines — displayed in the FanChirpBox during gameplay
// Distinct from bench/player chirps

// ── UNIVERSAL (any ballpark) ──
export const UNIVERSAL_FAN_YELLS = [
  // Ump complaints
  "Open your eyes, ump!",
  "That was outside!",
  "Where was that pitch?",
  "You're missing a good game!",
  "Check your prescription!",
  "That plate ain't that wide!",
  "Call it both ways!",
  "Same pitch, blue!",
  "Come on, blue!",
  "You're guessing now!",
  "Ask the first-base ump!",
  "Get some glasses!",
  "That was a strike!",
  "That was ball four!",
  "He was out by a mile!",
  "He was safe by a mile!",
  "You blew that call!",
  "Wake up, ump!",
  "That's two you've missed!",
  "Your zone keeps moving!",
  "Pick a strike zone!",
  "That's not a strike!",
  "That's not even close!",
  "Quit helping the pitcher!",
  "Quit squeezing him!",
  "Check the ball!",
  "Check his glove!",
  "He's balking!",
  "Watch the runner!",
  "Keep him honest!",
  // Pitching advice
  "Throw it over the plate!",
  "Make him hit it!",
  "Bring the heat!",
  "Give him the hook!",
  "He's got nothing left!",
  "Get the bullpen up!",
  "Take him out!",
  "Leave him in!",
  "One more pitch!",
  "Don't nibble!",
  "Challenge him!",
  "Go right after him!",
  "Throw the good one!",
  "He's sitting fastball!",
  "Watch the changeup!",
  "Don't hang it!",
  "Keep it down!",
  "Finish him off!",
  "Strike this guy out!",
  "Let's see the heater!",
  // Hitting advice
  "Protect the plate!",
  "Shorten up!",
  "Meet the ball!",
  "Wait for your pitch!",
  "Don't chase that!",
  "Make him throw strikes!",
  "Drive it the other way!",
  "Hit it where they ain't!",
  "Put one in the seats!",
  "Knock the cover off it!",
  "Give us a souvenir!",
  // Baserunning
  "Let's start a rally!",
  "Keep the line moving!",
  "Two-out magic!",
  "Bring him home!",
  "Get him over!",
  "Lay one down!",
  "Run on him!",
  "Take the extra base!",
  "Send him!",
  "Hold him!",
  "Get back!",
  "Slide!",
  "Beat it out!",
  "Dig, dig, dig!",
  "Turn two!",
  // Defense
  "Step on the bag!",
  "Hit the cutoff man!",
  "Keep it in front!",
  "Use two hands!",
  "Call it!",
  "Somebody catch it!",
  "Get under it!",
  "Back him up!",
  "Nice arm!",
  "Nice throw!",
  "Nice catch!",
  "That's leather!",
  "Nothing drops!",
  "Play the line!",
  "Guard the gap!",
  "Move your feet!",
  "Get dirty!",
  // Manager chirps
  "Manager, do something!",
  "Go argue that one!",
  "That's your best move?",
  "Who made that lineup?",
  "Wrong guy, skipper!",
  "Hit the showers!",
  "We paid to see baseball!",
  // Extras added for flavor
  "LET'S GO!",
  "Tie game, anything can happen!",
  "Crowd's into it now!",
  "We need a big hit here!",
  "Make some noise!",
  "Nobody out, let's go!",
  "That's a good at-bat!",
  "Work the count!",
  "That's all he's got!",
  "Here we go!",
  "Pick it up out there!",
  "Energy, guys, energy!",
  "Let's get one back!",
  "Come on, get a hit!",
  "Crowd on their feet!",
];

// ── TEAM-SPECIFIC ──
export const TEAM_FAN_YELLS = {
  cubs: [
    "Ryno, turn two!",
    "Sandberg, start the rally!",
    "Dernier, get on base!",
    "Gary, drive him home!",
    "Durham, clear the wall!",
    "Moreland, find the gap!",
    "Jody, block the plate!",
    "Cey, launch one!",
    "Bowa, make the play!",
    "Sutcliffe, mow 'em down!",
    "Trout, keep it low!",
    "Eck, paint the corner!",
    "Lee Smith, shut the door!",
    "Let's go, Cubbies!",
    "Put one in the basket!",
    "Watch the ivy!",
    "Bleacher power!",
    "Hit it onto Waveland!",
    "Send one to Sheffield!",
    "Use the wind!",
    "Keep it out of the well!",
    "That one's in the ivy!",
    "Turn two, North Siders!",
    "Fly the W!",
    "Wake up, Wrigley!",
    "Let's hear the organ!",
    "One more for the bleachers!",
    "Make Harry sing!",
    "Hey hey, holy cow!",
    "Come on, Chicago!",
  ],
  padres: [
    "Tony, slap one through!",
    "Gwynn, find the hole!",
    "Garvey, drive one!",
    "McReynolds, go deep!",
    "Kennedy, knock him in!",
    "Templeton, turn two!",
    "Nettles, pull one!",
    "Wiggins, use your wheels!",
    "Bevacqua, come through!",
    "Goose, shut the door!",
    "Show, bring the heat!",
    "Lollar, keep it down!",
    "Dravecky, deal!",
    "Lefferts, get the lefty!",
    "Let's go, Padres!",
    "Brown and gold, get loud!",
    "Fill the Murph!",
    "San Diego, make noise!",
    "Make the Murph roar!",
    "Send one to the seats!",
    "Beat L.A.!",
    "Beat the Dodgers!",
    "Padres, start a rally!",
    "Hold 'em, San Diego!",
    "Turn two, Friars!",
    "Let's go, Friars!",
    "Make the Murph shake!",
    "One more run, Padres!",
    "Keep it fair, Tony!",
    "Bring it home, San Diego!",
  ],
  dodgers: [
    "Fernando, fool him!",
    "Fernandomania!",
    "Pedro, launch one!",
    "Sax, start the rally!",
    "Marshall, drive him in!",
    "Landreaux, find the gap!",
    "Scioscia, block the plate!",
    "Russell, turn two!",
    "Guerrero, go downtown!",
    "Hershiser, keep it low!",
    "Welch, bring the heat!",
    "Reuss, paint the corner!",
    "Howe, shut the door!",
    "Let's go, Dodgers!",
    "Blue Crew, get loud!",
    "Think blue!",
    "Send one to the pavilion!",
    "Hit it to Chavez Ravine!",
    "Beat the Giants!",
    "Beat San Francisco!",
    "Turn two, Dodgers!",
    "Keep it in the park!",
    "One more run, Blue!",
    "Make Vin shout!",
    "Let's hear Dodger Stadium!",
    "Go deep, Los Angeles!",
    "Hold 'em, Blue!",
    "Start the wave!",
    "Bring him home, Pedro!",
    "Come on, Dodgers!",
  ],
  mets: [
    "Mookie, beat it out!",
    "Mookie, start the rally!",
    "Straw, send it deep!",
    "Darryl, crush one!",
    "Keith, find the gap!",
    "Foster, drive him in!",
    "Backman, get dirty!",
    "Brooks, turn two!",
    "Hubie, come through!",
    "Doctor K, ring him up!",
    "Gooden, bring the heat!",
    "Darling, deal!",
    "Sid, keep it low!",
    "Orosco, shut the door!",
    "Let's go, Mets!",
    "Meet the Mets!",
    "Shea, make some noise!",
    "Orange and blue, get loud!",
    "Beat the Yankees!",
    "Beat Philadelphia!",
    "Turn two, Mets!",
    "Send one to the bullpen!",
    "One more run, New York!",
    "Bring him home, Keith!",
    "Strawberry fields forever!",
    "Keep it fair, Mookie!",
    "Go deep at Shea!",
    "Let's hear it, Queens!",
    "Hold 'em, Mets!",
    "Come on, Amazin's!",
  ],
  yankees: [
    "Donnie, lace one!",
    "Mattingly, drive him in!",
    "Winfield, go downtown!",
    "Randolph, start the rally!",
    "Baylor, clear the wall!",
    "Griffey, find the gap!",
    "Smalley, turn two!",
    "Wynegar, block the plate!",
    "Guidry, bring the heat!",
    "Louisiana Lightning!",
    "Niekro, dance it up there!",
    "Righetti, shut the door!",
    "Shirley, get the lefty!",
    "Let's go, Yankees!",
    "Bronx Bombers, get loud!",
    "Send one to the porch!",
    "Hit it to Monument Park!",
    "Beat Boston!",
    "Beat the Red Sox!",
    "Turn two, Yankees!",
    "One more run, Bronx!",
    "Make the Stadium shake!",
    "Pinstripes, come through!",
    "Clear the short porch!",
    "Bring him home, Donnie!",
    "Hold 'em, Yankees!",
    "Start a Bronx rally!",
    "Go deep, Big Dave!",
    "Let's hear it, Bronx!",
    "Come on, New York!",
  ],
  redsox: [
    "Boggs, use the Wall!",
    "Wade, find the gap!",
    "Evans, drive him in!",
    "Dewey, go deep!",
    "Rice, crush one!",
    "Armas, clear the Wall!",
    "Easler, come through!",
    "Buckner, shoot the gap!",
    "Gedman, block the plate!",
    "Barrett, turn two!",
    "Hurst, paint the corner!",
    "Oil Can, deal!",
    "Ojeda, keep it low!",
    "Stanley, shut the door!",
    "Let's go, Red Sox!",
    "Hit the Monster!",
    "Use Pesky's Pole!",
    "Send one onto Lansdowne!",
    "Beat the Yankees!",
    "Beat New York!",
    "Turn two, Boston!",
    "Fenway, make some noise!",
    "One more run, Sox!",
    "Bring him home, Jim!",
    "Green Monster magic!",
    "Keep it fair, Wade!",
    "Hold 'em, Boston!",
    "Start a Fenway rally!",
    "Let's hear the Fenway roar!",
    "Come on, Red Sox!",
  ],
  tigers: [
    "Sweet Lou, start it up!",
    "Whitaker, turn two!",
    "Tram, find the gap!",
    "Trammell, drive him in!",
    "Gibby, hit the roof!",
    "Parrish, clear the wall!",
    "Evans, go deep!",
    "Lemon, chase it down!",
    "Herndon, come through!",
    "HoJo, pull one!",
    "Morris, bring the heat!",
    "Petry, keep it low!",
    "Wilcox, paint the corner!",
    "Willie, shut the door!",
    "Senor Smoke, deal!",
    "Let's go, Tigers!",
    "Bless you, boys!",
    "Roar, Detroit!",
    "Hit it onto the roof!",
    "Send one to right!",
    "Turn two, Tigers!",
    "Tiger Stadium, get loud!",
    "One more run, Detroit!",
    "Bring him home, Gibby!",
    "Beat Toronto!",
    "Beat the Royals!",
    "Hold 'em, Tigers!",
    "Start a Detroit rally!",
    "Make Sparky smile!",
    "Come on, Motor City!",
  ],
  orioles: [
    "Cal, lace one!",
    "Ripken, turn two!",
    "Eddie, go deep!",
    "Murray, drive him in!",
    "Singleton, find the gap!",
    "Lowenstein, pull one!",
    "Roenicke, come through!",
    "Dempsey, block the plate!",
    "Dauer, start the rally!",
    "Bumbry, use your wheels!",
    "Flanagan, deal!",
    "McGregor, keep it low!",
    "Davis, bring the heat!",
    "Tippy, shut the door!",
    "Let's go, Orioles!",
    "Oriole Magic!",
    "Birdland, get loud!",
    "Send one over the wall!",
    "Beat the Yankees!",
    "Beat Boston!",
    "Turn two, Birds!",
    "Memorial, make noise!",
    "One more run, Baltimore!",
    "Bring him home, Eddie!",
    "Keep it fair, Cal!",
    "Hold 'em, Orioles!",
    "Start a Birdland rally!",
    "Go deep, Iron Man!",
    "Let's hear it, Baltimore!",
    "Come on, O's!",
  ],
  reds: [
    "Cobra, strike hard!",
    "Parker, drive him in!",
    "Concepcion, turn two!",
    "Davey, find the gap!",
    "Esasky, go deep!",
    "Oester, start the rally!",
    "Redus, use your wheels!",
    "Milner, beat it out!",
    "Bilardello, block the plate!",
    "Soto, bring the heat!",
    "Hume, keep it low!",
    "Power, shut the door!",
    "Pastore, paint the corner!",
    "Price, get the lefty!",
    "Let's go, Reds!",
    "Big Red Machine!",
    "Riverfront, get loud!",
    "Send one to the red seats!",
    "Beat the Dodgers!",
    "Beat the Cubs!",
    "Turn two, Cincinnati!",
    "One more run, Reds!",
    "Bring him home, Cobra!",
    "Keep it fair, Davey!",
    "Hold 'em, Cincinnati!",
    "Start a Riverfront rally!",
    "Go deep, Nick!",
    "Make Riverfront rock!",
    "Let's hear it, Queen City!",
    "Come on, Redlegs!",
  ],
  royals: [
    "George, find the gap!",
    "Brett, drive him in!",
    "Willie, turn on the jets!",
    "Wilson, beat it out!",
    "Frank, turn two!",
    "White, bring him home!",
    "McRae, clear the wall!",
    "Balboni, go deep!",
    "Motley, come through!",
    "Wathan, block the plate!",
    "Saberhagen, deal!",
    "Leibrandt, keep it low!",
    "Gura, paint the corner!",
    "Quiz, shut the door!",
    "Let's go, Royals!",
    "Royals, get loud!",
    "Kauffman, make noise!",
    "Kiss the fountains!",
    "Send one to the waterfall!",
    "Beat the Yankees!",
    "Beat the Tigers!",
    "Turn two, Kansas City!",
    "One more run, Royals!",
    "Bring him home, George!",
    "Keep it fair, Brett!",
    "Hold 'em, Kansas City!",
    "Start a Royals rally!",
    "Go deep, Bye Bye!",
    "Let's hear it, K.C.!",
    "Come on, Royals!",
  ],
  phillies: [
    "Schmidt, crush one!",
    "Michael Jack, launch it!",
    "Carlton, blow it by him!",
    "Lefty, deal!",
    "Samuel, fly!",
    "Juan, use your wheels!",
    "Von Hayes, drive him in!",
    "Wilson, throw him out!",
    "Maddox, run it down!",
    "Virgil, block the plate!",
    "DeJesus, start the rally!",
    "Stone, beat it out!",
    "Holland, shut the door!",
    "Teke, submarine it!",
    "Tekulve, sink it!",
    "Andersen, get this guy!",
    "Let's go, Phillies!",
    "Roll Phanatic!",
    "The Vet is rocking!",
    "South Philly, get loud!",
    "Beat New York!",
    "Beat the Mets!",
    "Beat the Dodgers!",
    "Turn two, Phillies!",
    "One more run, Philadelphia!",
    "Bring him home, Schmidt!",
    "City of Brotherly Love, let's go!",
    "Veterans Stadium, make noise!",
    "Start a Phillies rally!",
    "Come on, Phils!",
  ],
};

/**
 * Pick a random fan yell for the given home team.
 * 50% chance of a team-specific yell (if available), 50% universal.
 */
export function pickFanYell(homeTeamKey = null) {
  const teamYells = homeTeamKey && TEAM_FAN_YELLS[homeTeamKey];
  const useTeam = teamYells && teamYells.length > 0 && Math.random() < 0.5;
  const pool = useTeam ? teamYells : UNIVERSAL_FAN_YELLS;
  return pool[Math.floor(Math.random() * pool.length)];
}

// ── FAN CHATTER ACHIEVEMENTS ──
export const FAN_CHATTER_ACHIEVEMENTS = [
  {
    id: 'fan_chatter_10',
    label: 'Bleacher Bum',
    description: 'Witnessed 10 fan yells during a game.',
    icon: '📣',
    category: 'fan',
  },
  {
    id: 'fan_chatter_50',
    label: 'Section 36',
    description: 'Witnessed 50 fan yells during a season.',
    icon: '🗣️',
    category: 'fan',
  },
  {
    id: 'fan_chatter_100',
    label: 'Die-Hard',
    description: 'Witnessed 100 fan yells. You never leave early.',
    icon: '🏟️',
    category: 'fan',
  },
  {
    id: 'fan_chatter_ump',
    label: 'Kill the Ump',
    description: 'Heard 10 ump complaints from the crowd.',
    icon: '😤',
    category: 'fan',
  },
  {
    id: 'fan_chatter_rally',
    label: 'Rally Starter',
    description: "Heard the crowd yell 'Let's start a rally!' five times.",
    icon: '🚀',
    category: 'fan',
  },
];

const UMP_PHRASES = [
  "Open your eyes, ump!", "That was outside!", "Where was that pitch?",
  "You're missing a good game!", "Check your prescription!", "That plate ain't that wide!",
  "Call it both ways!", "Same pitch, blue!", "Come on, blue!", "You're guessing now!",
  "Ask the first-base ump!", "Get some glasses!", "That was a strike!", "That was ball four!",
  "He was out by a mile!", "He was safe by a mile!", "You blew that call!", "Wake up, ump!",
  "That's two you've missed!", "Your zone keeps moving!", "Pick a strike zone!",
  "That's not a strike!", "That's not even close!", "Quit helping the pitcher!", "Quit squeezing him!",
  "Check the ball!", "Check his glove!", "He's balking!",
];

const TOTAL_YELLS_KEY = 'fanChatter_totalYells';
const UMP_YELLS_KEY = 'fanChatter_umpYells';
const RALLY_YELLS_KEY = 'fanChatter_rallyYells';

export function trackFanYell(text) {
  const unlocked = [];

  const total = (parseInt(localStorage.getItem(TOTAL_YELLS_KEY) || '0') + 1);
  localStorage.setItem(TOTAL_YELLS_KEY, total);

  if (total === 10 && !localStorage.getItem('ach_fan_chatter_10')) {
    localStorage.setItem('ach_fan_chatter_10', Date.now());
    unlocked.push('fan_chatter_10');
  }
  if (total === 50 && !localStorage.getItem('ach_fan_chatter_50')) {
    localStorage.setItem('ach_fan_chatter_50', Date.now());
    unlocked.push('fan_chatter_50');
  }
  if (total === 100 && !localStorage.getItem('ach_fan_chatter_100')) {
    localStorage.setItem('ach_fan_chatter_100', Date.now());
    unlocked.push('fan_chatter_100');
  }

  if (UMP_PHRASES.includes(text)) {
    const umpCount = (parseInt(localStorage.getItem(UMP_YELLS_KEY) || '0') + 1);
    localStorage.setItem(UMP_YELLS_KEY, umpCount);
    if (umpCount === 10 && !localStorage.getItem('ach_fan_chatter_ump')) {
      localStorage.setItem('ach_fan_chatter_ump', Date.now());
      unlocked.push('fan_chatter_ump');
    }
  }

  if (text === "Let's start a rally!") {
    const rallyCount = (parseInt(localStorage.getItem(RALLY_YELLS_KEY) || '0') + 1);
    localStorage.setItem(RALLY_YELLS_KEY, rallyCount);
    if (rallyCount === 5 && !localStorage.getItem('ach_fan_chatter_rally')) {
      localStorage.setItem('ach_fan_chatter_rally', Date.now());
      unlocked.push('fan_chatter_rally');
    }
  }

  return unlocked;
}