// Film Development & Cameras Interactive Museum Exhibits (851-875)
// 25 entries celebrating 1984 photography technology

const ENTRIES = [
  {
    id: 'kodak_gold',
    exhibit: 'Kodak Gold Film',
    icon: '📸',
    matchText: 'Kodak Gold was the standard color film for casual photographers, known for its warm, saturated colors and fine grain.',
    tagline: 'Golden Memories',
    year: '1984',
    description: 'Kodak Gold was the standard color film for casual photographers, known for its warm, saturated colors and fine grain. Available in ISO 100 and 200, it became the go-to choice for family vacations, holidays, and everyday snapshots. The rich, warm tones of Kodak Gold defined the look of 1980s family photos.',
    producer: 'Kodak',
    available: 'ISO 100, 200',
    characteristic: 'Warm, saturated colors',
    iconic: true,
    category: 'film',
    funFact: 'Kodak Gold\'s warm tones defined the aesthetic of 1980s family photography.',
  },
  {
    id: 'fujifilm_fujicolor',
    exhibit: 'Fujifilm Fujicolor',
    icon: '🎬',
    matchText: 'Fujifilm\'s Fujicolor film offered a cool, slightly blue-shifted color palette as an alternative to Kodak\'s warm tones.',
    tagline: 'Cool Colors',
    description: 'Fujifilm\'s Fujicolor film offered a cool, slightly blue-shifted color palette as an alternative to Kodak\'s warm tones. Professional photographers often preferred Fujicolor for its skin tone rendering and color accuracy. The rivalry between Kodak and Fuji films shaped the look of 1980s photography.',
    producer: 'Fujifilm',
    characteristic: 'Cool, blue-shifted palette',
    users: 'Professional photographers',
    category: 'film',
    iconic: true,
    funFact: 'Professional photographers often debated the merits of Kodak vs. Fujifilm tones.',
  },
  {
    id: 'polaroid_instant',
    exhibit: 'Polaroid Instant Film',
    icon: '🖼️',
    matchText: 'Polaroid instant film let photographers see their prints emerge from the camera in seconds, transforming spontaneous photography.',
    tagline: 'Instant Memories',
    description: 'Polaroid instant film let photographers see their prints emerge from the camera in seconds, transforming spontaneous photography. The SX-70 and other instant cameras became beloved tools for parties, events, and casual documentation. Despite the high cost per shot, the magic of instant photography made Polaroid a cultural phenomenon.',
    technology: 'Instant chemical development',
    advantage: 'Photos in seconds',
    cost: 'High per-shot',
    iconic: true,
    category: 'technology',
    funFact: 'Polaroid instant cameras became iconic status symbols in the 1980s.',
  },
  {
    id: 'canon_ae1',
    exhibit: 'Canon AE-1',
    icon: '🎥',
    matchText: 'The Canon AE-1 was the first affordable SLR camera with automatic exposure, making professional-level photography accessible to amateurs.',
    tagline: 'Democracy in Photography',
    year: '1976 (iconic 1984)',
    description: 'The Canon AE-1 was the first affordable SLR camera with automatic exposure, making professional-level photography accessible to amateurs. Though launched in 1976, it was still the industry standard in 1984, dominating photography classrooms and amateur darkrooms. The AE-1 proved that quality photography didn\'t require expensive manual cameras.',
    brand: 'Canon',
    significance: 'First affordable SLR with auto-exposure',
    impact: 'Democratized SLR photography',
    iconic: true,
    category: 'camera',
    funFact: 'The Canon AE-1 sold millions of units and launched countless photography careers.',
  },
  {
    id: 'nikon_fm2',
    exhibit: 'Nikon FM2',
    icon: '📷',
    matchText: 'The Nikon FM2 was a rugged, mechanical SLR beloved by professionals and serious amateurs for its reliability and build quality.',
    tagline: 'Built to Last',
    description: 'The Nikon FM2 was a rugged, mechanical SLR beloved by professionals and serious amateurs for its reliability and build quality. Its all-mechanical shutter meant it worked even without batteries, and its titanium shutter was famously durable. The FM2 represented the pinnacle of manual film camera engineering.',
    brand: 'Nikon',
    characteristic: 'All-mechanical, titanium shutter',
    users: 'Professionals, serious amateurs',
    iconic: true,
    category: 'camera',
    funFact: 'Nikon FM2s from the 1980s are still used by professional photographers today.',
  },
  {
    id: 'minolta_x700',
    exhibit: 'Minolta X-700',
    icon: '📹',
    matchText: 'The Minolta X-700 was an affordable, fully automatic SLR that brought SLR photography to casual photographers who didn\'t want to worry about exposure.',
    tagline: 'Set It and Forget It',
    description: 'The Minolta X-700 was an affordable, fully automatic SLR that brought SLR photography to casual photographers who didn\'t want to worry about exposure. Its program mode automatically set both aperture and shutter speed based on light conditions, eliminating exposure anxiety. The X-700 proved that automatic SLRs could appeal to serious photographers.',
    brand: 'Minolta',
    feature: 'Fully automatic exposure',
    appeal: 'Casual photographers',
    category: 'camera',
    funFact: 'The Minolta X-700 sold over 4 million units worldwide.',
  },
  {
    id: 'pentax_k1000',
    exhibit: 'Pentax K1000',
    icon: '🎞️',
    matchText: 'The Pentax K1000 was beloved by photography teachers for its simplicity, reliability, and ability to force students to learn exposure control manually.',
    tagline: 'The Teaching Camera',
    description: 'The Pentax K1000 was beloved by photography teachers for its simplicity, reliability, and ability to force students to learn exposure control manually. Its bright viewfinder and simple mechanical design made it ideal for understanding how cameras work. Generations of photography students learned on the K1000.',
    brand: 'Pentax',
    use: 'Photography education',
    strength: 'Simple, mechanical, reliable',
    category: 'camera',
    funFact: 'The Pentax K1000 was considered the ideal beginner SLR for learning exposure control.',
  },
  {
    id: 'olympus_om1',
    exhibit: 'Olympus OM-1',
    icon: '🔍',
    matchText: 'The Olympus OM-1 was a compact SLR that proved professional results didn\'t require large, heavy cameras.',
    tagline: 'Small but Mighty',
    description: 'The Olympus OM-1 was a compact SLR that proved professional results didn\'t require large, heavy cameras. Its small size and lightweight build made it ideal for travel and street photography. The OM system\'s compact lenses were also smaller than their Canon and Nikon equivalents.',
    brand: 'Olympus',
    strength: 'Compact, lightweight',
    appeal: 'Travel, street photographers',
    iconic: true,
    category: 'camera',
    funFact: 'The OM-1\'s compact size made it a favorite of photojournalists.',
  },
  {
    id: 'point_and_shoot',
    exhibit: 'Point-and-Shoot Cameras',
    icon: '📱',
    matchText: 'Simple point-and-shoot cameras with fixed lenses and automatic exposure made photography accessible to people who didn\'t want to learn camera controls.',
    tagline: 'Simplified Photography',
    description: 'Simple point-and-shoot cameras with fixed lenses and automatic exposure made photography accessible to people who didn\'t want to learn camera controls. By 1984, millions of casual photographers used basic point-and-shoots instead of SLRs. The simplicity of point-and-shoots eventually made them the dominant camera type.',
    technology: 'Fixed lens, automatic exposure',
    appeal: 'Casual photographers',
    advantage: 'No technical knowledge required',
    category: 'camera',
    funFact: 'Point-and-shoot cameras eventually outsold SLRs by millions of units.',
  },
  {
    id: 'autofocus_technology',
    exhibit: 'Autofocus Technology',
    icon: '🎯',
    matchText: 'Autofocus cameras that automatically focused on the subject were revolutionizing photography by making sharp focus nearly guaranteed.',
    tagline: 'Perfect Focus, Every Time',
    description: 'Autofocus cameras that automatically focused on the subject were revolutionizing photography by making sharp focus nearly guaranteed. Early autofocus systems were slow and sometimes unreliable, but by 1984 they were improving rapidly. Autofocus would eventually become standard on all cameras.',
    technology: 'Automatic focus adjustment',
    advantage: 'Reduced out-of-focus shots',
    drawback: 'Early systems slow, unreliable',
    category: 'technology',
    funFact: 'Autofocus revolutionized consumer photography by virtually eliminating focus errors.',
  },
  {
    id: 'flash_technology',
    exhibit: 'Electronic Flash',
    icon: '⚡',
    matchText: 'Electronic flash units, powered by batteries and capacitors, became standard equipment for photographers, enabling indoor and low-light photography.',
    tagline: 'Lighting Control',
    description: 'Electronic flash units, powered by batteries and capacitors, became standard equipment for photographers, enabling indoor and low-light photography. External flash units offered more power and flexibility than built-in flashes. The distinctive pop of an electronic flash became the sound of 1980s photography.',
    technology: 'Battery-powered light discharge',
    advantage: 'Indoor, low-light capability',
    types: ['Built-in', 'External units'],
    category: 'technology',
    funFact: 'The red-eye effect from flash photography became a common complaint by the 1980s.',
  },
  {
    id: 'tripod_essential',
    exhibit: 'The Tripod',
    icon: '🪣',
    matchText: 'Tripods were essential equipment for serious photographers, enabling long exposures, composition stability, and hands-free operation.',
    tagline: 'Steady Shots',
    description: 'Tripods were essential equipment for serious photographers, enabling long exposures, composition stability, and hands-free operation. By 1984, photographers used tripods for landscapes, portraits, studio work, and any situation requiring absolute sharpness. A quality tripod was a major investment.',
    purpose: 'Stabilization for sharp images',
    uses: ['Landscapes', 'Portraits', 'Studio work', 'Long exposures'],
    investment: 'Quality tripods expensive',
    category: 'equipment',
    funFact: 'Professional photographers considered a good tripod one of their most valuable tools.',
  },
  {
    id: 'lens_quality',
    exhibit: 'Lens Optics',
    icon: '🔭',
    matchText: 'High-quality camera lenses with precise optical coatings made the difference between mediocre and excellent photographs.',
    tagline: 'Optical Excellence',
    description: 'High-quality camera lenses with precise optical coatings made the difference between mediocre and excellent photographs. Photographers invested in premium lenses from companies like Zeiss, Leica, and Canon. A good lens could last decades and define a photographer\'s artistic style.',
    factor: 'Key to image quality',
    premium_brands: ['Zeiss', 'Leica', 'Canon', 'Nikon'],
    durability: 'Quality lenses last decades',
    category: 'equipment',
    funFact: 'Photographers often invested more in high-quality lenses than in camera bodies.',
  },
  {
    id: 'iso_film_speed',
    exhibit: 'ISO Film Speed',
    icon: '⚙️',
    matchText: 'Film speed (ISO) determined how sensitive film was to light, with higher ISO enabling faster shutter speeds in low light but reducing image quality.',
    tagline: 'Speed vs. Quality',
    description: 'Film speed (ISO) determined how sensitive film was to light, with higher ISO enabling faster shutter speeds in low light but reducing image quality. Photographers had to choose between ISO 100 (fine grain, slow) and ISO 400 (fast, grainy). Fast films like Tri-X 400 and HP5 became staples for photojournalists.',
    tradeoff: 'Higher ISO = graininess',
    usage: ['ISO 100 fine grain', 'ISO 400 fast'],
    famous_fast_films: ['Tri-X 400', 'HP5'],
    category: 'film',
    funFact: 'Fast film graincould be both a limitation and an artistic choice in 1980s photography.',
  },
  {
    id: 'black_and_white_film',
    exhibit: 'Black & White Film',
    icon: '⬛',
    matchText: 'Black and white film remained the choice of serious photographers and photojournalists for its superior tonal range and timeless quality.',
    tagline: 'Timeless Contrast',
    description: 'Black and white film remained the choice of serious photographers and photojournalists for its superior tonal range and timeless quality. Despite color film\'s dominance, many photographers considered B&W film more artistic and expressive. Darkroom B&W printing was an essential skill.',
    appeal: 'Photographers, photojournalists',
    advantage: 'Superior tonal range',
    perception: 'More artistic than color',
    iconic: true,
    category: 'film',
    funFact: 'Serious photographers often said "real photographers shoot in black and white."',
  },
  {
    id: 'darkroom_development',
    exhibit: 'Darkroom Printing',
    icon: '🖤',
    matchText: 'Darkroom printing involved developing negatives and making prints on light-sensitive paper, a skill that separated photographers from snapshooters.',
    tagline: 'The Craft of Photography',
    description: 'Darkroom printing involved developing negatives and making prints on light-sensitive paper, a skill that separated photographers from snapshooters. The darkroom was a magical space where photographers controlled contrast, dodging, and burning. Learning darkroom technique was considered essential to becoming a serious photographer.',
    process: 'Negative development + printing',
    skill: 'Advanced technique',
    perception: 'Separates amateurs from pros',
    category: 'process',
    iconic: true,
    funFact: 'Photography students spent countless hours in darkrooms learning their craft.',
  },
  {
    id: 'photo_processing_shop',
    exhibit: 'Photo Processing Shops',
    icon: '🏪',
    matchText: 'Local photo processing shops developed film and made prints, with customers waiting days or weeks for results.',
    tagline: 'The Wait',
    description: 'Local photo processing shops developed film and made prints, with customers waiting days or weeks for results. By 1984, many shops offered one-hour or same-day processing, but quality was inconsistent. Photos could be ruined by careless technicians, leading to anxiety about results.',
    timeline: '1-7 days typical',
    advancement: 'One-hour processing emerging',
    risk: 'Possible damage by technicians',
    category: 'service',
    funFact: 'The anticipation of waiting for photos to be developed was a defining 1980s experience.',
  },
  {
    id: '35mm_standard',
    exhibit: '35mm Film Standard',
    icon: '📽️',
    matchText: '35mm film had become the universal standard for both still photography and motion pictures, dominating the market completely.',
    tagline: 'The Standard',
    description: '35mm film had become the universal standard for both still photography and motion pictures, dominating the market completely. Smaller formats like 110 film and larger formats like 4x5 existed, but 35mm offered the best balance of convenience and quality. The 35mm format would remain dominant for decades.',
    format: '35mm (36mm film width)',
    adoption: 'Universal standard',
    balance: 'Convenience + quality',
    iconic: true,
    category: 'technology',
    funFact: 'The 35mm format\'s dominance began with Leica and never ended.',
  },
  {
    id: 'contact_sheets',
    exhibit: 'Contact Sheets',
    icon: '📋',
    matchText: 'Contact sheets were small prints of all negatives from a roll, allowing photographers to quickly review and select images for enlargement.',
    tagline: 'The Review Process',
    description: 'Contact sheets were small prints of all negatives from a roll, allowing photographers to quickly review and select images for enlargement. Professional photographers examined contact sheets with a magnifying loupe to spot focus, composition, and exposure. The contact sheet was the photographer\'s roadmap to selecting the best images.',
    purpose: 'Negative review and selection',
    tool: 'Magnifying loupe for examination',
    use: 'Professional workflow',
    category: 'process',
    funFact: 'Professional photographers used contact sheets to make critical selectionsmemories.',
  },
  {
    id: 'film_camera_revolution',
    exhibit: 'The Film Camera Era',
    icon: '🎬',
    matchText: 'In 1984, film cameras dominated photography with billions of rolls sold annually, before digital would eventually make them obsolete.',
    tagline: 'Peak of Film',
    year: '1984',
    description: 'In 1984, film cameras dominated photography with billions of rolls sold annually, before digital would eventually make them obsolete. The photography market was booming, with new models from Canon, Nikon, Minolta, and others competing for customers. This was the golden age of film photography.',
    market_condition: 'Booming, billions of rolls sold',
    competition: 'Canon, Nikon, Minolta, others',
    perspective: 'Peak before digital revolution',
    iconic: true,
    inspirational: true,
    category: 'milestone',
    funFact: 'In 1984, no one imagined digital cameras would replace film within two decades.',
  },
  {
    id: 'kodachrome_slides',
    exhibit: 'Kodachrome Slide Film',
    icon: '🌈',
    matchText: 'Kodachrome slide film produced the most vibrant, archival color images, though processing was complex and required a special lab.',
    tagline: 'Color Perfection',
    description: 'Kodachrome slide film produced the most vibrant, archival color images, though processing was complex and required a special lab. Kodachrome slides could last 70+ years without fading. Professional photographers, travel photographers, and serious amateurs swore by Kodachrome.',
    advantage: 'Vibrant, archival colors',
    drawback: 'Complex processing, limited labs',
    archival_life: '70+ years',
    iconic: true,
    category: 'film',
    funFact: 'Kodachrome slides remain vivid and unfaded decades later, a testament to Ektachrome quality.',
  },
  {
    id: 'photography_magazines',
    exhibit: 'Photography Magazines',
    icon: '📰',
    matchText: 'Photography magazines like National Geographic, Popular Photography, and Modern Photography provided inspiration, technique guides, and camera reviews.',
    tagline: 'Learning Photography',
    description: 'Photography magazines like National Geographic, Popular Photography, and Modern Photography provided inspiration, technique guides, and camera reviews. Photographers studied these magazines to learn new techniques and stay current with equipment. Magazine reviews heavily influenced purchasing decisions.',
    titles: ['National Geographic', 'Popular Photography', 'Modern Photography'],
    content: ['Inspiration', 'Technique guides', 'Camera reviews'],
    influence: 'Heavy influence on purchases',
    category: 'media',
    funFact: 'Photography magazines were crucial guides for amateurs learning their craft.',
  },
  {
    id: 'photographer_famous',
    exhibit: 'Photojournalism Icons',
    icon: '📸',
    matchText: 'Iconic photojournalists like Ansel Adams, Henri Cartier-Bresson, and others defined the visual language of the 20th century through their images.',
    tagline: 'Visual Storytellers',
    description: 'Iconic photojournalists like Ansel Adams, Henri Cartier-Bresson, and others defined the visual language of the 20th century through their images. Their work set standards for composition, light, and subject matter. Young photographers studied these masters to understand visual excellence.',
    masters: ['Ansel Adams', 'Henri Cartier-Bresson'],
    influence: 'Defined visual standards',
    legacy: 'Studied by all serious photographers',
    category: 'culture',
    funFact: 'Ansel Adams\' photographs of Yosemite became iconic American images.',
  },
  {
    id: 'film_preservation',
    exhibit: 'Film as Historical Record',
    icon: '🏛️',
    matchText: 'Photography became the primary way families and journalists documented history, creating billions of records that would preserve 1980s culture forever.',
    tagline: 'Preserving History',
    description: 'Photography became the primary way families and journalists documented history, creating billions of records that would preserve 1980s culture forever. Family photo albums were treasured heirlooms. Photojournalists documented wars, politics, and social change. Film truly was civilization\'s memory.',
    significance: 'Primary historical documentation',
    uses: ['Family records', 'Journalism', 'History'],
    legacy: 'Preserves culture forever',
    iconic: true,
    inspirational: true,
    category: 'culture',
    funFact: 'The photographs taken in 1984 remain the primary visual record of that year.',
  },
];

const VIEWED_EXHIBITS = new Set();
const EXHIBIT_VIEW_COUNTS = {};

export function findFilmDevelopmentCamerasEntry(adText) {
  // Exact match first, then keyword match for broadcast ad text like "Film processing"
  let match = ENTRIES.find(e => e.matchText === adText) || null;
  if (!match && adText && adText.includes('Film processing')) {
    // Map generic "Film processing" text to Polaroid Instant Film exhibit
    match = ENTRIES.find(e => e.id === 'polaroid_instant');
  }
  return match;
}

export function trackFilmDevelopmentCamerasView(entryId) {
  VIEWED_EXHIBITS.add(entryId);
  EXHIBIT_VIEW_COUNTS[entryId] = (EXHIBIT_VIEW_COUNTS[entryId] || 0) + 1;
  const unlocked = [];

  if (VIEWED_EXHIBITS.size >= 5) unlocked.push('film_enthusiast');
  if (VIEWED_EXHIBITS.size >= 15) unlocked.push('camera_aficionado');
  if (VIEWED_EXHIBITS.size >= 25) unlocked.push('film_historian');

  return unlocked;
}

export function getFilmDevelopmentCamerasViewCount() {
  return VIEWED_EXHIBITS.size;
}