// San Francisco Giants Broadcast — 1984
// Radio/TV: Hank Greenwald, Lon Simmons
// Candlestick Park — home of the Giants since 1960
// All stats cutoff: end of 1983 season

export function pickGiantsLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickGiantsPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Chili Davis": {
    lines: [
      "Chili Davis' full name is Charles Theodore Davis.",
      "Davis was born in Kingston, Jamaica.",
      "Chili Davis moved to the United States while still young.",
      "Davis attended Susan Miller Dorsey High School in Los Angeles.",
      "San Francisco selected Chili Davis in the 11th round of the 1977 amateur draft.",
      "Davis developed as a switch-hitting outfielder.",
      "Chili Davis made his major-league debut during April 1981.",
      "Davis appeared in only eight games during his first major-league trial.",
      "Chili Davis became San Francisco's regular center fielder during 1982.",
      "Davis appeared in 154 games during his first full season.",
      "Chili Davis batted .261 in 1982.",
      "Davis hit 19 home runs and drove in 76 runs.",
      "Chili Davis stole 24 bases.",
      "Davis finished fourth in the 1982 National League Rookie of the Year voting.",
      "Chili Davis was selected to the National League All-Star team in 1982.",
      "Davis followed with another full season in center field during 1983.",
      "Chili Davis possesses legitimate power from both sides of the plate.",
      "His switch-hitting makes him difficult to neutralize with a bullpen matchup.",
      "Davis has enough speed to bat first despite possessing middle-of-the-order power.",
      "Chili Davis covers considerable territory in the spacious Candlestick Park outfield.",
      "Davis has a strong throwing arm from center field.",
      "His combination of speed and power gives him the ability to affect a game without relying solely upon batting average.",
      "Davis can bunt for a hit, steal a base or drive a pitch into the seats.",
      "Opposing pitchers must be careful about falling behind because Davis can handle fastballs from either side of the plate.",
      "Entering 1984, Davis remains one of the most physically gifted young players on the San Francisco roster.",
    ],
  },
  "Joel Youngblood": {
    lines: [
      "Joel Youngblood's full name is Joel Randolph Youngblood III.",
      "Youngblood was born in Houston, Texas.",
      "Joel Youngblood attended Stephen F. Austin High School in Houston.",
      "Cincinnati selected Youngblood in the second round of the 1970 amateur draft.",
      "Joel Youngblood made his major-league debut with the Reds during 1976.",
      "Youngblood later joined the St. Louis Cardinals.",
      "Joel Youngblood was traded to the New York Mets during the 1977 season.",
      "Youngblood developed into one of the Mets' most useful and versatile players.",
      "Joel Youngblood can play third base, second base and all three outfield positions.",
      "Youngblood was selected to the 1981 National League All-Star team.",
      "On August 4, 1982, Youngblood began the day playing for the Mets in Chicago.",
      "Joel Youngblood collected a hit against Ferguson Jenkins during that afternoon game.",
      "The Mets traded him to the Montreal Expos before the game had ended.",
      "Youngblood traveled from Chicago to Philadelphia that evening.",
      "Joel Youngblood entered Montreal's game against the Phillies.",
      "Youngblood collected a hit against Steve Carlton.",
      "He became the first major-league player to record hits for two different teams in two different cities on the same day.",
      "San Francisco acquired Youngblood from Montreal later in 1982.",
      "Joel Youngblood appeared regularly for the Giants during 1983.",
      "Youngblood brings more offensive ability than teams normally expect from a utility player.",
      "His strong throwing arm is useful at third base and in right field.",
      "Youngblood can remain in a game after pinch-hitting because of his defensive flexibility.",
      "He is capable of hitting for average while also providing occasional home-run power.",
      "Youngblood's unusual 1982 accomplishment remains one of the best baseball trivia stories of the era.",
      "Starting him at third base allows the Giants to keep Chris Brown and Brad Wellman available as younger bench options.",
    ],
  },
  "Jack Clark": {
    lines: [
      "Jack Clark's full name is Jack Anthony Clark.",
      "Clark was born in New Brighton, Pennsylvania.",
      "Jack Clark attended Gladstone High School in Covina, California.",
      "San Francisco selected Clark in the 13th round of the 1973 amateur draft.",
      "Clark was originally evaluated as both a pitcher and position player.",
      "Jack Clark made his major-league debut during September 1975.",
      "Clark became San Francisco's regular right fielder.",
      "Jack Clark is commonly known by the nickname \"Jack the Ripper.\"",
      "Clark hit 25 home runs and drove in 98 runs during the 1978 season.",
      "Jack Clark was selected to the National League All-Star team that year.",
      "Clark hit 26 home runs during 1979.",
      "Jack Clark received another All-Star selection.",
      "Clark possesses one of the strongest throwing arms among National League right fielders.",
      "Jack Clark hit 27 home runs and drove in 103 runs during the 1982 season.",
      "Clark appeared in 135 games during the 1983 season.",
      "Jack Clark batted .268 with 132 hits.",
      "Clark collected 25 doubles.",
      "Jack Clark hit 20 home runs.",
      "Clark drove in 66 runs.",
      "Jack Clark scored 82 times.",
      "Clark drew 74 walks.",
      "Jack Clark posted a .361 on-base percentage.",
      "Pitchers must respect both his power and his willingness to accept a walk.",
      "Clark's throwing arm discourages runners from attempting to advance from first to third on routine singles.",
      "He is capable of producing power to the opposite field instead of relying entirely upon pulled home runs.",
      "When Clark is healthy, he is the most dangerous established power hitter in the San Francisco lineup.",
    ],
  },
  "Al Oliver": {
    lines: [
      "Al Oliver's full name is Albert Oliver Jr.",
      "Oliver was born in Portsmouth, Ohio.",
      "Al Oliver attended Portsmouth High School.",
      "Pittsburgh signed Oliver as an amateur free agent during 1964.",
      "Oliver made his major-league debut with the Pirates in 1968.",
      "Al Oliver became known by the nickname \"Scoop.\"",
      "The nickname fit both his first-base play and his smooth ability to collect base hits.",
      "Oliver became a regular on Pittsburgh's 1969 club.",
      "Al Oliver finished second in the 1969 National League Rookie of the Year voting.",
      "Oliver helped Pittsburgh win the 1971 World Series.",
      "Al Oliver developed into one of the National League's most dependable hitters.",
      "Oliver recorded more than 180 hits in several different seasons.",
      "Al Oliver was selected to multiple All-Star teams while playing for Pittsburgh.",
      "Oliver later played for the Texas Rangers.",
      "Al Oliver joined the Montreal Expos before the 1982 season.",
      "Oliver enjoyed an exceptional season in 1982.",
      "Al Oliver led the National League with a .331 batting average.",
      "Oliver also led the league in hits, doubles and total bases.",
      "Al Oliver hit 22 home runs and drove in 109 runs.",
      "Oliver was selected to the All-Star team and received a Silver Slugger Award.",
      "Al Oliver remained a productive .300 hitter during 1983.",
      "He had not yet appeared for San Francisco by the end of that season.",
      "Oliver uses an aggressive, level left-handed swing.",
      "He is especially skilled at hitting line drives into the gaps.",
      "Oliver rarely strikes out compared with most middle-of-the-order hitters.",
      "His ability to handle first base allows the Giants to place several athletic outfielders in the lineup.",
      "\"Scoop\" gives this roster an experienced left-handed hitter with a batting championship and World Series ring.",
    ],
  },
  "Jeffrey Leonard": {
    lines: [
      "Jeffrey Leonard's full name is Jeffrey Leonard.",
      "Leonard was born in Philadelphia, Pennsylvania.",
      "Jeffrey Leonard attended Overbrook High School.",
      "The Los Angeles Dodgers signed Leonard as an amateur free agent in 1973.",
      "Leonard made his major-league debut during September 1977.",
      "Jeffrey Leonard later played for the Houston Astros.",
      "San Francisco acquired Leonard from Houston before the 1981 season.",
      "Jeffrey Leonard became a regular Giants outfielder.",
      "Leonard bats and throws right-handed.",
      "Jeffrey Leonard possesses considerable raw power.",
      "Leonard is capable of playing either corner-outfield position.",
      "Jeffrey Leonard also has enough speed to take an extra base.",
      "Leonard appeared in more than 140 games during the 1983 season.",
      "Jeffrey Leonard became one of San Francisco's leading run producers.",
      "Leonard's aggressive approach can produce hard contact early in the count.",
      "Jeffrey Leonard is especially dangerous against left-handed pitching.",
      "Leonard's strong arm is useful in left or right field.",
      "He can drive pitches to the opposite field rather than merely pulling them.",
      "Jeffrey Leonard plays with visible confidence.",
      "His combination of strength and athleticism makes him a legitimate threat behind Al Oliver.",
      "Leonard can turn a mistake over the plate into an immediate extra-base hit.",
      "Pitchers who attempt to overpower him inside risk allowing him to extend his arms and pull the ball with authority.",
      "Leonard gives San Francisco another right-handed power threat behind Jack Clark.",
      "The Giants' Clark-Oliver-Leonard middle of the order forces pitchers to alternate carefully between right- and left-handed hitters.",
    ],
  },
  "Bob Brenly": {
    lines: [
      "Bob Brenly's full name is Robert Earl Brenly.",
      "Brenly was born in Coshocton, Ohio.",
      "Bob Brenly attended Ohio University.",
      "Brenly was not selected during the regular amateur draft.",
      "San Francisco signed Bob Brenly as an amateur free agent.",
      "Brenly developed primarily as a third baseman in the minor leagues.",
      "Bob Brenly later converted to catcher.",
      "Brenly made his major-league debut during August 1981.",
      "Bob Brenly became one of the Giants' primary catchers.",
      "Brenly can also play third base when required.",
      "Bob Brenly appeared in more than 100 games during the 1983 season.",
      "Brenly provided San Francisco with useful right-handed power.",
      "Bob Brenly is capable of driving a mistake over the left-field fence.",
      "Brenly's experience as an infielder helps him react quickly to bunts in front of the plate.",
      "Bob Brenly has a strong enough arm to control the running game.",
      "Brenly must coordinate a staff containing starters with very different pitching styles.",
      "Bob Brenly's responsibilities include handling Greg Minton's sinker and Gary Lavelle's left-handed breaking pitches.",
      "Brenly's offensive value separates him from purely defensive catchers.",
      "Bob Brenly can bat in the middle or lower third of the lineup.",
      "His willingness to attack fastballs makes him dangerous when pitchers attempt to steal a strike.",
      "Brenly remains relatively inexperienced compared with many National League starting catchers.",
      "His continued development behind the plate is important to the Giants' young pitching staff.",
      "Brenly's ability to play third base provides emergency flexibility on a compact exhibition roster.",
    ],
  },
  "Manny Trillo": {
    lines: [
      "Manny Trillo's full name is Jesus Manuel Marcano Trillo.",
      "Trillo was born in Caripito, Venezuela.",
      "Manny Trillo grew up in a Venezuelan oil-producing region.",
      "Philadelphia signed Trillo as an amateur free agent during the late 1960s.",
      "Trillo was selected by Oakland in the 1968 Rule 5 draft.",
      "Manny Trillo made his major-league debut with the Athletics during 1973.",
      "Trillo later became the Chicago Cubs' regular second baseman.",
      "Manny Trillo was selected to the National League All-Star team in 1977.",
      "Philadelphia acquired Trillo before the 1979 season.",
      "Manny Trillo became one of the finest defensive second basemen in baseball.",
      "Trillo possesses an exceptionally strong throwing arm for a second baseman.",
      "Manny Trillo can complete relay throws to the plate with unusual speed and accuracy.",
      "Trillo won National League Gold Glove Awards in 1979, 1981 and 1982.",
      "Manny Trillo helped Philadelphia win the 1980 World Series.",
      "Trillo batted .381 during the 1980 National League Championship Series.",
      "Manny Trillo was named Most Valuable Player of that series.",
      "Trillo received the National League Silver Slugger Award at second base in 1980.",
      "Manny Trillo later added another Silver Slugger.",
      "Trillo was selected to several All-Star teams as a Phillie.",
      "Philadelphia traded Trillo to Cleveland before the 1983 season.",
      "Manny Trillo remained with Cleveland through the end of 1983.",
      "He had not yet played for San Francisco.",
      "Trillo's hands and throwing arm are particularly valuable on difficult double-play pivots.",
      "Manny Trillo is willing to stand near the bag despite an incoming baserunner.",
      "His postseason experience strengthens a lineup containing several younger Giants.",
      "Trillo provides defense, contact hitting and championship experience at second base.",
      "His 1980 NLCS performance remains the defining offensive accomplishment of his career through 1983.",
    ],
  },
  "Johnnie LeMaster": {
    lines: [
      "Johnnie LeMaster's full name is Johnnie Lee LeMaster.",
      "LeMaster was born in Portsmouth, Ohio.",
      "Johnnie LeMaster attended Paintsville High School in Kentucky.",
      "San Francisco selected LeMaster with the sixth overall pick of the 1973 amateur draft.",
      "LeMaster developed as a shortstop in the Giants' farm system.",
      "Johnnie LeMaster made his major-league debut on September 2, 1975.",
      "LeMaster hit an inside-the-park home run during his first major-league at-bat.",
      "Johnnie LeMaster became the first player in modern major-league history to accomplish that feat in his debut plate appearance.",
      "LeMaster gradually became San Francisco's regular shortstop.",
      "Johnnie LeMaster is a tall, lean infielder with good range.",
      "LeMaster has played on Candlestick Park's artificial turf and natural grass surfaces.",
      "Johnnie LeMaster appeared in 154 games during the 1983 season.",
      "LeMaster's durability allowed the Giants to keep a stable defensive alignment.",
      "Johnnie LeMaster is known more for defense and speed than home-run power.",
      "LeMaster can steal an occasional base.",
      "Johnnie LeMaster has enough speed to take an extra base on a ball into the outfield gap.",
      "LeMaster's long reach helps him handle throws around second base.",
      "Johnnie LeMaster can make plays from deep in the shortstop hole.",
      "His offensive role emphasizes advancing runners and turning over the lineup.",
      "LeMaster's debut home run remains one of the most unusual first-at-bat moments in major-league history.",
      "Pairing him with Manny Trillo gives San Francisco an experienced defensive middle infield.",
      "LeMaster's steady presence allows the Giants to reserve Brad Wellman for late-inning flexibility.",
    ],
  },
  "Dusty Baker": {
    lines: [
      "Dusty Baker's full name is Johnnie B. Baker Jr.",
      "Baker was born in Riverside, California.",
      "Dusty Baker attended Del Campo High School near Sacramento.",
      "The Atlanta Braves selected Baker in the 26th round of the 1967 amateur draft.",
      "Baker made his major-league debut with Atlanta during 1968.",
      "Dusty Baker became a regular Braves outfielder during the early 1970s.",
      "Baker was a teammate of Hank Aaron.",
      "Dusty Baker was on base when Aaron hit his 715th career home run in 1974.",
      "The Los Angeles Dodgers acquired Baker before the 1976 season.",
      "Dusty Baker became a key member of the Dodgers' outfield.",
      "Baker was selected to the National League All-Star team in 1981 and 1982.",
      "Dusty Baker won a Gold Glove Award in 1981.",
      "Baker helped Los Angeles win the 1981 World Series.",
      "Dusty Baker received a Silver Slugger Award during his Dodgers career.",
      "Baker and Glenn Burke are associated with an early version of the celebratory high five.",
      "Dusty Baker remained a member of the Dodgers through the end of 1983.",
      "He had not yet appeared for San Francisco.",
      "Baker can play either corner-outfield position.",
      "Dusty Baker provides right-handed power from the bench.",
      "Baker is experienced in pennant races and postseason games.",
      "His calm confidence is useful in late-inning pinch-hitting situations.",
      "Dusty Baker is capable of remaining in the game as a reliable defensive outfielder.",
      "He gives San Francisco a veteran alternative behind Leonard, Clark and Davis.",
      "Baker's combination of defense, power and championship experience makes him far more valuable than an ordinary reserve.",
    ],
  },
  "Dan Gladden": {
    lines: [
      "Dan Gladden's full name is Clinton Daniel Gladden III.",
      "Gladden was born in San Jose, California.",
      "Dan Gladden attended Westmont High School in Campbell, California.",
      "Gladden later attended De Anza College.",
      "Dan Gladden was not selected during the amateur draft.",
      "San Francisco signed Gladden as a free agent.",
      "Gladden developed into a speedy outfielder in the Giants' minor-league system.",
      "Dan Gladden played for the Phoenix Giants at Triple-A.",
      "Gladden's game is built around speed, hustle and aggressive baserunning.",
      "Dan Gladden received a brief major-league opportunity during 1983.",
      "Gladden had only a handful of major-league games entering 1984.",
      "Opposing pitchers and catchers therefore possess little firsthand experience against him.",
      "Dan Gladden can play all three outfield positions.",
      "Gladden is especially valuable as a pinch-runner.",
      "Dan Gladden can score from first base on a well-placed double.",
      "His speed also makes him a useful late-inning defensive replacement.",
      "Gladden's aggressive style can force fielders to rush otherwise routine plays.",
      "Dan Gladden does not need a home run to create an important run.",
      "A walk, stolen base and shallow single can be enough for him to score.",
      "Gladden provides a different type of bench weapon from the more powerful Dusty Baker.",
      "Entering 1984, Gladden is trying to turn minor-league success into a permanent major-league role.",
    ],
  },
  "Brad Wellman": {
    lines: [
      "Brad Wellman's full name is Bradley Alan Wellman.",
      "Wellman was born in Lodi, California.",
      "Brad Wellman attended Castro Valley High School.",
      "Wellman played college baseball at Chabot College.",
      "San Francisco selected Brad Wellman in the first round of the January 1978 secondary draft.",
      "Wellman developed as a middle infielder.",
      "Brad Wellman made his major-league debut during 1982.",
      "Wellman can play second base, shortstop and third base.",
      "Brad Wellman appeared in a reserve role during the 1983 season.",
      "Wellman's versatility allows him to replace any member of the starting infield.",
      "Brad Wellman bats right-handed.",
      "Wellman's offensive approach emphasizes contact rather than home-run power.",
      "Brad Wellman can be used to bunt or move a runner.",
      "His range makes him useful as a late-inning defensive replacement.",
      "Wellman can enter for Al Oliver if the Giants rearrange their infield late in a game.",
      "Brad Wellman can also spell Trillo or LeMaster.",
      "His willingness to accept irregular playing time is important for a utility infielder.",
      "Wellman gives San Francisco a younger defensive option behind several established veterans.",
      "He is useful when a game requires several substitutions because he does not limit the manager to one position.",
      "Wellman's role is unlikely to produce attention, but it can prevent the defense from weakening after a pinch-hitting move.",
    ],
  },
  "Chris Brown": {
    lines: [
      "Chris Brown's full name is John Christopher Brown.",
      "Brown was born in Jackson, Mississippi.",
      "Chris Brown attended Crenshaw High School in Los Angeles.",
      "Brown played on a talented Crenshaw baseball program.",
      "San Francisco selected Chris Brown in the second round of the 1979 amateur draft.",
      "Brown developed as a third baseman.",
      "Chris Brown possesses a quick right-handed bat.",
      "Brown also has enough arm strength to handle third base.",
      "Chris Brown spent the 1983 season in the Giants' minor-league organization.",
      "Brown had not yet appeared in a major-league game by the end of 1983.",
      "Opposing National League pitchers therefore possess no major-league scouting history against him.",
      "Chris Brown's minor-league performance made him one of San Francisco's more promising infield prospects.",
      "Brown is capable of hitting for average and developing power.",
      "Chris Brown has enough athleticism to make difficult plays moving toward the foul line.",
      "Brown's youth gives him more raw upside than most reserve infielders.",
      "His inexperience also means that pitchers will test his discipline with breaking balls outside the strike zone.",
      "Chris Brown can replace Joel Youngblood at third base.",
      "Youngblood's versatility allows the Giants to place Brown at third without removing Youngblood's bat from consideration.",
      "Brown enters 1984 attempting to prove that his minor-league success can translate immediately.",
      "His inclusion gives the roster a high-upside prospect behind several established veterans.",
    ],
  },
  "Dan Driessen": {
    lines: [
      "Dan Driessen's full name is Daniel Driessen.",
      "Driessen was born in Hilton Head Island, South Carolina.",
      "Dan Driessen was not selected during the regular amateur draft.",
      "Cincinnati signed Driessen as an amateur free agent in 1969.",
      "Driessen made his major-league debut with the Reds during 1973.",
      "Dan Driessen originally played third base and the outfield.",
      "Driessen later became Cincinnati's regular first baseman.",
      "Dan Driessen was a member of the Reds' 1975 and 1976 World Series championship clubs.",
      "The designated hitter rule was used throughout the 1976 World Series.",
      "Dan Driessen became the first National League player to serve regularly as a designated hitter in a World Series.",
      "Driessen hit a home run during that Series.",
      "Dan Driessen combines left-handed power with useful speed.",
      "Driessen stole 31 bases during the 1977 season.",
      "Dan Driessen hit 17 home runs during the 1983 season.",
      "Driessen remained a member of Cincinnati through the end of 1983.",
      "He had not yet appeared for San Francisco.",
      "Driessen can replace Al Oliver at first base.",
      "Dan Driessen's left-handed bat is useful against right-handed relief pitching.",
      "Driessen has enough experience to handle an important pinch-hitting assignment.",
      "His World Series background gives him experience in pressure situations.",
      "Driessen is more athletic than many conventional reserve first basemen.",
      "He can remain in the game without costing the Giants mobility on the bases.",
      "Driessen and Dusty Baker give this bench two experienced veterans from successful National League clubs.",
    ],
  },
  "Mark Davis": {
    lines: [
      "Mark Davis' full name is Mark William Davis.",
      "Davis was born in Livermore, California.",
      "Mark Davis attended Granada High School in Livermore.",
      "Philadelphia selected Davis with the first overall pick of the 1979 amateur draft.",
      "Davis entered professional baseball as one of the most highly regarded young pitchers in the country.",
      "Mark Davis made his major-league debut with Philadelphia during 1980.",
      "Davis struggled to secure a permanent role with the Phillies.",
      "San Francisco acquired Mark Davis before the 1983 season.",
      "Davis is a left-handed pitcher.",
      "Mark Davis worked as both a starter and reliever during 1983.",
      "Davis possesses a lively fastball.",
      "Mark Davis also throws a hard breaking ball.",
      "His stuff can produce strikeouts when his control is sharp.",
      "Davis' challenge has been maintaining consistent command.",
      "Mark Davis is still young enough to develop into a top-of-the-rotation starter.",
      "His first-overall draft status created substantial expectations.",
      "Davis can be difficult on left-handed hitters because of his arm angle.",
      "Mark Davis can also attack right-handed hitters inside before moving the breaking ball away.",
      "Starting him first on your roster emphasizes his raw ability rather than his still-developing major-league record.",
      "Davis provides the rotation with its only left-handed starter.",
      "His previous relief work allows the Giants to remove him early without placing him in an unfamiliar role later.",
      "Entering 1984, Davis remains a talented pitcher seeking consistency.",
    ],
  },
  "Mike Krukow": {
    lines: [
      "Mike Krukow's full name is Michael Edward Krukow.",
      "Krukow was born in Long Beach, California.",
      "Mike Krukow attended San Gabriel High School.",
      "Krukow played college baseball at Cal Poly San Luis Obispo.",
      "The Chicago Cubs selected Mike Krukow in the eighth round of the 1973 amateur draft.",
      "Krukow made his major-league debut with Chicago during 1976.",
      "Mike Krukow became a regular member of the Cubs' rotation.",
      "Krukow won 10 or more games in several seasons for Chicago.",
      "Philadelphia acquired Mike Krukow before the 1982 season.",
      "Krukow helped the Phillies contend in the National League East.",
      "San Francisco acquired Mike Krukow before the 1983 season.",
      "Krukow immediately became one of the Giants' regular starting pitchers.",
      "Mike Krukow is a right-handed pitcher.",
      "Krukow relies upon command, movement and changing speeds.",
      "Mike Krukow can elevate his fastball when seeking a strikeout.",
      "His breaking pitches are most effective when he stays ahead in the count.",
      "Krukow is capable of pitching deep into games.",
      "Mike Krukow's experience at Wrigley Field and Veterans Stadium prepared him for difficult pitching environments.",
      "Candlestick Park can reward pitchers who keep the ball in the air.",
      "Krukow is an athletic pitcher who fields his position well.",
      "Mike Krukow also takes pride in contributing at the plate.",
      "His veteran experience provides balance behind the younger Mark Davis.",
      "Krukow is less likely than an inexperienced pitcher to become rattled by an early defensive mistake.",
      "He gives San Francisco a durable, established right-handed starter.",
    ],
  },
  "Bill Laskey": {
    lines: [
      "Bill Laskey's full name is William Alan Laskey.",
      "Laskey was born in Toledo, Ohio.",
      "Bill Laskey attended Woodward High School in Toledo.",
      "Kansas City selected Laskey in the second round of the 1975 amateur draft.",
      "Laskey developed in the Royals' minor-league organization.",
      "San Francisco later acquired Bill Laskey.",
      "Laskey made his major-league debut during 1982.",
      "Bill Laskey immediately entered the Giants' starting rotation.",
      "Laskey won 13 games as a rookie.",
      "Bill Laskey made more than 30 starts during the 1982 season.",
      "Laskey remained one of San Francisco's busiest starters during 1983.",
      "Bill Laskey again worked a substantial number of innings.",
      "Laskey is a right-handed pitcher.",
      "Bill Laskey depends more upon location and changing speeds than overpowering velocity.",
      "Laskey can induce ground balls by keeping the ball near the knees.",
      "Bill Laskey's willingness to challenge hitters helps him avoid unnecessary walks.",
      "His approach can also leave him vulnerable when pitches remain over the center of the plate.",
      "Laskey has demonstrated the durability required of a regular major-league starter.",
      "Bill Laskey can work quickly when his defense is making routine plays behind him.",
      "His pace prevents hitters from becoming comfortable between pitches.",
      "Laskey gives San Francisco a dependable innings option in the middle of the rotation.",
      "Entering 1984, he is attempting to build upon two full seasons of major-league experience.",
    ],
  },
  "Jeff Robinson": {
    lines: [
      "Jeff Robinson's full name is Jeffrey Daniel Robinson.",
      "Robinson was born in Santa Ana, California.",
      "Jeff Robinson attended Foothill High School in California.",
      "Robinson played college baseball at the University of California, Santa Barbara.",
      "San Francisco selected Jeff Robinson in the second round of the 1983 amateur draft.",
      "Robinson is a right-handed pitcher.",
      "Jeff Robinson possesses a strong fastball.",
      "Robinson entered professional baseball with a reputation as a power arm.",
      "Jeff Robinson pitched in the Giants' minor-league system during 1983.",
      "Robinson had not yet appeared in a major-league game by the end of the season.",
      "National League hitters therefore possess no firsthand major-league experience against him.",
      "Jeff Robinson can use his unfamiliarity to his advantage during an exhibition start.",
      "Robinson's fastball allows him to challenge hitters inside.",
      "Jeff Robinson must establish his breaking ball to prevent hitters from sitting on velocity.",
      "His youth makes him the least experienced member of the rotation.",
      "Robinson's raw stuff may also give him one of its highest ceilings.",
      "Jeff Robinson will need help from Bob Brenly when adjusting to major-league hitters.",
      "Brenly's pitch selection can prevent Robinson from becoming too predictable.",
      "Robinson enters 1984 attempting to move directly from prospect status into a major-league role.",
      "A successful start from Robinson would give San Francisco a badly needed young power pitcher.",
      "His presence makes this rotation a mixture of established veterans and developing arms.",
    ],
  },
  "Greg Minton": {
    lines: [
      "Greg Minton's full name is Gregory Brian Minton.",
      "Minton was born in Lubbock, Texas.",
      "Greg Minton attended Texas A&I University.",
      "Kansas City selected Minton in the third round of the 1970 amateur draft.",
      "Minton made his major-league debut with San Francisco during 1975.",
      "Greg Minton initially worked as both a starter and reliever.",
      "Minton eventually developed into the Giants' primary closer.",
      "Greg Minton is commonly known by the nickname \"Moon Man.\"",
      "Minton relies heavily upon a sinking fastball.",
      "His sinker produces large numbers of ground balls.",
      "Greg Minton also throws a slider.",
      "Minton's delivery and movement make it difficult for hitters to lift the ball.",
      "Greg Minton once went more than 260 consecutive innings without allowing a home run.",
      "That stretch established a modern major-league record.",
      "Minton recorded 30 saves during the 1982 season.",
      "Greg Minton was selected to the 1982 National League All-Star team.",
      "Minton remained San Francisco's principal late-inning reliever during 1983.",
      "Greg Minton can work more than one inning.",
      "Minton is not restricted to entering only at the beginning of the ninth.",
      "Greg Minton can inherit runners and attempt to induce a double-play ground ball.",
      "His sinker is particularly effective when a force play is available.",
      "Minton's lack of home runs allowed is especially valuable in close games.",
      "Right-handed hitters frequently drive his sinker into the ground near shortstop or third base.",
      "Greg Minton's slider provides a swing-and-miss option when he needs a strikeout.",
      "A successful Minton appearance should produce grounders, broken bats and very few deep fly balls.",
    ],
  },
  "Gary Lavelle": {
    lines: [
      "Gary Lavelle's full name is Gary Robert Lavelle.",
      "Lavelle was born in Scranton, Pennsylvania.",
      "Gary Lavelle attended Liberty High School in Bethlehem, Pennsylvania.",
      "San Francisco selected Lavelle in the 20th round of the 1967 amateur draft.",
      "Lavelle spent several years developing in the Giants' minor-league system.",
      "Gary Lavelle made his major-league debut during 1974.",
      "Lavelle became one of the National League's most effective left-handed relievers.",
      "Gary Lavelle was selected to the National League All-Star team in 1977.",
      "Lavelle received another All-Star selection in 1983.",
      "Gary Lavelle has frequently shared late-inning work with Greg Minton.",
      "Lavelle throws a fastball and sharp breaking ball.",
      "Gary Lavelle's breaking pitch is especially difficult for left-handed hitters.",
      "Lavelle can work several innings in the relief style common to the period.",
      "Gary Lavelle is capable of recording saves when Minton is unavailable.",
      "Lavelle can also enter during the seventh inning to face the heart of the opposing order.",
      "Gary Lavelle's control allows him to pitch around dangerous hitters when necessary.",
      "His experience gives the Giants a reliable alternative to the younger relievers.",
      "Lavelle's left-handed delivery prevents opponents from stacking their lineup solely against Minton.",
      "Gary Lavelle can neutralize a dangerous left-handed pinch-hitter late in the game.",
      "His All-Star selection confirms that he remained highly regarded entering 1984.",
      "Lavelle and Minton form one of the most experienced late-inning combinations on this roster.",
    ],
  },
  "Scott Garrelts": {
    lines: [
      "Scott Garrelts' full name is Scott William Garrelts.",
      "Garrelts was born in Urbana, Illinois.",
      "Scott Garrelts attended Buckley-Loda High School.",
      "San Francisco selected Garrelts in the first round of the January 1979 secondary draft.",
      "Garrelts developed as a hard-throwing right-handed pitcher.",
      "Scott Garrelts made his major-league debut during 1982.",
      "Garrelts worked primarily from the bullpen during his early major-league appearances.",
      "Scott Garrelts possesses an explosive fastball.",
      "His velocity gives San Francisco a different look from the sinking deliveries of Minton.",
      "Scott Garrelts also uses a breaking ball.",
      "Garrelts' greatest challenge is controlling his power repertoire.",
      "Scott Garrelts can accumulate strikeouts quickly when he is ahead in the count.",
      "Walks can create difficulty when he loses his release point.",
      "Garrelts can pitch more than one inning.",
      "Scott Garrelts is capable of entering during the middle innings and remaining through the eighth.",
      "His fastball is especially useful when the Giants need a strikeout with runners on base.",
      "Garrelts remains young enough to develop either as a starter or late-inning reliever.",
      "Scott Garrelts' role on this roster emphasizes his immediate value from the bullpen.",
      "He can protect Minton and Lavelle from excessive use.",
      "Garrelts gives San Francisco a potential future closer behind two established veterans.",
      "His unfamiliarity and velocity make him particularly dangerous during a short exhibition appearance.",
    ],
  },
  "Frank Williams": {
    lines: [
      "Frank Williams' full name is Frank Lee Williams.",
      "Williams was born in Seattle, Washington.",
      "Frank Williams is a right-handed pitcher.",
      "San Francisco selected Williams during the amateur draft process.",
      "Williams developed in the Giants' minor-league organization.",
      "Frank Williams worked primarily as a relief pitcher.",
      "Williams spent the 1983 season in the minor leagues.",
      "Frank Williams had not yet appeared in a major-league game by the end of 1983.",
      "Opposing National League hitters therefore possess no firsthand scouting experience against him.",
      "Williams can benefit from hitters being unfamiliar with his release point.",
      "Frank Williams throws with good velocity.",
      "Williams is capable of producing strikeouts when he locates his fastball.",
      "Frank Williams must avoid falling behind in the count.",
      "His breaking ball becomes more effective when hitters must protect against the fastball.",
      "Williams gives the Giants a younger right-handed relief option.",
      "Frank Williams can be used before the established Minton-Lavelle combination.",
      "Williams' minor-league relief background prepares him to enter with runners already on base.",
      "His lack of major-league experience makes him more unpredictable than the veteran relievers.",
      "Williams enters 1984 attempting to earn a permanent bullpen role.",
      "A strong early performance could move him rapidly into more important innings.",
    ],
  },
  "Bob Lacey": {
    lines: [
      "Bob Lacey's full name is Robert Joseph Lacey Jr.",
      "Lacey was born in Newark, New Jersey.",
      "Bob Lacey attended East Los Angeles College.",
      "Oakland selected Lacey in the tenth round of the 1972 amateur draft.",
      "Lacey made his major-league debut with the Athletics during 1977.",
      "Bob Lacey is a left-handed pitcher.",
      "Lacey became an effective relief specialist for Oakland.",
      "Bob Lacey appeared in 74 games during the 1978 season.",
      "Lacey recorded a 3.01 ERA that year.",
      "Bob Lacey has experience working both short and extended relief assignments.",
      "Lacey later pitched for Cleveland and Texas.",
      "Bob Lacey joined San Francisco during the early 1980s.",
      "Lacey provides the bullpen with a second left-handed option behind Gary Lavelle.",
      "Bob Lacey can be used against a single difficult left-handed hitter.",
      "He can also remain in the game for several innings.",
      "Lacey relies upon movement and changing speeds.",
      "Bob Lacey is more likely to induce contact than overpower hitters.",
      "His experience allows him to enter with runners already aboard.",
      "Lacey's presence prevents the Giants from overusing Lavelle in every left-handed matchup.",
      "Bob Lacey can work during the middle innings before Garrelts, Lavelle and Minton.",
      "His veteran background gives San Francisco a stabilizing option when a young starter leaves early.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive — base hit.\"",
    "\"Long drive to right field — way back — gone. Home run!\"",
    "\"Ground ball to short — over to first — in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub has some real talent — Clark, Oliver, Davis — the Giants can play with anybody.\"",
    "\"San Francisco baseball is alive and well — the fans here at Candlestick love their Giants.\"",
    "\"This team has power and experience — Jack Clark is one of the most dangerous hitters in the league.\"",
    "\"Candlestick Park is home — and the Giants are ready to make some noise in the NL West.\"",
    "\"Jack Clark is the most feared power hitter in the National League — bar none.\"",
    "\"Al Oliver won a batting title in 1982 — .331! That's extraordinary.\"",
    "\"Manny Trillo has three Gold Gloves and a World Series MVP — he's a winner.\"",
    "\"There's talent everywhere you look in this lineup — the Giants can hurt you.\"",
    "\"This club is building something — San Francisco believes it can contend in the West.\"",
    "\"The fans in San Francisco have been waiting for a winner — they love their Giants.\"",
    "\"There's a buzz around the Giants this year — people can feel something building.\"",
    "\"From Jack the Ripper to Scoop to Moon Man — the Giants have characters at every position.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Jack Clark is the most dangerous power hitter in the National League — 27 homers, 103 RBI in '82.\"",
    "\"Al Oliver led the league in batting in 1982 — .331 average. Scoop can flat-out hit.\"",
    "\"Manny Trillo was the MVP of the 1980 NLCS — .381 batting average. He's a champion.\"",
    "\"Chili Davis is one of the most gifted young players in baseball — switch-hitter with power and speed.\"",
    "\"Greg Minton went 260 innings without giving up a home run — that's an incredible record.\"",
    "\"Dusty Baker was on base when Hank Aaron hit 715 — he's been part of baseball history.\"",
    "\"Bob Brenly provides power from the catcher position — that's invaluable.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Candlestick Park.\"",
    "\"The lights are on at the Stick — Giants baseball tonight.\"",
    "Candlestick Park — home of the Giants since 1960.",
    "\"The wind is howling off the bay tonight — this ballpark can be brutal.\"",
    "\"The stands are filling up nicely — San Francisco loves its Giants.\"",
    "\"You can feel the chill in the air — Candlestick is famous for its cold summer nights.\"",
    "\"The fog is rolling in off San Francisco Bay — classic conditions at the Stick.\"",
    "\"The wind is playing tricks with every fly ball — outfielders have to be alert.\"",
    "\"The crowd is bundled up tonight — it's cold out there by the bay.\"",
    "\"The lights are cutting through the fog — a classic San Francisco baseball night.\"",
    "\"Candlestick Park has seen some great moments — this is a historic ballpark.\"",
    "\"The wind is knocking down every deep drive — nothing leaves here easily.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here at Candlestick is into this ballgame.\"",
    "\"Giants fans are making some noise tonight.\"",
    "\"The fans in San Francisco are fired up tonight — they love their Giants.\"",
    "\"Candlestick Park is rocking tonight.\"",
    "\"San Francisco fans are among the most loyal in baseball — they've been through a lot.\"",
    "\"The crowd is on its feet — they can feel something building here.\"",
    "\"A great turnout at the Stick tonight.\"",
    "\"These fans love their Giants — from Jack the Ripper to Scoop to Moon Man.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Candlestick Park, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball at the Stick.\"",
    "\"From all of us here in San Francisco, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story — that's the beauty of this sport.\"",
    "\"Baseball by the bay — there's nothing better.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone — into the wind at Candlestick!\"",
    "\"Jack the Ripper strikes again!\"",
    "\"The Giants are making their move here at the Stick.\"",
    "\"And San Francisco wins it — what a finish by the bay!\"",
    "\"You won't see many better than that one.\"",
    "\"Holy cow, what a ballgame!\"",
  ]},
};