// Cleveland Indians Broadcast — 1984
// Radio: Herb Score & Nev Chandler (WWWE) / TV: Bruce Drennen
// Cleveland Municipal Stadium — home of the Indians
// All stats cutoff: end of 1983 season

export function pickIndiansLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickIndiansPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Brett Butler": {
    lines: [
      "Brett Butler's full name is Brett Morgan Butler.",
      "Brett Butler played college baseball at Southeastern Oklahoma State University.",
      "Brett Butler was selected by Atlanta in the 23rd round of the 1979 amateur draft.",
      "Brett Butler reached the major leagues with the Braves in August 1981.",
      "Brett Butler collected a hit and drove in a run during his major-league debut.",
      "Brett Butler became Atlanta's regular left fielder during the 1982 season.",
      "Brett Butler developed into an effective leadoff hitter through speed, contact and patience.",
      "Brett Butler played 151 games for Atlanta during the 1983 season.",
      "Brett Butler batted .281 with a .344 on-base percentage in 1983.",
      "Brett Butler collected 154 hits and scored 84 runs during the 1983 season.",
      "Brett Butler recorded 21 doubles and 13 triples in 1983.",
      "Brett Butler's 13 triples demonstrated how quickly he could move around the bases.",
      "Brett Butler hit five home runs and drove in 37 runs during the 1983 season.",
      "Brett Butler stole 39 bases in 1983.",
      "Brett Butler drew 54 walks during the 1983 season.",
      "Brett Butler was traded to Cleveland after the 1983 season as part of the Len Barker transaction.",
      "Brett Butler arrived in Cleveland with Brook Jacoby and pitcher Rick Behenna.",
      "Brett Butler can place a bunt along either line and force the defense to make a quick play.",
      "Brett Butler's speed allows him to cover considerable ground in center field.",
      "Brett Butler is capable of turning a single into a scoring opportunity before the next pitch.",
      "Brett Butler gives Cleveland a natural leadoff hitter who can pressure the defense immediately.",
      "Brett Butler is more interested in reaching base than attempting to hit for power.",
      "Brett Butler can disrupt a pitcher simply by taking a large lead from first base.",
    ],
  },
  "Mike Hargrove": {
    lines: [
      "Mike Hargrove's full name is Dudley Michael Hargrove.",
      "Mike Hargrove was born and raised in Perryton, Texas.",
      "Mike Hargrove was selected by the Texas Rangers in the 25th round of the 1972 draft.",
      "Mike Hargrove moved directly from Class A baseball to the major leagues in 1974.",
      "Mike Hargrove won the 1974 American League Rookie of the Year Award.",
      "Mike Hargrove batted .323 with a .395 on-base percentage during his rookie season.",
      "Mike Hargrove was selected to the American League All-Star team in 1975.",
      "Mike Hargrove became known as \"The Human Rain Delay\" because of his deliberate routine between pitches.",
      "Mike Hargrove adjusts his gloves, sleeves, helmet and uniform before settling back into the box.",
      "Mike Hargrove's lengthy routine can disrupt a pitcher's rhythm.",
      "Mike Hargrove joined Cleveland during the 1979 season.",
      "Mike Hargrove revitalized his career after becoming Cleveland's regular first baseman.",
      "Mike Hargrove batted .304 with a .415 on-base percentage in 1980.",
      "Mike Hargrove collected 179 hits and drew 111 walks during the 1980 season.",
      "Mike Hargrove appeared in 134 games for Cleveland in 1983.",
      "Mike Hargrove batted .286 with a .388 on-base percentage in 1983.",
      "Mike Hargrove collected 134 hits, including 21 doubles and four triples, in 1983.",
      "Mike Hargrove drove in 57 runs and scored 57 times during the 1983 season.",
      "Mike Hargrove drew 78 walks while striking out only 40 times in 1983.",
      "Mike Hargrove is one of the most patient hitters in the Cleveland lineup.",
      "Mike Hargrove rarely allows a pitcher to hurry through an at-bat.",
      "Mike Hargrove is particularly valuable when Cleveland needs a runner on base.",
      "Mike Hargrove is comfortable hitting behind a speedy leadoff man.",
      "Mike Hargrove's knowledge of the strike zone makes him difficult to retire on marginal pitches.",
    ],
  },
  "Julio Franco": {
    lines: [
      "Julio Franco's full name is Julio Cesar Franco.",
      "Julio Franco was born in Hato Mayor del Rey in the Dominican Republic.",
      "Julio Franco worked in a factory after high school while pursuing an opportunity to play baseball.",
      "Julio Franco signed with Philadelphia for a reported four-thousand-dollar bonus.",
      "Julio Franco began his American professional career in Butte, Montana, in 1978.",
      "Julio Franco batted .305 during his first professional season.",
      "Julio Franco won league Most Valuable Player honors in the Northwest League.",
      "Julio Franco later batted .321 with 99 RBI while helping Peninsula win a Carolina League championship.",
      "Julio Franco reached the major leagues with Philadelphia in 1982.",
      "Julio Franco appeared in 16 games for the Phillies before being traded to Cleveland.",
      "Julio Franco was the key young player Cleveland demanded in the five-player trade for Von Hayes.",
      "Julio Franco became Cleveland's regular shortstop during his first full major-league season.",
      "Julio Franco played 149 games for Cleveland in 1983.",
      "Julio Franco batted .273 with 153 hits during the 1983 season.",
      "Julio Franco collected 24 doubles and eight triples in 1983.",
      "Julio Franco hit eight home runs and drove in 80 runs during the 1983 season.",
      "Julio Franco scored 68 runs in 1983.",
      "Julio Franco stole 32 bases during his first full major-league season.",
      "Julio Franco finished second in the 1983 American League Rookie of the Year voting.",
      "Julio Franco uses an unusual batting stance with the bat held high over his head.",
      "Julio Franco's long arms allow him to reach pitches on the outside part of the plate.",
      "Julio Franco has enough range to reach balls deep in the shortstop hole.",
      "Julio Franco's range can occasionally lead him to attempt extremely difficult throws.",
      "Julio Franco combines the offensive skills of an outfielder with the responsibilities of a shortstop.",
      "Julio Franco gives Cleveland power, speed and run production from the middle infield.",
    ],
  },
  "Andre Thornton": {
    lines: [
      "Andre Thornton is commonly known by the nickname \"Thunder.\"",
      "Andre Thornton was born in Tuskegee, Alabama.",
      "Andre Thornton attended a Philadelphia Phillies tryout at Connie Mack Stadium in 1967.",
      "Andre Thornton's professional opportunity nearly disappeared when a scout had difficulty locating him after the tryout.",
      "Andre Thornton was eventually found playing pool and was signed by Philadelphia.",
      "Andre Thornton served in the National Guard and trained at Fort Dix.",
      "Andre Thornton began his major-league career with the Chicago Cubs in 1973.",
      "Andre Thornton was traded to Cleveland during the 1976 season.",
      "Andre Thornton developed into the most feared power hitter in the Cleveland lineup.",
      "Andre Thornton hit 28 home runs and drove in 70 runs in 1977.",
      "Andre Thornton endured a devastating personal tragedy when his wife and young daughter were killed in a 1977 automobile accident.",
      "Andre Thornton's young son survived the accident.",
      "Andre Thornton later wrote a book titled \"Triumph Born of Tragedy.\"",
      "Andre Thornton hit 33 home runs and drove in 97 runs during the 1978 season.",
      "Andre Thornton also scored 97 runs and drew 93 walks in 1978.",
      "Andre Thornton missed the 1980 season after serious knee problems required surgery.",
      "Andre Thornton suffered another setback when a pitched ball broke his hand in 1981.",
      "Andre Thornton returned to full strength during the 1982 season.",
      "Andre Thornton hit 32 home runs and drove in 116 runs in 1982.",
      "Andre Thornton drew 109 walks during the 1982 season.",
      "Andre Thornton was selected to the American League All-Star team in 1982.",
      "Andre Thornton was named The Sporting News American League Comeback Player of the Year for 1982.",
      "Andre Thornton appeared in 141 games during the 1983 season.",
      "Andre Thornton batted .281 with a .383 on-base percentage in 1983.",
      "Andre Thornton collected 143 hits and 27 doubles during the 1983 season.",
      "Andre Thornton hit 17 home runs and drove in 77 runs in 1983.",
      "Andre Thornton scored 78 runs and drew 87 walks during the 1983 season.",
      "Andre Thornton is willing to take a walk when pitchers refuse to challenge him.",
      "Andre Thornton remains dangerous even when he is used primarily as the designated hitter.",
      "Andre Thornton has enough power to change the game with one mistake over the plate.",
      "Andre Thornton's strength is matched by one of the most remarkable personal comeback stories in baseball.",
    ],
  },
  "Joe Carter": {
    lines: [
      "Joe Carter's full name is Joseph Chris Carter.",
      "Joe Carter grew up in Oklahoma City, Oklahoma.",
      "Joe Carter attended Millwood High School before playing at Wichita State University.",
      "Joe Carter became one of the first major stars of Wichita State's revived baseball program.",
      "Joe Carter earned All-America recognition in each of his three college seasons.",
      "Joe Carter was named national college Player of the Year in 1981 by The Sporting News and All-America Baseball News.",
      "Joe Carter was selected by the Chicago Cubs with the second overall pick in the 1981 draft.",
      "Joe Carter began his professional career with the Midland Cubs.",
      "Joe Carter batted .319 with 25 home runs and 98 RBI for Midland in 1982.",
      "Joe Carter reached the major leagues with Chicago on July 30, 1983.",
      "Joe Carter appeared in 23 games during his first major-league trial.",
      "Joe Carter collected nine hits, one double and one triple in 51 at-bats in 1983.",
      "Joe Carter scored six runs and drove in one during his brief 1983 appearance.",
      "Joe Carter entered 1984 as one of the better young power prospects in baseball.",
      "Joe Carter was acquired by Cleveland from Chicago during the 1984 season.",
      "Joe Carter came to Cleveland in the trade that sent Rick Sutcliffe to the Cubs.",
      "Joe Carter's combination of strength and speed gives him several ways to help an offense.",
      "Joe Carter can play either corner-outfield position and has experience in center field.",
      "Joe Carter generates considerable power with a compact right-handed swing.",
      "Joe Carter is aggressive and capable of driving the first hittable pitch.",
      "Joe Carter is still only 24 years old during the 1984 season.",
      "Joe Carter joins a young Cleveland nucleus that includes Brett Butler, Julio Franco and Brook Jacoby.",
    ],
  },
  "Tony Bernazard": {
    lines: [
      "Tony Bernazard was born in Caguas, Puerto Rico.",
      "Tony Bernazard is a switch-hitting middle infielder.",
      "Tony Bernazard began his major-league career with the Montreal Expos.",
      "Tony Bernazard was traded from Montreal to the Chicago White Sox before the 1981 season.",
      "Tony Bernazard developed into Chicago's regular second baseman.",
      "Tony Bernazard appeared in 137 games during the 1982 season.",
      "Tony Bernazard scored 90 runs and collected 138 hits in 1982.",
      "Tony Bernazard recorded 25 doubles, nine triples and 11 home runs during the 1982 season.",
      "Tony Bernazard drove in 56 runs and drew 67 walks in 1982.",
      "Tony Bernazard split the 1983 season between Chicago and Seattle.",
      "Tony Bernazard was traded to Seattle in the deal that sent Julio Cruz to the White Sox.",
      "Tony Bernazard played 139 games during the 1983 season.",
      "Tony Bernazard batted .265 with 141 hits in 1983.",
      "Tony Bernazard collected 34 doubles, three triples and eight home runs during the 1983 season.",
      "Tony Bernazard scored 65 runs and drove in 56 in 1983.",
      "Tony Bernazard stole 23 bases during the 1983 season.",
      "Tony Bernazard was traded from Seattle to Cleveland after the 1983 season.",
      "Tony Bernazard came to Cleveland in the transaction involving Gorman Thomas and Jack Perconte.",
      "Tony Bernazard gives Cleveland another switch-hitter with speed near the top of the lineup.",
      "Tony Bernazard is capable of hitting for more power than the average second baseman.",
      "Tony Bernazard and Julio Franco form an athletic middle-infield combination.",
      "Tony Bernazard can bunt, steal a base or drive a ball into the gap.",
    ],
  },
  "Brook Jacoby": {
    lines: [
      "Brook Jacoby's full name is Brook Wallace Jacoby.",
      "Brook Jacoby was selected by Atlanta in the seventh round of the 1979 amateur draft.",
      "Brook Jacoby developed as a third baseman in the Braves farm system.",
      "Brook Jacoby received brief major-league trials with Atlanta in 1981 and 1983.",
      "Brook Jacoby appeared in only 15 major-league games before joining Cleveland.",
      "Brook Jacoby spent most of the 1983 season with Triple-A Richmond.",
      "Brook Jacoby played 133 games for Richmond during the 1983 season.",
      "Brook Jacoby batted .315 with a .387 on-base percentage for Richmond in 1983.",
      "Brook Jacoby slugged .542 during the 1983 minor-league season.",
      "Brook Jacoby collected 154 hits and scored 88 runs for Richmond.",
      "Brook Jacoby recorded 32 doubles and two triples in 1983.",
      "Brook Jacoby hit 25 home runs and drove in 100 runs for Richmond in 1983.",
      "Brook Jacoby's Triple-A performance established him as a major-league-ready prospect.",
      "Brook Jacoby was traded to Cleveland after the 1983 season.",
      "Brook Jacoby joined Brett Butler and Rick Behenna as the final portion of the Len Barker trade.",
      "Brook Jacoby gives Cleveland a young, natural third baseman.",
      "Brook Jacoby has the strength to drive the ball down either foul line.",
      "Brook Jacoby is capable of producing both doubles and home runs.",
      "Brook Jacoby enters 1984 seeking his first extended major-league opportunity.",
      "Brook Jacoby is another important part of Cleveland's effort to build around young players.",
    ],
  },
  "George Vukovich": {
    lines:! [
            "George Vukovich's full name is George Stephen Vukovich.",
      "George Vukovich is a left-handed-hitting outfielder from Chicago.",
      "George Vukovich was selected by Philadelphia in the fourth round of the 1977 amateur draft.",
      "George Vukovich reached the major leagues with the Phillies in 1980.",
      "George Vukovich served as a reserve outfielder and pinch-hitter in Philadelphia.",
      "George Vukovich was part of the large trade that sent Von Hayes from Cleveland to Philadelphia.",
      "George Vukovich came to Cleveland with Julio Franco, Manny Trillo, Jay Baller and Jerry Willard.",
      "George Vukovich became Cleveland's most frequently used right fielder during 1983.",
      "George Vukovich appeared in 124 games during the 1983 season.",
      "George Vukovich collected 77 hits in 312 at-bats in 1983.",
      "George Vukovich recorded 13 doubles, two triples and three home runs in 1983.",
      "George Vukovich drove in 44 runs during the 1983 season.",
      "George Vukovich is capable of filling either corner-outfield position.",
      "George Vukovich provides a left-handed bat against right-handed pitching.",
      "George Vukovich can also be used as a pinch-hitter late in a game.",
      "George Vukovich is most effective when he stays back and drives the ball toward left-center field.",
    ],
  },
  "Chris Bando": {
    lines: [
      "Chris Bando was born in Cleveland, Ohio.",
      "Chris Bando grew up in nearby Warrensville Heights.",
      "Chris Bando is the younger brother of longtime major-league third baseman Sal Bando.",
      "Chris Bando attended Solon High School in northeastern Ohio.",
      "Chris Bando played college baseball at Arizona State University.",
      "Chris Bando was selected by Cleveland in the second round of the 1978 amateur draft.",
      "Chris Bando is a switch-hitting catcher.",
      "Chris Bando reached the major leagues with Cleveland in 1981.",
      "Chris Bando appeared in 66 games during the 1982 season.",
      "Chris Bando hit three home runs and drove in 16 runs in 1982.",
      "Chris Bando appeared in 48 games for Cleveland during the 1983 season.",
      "Chris Bando batted .256 with a .336 on-base percentage in 1983.",
      "Chris Bando collected three doubles and four home runs during the 1983 season.",
      "Chris Bando drove in 15 runs in 121 at-bats in 1983.",
      "Chris Bando's four home runs gave him one home run for roughly every 30 at-bats.",
      "Chris Bando gives Cleveland a catcher capable of batting from either side of the plate.",
      "Chris Bando's familiarity with Cleveland pitchers is valuable even when his name is not in the lineup.",
      "Chris Bando has the unusual distinction of playing major-league baseball near the city where he was born.",
    ],
  },
  "Jerry Willard": {
    lines: [
      "Jerry Willard played college baseball at Oxnard College in California.",
      "Jerry Willard was selected by Philadelphia in the 19th round of the 1979 amateur draft.",
      "Jerry Willard developed as a catcher in the Phillies farm system.",
      "Jerry Willard played for the Central Oregon Phillies during the 1980 season.",
      "Jerry Willard batted .368 with a .481 on-base percentage for Central Oregon in 1980.",
      "Jerry Willard slugged .532 during that 1980 minor-league season.",
      "Jerry Willard collected 21 doubles, five home runs and 59 RBI in 65 games in 1980.",
      "Jerry Willard advanced steadily through the Philadelphia organization.",
      "Jerry Willard was included in the five-player package Cleveland received for Von Hayes.",
      "Jerry Willard has not yet appeared in a major-league regular-season game entering 1984.",
      "Jerry Willard enters 1984 competing for time behind the plate.",
      "Jerry Willard gives Cleveland a younger catching option alongside Chris Bando.",
      "Jerry Willard's minor-league record suggests a patient hitter with extra-base ability.",
    ],
  },
  "Pat Tabler": {
    lines: [
      "Pat Tabler's full name is Patrick Sean Tabler.",
      "Pat Tabler was born in Hamilton, Ohio.",
      "Pat Tabler was selected by the New York Yankees in the first round of the 1976 amateur draft.",
      "Pat Tabler developed as a shortstop and utility infielder in the Yankees organization.",
      "Pat Tabler reached the major leagues with the Chicago Cubs in 1981.",
      "Pat Tabler was traded twice before finding a regular opportunity in Cleveland.",
      "Pat Tabler can play first base, third base, second base and the corner outfield.",
      "Pat Tabler appeared in 124 games for Cleveland in 1983.",
      "Pat Tabler batted .291 with a .370 on-base percentage during the 1983 season.",
      "Pat Tabler collected 125 hits in 430 at-bats in 1983.",
      "Pat Tabler recorded 23 doubles and five triples during the 1983 season.",
      "Pat Tabler hit six home runs and drove in 65 runs in 1983.",
      "Pat Tabler scored 56 runs and drew 56 walks during the 1983 season.",
      "Pat Tabler produced 65 RBI despite hitting only six home runs.",
      "Pat Tabler led Cleveland in several offensive categories when compared with fellow young shortstop Cal Ripken during their minor-league season.",
      "Pat Tabler's versatility allows the manager to move him around the diamond.",
      "Pat Tabler is capable of starting regularly or supplying a difficult at-bat from the bench.",
      "Pat Tabler's contact skills make him useful with runners in scoring position.",
      "Pat Tabler gives Cleveland a reliable right-handed bat against left-handed pitching.",
    ],
  },
  "Carmen Castillo": {
    lines: [
      "Carmen Castillo's full name is Monte Carmelo Castillo, and he is frequently listed under the first name Carmen.",
      "Carmen Castillo was born in San Pedro de Macoris in the Dominican Republic.",
      "Carmen Castillo signed professionally as a young outfielder.",
      "Carmen Castillo stole 46 bases during the 1980 minor-league season.",
      "Carmen Castillo also hit 11 home runs and drove in 64 runs during that 1980 campaign.",
      "Carmen Castillo reached the major leagues with Cleveland in July 1982.",
      "Carmen Castillo appeared in 47 games during his 1982 rookie season.",
      "Carmen Castillo hit two home runs and drove in 11 runs in 1982.",
      "Carmen Castillo appeared in 23 games during the 1983 season.",
      "Carmen Castillo batted .278 with a .366 on-base percentage in 1983.",
      "Carmen Castillo slugged .472 during his limited 1983 action.",
      "Carmen Castillo collected two doubles, one triple and one home run in 36 at-bats in 1983.",
      "Carmen Castillo gives Cleveland a reserve outfielder with useful speed.",
      "Carmen Castillo is capable of playing either corner-outfield position.",
      "Carmen Castillo can be used as a pinch-runner, defensive substitute or occasional starter.",
    ],
  },
  "Mel Hall": {
    lines: [
      "Mel Hall's full name is Melvin Hall Jr.",
      "Mel Hall was selected by the Chicago Cubs in the second round of the 1978 amateur draft.",
      "Mel Hall reached the major leagues with Chicago in September 1981.",
      "Mel Hall spent the 1982 minor-league season with Triple-A Iowa.",
      "Mel Hall batted .329 with a .377 on-base percentage for Iowa in 1982.",
      "Mel Hall slugged .612 during the 1982 minor-league season.",
      "Mel Hall collected 165 hits and scored 116 runs for Iowa in 1982.",
      "Mel Hall recorded 34 doubles, six triples and 32 home runs during that season.",
      "Mel Hall drove in 125 runs for Iowa in 1982.",
      "Mel Hall established himself in Chicago's outfield during the 1983 season.",
      "Mel Hall batted .283 with 17 home runs in 1983.",
      "Mel Hall slugged .488 during his first full major-league season.",
      "Mel Hall entered 1984 as an established young left-handed power hitter.",
      "Mel Hall was acquired by Cleveland from Chicago during the 1984 season.",
      "Mel Hall joined Joe Carter in the trade that sent Rick Sutcliffe to the Cubs.",
      "Mel Hall can play all three outfield positions.",
      "Mel Hall's left-handed power provides balance in the Cleveland lineup.",
      "Mel Hall has already demonstrated that he can drive in runs in both the high minors and major leagues.",
    ],
  },
  "Otis Nixon": {
    lines: [
      "Otis Nixon's full name is Otis Junior Nixon Jr.",
      "Otis Nixon attended Louisburg College in North Carolina.",
      "Otis Nixon was drafted three different times before signing professionally.",
      "Otis Nixon was selected by the Yankees in the first round of the June 1979 secondary draft.",
      "Otis Nixon quickly became known as one of the fastest players in the minor leagues.",
      "Otis Nixon stole 67 bases for Greensboro during the 1980 season.",
      "Otis Nixon scored 124 runs and drew 113 walks for Greensboro in 1980.",
      "Otis Nixon stole 72 bases and drew 110 walks for Nashville in 1981.",
      "Otis Nixon stole 107 bases across two minor-league levels during the 1982 season.",
      "Otis Nixon stole 94 bases for Triple-A Columbus in 1983.",
      "Otis Nixon collected 162 hits and scored 129 runs for Columbus in 1983.",
      "Otis Nixon reached the major leagues with the Yankees in September 1983.",
      "Otis Nixon appeared in 13 games during his first major-league trial.",
      "Otis Nixon collected two hits, scored two runs and stole two bases in 1983.",
      "Otis Nixon was traded from New York to Cleveland before the 1984 season.",
      "Otis Nixon is most valuable as a pinch-runner, defensive replacement or leadoff option.",
      "Otis Nixon can turn a routine single into an immediate threat to steal.",
      "Otis Nixon's speed can affect the pitcher, catcher and entire infield.",
      "Otis Nixon has the kind of speed that cannot be taught.",
    ],
  },
  "Bert Blyleven": {
    lines: [
      "Bert Blyleven's birth name is Rik Aalbert Blijleven.",
      "Bert Blyleven was born in Zeist in the Netherlands.",
      "Bert Blyleven's family later moved to Canada and then Southern California.",
      "Bert Blyleven was selected by Minnesota in the third round of the 1969 amateur draft.",
      "Bert Blyleven reached the major leagues at the age of 19 in 1970.",
      "Bert Blyleven won 10 games as a teenage rookie.",
      "Bert Blyleven developed one of the finest curveballs in baseball.",
      "Bert Blyleven's curveball begins high before dropping sharply beneath the hitter's swing.",
      "Bert Blyleven won 20 games for Minnesota during the 1973 season.",
      "Bert Blyleven struck out 258 hitters and posted a 2.52 ERA in 1973.",
      "Bert Blyleven has pitched for Minnesota, Texas, Pittsburgh and Cleveland.",
      "Bert Blyleven helped Pittsburgh win the 1979 World Series.",
      "Bert Blyleven pitched four scoreless relief innings in Game Six of the 1979 World Series.",
      "Bert Blyleven was traded to Cleveland after the 1980 season.",
      "Bert Blyleven went 11-7 with a 2.88 ERA during the strike-shortened 1981 season.",
      "Bert Blyleven completed several consecutive starts during an outstanding stretch in 1981.",
      "Bert Blyleven suffered a serious elbow injury early in the 1982 season.",
      "Bert Blyleven returned to make 24 starts for Cleveland in 1983.",
      "Bert Blyleven went 7-10 with a 3.91 ERA during the 1983 season.",
      "Bert Blyleven threw 156 and a third innings in 1983.",
      "Bert Blyleven completed five games during the 1983 season.",
      "Bert Blyleven struck out 123 hitters while walking only 44 in 1983.",
      "Bert Blyleven allowed only eight home runs during the 1983 season.",
      "Bert Blyleven can throw his curveball for a strike or bury it below the zone.",
      "Bert Blyleven remains capable of working deep into a game when his command is sharp.",
      "Bert Blyleven's experience gives Cleveland a veteran at the front of the rotation.",
    ],
  },
  "Neal Heaton": {
    lines: [
      "Neal Heaton is a left-handed pitcher from New York.",
      "Neal Heaton was originally drafted by the New York Mets but chose not to sign.",
      "Neal Heaton attended the University of Miami.",
      "Neal Heaton was selected by Cleveland in the second round of the 1981 amateur draft.",
      "Neal Heaton advanced rapidly through the Cleveland farm system.",
      "Neal Heaton made his major-league debut on September 3, 1982.",
      "Neal Heaton entered his first full season as both a starter and reliever.",
      "Neal Heaton appeared in 39 games for Cleveland during the 1983 season.",
      "Neal Heaton made 16 starts in 1983.",
      "Neal Heaton went 11-7 during the 1983 season.",
      "Neal Heaton posted a 4.16 ERA over 149 and a third innings in 1983.",
      "Neal Heaton completed four games during the 1983 season.",
      "Neal Heaton recorded three saves while also making 16 starts.",
      "Neal Heaton struck out 75 hitters and walked 44 in 1983.",
      "Neal Heaton gives Cleveland a young left-handed starter.",
      "Neal Heaton's relief experience allows him to remain useful if he is temporarily removed from the rotation.",
      "Neal Heaton demonstrated unusual versatility during his first complete major-league season.",
    ],
  },
  "Steve Comer": {
    lines: [
      "Steve Comer was born in Minneapolis, Minnesota.",
      "Steve Comer attended the University of Minnesota.",
      "Steve Comer was selected by the Texas Rangers in the first round of the 1976 amateur draft.",
      "Steve Comer reached the major leagues with Texas in 1978.",
      "Steve Comer enjoyed his finest season as a starting pitcher in 1979.",
      "Steve Comer went 17-12 with a 3.68 ERA during the 1979 season.",
      "Steve Comer made 36 starts and threw 242 and a third innings in 1979.",
      "Steve Comer completed six games and recorded one shutout during the 1979 season.",
      "Steve Comer later demonstrated that he could also succeed as a relief pitcher.",
      "Steve Comer went 8-2 with a 2.56 ERA in 1981.",
      "Steve Comer recorded six saves while making only one start in 1981.",
      "Steve Comer pitched 77 and a third innings in 36 appearances during that 1981 season.",
      "Steve Comer appeared briefly for Philadelphia during the 1983 season.",
      "Steve Comer made three appearances and one start for the Phillies in 1983.",
      "Steve Comer went 1-0 during his limited 1983 action.",
      "Steve Comer relies more on control and movement than overpowering velocity.",
      "Steve Comer has experience as a starter, long reliever and late-inning pitcher.",
      "Steve Comer gives Cleveland a veteran who can adjust to several different roles.",
    ],
  },
  "Steve Farr": {
    lines: [
      "Steve Farr attended DeMatha Catholic High School in Maryland.",
      "Steve Farr played both pitcher and catcher during his amateur career.",
      "Steve Farr attended American University for one year.",
      "Steve Farr signed professionally with the Pittsburgh Pirates organization.",
      "Steve Farr spent several seasons developing in the minor leagues.",
      "Steve Farr has experience as both a starting pitcher and a reliever.",
      "Steve Farr has not yet appeared in a major-league regular-season game entering 1984.",
      "Steve Farr enters 1984 attempting to earn his first major-league opportunity.",
      "Steve Farr gives Cleveland another right-handed option for the rotation.",
      "Steve Farr's background as a catcher provides him with an additional understanding of pitch selection.",
      "Steve Farr has the arm strength to work as either a starter or a multi-inning reliever.",
      "Steve Farr's path to Cleveland has required considerably more patience than that of a highly advertised prospect.",
    ],
  },
  "Ernie Camacho": {
    lines: [
      "Ernie Camacho's full name is Ernest Carlos Camacho.",
      "Ernie Camacho was born in Salinas, California.",
      "Ernie Camacho began his major-league career with the Oakland Athletics in 1980.",
      "Ernie Camacho later pitched in the Pittsburgh organization.",
      "Ernie Camacho spent portions of several seasons moving between the majors and minors.",
      "Ernie Camacho was acquired by Cleveland during the 1983 season.",
      "Ernie Camacho appeared in four games for Cleveland late in 1983.",
      "Ernie Camacho entered 1984 with only limited major-league experience.",
      "Ernie Camacho throws hard enough to be considered for late-inning work.",
      "Ernie Camacho is most effective when he gets ahead and forces hitters to protect the plate.",
      "Ernie Camacho enters 1984 with an opportunity to establish himself as Cleveland's closer.",
      "Ernie Camacho's path to the ninth inning has required persistence through several organizations.",
    ],
  },
  "Tom Waddell": {
    lines: [
      "Tom Waddell's full name is Thomas David Waddell.",
      "Tom Waddell was born in Dundee, Scotland.",
      "Tom Waddell is one of the few Scottish-born players to reach organized professional baseball.",
      "Tom Waddell worked as a clothing salesman before beginning his professional baseball career.",
      "Tom Waddell signed with the Atlanta Braves as an undrafted free agent in 1981.",
      "Tom Waddell developed as a right-handed relief pitcher in the Atlanta farm system.",
      "Tom Waddell was selected by Cleveland in the December 1983 Rule 5 Draft.",
      "Tom Waddell must remain on Cleveland's active roster or be offered back to Atlanta.",
      "Tom Waddell has not yet appeared in a major-league regular-season game entering 1984.",
      "Tom Waddell enters 1984 with an opportunity few undrafted players receive.",
      "Tom Waddell's unusual route from Scotland to professional baseball makes him one of the roster's most interesting stories.",
      "Tom Waddell may be used for more than one inning when the bullpen requires length.",
    ],
  },
  "Luis Aponte": {
    lines: [
      "Luis Aponte was born in El Tigre, Venezuela.",
      "Luis Aponte signed with the Boston Red Sox organization as an amateur free agent.",
      "Luis Aponte reached the major leagues with Boston in September 1980.",
      "Luis Aponte worked primarily as a middle and long relief pitcher.",
      "Luis Aponte participated in the famous 33-inning minor-league game between Pawtucket and Rochester in 1981.",
      "Luis Aponte pitched four scoreless innings during that marathon game.",
      "Luis Aponte arrived home around dawn after the suspended game.",
      "Luis Aponte's wife reportedly did not initially believe that a baseball game had lasted throughout the night.",
      "Luis Aponte enjoyed his best major-league season to date in 1982.",
      "Luis Aponte appeared in 40 games with a 3.18 ERA during the 1982 season.",
      "Luis Aponte recorded three saves in 1982.",
      "Luis Aponte appeared in 34 games for Boston during the 1983 season.",
      "Luis Aponte went 5-4 with a 3.63 ERA in 1983.",
      "Luis Aponte recorded three saves and pitched 62 innings during the 1983 season.",
      "Luis Aponte struck out 32 hitters and walked 23 in 1983.",
      "Luis Aponte joined Cleveland before the 1984 season.",
      "Luis Aponte can enter in the middle innings and remain through the late innings.",
      "Luis Aponte gives Cleveland another experienced right-handed relief option.",
    ],
  },
  "Jamie Easterly": {
    lines: [
      "Jamie Easterly's full name is James Morris Easterly.",
      "Jamie Easterly is a left-handed pitcher from Texas.",
      "Jamie Easterly began his major-league career with the Atlanta Braves in 1974.",
      "Jamie Easterly worked as both a starter and reliever during his early career.",
      "Jamie Easterly threw a perfect game for the Triple-A Denver Bears during the 1974 season.",
      "Jamie Easterly later joined the Milwaukee Brewers organization.",
      "Jamie Easterly reestablished himself as a major-league reliever in 1981.",
      "Jamie Easterly appeared in 44 games with a 3.19 ERA for Milwaukee in 1981.",
      "Jamie Easterly appeared during Milwaukee's 1981 postseason series.",
      "Jamie Easterly split the 1983 season between Milwaukee and Cleveland.",
      "Jamie Easterly made 41 relief appearances after joining Cleveland in 1983.",
      "Jamie Easterly went 4-2 with a 3.63 ERA for Cleveland.",
      "Jamie Easterly pitched 57 innings and recorded three saves for Cleveland in 1983.",
      "Jamie Easterly struck out 39 hitters during his Cleveland appearances.",
      "Jamie Easterly gives the bullpen an experienced left-handed option.",
      "Jamie Easterly can face one difficult left-handed hitter or continue for multiple innings.",
      "Jamie Easterly's perfect game remains an unusual achievement in his professional history.",
    ],
  },
  "Mike Jeffcoat": {
    lines: [
      "Mike Jeffcoat is a left-handed pitcher from Pine Bluff, Arkansas.",
      "Mike Jeffcoat was selected by Cleveland in the 13th round of the 1980 amateur draft.",
      "Mike Jeffcoat developed as a starting pitcher in the Cleveland farm system.",
      "Mike Jeffcoat made 27 minor-league starts during the 1982 season.",
      "Mike Jeffcoat went 13-12 with a 3.26 ERA in 1982.",
      "Mike Jeffcoat threw 190 and a third innings during that minor-league season.",
      "Mike Jeffcoat struck out 175 hitters in 1982.",
      "Mike Jeffcoat made his major-league debut on August 21, 1983.",
      "Mike Jeffcoat appeared in 11 games for Cleveland during the 1983 season.",
      "Mike Jeffcoat made two major-league starts in 1983.",
      "Mike Jeffcoat went 1-3 with a 3.31 ERA during his first major-league trial.",
      "Mike Jeffcoat pitched 32 and a third innings and allowed 32 hits in 1983.",
      "Mike Jeffcoat gives Cleveland another young left-handed pitcher.",
      "Mike Jeffcoat can work in relief or make an emergency start.",
      "Mike Jeffcoat's minor-league strikeout record suggests more power than his quiet delivery might indicate.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive — base hit.\"",
    "\"Long drive to right field — way back — gone. Home run!\"",
    "\"Ground ball to short — over to first — in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This is a ballclub with young talent all over the diamond — the Indians are building something here.\"",
    "\"Cleveland baseball has a bright future with these young players.\"",
    "\"The Indians have put together an athletic, exciting young club.\"",
    "\"There's a new energy at Cleveland Municipal Stadium this season.\"",
    "\"Brett Butler, Julio Franco, Brook Jacoby — that's a young core to build around.\"",
    "\"The trades have brought in talent and the future looks bright for the Indians.\"",
    "\"This team is younger and faster than Cleveland fans have seen in years.\"",
    "\"The Indians are turning the corner — you can feel it at the ballpark.\"",
    "\"Cleveland has a nucleus here that could compete for years to come.\"",
    "\"There's talent up and down this roster, and it's starting to come together.\"",
    "\"The fans in Cleveland have been waiting for a winner — this club is working toward it.\"",
    "\"This team doesn't quit. They play hard all nine innings — that's Indians baseball.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Brett Butler gives the Indians a true leadoff man with game-changing speed.\"",
    "\"Julio Franco is one of the most exciting young shortstops in the American League.\"",
    "\"Andre Thornton provides the power in the middle of this Cleveland lineup.\"",
    "\"Bert Blyleven's curveball is still one of the best in baseball.\"",
    "\"Mike Hargrove is as patient a hitter as you'll find anywhere.\"",
    "\"Brook Jacoby is a young third baseman with real power potential.\"",
    "\"The Indians have assembled athletic, young players at every position.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Cleveland Municipal Stadium.\"",
    "\"The lights are on at the old ballpark by the lake — Indians baseball tonight.\"",
    "\"Cleveland Municipal Stadium — one of the largest and most historic venues in baseball.\"",
    "\"The breeze off Lake Erie is blowing in tonight — that could knock down a few fly balls.\"",
    "\"The cavernous dimensions here at the stadium make it tough on home-run hitters.\"",
    "\"The artificial turf plays fast tonight — ground balls will scoot through the infield.\"",
    "\"There's plenty of room out there in the outfield — this is one big ballpark.\"",
    "\"The seats stretch far back at Cleveland Municipal Stadium — there's not a bad seat in the house.\"",
    "\"The Cleveland skyline is visible beyond the outfield walls on a clear night.\"",
    "\"The wind off the lake can be a factor all game long — outfielders have to be alert.\"",
    "\"This stadium was built for football, but it's been home to Indians baseball for decades.\"",
    "\"It may be a big ballpark, but the fans who show up love their Indians.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here in Cleveland is into this ballgame.\"",
    "\"Indians fans are making some noise tonight.\"",
    "\"The fans in Cleveland love their baseball — listen to that.\"",
    "\"The faithful at the old stadium are on their feet.\"",
    "\"Cleveland fans have been through a lot — they're loyal to this ballclub.\"",
    "\"The crowd is energized tonight — they can feel something building here.\"",
    "\"A great turnout at Cleveland Municipal Stadium.\"",
    "\"These fans have supported this team through some tough years — they deserve a winner.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Cleveland Municipal Stadium, everyone. A fine evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball by the lake on a summer night.\"",
    "\"From all of us here in Cleveland, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story — that's the beauty of this sport.\"",
    "\"Baseball in Cleveland — it's a tradition that runs deep in this city.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone — into the seats at the old ballpark!\"",
    "\"A magnificent piece of hitting. Simply magnificent.\"",
    "\"The Indians are making their move here at Cleveland Municipal Stadium.\"",
    "\"That one is long gone — souvenir for a fan in the bleachers.\"",
    "\"You won't see many better than that one.\"",
    "\"He stood there like the house by the side of the road.\"",
  ]},
};