// Long-Distance Phone Wars Interactive Museum Exhibits (826-850)
// 25 entries celebrating the 1984 telecom revolution

const ENTRIES = [
  {
    id: 'att_breakup',
    exhibit: 'The AT&T Breakup',
    icon: '⚡',
    matchText: 'On January 1, 1984, a federal court order broke apart the largest company in the world.',
    tagline: 'Divestiture Day',
    year: '1984',
    description: 'On January 1, 1984, a federal court order broke apart the largest company in the world. AT&T, which had controlled nearly all telephone service in the United States since the early 20th century, was split into a long-distance company and seven regional "Baby Bell" operating companies. The breakup ended decades of monopoly and opened the door for competition in long-distance telephone service.',
    date: 'January 1, 1984',
    significance: 'Ended AT&T monopoly',
    result: '7 Baby Bells + AT&T long-distance',
    iconic: true,
    category: 'milestone',
    funFact: 'The AT&T breakup was one of the largest corporate restructurings in history.',
  },
  {
    id: 'baby_bells',
    exhibit: 'The Baby Bells',
    icon: '🔔',
    matchText: 'The 1984 breakup created seven regional telephone companies known as the Baby Bells.',
    tagline: 'Seven New Companies',
    year: '1984',
    description: 'The 1984 breakup created seven regional telephone companies known as the Baby Bells: Nynex, Bell Atlantic, BellSouth, Southwestern Bell, Ameritech, US West, and Pacific Telesis. Each provided local phone service in a different geographic region. The Baby Bells would eventually merge and recombine over the following decades, with some growing back into national telecommunications giants.',
    companies: ['Nynex', 'Bell Atlantic', 'BellSouth', 'Southwestern Bell', 'Ameritech', 'US West', 'Pacific Telesis'],
    count: '7 regional companies',
    iconic: true,
    category: 'milestone',
    funFact: 'Several Baby Bells later re-merged, with some eventually reconstituting parts of AT&T itself.',
  },
  {
    id: 'mci',
    exhibit: 'MCI Communications',
    icon: '📞',
    matchText: 'MCI Communications was the scrappy challenger that helped bring down the AT&T monopoly and became its first major long-distance competitor.',
    tagline: 'The Challenger',
    description: 'MCI Communications was the scrappy challenger that helped bring down the AT&T monopoly and became its first major long-distance competitor. After the breakup, MCI aggressively marketed cut-rate long-distance service to homes and businesses, using direct sales, television advertising, and eventually its famous Friends & Family plan. MCI proved that competition in telecommunications was not only possible but profitable.',
    role: 'First major competitor',
    strategy: 'Cut-rate pricing, aggressive marketing',
    iconic: true,
    category: 'company',
    funFact: 'MCI\'s antitrust lawsuit against AT&T helped trigger the breakup.',
  },
  {
    id: 'sprint',
    exhibit: 'Sprint',
    icon: '📌',
    matchText: 'Sprint entered the long-distance market as the third major competitor, famous for its "pin drop" commercials suggesting crystal-clear calls.',
    tagline: 'Hear a Pin Drop',
    description: 'Sprint entered the long-distance market as the third major competitor, famous for its "pin drop" commercials suggesting crystal-clear calls. Backed by the Southern Pacific Railroad\'s fiber-optic network, Sprint positioned itself as the quality leader among long-distance carriers. The pin drop became one of the most recognizable advertising icons of the 1980s.',
    network: 'Southern Pacific fiber-optic',
    slogan: 'Hear a pin drop',
    iconic: true,
    category: 'company',
    funFact: 'Sprint\'s network originally ran along Southern Pacific Railroad rights-of-way.',
  },
  {
    id: 'reach_out_america',
    exhibit: 'Reach Out America',
    icon: '🤝',
    matchText: 'AT&T launched the "Reach Out America" campaign to convince customers to stay with AT&T after the breakup.',
    tagline: 'Choose AT&T',
    year: '1984',
    description: 'AT&T launched the "Reach Out America" campaign to convince customers to stay with AT&T after the breakup. For the first time, AT&T had to compete for customers who had always been theirs by default. The campaign featured warm, emotional advertising emphasizing AT&T\'s reliability, experience, and commitment to connecting people across the country.',
    campaign: 'Reach Out America',
    purpose: 'Retain customers post-breakup',
    category: 'advertising',
    iconic: true,
    funFact: 'Reach Out America was AT&T\'s first-ever campaign asking customers to choose them.',
  },
  {
    id: 'friends_and_family',
    exhibit: 'MCI Friends & Family',
    icon: '👨‍👩‍👧‍👦',
    matchText: 'MCI\'s Friends & Family plan offered discounts when both callers used MCI, creating a viral marketing phenomenon.',
    tagline: 'Get Your Friends to Switch',
    year: '1984',
    description: 'MCI\'s Friends & Family plan offered discounts when both callers used MCI, creating a viral marketing phenomenon. Customers were incentivized to recruit their friends and relatives to switch to MCI, turning every subscriber into a salesperson. The plan was one of the most successful marketing innovations of the decade and forced AT&T and Sprint to create their own network-based discount plans.',
    innovation: 'Network-based discounts',
    effect: 'Viral customer recruitment',
    iconic: true,
    category: 'advertising',
    funFact: 'Friends & Family turned MCI customers into a sales force for the company.',
  },
  {
    id: 'pin_drop',
    exhibit: 'The Sprint Pin Drop',
    icon: '📍',
    matchText: 'Sprint\'s "pin drop" became one of the most iconic advertising sounds of the 1980s.',
    tagline: 'Crystal Clear Quality',
    description: 'Sprint\'s "pin drop" became one of the most iconic advertising sounds of the 1980s. The commercials showed a pin dropping onto a surface, with the sound clearly audible, implying that Sprint\'s fiber-optic network was so quiet and clear you could hear a pin drop from across the country. The campaign successfully positioned Sprint as the quality leader in long-distance.',
    icon: 'Pin drop sound',
    message: 'Fiber-optic clarity',
    category: 'advertising',
    iconic: true,
    funFact: 'The pin drop sound became instantly recognizable to millions of TV viewers.',
  },
  {
    id: 'long_distance_rates',
    exhibit: 'Long-Distance Rate Wars',
    icon: '💰',
    matchText: 'Before competition, AT&T charged high flat rates for long-distance calls. After the breakup, rates began falling as MCI and Sprint undercut each other.',
    tagline: 'Prices Plummet',
    description: 'Before competition, AT&T charged high flat rates for long-distance calls. After the breakup, rates began falling as MCI and Sprint undercut each other. Customers who had paid dollars per minute for coast-to-coast calls started seeing rates drop steadily throughout the 1980s. The rate wars made long-distance calling affordable for ordinary families for the first time.',
    before: 'High flat rates',
    after: 'Falling competitive rates',
    category: 'milestone',
    funFact: 'Long-distance rates fell dramatically throughout the 1980s thanks to competition.',
  },
  {
    id: 'calling_cards',
    exhibit: 'Telephone Calling Cards',
    icon: '💳',
    matchText: 'Plastic calling cards let customers charge long-distance calls to their home phone account from any telephone.',
    tagline: 'Call From Anywhere',
    description: 'Plastic calling cards let customers charge long-distance calls to their home phone account from any telephone. Each card had an account number and PIN, allowing travelers to make calls from pay phones, hotel rooms, and other people\'s homes without needing coins. The cards became essential tools for business travelers and visiting relatives alike.',
    features: ['Account number', 'PIN', 'Charge to home phone'],
    users: 'Travelers, business people',
    category: 'technology',
    funFact: 'Calling cards freed travelers from carrying rolls of quarters for pay phones.',
  },
  {
    id: 'collect_calls',
    exhibit: 'Collect Calls',
    icon: '🪙',
    matchText: 'A collect call let the person receiving the call agree to pay the charges, a service especially popular with college students calling home.',
    tagline: 'Call Home for Free',
    description: 'A collect call let the person receiving the call agree to pay the charges, a service especially popular with college students calling home. The caller would dial the operator, request a collect call, and the operator would ask the recipient if they accepted the charges. Many parents learned to listen carefully for the operator\'s voice before agreeing to pay.',
    process: 'Operator asks recipient to accept',
    popularWith: 'College students',
    category: 'service',
    funFact: 'College students made collect calls home so often that parents developed screening rituals.',
  },
  {
    id: 'operator_services',
    exhibit: 'Operator Services',
    icon: '👩‍💼',
    matchText: 'Before automated systems, human operators handled directory assistance, collect calls, person-to-person calls, and billing disputes.',
    tagline: 'Number, Please',
    description: 'Before automated systems, human operators handled directory assistance, collect calls, person-to-person calls, and billing disputes. In 1984, operators were still a familiar voice on the line, though automation was beginning to reduce their numbers. The phrase "number, please" was fading but still echoed in the memories of older callers.',
    services: ['Directory assistance', 'Collect calls', 'Person-to-person', 'Billing disputes'],
    trend: 'Increasing automation',
    category: 'service',
    funFact: 'Operators once knew regular callers by voice in small towns.',
  },
  {
    id: 'pay_phones',
    exhibit: 'The Pay Phone',
    icon: '☎️',
    matchText: 'In 1984, pay phones were everywhere: street corners, gas stations, restaurants, airports, and hotel lobbies.',
    tagline: 'A Dime for a Dial',
    description: 'In 1984, pay phones were everywhere: street corners, gas stations, restaurants, airports, and hotel lobbies. A local call typically cost a dime or a quarter, while long-distance calls required a small fortune in coins or a calling card. The pay phone was an essential piece of American infrastructure, connecting people before cell phones made them obsolete.',
    locations: ['Street corners', 'Gas stations', 'Restaurants', 'Airports', 'Hotel lobbies'],
    localCall: '10-25 cents',
    category: 'technology',
    iconic: true,
    funFact: 'A local pay phone call cost just a dime in many cities in 1984.',
  },
  {
    id: 'dial_around',
    exhibit: 'Dial-Around Services',
    icon: '🔢',
    matchText: 'Dial-around services let callers bypass their default long-distance carrier by dialing a special access code.',
    tagline: '10-XXX',
    description: 'Dial-around services let callers bypass their default long-distance carrier by dialing a special access code. By entering a 5-digit code (starting with 10) before the number, callers could route their call through a different carrier that might offer lower rates. The system gave consumers a way to shop for the best price on every call.',
    code: '10-XXX format',
    purpose: 'Bypass default carrier',
    category: 'technology',
    funFact: 'Dial-around codes let consumers comparison-shop on every single call.',
  },
  {
    id: 'fiber_optic',
    exhibit: 'Fiber-Optic Networks',
    icon: '🌐',
    matchText: 'Fiber-optic cables, carrying calls as pulses of light, revolutionized long-distance transmission in the 1980s.',
    tagline: 'Light-Speed Calls',
    description: 'Fiber-optic cables, carrying calls as pulses of light, revolutionized long-distance transmission in the 1980s. A single fiber-optic strand could carry thousands of simultaneous conversations with crystal-clear quality. Sprint built its marketing around fiber optics, and AT&T and MCI raced to lay their own fiber networks across the country.',
    technology: 'Light pulses through glass',
    capacity: 'Thousands of calls per strand',
    category: 'technology',
    iconic: true,
    funFact: 'A single fiber-optic strand can carry thousands of simultaneous calls.',
  },
  {
    id: 'att_logo',
    exhibit: 'The AT&T Globe Logo',
    icon: '🌍',
    matchText: 'After the breakup, AT&T introduced a new logo: a stylized globe with horizontal lines, designed by Saul Bass.',
    tagline: 'The Death Star',
    year: '1984',
    description: 'After the breakup, AT&T introduced a new logo: a stylized globe with horizontal lines, designed by Saul Bass. The logo, sometimes nicknamed the "Death Star," replaced the familiar Bell System logo and signaled a new era for the company. It became one of the most recognizable corporate symbols of the 1980s.',
    designer: 'Saul Bass',
    nickname: 'The Death Star',
    category: 'advertising',
    iconic: true,
    funFact: 'The AT&T globe logo was designed by legendary graphic designer Saul Bass.',
  },
  {
    id: 'bell_system_logo',
    exhibit: 'The Bell System Logo',
    icon: '🔔',
    matchText: 'The Bell System logo, a cross-section of a bell inside a circle, had represented American telephone service for decades before the breakup.',
    tagline: 'A Familiar Ring',
    description: 'The Bell System logo, a cross-section of a bell inside a circle, had represented American telephone service for decades before the breakup. After 1984, the Bell logo was retired from national use, though the Baby Bells continued using variations of it. For millions of Americans, the Bell symbol had meant "telephone" their entire lives.',
    symbol: 'Bell cross-section in circle',
    legacy: 'Retired from national use',
    category: 'advertising',
    iconic: true,
    funFact: 'The Bell logo was so familiar that "Ma Bell" became a household nickname for AT&T.',
  },
  {
    id: 'ma_bell',
    exhibit: 'Ma Bell',
    icon: '👵',
    matchText: '"Ma Bell" was the affectionate nickname Americans gave to the Bell System, reflecting its maternal monopoly over telephone service.',
    tagline: 'The Mother of All Phones',
    description: '"Ma Bell" was the affectionate nickname Americans gave to the Bell System, reflecting its maternal monopoly over telephone service. The name captured both the comfort of reliable service and the frustration of dealing with a giant bureaucracy. After the breakup, people wondered whether the Baby Bells would grow up to be as powerful as their mother.',
    meaning: 'Maternal monopoly nickname',
    sentiment: 'Comfort + frustration',
    category: 'culture',
    funFact: 'The "Ma Bell" nickname reflected both affection and frustration with the monopoly.',
  },
  {
    id: 'long_distance_anxiety',
    exhibit: 'Long-Distance Anxiety',
    icon: '😰',
    matchText: 'Before the rate wars, many families treated long-distance calls as luxury items, keeping them brief and saving them for special occasions.',
    tagline: 'Is This Long Distance?',
    description: 'Before the rate wars, many families treated long-distance calls as luxury items, keeping them brief and saving them for special occasions. The phrase "is this long distance?" was commonly asked before accepting a call, and parents scolded children for making long-distance calls without permission. The falling rates of the 1980s gradually erased this anxiety.',
    behavior: 'Brief calls, special occasions',
    fear: 'High per-minute costs',
    category: 'culture',
    funFact: 'Families once timed long-distance calls to avoid expensive per-minute charges.',
  },
  {
    id: 'telemarketing',
    exhibit: 'Telemarketing Boom',
    icon: '📲',
    matchText: 'The breakup of AT&T coincided with a boom in telemarketing, as companies used the telephone to sell products directly to consumers.',
    tagline: 'Hello, Am I Bothering You?',
    description: 'The breakup of AT&T coincided with a boom in telemarketing, as companies used the telephone to sell products directly to consumers. Long-distance carriers themselves became some of the most aggressive telemarketers, calling homes to ask people to switch carriers. The dinner-hour phone call from a stranger became a new American tradition.',
    growth: 'Direct phone sales',
    callers: 'Long-distance carriers, products',
    category: 'culture',
    funFact: 'Long-distance carriers were among the most aggressive telemarketers of the 1980s.',
  },
  {
    id: 'slamming',
    exhibit: 'Slamming',
    icon: '🔄',
    matchText: '"Slamming" was the illegal practice of switching a customer\'s long-distance carrier without their knowledge or consent.',
    tagline: 'Switched Without Knowing',
    description: '"Slamming" was the illegal practice of switching a customer\'s long-distance carrier without their knowledge or consent. Some aggressive sales agents would forge signatures or mislead customers into signing up, only for the victim to discover they had been moved to a different carrier. The practice became a major consumer protection issue.',
    practice: 'Unauthorized carrier switching',
    status: 'Illegal',
    category: 'culture',
    funFact: 'Slamming victims often discovered the switch only when their next bill arrived.',
  },
  {
    id: 'wats_lines',
    exhibit: 'WATS Lines',
    icon: '📶',
    matchText: 'Wide Area Telephone Service (WATS) lines let businesses make unlimited outbound long-distance calls for a flat monthly fee.',
    tagline: 'Flat-Rate Calling',
    description: 'Wide Area Telephone Service (WATS) lines let businesses make unlimited outbound long-distance calls for a flat monthly fee. WATS lines were essential for companies with national sales forces, customer service departments, and telemarketing operations. The familiar "1-800" toll-free numbers used inbound WATS service to let customers call businesses for free.',
    full: 'Wide Area Telephone Service',
    benefit: 'Flat monthly fee',
    category: 'technology',
    funFact: 'WATS lines powered the 1-800 toll-free numbers that businesses advertised nationwide.',
  },
  {
    id: 'toll_free_800',
    exhibit: '1-800 Toll-Free Numbers',
    icon: '🆓',
    matchText: '1-800 toll-free numbers let customers call businesses without paying, with the business picking up the tab.',
    tagline: 'Call Us Free',
    description: '1-800 toll-free numbers let customers call businesses without paying, with the business picking up the tab. The numbers became powerful marketing tools, appearing in television commercials, print ads, and billboards across the country. A memorable 1-800 number could be worth millions in customer response.',
    format: '1-800-XXX-XXXX',
    benefit: 'Business pays for the call',
    category: 'technology',
    iconic: true,
    funFact: 'A memorable 1-800 number could be worth millions in customer response.',
  },
  {
    id: 'touch_tone',
    exhibit: 'Touch-Tone Phones',
    icon: '🎵',
    matchText: 'Touch-Tone phones, with push-button keypads replacing rotary dials, were becoming the standard in American homes by 1984.',
    tagline: 'Push, Don\'t Dial',
    description: 'Touch-Tone phones, with push-button keypads replacing rotary dials, were becoming the standard in American homes by 1984. The dual-tone multi-frequency (DTMF) tones allowed faster dialing and enabled automated phone systems, voicemail, and banking-by-phone services. The familiar musical tones of a Touch-Tone keypad became the sound of modern telecommunications.',
    technology: 'DTMF tones',
    advantage: 'Faster dialing, automated systems',
    category: 'technology',
    iconic: true,
    funFact: 'Touch-Tone tones enabled the first banking-by-phone and voicemail systems.',
  },
  {
    id: 'competition_benefits',
    exhibit: 'The Benefits of Competition',
    icon: '🏆',
    matchText: 'The long-distance phone wars brought lower prices, better quality, new services, and marketing innovations to American consumers.',
    tagline: 'A Win for Consumers',
    description: 'The long-distance phone wars brought lower prices, better quality, new services, and marketing innovations to American consumers. Before the breakup, there was one phone company and one set of rates. After 1984, Americans could choose their carrier, shop for the best price, and enjoy steadily improving service. The phone wars proved that competition could transform even the most entrenched monopoly.',
    benefits: ['Lower prices', 'Better quality', 'New services', 'Marketing innovations'],
    lesson: 'Competition transforms monopolies',
    iconic: true,
    inspirational: true,
    category: 'milestone',
    funFact: 'The phone wars proved that competition could transform even a century-old monopoly.',
  },
];

const VIEWED_EXHIBITS = new Set();
const EXHIBIT_VIEW_COUNTS = {};

export function findLongDistancePhoneWarsEntry(adText) {
  return ENTRIES.find(e => e.matchText === adText) || null;
}

export function trackLongDistancePhoneWarsView(entryId) {
  VIEWED_EXHIBITS.add(entryId);
  EXHIBIT_VIEW_COUNTS[entryId] = (EXHIBIT_VIEW_COUNTS[entryId] || 0) + 1;
  const unlocked = [];

  if (VIEWED_EXHIBITS.size >= 5) unlocked.push('phone_wars_fan');
  if (VIEWED_EXHIBITS.size >= 15) unlocked.push('phone_wars_enthusiast');
  if (VIEWED_EXHIBITS.size >= 25) unlocked.push('phone_wars_historian');

  return unlocked;
}

export function getLongDistancePhoneWarsViewCount() {
  return VIEWED_EXHIBITS.size;
}