// Mall Culture Interactive Museum Exhibits (901-925)
// 25 entries celebrating 1984 shopping mall culture

const ENTRIES = [
  {
    id: 'food_court',
    exhibit: 'The Food Court',
    icon: '🍕',
    matchText: 'By 1984, the food court had become the mall\'s unofficial town square.',
    tagline: 'The Unofficial Town Square',
    year: '1984',
    description: 'By 1984, the food court had become the mall\'s unofficial town square. Shoppers carrying bags from three different stores could choose pizza, burgers, egg rolls, hot dogs, frozen yogurt, or a frothy Orange Julius without leaving the building. Nobody in a group had to agree on where to eat-and afterward, everyone occupied the same sticky table. The mixture of cooking smells could guide a hungry shopper from nearly any wing of the mall.',
    purpose: 'Gathering place',
    options: ['Pizza', 'Burgers', 'Egg rolls', 'Hot dogs', 'Frozen yogurt', 'Orange Julius'],
    advantage: 'No group agreement needed',
    iconic: true,
    category: 'dining',
    funFact: 'The food court smell could guide hungry shoppers from halfway across the mall.',
  },
  {
    id: 'mall_fountain',
    exhibit: 'The Mall Fountain',
    icon: '⛲',
    matchText: 'Large indoor fountains gave shopping malls a touch of glamour while also providing a natural meeting place.',
    tagline: 'Glamour Meets Commerce',
    year: '1984',
    description: 'Large indoor fountains gave shopping malls a touch of glamour while also providing a natural meeting place. Children tossed pennies into the water, parents rested along the edge, and teenagers gathered nearby while pretending they were not waiting for anyone in particular. The faint smell of chlorine mixed with perfume counters, pizza ovens, and cigarette smoke from whatever portion of the mall still allowed it. Every so often, a prankster added soap and turned the centerpiece into an indoor bubble disaster.',
    function: 'Meeting place',
    activities: ['Penny tossing', 'Parent resting', 'Teenager gathering'],
    smell: 'Chlorine, perfume, pizza, smoke',
    iconic: true,
    category: 'architecture',
    funFact: 'Pranksters sometimes added soap and turned the fountain into a bubble-producing spectacle.',
  },
  {
    id: 'arcade',
    exhibit: 'The Arcade',
    icon: '👾',
    matchText: 'Aladdin\'s Castle, Tilt, and hundreds of independent arcades offered dark rooms filled with glowing screens, electronic noise, and teenagers carrying rolls of quarters.',
    tagline: 'High Scores = Social Status',
    year: '1984',
    description: 'Aladdin\'s Castle, Tilt, and hundreds of independent arcades offered dark rooms filled with glowing screens, electronic noise, and teenagers carrying rolls of quarters. A player could spend an entire Saturday moving between Galaga, Pac-Man, Defender, Donkey Kong, and the change machine. High scores were treated like local sports records, and placing your initials on a machine could provide bragging rights for weeks. After spending every quarter, the same teenager would often tell a parent there was "nothing to do."',
    chains: ['Aladdin\'s Castle', 'Tilt'],
    games: ['Galaga', 'Pac-Man', 'Defender', 'Donkey Kong'],
    currency: 'Rolls of quarters',
    status: 'High scores = bragging rights',
    iconic: true,
    category: 'entertainment',
    funFact: 'High scores were treated like local sports records, with initials providing weeks of bragging rights.',
  },
  {
    id: 'spencer_gifts',
    exhibit: 'Spencer Gifts',
    icon: '🌀',
    matchText: 'Walking into Spencer Gifts meant entering a dimly lit world of blacklight posters, lava lamps, novelty mugs, rude greeting cards, gag gifts, rock merchandise, and products that caused parents to suddenly suggest visiting Sears instead.',
    tagline: 'Dimly Lit Teenage Museum',
    year: '1984',
    description: 'Walking into Spencer Gifts meant entering a dimly lit world of blacklight posters, lava lamps, novelty mugs, rude greeting cards, gag gifts, rock merchandise, and products that caused parents to suddenly suggest visiting Sears instead. It was part gift shop, part teenage museum, and part test of how long an unsupervised kid could remain before an employee became suspicious. Even shoppers who bought nothing usually left after examining at least one object they could not believe was being sold in a respectable mall.',
    items: ['Blacklight posters', 'Lava lamps', 'Novelty mugs', 'Rude cards', 'Gag gifts', 'Rock merchandise'],
    purpose: 'Gift shop + teenage hangout + parent escape',
    iconic: true,
    category: 'retail',
    funFact: 'Every customer left after examining at least one product they couldn\'t believe was sold in a mall.',
  },
  {
    id: 'sam_goody',
    exhibit: 'Sam Goody / Musicland',
    icon: '🎵',
    matchText: 'Musicland and Sam Goody helped make the mall record store a destination rather than a quick errand.',
    tagline: 'The Record Store Pilgrimage',
    year: '1984',
    description: 'Musicland and Sam Goody helped make the mall record store a destination rather than a quick errand. Shoppers flipped through vinyl albums, cassette tapes, singles, music magazines, and the still-small selection of expensive compact discs. Teenagers could spend an hour examining album covers, comparing track lists, and checking prices before leaving without buying anything. The employees generally knew more about music than the customers, although they sometimes appeared determined not to prove it.',
    formats: ['Vinyl albums', 'Cassette tapes', 'Singles', 'Music magazines', 'Compact discs'],
    behavior: 'Browse for hours, leave without buying',
    staff: 'Knowledgeable but reluctant to help',
    iconic: true,
    category: 'retail',
    funFact: 'Employees usually knew more about music than customers but seemed determined not to prove it.',
  },
  {
    id: 'orange_julius',
    exhibit: 'The Orange Julius',
    icon: '🥤',
    matchText: 'The Orange Julius combined orange juice, sweetness, milkiness, and crushed ice into a frothy drink that seemed specifically engineered for drinking through a straw while wandering past department-store windows.',
    tagline: 'Neither Juice Nor Milkshake',
    year: '1984',
    description: 'The Orange Julius combined orange juice, sweetness, milkiness, and crushed ice into a frothy drink that seemed specifically engineered for drinking through a straw while wandering past department-store windows. It was neither quite a milkshake nor ordinary orange juice. It occupied its own mysterious category and became one of the unofficial beverages of American mall culture. Shoppers rarely questioned what was in it. They simply carried the paper cup through the mall until nothing remained but foam and a noisy straw.',
    ingredients: 'Orange juice, sweetness, milkiness, crushed ice',
    mystery: 'Exact recipe unknown',
    consumption: 'Through a straw while shopping',
    iconic: true,
    category: 'dining',
    funFact: 'Nobody questioned what was in it-they just drank it while shopping.',
  },
  {
    id: 'mall_map',
    exhibit: 'The Mall Map',
    icon: '🗺️',
    matchText: 'The giant "YOU ARE HERE" directory was supposed to simplify navigation.',
    tagline: 'You Are Confused Here',
    year: '1984',
    description: 'The giant "YOU ARE HERE" directory was supposed to simplify navigation. Instead, shoppers stared at the red dot, turned the map sideways, pointed in three directions, and eventually followed someone who merely looked confident. Stores were listed alphabetically and assigned tiny numbers scattered across several color-coded wings. Finding the restroom required basic cartography. Returning to the correct parking-lot entrance required advanced training and possibly a compass.',
    intention: 'Simplify navigation',
    reality: 'Confuse everyone',
    difficulty: 'Finding restroom = basic cartography',
    parking: 'Requires compass',
    iconic: true,
    category: 'navigation',
    funFact: 'Shoppers eventually just followed someone who looked confident.',
  },
  {
    id: 'food_court_tray',
    exhibit: 'The Food Court Tray',
    icon: '📋',
    matchText: 'The molded plastic food-court tray turned unrelated purchases into a complete dining experience.',
    tagline: 'Sticky Compartments',
    year: '1984',
    description: 'The molded plastic food-court tray turned unrelated purchases into a complete dining experience. A slice of pizza, a paper cup of soda, three napkins, and a plastic fork could be balanced together while the shopper searched for an open table. The tray was always slightly wet for reasons nobody wished to investigate. Once emptied, it was stacked beside a trash opening that required separating utensils, paper, and food with a level of responsibility rarely demonstrated elsewhere in the mall.',
    capacity: 'Pizza slice, soda, napkins, fork',
    condition: 'Always slightly wet',
    disposal: 'Requires separation of waste',
    iconic: true,
    category: 'dining',
    funFact: 'The tray was always inexplicably wet for reasons nobody wanted to investigate.',
  },
  {
    id: 'escalator',
    exhibit: 'The Escalator',
    icon: '🪜',
    matchText: 'For adults, the escalator was transportation. For teenagers and children, it was an attraction provided free of charge.',
    tagline: 'Free Entertainment',
    year: '1984',
    description: 'For adults, the escalator was transportation. For teenagers and children, it was an attraction provided free of charge. Riders went up, crossed the landing, and immediately came back down without entering a single store. Others attempted to walk against its direction or touched the moving handrail until static electricity delivered a warning. Mall security usually tolerated a few unnecessary trips before issuing the traditional command: "Keep moving."',
    adult_use: 'Transportation',
    teen_use: 'Attraction',
    activities: ['Riding up and down', 'Walking against it', 'Static electricity challenge'],
    iconic: true,
    category: 'entertainment',
    funFact: 'Teens rode escalators purely for entertainment, with security eventually issuing "Keep moving" commands.',
  },
  {
    id: 'mall_santa',
    exhibit: 'The Mall Santa',
    icon: '🎅',
    matchText: 'Every holiday season, a temporary North Pole appeared near the mall fountain or department-store entrance.',
    tagline: 'Screaming Children Photo Op',
    year: 'Holiday 1984',
    description: 'Every holiday season, a temporary North Pole appeared near the mall fountain or department-store entrance. Santa sat inside a plywood grotto surrounded by artificial snow, wrapped presents, plastic reindeer, and elves earning seasonal wages. Children waited in a long line to whisper their Christmas wishes, although many changed their minds upon reaching the front and began screaming instead. Parents paid for a photograph capturing either a magical childhood memory or several adults attempting to hold one terrified child still.',
    setup: 'Plywood grotto, artificial snow, plastic reindeer',
    outcome: 'Magical memory OR terrified screaming',
    photo_cost: 'Expensive',
    iconic: true,
    category: 'holiday',
    funFact: 'Many children screamed instead of whispering wishes when they reached Santa.',
  },
  {
    id: 'cinnamon_roll',
    exhibit: 'The Cinnamon Roll Stand',
    icon: '🧁',
    matchText: 'The cinnamon-roll stand rarely needed a sign because shoppers could smell it from halfway across the mall.',
    tagline: 'Nose-Guided Advertising',
    year: '1984',
    description: 'The cinnamon-roll stand rarely needed a sign because shoppers could smell it from halfway across the mall. Warm dough, brown sugar, cinnamon, melted butter, and thick icing drifted through the corridors like an advertising campaign delivered directly through the nose. Shoppers who had already eaten lunch suddenly decided they had room for something else. The oversized roll arrived on a paper plate, required several napkins, and contained enough icing to leave the customer sticky until reaching the parking lot.',
    ingredients: ['Warm dough', 'Brown sugar', 'Cinnamon', 'Melted butter', 'Thick icing'],
    marketing: 'Smell-based advertising',
    effect: 'Hungry conversion in 5 seconds',
    mess_level: 'Parking lot sticky',
    iconic: true,
    category: 'dining',
    funFact: 'The smell alone was advertisement enough-shoppers didn\'t need to see a sign.',
  },
  {
    id: 'mall_walker',
    exhibit: 'The Mall Walker',
    icon: '🚶',
    matchText: 'Long before the stores opened, groups of walkers arrived wearing comfortable shoes, sweatshirts, and sometimes brightly colored warm-up suits.',
    tagline: 'Indoor Exercise Track',
    year: '1984',
    description: 'Long before the stores opened, groups of walkers arrived wearing comfortable shoes, sweatshirts, and sometimes brightly colored warm-up suits. They used the mall\'s long, level corridors as an indoor exercise track protected from rain, snow, summer heat, traffic, and uneven sidewalks. Some counted laps, others walked in groups, and nearly everyone knew exactly how many trips around the fountain equaled a mile. By the time ordinary shoppers arrived, the mall walkers had already completed their morning workout.',
    time: 'Before stores open',
    attire: ['Comfortable shoes', 'Sweatshirts', 'Warm-up suits'],
    benefits: ['No rain', 'No snow', 'No heat', 'No traffic', 'Flat surface'],
    knowledge: 'Fountain lap calculations',
    iconic: true,
    category: 'culture',
    funFact: 'Mall walkers knew exactly how many fountain loops equaled a mile.',
  },
  {
    id: 'anchor_store',
    exhibit: 'The Anchor Store',
    icon: '🏬',
    matchText: 'Sears, JCPenney, Macy\'s, Montgomery Ward, or a regional department store occupied the ends of the mall\'s major wings.',
    tagline: 'The Gravitational Pull',
    year: '1984',
    description: 'Sears, JCPenney, Macy\'s, Montgomery Ward, or a regional department store occupied the ends of the mall\'s major wings. These "anchors" attracted enough shoppers to support the smaller stores connecting them. A family could enter through Sears automotive, cross cosmetics, examine appliances, pass through the mall, and emerge an hour later at another department store without remembering what it had originally come to buy. The anchor store gave the entire mall its gravitational pull.',
    chains: ['Sears', 'JCPenney', 'Macy\'s', 'Montgomery Ward'],
    function: 'Anchor tenant',
    gravity: 'Entire mall structure',
    navigation: 'Defined by anchor name',
    iconic: true,
    category: 'retail',
    funFact: 'Families entered through one anchor and emerged an hour later at another, having forgotten their original purpose.',
  },
  {
    id: 'mall_rat',
    exhibit: 'The Mall Rat',
    icon: '🐭',
    matchText: 'The mall rat did not necessarily purchase anything.',
    tagline: 'Saturday Afternoon Teenager',
    year: '1984',
    description: 'The mall rat did not necessarily purchase anything. The mall rat arrived Saturday afternoon, met friends near the fountain, walked the same circuit repeatedly, visited the arcade, occupied a food-court table, and remained until someone\'s parent provided transportation home. The mall offered climate control, music, food, potential romance, and very little adult supervision. For a teenager in 1984, that was an excellent entertainment package.',
    saturday_routine: ['Meet friends at fountain', 'Walk circuit', 'Visit arcade', 'Occupy table', 'Wait for parent'],
    mall_benefits: ['Climate control', 'Music', 'Food', 'Potential romance', 'No supervision'],
    iconic: true,
    category: 'culture',
    funFact: 'The mall was essentially free all-day teen entertainment with minimal adult supervision.',
  },
  {
    id: 'photo_booth',
    exhibit: 'The Photo Booth',
    icon: '📷',
    matchText: 'For about a dollar, friends or couples squeezed behind a curtain and received a narrow strip containing four small photographs.',
    tagline: 'Wallet-Sized Memories',
    year: '1984',
    description: 'For about a dollar, friends or couples squeezed behind a curtain and received a narrow strip containing four small photographs. A warning light flashed before each exposure, providing just enough time to change expressions-or realize somebody had blinked. The resulting black-and-white pictures were grainy, imperfect, and completely unique. They were tucked into wallets, taped inside lockers, exchanged between sweethearts, or discovered years later in a box full of concert tickets and handwritten notes.',
    cost: '~$1',
    format: 'Strip of 4 black-and-white photos',
    quality: 'Grainy, imperfect, unique',
    fate: ['Wallet', 'Locker', 'Exchanged', 'Rediscovered years later'],
    iconic: true,
    category: 'entertainment',
    funFact: 'The warning light gave just enough time to change expressions-or realize someone blinked.',
  },
  {
    id: 'hickory_farms',
    exhibit: 'The Hickory Farms Kiosk',
    icon: '🧀',
    matchText: 'As the holidays approached, Hickory Farms displays appeared with gift boxes full of summer sausage, cheese, crackers, mustard, and candies.',
    tagline: 'Holiday Sausage Gifts',
    year: 'Holiday 1984',
    description: 'As the holidays approached, Hickory Farms displays appeared with gift boxes full of summer sausage, cheese, crackers, mustard, and candies. Employees offered tiny samples on toothpicks, allowing shoppers to assemble nearly an entire lunch by making several carefully spaced passes. The products were presented as elegant gifts even though the recipient usually opened them while standing at the kitchen counter. Nothing announced Christmas quite like a log of sausage wrapped in festive paper.',
    items: ['Summer sausage', 'Cheese', 'Crackers', 'Mustard', 'Candies'],
    sampling: 'Tiny toothpick samples',
    presentation: 'Elegant gift',
    reality: 'Kitchen counter snack',
    iconic: true,
    category: 'retail',
    funFact: 'Shoppers could assemble an entire lunch through multiple carefully-timed sample passes.',
  },
  {
    id: 'fountain_coin',
    exhibit: 'The Mall Fountain Coin',
    icon: '💰',
    matchText: 'Throwing a penny into the fountain was a small ritual performed by children, teenagers, and adults who knew perfectly well that the wish was unlikely to work.',
    tagline: 'Wish and Bad Luck Risk',
    year: '1984',
    description: 'Throwing a penny into the fountain was a small ritual performed by children, teenagers, and adults who knew perfectly well that the wish was unlikely to work. The coins accumulated beneath the water in shining copper patches and were periodically collected, often for charity or mall maintenance. Children also considered reaching into the water to retrieve one, until a parent explained that stealing somebody else\'s wish would probably bring extremely bad luck.',
    ritual: 'Throw penny, make wish',
    belief_level: 'Low but persistent',
    retrieval: 'Extremely bad luck',
    collection: 'Charity or mall maintenance',
    iconic: true,
    category: 'culture',
    funFact: 'Children learned that stealing someone else\'s wish would bring extremely bad luck.',
  },
  {
    id: 'listening_station',
    exhibit: 'The Record-Store Listening Station',
    icon: '🎧',
    matchText: 'A shopper wanting to hear an album might ask the clerk to play it over the store system or use whatever supervised listening setup the shop provided.',
    tagline: 'Supervised Music Preview',
    year: '1984',
    description: 'A shopper wanting to hear an album might ask the clerk to play it over the store system or use whatever supervised listening setup the shop provided. Headphones were usually large, heavily used, and attached firmly enough to discourage theft. Customers listened to part of one song while a clerk watched closely enough to ensure the experience did not become a free private concert. Listening too long without purchasing anything could produce a stare powerful enough to end the demonstration.',
    equipment: ['Large headphones', 'Heavily used', 'Anti-theft tethered'],
    clerk_role: 'Watchful overseer',
    risk: 'Power stare if too long',
    iconic: true,
    category: 'retail',
    funFact: 'A clerk\'s stare could end your listening session if you took too long without buying.',
  },
  {
    id: 'security_guard',
    exhibit: 'The Mall Security Guard',
    icon: '👮',
    matchText: 'The 1984 mall guard usually patrolled on foot, carrying a radio and watching for shoplifters, smoking teenagers, runaway children, fountain climbers, and arcade disputes.',
    tagline: 'Keeper of Mall Order',
    year: '1984',
    description: 'The 1984 mall guard usually patrolled on foot, carrying a radio and watching for shoplifters, smoking teenagers, runaway children, fountain climbers, and arcade disputes. Some larger properties used small three-wheeled electric carts, but most guards relied on comfortable shoes and professional suspicion. The guard\'s greatest challenge was distinguishing dangerous conduct from ordinary teenage boredom. Most confrontations ended with the deeply serious sentence, "Either buy something or move along."',
    patrols: 'On foot or electric cart',
    watches_for: ['Shoplifters', 'Smoking teens', 'Runaway kids', 'Fountain climbers', 'Arcade fights'],
    challenge: 'Teen boredom vs. danger',
    catchphrase: '"Either buy something or move along"',
    iconic: true,
    category: 'culture',
    funFact: 'The guard\'s greatest challenge was distinguishing teenage boredom from actual danger.',
  },
  {
    id: 'christmas_decorations',
    exhibit: 'The Christmas Decorations',
    icon: '🎄',
    matchText: 'By November, the mall became a brightly lit indoor winter village.',
    tagline: 'Holiday Transformation',
    year: 'November-January',
    description: 'By November, the mall became a brightly lit indoor winter village. Garlands hung from railings, enormous ornaments floated over the fountain, and a giant tree appeared in the central court. Children waited to meet Santa while parents purchased overpriced photograph packages. Department-store windows became elaborate holiday displays, and recorded Christmas music repeated until every employee could identify a song from its first half-second. When the decorations disappeared in January, the mall suddenly looked strangely empty.',
    decorations: ['Garlands', 'Enormous ornaments', 'Giant tree'],
    display: 'Winter village theme',
    music: 'Recorded Christmas repeats',
    removal_impact: 'Mall feels empty',
    iconic: true,
    category: 'holiday',
    funFact: 'When decorations were removed in January, the mall suddenly looked strangely empty.',
  },
  {
    id: 'directory_board',
    exhibit: 'The Mall Directory Board',
    icon: '📋',
    matchText: 'Before digital touchscreens, store names were displayed on a large illuminated board using plastic letters pushed into narrow grooves.',
    tagline: 'Slightly Crooked Retail',
    year: '1984',
    description: 'Before digital touchscreens, store names were displayed on a large illuminated board using plastic letters pushed into narrow grooves. New tenants were added by hand, closed stores were removed, and at least one word always appeared slightly crooked. The directory might list "Ladies\' Apparel," "Records & Tapes," "Tobacco," and "Typewriter Repair" as perfectly normal retail categories. A blank space usually indicated either an exciting store coming soon or a business that had vanished overnight.',
    technology: 'Plastic letters in grooves',
    characteristic: 'One word always crooked',
    categories: ['Ladies\' Apparel', 'Records & Tapes', 'Tobacco', 'Typewriter Repair'],
    blank_space_meaning: 'Coming soon OR vanished',
    iconic: true,
    category: 'retail',
    funFact: 'At least one word was always slightly crooked on the directory board.',
  },
  {
    id: 'pretzel_stand',
    exhibit: 'The Pretzel Stand',
    icon: '🥨',
    matchText: 'The pretzel counter announced itself through smell long before it came into view.',
    tagline: 'Butter and Salt Addiction',
    year: '1984',
    description: 'The pretzel counter announced itself through smell long before it came into view. Hot dough, melted butter, coarse salt, cinnamon, and warm cheese dip drifted several storefronts in every direction. The pretzel was handed over in a paper sleeve that immediately became translucent with butter. It could be eaten while walking, shopping, or waiting for a ride, making it one of the mall\'s most practical foods-provided the customer did not mind wearing some of the salt.',
    smell: 'Dough, butter, salt, cinnamon, cheese',
    range: 'Several storefronts',
    format: 'Paper sleeve',
    condition: 'Translucent with butter',
    advantage: 'Portable',
    drawback: 'Wear salt',
    iconic: true,
    category: 'dining',
    funFact: 'The pretzel sleeve immediately became translucent with butter.',
  },
  {
    id: 'mall_bench',
    exhibit: 'The Mall Bench',
    icon: '🪑',
    matchText: 'Every mall contained benches occupied by tired parents, elderly walkers, bored children, and husbands buried beneath shopping bags.',
    tagline: 'The Waiting Room',
    year: '1984',
    description: 'Every mall contained benches occupied by tired parents, elderly walkers, bored children, and husbands buried beneath shopping bags. The bench served as a waiting room for every store nobody wished to enter. From this position, a person could observe fashions, overhear arguments, watch children, and announce every ten minutes that it was "probably time to go." Anyone saying this was routinely informed that there was only one more store.',
    occupants: ['Tired parents', 'Elderly walkers', 'Bored children', 'Husbands with bags'],
    function: 'Waiting room',
    observations: ['Fashion watching', 'Argument overhearing', 'Child monitoring'],
    refrain: '"Probably time to go"',
    response: '"Only one more store"',
    iconic: true,
    category: 'culture',
    funFact: 'Husbands on benches were always informed "there\'s only one more store."',
  },
  {
    id: 'greeting_card_store',
    exhibit: 'The Greeting Card Store',
    icon: '🎴',
    matchText: 'Hallmark and other card shops carried birthday cards, anniversary cards, graduation cards, wrapping paper, ornaments, figurines, stationery, and small gifts selected when the shopper had no better idea.',
    tagline: 'Last-Minute Gift Solution',
    year: '1984',
    description: 'Hallmark and other card shops carried birthday cards, anniversary cards, graduation cards, wrapping paper, ornaments, figurines, stationery, and small gifts selected when the shopper had no better idea. Customers stood silently opening card after card, searching for one that was funny without being insulting or sentimental without becoming embarrassing. The store was rarely entered casually. Everyone inside had a mission, a deadline, and at least one relative who was difficult to shop for.',
    products: ['Birthday cards', 'Anniversary cards', 'Graduation cards', 'Wrapping paper', 'Ornaments', 'Figurines', 'Stationery'],
    customer_behavior: 'Silent card selection',
    selection_criteria: 'Funny but not insulting; sentimental but not embarrassing',
    motivation: ['Mission', 'Deadline', 'Difficult relative'],
    iconic: true,
    category: 'retail',
    funFact: 'Customers silently searched for cards that were funny without being insulting.',
  },
  {
    id: 'parking_lot',
    exhibit: 'The Mall Parking Lot',
    icon: '🅿️',
    matchText: 'The mall parking lot was a vast field of station wagons, sedans, vans, and families trying to remember where they had parked.',
    tagline: 'The Final Frontier',
    year: '1984',
    description: 'The mall parking lot was a vast field of station wagons, sedans, vans, and families trying to remember where they had parked. During the holidays, drivers followed shoppers carrying bags in hopes of inheriting their space. Parents identified entrances by anchor stores-"We came in by Sears"-only to discover the mall contained more than one Sears doorway. After twenty minutes of searching, somebody usually claimed the car had been stolen just before it appeared two rows away.',
    vehicles: ['Station wagons', 'Sedans', 'Vans'],
    challenge: 'Remember where you parked',
    strategy: 'Follow shoppers with bags',
    identification: ['By anchor store name', 'By forgotten details'],
    panic: 'Car stolen... found two rows away',
    iconic: true,
    category: 'culture',
    funFact: 'After 20 minutes of searching, the car miraculously appeared two rows away.',
  },
];

const VIEWED_EXHIBITS = new Set();
const EXHIBIT_VIEW_COUNTS = {};

export function findMallCultureEntry(adText) {
  return ENTRIES.find(e => e.matchText === adText) || null;
}

export function trackMallCultureView(entryId) {
  VIEWED_EXHIBITS.add(entryId);
  EXHIBIT_VIEW_COUNTS[entryId] = (EXHIBIT_VIEW_COUNTS[entryId] || 0) + 1;
  const unlocked = [];

  if (VIEWED_EXHIBITS.size >= 5) unlocked.push('mall_culture_fan');
  if (VIEWED_EXHIBITS.size >= 15) unlocked.push('mall_culture_enthusiast');
  if (VIEWED_EXHIBITS.size >= 25) unlocked.push('mall_culture_historian');

  return unlocked;
}

export function getMallCultureViewCount() {
  return VIEWED_EXHIBITS.size;
}