// Seattle Mariners Broadcast - 1984
// Radio: Dave Niehaus & Ken Wilson (KIRO) / TV: Dave Henderson & Ron Fairly (KING)
// Kingdome - home of the Mariners since 1977
// All stats cutoff: end of 1983 season

export function pickMarinersLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickMarinersPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Jack Perconte": {
    lines: [
      "Jack Perconte's full name is John Patrick Perconte.",
      "Jack Perconte was born in Joliet, Illinois.",
      "Perconte is a left-handed hitter who throws right-handed.",
      "Jack Perconte played college baseball at Murray State University.",
      "The Los Angeles Dodgers selected Perconte in the 16th round of the 1976 amateur draft.",
      "Perconte made his major-league debut with Los Angeles during the 1980 season.",
      "Jack Perconte appeared briefly for the Dodgers in both 1980 and 1981.",
      "Perconte was included in the 1981 trade that sent Rick Sutcliffe from Los Angeles to Cleveland.",
      "Jack Perconte played primarily at second base in the Cleveland organization.",
      "Perconte appeared in 48 games for Cleveland during the 1982 season.",
      "Jack Perconte received only a brief major-league opportunity in 1983.",
      "Perconte appeared in 14 games and collected seven hits in 26 at-bats for Cleveland.",
      "Jack Perconte batted .269 and recorded a .387 on-base percentage during that limited 1983 opportunity.",
      "Perconte stole three bases without being caught in 1983.",
      "Seattle acquired Perconte and Gorman Thomas from Cleveland during December 1983.",
      "The Mariners sent second baseman Tony Bernazard to Cleveland in the transaction.",
      "Perconte's game is built more around contact, speed and reaching base than home-run power.",
      "Jack Perconte can use his speed to beat out an infield grounder or move from first to third on a single.",
      "Perconte gives Seattle a left-handed option at the top of the batting order.",
      "Jack Perconte enters 1984 with an opportunity to establish himself as an everyday major-league second baseman.",
    ],
  },
  "Phil Bradley": {
    lines: [
      "Phil Bradley's full name is Philip Poole Bradley.",
      "Phil Bradley was born in Bloomington, Indiana.",
      "Bradley was an outstanding two-sport athlete at the University of Missouri.",
      "Phil Bradley became Missouri's starting quarterback in addition to playing college baseball.",
      "Bradley was named the Big Eight Conference's Offensive Player of the Year three times.",
      "Phil Bradley accumulated more than 6,000 yards of total offense during his college football career.",
      "Seattle selected Bradley in the third round of the 1981 amateur baseball draft.",
      "Bradley chose professional baseball rather than pursuing a football career.",
      "Phil Bradley developed as an outfielder in the Mariners' farm system.",
      "Bradley bats and throws right-handed.",
      "Phil Bradley made his major-league debut on September 2, 1983.",
      "Bradley appeared in 23 games during his first major-league trial.",
      "Phil Bradley collected 18 hits in 67 at-bats.",
      "Bradley batted .269 with two doubles and five RBI.",
      "Phil Bradley scored eight runs and drew eight walks.",
      "Bradley stole three bases during his September opportunity.",
      "Phil Bradley's football background is apparent in his speed, strength and overall athleticism.",
      "Bradley can run, throw and cover considerable territory in the outfield.",
      "Phil Bradley enters 1984 with fewer than 70 major-league at-bats.",
      "Bradley's athletic ability is established, but he is still learning the tendencies of American League pitchers.",
      "Seattle is giving Bradley the opportunity to develop into a regular left fielder near the top of the lineup.",
    ],
  },
  "Alvin Davis": {
    lines: [
      "Alvin Davis' full name is Alvin Glenn Davis.",
      "Alvin Davis was born in Riverside, California.",
      "Davis is a left-handed hitter who throws right-handed.",
      "Alvin Davis played college baseball at Arizona State University.",
      "Oakland selected Davis in the sixth round of the 1981 draft, but he did not sign.",
      "Seattle selected Alvin Davis in the sixth round of the 1982 amateur draft.",
      "Davis enjoyed an outstanding final college season at Arizona State.",
      "Alvin Davis batted .351 with 13 home runs and 91 RBI during the 1982 college season.",
      "Davis drew 87 walks and recorded a .523 on-base percentage that year.",
      "Alvin Davis advanced quickly through Seattle's minor-league system.",
      "Davis spent the 1983 season with Double-A Chattanooga.",
      "Alvin Davis appeared in 131 games for Chattanooga.",
      "Davis batted .296 with 125 hits.",
      "Alvin Davis collected 24 doubles, three triples and 18 home runs.",
      "Davis drove in 83 runs during the 1983 season.",
      "Alvin Davis drew an extraordinary 120 walks while striking out only 57 times.",
      "Davis recorded a .443 on-base percentage and a .495 slugging percentage.",
      "Alvin Davis has not yet appeared in a major-league game entering 1984.",
      "Davis combines developing power with unusually advanced strike-zone judgment.",
      "Alvin Davis is willing to accept a walk rather than chase a pitcher's pitch.",
      "Davis can drive the ball to the opposite field as well as pull it.",
      "Seattle is asking a player with no major-league experience to assume an important position in the middle of the lineup.",
    ],
  },
  "Ken Phelps": {
    lines: [
      "Ken Phelps' full name is Kenneth Allan Phelps.",
      "Ken Phelps was born in Seattle, Washington.",
      "Phelps attended Ingraham High School in Seattle.",
      "Ken Phelps continued his baseball career at Washington State, Mesa Community College and Arizona State.",
      "Phelps was originally drafted by the Atlanta Braves while still in high school.",
      "Ken Phelps eventually began his professional career in the Kansas City organization.",
      "Phelps later moved through the Montreal organization.",
      "Seattle purchased Ken Phelps' contract from Montreal shortly before the 1983 season.",
      "The transaction brought the Seattle native back to his hometown organization.",
      "Ken Phelps bats left-handed and throws right-handed.",
      "Phelps can play first base but is particularly suited to the designated-hitter role.",
      "Ken Phelps split the 1983 season between Triple-A and the major leagues.",
      "Phelps appeared in 50 games for Seattle.",
      "Ken Phelps collected 30 hits in 127 at-bats.",
      "Phelps hit four doubles, one triple and seven home runs.",
      "Ken Phelps drove in 16 runs and drew 13 walks.",
      "Phelps batted .236 with a .301 on-base percentage and a .449 slugging percentage.",
      "Seven of Phelps' 30 major-league hits left the ballpark.",
      "Ken Phelps' power production is more impressive than his batting average suggests.",
      "Phelps has displayed a willingness to work deep counts throughout his minor-league career.",
      "Ken Phelps gives Seattle a left-handed power bat behind Alvin Davis.",
      "The designated-hitter role allows Phelps to concentrate almost entirely on reaching base and driving the baseball.",
    ],
  },
  "Dave Henderson": {
    lines: [
      "Dave Henderson's full name is David Lee Henderson.",
      "Dave Henderson is commonly known by the nickname \"Hendu.\"",
      "Henderson was born in Merced, California.",
      "Dave Henderson attended Dos Palos High School in California.",
      "Seattle selected Henderson in the first round of the 1977 amateur draft.",
      "Henderson was the 26th overall selection.",
      "Dave Henderson was the first player ever selected in an amateur draft by the Mariners franchise.",
      "Henderson developed entirely within Seattle's organization.",
      "Dave Henderson made his major-league debut on April 9, 1981.",
      "Henderson gradually established himself as Seattle's regular center fielder.",
      "Dave Henderson bats and throws right-handed.",
      "Henderson appeared in 137 games during the 1983 season.",
      "Dave Henderson batted .269 with 130 hits.",
      "Henderson recorded 24 doubles and five triples.",
      "Dave Henderson hit 17 home runs and drove in 55 runs.",
      "Henderson scored 50 runs and stole nine bases.",
      "Dave Henderson recorded a .444 slugging percentage in 1983.",
      "Henderson combines power with enough speed to take an extra base.",
      "Dave Henderson has a strong throwing arm from center field.",
      "Henderson's aggressive style can produce extra-base hits, although it can also lead to strikeouts.",
      "Dave Henderson remains one of the relatively few Seattle regulars developed entirely within the organization.",
      "Hendu enters 1984 as a young center fielder whose power continues to develop.",
    ],
  },
  "Al Cowens": {
    lines: [
      "Al Cowens' full name is Alfred Edward Cowens Jr.",
      "Al Cowens was born in Los Angeles, California.",
      "Cowens developed in the Kansas City Royals organization.",
      "Al Cowens made his major-league debut with Kansas City during the 1974 season.",
      "Cowens became the Royals' regular right fielder.",
      "Al Cowens enjoyed an exceptional season in 1977.",
      "Cowens batted .312 with 23 home runs and 112 RBI.",
      "Al Cowens scored 98 runs and collected 189 hits in 1977.",
      "Cowens won an American League Gold Glove Award that season.",
      "Al Cowens finished second to Rod Carew in the 1977 American League Most Valuable Player voting.",
      "Cowens later played for California and Detroit.",
      "Seattle purchased Al Cowens' contract from Detroit shortly before the 1982 season.",
      "Cowens brought the Mariners a veteran with experience in a pennant race.",
      "Al Cowens appeared in 110 games during the 1983 season.",
      "Cowens collected 73 hits, including 19 doubles and two triples.",
      "Al Cowens hit seven home runs and drove in 35 runs.",
      "Cowens scored 39 times and stole 10 bases.",
      "Al Cowens batted .205 with a .255 on-base percentage in 1983.",
      "Cowens' 1983 offensive numbers were far below the standards of his best Kansas City seasons.",
      "Al Cowens still supplies experience, an accurate throwing arm and dependable outfield instincts.",
      "Cowens can play either corner-outfield position.",
      "A return to his previous line-drive form would add needed balance to Seattle's young lineup.",
    ],
  },
  "Jim Presley": {
    lines: [
      "Jim Presley's full name is James Arthur Presley.",
      "Jim Presley was born in Pensacola, Florida.",
      "Presley attended Escambia High School in Pensacola.",
      "Seattle selected Jim Presley in the fourth round of the 1979 amateur draft.",
      "Presley developed primarily as a third baseman.",
      "Jim Presley bats and throws right-handed.",
      "Presley spent the 1983 season with Double-A Chattanooga.",
      "Jim Presley appeared in 131 games for Chattanooga.",
      "Presley collected 122 hits in 461 at-bats.",
      "Jim Presley recorded 31 doubles and five triples.",
      "Presley hit 14 home runs and drove in 90 runs.",
      "Jim Presley scored 72 times and stole nine bases.",
      "Presley drew 56 walks but also struck out 101 times.",
      "Jim Presley batted .265 with a .341 on-base percentage and a .445 slugging percentage.",
      "Presley has not yet appeared in a major-league game entering 1984.",
      "Jim Presley has shown enough power to drive the ball into either outfield gap.",
      "Presley's 90 RBI demonstrate his ability to produce runs in the middle of a minor-league lineup.",
      "Jim Presley is still developing his strike-zone judgment.",
      "Presley must also adjust to the speed of major-league bunts and sharply hit balls at third base.",
      "Seattle is giving Presley an opportunity to make the difficult jump from Double-A to a major-league starting job.",
    ],
  },
  "Bob Kearney": {
    lines: [
      "Bob Kearney's full name is Robert Henry Kearney.",
      "Bob Kearney was born in San Antonio, Texas.",
      "Kearney played college baseball at the University of Texas.",
      "San Francisco selected Bob Kearney in the 14th round of the 1977 amateur draft.",
      "Kearney made his major-league debut with the Giants during the 1979 season.",
      "Bob Kearney later joined the Oakland Athletics.",
      "Kearney received his first extended major-league opportunity during the 1983 season.",
      "Bob Kearney appeared in 108 games for Oakland.",
      "Kearney collected 76 hits in 298 at-bats.",
      "Bob Kearney recorded 11 doubles and eight home runs.",
      "Kearney drove in 32 runs and scored 28 times.",
      "Bob Kearney batted .255 with a .312 on-base percentage and a .372 slugging percentage.",
      "Kearney was selected to the 1983 Topps Major League All-Star Rookie team.",
      "Bob Kearney established himself primarily through defense and his handling of pitchers.",
      "Seattle acquired Kearney and pitcher Dave Beard from Oakland in November 1983.",
      "The Mariners sent Bill Caudill and Darrel Akerfelds to the Athletics.",
      "Kearney possesses a strong throwing arm behind the plate.",
      "Bob Kearney is comfortable working with pitchers who rely on breaking balls and changing speeds.",
      "Kearney gives Seattle a catcher coming directly from his first full major-league season.",
      "His defense will be particularly important while Seattle introduces several inexperienced pitchers.",
    ],
  },
  "Spike Owen": {
    lines: [
      "Spike Owen's full name is Spike Dee Owen.",
      "Spike Owen was born in Cleburne, Texas.",
      "Owen is a switch-hitter who throws right-handed.",
      "Seattle selected Spike Owen with the sixth overall pick of the 1982 amateur draft.",
      "Owen advanced through the minor leagues rapidly after signing.",
      "Spike Owen made his major-league debut on June 25, 1983.",
      "Owen led off his first major-league game.",
      "Spike Owen collected his first major-league hit with a single against Toronto pitcher Jim Gott.",
      "Seattle ended an eight-game losing streak during Owen's debut.",
      "Spike Owen appeared in 80 games during the 1983 season.",
      "Owen collected 60 hits in 306 at-bats.",
      "Spike Owen recorded 11 doubles and three triples.",
      "Owen hit two home runs and drove in 21 runs.",
      "Spike Owen scored 36 times and stole 10 bases.",
      "Owen drew 24 walks and struck out 44 times.",
      "Spike Owen batted .196 with a .257 on-base percentage.",
      "Owen's batting average reflects the difficulty of reaching the majors only one year after being drafted.",
      "Spike Owen's switch-hitting allows him to remain in the lineup against either right-handed or left-handed pitching.",
      "Owen is valued for his range, hands and throwing arm at shortstop.",
      "Spike Owen is still learning when to make the difficult play and when to hold the baseball.",
      "Seattle enters 1984 with a very young shortstop occupying one of the game's most demanding defensive positions.",
    ],
  },
  "Barry Bonnell": {
    lines: [
      "Barry Bonnell's full name is Robert Barry Bonnell.",
      "Barry Bonnell was born in Milford, Ohio.",
      "Bonnell played both baseball and basketball at Ohio State University.",
      "Barry Bonnell began his major-league career with the Atlanta Braves.",
      "Bonnell made his major-league debut during the 1977 season.",
      "Barry Bonnell later joined the Toronto Blue Jays.",
      "Bonnell can play all three outfield positions.",
      "Barry Bonnell enjoyed one of the finest seasons of his career in 1983.",
      "Bonnell appeared in 121 games for Toronto.",
      "Barry Bonnell batted .318 with 120 hits.",
      "Bonnell collected 21 doubles, three triples and 10 home runs.",
      "Barry Bonnell drove in 54 runs and scored 49 times.",
      "Bonnell stole 10 bases and drew 33 walks.",
      "Barry Bonnell recorded a .369 on-base percentage and a .469 slugging percentage.",
      "Seattle acquired Bonnell from Toronto during December 1983.",
      "The Mariners sent pitcher Bryan Clark to the Blue Jays.",
      "Bonnell gives Seattle an experienced right-handed hitter from the bench.",
      "Barry Bonnell can start at any outfield position without forcing a major defensive rearrangement.",
      "His .318 average in 1983 makes him more than a conventional reserve.",
    ],
  },
  "Steve Henderson": {
    lines: [
      "Steve Henderson's full name is Steven Curtis Henderson.",
      "Steve Henderson was born in Houston, Texas.",
      "Henderson began his professional career in the Cincinnati organization.",
      "Steve Henderson was one of the principal players sent to the New York Mets in the 1977 trade for Tom Seaver.",
      "Henderson reached the major leagues shortly after that transaction.",
      "Steve Henderson immediately became the Mets' regular left fielder.",
      "Henderson later played for the Chicago Cubs.",
      "Seattle acquired Steve Henderson from Chicago following the 1982 season.",
      "Steve Henderson is not related to teammate Dave Henderson.",
      "The two Hendersons nevertheless give Seattle announcers a natural opportunity for clarification.",
      "Steve Henderson appeared in 121 games for Seattle during the 1983 season.",
      "Henderson batted .294 with 128 hits.",
      "Steve Henderson collected 32 doubles, three triples and 10 home runs.",
      "Henderson drove in 54 runs and scored 50 times.",
      "Steve Henderson stole 10 bases and drew 44 walks.",
      "Henderson recorded a .356 on-base percentage and a .450 slugging percentage.",
      "Steve Henderson became a free agent following the 1983 season.",
      "Seattle re-signed him in January 1984.",
      "Henderson gives the Mariners a veteran right-handed hitter who can play either corner-outfield position.",
      "Steve Henderson's combination of contact hitting and extra-base power makes him useful as a pinch-hitter or occasional starter.",
    ],
  },
  "Gorman Thomas": {
    lines: [
      "Gorman Thomas' full name is James Gorman Thomas III.",
      "Thomas is commonly known by the nickname \"Stormin' Gorman.\"",
      "Gorman Thomas was born in Charleston, South Carolina.",
      "Thomas was selected by the Seattle Pilots during the 1969 amateur draft.",
      "Gorman Thomas was the only first-round draft selection in the Pilots' brief history.",
      "Thomas remained with the organization when the Pilots moved to Milwaukee.",
      "Gorman Thomas developed into one of the American League's most dangerous home-run hitters.",
      "Thomas led the American League with 45 home runs during the 1979 season.",
      "Gorman Thomas also drove in 123 runs in 1979.",
      "Thomas tied for the American League lead with 39 home runs in 1982.",
      "Gorman Thomas is known for tremendous power, a strong throwing arm and frequent strikeouts.",
      "Thomas is capable of playing center field despite his thick, powerful build.",
      "Milwaukee traded Gorman Thomas to Cleveland during June 1983.",
      "Thomas appeared in 46 games for Milwaukee and hit five home runs before the trade.",
      "Gorman Thomas played 106 games for Cleveland.",
      "Thomas hit 17 home runs and drove in 51 runs for the Indians.",
      "Gorman Thomas drew 57 walks during his time with Cleveland.",
      "Cleveland traded Thomas and Jack Perconte to Seattle in December 1983.",
      "The Mariners sent Tony Bernazard to Cleveland.",
      "Thomas can serve as an outfielder, designated hitter or right-handed pinch-hitter.",
      "Few reserve players possess Gorman Thomas' proven ability to change a game with one swing.",
      "Seattle hopes a change of surroundings will help Stormin' Gorman rediscover his best Milwaukee form.",
    ],
  },
  "Orlando Mercado": {
    lines: [
      "Orlando Mercado's full name is Orlando Mercado Rodriguez.",
      "Mercado was born in Arecibo, Puerto Rico.",
      "Orlando Mercado is a right-handed catcher.",
      "Mercado developed within the Seattle organization.",
      "Orlando Mercado made his major-league debut on September 13, 1982.",
      "Mercado appeared in nine games during his first major-league trial.",
      "Orlando Mercado collected two hits in 17 at-bats.",
      "One of Mercado's two hits was a home run.",
      "Orlando Mercado drove in six runs during that brief 1982 opportunity.",
      "Mercado received a much longer major-league look during the 1983 season.",
      "Orlando Mercado appeared in 66 games.",
      "Mercado collected 35 hits in 178 at-bats.",
      "Orlando Mercado recorded 11 doubles and two triples.",
      "Mercado hit one home run and drove in 16 runs.",
      "Orlando Mercado batted .197 with a .256 on-base percentage.",
      "Mercado's principal responsibility is receiving and throwing rather than providing power.",
      "Orlando Mercado gives Bob Kearney a reserve who already knows many of Seattle's pitchers.",
      "Mercado can enter for defense or start when Kearney requires a day away from catching.",
    ],
  },
  "Domingo Ramos": {
    lines: [
      "Domingo Ramos' full name is Domingo Antonio Ramos.",
      "Ramos was born in Santiago de los Caballeros in the Dominican Republic.",
      "Domingo Ramos signed with the New York Yankees organization in 1975.",
      "Ramos made his major-league debut with the Yankees on September 8, 1978.",
      "Domingo Ramos was included in the large trade that sent Sparky Lyle from New York to Texas.",
      "Ramos later moved through the Toronto organization.",
      "Seattle selected Domingo Ramos from Toronto in the 1981 Rule 5 draft.",
      "Ramos appeared at all four infield positions for Seattle during the 1982 season.",
      "Domingo Ramos played 53 games during the 1983 season.",
      "Ramos collected 36 hits in 127 at-bats.",
      "Domingo Ramos batted .283.",
      "Ramos recorded four doubles and two home runs.",
      "Domingo Ramos drove in 10 runs and scored 14 times.",
      "Ramos drew seven walks and stole three bases.",
      "Domingo Ramos recorded a .326 on-base percentage and a .362 slugging percentage.",
      "Ramos hit the first home run of his major-league career on April 17, 1983.",
      "Domingo Ramos recorded his first career stolen base two days later.",
      "Ramos can replace either middle infielder and can also fill in at third base.",
      "Domingo Ramos' versatility allows Seattle to carry additional outfield and power specialists on the bench.",
    ],
  },
  "Mark Langston": {
    lines: [
      "Mark Langston's full name is Mark Edward Langston.",
      "Langston was born in San Diego, California.",
      "Mark Langston attended Buchser High School in Santa Clara.",
      "Langston played college baseball at San Jose State University.",
      "Seattle selected Mark Langston in the second round of the 1981 amateur draft.",
      "Langston is a tall, left-handed pitcher.",
      "Mark Langston developed rapidly in Seattle's farm system.",
      "Langston spent the 1983 season with Double-A Chattanooga.",
      "Mark Langston made 28 starts.",
      "Langston went 14-9 with a 3.59 ERA.",
      "Mark Langston threw 198 innings.",
      "Langston completed 10 games.",
      "Mark Langston struck out 142 hitters.",
      "Langston allowed 187 hits and only eight home runs.",
      "Mark Langston walked 102 hitters, demonstrating that control remains an important area of development.",
      "Langston has not yet appeared in a major-league game entering 1984.",
      "Mark Langston's fastball gives Seattle a power left-hander at the top of the rotation.",
      "Langston can overpower hitters when he gets ahead in the count.",
      "His challenge is avoiding long innings created by walks.",
      "Seattle is entrusting an important rotation position to a pitcher coming directly from Double-A.",
    ],
  },
  "Mike Moore": {
    lines: [
      "Mike Moore's full name is Michael Wayne Moore.",
      "Moore was born in Eakly, Oklahoma.",
      "Mike Moore played college baseball at Oral Roberts University.",
      "St. Louis selected Moore in the third round of the 1978 draft, but he did not sign.",
      "Seattle selected Mike Moore with the first overall pick of the 1981 amateur draft.",
      "Moore made his major-league debut on April 11, 1982.",
      "Mike Moore reached the majors less than one year after being drafted.",
      "Moore is a tall right-handed pitcher with a strong fastball.",
      "Mike Moore received extensive starting experience during his rookie season.",
      "Moore appeared in 22 games during the 1983 season.",
      "Mike Moore made 21 starts.",
      "Moore went 6-8 with a 4.71 ERA.",
      "Mike Moore worked 128 innings.",
      "Moore completed three games and recorded two shutouts.",
      "Mike Moore struck out 108 hitters.",
      "Moore allowed 130 hits and walked 60.",
      "Mike Moore surrendered only 10 home runs during the season.",
      "Moore's strikeout total demonstrates the quality of his raw pitches.",
      "Mike Moore is still learning how to conserve pitches and work deep into games.",
      "Seattle hopes greater consistency will allow Moore to fulfill the expectations attached to a first overall draft selection.",
    ],
  },
  "Jim Beattie": {
    lines: [
      "Jim Beattie's full name is James Louis Beattie.",
      "Beattie was born in Hampton, Virginia.",
      "Jim Beattie played college baseball at Dartmouth College.",
      "The New York Yankees selected Beattie during the 1975 amateur draft.",
      "Jim Beattie made his major-league debut with New York during the 1978 season.",
      "Beattie reached the majors in time to contribute to a championship team.",
      "Jim Beattie started Game Five of the 1978 World Series against Los Angeles.",
      "Beattie pitched a complete game as the Yankees won 12-2.",
      "That victory gave New York a three-games-to-two lead in the series.",
      "Jim Beattie later joined the Seattle rotation.",
      "Beattie appeared in 30 games during the 1983 season.",
      "Jim Beattie made 29 starts.",
      "Beattie went 10-15 with a 3.84 ERA.",
      "Jim Beattie threw 196 and two-thirds innings.",
      "Beattie completed eight games and recorded two shutouts.",
      "Jim Beattie struck out 132 hitters while walking 66.",
      "On September 27, 1983, Beattie pitched the first one-hitter in Mariners history.",
      "Jim Beattie defeated Kansas City 4-0 in that performance.",
      "A single by U.L. Washington accounted for the Royals' only hit.",
      "Beattie gives Seattle a veteran starter with both World Series and heavy-workload experience.",
      "Jim Beattie relies on changing speeds, location and keeping hitters from becoming comfortable.",
      "He remains capable of finishing a game when his command is sharp.",
    ],
  },
  "Matt Young": {
    lines: [
      "Matt Young's full name is Matthew John Young.",
      "Young was born in Pasadena, California.",
      "Matt Young attended Pasadena City College before transferring to UCLA.",
      "Boston selected Young during the 1978 draft, but he did not sign.",
      "Seattle selected Matt Young in the second round of the 1980 amateur draft.",
      "Young is a left-handed pitcher.",
      "Matt Young made his major-league debut during the 1983 season.",
      "Young immediately received a regular place in Seattle's rotation.",
      "Matt Young appeared in 33 games.",
      "Young made 32 starts.",
      "Matt Young went 11-15 with a 3.27 ERA.",
      "Young led the Mariners in victories.",
      "Matt Young also recorded the best ERA among Seattle's regular starting pitchers.",
      "Young threw 203 and two-thirds innings.",
      "Matt Young completed five games and recorded two shutouts.",
      "Young allowed only 178 hits.",
      "Matt Young struck out 130 hitters and walked 79.",
      "Young recorded a 1.26 WHIP during his rookie season.",
      "Matt Young represented Seattle in the 1983 All-Star Game.",
      "Young pitched a scoreless eighth inning against Johnny Bench, Darrell Evans and Pedro Guerrero.",
      "Young's rookie performance gives Seattle a proven left-handed starter to accompany the inexperienced Mark Langston.",
      "Matt Young enters 1984 attempting to demonstrate that his strong first season was not a temporary success.",
    ],
  },
  "Mike Stanton": {
    lines: [
      "Mike Stanton's full name is Michael Thomas Stanton.",
      "This Mike Stanton is a right-handed pitcher and should not be confused with any later player carrying the same name.",
      "Stanton was born in St. Louis, Missouri.",
      "Mike Stanton was selected several times in amateur drafts before beginning his professional career.",
      "Houston selected Stanton in the first round of the January 1973 secondary draft.",
      "Mike Stanton made his major-league debut with Houston during the 1975 season.",
      "Stanton later pitched for Cleveland.",
      "Mike Stanton developed primarily into a relief pitcher.",
      "Stanton joined the Mariners before the 1983 season.",
      "Mike Stanton appeared in 50 games for Seattle.",
      "Stanton went 2-3 with a 3.32 ERA.",
      "Mike Stanton recorded seven saves.",
      "Stanton worked 65 innings.",
      "Mike Stanton allowed 65 hits and only three home runs.",
      "Stanton struck out 47 hitters and walked 28.",
      "Mike Stanton finished 23 games during the 1983 season.",
      "Stanton is capable of entering before the ninth inning rather than waiting for a clean save situation.",
      "Mike Stanton's role as closer reflects Seattle's preference for an experienced reliever in late innings.",
      "Stanton relies upon movement and location rather than simply trying to overpower every hitter.",
    ],
  },
  "Dave Beard": {
    lines: [
      "Dave Beard's full name is Charles David Beard.",
      "Beard is a right-handed pitcher.",
      "Dave Beard began his major-league career with the Oakland Athletics.",
      "Beard developed into an important member of Oakland's bullpen.",
      "Dave Beard enjoyed a productive season in 1982.",
      "Beard went 10-9 with a 3.44 ERA.",
      "Dave Beard recorded 11 saves during the 1982 season.",
      "Beard appeared in 43 games for Oakland during the 1983 season.",
      "Dave Beard went 5-5 with a 5.61 ERA.",
      "Beard worked 61 innings.",
      "Dave Beard recorded 10 saves and finished 26 games.",
      "Beard struck out 40 hitters but walked 36.",
      "Dave Beard allowed eight home runs during the 1983 season.",
      "Seattle acquired Beard and catcher Bob Kearney from Oakland in November 1983.",
      "The Mariners sent Bill Caudill and Darrel Akerfelds to the Athletics.",
      "Beard brings previous closing experience to Seattle's bullpen.",
      "Dave Beard can protect a lead when Mike Stanton is unavailable.",
      "Improved control will be important if Beard is to regain his 1982 effectiveness.",
    ],
  },
  "Paul Mirabella": {
    lines: [
      "Paul Mirabella's full name is Paul Thomas Mirabella.",
      "Mirabella is a left-handed pitcher.",
      "Paul Mirabella began his major-league career with the Texas Rangers.",
      "Mirabella later pitched for the New York Yankees, Toronto Blue Jays and Baltimore Orioles.",
      "Paul Mirabella was included in the large trade that sent Sparky Lyle from the Yankees to Texas.",
      "That transaction also involved future Seattle infielder Domingo Ramos.",
      "Mirabella has worked as both a starting pitcher and reliever.",
      "Paul Mirabella's starting experience allows him to remain in a game for several innings.",
      "Mirabella made three major-league appearances for Baltimore during the 1983 season.",
      "Paul Mirabella made two starts.",
      "Mirabella worked 9 and two-thirds innings and posted a 5.59 ERA.",
      "Paul Mirabella allowed nine hits, walked seven and struck out four.",
      "Mirabella gives Seattle a veteran left-handed option in a mostly right-handed bullpen.",
      "Paul Mirabella can be used against a dangerous left-handed hitter or as a long reliever.",
      "His ability to change roles provides insurance behind a young starting rotation.",
    ],
  },
  "Edwin Nunez": {
    lines: [
      "Edwin Nunez was born in Humacao, Puerto Rico.",
      "Nunez is a right-handed pitcher.",
      "Seattle signed Edwin Nunez as an undrafted amateur free agent in 1979.",
      "Nunez advanced through the organization at an unusually young age.",
      "Edwin Nunez made his major-league debut on April 7, 1982.",
      "Nunez was only 18 years and 315 days old.",
      "Edwin Nunez was one of the youngest players in the major leagues.",
      "Nunez appeared in eight games during the 1982 season.",
      "Edwin Nunez made five starts and went 1-2 with a 4.58 ERA.",
      "Nunez struck out 27 hitters in 35 and a third innings.",
      "Edwin Nunez appeared in 14 games during the 1983 season.",
      "Nunez again made five starts.",
      "Edwin Nunez went 0-4 with a 4.38 ERA.",
      "Nunez worked 37 innings and recorded three saves.",
      "Edwin Nunez struck out 35 hitters.",
      "Nunez allowed 40 hits and walked 22.",
      "Edwin Nunez enters 1984 at only 20 years old.",
      "Nunez's strikeout rate demonstrates a strong arm.",
      "Seattle can use him for short relief, extended relief or an emergency start.",
      "Control and consistent pitch selection remain the principal challenges for the young right-hander.",
    ],
  },
  "Bob Stoddard": {
    lines: [
      "Bob Stoddard's full name is Robert Lyle Stoddard.",
      "Stoddard was born in San Jose, California.",
      "Bob Stoddard is a right-handed pitcher.",
      "Stoddard began his major-league career with the Seattle Mariners.",
      "Bob Stoddard received extensive starting work during the 1983 season.",
      "Stoddard appeared in 35 games.",
      "Bob Stoddard made 23 starts.",
      "Stoddard went 9-17 with a 4.41 ERA.",
      "Bob Stoddard worked 175 and two-thirds innings.",
      "Stoddard completed four games.",
      "Bob Stoddard recorded two shutouts.",
      "Stoddard also earned one relief save.",
      "Bob Stoddard allowed 182 hits and struck out 87 hitters.",
      "Stoddard walked 58.",
      "Bob Stoddard surrendered 29 home runs during the 1983 season.",
      "Stoddard's extensive starting experience makes him a natural long-relief option on this roster.",
      "Bob Stoddard can enter early when a starter is removed and work through several innings.",
      "Stoddard can also make an emergency start during periods of injury or heavy scheduling.",
      "Keeping the ball inside the park will be important after his high home-run total in 1983.",
      "Bob Stoddard gives Seattle a bullpen pitcher already accustomed to carrying a starter's workload.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive - base hit.\"",
    "\"Long drive to left field - way back - gone. Home run!\"",
    "\"Ground ball to short - over to first - in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This is a young ballclub with some real talent - the Mariners are building something here.\"",
    "\"Seattle baseball is alive and well - the fans in the Pacific Northwest love their Mariners.\"",
    "\"This team has some exciting young players - Alvin Davis, Phil Bradley, Mark Langston - that's a foundation.\"",
    "\"The Kingdome is home - and the Mariners are putting down roots indoors.\"",
    "\"Dave Niehaus is the voice of the Mariners - and he's excited about this young club.\"",
    "\"There's talent everywhere you look in this lineup - the Mariners can surprise you.\"",
    "\"This club is building something - the young players are starting to come together.\"",
    "\"Seattle has one of the most exciting young cores in the American League.\"",
    "\"The fans in Seattle have been waiting for a winner - and this team is getting closer.\"",
    "\"There's a buzz around the Mariners this year - people can feel something building.\"",
    "\"This is a team that's been through some lean years - but the future is bright.\"",
    "\"Seattle baseball - there's nothing quite like a night at the Kingdome.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Alvin Davis is one of the most promising young hitters to come along in years - just watch him hit.\"",
    "\"Mark Langston is going to win a lot of games in this league - that fastball is electric.\"",
    "\"Dave Henderson - Hendu - is one of the most exciting young center fielders in the American League.\"",
    "\"Gorman Thomas can hit the ball out of any part of this ballpark - Stormin' Gorman is the real deal.\"",
    "\"Matt Young was an All-Star as a rookie - that left arm is something special.\"",
    "\"Spike Owen was the sixth overall pick just two years ago - the kid can play shortstop.\"",
    "\"Ken Phelps gives Seattle a left-handed power bat - when he connects, it goes a long way.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening indoors at the Kingdome.\"",
    "\"The lights are on at the Dome - Mariners baseball tonight.\"",
    "The Kingdome - home of the Mariners since 1977 - baseball under the concrete roof.",
    "\"The air conditioning is humming tonight - always 72 degrees inside the Dome.\"",
    "\"The white concrete roof stretched above the field - there's nothing else like it in baseball.\"",
    "\"The artificial turf plays fast tonight - ground balls will scoot through the infield.\"",
    "\"The seats are filling up nicely - Seattle fans are excited about this young team.\"",
    "\"You can hear the ballgame echoing off the roof tonight - the Dome has its own sound.\"",
    "\"A comfortable evening inside the Kingdome - no rain delays here, ever.\"",
    "\"This is still a young ballpark - the fans are still growing with this franchise.\"",
    "\"The Kingdome is hopping tonight - the crowd is into this one.\"",
    "\"Baseball indoors in the Pacific Northwest - the Kingdome is home.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here in Seattle is into this ballgame.\"",
    "\"Mariners fans are making some noise tonight at the Kingdome.\"",
    "\"The fans in Seattle have waited a long time for a winner - they're fired up tonight.\"",
    "\"The Kingdome is rocking tonight.\"",
    "\"Seattle fans are among the most loyal in baseball - they've been through some lean years.\"",
    "\"The crowd is on its feet - they can feel something building here.\"",
    "\"A great turnout at the Kingdome tonight.\"",
    "\"These fans can see the talent on this young club - they're excited about the future.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to the Kingdome, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball on a Seattle evening.\"",
    "\"From all of us in the Pacific Northwest, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story - that's the beauty of this sport.\"",
    "\"Baseball in Seattle - it's a tradition that's growing in this city.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone - into the seats at the Kingdome!\"",
    "\"My oh my - what a ballgame!\"",
    "\"The Mariners are making their move here at the Kingdome.\"",
    "\"That one is long gone - off the Dome roof!\"",
    "\"You won't see many better than that one.\"",
    "\"And Seattle goes crazy - what a finish!\"",
  ]},
};