// More Obscure TV interactive popups for the 1984 game experience
// 25 entries matching the "More Obscure TV" banner ads in broadcastAds.js (#601-625)
// These are real 1984-era TV shows and special presentations (not cancelled shows)

const ENTRIES = [
  {
    id: 'cover_up',
    type: 'show',
    show: 'Cover Up',
    network: 'NBC',
    networkColor: '#6366f1',
    icon: '📸',
    day: 'Fridays',
    time: '8:00 PM',
    matchText: 'Catch an all-new episode of "Cover Up" this Friday night.',
    tagline: "One of television's most ambitious new action dramas.",
    description: "Fashion photographer Dani Reynolds thought she had it all. Then her secret-agent husband disappears under mysterious circumstances. Recruited by U.S. intelligence, Dani is paired with undercover operative Mac Harper and thrust into a world of espionage, danger, and international intrigue.",
    cast: ['Jennifer O\'Neill', 'Jon-Erik Hexum'],
    funFact: "Star Jon-Erik Hexum became one of television's fastest-rising stars before a tragic on-set accident in 1984 shocked Hollywood and ended the series prematurely.",
    quote: "One of television's most ambitious new action dramas. — TV Guide",
  },
  {
    id: 'riptide_602',
    type: 'show',
    show: 'Riptide',
    network: 'NBC',
    networkColor: '#6366f1',
    icon: '🚁',
    day: 'Tuesdays',
    time: '8:00 PM',
    matchText: 'Don\'t miss "Riptide," featuring adventure on the California coast.',
    tagline: "Adventure has never looked this sunny.",
    description: "Private investigators Cody Allen, Nick Ryder, and computer genius Murray \"Boz\" Bozinsky solve crimes up and down the California coast using speedboats, helicopters, and some very unusual detective work.",
    cast: ['Perry King', 'Joe Penny', 'Thom Bray'],
    funFact: "Many fans remember the robot and helicopter more than the actual mysteries. The famous pink helicopter and robot sidekick Murray became icons of 1980s television.",
    quote: "Adventure has never looked this sunny.",
  },
  {
    id: 'mike_hammer',
    type: 'show',
    show: 'Mickey Spillane\'s Mike Hammer',
    network: 'CBS',
    networkColor: '#0ea5e9',
    icon: '🕵️',
    day: 'Weekly',
    time: 'Primetime',
    matchText: '"Mickey Spillane\'s Mike Hammer" returns with another mystery this week.',
    tagline: "The toughest private eye on television.",
    description: "The legendary detective returns. Private investigator Mike Hammer prowls the streets of New York taking on mobsters, killers, blackmailers, and anyone else foolish enough to cross him.",
    cast: ['Stacy Keach'],
    funFact: "The show's success helped revive interest in classic detective fiction throughout the 1980s. Based on the bestselling novels of Mickey Spillane.",
    quote: "The toughest private eye on television.",
  },
  {
    id: 'hotel',
    type: 'show',
    show: 'Hotel',
    network: 'ABC',
    networkColor: '#e11d48',
    icon: '🏨',
    day: 'Wednesdays',
    time: '9:00 PM',
    matchText: 'Tune in for "Hotel" Wednesday evening.',
    tagline: "Every room has a story.",
    description: "Welcome to the elegant St. Gregory Hotel in San Francisco, where every guest brings a new mystery, romance, scandal, or adventure.",
    cast: ['James Brolin', 'Connie Sellecca'],
    funFact: "Hotel featured more guest stars than almost any other television drama of its era. Hollywood's biggest names appear weekly.",
    quote: "Every room has a story.",
  },
  {
    id: 'falcon_crest',
    type: 'show',
    show: 'Falcon Crest',
    network: 'CBS',
    networkColor: '#0ea5e9',
    icon: '🍷',
    day: 'Fridays',
    time: '9:00 PM',
    matchText: 'The drama continues on "Falcon Crest."',
    tagline: "Television's most intoxicating drama.",
    description: "Power. Wealth. Betrayal. The battle for control of California's wine country continues as the Gioberti and Channing families wage war over the legendary Falcon Crest vineyards.",
    cast: ['Jane Wyman', 'Lorenzo Lamas'],
    funFact: "Jane Wyman was the first wife of future President Ronald Reagan.",
    quote: "Television's most intoxicating drama.",
  },
  {
    id: 'knots_landing',
    type: 'show',
    show: 'Knots Landing',
    network: 'CBS',
    networkColor: '#0ea5e9',
    icon: '🏘️',
    day: 'Thursdays',
    time: '10:00 PM',
    matchText: 'See what happens next on "Knots Landing."',
    tagline: "Where neighbors know everyone's business.",
    description: "The cul-de-sac may look peaceful, but behind closed doors lies a world of secrets, affairs, rivalries, and heartbreak.",
    cast: ['Michele Lee', 'Ted Shackelford', 'Joan Van Ark'],
    funFact: "Knots Landing eventually lasted longer than Dallas itself. Spin-off of Dallas.",
    quote: "Where neighbors know everyone's business.",
  },
  {
    id: 'lottery',
    type: 'show',
    show: 'Lottery!',
    network: 'ABC',
    networkColor: '#e11d48',
    icon: '🎟️',
    day: 'Thursdays',
    time: '8:00 PM',
    matchText: 'Don\'t miss "Lottery!" this Thursday night.',
    tagline: "One ticket can change everything.",
    description: "What would YOU do with a million dollars? Each week follows a different lottery winner whose life changes forever after hitting the jackpot.",
    cast: ['Ben Murphy', 'Marshall Colt'],
    funFact: "Every episode featured a completely different winner and story.",
    quote: "One ticket can change everything.",
  },
  {
    id: 'airwolf',
    type: 'show',
    show: 'Airwolf',
    network: 'CBS',
    networkColor: '#0ea5e9',
    icon: '🚁',
    day: 'Saturdays',
    time: '8:00 PM',
    matchText: 'An all-new episode of "Airwolf" takes flight this weekend.',
    tagline: "The sky is no longer the limit.",
    description: "The world's most advanced combat helicopter takes flight. Pilot Stringfellow Hawke and Dominic Santini tackle impossible missions using Airwolf's incredible speed, stealth technology, and devastating firepower.",
    cast: ['Jan-Michael Vincent', 'Ernest Borgnine'],
    funFact: "The helicopter sequences remain some of the most impressive action footage ever filmed for television.",
    quote: "The sky is no longer the limit.",
  },
  {
    id: 'airwolf_spotlight',
    type: 'spotlight',
    show: 'Stringfellow Hawke Returns!',
    network: 'CBS',
    networkColor: '#0ea5e9',
    icon: '✈️',
    day: 'Saturdays',
    time: '8:00 PM',
    matchText: 'Join Stringfellow Hawke for another mission on "Airwolf."',
    tagline: "He's the best pilot in the world. His helicopter is even better.",
    description: "America's favorite helicopter pilot is back for another dangerous mission. Former test pilot Stringfellow Hawke continues his secret work for The Firm while searching for answers about his missing brother.",
    cast: ['Jan-Michael Vincent'],
    funFact: "Aircraft: Airwolf. Maximum Speed: Classified. Mission Status: Active.",
    quote: "He's the best pilot in the world. His helicopter is even better.",
  },
  {
    id: 'blue_thunder',
    type: 'show',
    show: 'Blue Thunder',
    network: 'ABC',
    networkColor: '#e11d48',
    icon: '🚁',
    day: 'Weekly',
    time: 'Primetime',
    matchText: 'Catch "Blue Thunder" this week.',
    tagline: "Crime doesn't stand a chance.",
    description: "The battle for the skies continues. Based on the hit motion picture, Blue Thunder follows the adventures of Frank Chaney and the revolutionary police helicopter that can see, hear, and track criminals from miles away.",
    cast: ['James Farentino'],
    funFact: "Blue Thunder and Airwolf competed directly for helicopter-action fans during the 1980s.",
    quote: "Crime doesn't stand a chance.",
  },
  {
    id: 'special_presentation',
    type: 'special',
    show: 'The Last Crossing',
    network: 'Special Presentation',
    networkColor: '#f59e0b',
    icon: '🎬',
    day: 'Tonight',
    time: 'Following the game',
    matchText: 'Stay tuned for a special television presentation following tonight\'s game.',
    tagline: "A gripping Cold War thriller.",
    description: "When a retired Navy captain discovers a Soviet submarine operating near American waters, he finds himself caught in a deadly Cold War confrontation.",
    cast: ['Robert Stack', 'Linda Evans'],
    funFact: "Running Time: 2 Hours. Presented Commercial-Free By Your Local Station.",
    quote: "A gripping Cold War thriller.",
  },
  {
    id: 'network_movie_premiere',
    type: 'special',
    show: 'Smokey and the Bandit',
    network: 'ABC Sunday Night Movie',
    networkColor: '#e11d48',
    icon: '🎬',
    day: 'Sunday',
    time: '8:00 PM',
    matchText: 'Enjoy a network movie premiere this Sunday evening.',
    tagline: "The chase that made movie history.",
    description: "For the first time on network television... Burt Reynolds races across America with Jackie Gleason hot on his trail in one of the decade's biggest box-office hits.",
    cast: ['Burt Reynolds', 'Sally Field', 'Jackie Gleason'],
    funFact: "Originally Released: 1977. Television Premiere Event.",
    quote: "The chase that made movie history.",
  },
  {
    id: 'two_night_event',
    type: 'special',
    show: 'Shadow of the Eagle',
    network: 'Two-Night Miniseries Event',
    networkColor: '#f59e0b',
    icon: '🦅',
    day: 'Sunday & Monday',
    time: '9:00 PM',
    matchText: 'A two-night television event begins this week.',
    tagline: "America's story becomes their story.",
    description: "A powerful two-night miniseries event. Three generations of an American family struggle through war, politics, and personal tragedy from World War II through the modern era.",
    cast: ['Richard Chamberlain', 'Angie Dickinson'],
    funFact: "Part One: Sunday. Part Two: Monday. Don't miss either night of this epic television event.",
    quote: "America's story becomes their story.",
  },
  {
    id: 'movie_night',
    type: 'special',
    show: 'The Great Escape',
    network: 'Tonight\'s Feature',
    networkColor: '#f59e0b',
    icon: '🍿',
    day: 'Tonight',
    time: 'Primetime',
    matchText: 'Grab some popcorn and enjoy a movie at home.',
    tagline: "One of the greatest adventure films ever made.",
    description: "Steve McQueen leads an unforgettable World War II prison break in one of Hollywood's most beloved adventure classics.",
    cast: ['Steve McQueen', 'James Garner', 'Richard Attenborough'],
    funFact: "Academy Award Nominee. Running Time: 172 Minutes.",
    quote: "One of the greatest adventure films ever made.",
  },
  {
    id: 'late_night',
    type: 'special',
    show: 'Late Night with David Letterman',
    network: 'NBC Late Night',
    networkColor: '#6366f1',
    icon: '🌙',
    day: 'Nightly',
    time: 'After local news',
    matchText: 'Stay tuned for late-night entertainment after your local news.',
    tagline: "You never know what's going to happen.",
    description: "Join David Letterman for another night of comedy, celebrity guests, unusual stunts, and unpredictable television.",
    cast: ['David Letterman', 'Paul Shaffer'],
    funFact: "Paul Shaffer and The World's Most Dangerous Band provide the music. Letterman's show has become one of the hottest programs among younger viewers.",
    quote: "You never know what's going to happen.",
  },
  {
    id: 'scarecrow_mrs_king',
    type: 'show',
    show: 'Scarecrow and Mrs. King',
    network: 'CBS',
    networkColor: '#0ea5e9',
    icon: '🕵️',
    day: 'Weekly',
    time: 'Primetime',
    matchText: '"Scarecrow and Mrs. King" returns this week.',
    tagline: "Espionage has never been this charming.",
    description: "Suburban housewife Amanda King never expected to become a spy. Working alongside secret agent Lee Stetson, she helps save the world while trying to maintain a normal family life.",
    cast: ['Kate Jackson', 'Bruce Boxleitner'],
    funFact: "Kate Jackson, formerly of Charlie's Angels, brought her star power to this charming espionage drama.",
    quote: "Espionage has never been this charming.",
  },
  {
    id: 'tj_hooker',
    type: 'show',
    show: 'T.J. Hooker',
    network: 'ABC',
    networkColor: '#e11d48',
    icon: '👮',
    day: 'Saturdays',
    time: '9:00 PM',
    matchText: 'The adventure continues on "T.J. Hooker."',
    tagline: "Experience still counts.",
    description: "Veteran police sergeant T.J. Hooker patrols the streets, training rookie officers while fighting crime the old-fashioned way.",
    cast: ['William Shatner', 'Heather Locklear'],
    funFact: "Many viewers knew Shatner as Captain Kirk before he became television's toughest cop.",
    quote: "Experience still counts.",
  },
  {
    id: 'tj_hooker_shatner',
    type: 'spotlight',
    show: 'William Shatner as T.J. Hooker',
    network: 'ABC',
    networkColor: '#e11d48',
    icon: '⭐',
    day: 'Saturdays',
    time: '9:00 PM',
    matchText: 'William Shatner stars in another exciting episode of "T.J. Hooker."',
    tagline: "From the bridge of the Enterprise to the streets of L.A.",
    description: "William Shatner brings his commanding presence to the role of T.J. Hooker, a veteran cop who trains rookies while taking down criminals the old-fashioned way. After years as Captain Kirk, Shatner proves he can throw a punch as well as he can give an order.",
    cast: ['William Shatner', 'Heather Locklear'],
    funFact: "Shatner performed many of his own stunts on the show, insisting that Hooker's action scenes look authentic. Heather Locklear co-stars as Officer Stacy Sheridan.",
    quote: "Experience still counts.",
  },
  {
    id: 'hunter',
    type: 'show',
    show: 'Hunter',
    network: 'NBC',
    networkColor: '#6366f1',
    icon: '🔫',
    day: 'Weekends',
    time: 'Primetime',
    matchText: 'Don\'t miss "Hunter" this weekend.',
    tagline: "Crime fears him. Criminals hate him.",
    description: "Detective Rick Hunter doesn't always play by the rules—but he gets results. Together with partner Dee Dee McCall, Hunter takes on Los Angeles' toughest criminals.",
    cast: ['Fred Dryer'],
    funFact: "The show combined gritty police drama with explosive action, earning a loyal following among fans of the genre.",
    quote: "Crime fears him. Criminals hate him.",
  },
  {
    id: 'hunter_dryer',
    type: 'spotlight',
    show: 'Fred Dryer as Detective Rick Hunter',
    network: 'NBC',
    networkColor: '#6366f1',
    icon: '🏈',
    day: 'Thursdays',
    time: 'Primetime',
    matchText: 'Fred Dryer stars in "Hunter" Thursday night.',
    tagline: "From the gridiron to the streets of L.A.",
    description: "Fred Dryer brings his NFL intensity to the role of Detective Rick Hunter, a tough, no-nonsense cop who bends the rules to get justice. His imposing 6'6\" frame and athletic background make Hunter one of television's most physically intimidating heroes.",
    cast: ['Fred Dryer', 'Stepfanie Kramer'],
    funFact: "Dryer played 13 seasons in the NFL for the New York Giants and Los Angeles Rams before becoming a television star. He was the first NFL player to record two safeties in a single game.",
    quote: "Crime fears him. Criminals hate him.",
  },
  {
    id: 'matt_houston',
    type: 'show',
    show: 'Matt Houston',
    network: 'ABC',
    networkColor: '#e11d48',
    icon: '🤵',
    day: 'Weekly',
    time: 'Primetime',
    matchText: '"Matt Houston" returns with another case.',
    tagline: "Justice travels first class.",
    description: "Millionaire. Playboy. Detective. Texas oil heir Matt Houston uses his wealth, private jet, and investigative instincts to solve crimes around the globe.",
    cast: ['Lee Horsley'],
    funFact: "Few shows embraced 1980s excess more completely than Matt Houston.",
    quote: "Justice travels first class.",
  },
  {
    id: 'webster',
    type: 'show',
    show: 'Webster',
    network: 'ABC',
    networkColor: '#e11d48',
    icon: '👦',
    day: 'Weekly',
    time: 'Primetime',
    matchText: 'Join us for an all-new episode of "Webster."',
    tagline: "Small kid. Big laughs.",
    description: "Young Webster Long is adopted by former NFL star George Papadopolis and his wife Katherine after losing his parents. Heartwarming family comedy continues this week.",
    cast: ['Emmanuel Lewis'],
    funFact: "Emmanuel Lewis became one of television's most recognizable child stars.",
    quote: "Small kid. Big laughs.",
  },
  {
    id: 'punky_brewster',
    type: 'show',
    show: 'Punky Brewster',
    network: 'NBC',
    networkColor: '#6366f1',
    icon: '🌈',
    day: 'Weekly',
    time: 'Primetime',
    matchText: 'Family laughs continue on "Punky Brewster."',
    tagline: "Every day is an adventure.",
    description: "Punky's adventures continue! The spirited youngster and her loyal dog Brandon continue to turn everyday life into unforgettable adventures.",
    cast: ['Soleil Moon Frye'],
    funFact: "Punky's colorful clothing became a fashion trend among young viewers.",
    quote: "Every day is an adventure.",
  },
  {
    id: 'charles_in_charge',
    type: 'show',
    show: 'Charles in Charge',
    network: 'CBS',
    networkColor: '#0ea5e9',
    icon: '🎓',
    day: 'Weekly',
    time: 'Primetime',
    matchText: 'Don\'t miss "Charles in Charge."',
    tagline: "One guy. One family. Endless headaches.",
    description: "College student Charles takes care of a busy family's children while trying to manage his own life.",
    cast: ['Scott Baio'],
    funFact: "The theme song became one of television's most recognizable tunes.",
    quote: "One guy. One family. Endless headaches.",
  },
  {
    id: 'night_court',
    type: 'show',
    show: 'Night Court',
    network: 'NBC',
    networkColor: '#6366f1',
    icon: '⚖️',
    day: 'Weekly',
    time: 'Primetime',
    matchText: 'The laughs continue this week on "Night Court."',
    tagline: "Justice has never been funnier.",
    description: "Court is now in session. Judge Harry Stone presides over Manhattan's strangest courtroom, where bizarre cases and even stranger people appear nightly.",
    cast: ['Harry Anderson', 'John Larroquette', 'Richard Moll'],
    funFact: "John Larroquette won four consecutive Emmy Awards for his role as Dan Fielding.",
    quote: "Justice has never been funnier.",
    spotlight: {
      show: 'Meet Bull Shannon',
      icon: '🧑‍⚖️',
      tagline: "Court adjourned!",
      description: "Standing over seven feet tall, court bailiff Bull Shannon keeps order in New York's craziest courtroom. Despite his intimidating size, Bull is often the sweetest person in the room.",
      cast: ['Richard Moll'],
      funFact: "Bull's favorite hobby is science fiction. Despite his intimidating size, Bull is often the sweetest person in the room.",
      quote: "Court adjourned!",
      achievementId: 'bull_shannon_fan',
    },
  },
];

// Tracking for viewed More Obscure TV ads
const VIEWED_ADS = new Set();

/**
 * Find the More Obscure TV entry matching a given ad text.
 * @param {string} adText
 * @returns {object|null}
 */
export function findMoreObscureTvEntry(adText) {
  return ENTRIES.find(e => e.matchText === adText) || null;
}

/**
 * Track a view of a More Obscure TV ad. Returns newly unlocked achievement IDs.
 * @param {string} entryId
 * @param {boolean} showedSpotlight - whether a spotlight variant was shown
 * @returns {string[]}
 */
export function trackMoreObscureTvView(entryId, showedSpotlight = false) {
  VIEWED_ADS.add(entryId);
  const unlocked = [];

  if (VIEWED_ADS.size >= 5) {
    unlocked.push('prime_time_viewer');
  }
  if (VIEWED_ADS.size >= 15) {
    unlocked.push('couch_potato');
  }
  if (VIEWED_ADS.size >= 25) {
    unlocked.push('tv_guide_completionist');
  }

  // Bull Shannon spotlight achievement
  if (entryId === 'night_court' && showedSpotlight) {
    unlocked.push('bull_shannon_fan');
  }

  return unlocked;
}

/**
 * Get count of viewed More Obscure TV ads.
 * @returns {number}
 */
export function getMoreObscureTvViewCount() {
  return VIEWED_ADS.size;
}