// NASA & Space Shuttle Interactive Museum Exhibits (776-800)
// 25 entries celebrating space exploration milestones

const ENTRIES = [
  {
    id: 'apollo_11',
    exhibit: 'Apollo 11',
    icon: '🚀',
    matchText: 'On July 20, 1969, American astronauts Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon.',
    tagline: 'First Steps on the Moon',
    year: '1969',
    description: 'On July 20, 1969, American astronauts Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon. An estimated 600 million people watched the event on television, making it one of the most important moments in human history.',
    significance: 'Lunar landing',
    viewers: '600 million',
    category: 'milestone',
    iconic: true,
    funFact: 'Apollo 11 remains one of the greatest achievements in human exploration.',
  },
  {
    id: 'neil_armstrong',
    exhibit: 'Neil Armstrong',
    icon: '👨‍🚀',
    matchText: 'Commander Neil Armstrong took humanity\'s first steps on the lunar surface in 1969.',
    tagline: 'First Footstep',
    description: 'Commander Neil Armstrong took humanity\'s first steps on the lunar surface in 1969. His famous words, "That\'s one small step for man, one giant leap for mankind," remain among the most quoted phrases in history.',
    achievement: 'First Human on the Moon',
    famousWords: '"One small step for man, one giant leap for mankind"',
    category: 'astronaut',
    iconic: true,
    funFact: 'Neil Armstrong\'s first words on the Moon are among the most famous in history.',
  },
  {
    id: 'buzz_aldrin',
    exhibit: 'Buzz Aldrin',
    icon: '👨‍🚀',
    matchText: 'Buzz Aldrin followed Neil Armstrong onto the Moon during Apollo 11.',
    tagline: 'Lunar Pioneer',
    description: 'Buzz Aldrin followed Neil Armstrong onto the Moon during Apollo 11. The former Air Force pilot spent more than 21 hours on the lunar surface and helped conduct scientific experiments that expanded our understanding of the Moon.',
    achievement: 'Second Human on the Moon',
    lunarTime: '21+ hours',
    category: 'astronaut',
    iconic: true,
    funFact: 'Buzz Aldrin conducted numerous scientific experiments during Apollo 11.',
  },
  {
    id: 'john_glenn',
    exhibit: 'John Glenn',
    icon: '🌍',
    matchText: 'In 1962, John Glenn became the first American to orbit the Earth.',
    tagline: 'American Orbiter',
    year: '1962',
    description: 'In 1962, John Glenn became the first American to orbit the Earth. His Friendship 7 mission made him a national hero and helped establish the United States as a major force in the Space Race.',
    achievement: 'First American in Orbit',
    mission: 'Friendship 7',
    category: 'astronaut',
    iconic: true,
    funFact: 'John Glenn\'s orbital flight was a turning point in the Space Race.',
  },
  {
    id: 'alan_shepard',
    exhibit: 'Alan Shepard',
    icon: '🚀',
    matchText: 'Alan Shepard became the first American in space on May 5, 1961.',
    tagline: 'American Pioneer',
    year: '1961',
    description: 'Alan Shepard became the first American in space on May 5, 1961. Ten years later, he also became the fifth man to walk on the Moon during Apollo 14.',
    achievement: 'First American in Space & Lunar Walker',
    date: 'May 5, 1961',
    category: 'astronaut',
    iconic: true,
    funFact: 'Alan Shepard is the only person to both be first American in space and walk on the Moon.',
  },
  {
    id: 'space_shuttle',
    exhibit: 'The Space Shuttle',
    icon: '🛸',
    matchText: 'NASA\'s Space Shuttle program began in 1981 and introduced reusable spacecraft to the world.',
    tagline: 'Reusable Revolution',
    year: '1981',
    description: 'NASA\'s Space Shuttle program began in 1981 and introduced reusable spacecraft to the world. Unlike earlier capsules, the Shuttle launched like a rocket and landed like an airplane.',
    significance: 'First reusable spacecraft',
    innovation: 'Rocket launch, airplane landing',
    category: 'spacecraft',
    iconic: true,
    funFact: 'The Space Shuttle revolutionized space travel with its reusable design.',
  },
  {
    id: 'columbia',
    exhibit: 'Space Shuttle Columbia',
    icon: '🛸',
    matchText: 'Space Shuttle Columbia made history in 1981 as the first Space Shuttle ever launched.',
    tagline: 'First Shuttle',
    year: '1981',
    description: 'Space Shuttle Columbia made history in 1981 as the first Space Shuttle ever launched. Its successful mission proved that reusable spacecraft could become a practical part of future space exploration.',
    achievement: 'First Space Shuttle Launch',
    significance: 'Proved reusable design',
    category: 'spacecraft',
    iconic: true,
    funFact: 'Columbia\'s successful launch opened a new era in space exploration.',
  },
  {
    id: 'challenger',
    exhibit: 'Space Shuttle Challenger',
    icon: '🛸',
    matchText: 'Space Shuttle Challenger entered service in 1983 and quickly became one of NASA\'s busiest orbiters.',
    tagline: 'Busy Orbiter',
    year: '1983',
    description: 'Space Shuttle Challenger entered service in 1983 and quickly became one of NASA\'s busiest orbiters. Its missions carried satellites, scientific experiments, and astronauts into Earth orbit.',
    missions: 'Multiple',
    capabilities: 'Satellites, experiments, astronauts',
    category: 'spacecraft',
    funFact: 'Challenger became one of NASA\'s most active Space Shuttle orbiters.',
  },
  {
    id: 'sally_ride',
    exhibit: 'Sally Ride',
    icon: '👩‍🚀',
    matchText: 'In 1983, Sally Ride became the first American woman in space.',
    tagline: 'American First',
    year: '1983',
    description: 'In 1983, Sally Ride became the first American woman in space. A physicist and astronaut, Ride inspired millions of young Americans to pursue careers in science and engineering.',
    achievement: 'First American Woman in Space',
    background: 'Physicist',
    impact: 'Inspired millions',
    category: 'astronaut',
    iconic: true,
    funFact: 'Sally Ride\'s achievement inspired a generation of women scientists.',
  },
  {
    id: 'kathryn_sullivan',
    exhibit: 'Kathryn Sullivan',
    icon: '👩‍🚀',
    matchText: 'Astronaut Kathryn Sullivan became the first American woman to perform a spacewalk in 1984.',
    tagline: 'First Woman Spacewalk',
    year: '1984',
    description: 'Astronaut Kathryn Sullivan became the first American woman to perform a spacewalk in 1984. Her achievement demonstrated the growing role of women in America\'s space program.',
    achievement: 'First American Woman Spacewalk',
    significance: 'Women in space',
    category: 'astronaut',
    iconic: true,
    funFact: 'Kathryn Sullivan\'s spacewalk showed women could perform all astronaut roles.',
  },
  {
    id: 'saturn_v',
    exhibit: 'The Saturn V',
    icon: '🔴',
    matchText: 'The Saturn V rocket remains the most powerful rocket ever successfully flown.',
    tagline: 'Most Powerful Rocket',
    description: 'The Saturn V rocket remains the most powerful rocket ever successfully flown. Standing 363 feet tall, it launched every Apollo mission that carried astronauts to the Moon.',
    height: '363 feet',
    power: 'Most powerful ever',
    achievement: 'Lunar launcher',
    category: 'technology',
    iconic: true,
    funFact: 'The Saturn V remains unmatched in raw power and success rate.',
  },
  {
    id: 'orbital_speed',
    exhibit: 'How Fast Is Orbit?',
    icon: '⚡',
    matchText: 'To remain in low Earth orbit, a spacecraft must travel approximately 17,500 miles per hour.',
    tagline: 'Orbital Velocity',
    description: 'To remain in low Earth orbit, a spacecraft must travel approximately 17,500 miles per hour. At that speed, astronauts circle the Earth roughly every 90 minutes.',
    speed: '17,500 mph',
    period: 'Every 90 minutes',
    category: 'science',
    funFact: 'Orbital velocity is achieved through a precise balance of speed and gravity.',
  },
  {
    id: 'lunar_distance',
    exhibit: 'How Far Away Is the Moon?',
    icon: '🌙',
    matchText: 'The Moon is approximately 239,000 miles from Earth.',
    tagline: 'Lunar Distance',
    description: 'The Moon is approximately 239,000 miles from Earth. Apollo astronauts traveled that distance in about three days using technology far less powerful than today\'s home computers.',
    distance: '239,000 miles',
    travelTime: 'About 3 days',
    perspective: 'Less power than home computers',
    category: 'science',
    funFact: 'Apollo astronauts achieved the Moon with remarkable simplicity in computing power.',
  },
  {
    id: 'weightlessness',
    exhibit: 'What Is Weightlessness?',
    icon: '🌌',
    matchText: 'Astronauts appear weightless because they are constantly falling around the Earth while traveling at tremendous speeds.',
    tagline: 'Microgravity',
    description: 'Astronauts appear weightless because they are constantly falling around the Earth while traveling at tremendous speeds. This condition is called microgravity.',
    phenomenon: 'Constant freefall',
    scientificName: 'Microgravity',
    category: 'science',
    funFact: 'Weightlessness is actually the sensation of continuous freefall.',
  },
  {
    id: 'gemini_program',
    exhibit: 'The Gemini Program',
    icon: '🛰️',
    matchText: 'Before astronauts could reach the Moon, NASA developed critical techniques through Project Gemini.',
    tagline: 'Stepping Stone',
    description: 'Before astronauts could reach the Moon, NASA developed critical techniques through Project Gemini. Gemini missions perfected docking, rendezvous, and long-duration spaceflight.',
    achievements: ['Docking', 'Rendezvous', 'Long-duration flight'],
    significance: 'Path to Moon',
    category: 'program',
    funFact: 'Project Gemini provided essential practice for Apollo missions.',
  },
  {
    id: 'apollo_13',
    exhibit: 'Apollo 13',
    icon: '⚠️',
    matchText: 'Apollo 13 suffered a major explosion on its way to the Moon in 1970.',
    tagline: 'Crisis & Survival',
    year: '1970',
    description: 'Apollo 13 suffered a major explosion on its way to the Moon in 1970. Despite overwhelming odds, NASA engineers and astronauts worked together to bring the crew safely home.',
    crisis: 'Major explosion',
    outcome: 'Crew safely returned',
    significance: 'Triumph over adversity',
    category: 'mission',
    iconic: true,
    funFact: 'Apollo 13 demonstrates human ingenuity under extreme pressure.',
  },
  {
    id: 'skylab',
    exhibit: 'Skylab',
    icon: '🏗️',
    matchText: 'America\'s first space station, Skylab, operated from 1973 to 1979.',
    tagline: 'First American Station',
    years: '1973-1979',
    description: 'America\'s first space station, Skylab, operated from 1973 to 1979. Astronauts spent weeks and even months conducting scientific experiments in orbit.',
    duration: 'Weeks to months',
    purpose: 'Scientific research',
    category: 'station',
    iconic: true,
    funFact: 'Skylab proved humans could work productively in space for extended periods.',
  },
  {
    id: 'mission_control',
    exhibit: 'Mission Control',
    icon: '🎛️',
    matchText: 'NASA\'s Mission Control Center in Houston, Texas directs American space missions.',
    tagline: 'Heart of Operations',
    location: 'Houston, Texas',
    description: 'NASA\'s Mission Control Center in Houston, Texas directs American space missions. Hundreds of engineers and specialists monitor spacecraft systems around the clock.',
    staff: 'Hundreds of specialists',
    operation: '24/7 monitoring',
    category: 'infrastructure',
    iconic: true,
    funFact: 'Mission Control is the nerve center of all American space operations.',
  },
  {
    id: 'space_food',
    exhibit: 'Space Food',
    icon: '🥫',
    matchText: 'Early astronauts ate food squeezed from tubes.',
    tagline: 'Evolution of Eating',
    description: 'Early astronauts ate food squeezed from tubes. By the 1980s, astronauts enjoyed a much wider menu including sandwiches, fruit, and hot meals prepared aboard the Space Shuttle.',
    early: 'Squeezed from tubes',
    modern: 'Sandwiches, fruit, hot meals',
    evolution: 'From basic to diverse',
    category: 'living',
    funFact: 'Space food has evolved from simple tubes to varied, nutritious meals.',
  },
  {
    id: 'space_suits',
    exhibit: 'Space Suits',
    icon: '🪂',
    matchText: 'A modern astronaut\'s space suit functions as a personal spacecraft.',
    tagline: 'Personal Spacecraft',
    description: 'A modern astronaut\'s space suit functions as a personal spacecraft. It supplies oxygen, regulates temperature, and protects astronauts from the harsh environment of space.',
    functions: ['Oxygen supply', 'Temperature control', 'Protection'],
    technology: 'Personal systems',
    category: 'equipment',
    funFact: 'A space suit is essentially a complete self-contained spacecraft.',
  },
  {
    id: 'satellites',
    exhibit: 'Satellites',
    icon: '🛰️',
    matchText: 'Hundreds of satellites orbit the Earth every day.',
    tagline: 'Modern Necessity',
    description: 'Hundreds of satellites orbit the Earth every day. They help forecast weather, provide communications, conduct scientific research, and assist navigation systems.',
    purposes: ['Weather forecasting', 'Communications', 'Research', 'Navigation'],
    quantity: 'Hundreds',
    category: 'technology',
    iconic: true,
    funFact: 'Satellites are essential to modern civilization.',
  },
  {
    id: 'hubble_idea',
    exhibit: 'The Hubble Idea',
    icon: '🔭',
    matchText: 'NASA is developing a powerful new space telescope that will orbit above Earth\'s atmosphere.',
    tagline: 'Future Observatory',
    description: 'NASA is developing a powerful new space telescope that will orbit above Earth\'s atmosphere. Scientists hope it will provide the clearest views of the universe ever obtained.',
    objective: 'Clearest views of universe',
    location: 'Orbit above atmosphere',
    future: 'Revolutionary astronomy',
    category: 'science',
    funFact: 'The Space Telescope (later named Hubble) will revolutionize astronomy.',
  },
  {
    id: 'computers_everywhere',
    exhibit: 'A Computer in Every Home?',
    icon: '💻',
    matchText: 'Many experts believe computers will become common household items in the future.',
    tagline: '1984 Prediction',
    description: 'Many experts believe computers will become common household items in the future. NASA already relies heavily on computers to guide spacecraft, process data, and communicate with astronauts.',
    prediction: 'Computers in homes',
    currentUse: 'NASA computing',
    perspective: '1984 view',
    category: 'culture',
    funFact: 'NASA\'s computing needs helped drive computer technology forward.',
  },
  {
    id: 'mars_frontier',
    exhibit: 'Mars: The Next Frontier',
    icon: '🔴',
    matchText: 'Many scientists believe Mars could become humanity\'s next great destination.',
    tagline: 'Red Planet Goal',
    description: 'Many scientists believe Mars could become humanity\'s next great destination. Although no human has visited the Red Planet, NASA continues to study how such a mission might someday be possible.',
    target: 'Mars',
    status: 'No humans yet',
    study: 'Future missions',
    category: 'exploration',
    iconic: true,
    funFact: 'Mars exploration remains a central goal of NASA planning.',
  },
  {
    id: 'future_of_space',
    exhibit: 'The Future of Space',
    icon: '🌠',
    matchText: 'Just 66 years separated the Wright Brothers\' first flight from the Apollo 11 Moon landing.',
    tagline: 'Progress Unlimited',
    description: 'Just 66 years separated the Wright Brothers\' first flight from the Apollo 11 Moon landing. If progress continues at that pace, today\'s students may someday witness permanent bases on the Moon—or even journeys to Mars.',
    timespan: '66 years',
    context: 'Wright Brothers to Moon',
    future: 'Lunar bases, Mars missions',
    category: 'vision',
    iconic: true,
    inspirational: true,
    funFact: 'Space exploration has advanced more rapidly than any other technological field.',
  },
];

const VIEWED_EXHIBITS = new Set();
const EXHIBIT_VIEW_COUNTS = {};

export function findNasaSpaceEntry(adText) {
  return ENTRIES.find(e => e.matchText === adText) || null;
}

export function trackNasaSpaceView(entryId) {
  VIEWED_EXHIBITS.add(entryId);
  EXHIBIT_VIEW_COUNTS[entryId] = (EXHIBIT_VIEW_COUNTS[entryId] || 0) + 1;
  const unlocked = [];

  if (VIEWED_EXHIBITS.size >= 5) unlocked.push('space_explorer');
  if (VIEWED_EXHIBITS.size >= 15) unlocked.push('space_devotee');
  if (VIEWED_EXHIBITS.size >= 25) unlocked.push('space_historian');

  return unlocked;
}

export function getNasaSpaceViewCount() {
  return VIEWED_EXHIBITS.size;
}