// National Banner Achievements — 370 total (354 window + 16 hidden category)
// Generated from the Master Achievement List spec
// Each hidden achievement auto-unlocks when all window achievements in its category are collected

// Category slugs map to banner data file prefixes
export const NATIONAL_CATEGORIES = {
  tv: { name: 'TV Shows', hiddenName: "Prime Time '84" },
  movies: { name: 'Movies', hiddenName: null },
  electronics: { name: 'Electronics & Computers', hiddenName: null },
  generalProducts: { name: 'General Products / Americana', hiddenName: null },
  arcade: { name: 'Arcade & Video Games', hiddenName: null },
  wrestling: { name: 'Pro Wrestling', hiddenName: "And That's the Bottom Line in '84" },
  olympics: { name: '1984 LA Olympics', hiddenName: 'Spirit of \'84' },
  space: { name: 'Space / NASA / Aviation', hiddenName: 'The Final Frontier' },
  newspapers: { name: 'Newspapers & Classifieds', hiddenName: 'Read All About It' },
  phoneWars: { name: 'Long Distance Phone Wars', hiddenName: 'Long Distance Champion' },
  film: { name: 'Film Development & Cameras', hiddenName: "That's a Keeper" },
  scream1984: { name: 'Things That Scream 1984', hiddenName: 'Totally Eighties' },
  mall: { name: '1984 Mall Culture', hiddenName: 'Closing Time at the Mall' },
  formatWars: { name: 'Home Video Format Wars', hiddenName: 'Tracking Adjusted' },
  countyFair: { name: 'County Fairs & Americana', hiddenName: 'See You Next Summer' },
  music: { name: 'Music & MTV', hiddenName: 'I Want My MTV' },
  cars: { name: 'Cars & the Road', hiddenName: 'Full Tank, Open Road' },
  cartoons: { name: 'Saturday Morning Cartoons', hiddenName: "Kids, Don't Try This at Home" },
  cereal: { name: 'Cereal & Their Mascots', hiddenName: 'Cleaned the Bowl' },
  promoNights: { name: 'Ballpark Promo Nights & Giveaways', hiddenName: 'Promo Night Regular' },
};

// Window achievements (one per popup) — 354 total
// Format: { id, name, emoji, cat }
export const NATIONAL_WINDOW_ACHIEVEMENTS = [
  // ── TV Shows (25) ──
  { id: 'nat_tv_vice_marathon', name: 'Vice Marathon', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_southfork', name: 'Southfork Schermer', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_carrington', name: 'Carrington Catfight', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_plan_comes_together', name: 'I Love It When a Plan Comes Together', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_st_gregory', name: 'Checked In at the St. Gregory', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_simon_brothers', name: 'Simon Brothers Investigations', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_robin_nest', name: "Robin's Nest Regular", emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_keaton_dinner', name: 'Keaton Family Dinner', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_cabot_cove', name: 'Cabot Cove Sleuth', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_cheers', name: 'Last Call at Cheers', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_king_harbor', name: 'King Harbor Crew', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_matts_plan', name: "Matt's Master Plan", emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_squad_room', name: 'Squad Room Regular', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_stuntman', name: 'Unknown Stuntman', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_eastland', name: 'Eastland Honor Roll', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_order_court', name: 'Order in the Court', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_mels_diner', name: "Mel's Diner Regular", emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_knight_road', name: 'Knight of the Road', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_big_heart', name: 'Big Heart, Small Package', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_steele', name: 'Steele Investigations', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_stairway', name: 'Stairway Traveler', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_roll_call', name: 'Roll Call Regular', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_brownstone', name: 'Brownstone Buddies', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_night_court', name: 'Order in the Night Court', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_sf_memorial', name: 'San Francisco Memorial Rounds', emoji: '📺', cat: 'tv' },

  // ── Movies (25) ──
  { id: 'nat_movie_ghostbusters', name: 'Who You Gonna Call', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_axel_foley', name: 'Axel Foley', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_fortune_glory', name: 'Fortune and Glory', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_three_rules', name: 'The Three Rules', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_wax_on', name: 'Wax On, Wax Off', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_roll_call', name: 'Roll Call', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_cut_loose', name: 'Cut Loose', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_chase_stone', name: 'Chase the Stone', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_needs_many', name: 'The Needs of the Many', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_catch_day', name: 'Catch of the Day', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_stage_lights', name: 'Stage Lights', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_paddle_up', name: 'Paddle Up', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_pop_lock', name: 'Pop and Lock', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_starfighter', name: 'Greetings, Starfighter', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_broadway', name: 'Broadway Bound', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_nerd_power', name: 'Nerd Power', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_real_game', name: 'The Real Game', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_class_session', name: 'Class in Session', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_through_lens', name: 'Through the Lens', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_ill_be_back', name: "I'll Be Back", emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_dont_fall_asleep', name: "Don't Fall Asleep", emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_eleven', name: 'These Go to Eleven', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_spice_flow', name: 'The Spice Must Flow', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_call_name', name: 'Call My Name', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movie_knock_cover', name: 'Knock the Cover Off', emoji: '🎥', cat: 'movies' },

  // ── Electronics & Computers (15) ──
  { id: 'nat_elec_64k', name: '64K of Power', emoji: '💾', cat: 'electronics' },
  { id: 'nat_elec_head_class', name: 'Head of the Class', emoji: '👩‍🏫', cat: 'electronics' },
  { id: 'nat_elec_point_click', name: 'Point and Click', emoji: '🖱️', cat: 'electronics' },
  { id: 'nat_elec_trust_shack', name: 'Trust the Shack', emoji: '🕹️', cat: 'electronics' },
  { id: 'nat_elec_atari', name: 'Have You Played Atari Today?', emoji: '👾', cat: 'electronics' },
  { id: 'nat_elec_be_kind', name: 'Be Kind, Rewind', emoji: '⏪', cat: 'electronics' },
  { id: 'nat_elec_press_play', name: 'Press Play', emoji: '🎧', cat: 'electronics' },
  { id: 'nat_elec_pump_volume', name: 'Pump Up the Volume', emoji: '🔊', cat: 'electronics' },
  { id: 'nat_elec_high_score', name: 'High Score', emoji: '🌟', cat: 'electronics' },
  { id: 'nat_elec_perfect_sound', name: 'Perfect Sound', emoji: '🎶', cat: 'electronics' },
  { id: 'nat_elec_business', name: 'Means Business', emoji: '💼', cat: 'electronics' },
  { id: 'nat_elec_lights_camera', name: 'Lights, Camera, Action', emoji: '📷', cat: 'electronics' },
  { id: 'nat_elec_future_wrist', name: 'Future on Your Wrist', emoji: '⌚', cat: 'electronics' },
  { id: 'nat_elec_welcome_future', name: 'Welcome to the Future', emoji: '🚀', cat: 'electronics' },
  { id: 'nat_elec_dialing_in', name: 'Dialing In', emoji: '☎️', cat: 'electronics' },

  // ── General Products / Americana (15) ──
  { id: 'nat_gp_blue_light', name: 'Blue Light Special', emoji: '🔵', cat: 'generalProducts' },
  { id: 'nat_gp_wish_book', name: 'The Wish Book', emoji: '📖', cat: 'generalProducts' },
  { id: 'nat_gp_meet_counter', name: 'Meet Me at the Counter', emoji: '🍽️', cat: 'generalProducts' },
  { id: 'nat_gp_two_beef', name: 'Two All-Beef Patties', emoji: '🍔', cat: 'generalProducts' },
  { id: 'nat_gp_pick_side', name: 'Pick a Side', emoji: '⬅️', cat: 'generalProducts' },
  { id: 'nat_gp_food_court', name: 'Meet at the Food Court', emoji: '🍟', cat: 'generalProducts' },
  { id: 'nat_gp_adoption', name: 'Adoption Papers', emoji: '📔', cat: 'generalProducts' },
  { id: 'nat_gp_solve_cube', name: 'Solve the Cube', emoji: '🧊', cat: 'generalProducts' },
  { id: 'nat_gp_get_together', name: 'Get It Together', emoji: '🤝', cat: 'generalProducts' },
  { id: 'nat_gp_totally_rad', name: 'Totally Rad', emoji: '🆒', cat: 'generalProducts' },
  { id: 'nat_gp_burp_lid', name: 'Burp the Lid', emoji: '🤢', cat: 'generalProducts' },
  { id: 'nat_gp_shake_it', name: 'Shake It', emoji: '📸', cat: 'generalProducts' },
  { id: 'nat_gp_dinner_minutes', name: 'Dinner in Minutes', emoji: '🥘', cat: 'generalProducts' },
  { id: 'nat_gp_friday_rental', name: 'Friday Night Rental', emoji: '🎥', cat: 'generalProducts' },
  { id: 'nat_gp_good_old_days', name: 'The Good Old Days', emoji: '🇺🇸', cat: 'generalProducts' },

  // ── Arcade & Video Games (15) ──
  { id: 'nat_arc_chomp', name: 'Chomp Champion', emoji: '🪙', cat: 'arcade' },
  { id: 'nat_arc_dirk', name: 'Dirk the Daring', emoji: '🐲', cat: 'arcade' },
  { id: 'nat_arc_keep_rolling', name: 'Keep Rolling', emoji: '🔵', cat: 'arcade' },
  { id: 'nat_arc_pump_up', name: 'Pump It Up', emoji: '🪓', cat: 'arcade' },
  { id: 'nat_arc_how_high', name: 'How High Can You Get?', emoji: '🕹️', cat: 'arcade' },
  { id: 'nat_arc_quarters', name: 'Quarters to Empires', emoji: '🦍', cat: 'arcade' },
  { id: 'nat_arc_wood_grain', name: 'Wood Grain Warrior', emoji: '🪵', cat: 'arcade' },
  { id: 'nat_arc_survived', name: 'Survived the Crash', emoji: '🚀', cat: 'arcade' },
  { id: 'nat_arc_double_ship', name: 'Double Ship', emoji: '🚢', cat: 'arcade' },
  { id: 'nat_arc_reflexes', name: 'Reflexes of the Gods', emoji: '🧠', cat: 'arcade' },
  { id: 'nat_arc_next_game', name: "Next Game's Mine", emoji: '👾', cat: 'arcade' },
  { id: 'nat_arc_initials', name: 'Enter Your Initials', emoji: '⌨️', cat: 'arcade' },
  { id: 'nat_arc_into_grid', name: 'Into the Grid', emoji: '⬛', cat: 'arcade' },
  { id: 'nat_arc_hop_to_it', name: 'Hop to It', emoji: '🐸', cat: 'arcade' },
  { id: 'nat_arc_under_covers', name: 'Under the Covers', emoji: '🛸', cat: 'arcade' },

  // ── Pro Wrestling (25) ──
  { id: 'nat_wre_nature_boy', name: 'The Nature Boy', emoji: '⭐', cat: 'wrestling' },
  { id: 'nat_wre_king_territories', name: 'King of the Territories', emoji: '👑', cat: 'wrestling' },
  { id: 'nat_wre_american_dream', name: 'The American Dream', emoji: '💙', cat: 'wrestling' },
  { id: 'nat_wre_enforcer', name: 'The Enforcer', emoji: '🛡️', cat: 'wrestling' },
  { id: 'nat_wre_slamming', name: 'Slamming It', emoji: '🧳', cat: 'wrestling' },
  { id: 'nat_wre_wrecking_crew', name: 'Minnesota Wrecking Crew', emoji: '🧠', cat: 'wrestling' },
  { id: 'nat_wre_four_fingers', name: 'Four Fingers in the Air', emoji: '☝️', cat: 'wrestling' },
  { id: 'nat_wre_texas_heroes', name: 'Texas Heroes', emoji: '⭐', cat: 'wrestling' },
  { id: 'nat_wre_bad_street', name: 'Bad Street Brawlers', emoji: '👊', cat: 'wrestling' },
  { id: 'nat_wre_legion_doom', name: 'Legion of Doom', emoji: '💀', cat: 'wrestling' },
  { id: 'nat_wre_natural', name: 'The Natural', emoji: '🌳', cat: 'wrestling' },
  { id: 'nat_wre_whatcha', name: 'Whatcha Gonna Do', emoji: '🎙️', cat: 'wrestling' },
  { id: 'nat_wre_hot_rod', name: 'Hot Rod', emoji: '🎤', cat: 'wrestling' },
  { id: 'nat_wre_eighth_wonder', name: 'Eighth Wonder', emoji: '🏆', cat: 'wrestling' },
  { id: 'nat_wre_camel_clutch', name: 'Camel Clutch', emoji: '🤼', cat: 'wrestling' },
  { id: 'nat_wre_superfly', name: 'Superfly Splash', emoji: '🤸', cat: 'wrestling' },
  { id: 'nat_wre_grab_cakes', name: 'Grab Them Cakes', emoji: '🍰', cat: 'wrestling' },
  { id: 'nat_wre_dragon', name: 'The Dragon', emoji: '🐉', cat: 'wrestling' },
  { id: 'nat_wre_cobra_clutch', name: 'Cobra Clutch', emoji: '🐍', cat: 'wrestling' },
  { id: 'nat_wre_brain_trust', name: 'The Brain Trust', emoji: '🎩', cat: 'wrestling' },
  { id: 'nat_wre_mtv_mania', name: 'MTV Mania', emoji: '🎸', cat: 'wrestling' },
  { id: 'nat_wre_drawing_map', name: 'Drawing the Map', emoji: '🗺️', cat: 'wrestling' },
  { id: 'nat_wre_saturday_night', name: "Saturday Night's Main Event", emoji: '📺', cat: 'wrestling' },
  { id: 'nat_wre_action_figure', name: 'Action Figure Army', emoji: '🕴️', cat: 'wrestling' },
  { id: 'nat_wre_showcase', name: 'The Showcase of the Immortals', emoji: '🏟️', cat: 'wrestling' },

  // ── 1984 LA Olympics (17) ──
  { id: 'nat_oly_stick_landing', name: 'Stick the Landing', emoji: '🤸', cat: 'olympics' },
  { id: 'nat_oly_chasing_jesse', name: 'Chasing Jesse Owens', emoji: '🏃', cat: 'olympics' },
  { id: 'nat_oly_streak', name: 'The Streak', emoji: '🚧', cat: 'olympics' },
  { id: 'nat_oly_perfect_form', name: 'Perfect Form', emoji: '🏅', cat: 'olympics' },
  { id: 'nat_oly_262_history', name: '26.2 to History', emoji: '👣', cat: 'olympics' },
  { id: 'nat_oly_amateur_hour', name: 'Amateur Hour', emoji: '🕒', cat: 'olympics' },
  { id: 'nat_oly_let_games_begin', name: 'Let the Games Begin', emoji: '🎈', cat: 'olympics' },
  { id: 'nat_oly_carry_flame', name: 'Carry the Flame', emoji: '🔥', cat: 'olympics' },
  { id: 'nat_oly_mascot_mania', name: 'Mascot Mania', emoji: '🐻', cat: 'olympics' },
  { id: 'nat_oly_empty_lanes', name: 'The Empty Lanes', emoji: '🌐', cat: 'olympics' },
  { id: 'nat_oly_top_podium', name: 'Top of the Podium', emoji: '🥈', cat: 'olympics' },
  { id: 'nat_oly_in_black', name: 'In the Black', emoji: '⬛', cat: 'olympics' },
  { id: 'nat_oly_wave_flag', name: 'Wave Your Flag', emoji: '🇺🇸', cat: 'olympics' },
  { id: 'nat_oly_prime_gold', name: 'Prime-Time Gold', emoji: '🥇', cat: 'olympics' },
  { id: 'nat_oly_stuck_it', name: 'Stuck It', emoji: '🤸', cat: 'olympics' },
  { id: 'nat_oly_golden_gloves', name: 'Golden Gloves', emoji: '🥊', cat: 'olympics' },
  { id: 'nat_oly_pin_collector', name: 'Pin Collector', emoji: '📌', cat: 'olympics' },

  // ── Space / NASA / Aviation (18) ──
  { id: 'nat_spc_human_satellite', name: 'The Human Satellite', emoji: '👩', cat: 'space' },
  { id: 'nat_spc_strap_in', name: 'Strap In', emoji: '💺', cat: 'space' },
  { id: 'nat_spc_maiden_voyage', name: 'Maiden Voyage', emoji: '🚀', cat: 'space' },
  { id: 'nat_spc_airlock', name: 'Out the Airlock', emoji: '🚪', cat: 'space' },
  { id: 'nat_spc_orbital_tow', name: 'Orbital Tow Truck', emoji: '🚚', cat: 'space' },
  { id: 'nat_spc_wheels_down', name: 'Wheels Down', emoji: '🛞', cat: 'space' },
  { id: 'nat_spc_go_launch', name: 'Go for Launch', emoji: '🎧', cat: 'space' },
  { id: 'nat_spc_right_stuff', name: 'Right Stuff', emoji: '🎒', cat: 'space' },
  { id: 'nat_spc_liftoff', name: 'We Have Liftoff', emoji: '☄️', cat: 'space' },
  { id: 'nat_spc_microgravity', name: 'Microgravity Lab', emoji: '🔬', cat: 'space' },
  { id: 'nat_spc_overview', name: 'Overview Effect', emoji: '🌍', cat: 'space' },
  { id: 'nat_spc_space_fever', name: 'Space Fever', emoji: '🌌', cat: 'space' },
  { id: 'nat_spc_deep_signal', name: 'Deep Space Signal', emoji: '📡', cat: 'space' },
  { id: 'nat_spc_mach2', name: 'Mach 2', emoji: '✈️', cat: 'space' },
  { id: 'nat_spc_afterburner', name: 'Afterburner', emoji: '🔥', cat: 'space' },
  { id: 'nat_spc_cleared_takeoff', name: 'Cleared for Takeoff', emoji: '🛠️', cat: 'space' },
  { id: 'nat_spc_pioneer', name: 'Pioneer Spirit', emoji: '🕊️', cat: 'space' },
  { id: 'nat_spc_reach_stars', name: 'Reach for the Stars', emoji: '🌠', cat: 'space' },

  // ── Newspapers & Classifieds (14) ──
  { id: 'nat_news_obo', name: 'OBO', emoji: '📰', cat: 'newspapers' },
  { id: 'nat_news_now_hiring', name: 'Now Hiring', emoji: '💼', cat: 'newspapers' },
  { id: 'nat_news_missed_connection', name: 'Missed Connection', emoji: '💌', cat: 'newspapers' },
  { id: 'nat_news_box_score', name: 'Read the Box Score', emoji: '📊', cat: 'newspapers' },
  { id: 'nat_news_funnies', name: 'Read the Funnies', emoji: '😋', cat: 'newspapers' },
  { id: 'nat_news_paper_route', name: 'Paper Route', emoji: '🚲', cat: 'newspapers' },
  { id: 'nat_news_stop_presses', name: 'Stop the Presses', emoji: '🛑', cat: 'newspapers' },
  { id: 'nat_news_clip_save', name: 'Clip & Save', emoji: '✂️', cat: 'newspapers' },
  { id: 'nat_news_hatch_match', name: 'Hatch, Match & Dispatch', emoji: '🤝', cat: 'newspapers' },
  { id: 'nat_news_runs_great', name: 'Runs Great, Must Sell', emoji: '🚗', cat: 'newspapers' },
  { id: 'nat_news_2br', name: '2BR, 1BA', emoji: '🔑', cat: 'newspapers' },
  { id: 'nat_news_got_change', name: 'Got Change?', emoji: '❓', cat: 'newspapers' },
  { id: 'nat_news_hot_press', name: 'Hot Off the Presses', emoji: '☕', cat: 'newspapers' },
  { id: 'nat_news_ink_fingers', name: 'Ink-Stained Fingers', emoji: '🖐️', cat: 'newspapers' },

  // ── Long Distance Phone Wars (10) ──
  { id: 'nat_phone_big_breakup', name: 'The Big Breakup', emoji: '🏛️', cat: 'phoneWars' },
  { id: 'nat_phone_reach_out', name: 'Reach Out', emoji: '📞', cat: 'phoneWars' },
  { id: 'nat_phone_dial_diff', name: 'Dial the Difference', emoji: '☎️', cat: 'phoneWars' },
  { id: 'nat_phone_pin_drop', name: 'Pin-Drop Clear', emoji: '📌', cat: 'phoneWars' },
  { id: 'nat_phone_itemized', name: 'Itemized', emoji: '🧾', cat: 'phoneWars' },
  { id: 'nat_phone_after_9', name: 'After 9 PM', emoji: '🌙', cat: 'phoneWars' },
  { id: 'nat_phone_deposit_coins', name: 'Deposit More Coins', emoji: '🪙', cat: 'phoneWars' },
  { id: 'nat_phone_operators', name: 'Operators Standing By', emoji: '👥', cat: 'phoneWars' },
  { id: 'nat_phone_touch_tone', name: 'Touch-Tone', emoji: '💋', cat: 'phoneWars' },
  { id: 'nat_phone_connect_call', name: 'Connect the Call', emoji: '🏆', cat: 'phoneWars' },

  // ── Film Development & Cameras (10) ──
  { id: 'nat_film_load_roll', name: 'Load the Roll', emoji: '🎞️', cat: 'film' },
  { id: 'nat_film_ready_hour', name: 'Ready in an Hour', emoji: '✨', cat: 'film' },
  { id: 'nat_film_watch_develop', name: 'Watch It Develop', emoji: '⏱️', cat: 'film' },
  { id: 'nat_film_spin_disc', name: 'Spin the Disc', emoji: '📀', cat: 'film' },
  { id: 'nat_film_drop_cartridge', name: 'Drop-In Cartridge', emoji: '📥', cat: 'film' },
  { id: 'nat_film_say_cheese', name: 'Say Cheese', emoji: '🧀', cat: 'film' },
  { id: 'nat_film_sticky_pages', name: 'Sticky Pages', emoji: '📋', cat: 'film' },
  { id: 'nat_film_focus_frame', name: 'Focus and Frame', emoji: '📸', cat: 'film' },
  { id: 'nat_film_next_slide', name: 'Next Slide, Please', emoji: '🎥', cat: 'film' },
  { id: 'nat_film_come_out', name: 'Did They Come Out?', emoji: '🤷', cat: 'film' },

  // ── Things That Scream 1984 (18) ──
  { id: 'nat_scream_whats_twenty', name: "What's Your Twenty?", emoji: '📟', cat: 'scream1984' },
  { id: 'nat_scream_cash_demand', name: 'Cash on Demand', emoji: '📺', cat: 'scream1984' },
  { id: 'nat_scream_coming_through', name: 'Coming Through', emoji: '➡️', cat: 'scream1984' },
  { id: 'nat_scream_catch_wave', name: 'Catch a Wave', emoji: '🌊', cat: 'scream1984' },
  { id: 'nat_scream_read_mood', name: 'Read My Mood', emoji: '📖', cat: 'scream1984' },
  { id: 'nat_scream_press_it', name: 'Press It On', emoji: '👔', cat: 'scream1984' },
  { id: 'nat_scream_feel_burn', name: 'Feel the Burn', emoji: '🔥', cat: 'scream1984' },
  { id: 'nat_scream_step_inside', name: 'Step Inside', emoji: '🚶', cat: 'scream1984' },
  { id: 'nat_scream_pile_wayback', name: 'Pile in the Way-Back', emoji: '🚚', cat: 'scream1984' },
  { id: 'nat_scream_scratch_sniff', name: 'Scratch & Sniff', emoji: '🌸', cat: 'scream1984' },
  { id: 'nat_scream_adjust_antenna', name: 'Adjust the Antenna', emoji: '📡', cat: 'scream1984' },
  { id: 'nat_scream_dont_stay_up', name: "Don't Stay Up Too Late", emoji: '🌙', cat: 'scream1984' },
  { id: 'nat_scream_spin_wheel', name: 'Spin the Wheel', emoji: '🎡', cat: 'scream1984' },
  { id: 'nat_scream_carriage_return', name: 'Carriage Return', emoji: '📃', cat: 'scream1984' },
  { id: 'nat_scream_change_channel', name: 'Change the Channel', emoji: '🎛️', cat: 'scream1984' },
  { id: 'nat_scream_fill_er_up', name: "Fill 'Er Up", emoji: '🎞️', cat: 'scream1984' },
  { id: 'nat_scream_must_see', name: 'Must-See Listings', emoji: '📋', cat: 'scream1984' },
  { id: 'nat_scream_totally_rad', name: 'Totally Rad', emoji: '🔺', cat: 'scream1984' },

  // ── 1984 Mall Culture (20) ──
  { id: 'nat_mall_grab_tray', name: 'Grab a Tray', emoji: '🥨', cat: 'mall' },
  { id: 'nat_mall_frothy_cold', name: 'Frothy and Cold', emoji: '🥤', cat: 'mall' },
  { id: 'nat_mall_browse_racks', name: 'Browse the Racks', emoji: '👕', cat: 'mall' },
  { id: 'nat_mall_weird_store', name: 'The Weird Store', emoji: '👻', cat: 'mall' },
  { id: 'nat_mall_flip_bins', name: 'Flip Through the Bins', emoji: '🎰', cat: 'mall' },
  { id: 'nat_mall_quarter_machine', name: 'Quarter on the Machine', emoji: '🪙', cat: 'mall' },
  { id: 'nat_mall_free_sample', name: 'Free Sample', emoji: '🍦', cat: 'mall' },
  { id: 'nat_mall_ride_escalator', name: 'Ride the Escalator', emoji: '🏗️', cat: 'mall' },
  { id: 'nat_mall_stonewashed', name: 'Stonewashed', emoji: '👖', cat: 'mall' },
  { id: 'nat_mall_lace_em', name: "Lace 'Em Up", emoji: '👟', cat: 'mall' },
  { id: 'nat_mall_twist_salt', name: 'Twist and Salt', emoji: '🥨', cat: 'mall' },
  { id: 'nat_mall_four_poses', name: 'Four Poses', emoji: '📸', cat: 'mall' },
  { id: 'nat_mall_make_wish', name: 'Make a Wish', emoji: '🌟', cat: 'mall' },
  { id: 'nat_mall_puppy_window', name: 'Puppy in the Window', emoji: '🐶', cat: 'mall' },
  { id: 'nat_mall_by_scoop', name: 'By the Scoop', emoji: '🍨', cat: 'mall' },
  { id: 'nat_mall_pick_card', name: 'Pick a Card', emoji: '💌', cat: 'mall' },
  { id: 'nat_mall_gadgets', name: 'Gadgets & Gizmos', emoji: '🎮', cat: 'mall' },
  { id: 'nat_mall_catch_flick', name: 'Catch a Flick', emoji: '🎥', cat: 'mall' },
  { id: 'nat_mall_picture_santa', name: 'Picture with Santa', emoji: '🌲', cat: 'mall' },
  { id: 'nat_mall_mall_rat', name: 'Mall Rat', emoji: '🐀', cat: 'mall' },

  // ── Home Video Format Wars (12) ──
  { id: 'nat_fmt_pick_side', name: 'Pick a Side', emoji: '⚔️', cat: 'formatWars' },
  { id: 'nat_fmt_team_vhs', name: 'Team VHS', emoji: '📼', cat: 'formatWars' },
  { id: 'nat_fmt_team_beta', name: 'Team Beta', emoji: '🅱️', cat: 'formatWars' },
  { id: 'nat_fmt_flip_disc', name: 'Flip the Disc', emoji: '💿', cat: 'formatWars' },
  { id: 'nat_fmt_set_timer', name: 'Set the Timer', emoji: '⏱️', cat: 'formatWars' },
  { id: 'nat_fmt_blinking_12', name: 'Blinking 12:00', emoji: '🕛', cat: 'formatWars' },
  { id: 'nat_fmt_tape_over', name: 'Tape Over It', emoji: '📼', cat: 'formatWars' },
  { id: 'nat_fmt_be_kind', name: 'Be Kind, Rewind', emoji: '🎥', cat: 'formatWars' },
  { id: 'nat_fmt_adjust_tracking', name: 'Adjust the Tracking', emoji: '📈', cat: 'formatWars' },
  { id: 'nat_fmt_fast_forward', name: 'Fast-Forward the Previews', emoji: '⏭️', cat: 'formatWars' },
  { id: 'nat_fmt_ka_chunk', name: 'Ka-Chunk', emoji: '💥', cat: 'formatWars' },
  { id: 'nat_fmt_movie_night', name: 'Movie Night', emoji: '🎬', cat: 'formatWars' },

  // ── County Fairs & Americana (14) ──
  { id: 'nat_fair_top_wheel', name: 'Top of the Wheel', emoji: '🎡', cat: 'countyFair' },
  { id: 'nat_fair_win_prize', name: 'Win the Big Prize', emoji: '🎟️', cat: 'countyFair' },
  { id: 'nat_fair_powdered_sugar', name: 'Powdered Sugar', emoji: '🍩', cat: 'countyFair' },
  { id: 'nat_fair_spun_sugar', name: 'Spun Sugar', emoji: '🍭', cat: 'countyFair' },
  { id: 'nat_fair_blue_ribbon', name: 'Blue Ribbon', emoji: '🎗️', cat: 'countyFair' },
  { id: 'nat_fair_best_show', name: 'Best in Show', emoji: '🥇', cat: 'countyFair' },
  { id: 'nat_fair_prize_pumpkin', name: 'Prize Pumpkin', emoji: '🎃', cat: 'countyFair' },
  { id: 'nat_fair_last_car', name: 'Last Car Running', emoji: '🚗', cat: 'countyFair' },
  { id: 'nat_fair_full_pull', name: 'Full Pull', emoji: '🕹️', cat: 'countyFair' },
  { id: 'nat_fair_feed_goats', name: 'Feed the Goats', emoji: '🐐', cat: 'countyFair' },
  { id: 'nat_fair_here_comes_band', name: 'Here Comes the Band', emoji: '🎷', cat: 'countyFair' },
  { id: 'nat_fair_crowned', name: 'Crowned', emoji: '👑', cat: 'countyFair' },
  { id: 'nat_fair_midway_lights', name: 'Midway Lights', emoji: '🎢', cat: 'countyFair' },
  { id: 'nat_fair_sleepy_drive', name: 'Sleepy Drive Home', emoji: '😴', cat: 'countyFair' },

  // ── Music & MTV (23) ──
  { id: 'nat_mus_video_killed', name: 'Video Killed the Radio Star', emoji: '📺', cat: 'music' },
  { id: 'nat_mus_one_glove', name: 'One Glove', emoji: '🧤', cat: 'music' },
  { id: 'nat_mus_purple_reign', name: 'Purple Reign', emoji: '💜', cat: 'music' },
  { id: 'nat_mus_like_star', name: 'Like a Star', emoji: '⭐', cat: 'music' },
  { id: 'nat_mus_the_boss', name: 'The Boss', emoji: '🕶️', cat: 'music' },
  { id: 'nat_mus_jump', name: 'Jump', emoji: '🤸', cat: 'music' },
  { id: 'nat_mus_true_colors', name: 'True Colors', emoji: '🌈', cat: 'music' },
  { id: 'nat_mus_press_play', name: 'Press Play', emoji: '🎧', cat: 'music' },
  { id: 'nat_mus_hit_record', name: 'Hit Record', emoji: '💿', cat: 'music' },
  { id: 'nat_mus_number_one', name: 'Number One', emoji: '🥇', cat: 'music' },
  { id: 'nat_mus_pump_volume', name: 'Pump Up the Volume', emoji: '🔊', cat: 'music' },
  { id: 'nat_mus_on_mic', name: 'On the Mic', emoji: '🎙️', cat: 'music' },
  { id: 'nat_mus_synthesize', name: 'Synthesize', emoji: '🎹', cat: 'music' },
  { id: 'nat_mus_simply_best', name: 'Simply the Best', emoji: '🎸', cat: 'music' },
  { id: 'nat_mus_second_invasion', name: 'Second Invasion', emoji: '🛸', cat: 'music' },
  { id: 'nat_mus_lighters_up', name: 'Lighters Up', emoji: '🔦', cat: 'music' },
  { id: 'nat_mus_side_a_b', name: 'Side A, Side B', emoji: '📻', cat: 'music' },
  { id: 'nat_mus_tour_tee', name: 'Tour Tee', emoji: '👕', cat: 'music' },
  { id: 'nat_mus_world_premiere', name: 'World Premiere', emoji: '🎥', cat: 'music' },
  { id: 'nat_mus_sweep_awards', name: 'Sweep the Awards', emoji: '🧹', cat: 'music' },
  { id: 'nat_mus_hit_floor', name: 'Hit the Floor', emoji: '💃', cat: 'music' },
  { id: 'nat_mus_one_done', name: 'One and Done', emoji: '✨', cat: 'music' },
  { id: 'nat_mus_greatest_year', name: 'Greatest Year', emoji: '🌍', cat: 'music' },

  // ── Cars & the Road (13) ──
  { id: 'nat_car_sliding_door', name: 'Sliding Door', emoji: '🚗', cat: 'cars' },
  { id: 'nat_car_pop_up', name: 'Pop-Up Headlights', emoji: '🚘', cat: 'cars' },
  { id: 'nat_car_thrifty_miles', name: 'Thrifty Miles', emoji: '⛽', cat: 'cars' },
  { id: 'nat_car_v8_rumble', name: 'V8 Rumble', emoji: '🏎️', cat: 'cars' },
  { id: 'nat_car_calling_car', name: 'Calling from the Car', emoji: '📱', cat: 'cars' },
  { id: 'nat_car_order_speaker', name: 'Order at the Speaker', emoji: '🗣️', cat: 'cars' },
  { id: 'nat_car_are_we_there', name: 'Are We There Yet?', emoji: '🛣️', cat: 'cars' },
  { id: 'nat_car_windows_down', name: 'Windows Down', emoji: '🪟', cat: 'cars' },
  { id: 'nat_car_top_off', name: 'Top Off the Tank', emoji: '⛽', cat: 'cars' },
  { id: 'nat_car_load_bed', name: 'Load the Bed', emoji: '📦', cat: 'cars' },
  { id: 'nat_car_murals_shag', name: 'Murals & Shag', emoji: '🌈', cat: 'cars' },
  { id: 'nat_car_roll_down', name: 'Roll Down the Window', emoji: '👐', cat: 'cars' },
  { id: 'nat_car_just_drive', name: 'Just Drive', emoji: '🏁', cat: 'cars' },

  // ── Saturday Morning Cartoons (25) ──
  { id: 'nat_toon_bowl_hand', name: 'Bowl in Hand', emoji: '🥣', cat: 'cartoons' },
  { id: 'nat_toon_transform', name: 'Transform!', emoji: '👑', cat: 'cartoons' },
  { id: 'nat_toon_knowing_half', name: 'Knowing Is Half the Battle', emoji: '🛡️', cat: 'cartoons' },
  { id: 'nat_toon_raise_sword', name: 'Raise the Sword', emoji: '⚔️', cat: 'cartoons' },
  { id: 'nat_toon_caring_stare', name: 'Caring Stare', emoji: '🌈', cat: 'cartoons' },
  { id: 'nat_toon_pint_sized', name: 'Pint-Sized', emoji: '✂️', cat: 'cartoons' },
  { id: 'nat_toon_thats_all', name: "That's All Folks", emoji: '🎬', cat: 'cartoons' },
  { id: 'nat_toon_unmask_villain', name: 'Unmask the Villain', emoji: '🎭', cat: 'cartoons' },
  { id: 'nat_toon_three_apples', name: 'Three Apples High', emoji: '🔵', cat: 'cartoons' },
  { id: 'nat_toon_game_on', name: 'Game On', emoji: '🎮', cat: 'cartoons' },
  { id: 'nat_toon_schoolhouse', name: 'Schoolhouse Smarts', emoji: '🏫', cat: 'cartoons' },
  { id: 'nat_toon_heroes', name: 'Heroes Assemble', emoji: '🦸', cat: 'cartoons' },
  { id: 'nat_toon_wacky', name: 'Wacky Antics', emoji: '🐒', cat: 'cartoons' },
  { id: 'nat_toon_collect_all', name: 'Collect Them All', emoji: '📦', cat: 'cartoons' },
  { id: 'nat_toon_i_want_that', name: 'I Want That One', emoji: '🦖', cat: 'cartoons' },
  { id: 'nat_toon_puppet_show', name: 'Puppet Show', emoji: '🎭', cat: 'cartoons' },
  { id: 'nat_toon_yabba', name: 'Yabba Fun', emoji: '🤡', cat: 'cartoons' },
  { id: 'nat_toon_blast_off', name: 'Blast Off', emoji: '🚀', cat: 'cartoons' },
  { id: 'nat_toon_checkered', name: 'Checkered Flag', emoji: '🏁', cat: 'cartoons' },
  { id: 'nat_toon_boo', name: 'Boo!', emoji: '👻', cat: 'cartoons' },
  { id: 'nat_toon_stay_tuned', name: 'Stay Tuned', emoji: '💼', cat: 'cartoons' },
  { id: 'nat_toon_toon_box', name: 'Toon on the Box', emoji: '📦', cat: 'cartoons' },
  { id: 'nat_toon_go_outside', name: 'Go Outside and Play', emoji: '☀️', cat: 'cartoons' },
  { id: 'nat_toon_show_off', name: 'Show It Off', emoji: '✨', cat: 'cartoons' },
  { id: 'nat_toon_saturday_magic', name: 'Saturday Magic', emoji: '📺', cat: 'cartoons' },

  // ── Cereal & Their Mascots (15) ──
  { id: 'nat_cer_pick_box', name: 'Pick a Box', emoji: '🛒', cat: 'cereal' },
  { id: 'nat_cer_prize_bottom', name: 'Prize at the Bottom', emoji: '🎁', cat: 'cereal' },
  { id: 'nat_cer_grreat', name: 'Grrreat', emoji: '😋', cat: 'cereal' },
  { id: 'nat_cer_monster_mash', name: 'Monster Mash', emoji: '👹', cat: 'cereal' },
  { id: 'nat_cer_catch_charms', name: 'Catch the Charms', emoji: '🥣', cat: 'cereal' },
  { id: 'nat_cer_follow_nose', name: 'Follow Your Nose', emoji: '👃', cat: 'cereal' },
  { id: 'nat_cer_sugar_rush', name: 'Sugar Rush', emoji: '🍬', cat: 'cereal' },
  { id: 'nat_cer_balanced', name: 'Balanced Breakfast', emoji: '🔍', cat: 'cereal' },
  { id: 'nat_cer_solve_maze', name: 'Solve the Maze', emoji: '🧩', cat: 'cereal' },
  { id: 'nat_cer_6_to_8', name: '6 to 8 Weeks', emoji: '📅', cat: 'cereal' },
  { id: 'nat_cer_on_box', name: 'On the Box', emoji: '📦', cat: 'cereal' },
  { id: 'nat_cer_eat_bran', name: 'Eat Your Bran', emoji: '🌾', cat: 'cereal' },
  { id: 'nat_cer_bowl_knees', name: 'Bowl on the Knees', emoji: '🥣', cat: 'cereal' },
  { id: 'nat_cer_drink_milk', name: 'Drink the Milk', emoji: '🥛', cat: 'cereal' },
  { id: 'nat_cer_breakfast_champs', name: 'Breakfast of Champions', emoji: '🥣', cat: 'cereal' },

  // ── Ballpark Promo Nights & Giveaways (25) ──
  { id: 'nat_promo_free_bat', name: 'Free Bat', emoji: '🏏', cat: 'promoNights' },
  { id: 'nat_promo_light_sky', name: 'Light Up the Sky', emoji: '🎆', cat: 'promoNights' },
  { id: 'nat_promo_lid', name: 'Lid for Everyone', emoji: '🧢', cat: 'promoNights' },
  { id: 'nat_promo_lucky_seat', name: 'Lucky Seat Number', emoji: '🎫', cat: 'promoNights' },
  { id: 'nat_promo_legends_return', name: 'The Legends Return', emoji: '🔙', cat: 'promoNights' },
  { id: 'nat_promo_buck_dog', name: 'Buck a Dog', emoji: '🌭', cat: 'promoNights' },
  { id: 'nat_promo_play_ball', name: 'Play Ball', emoji: '⚾', cat: 'promoNights' },
  { id: 'nat_promo_up_close', name: 'Up Close', emoji: '📷', cat: 'promoNights' },
  { id: 'nat_promo_helmet', name: 'Helmet On', emoji: '⛑️', cat: 'promoNights' },
  { id: 'nat_promo_suit_up', name: 'Suit Up', emoji: '👔', cat: 'promoNights' },
  { id: 'nat_promo_spin_stagger', name: 'Spin and Stagger', emoji: '🌀', cat: 'promoNights' },
  { id: 'nat_promo_take_me_out', name: 'Take Me Out', emoji: '💨', cat: 'promoNights' },
  { id: 'nat_promo_free_baseball', name: 'Free Baseball', emoji: '🆓', cat: 'promoNights' },
  { id: 'nat_promo_bark_park', name: 'Bark in the Park', emoji: '🌳', cat: 'promoNights' },
  { id: 'nat_promo_goldfish', name: 'Goldfish in the Stands', emoji: '🐠', cat: 'promoNights' },
  { id: 'nat_promo_may_force', name: 'May the Force', emoji: '🚀', cat: 'promoNights' },
  { id: 'nat_promo_wave_towel', name: 'Wave the Towel', emoji: '🧣', cat: 'promoNights' },
  { id: 'nat_promo_tacky', name: 'Tacky and Proud', emoji: '🎀', cat: 'promoNights' },
  { id: 'nat_promo_dregs', name: 'Dregs of Humanity Live', emoji: '🧬', cat: 'promoNights' },
  { id: 'nat_promo_fresh_socks', name: 'Fresh Socks', emoji: '🧦', cat: 'promoNights' },
  { id: 'nat_promo_cape', name: 'Cape Crusader', emoji: '🧥', cat: 'promoNights' },
  { id: 'nat_promo_jammies', name: 'Jammies On', emoji: '🌙', cat: 'promoNights' },
  { id: 'nat_promo_party_back', name: 'Party in the Back', emoji: '🥳', cat: 'promoNights' },
  { id: 'nat_promo_number_one', name: "We're Number One", emoji: '☝️', cat: 'promoNights' },
  { id: 'nat_promo_mascot_mayhem', name: 'Mascot Mayhem', emoji: '🎭', cat: 'promoNights' },
];

// Build hidden category achievements (16 total — categories that have a "collect whole category" hidden achievement)
export const NATIONAL_HIDDEN_ACHIEVEMENTS = Object.entries(NATIONAL_CATEGORIES)
  .filter(([, info]) => info.hiddenName)
  .map(([slug, info]) => ({
    id: `nat_hidden_${slug}`,
    name: info.hiddenName,
    desc: `Collect all ${NATIONAL_CATEGORIES[slug].name} window achievements`,
    icon: '🏆',
    category: 'bannerHidden',
    hiddenForCategory: slug,
  }));

// Full export: all 370 national achievements (354 window + 16 hidden)
export const NATIONAL_BANNER_ACHIEVEMENTS = [
  ...NATIONAL_WINDOW_ACHIEVEMENTS.map(a => ({
    id: a.id,
    name: a.name,
    desc: `${NATIONAL_CATEGORIES[a.cat].name}: ${a.name}`,
    icon: a.emoji,
    category: 'bannerNational',
    catSlug: a.cat,
  })),
  ...NATIONAL_HIDDEN_ACHIEVEMENTS,
];

// Map: category slug → array of window achievement IDs in that category
export const NATIONAL_CATEGORY_ACH_IDS = NATIONAL_WINDOW_ACHIEVEMENTS.reduce((acc, a) => {
  if (!acc[a.cat]) acc[a.cat] = [];
  acc[a.cat].push(a.id);
  return acc;
}, {});

// Map: category slug → hidden achievement ID
export const NATIONAL_HIDDEN_ACH_ID = Object.fromEntries(
  Object.entries(NATIONAL_CATEGORIES)
    .filter(([, info]) => info.hiddenName)
    .map(([slug]) => [slug, `nat_hidden_${slug}`])
);

/**
 * Check if any hidden category achievements should unlock based on collected window achievements.
 * @param {function} unlockFn - The unlockAchievement function
 */
export function checkNationalCategoryAchievements(unlockFn) {
  if (!unlockFn) return;
  const stored = JSON.parse(localStorage.getItem('bb84_achievements') || '{}');
  for (const [slug, windowIds] of Object.entries(NATIONAL_CATEGORY_ACH_IDS)) {
    const hiddenId = NATIONAL_HIDDEN_ACH_ID[slug];
    if (hiddenId && !stored[hiddenId] && windowIds.every(id => stored[id])) {
      unlockFn(hiddenId);
    }
  }
}