// Continuation: Arcade Games, Home Computers, Weird Tech, Products, Music, PSAs

// ── ARCADE GAMES (#526-540 & #651-675 combined) ──
export const ARCADE_GAMES = [
  {
    id: 'arcade_526',
    title: 'Dragon\'s Lair',
    icon: '🐉',
    color: '#ef4444',
    anim: 'flame',
    matchText: 'Visit your local arcade and try Dragon\'s Lair.',
    type: 'arcade',
    body: `DRAGON'S LAIR - The Arcade Game That Changed Everything

Dragon's Lair, released in 1983, revolutionized arcade gaming by featuring the first fully animated graphics generated by computer animation instead of pixel graphics.

THE BREAKTHROUGH
Using LaserDisc technology, Dragon's Lair displayed beautiful, fluid animations that made it look like a playable cartoon. Players controlled a knight named Dirk the Daring as he navigated a wizard's castle to rescue Princess Daphne.

THE GAMEPLAY
Rather than traditional joystick-based action, Dragon's Lair required quick reactions to on-screen prompts—dodge left when Dirk needed to avoid a boulder, thrust your sword when an enemy appeared.

THE PHENOMENON
Arcades nationwide reported lines of players waiting to spend quarters trying to survive the wizard's challenges. The game became the highest-grossing arcade game ever at its time.

THE LEGACY
Dragon's Lair proved that animation and graphics could drive arcade appeal, inspiring a generation of games focused on cinematic presentation.`,
  },
  {
    id: 'arcade_527',
    title: 'Pole Position',
    icon: '🏎️',
    color: '#f97316',
    anim: 'drive',
    matchText: 'Challenge your friends to a game of Pole Position.',
    type: 'arcade',
    body: `POLE POSITION - Racing Into the Future

Released in 1982, Pole Position was the arcade game that defined racing sims for a generation, featuring a sitting cabinet where players gripped a steering wheel and felt the road vibrate beneath them.

THE IMMERSION
The deluxe arcade cabinet featured a force-feedback steering wheel, an accelerator pedal, and brake pedal, creating unprecedented immersion in a racing experience.

THE TRACKS
Players raced through digitized versions of famous racing circuits, with Fuji International Speedway as the featured track. Completing laps unlocked new courses.

THE CHALLENGE
The game demanded precision—hitting cones slowed you down, running off the track was instant failure. Victory required memorizing the track layout and racing line.

THE ARCADE LEGACY
Pole Position was so popular that it inspired an entire subgenre of arcade racing games and proved that simulation-style gameplay could compete with action games for quarters.`,
  },
  {
    id: 'arcade_528',
    title: 'Q*bert',
    icon: '🔷',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'The arcade hit Q*bert is waiting.',
    type: 'arcade',
    body: `Q*BERT - A Puzzle-Action Phenomenon

Q*bert, released in 1982, introduced a unique isometric perspective that became instantly iconic, featuring a cute alien character bouncing on a pyramid of cubes.

THE CHARACTER
Q*bert is a small, orange creature with a long snout, one eye, and an inexplicable ability to bounce on a three-dimensional pyramid. His design became beloved by arcade fans.

THE PUZZLE
Players must change the color of every cube on a pyramid by bouncing on it, while avoiding enemies and bouncing balls that patrol the structure.

THE MECHANICS
Q*bert can't move freely—only diagonal bounces are possible. Players must strategize movements to color all cubes while evading enemies and finding escape routes.

THE ACHIEVEMENT
Q*bert proved that arcade games didn't need complex narratives or intense action. A simple, clever mechanic executed brilliantly could create lasting appeal and cultural impact.`,
  },
  {
    id: 'arcade_529',
    title: 'Zaxxon',
    icon: '✈️',
    color: '#3b82f6',
    anim: 'drive',
    matchText: 'Can you master Zaxxon?',
    type: 'arcade',
    body: `ZAXXON - The Isometric 3D Pioneer

Zaxxon, released in 1982, was one of the first games to use isometric perspective, giving players a unique view of a space fortress they must navigate as a starfighter.

THE VIEW
The isometric perspective gave Zaxxon a pseudo-3D appearance, creating depth and spatial relationships that felt revolutionary compared to traditional side-scrolling games.

THE MISSION
Players pilot a fighter ship through an enemy space fortress, dodging obstacles, enemy fire, and terrain hazards while collecting fuel and bonus points.

THE CHALLENGE
Flying through narrow passages requires precision, and the constantly scrolling environment creates urgency. Fuel management adds strategic depth.

THE INFLUENCE
Zaxxon's visual style influenced countless games and proved that isometric perspective could create engaging, playable experiences in arcade games.`,
  },
  {
    id: 'arcade_530',
    title: 'Donkey Kong',
    icon: '🦍',
    color: '#fbbf24',
    anim: 'bounce',
    matchText: 'The arcade phenomenon Donkey Kong is still drawing crowds.',
    type: 'arcade',
    body: `DONKEY KONG - The Game That Started It All

Released in 1981, Donkey Kong introduced the world to Mario (originally called Jumpman) and became one of the most iconic and influential arcade games ever created.

THE PREMISE
A giant ape (Donkey Kong) has kidnapped a damsel in distress at the top of a construction site. The player must guide a small carpenter up ladders and across platforms while avoiding barrels and hazards.

THE INNOVATION
Donkey Kong proved that arcade games could tell a story, feature relatable characters, and use humor alongside action to create engaging entertainment.

THE CHARACTER
Mario became gaming's most recognizable character, launching a franchise that would define home video games for decades. His simplicity belied his staying power.

THE LEGACY
Donkey Kong legitimized arcade gaming as serious entertainment and paved the way for the entire video game industry that followed.`,
  },
  {
    id: 'arcade_531',
    title: 'Galaga',
    icon: '👾',
    color: '#a855f7',
    anim: 'pulse',
    matchText: 'Challenge the high score in Galaga.',
    type: 'arcade',
    body: `GALAGA - Space Shooter Excellence

Galaga, released in 1981, perfected the space shooter formula with intense action, strategic depth, and increasingly challenging waves of alien enemies.

THE GAMEPLAY
Controlling a small space fighter at the bottom of the screen, players must shoot down waves of alien invaders descending in formation, dodging their fire.

THE TENSION
As waves progress, aliens move faster and shoot more frequently. The difficulty curve is perfectly balanced, making the game accessible to newcomers but challenging for veterans.

THE STRATEGY
Players can position themselves to create angles for multi-hit shots. Catching power-ups during combat provides temporary advantages but requires risky positioning.

THE ACHIEVEMENT
Galaga became one of the most successful arcade games because it rewarded both twitch reflexes and tactical thinking, creating depth underneath the simple premise.`,
  },
  {
    id: 'arcade_532',
    title: 'Centipede',
    icon: '🐛',
    color: '#ef4444',
    anim: 'wave',
    matchText: 'Centipede remains one of America\'s favorite arcade games.',
    type: 'arcade',
    body: `CENTIPEDE - Strategy Meets Action

Centipede, released in 1980, combined action-based gameplay with puzzle-like strategy as players controlled a small creature shooting at a descending centipede.

THE SETTING
Viewed from above, the player controls a small insect at the bottom of the screen while a centipede made of segments descends through mushroom fields.

THE MECHANIC
Shooting the centipede's head causes it to split into two shorter segments, eventually creating many independent segments to track and destroy.

THE CHALLENGE
Mushrooms act as obstacles and cover, forcing players to strategically navigate the field while keeping track of multiple threats and planning shots.

THE APPEAL
Centipede appealed to a broader audience than typical arcade games, attracting players who enjoyed puzzle-like problem-solving alongside quick reflexes.`,
  },
  {
    id: 'arcade_533',
    title: 'Defender',
    icon: '🛸',
    color: '#06b6d4',
    anim: 'drive',
    matchText: 'Defender continues to challenge players.',
    type: 'arcade',
    body: `DEFENDER - The Arcade Classic

Defender, released in 1980, challenged players to protect a planet from descending alien invaders in one of the most complex arcade control schemes of its era.

THE CONTROLS
Defender's control panel was overwhelming—five buttons controlling movement, fire, smart bomb, and screen views. Mastering it took dedication and practice.

THE CHALLENGE
Aliens descend to kidnap humans, which must be rescued. Defending the planet required constant movement, strategic bomb placement, and resource management.

THE DEPTH
Unlike simpler space shooters, Defender required planning and adaptation. Different alien types required different strategies, and protecting humans added moral dimension.

THE LEGACY
Defender proved that arcade games could be complex, challenging, and reward skilled, experienced players willing to invest time in mastery.`,
  },
  {
    id: 'arcade_534',
    title: 'Robotron: 2084',
    icon: '🤖',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'See if you can survive Robotron 2084.',
    type: 'arcade',
    body: `ROBOTRON: 2084 - Maximum Arcade Action

Released in 1982, Robotron: 2084 featured two joysticks creating dual-stick arcade gameplay decades before modern gaming popularized the control scheme.

THE PREMISE
In a dystopian future, a lone human must defend humanity against waves of robots using a unique two-joystick control system.

THE INNOVATION
One joystick controlled movement, the other controlled firing direction independently. This allowed strafing, a technique revolutionary for 1982 arcade gaming.

THE INTENSITY
Robotron is relentless—hundreds of enemies appear simultaneously, demanding constant movement, rapid aiming, and split-second decision-making.

THE SKILL CEILING
While accessible to casual players, Robotron rewarded experienced players with techniques and positioning strategies that separated champions from novices.`,
  },
  {
    id: 'arcade_535',
    title: 'Ms. Pac-Man',
    icon: '👾',
    color: '#fbbf24',
    anim: 'pulse',
    matchText: 'Ms. Pac-Man remains a favorite with players of all ages.',
    type: 'arcade',
    body: `MS. PAC-MAN - A Sequel That Surpassed

Released in 1981, Ms. Pac-Man was initially a fan-created mod of Pac-Man that became so popular, Atari officially released it as a standalone game.

THE EVOLUTION
Ms. Pac-Man retained the core Pac-Man gameplay but added visual variety, new mazes, bonus items, and subtle AI improvements that made the game more engaging.

THE CHARACTER
Ms. Pac-Man, the first significant female video game character, became iconic in her own right, appealing to players who found Pac-Man's simplicity limiting.

THE GAMEPLAY
New maze designs required different strategies, and the ghosts' AI was improved to make them more unpredictable and challenging.

THE SUCCESS
Ms. Pac-Man rivaled the original's popularity, proving that sequels could be better, and that games could evolve while respecting their source material.`,
  },
  {
    id: 'arcade_536',
    title: 'Joust',
    icon: '🦅',
    color: '#a855f7',
    anim: 'bounce',
    matchText: 'Joust continues to attract competitors.',
    type: 'arcade',
    body: `JOUST - Arcade Brilliance

Joust, released in 1982, featured a knight riding an ostrich, jousting against enemy knights in an action-puzzle game of timing and positioning.

THE PREMISE
Players control a knight on an ostrich, flying upward to joust enemies. The twist—height advantage determines victory, making positioning crucial.

THE MECHANIC
Attacking an enemy requires being above them. Complex flight physics meant high-scoring players developed intricate maneuvering techniques.

THE MULTIPLAYER
Joust featured excellent two-player cooperative gameplay where players could choose to compete or cooperate, adding strategic depth.

THE LEGACY
Joust proved that simple premises could create sophisticated gameplay when executed brilliantly, creating a cult following that endures today.`,
  },
];

// ── HOME COMPUTERS (#541-550) ──
export const HOME_COMPUTERS = [
  {
    id: 'computer_541',
    title: 'The Commodore 64',
    icon: '💻',
    color: '#3b82f6',
    anim: 'pulse',
    matchText: 'The Commodore 64 is changing the way America computes.',
    type: 'computer',
    body: `COMMODORE 64 - The Computer That Changed Everything

Announced in 1982 and hitting the market in 1984, the Commodore 64 is the most affordable home computer available, retailing for just $595.

TECHNICAL SPECS
- Processor: MOS Technology 6510 (1 MHz)
- RAM: 64KB (hence the name)
- Graphics: 320×200 resolution, 16-color palette
- Sound: Three-voice synthesizer chip (SID)
- Storage: Cassette or 5.25" floppy drive

THE APPEAL
At $595, the C64 costs half as much as competing computers while offering equal or superior performance. The included color monitor and joystick make it immediately usable.

THE SOFTWARE
Hundreds of games, educational programs, and productivity tools are available. The library grows monthly as independent developers create software.

THE FUTURE
Industry analysts predict the Commodore 64 will become America's most popular home computer, rivaling or surpassing the Apple II in market share.`,
  },
  {
    id: 'computer_542',
    title: 'Apple II',
    icon: '🍎',
    color: '#06b6d4',
    anim: 'pulse',
    matchText: 'Discover the future with the Apple IIe.',
    type: 'computer',
    body: `APPLE II - The Personal Computer Pioneer

The Apple II, introduced in 1977 and updated to the IIe in 1983, remains the leader in home and educational computing, dominating schools nationwide.

EDUCATIONAL DOMINANCE
Schools choose Apple II because it offers sophisticated educational software, including programs for learning math, science, reading, and computer fundamentals.

BUSINESS POTENTIAL
While pricier than competitors ($1,295 for the IIe), educators and businesspeople recognize its long-term value in developing computer literacy.

EXPANSION OPTIONS
The Apple II's open architecture allows users to add cards for printing, networking, and external storage, creating a customizable system.

THE LEGACY
Apple's early commitment to education ensures a generation of students grows up using Apple computers, building brand loyalty for the future.`,
  },
  {
    id: 'computer_543',
    title: 'Atari 800XL',
    icon: '🎮',
    color: '#f97316',
    anim: 'pulse',
    matchText: 'The Atari 800XL is available now.',
    type: 'computer',
    body: `ATARI 800XL - Entertainment and Education Combined

The Atari 800XL ($399) offers impressive capabilities for gaming enthusiasts and serious users, featuring 64KB of RAM and color graphics superior to Apple II.

FEATURES
- 6502 Processor (1.77 MHz)
- Built-in BASIC programming language
- 80 column text capability
- Powerful graphics and sound chips
- Large catalog of games and educational software

GAMING FOCUS
Where the Apple II focuses on education, Atari dominates gaming. Arcade-quality games like Pac-Man, Defender, and original titles draw gamers nationwide.

AFFORDABILITY
At $399, the 800XL undercuts Apple II pricing while offering better graphics and sound—perfect for families prioritizing entertainment.

THE CHOICE
Consumers choosing computers must decide: education (Apple), gaming (Atari), or business (IBM)—each serving different needs.`,
  },
  {
    id: 'computer_544',
    title: 'TRS-80 by Radio Shack',
    icon: '📻',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'The TRS-80 remains a trusted home computer.',
    type: 'computer',
    body: `TRS-80 - The Accessible Computer

Radio Shack's TRS-80 line, starting at $799, brought computing to neighborhoods through convenient Radio Shack retail locations nationwide.

AVAILABILITY
Radio Shack's ubiquity gave customers local support, financing options, and immediate assistance—advantages competitors couldn't match.

SOFTWARE ECOSYSTEM
Radio Shack actively supported software development, resulting in a strong library of business, educational, and entertainment titles.

TRAINING & SUPPORT
Radio Shack offered classes, manuals, and technical support that Apple and Commodore couldn't replicate through mail order.

THE STRATEGY
While not the most advanced computer, TRS-80 succeeded by prioritizing customer service and accessibility over pure technical specifications.`,
  },
  {
    id: 'computer_545',
    title: 'Home Computing',
    icon: '📱',
    color: '#06b6d4',
    anim: 'pulse',
    matchText: 'Bring home educational software for your family computer.',
    type: 'computer',
    body: `THE HOME COMPUTER REVOLUTION

1984 marks a turning point in American domestic technology. Home computers are transitioning from novelty luxury to essential household appliances.

THE TREND
Families purchasing computers cite education as the primary motivation. Parents view computer literacy as essential for children's future success.

THE REALITY
Most families lack knowledge about computers. Manufacturers must invest heavily in education and support, making early adopters feel confident.

THE FUTURE
Within a decade, computers may become as common as televisions. The families investing now will be ahead of the curve.

THE CHALLENGE
Software quality remains inconsistent. While some educational programs are brilliant, many are mediocre, making selection critical.`,
  },
];

// ── WEIRD TECHNOLOGY (#551-560) ──
export const WEIRD_TECHNOLOGY = [
  {
    id: 'tech_551',
    title: 'Compact Discs',
    icon: '💿',
    color: '#2563eb',
    anim: 'spin',
    matchText: 'Compact Discs may be the future of recorded music.',
    type: 'technology',
    body: `COMPACT DISC TECHNOLOGY - The Digital Future of Music

Philips and Sony have developed Compact Disc (CD) technology that stores music digitally on 4.7-inch discs, offering perfect sound quality and durability.

THE TECHNOLOGY
CDs use laser technology to read tiny pits on a reflective disc surface. No physical contact means no wear—CDs theoretically play perfectly thousands of times.

THE SOUND QUALITY
CD sound is digitally encoded at 44.1 kHz sampling rate, 16-bit depth, producing audio that exceeds vinyl records in clarity and consistency.

THE ADVANTAGES
- No surface noise
- No skipping or scratching
- Perfect portability
- Longer lifespan than cassettes
- Better fidelity than vinyl

THE ADOPTION CHALLENGE
CD players cost $800-$1,000, and CDs retail for $12-$16—expensive compared to cassettes at $6-$8. Widespread adoption depends on prices falling significantly.

THE PREDICTION
Industry observers believe CDs will eventually replace vinyl and cassettes, but the transition will take years as prices gradually decrease.`,
  },
  {
    id: 'tech_552',
    title: 'Cellular Telephones',
    icon: '📱',
    color: '#3b82f6',
    anim: 'pulse',
    matchText: 'Cellular telephones are now available in select markets.',
    type: 'technology',
    body: `CELLULAR PHONES - Mobile Communication Arrives

Limited cellular phone service is rolling out in select US cities, promising the future of mobile communication for wealthy early adopters.

THE TECHNOLOGY
Cellular networks use radio waves to connect phones to base stations distributed throughout a geographic area, allowing seamless handoff between stations.

CURRENT REALITY
Motorola and other manufacturers have developed portable cellular phones weighing 2-3 pounds, small enough for car mounting or briefcase carrying.

THE SERVICE
AT&T and other carriers are building networks in major cities. Service costs are substantial—$4,000-$5,000 for equipment, plus $50+ monthly for limited minutes.

THE FUTURE
Cellular phones will likely become more common and affordable, eventually replacing car phones and pay phones. The technology is still experimental but promising.

THE LIMITATION
Current phones require car mounting or special carrying cases. True pocket-sized mobile phones remain years away.`,
  },
  {
    id: 'tech_553',
    title: 'Fax Machines',
    icon: '📠',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'More businesses are using fax machines every day.',
    type: 'technology',
    body: `FAX MACHINES - Instant Document Transmission

Fax technology is revolutionizing business communication. Documents can be transmitted over phone lines in seconds, replacing overnight mail and couriers for urgent communication.

THE TECHNOLOGY
Fax machines scan documents and convert them to digital signals transmitted over phone lines, reconstructed as printed images on the receiving end.

THE BUSINESS IMPACT
Companies report increased efficiency from instant document transmission. Contracts, signatures, and information that previously required physical transport now arrive instantly.

THE SPEED
A single-page fax transmits in 30-60 seconds, while receiving requires just moments. Information that took days to deliver by mail now arrives in minutes.

THE ADOPTION
Fax machines remain expensive ($1,500-$3,000), limiting adoption to businesses where efficiency gains justify the investment.

THE FUTURE
As prices fall, faxes may become standard office equipment. Some predict every office will eventually have fax capability.`,
  },
  {
    id: 'tech_554',
    title: 'Word Processors',
    icon: '⌨️',
    color: '#06b6d4',
    anim: 'pulse',
    matchText: 'Word processors are replacing traditional typewriters.',
    type: 'technology',
    body: `WORD PROCESSORS - The Death of Typewriters

Dedicated word processors and computer word processing software are rapidly replacing mechanical typewriters in offices nationwide.

THE ADVANTAGE
Text editing on a word processor is dramatically faster than typewriters. Changes, corrections, and reformatting happen instantly without retyping pages.

THE TRANSITION
Writers, journalists, and office workers report that word processing increases productivity significantly. Pages that took hours to perfect now take minutes.

THE SOFTWARE
Programs like WordStar dominate the market, offering features like find-and-replace, formatting, and file management unimaginable on typewriters.

THE RESISTANCE
Some writers resist word processors, claiming typewriter mechanical feedback aids creativity. However, the efficiency advantages are undeniable.

THE FUTURE
Mechanical typewriters will likely become obsolete within a decade as word processing becomes standard in offices.`,
  },
];

// Continue with PRODUCTS, MUSIC, PSAs in a third file...