// Continuation: Arcade Games, Home Computers, Weird Tech, Products, Music, PSAs

// ── ARCADE GAMES (#526-540 & #651-675 combined) ──
export const ARCADE_GAMES = [
  {
    id: 'arcade_526',
    title: 'Dragon\'s Lair',
    icon: '🐉',
    color: '#ef4444',
    anim: 'flame',
    matchText: 'Visit your local arcade and try Dragon\'s Lair.',
    type: 'arcade',
    body: `DRAGON'S LAIR - The Arcade Game That Changed Everything

Dragon's Lair, released in 1983, revolutionized arcade gaming by featuring the first fully animated graphics generated by computer animation instead of pixel graphics.

THE BREAKTHROUGH
Using LaserDisc technology, Dragon's Lair displayed beautiful, fluid animations that made it look like a playable cartoon. Players controlled a knight named Dirk the Daring as he navigated a wizard's castle to rescue Princess Daphne.

THE GAMEPLAY
Rather than traditional joystick-based action, Dragon's Lair required quick reactions to on-screen prompts—dodge left when Dirk needed to avoid a boulder, thrust your sword when an enemy appeared.

THE PHENOMENON
Arcades nationwide reported lines of players waiting to spend quarters trying to survive the wizard's challenges. The game became the highest-grossing arcade game ever at its time.

THE LEGACY
Dragon's Lair proved that animation and graphics could drive arcade appeal, inspiring a generation of games focused on cinematic presentation.`,
  },
  {
    id: 'arcade_527',
    title: 'Pole Position',
    icon: '🏎️',
    color: '#f97316',
    anim: 'drive',
    matchText: 'Challenge your friends to a game of Pole Position.',
    type: 'arcade',
    body: `POLE POSITION - Racing Into the Future

Released in 1982, Pole Position was the arcade game that defined racing sims for a generation, featuring a sitting cabinet where players gripped a steering wheel and felt the road vibrate beneath them.

THE IMMERSION
The deluxe arcade cabinet featured a force-feedback steering wheel, an accelerator pedal, and brake pedal, creating unprecedented immersion in a racing experience.

THE TRACKS
Players raced through digitized versions of famous racing circuits, with Fuji International Speedway as the featured track. Completing laps unlocked new courses.

THE CHALLENGE
The game demanded precision—hitting cones slowed you down, running off the track was instant failure. Victory required memorizing the track layout and racing line.

THE ARCADE LEGACY
Pole Position was so popular that it inspired an entire subgenre of arcade racing games and proved that simulation-style gameplay could compete with action games for quarters.`,
  },
  {
    id: 'arcade_528',
    title: 'Q*bert',
    icon: '🔷',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'The arcade hit Q*bert is waiting.',
    type: 'arcade',
    body: `Q*BERT - A Puzzle-Action Phenomenon

Q*bert, released in 1982, introduced a unique isometric perspective that became instantly iconic, featuring a cute alien character bouncing on a pyramid of cubes.

THE CHARACTER
Q*bert is a small, orange creature with a long snout, one eye, and an inexplicable ability to bounce on a three-dimensional pyramid. His design became beloved by arcade fans.

THE PUZZLE
Players must change the color of every cube on a pyramid by bouncing on it, while avoiding enemies and bouncing balls that patrol the structure.

THE MECHANICS
Q*bert can't move freely—only diagonal bounces are possible. Players must strategize movements to color all cubes while evading enemies and finding escape routes.

THE ACHIEVEMENT
Q*bert proved that arcade games didn't need complex narratives or intense action. A simple, clever mechanic executed brilliantly could create lasting appeal and cultural impact.`,
  },
  {
    id: 'arcade_529',
    title: 'Zaxxon',
    icon: '✈️',
    color: '#3b82f6',
    anim: 'drive',
    matchText: 'Can you master Zaxxon?',
    type: 'arcade',
    body: `ZAXXON - The Isometric 3D Pioneer

Zaxxon, released in 1982, was one of the first games to use isometric perspective, giving players a unique view of a space fortress they must navigate as a starfighter.

THE VIEW
The isometric perspective gave Zaxxon a pseudo-3D appearance, creating depth and spatial relationships that felt revolutionary compared to traditional side-scrolling games.

THE MISSION
Players pilot a fighter ship through an enemy space fortress, dodging obstacles, enemy fire, and terrain hazards while collecting fuel and bonus points.

THE CHALLENGE
Flying through narrow passages requires precision, and the constantly scrolling environment creates urgency. Fuel management adds strategic depth.

THE INFLUENCE
Zaxxon's visual style influenced countless games and proved that isometric perspective could create engaging, playable experiences in arcade games.`,
  },
  {
    id: 'arcade_530',
    title: 'Donkey Kong',
    icon: '🦍',
    color: '#fbbf24',
    anim: 'bounce',
    matchText: 'The arcade phenomenon Donkey Kong is still drawing crowds.',
    type: 'arcade',
    body: `DONKEY KONG - The Game That Started It All

Released in 1981, Donkey Kong introduced the world to Mario (originally called Jumpman) and became one of the most iconic and influential arcade games ever created.

THE PREMISE
A giant ape (Donkey Kong) has kidnapped a damsel in distress at the top of a construction site. The player must guide a small carpenter up ladders and across platforms while avoiding barrels and hazards.

THE INNOVATION
Donkey Kong proved that arcade games could tell a story, feature relatable characters, and use humor alongside action to create engaging entertainment.

THE CHARACTER
Mario became gaming's most recognizable character, launching a franchise that would define home video games for decades. His simplicity belied his staying power.

THE LEGACY
Donkey Kong legitimized arcade gaming as serious entertainment and paved the way for the entire video game industry that followed.`,
  },
  {
    id: 'arcade_531',
    title: 'Galaga',
    icon: '👾',
    color: '#a855f7',
    anim: 'pulse',
    matchText: 'Challenge the high score in Galaga.',
    type: 'arcade',
    body: `GALAGA - Space Shooter Excellence

Galaga, released in 1981, perfected the space shooter formula with intense action, strategic depth, and increasingly challenging waves of alien enemies.

THE GAMEPLAY
Controlling a small space fighter at the bottom of the screen, players must shoot down waves of alien invaders descending in formation, dodging their fire.

THE TENSION
As waves progress, aliens move faster and shoot more frequently. The difficulty curve is perfectly balanced, making the game accessible to newcomers but challenging for veterans.

THE STRATEGY
Players can position themselves to create angles for multi-hit shots. Catching power-ups during combat provides temporary advantages but requires risky positioning.

THE ACHIEVEMENT
Galaga became one of the most successful arcade games because it rewarded both twitch reflexes and tactical thinking, creating depth underneath the simple premise.`,
  },
  {
    id: 'arcade_532',
    title: 'Centipede',
    icon: '🐛',
    color: '#ef4444',
    anim: 'wave',
    matchText: 'Centipede remains one of America\'s favorite arcade games.',
    type: 'arcade',
    body: `CENTIPEDE - Strategy Meets Action

Centipede, released in 1980, combined action-based gameplay with puzzle-like strategy as players controlled a small creature shooting at a descending centipede.

THE SETTING
Viewed from above, the player controls a small insect at the bottom of the screen while a centipede made of segments descends through mushroom fields.

THE MECHANIC
Shooting the centipede's head causes it to split into two shorter segments, eventually creating many independent segments to track and destroy.

THE CHALLENGE
Mushrooms act as obstacles and cover, forcing players to strategically navigate the field while keeping track of multiple threats and planning shots.

THE APPEAL
Centipede appealed to a broader audience than typical arcade games, attracting players who enjoyed puzzle-like problem-solving alongside quick reflexes.`,
  },
  {
    id: 'arcade_533',
    title: 'Defender',
    icon: '🛸',
    color: '#06b6d4',
    anim: 'drive',
    matchText: 'Defender continues to challenge players.',
    type: 'arcade',
    body: `DEFENDER - The Arcade Classic

Defender, released in 1980, challenged players to protect a planet from descending alien invaders in one of the most complex arcade control schemes of its era.

THE CONTROLS
Defender's control panel was overwhelming—five buttons controlling movement, fire, smart bomb, and screen views. Mastering it took dedication and practice.

THE CHALLENGE
Aliens descend to kidnap humans, which must be rescued. Defending the planet required constant movement, strategic bomb placement, and resource management.

THE DEPTH
Unlike simpler space shooters, Defender required planning and adaptation. Different alien types required different strategies, and protecting humans added moral dimension.

THE LEGACY
Defender proved that arcade games could be complex, challenging, and reward skilled, experienced players willing to invest time in mastery.`,
  },
  {
    id: 'arcade_534',
    title: 'Robotron: 2084',
    icon: '🤖',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'See if you can survive Robotron 2084.',
    type: 'arcade',
    body: `ROBOTRON: 2084 - Maximum Arcade Action

Released in 1982, Robotron: 2084 featured two joysticks creating dual-stick arcade gameplay decades before modern gaming popularized the control scheme.

THE PREMISE
In a dystopian future, a lone human must defend humanity against waves of robots using a unique two-joystick control system.

THE INNOVATION
One joystick controlled movement, the other controlled firing direction independently. This allowed strafing, a technique revolutionary for 1982 arcade gaming.

THE INTENSITY
Robotron is relentless—hundreds of enemies appear simultaneously, demanding constant movement, rapid aiming, and split-second decision-making.

THE SKILL CEILING
While accessible to casual players, Robotron rewarded experienced players with techniques and positioning strategies that separated champions from novices.`,
  },
  {
    id: 'arcade_535',
    title: 'Ms. Pac-Man',
    icon: '👾',
    color: '#fbbf24',
    anim: 'pulse',
    matchText: 'Ms. Pac-Man remains a favorite with players of all ages.',
    type: 'arcade',
    body: `MS. PAC-MAN - A Sequel That Surpassed

Released in 1981, Ms. Pac-Man was initially a fan-created mod of Pac-Man that became so popular, Atari officially released it as a standalone game.

THE EVOLUTION
Ms. Pac-Man retained the core Pac-Man gameplay but added visual variety, new mazes, bonus items, and subtle AI improvements that made the game more engaging.

THE CHARACTER
Ms. Pac-Man, the first significant female video game character, became iconic in her own right, appealing to players who found Pac-Man's simplicity limiting.

THE GAMEPLAY
New maze designs required different strategies, and the ghosts' AI was improved to make them more unpredictable and challenging.

THE SUCCESS
Ms. Pac-Man rivaled the original's popularity, proving that sequels could be better, and that games could evolve while respecting their source material.`,
  },
  {
    id: 'arcade_536',
    title: 'Joust',
    icon: '🦅',
    color: '#a855f7',
    anim: 'bounce',
    matchText: 'Joust continues to attract competitors.',
    type: 'arcade',
    body: `JOUST - Arcade Brilliance

Joust, released in 1982, featured a knight riding an ostrich, jousting against enemy knights in an action-puzzle game of timing and positioning.

THE PREMISE
Players control a knight on an ostrich, flying upward to joust enemies. The twist—height advantage determines victory, making positioning crucial.

THE MECHANIC
Attacking an enemy requires being above them. Complex flight physics meant high-scoring players developed intricate maneuvering techniques.

THE MULTIPLAYER
Joust featured excellent two-player cooperative gameplay where players could choose to compete or cooperate, adding strategic depth.

THE LEGACY
Joust proved that simple premises could create sophisticated gameplay when executed brilliantly, creating a cult following that endures today.`,
  },
];

// ── HOME COMPUTERS (#541-550) ──
export const HOME_COMPUTERS = [
  {
    id: 'computer_541',
    title: 'The Commodore 64',
    icon: '💻',
    color: '#3b82f6',
    anim: 'pulse',
    matchText: 'The Commodore 64 is changing the way America computes.',
    type: 'computer',
    body: `COMMODORE 64 - The Computer That Changed Everything

Announced in 1982 and hitting the market in 1984, the Commodore 64 is the most affordable home computer available, retailing for just $595.

TECHNICAL SPECS
- Processor: MOS Technology 6510 (1 MHz)
- RAM: 64KB (hence the name)
- Graphics: 320×200 resolution, 16-color palette
- Sound: Three-voice synthesizer chip (SID)
- Storage: Cassette or 5.25" floppy drive

THE APPEAL
At $595, the C64 costs half as much as competing computers while offering equal or superior performance. The included color monitor and joystick make it immediately usable.

THE SOFTWARE
Hundreds of games, educational programs, and productivity tools are available. The library grows monthly as independent developers create software.

THE FUTURE
Industry analysts predict the Commodore 64 will become America's most popular home computer, rivaling or surpassing the Apple II in market share.`,
  },
  {
    id: 'computer_542',
    title: 'Apple II',
    icon: '🍎',
    color: '#06b6d4',
    anim: 'pulse',
    matchText: 'Discover the future with the Apple IIe.',
    type: 'computer',
    body: `APPLE II - The Personal Computer Pioneer

The Apple II, introduced in 1977 and updated to the IIe in 1983, remains the leader in home and educational computing, dominating schools nationwide.

EDUCATIONAL DOMINANCE
Schools choose Apple II because it offers sophisticated educational software, including programs for learning math, science, reading, and computer fundamentals.

BUSINESS POTENTIAL
While pricier than competitors ($1,295 for the IIe), educators and businesspeople recognize its long-term value in developing computer literacy.

EXPANSION OPTIONS
The Apple II's open architecture allows users to add cards for printing, networking, and external storage, creating a customizable system.

THE LEGACY
Apple's early commitment to education ensures a generation of students grows up using Apple computers, building brand loyalty for the future.`,
  },
  {
    id: 'computer_543',
    title: 'Atari 800XL',
    icon: '🎮',
    color: '#f97316',
    anim: 'pulse',
    matchText: 'The Atari 800XL is available now.',
    type: 'computer',
    body: `ATARI 800XL - Entertainment and Education Combined

The Atari 800XL ($399) offers impressive capabilities for gaming enthusiasts and serious users, featuring 64KB of RAM and color graphics superior to Apple II.

FEATURES
- 6502 Processor (1.77 MHz)
- Built-in BASIC programming language
- 80 column text capability
- Powerful graphics and sound chips
- Large catalog of games and educational software

GAMING FOCUS
Where the Apple II focuses on education, Atari dominates gaming. Arcade-quality games like Pac-Man, Defender, and original titles draw gamers nationwide.

AFFORDABILITY
At $399, the 800XL undercuts Apple II pricing while offering better graphics and sound—perfect for families prioritizing entertainment.

THE CHOICE
Consumers choosing computers must decide: education (Apple), gaming (Atari), or business (IBM)—each serving different needs.`,
  },
  {
    id: 'computer_544',
    title: 'TRS-80 by Radio Shack',
    icon: '📻',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'The TRS-80 remains a trusted home computer.',
    type: 'computer',
    body: `TRS-80 - The Accessible Computer

Radio Shack's TRS-80 line, starting at $799, brought computing to neighborhoods through convenient Radio Shack retail locations nationwide.

AVAILABILITY
Radio Shack's ubiquity gave customers local support, financing options, and immediate assistance—advantages competitors couldn't match.

SOFTWARE ECOSYSTEM
Radio Shack actively supported software development, resulting in a strong library of business, educational, and entertainment titles.

TRAINING & SUPPORT
Radio Shack offered classes, manuals, and technical support that Apple and Commodore couldn't replicate through mail order.

THE STRATEGY
While not the most advanced computer, TRS-80 succeeded by prioritizing customer service and accessibility over pure technical specifications.`,
  },
  {
    id: 'computer_software',
    title: 'Home Computer Software',
    icon: '💾',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'Ask about computer software at your local electronics dealer.',
    type: 'computer',
    body: `HOME COMPUTER SOFTWARE — THE WILD WEST OF 1984

If the hardware is the body of a home computer, software is the soul. In 1984, the software market is exploding with games, educational programs, productivity tools, and utilities of wildly varying quality.

THE CATEGORIES

GAMES (most popular)
From adventure text games to arcade ports, games drive most home computer purchases. Titles like Zork, Ultima, and Karateka prove computers can be entertaining, not just productive.

EDUCATIONAL SOFTWARE
Oregon Trail (school standard), Reader Rabbit, and Math Blaster are showing parents that computers can genuinely teach their children.

PRODUCTIVITY
VisiCalc — the first spreadsheet — launched the concept of the "killer app," software so useful it justifies the hardware purchase alone. WordStar and dBASE III are business essentials.

WHAT FORMATS EXIST
Software ships on 5.25-inch floppy disks ($20–$50 per program) or cassette tapes ($10–$30 for simpler programs). Compatibility between systems is a nightmare — Commodore 64 software won't run on Apple II.

WHERE TO BUY
• Radio Shack (Tandy/TRS-80 software and some multi-platform titles)
• Computerland stores (higher-end software for Apple and IBM)
• Kay-Bee Toys and Toys "R" Us (game software)
• Specialty computer stores (broadest selection, expert staff)

THE ADVICE
Before buying, confirm the software matches your specific computer model. A Commodore 64 version may run differently than an Atari version, even of the same title.`,
  },
  {
    id: 'computer_545',
    title: 'Home Computing',
    icon: '📱',
    color: '#06b6d4',
    anim: 'pulse',
    matchText: 'Bring home educational software for your family computer.',
    type: 'computer',
    body: `THE HOME COMPUTER REVOLUTION

1984 marks a turning point in American domestic technology. Home computers are transitioning from novelty luxury to essential household appliances.

THE TREND
Families purchasing computers cite education as the primary motivation. Parents view computer literacy as essential for children's future success.

THE REALITY
Most families lack knowledge about computers. Manufacturers must invest heavily in education and support, making early adopters feel confident.

THE FUTURE
Within a decade, computers may become as common as televisions. The families investing now will be ahead of the curve.

THE CHALLENGE
Software quality remains inconsistent. While some educational programs are brilliant, many are mediocre, making selection critical.`,
  },
];

// ── WEIRD TECHNOLOGY (#551-560) ──
export const WEIRD_TECHNOLOGY = [
  {
    id: 'tech_microwave',
    title: 'Microwave Ovens',
    icon: '📡',
    color: '#f97316',
    anim: 'pulse',
    matchText: 'You know, I still don\'t understand microwave ovens.',
    type: 'technology',
    body: `MICROWAVE OVENS — COOKING FROM THE FUTURE

The microwave oven has gone from a $3,000 laboratory curiosity in the 1950s to a $200 kitchen appliance that baffles and delights Americans in equal measure.

HOW IT WORKS (sort of)
Microwave ovens use electromagnetic radiation at 2.45 gigahertz to excite water molecules inside food, generating heat from the inside out rather than from an external flame. This has confused nearly every adult in America.

THE QUESTION
"But how does it know?" is the question most often asked about microwave ovens. The answer involves magnetrons, standing waves, and rotating turntables — none of which most people want to understand when they're reheating Tuesday's leftover meatloaf.

THE RESULTS
• Reheating coffee: Revolutionary
• Popping popcorn: Borderline miraculous  
• Defrosting chicken: Unreliable, producing one frozen corner and three cooked ones
• Cooking a full meal: Theoretically possible; practically questionable

THE METAL RULE
Never. Ever. Put metal in the microwave. This has been explained 40 million times. It will be explained 40 million more.

THE MANUAL
The Litton microwave manual is 48 pages. Approximately 0% of American households have read it. They have, however, read the part about not putting metal in there.

In 1984, 25% of American homes have a microwave oven. By 1990, that number will approach 90%. The confusion will scale accordingly.`,
  },
  {
    id: 'tech_nephew_computers',
    title: 'The Computer Future',
    icon: '💻',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'My nephew says computers are the future. We\'ll see.',
    type: 'technology',
    body: `THE NEPHEW THESIS — "COMPUTERS ARE THE FUTURE"

Somewhere in America right now, a nephew is explaining computers to his uncle over pot roast, and the uncle is nodding in the way people nod when they're not listening.

THE NEPHEW'S CASE
"They can do everything. Math. Letters. Games. Eventually you'll order groceries through it."

THE UNCLE'S RESPONSE
"The refrigerator tells me when I'm out of groceries. I don't need a computer."

THE NEPHEW'S COUNTER
"It's not like that. It's — look, just trust me."

WHAT THE NEPHEW IS RIGHT ABOUT
Everything, it turns out. Though in 1984, even the nephew has no idea how right.

THE REALITY IN 1984
Approximately 7% of American homes have a personal computer. Most are used for:
1. The word processing of documents that could be typed
2. Games (by a wide margin the primary use)
3. Spreadsheets by people who own small businesses
4. Sitting in a corner looking impressive

THE 20-YEAR FORECAST
The nephew's vision will exceed even his own predictions. The uncle will eventually own a device in his pocket more powerful than a 1984 Cray supercomputer and use it mostly to watch short videos about dogs.

"We'll see," said 1984. It would.`,
  },
  {
    id: 'tech_innovation',
    title: 'The Information Age',
    icon: '💡',
    color: '#3b82f6',
    anim: 'pulse',
    matchText: 'The information age is only beginning.',
    type: 'technology',
    body: `THE INFORMATION AGE — ALWAYS MOVING FORWARD

"Innovation continues." Four words that capture 1984's relentless technological march.

WHAT'S CHANGING RIGHT NOW
In 1984, technology isn't something that happens once and stops. The pace of change feels unprecedented to people living through it.

THE COMPUTERS
In 1980, personal computers were hobbyist curiosities. In 1984, they sit in millions of American homes and offices. In 1990? Nobody is quite sure, but the trend is unmistakable.

THE COMMUNICATIONS
AT&T's court-ordered breakup in 1984 unleashed competition in telephone service. Long-distance rates are falling. Cellular phones exist (barely). Fax machines are spreading.

THE ENTERTAINMENT
Cable television, VCRs, and video games have fundamentally changed how Americans spend leisure time in just five years.

THE FEELING
Americans in 1984 sense they're living through something historic. The computerization of work, the miniaturization of electronics, the digitization of music — each development hints at a world just around the corner.

THE UNCERTAINTY
Nobody knows exactly what's coming, but the direction seems clear: smaller, faster, cheaper, more connected.

The future has always been arriving. In 1984, it seems to be running.`,
  },
  {
    id: 'tech_551',
    title: 'Compact Discs',
    icon: '💿',
    color: '#2563eb',
    anim: 'spin',
    matchText: 'Compact Discs may be the future of recorded music.',
    type: 'technology',
    body: `COMPACT DISC TECHNOLOGY - The Digital Future of Music

Philips and Sony have developed Compact Disc (CD) technology that stores music digitally on 4.7-inch discs, offering perfect sound quality and durability.

THE TECHNOLOGY
CDs use laser technology to read tiny pits on a reflective disc surface. No physical contact means no wear—CDs theoretically play perfectly thousands of times.

THE SOUND QUALITY
CD sound is digitally encoded at 44.1 kHz sampling rate, 16-bit depth, producing audio that exceeds vinyl records in clarity and consistency.

THE ADVANTAGES
- No surface noise
- No skipping or scratching
- Perfect portability
- Longer lifespan than cassettes
- Better fidelity than vinyl

THE ADOPTION CHALLENGE
CD players cost $800-$1,000, and CDs retail for $12-$16—expensive compared to cassettes at $6-$8. Widespread adoption depends on prices falling significantly.

THE PREDICTION
Industry observers believe CDs will eventually replace vinyl and cassettes, but the transition will take years as prices gradually decrease.`,
  },
  {
    id: 'tech_552',
    title: 'Cellular Telephones',
    icon: '📱',
    color: '#3b82f6',
    anim: 'pulse',
    matchText: 'Cellular telephones are now available in select markets.',
    type: 'technology',
    body: `CELLULAR PHONES - Mobile Communication Arrives

Limited cellular phone service is rolling out in select US cities, promising the future of mobile communication for wealthy early adopters.

THE TECHNOLOGY
Cellular networks use radio waves to connect phones to base stations distributed throughout a geographic area, allowing seamless handoff between stations.

CURRENT REALITY
Motorola and other manufacturers have developed portable cellular phones weighing 2-3 pounds, small enough for car mounting or briefcase carrying.

THE SERVICE
AT&T and other carriers are building networks in major cities. Service costs are substantial—$4,000-$5,000 for equipment, plus $50+ monthly for limited minutes.

THE FUTURE
Cellular phones will likely become more common and affordable, eventually replacing car phones and pay phones. The technology is still experimental but promising.

THE LIMITATION
Current phones require car mounting or special carrying cases. True pocket-sized mobile phones remain years away.`,
  },
  {
    id: 'tech_553',
    title: 'Fax Machines',
    icon: '📠',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'More businesses are using fax machines every day.',
    type: 'technology',
    body: `FAX MACHINES - Instant Document Transmission

Fax technology is revolutionizing business communication. Documents can be transmitted over phone lines in seconds, replacing overnight mail and couriers for urgent communication.

THE TECHNOLOGY
Fax machines scan documents and convert them to digital signals transmitted over phone lines, reconstructed as printed images on the receiving end.

THE BUSINESS IMPACT
Companies report increased efficiency from instant document transmission. Contracts, signatures, and information that previously required physical transport now arrive instantly.

THE SPEED
A single-page fax transmits in 30-60 seconds, while receiving requires just moments. Information that took days to deliver by mail now arrives in minutes.

THE ADOPTION
Fax machines remain expensive ($1,500-$3,000), limiting adoption to businesses where efficiency gains justify the investment.

THE FUTURE
As prices fall, faxes may become standard office equipment. Some predict every office will eventually have fax capability.`,
  },
  {
    id: 'tech_554',
    title: 'Word Processors',
    icon: '⌨️',
    color: '#06b6d4',
    anim: 'pulse',
    matchText: 'Word processors are replacing traditional typewriters.',
    type: 'technology',
    body: `WORD PROCESSORS - The Death of Typewriters

Dedicated word processors and computer word processing software are rapidly replacing mechanical typewriters in offices nationwide.

THE ADVANTAGE
Text editing on a word processor is dramatically faster than typewriters. Changes, corrections, and reformatting happen instantly without retyping pages.

THE TRANSITION
Writers, journalists, and office workers report that word processing increases productivity significantly. Pages that took hours to perfect now take minutes.

THE SOFTWARE
Programs like WordStar dominate the market, offering features like find-and-replace, formatting, and file management unimaginable on typewriters.

THE RESISTANCE
Some writers resist word processors, claiming typewriter mechanical feedback aids creativity. However, the efficiency advantages are undeniable.

THE FUTURE
Mechanical typewriters will likely become obsolete within a decade as word processing becomes standard in offices.`,
  },
];

// ── ODD PRODUCTS (#561-575) ──
export const ODD_PRODUCTS = [
  {
    id: 'product_561',
    title: 'Pet Rocks',
    icon: '🪨',
    color: '#8b7355',
    anim: 'pulse',
    matchText: 'Pet Rocks are still available.',
    type: 'product',
    body: `PET ROCKS - The Novelty That Won't Die

Despite being a 1970s fad, Pet Rocks continue to sell in 1984. Each rock comes with a training manual teaching owners how to care for their pet stone.

THE CONCEPT
A smooth stone selected from a beach, packaged in a box with straw bedding and accompanied by a humorous training guide featuring tips like "Housebreaking" and "Tricks."

THE HUMOR
The entire product is a joke—rocks require no care, no feeding, no attention. The training manual is filled with absurdist humor that appeals to adults and children alike.

THE PHENOMENON
Pet Rocks represent marketing genius—turning a worthless product into a cultural sensation through novelty and clever packaging.

THE REALITY
1984 buyers are mostly people reliving the fad or discovering it for the first time. The peak has passed, but the concept endures as a novelty gift.`,
  },
  {
    id: 'product_562',
    title: 'Rubik\'s Cube',
    icon: '🧩',
    color: '#ef4444',
    anim: 'spin',
    matchText: 'Rubik\'s Cube continues to challenge puzzle enthusiasts.',
    type: 'product',
    body: `RUBIK'S CUBE - The Unsolved Mystery

Invented in 1974, Rubik's Cube remains a bestselling puzzle toy in 1984, with millions sold worldwide. The challenge: arrange all colored squares so each face is uniform.

THE CHALLENGE
Seemingly simple, solving the cube requires logic, spatial reasoning, and pattern recognition. Most people can solve one face but struggle beyond.

THE SOLUTION
Expert solvers have developed methods to solve the cube in under a minute. Championship competitions showcase these skilled puzzlers competing for speed records.

THE PHENOMENON
Rubik's Cube represents the appeal of logical puzzles to a broad audience. It's equally enjoyed by children and adults, making it one of the most successful toys ever.

THE MARKET
Nearly a decade after introduction, Rubik's Cube remains popular and continues selling at $10-15 retail price.`,
  },
  {
    id: 'product_563',
    title: 'Lite-Brite',
    icon: '✨',
    color: '#fbbf24',
    anim: 'pulse',
    matchText: 'Create light pictures with Lite-Brite.',
    type: 'product',
    body: `LITE-BRITE - Illuminated Creativity

Lite-Brite, a classic toy still popular in 1984, allows children to create glowing images by inserting colored pegs into a backlit board.

THE CONCEPT
A flat board with thousands of small holes is backlit by a light bulb. Pegs in various colors fit into holes, creating images that glow when the light is on.

THE APPEAL
The glowing result satisfies children's desire to create something beautiful and functional. The pegs are large enough for small hands to manipulate easily.

THE IMAGES
Lite-Brite includes design templates that children can follow or create original designs using the colored pegs.

THE LONGEVITY
Despite being introduced in the 1960s, Lite-Brite remains popular because it offers open-ended creative play without electronic components or batteries.`,
  },
  {
    id: 'product_564',
    title: 'Slinky',
    icon: '⬇️',
    color: '#3b82f6',
    anim: 'wave',
    matchText: 'The classic toy Slinky never goes out of style.',
    type: 'product',
    body: `SLINKY - The Perpetual Motion Toy

Invented in 1945, Slinky remains a bestselling toy in 1984. This simple spring creates enduring appeal through elegant physics and mesmerizing motion.

THE DESIGN
A pre-compressed helical spring made of steel, Slinky "walks" down stairs, creating the appearance of continuous motion without external power.

THE MAGIC
Children are endlessly fascinated by Slinky's fluid motion. Watching it descend stairs or move across a table never gets old.

THE SCIENCE
Slinky demonstrates gravity, momentum, and wave mechanics in a simple, visual way that engages children's curiosity about how things work.

THE MARKETING
Slinky's longevity proves that simple toys often outperform complex ones. Good design and satisfying physics create lasting appeal.`,
  },
];

// ── MUSIC ALBUMS & CASSETTES (#576-590) ──
export const MUSIC = [
  {
    id: 'music_576',
    title: 'Prince - Purple Rain',
    icon: '💿',
    color: '#8b5cf6',
    anim: 'spin',
    matchText: 'Enjoy the latest music from Prince.',
    type: 'music',
    body: `PRINCE - PURPLE RAIN
Released: July 27, 1984
Format: Cassette ($7.99) | Vinyl ($8.99) | Upcoming: CD (1985)

TRACK LISTING
1. Let's Pretend We're Married (4:43)
2. Raspberry Beret (3:58)
3. Delirious (3:29)
4. When Doves Cry (5:23)
5. I Would Die 4 U (2:45)
6. Maybe This Time (3:32)
7. The Most Beautiful Girl in the World (2:50)
8. Purple Rain (8:42)
9. Computer Blue (3:50)
10. Darling Nikki (4:10)
11. Mother Father (5:20)
12. God Is Watching Us (2:19)

THE PHENOMENON
Purple Rain is the biggest album release of 1984. Prince's virtuosity—playing all instruments, writing all songs, producing everything—creates sonic depth unmatched by contemporary releases.

THE SINGLES
"When Doves Cry" became a #1 hit, featuring Prince's signature falsetto and minimalist production (drums and voice only on the hook).

THE ARTISTRY
Purple Rain showcases Prince's ambition to create a complete artistic vision. The album balances funk, rock, pop, and R&B, proving Prince transcends traditional genre boundaries.

THE FILM
Prince is also starring in a film of the same name, making Purple Rain a multimedia phenomenon.`,
  },
  {
    id: 'music_577',
    title: 'Michael Jackson - Thriller',
    icon: '🎵',
    color: '#000000',
    anim: 'pulse',
    matchText: 'Michael Jackson\'s Thriller continues to dominate the charts.',
    type: 'music',
    body: `MICHAEL JACKSON - THRILLER
Released: November 30, 1982
Format: Cassette ($7.99) | Vinyl ($8.99) | CD ($14.99)

TRACK LISTING
1. Billie Jean (4:54)
2. Beat It (4:18)
3. Billie Jean (Alternative Mix) (4:46)
4. Human Nature (4:07)
5. The Girl Is Mine (3:42)
6. Thriller (5:57)
7. Beat It (Alternate) (4:18)
8. Wanna Be Startin' Somethin' (6:03)
9. Lady in My Life (5:16)
10. The Girl Is Mine (Alternative Mix) (3:39)
11. Thriller (Alternate) (4:32)

THE DOMINATION
Nearly two years after release, Thriller remains the best-selling album in America. Sales exceed 15 million copies worldwide, making it the best-selling album of all time.

THE SINGLES
"Billie Jean," "Beat It," and "Thriller" were massive hit singles. The "Thriller" music video, featuring groundbreaking choreography and special effects, revolutionized the medium.

THE ARTISTRY
Producer Quincy Jones and Michael Jackson created an album that appeals to pop, R&B, rock, and mainstream audiences simultaneously.

THE CULTURAL IMPACT
Thriller transcended music, becoming a cultural phenomenon that influenced dance, fashion, and video production globally.`,
  },
  {
    id: 'music_578',
    title: 'Cyndi Lauper - Girls Just Want to Have Fun',
    icon: '🎤',
    color: '#ec4899',
    anim: 'pulse',
    matchText: 'Cyndi Lauper\'s debut is a colorful explosion of pop fun.',
    type: 'music',
    body: `CYNDI LAUPER - GIRLS JUST WANT TO HAVE FUN
Released: February 14, 1984
Format: Cassette ($7.99) | Vinyl ($8.99) | CD ($14.99)

TRACK LISTING
1. Girls Just Want to Have Fun (3:24)
2. Time After Time (3:25)
3. She's So Unusual (3:00)
4. All Through the Night (3:42)
5. I'll Kiss You (3:48)
6. He's So Unusual (3:22)
7. Money Changes Everything (3:13)
8. Witness (3:49)
9. I Know My Love (3:08)

THE BREAKTHROUGH
Cyndi Lauper's debut album introduces a brash, colorful personality to pop music. Her unique voice and fashion sense make her instantly recognizable.

THE HIT
"Girls Just Want to Have Fun" became the anthem for 1984, celebrating female empowerment and joy through infectious pop production.

THE FOLLOW-UP
"Time After Time" showcases Lauper's vocal range and emotional depth, proving the album contains substance alongside pop hooks.

THE IMPACT
Lauper challenged 1980s pop conformity with bold fashion, unique personality, and unapologetic femininity that influenced culture beyond music.`,
  },
  {
    id: 'music_579',
    title: 'Van Halen - 1984',
    icon: '🎸',
    color: '#ef4444',
    anim: 'pulse',
    matchText: 'Van Halen\'s self-titled 1984 is heavy rock perfection.',
    type: 'music',
    body: `VAN HALEN - 1984
Released: January 9, 1984
Format: Cassette ($7.99) | Vinyl ($8.99) | CD ($14.99)

TRACK LISTING
1. Panama (3:33)
2. Jump (4:00)
3. Top Jimmy (3:39)
4. Drop Dead Legs (3:21)
5. House of Pain (3:19)
6. I'll Wait (5:33)
7. Girl Gone Bad (3:34)
8. Diver Down (5:22)
9. secrets (4:14)
10. Unchained (3:41)

THE SOUND
Van Halen dominates arena rock with Edward Van Halen's revolutionary guitar techniques and David Lee Roth's charismatic vocals.

THE HITS
"Panama" and "Jump" became massive rock radio staples, with "Jump" featuring a synthesizer that showcased Van Halen's willingness to experiment with new sounds.

THE VIRTUOSITY
Edward Van Halen's guitar playing reaches new heights, featuring unprecedented speed, tapping, and harmonic techniques that revolutionize rock guitar.

THE PHENOMENON
1984 proves Van Halen's continued dominance in arena rock, combining technical mastery with infectious hooks and irrepressible energy.`,
  },
  {
    id: 'music_580',
    title: 'Culture Club - Colour by Numbers',
    icon: '🎶',
    color: '#ec4899',
    anim: 'pulse',
    matchText: 'Culture Club\'s Colour by Numbers is colorful new wave.',
    type: 'music',
    body: `CULTURE CLUB - COLOUR BY NUMBERS
Released: October 1, 1983
Format: Cassette ($7.99) | Vinyl ($8.99) | CD ($14.99)

TRACK LISTING
1. Karma Chameleon (3:14)
2. Church of the Poison Mind (3:27)
3. Ms. Vain (3:34)
4. Stormkeeper (4:29)
5. Victims (3:40)
6. White Boys Can't Dance (2:36)
7. The Medal Song (4:17)
8. Romance Beyond the Alphabet (4:25)
9. Colour by Numbers (3:45)
10. It Takes Time (3:25)

THE SUCCESS
Culture Club's colorful new wave aesthetic and Boy George's androgynous fashion captured 1984's imagination.

THE HIT
"Karma Chameleon" became a massive worldwide hit, showcasing Culture Club's ability to blend pop appeal with sophisticated production.

THE PERSONALITY
Boy George's distinctive voice and fashion choices made Culture Club stand out in a crowded pop landscape.

THE INFLUENCE
Culture Club helped normalize gender-bending fashion and alternative aesthetics in mainstream pop culture.`,
  },
];

// ── RANDOM 1984 LIFE & CULTURE (#591-605) ──
export const RANDOM_1984_LIFE = [
  {
    id: 'life_591',
    title: 'Video Rental Stores',
    icon: '📼',
    color: '#06b6d4',
    anim: 'pulse',
    matchText: 'Rent the latest movies at your local video store.',
    type: 'culture',
    body: `THE VIDEO RENTAL REVOLUTION

The VCR boom of 1983-84 created an explosion of video rental stores in neighborhoods nationwide. Blockbuster, Video City, and independent shops have emerged as community gathering places.

THE EXPERIENCE
Friday night video rental is now a family ritual. Parents and children browse shelves of VHS tapes, each weighing their options before selecting a movie to watch over the weekend.

THE ECONOMICS
Video rental stores charge $3-5 per rental, encouraging multiple viewings per family to justify the fee. Late fees provide additional revenue.

THE SELECTION
Stores stock hit movies, obscure films, and adult content in restricted sections. The selection varies by location and store policies.

THE COMMUNITY
Video stores become neighborhood social hubs where employees recommend films, customers discover new movies, and the store becomes a third place outside home and work.

THE FUTURE
As more families acquire VCRs, video rental stores will likely expand rapidly. Analysts predict they'll become as common as pizza places within a few years.`,
  },
  {
    id: 'life_592',
    title: 'The Boom Box Era',
    icon: '📻',
    color: '#fbbf24',
    anim: 'pulse',
    matchText: 'Bring your music anywhere with a portable boom box.',
    type: 'culture',
    body: `BOOM BOXES - PORTABLE AUDIO DOMINATES

The Sony Walkman revolutionized personal audio in 1979, but 1984 belongs to the boom box—a large, portable stereo system with dual cassette decks and AM/FM radio.

THE DEVICE
Boom boxes are shoulder-mounted or carried in both hands, weighing 10-15 pounds. They play cassettes, FM radio, and some feature record players.

THE CULTURE
Young people carry boom boxes to parks, beaches, and street corners, using them to share music with friends and create impromptu dance parties.

THE TREND
Boom boxes become status symbols. Models with bigger speakers, more features, and better sound quality are coveted. Brands like Panasonic, JBL, and Crown dominate.

THE SOUND
Turning up the bass on a boom box while standing in a public place becomes a form of rebellion and self-expression.

THE FUTURE
Boom boxes will likely peak in the late 1980s before personal Walkmans and car stereos eventually reclaim dominance in portable audio.`,
  },
  {
    id: 'life_593',
    title: 'The Fitness Craze',
    icon: '💪',
    color: '#ef4444',
    anim: 'pulse',
    matchText: 'Join the fitness revolution and get in shape.',
    type: 'culture',
    body: `THE 1980S FITNESS EXPLOSION

Starting with Richard Simmons' aerobics craze and Jane Fonda's workout videos, America is experiencing unprecedented interest in physical fitness.

THE PHENOMENON
Aerobics studios are opening in every mall and city center. Women flock to classes featuring rhythmic exercise set to pop music and led by enthusiastic instructors.

THE VIDEOS
Jane Fonda's workout VHS cassette is one of the best-selling videos, allowing people to exercise at home with a celebrity instructor leading them.

THE FASHION
Neon leg warmers, spandex leotards, and matching headbands become fashionable workout attire. Brands like Nike and Reebok capitalize on the fitness boom.

THE MOTIVATION
Americans embrace fitness for health, appearance, and stress relief. Gyms report record memberships and waiting lists for popular classes.

THE CULTURAL SHIFT
The 1980s fitness craze represents changing attitudes about health, body image, and self-care in American culture.`,
  },
  {
    id: 'life_594',
    title: 'MTV Music Videos',
    icon: '📺',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'MTV is changing how America experiences music.',
    type: 'culture',
    body: `MTV - MUSIC TELEVISION PHENOMENON

MTV launched in August 1981, but 1984 represents its breakthrough moment as music videos become central to how songs are promoted and consumed.

THE FORMAT
MTV plays music videos 24/7, initially filling hours with videos from any artist willing to provide them. The quality and budgets increase as labels recognize videos' marketing power.

THE BREAKTHROUGH VIDEOS
Michael Jackson's "Thriller," Prince's "When Doves Cry," and David Bowie's "Let's Dance" showcase the artistic possibilities of the music video format.

THE IMPACT
Artists invest heavily in creating visually stunning videos. Directors become celebrities. Music videos become as important as the songs themselves.

THE CULTURAL SHIFT
Watching MTV becomes a social activity. Young people gather to see new videos and participate in music culture beyond radio.

THE FUTURE
MTV will likely become an even more dominant force in music promotion and consumption, potentially challenging radio's primacy.`,
  },
];

// ── PUBLIC SERVICE ANNOUNCEMENTS (#606-625) ──
export const PSAs = [
  {
    id: 'psa_606',
    title: 'Smokey the Bear - Only YOU',
    icon: '🔥',
    color: '#8b5cf6',
    anim: 'pulse',
    matchText: 'Only YOU can prevent forest fires.',
    type: 'psa',
    body: `SMOKEY THE BEAR - FOREST FIRE PREVENTION

Since 1944, Smokey the Bear has been America's most recognizable forest fire prevention mascot, teaching generations about responsible outdoor behavior.

THE MESSAGE
"Only YOU can prevent forest fires" is one of the most famous advertising slogans in American history, emphasizing individual responsibility.

THE CAMPAIGN
Smokey appears in billboards, television spots, radio advertisements, and print media throughout 1984, always with the same crucial message.

THE IMPACT
The Smokey campaign is credited with significantly reducing accidental forest fires through public education and awareness.

THE CHARACTER
Smokey the Bear, dressed in ranger outfit and cowboy hat, appeals to both children and adults, making forest fire prevention accessible to all ages.

THE CONTINUATION
The campaign remains active in 1984 with renewed emphasis on responsible camping and outdoor activities during fire season.`,
  },
  {
    id: 'psa_607',
    title: 'Buckle Up for Safety',
    icon: '🚗',
    color: '#ef4444',
    anim: 'pulse',
    matchText: 'Buckle up for safety. It\'s the law and it saves lives.',
    type: 'psa',
    body: `SEAT BELT SAFETY CAMPAIGN

Throughout the 1980s, safety campaigns emphasize the importance of seat belts as automotive fatality rates rise.

THE MESSAGE
"Buckle Up for Safety" campaigns highlight the proven life-saving potential of seat belts through statistics and emotional testimonials.

THE LAW
Several states have passed mandatory seat belt laws, making buckle-up campaigns legally enforceable in addition to safety-focused.

THE RESISTANCE
Despite evidence, some Americans resist seat belt mandates, viewing them as personal freedom infringements.

THE CAMPAIGN
Public service announcements feature dramatic crash simulations, injury statistics, and survivor stories.

THE ADVOCACY
Safety organizations push for stronger enforcement and increased public awareness of seat belt effectiveness.`,
  },
  {
    id: 'psa_608',
    title: 'This Is Your Brain on Drugs',
    icon: '🧠',
    color: '#fbbf24',
    anim: 'pulse',
    matchText: 'This is your brain. This is your brain on drugs. Any questions?',
    type: 'psa',
    body: `THIS IS YOUR BRAIN ON DRUGS

One of the most famous and memorably simple public service announcements, "This Is Your Brain on Drugs" uses a raw egg to demonstrate drug damage.

THE CONCEPT
A spokesperson holds an egg, declaring "This is your brain." Then they crack it into a hot skillet: "This is your brain on drugs."

THE IMPACT
The advertisement's simplicity and directness resonate with viewers of all ages, making it one of the most recognizable PSAs of the 1980s.

THE CAMPAIGN
The anti-drug PSA airs during primetime television, reaching millions of Americans with an anti-drug message during peak drug crisis years.

THE EFFECTIVENESS
Public health officials believe the PSA reaches young people and encourages drug avoidance through its memorable and stark visual.

THE LEGACY
The "This Is Your Brain on Drugs" PSA becomes iconic, quoted and parodied for decades after its initial broadcast.`,
  },
  {
    id: 'psa_609',
    title: 'Designated Driver Campaign',
    icon: '🚙',
    color: '#3b82f6',
    anim: 'pulse',
    matchText: 'Friends don\'t let friends drive drunk.',
    type: 'psa',
    body: `FRIENDS DON'T LET FRIENDS DRIVE DRUNK

A relatively new campaign gaining momentum in 1984, the "Designated Driver" message encourages friends to prevent drunk driving through personal intervention.

THE MESSAGE
"Friends don't let friends drive drunk" emphasizes personal responsibility for friends' safety during social situations.

THE CONCEPT
The campaign suggests that designating a non-drinking driver before drinking begins is an effective harm-reduction strategy.

THE TIMING
As drunk driving deaths reach epidemic levels in the 1980s, awareness campaigns attempt to shift social norms around drinking and driving.

THE IMPACT
The campaign resonates especially with young adults and college-age populations where drunk driving risk is highest.

THE CHALLENGE
Changing social behaviors around alcohol consumption requires sustained campaigns and cultural shifts beyond advertising alone.`,
  },
];

// Export all categories
export const ALL_ENTRIES = [
  ...ARCADE_GAMES,
  ...HOME_COMPUTERS,
  ...WEIRD_TECHNOLOGY,
  ...ODD_PRODUCTS,
  ...MUSIC,
  ...RANDOM_1984_LIFE,
  ...PSAs,
];