// National Banner Achievements — 370 total (354 window + 16 hidden category)
// Generated from the Master Achievement List spec
// Each hidden achievement auto-unlocks when all window achievements in its category are collected

// Category slugs map to banner data file prefixes
export const NATIONAL_CATEGORIES = {
  tv: { name: 'TV Shows', hiddenName: "Prime Time '84" },
  movies: { name: 'Movies', hiddenName: null },
  electronics: { name: 'Electronics & Computers', hiddenName: null },
  generalProducts: { name: 'General Products / Americana', hiddenName: null },
  arcade: { name: 'Arcade & Video Games', hiddenName: null },
  wrestling: { name: 'Pro Wrestling', hiddenName: "And That's the Bottom Line in '84" },
  olympics: { name: '1984 LA Olympics', hiddenName: 'Spirit of \'84' },
  space: { name: 'Space / NASA / Aviation', hiddenName: 'The Final Frontier' },
  newspapers: { name: 'Newspapers & Classifieds', hiddenName: 'Read All About It' },
  phoneWars: { name: 'Long Distance Phone Wars', hiddenName: 'Long Distance Champion' },
  film: { name: 'Film Development & Cameras', hiddenName: "That's a Keeper" },
  scream1984: { name: 'Things That Scream 1984', hiddenName: 'Totally Eighties' },
  mall: { name: '1984 Mall Culture', hiddenName: 'Closing Time at the Mall' },
  formatWars: { name: 'Home Video Format Wars', hiddenName: 'Tracking Adjusted' },
  countyFair: { name: 'County Fairs & Americana', hiddenName: 'See You Next Summer' },
  music: { name: 'Music & MTV', hiddenName: 'I Want My MTV' },
  cars: { name: 'Cars & the Road', hiddenName: 'Full Tank, Open Road' },
  cartoons: { name: 'Saturday Morning Cartoons', hiddenName: "Kids, Don't Try This at Home" },
  cereal: { name: 'Cereal & Their Mascots', hiddenName: 'Cleaned the Bowl' },
  promoNights: { name: 'Ballpark Promo Nights & Giveaways', hiddenName: 'Promo Night Regular' },
};

// Window achievements (one per popup) — 354 total
// Format: { id, name, emoji, cat }
export const NATIONAL_WINDOW_ACHIEVEMENTS = [
  // ── TV Shows (25) ──
  { id: 'nat_tv_1', name: 'Vice Marathon', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_2', name: 'Southfork Schermer', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_3', name: 'Carrington Catfight', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_4', name: 'I Love It When a Plan Comes Together', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_5', name: 'Checked In at the St. Gregory', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_6', name: 'Simon Brothers Investigations', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_7', name: "Robin's Nest Regular", emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_8', name: 'Keaton Family Dinner', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_9', name: 'Cabot Cove Sleuth', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_10', name: 'Last Call at Cheers', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_11', name: 'King Harbor Crew', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_12', name: "Matt's Master Plan", emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_13', name: 'Squad Room Regular', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_14', name: 'Unknown Stuntman', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_15', name: 'Eastland Honor Roll', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_16', name: 'Order in the Court', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_17', name: "Mel's Diner Regular", emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_18', name: 'Knight of the Road', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_19', name: 'Big Heart, Small Package', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_20', name: 'Steele Investigations', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_21', name: 'Stairway Traveler', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_22', name: 'Roll Call Regular', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_23', name: 'Brownstone Buddies', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_24', name: 'Order in the Night Court', emoji: '📺', cat: 'tv' },
  { id: 'nat_tv_25', name: 'San Francisco Memorial Rounds', emoji: '📺', cat: 'tv' },

  // ── Movies (25) ──
  { id: 'nat_movies_1', name: 'Who You Gonna Call', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_2', name: 'Axel Foley', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_3', name: 'Fortune and Glory', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_4', name: 'The Three Rules', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_5', name: 'Wax On, Wax Off', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_6', name: 'Roll Call', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_7', name: 'Cut Loose', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_8', name: 'Chase the Stone', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_9', name: 'The Needs of the Many', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_10', name: 'Catch of the Day', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_11', name: 'Stage Lights', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_12', name: 'Paddle Up', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_13', name: 'Pop and Lock', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_14', name: 'Greetings, Starfighter', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_15', name: 'Broadway Bound', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_16', name: 'Nerd Power', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_17', name: 'The Real Game', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_18', name: 'Class in Session', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_19', name: 'Through the Lens', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_20', name: "I'll Be Back", emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_21', name: "Don't Fall Asleep", emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_22', name: 'These Go to Eleven', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_23', name: 'The Spice Must Flow', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_24', name: 'Call My Name', emoji: '🎥', cat: 'movies' },
  { id: 'nat_movies_25', name: 'Knock the Cover Off', emoji: '🎥', cat: 'movies' },

  // ── Electronics & Computers (15) ──
  { id: 'nat_electronics_1', name: '64K of Power', emoji: '💾', cat: 'electronics' },
  { id: 'nat_electronics_2', name: 'Head of the Class', emoji: '👩‍🏫', cat: 'electronics' },
  { id: 'nat_electronics_3', name: 'Point and Click', emoji: '🖱️', cat: 'electronics' },
  { id: 'nat_electronics_4', name: 'Trust the Shack', emoji: '🕹️', cat: 'electronics' },
  { id: 'nat_electronics_5', name: 'Have You Played Atari Today?', emoji: '👾', cat: 'electronics' },
  { id: 'nat_electronics_6', name: 'Be Kind, Rewind', emoji: '⏪', cat: 'electronics' },
  { id: 'nat_electronics_7', name: 'Press Play', emoji: '🎧', cat: 'electronics' },
  { id: 'nat_electronics_8', name: 'Pump Up the Volume', emoji: '🔊', cat: 'electronics' },
  { id: 'nat_electronics_9', name: 'High Score', emoji: '🌟', cat: 'electronics' },
  { id: 'nat_electronics_10', name: 'Perfect Sound', emoji: '🎶', cat: 'electronics' },
  { id: 'nat_electronics_11', name: 'Means Business', emoji: '💼', cat: 'electronics' },
  { id: 'nat_electronics_12', name: 'Lights, Camera, Action', emoji: '📷', cat: 'electronics' },
  { id: 'nat_electronics_13', name: 'Future on Your Wrist', emoji: '⌚', cat: 'electronics' },
  { id: 'nat_electronics_14', name: 'Welcome to the Future', emoji: '🚀', cat: 'electronics' },
  { id: 'nat_electronics_15', name: 'Dialing In', emoji: '☎️', cat: 'electronics' },

  // ── General Products / Americana (15) ──
  { id: 'nat_generalProducts_1', name: 'Blue Light Special', emoji: '🔵', cat: 'generalProducts' },
  { id: 'nat_generalProducts_2', name: 'The Wish Book', emoji: '📖', cat: 'generalProducts' },
  { id: 'nat_generalProducts_3', name: 'Meet Me at the Counter', emoji: '🍽️', cat: 'generalProducts' },
  { id: 'nat_generalProducts_4', name: 'Two All-Beef Patties', emoji: '🍔', cat: 'generalProducts' },
  { id: 'nat_generalProducts_5', name: 'Pick a Side', emoji: '⬅️', cat: 'generalProducts' },
  { id: 'nat_generalProducts_6', name: 'Meet at the Food Court', emoji: '🍟', cat: 'generalProducts' },
  { id: 'nat_generalProducts_7', name: 'Adoption Papers', emoji: '📔', cat: 'generalProducts' },
  { id: 'nat_generalProducts_8', name: 'Solve the Cube', emoji: '🧊', cat: 'generalProducts' },
  { id: 'nat_generalProducts_9', name: 'Get It Together', emoji: '🤝', cat: 'generalProducts' },
  { id: 'nat_generalProducts_10', name: 'Totally Rad', emoji: '🆒', cat: 'generalProducts' },
  { id: 'nat_generalProducts_11', name: 'Burp the Lid', emoji: '🤢', cat: 'generalProducts' },
  { id: 'nat_generalProducts_12', name: 'Shake It', emoji: '📸', cat: 'generalProducts' },
  { id: 'nat_generalProducts_13', name: 'Dinner in Minutes', emoji: '🥘', cat: 'generalProducts' },
  { id: 'nat_generalProducts_14', name: 'Friday Night Rental', emoji: '🎥', cat: 'generalProducts' },
  { id: 'nat_generalProducts_15', name: 'The Good Old Days', emoji: '🇺🇸', cat: 'generalProducts' },

  // ── Arcade & Video Games (15) ──
  { id: 'nat_arcade_1', name: 'Chomp Champion', emoji: '🪙', cat: 'arcade' },
  { id: 'nat_arcade_2', name: 'Dirk the Daring', emoji: '🐲', cat: 'arcade' },
  { id: 'nat_arcade_3', name: 'Keep Rolling', emoji: '🔵', cat: 'arcade' },
  { id: 'nat_arcade_4', name: 'Pump It Up', emoji: '🪓', cat: 'arcade' },
  { id: 'nat_arcade_5', name: 'How High Can You Get?', emoji: '🕹️', cat: 'arcade' },
  { id: 'nat_arcade_6', name: 'Quarters to Empires', emoji: '🦍', cat: 'arcade' },
  { id: 'nat_arcade_7', name: 'Wood Grain Warrior', emoji: '🪵', cat: 'arcade' },
  { id: 'nat_arcade_8', name: 'Survived the Crash', emoji: '🚀', cat: 'arcade' },
  { id: 'nat_arcade_9', name: 'Double Ship', emoji: '🚢', cat: 'arcade' },
  { id: 'nat_arcade_10', name: 'Reflexes of the Gods', emoji: '🧠', cat: 'arcade' },
  { id: 'nat_arcade_11', name: "Next Game's Mine", emoji: '👾', cat: 'arcade' },
  { id: 'nat_arcade_12', name: 'Enter Your Initials', emoji: '⌨️', cat: 'arcade' },
  { id: 'nat_arcade_13', name: 'Into the Grid', emoji: '⬛', cat: 'arcade' },
  { id: 'nat_arcade_14', name: 'Hop to It', emoji: '🐸', cat: 'arcade' },
  { id: 'nat_arcade_15', name: 'Under the Covers', emoji: '🛸', cat: 'arcade' },

  // ── Pro Wrestling (25) ──
  { id: 'nat_wrestling_1', name: 'The Nature Boy', emoji: '⭐', cat: 'wrestling' },
  { id: 'nat_wrestling_2', name: 'King of the Territories', emoji: '👑', cat: 'wrestling' },
  { id: 'nat_wrestling_3', name: 'The American Dream', emoji: '💙', cat: 'wrestling' },
  { id: 'nat_wrestling_4', name: 'The Enforcer', emoji: '🛡️', cat: 'wrestling' },
  { id: 'nat_wrestling_5', name: 'Slamming It', emoji: '🧳', cat: 'wrestling' },
  { id: 'nat_wrestling_6', name: 'Minnesota Wrecking Crew', emoji: '🧠', cat: 'wrestling' },
  { id: 'nat_wrestling_7', name: 'Four Fingers in the Air', emoji: '☝️', cat: 'wrestling' },
  { id: 'nat_wrestling_8', name: 'Texas Heroes', emoji: '⭐', cat: 'wrestling' },
  { id: 'nat_wrestling_9', name: 'Bad Street Brawlers', emoji: '👊', cat: 'wrestling' },
  { id: 'nat_wrestling_10', name: 'Legion of Doom', emoji: '💀', cat: 'wrestling' },
  { id: 'nat_wrestling_11', name: 'The Natural', emoji: '🌳', cat: 'wrestling' },
  { id: 'nat_wrestling_12', name: 'Whatcha Gonna Do', emoji: '🎙️', cat: 'wrestling' },
  { id: 'nat_wrestling_13', name: 'Hot Rod', emoji: '🎤', cat: 'wrestling' },
  { id: 'nat_wrestling_14', name: 'Eighth Wonder', emoji: '🏆', cat: 'wrestling' },
  { id: 'nat_wrestling_15', name: 'Camel Clutch', emoji: '🤼', cat: 'wrestling' },
  { id: 'nat_wrestling_16', name: 'Superfly Splash', emoji: '🤸', cat: 'wrestling' },
  { id: 'nat_wrestling_17', name: 'Grab Them Cakes', emoji: '🍰', cat: 'wrestling' },
  { id: 'nat_wrestling_18', name: 'The Dragon', emoji: '🐉', cat: 'wrestling' },
  { id: 'nat_wrestling_19', name: 'Cobra Clutch', emoji: '🐍', cat: 'wrestling' },
  { id: 'nat_wrestling_20', name: 'The Brain Trust', emoji: '🎩', cat: 'wrestling' },
  { id: 'nat_wrestling_21', name: 'MTV Mania', emoji: '🎸', cat: 'wrestling' },
  { id: 'nat_wrestling_22', name: 'Drawing the Map', emoji: '🗺️', cat: 'wrestling' },
  { id: 'nat_wrestling_23', name: "Saturday Night's Main Event", emoji: '📺', cat: 'wrestling' },
  { id: 'nat_wrestling_24', name: 'Action Figure Army', emoji: '🕴️', cat: 'wrestling' },
  { id: 'nat_wrestling_25', name: 'The Showcase of the Immortals', emoji: '🏟️', cat: 'wrestling' },

  // ── 1984 LA Olympics (17) ──
  { id: 'nat_olympics_1', name: 'Stick the Landing', emoji: '🤸', cat: 'olympics' },
  { id: 'nat_olympics_2', name: 'Chasing Jesse Owens', emoji: '🏃', cat: 'olympics' },
  { id: 'nat_olympics_3', name: 'The Streak', emoji: '🚧', cat: 'olympics' },
  { id: 'nat_olympics_4', name: 'Perfect Form', emoji: '🏅', cat: 'olympics' },
  { id: 'nat_olympics_5', name: '26.2 to History', emoji: '👣', cat: 'olympics' },
  { id: 'nat_olympics_6', name: 'Amateur Hour', emoji: '🕒', cat: 'olympics' },
  { id: 'nat_olympics_7', name: 'Let the Games Begin', emoji: '🎈', cat: 'olympics' },
  { id: 'nat_olympics_8', name: 'Carry the Flame', emoji: '🔥', cat: 'olympics' },
  { id: 'nat_olympics_9', name: 'Mascot Mania', emoji: '🐻', cat: 'olympics' },
  { id: 'nat_olympics_10', name: 'The Empty Lanes', emoji: '🌐', cat: 'olympics' },
  { id: 'nat_olympics_11', name: 'Top of the Podium', emoji: '🥈', cat: 'olympics' },
  { id: 'nat_olympics_12', name: 'In the Black', emoji: '⬛', cat: 'olympics' },
  { id: 'nat_olympics_13', name: 'Wave Your Flag', emoji: '🇺🇸', cat: 'olympics' },
  { id: 'nat_olympics_14', name: 'Prime-Time Gold', emoji: '🥇', cat: 'olympics' },
  { id: 'nat_olympics_15', name: 'Stuck It', emoji: '🤸', cat: 'olympics' },
  { id: 'nat_olympics_16', name: 'Golden Gloves', emoji: '🥊', cat: 'olympics' },
  { id: 'nat_olympics_17', name: 'Pin Collector', emoji: '📌', cat: 'olympics' },

  // ── Space / NASA / Aviation (18) ──
  { id: 'nat_space_1', name: 'The Human Satellite', emoji: '👩', cat: 'space' },
  { id: 'nat_space_2', name: 'Strap In', emoji: '💺', cat: 'space' },
  { id: 'nat_space_3', name: 'Maiden Voyage', emoji: '🚀', cat: 'space' },
  { id: 'nat_space_4', name: 'Out the Airlock', emoji: '🚪', cat: 'space' },
  { id: 'nat_space_5', name: 'Orbital Tow Truck', emoji: '🚚', cat: 'space' },
  { id: 'nat_space_6', name: 'Wheels Down', emoji: '🛞', cat: 'space' },
  { id: 'nat_space_7', name: 'Go for Launch', emoji: '🎧', cat: 'space' },
  { id: 'nat_space_8', name: 'Right Stuff', emoji: '🎒', cat: 'space' },
  { id: 'nat_space_9', name: 'We Have Liftoff', emoji: '☄️', cat: 'space' },
  { id: 'nat_space_10', name: 'Microgravity Lab', emoji: '🔬', cat: 'space' },
  { id: 'nat_space_11', name: 'Overview Effect', emoji: '🌍', cat: 'space' },
  { id: 'nat_space_12', name: 'Space Fever', emoji: '🌌', cat: 'space' },
  { id: 'nat_space_13', name: 'Deep Space Signal', emoji: '📡', cat: 'space' },
  { id: 'nat_space_14', name: 'Mach 2', emoji: '✈️', cat: 'space' },
  { id: 'nat_space_15', name: 'Afterburner', emoji: '🔥', cat: 'space' },
  { id: 'nat_space_16', name: 'Cleared for Takeoff', emoji: '🛠️', cat: 'space' },
  { id: 'nat_space_17', name: 'Pioneer Spirit', emoji: '🕊️', cat: 'space' },
  { id: 'nat_space_18', name: 'Reach for the Stars', emoji: '🌠', cat: 'space' },

  // ── Newspapers & Classifieds (14) ──
  { id: 'nat_newspapers_1', name: 'OBO', emoji: '📰', cat: 'newspapers' },
  { id: 'nat_newspapers_2', name: 'Now Hiring', emoji: '💼', cat: 'newspapers' },
  { id: 'nat_newspapers_3', name: 'Missed Connection', emoji: '💌', cat: 'newspapers' },
  { id: 'nat_newspapers_4', name: 'Read the Box Score', emoji: '📊', cat: 'newspapers' },
  { id: 'nat_newspapers_5', name: 'Read the Funnies', emoji: '😋', cat: 'newspapers' },
  { id: 'nat_newspapers_6', name: 'Paper Route', emoji: '🚲', cat: 'newspapers' },
  { id: 'nat_newspapers_7', name: 'Stop the Presses', emoji: '🛑', cat: 'newspapers' },
  { id: 'nat_newspapers_8', name: 'Clip & Save', emoji: '✂️', cat: 'newspapers' },
  { id: 'nat_newspapers_9', name: 'Hatch, Match & Dispatch', emoji: '🤝', cat: 'newspapers' },
  { id: 'nat_newspapers_10', name: 'Runs Great, Must Sell', emoji: '🚗', cat: 'newspapers' },
  { id: 'nat_newspapers_11', name: '2BR, 1BA', emoji: '🔑', cat: 'newspapers' },
  { id: 'nat_newspapers_12', name: 'Got Change?', emoji: '❓', cat: 'newspapers' },
  { id: 'nat_newspapers_13', name: 'Hot Off the Presses', emoji: '☕', cat: 'newspapers' },
  { id: 'nat_newspapers_14', name: 'Ink-Stained Fingers', emoji: '🖐️', cat: 'newspapers' },

  // ── Long Distance Phone Wars (10) ──
  { id: 'nat_phoneWars_1', name: 'The Big Breakup', emoji: '🏛️', cat: 'phoneWars' },
  { id: 'nat_phoneWars_2', name: 'Reach Out', emoji: '📞', cat: 'phoneWars' },
  { id: 'nat_phoneWars_3', name: 'Dial the Difference', emoji: '☎️', cat: 'phoneWars' },
  { id: 'nat_phoneWars_4', name: 'Pin-Drop Clear', emoji: '📌', cat: 'phoneWars' },
  { id: 'nat_phoneWars_5', name: 'Itemized', emoji: '🧾', cat: 'phoneWars' },
  { id: 'nat_phoneWars_6', name: 'After 9 PM', emoji: '🌙', cat: 'phoneWars' },
  { id: 'nat_phoneWars_7', name: 'Deposit More Coins', emoji: '🪙', cat: 'phoneWars' },
  { id: 'nat_phoneWars_8', name: 'Operators Standing By', emoji: '👥', cat: 'phoneWars' },
  { id: 'nat_phoneWars_9', name: 'Touch-Tone', emoji: '💋', cat: 'phoneWars' },
  { id: 'nat_phoneWars_10', name: 'Connect the Call', emoji: '🏆', cat: 'phoneWars' },

  // ── Film Development & Cameras (10) ──
  { id: 'nat_film_1', name: 'Load the Roll', emoji: '🎞️', cat: 'film' },
  { id: 'nat_film_2', name: 'Ready in an Hour', emoji: '✨', cat: 'film' },
  { id: 'nat_film_3', name: 'Watch It Develop', emoji: '⏱️', cat: 'film' },
  { id: 'nat_film_4', name: 'Spin the Disc', emoji: '📀', cat: 'film' },
  { id: 'nat_film_5', name: 'Drop-In Cartridge', emoji: '📥', cat: 'film' },
  { id: 'nat_film_6', name: 'Say Cheese', emoji: '🧀', cat: 'film' },
  { id: 'nat_film_7', name: 'Sticky Pages', emoji: '📋', cat: 'film' },
  { id: 'nat_film_8', name: 'Focus and Frame', emoji: '📸', cat: 'film' },
  { id: 'nat_film_9', name: 'Next Slide, Please', emoji: '🎥', cat: 'film' },
  { id: 'nat_film_10', name: 'Did They Come Out?', emoji: '🤷', cat: 'film' },

  // ── Things That Scream 1984 (18) ──
  { id: 'nat_scream1984_1', name: "What's Your Twenty?", emoji: '📟', cat: 'scream1984' },
  { id: 'nat_scream1984_2', name: 'Cash on Demand', emoji: '📺', cat: 'scream1984' },
  { id: 'nat_scream1984_3', name: 'Coming Through', emoji: '➡️', cat: 'scream1984' },
  { id: 'nat_scream1984_4', name: 'Catch a Wave', emoji: '🌊', cat: 'scream1984' },
  { id: 'nat_scream1984_5', name: 'Read My Mood', emoji: '📖', cat: 'scream1984' },
  { id: 'nat_scream1984_6', name: 'Press It On', emoji: '👔', cat: 'scream1984' },
  { id: 'nat_scream1984_7', name: 'Feel the Burn', emoji: '🔥', cat: 'scream1984' },
  { id: 'nat_scream1984_8', name: 'Step Inside', emoji: '🚶', cat: 'scream1984' },
  { id: 'nat_scream1984_9', name: 'Pile in the Way-Back', emoji: '🚚', cat: 'scream1984' },
  { id: 'nat_scream1984_10', name: 'Scratch & Sniff', emoji: '🌸', cat: 'scream1984' },
  { id: 'nat_scream1984_11', name: 'Adjust the Antenna', emoji: '📡', cat: 'scream1984' },
  { id: 'nat_scream1984_12', name: "Don't Stay Up Too Late", emoji: '🌙', cat: 'scream1984' },
  { id: 'nat_scream1984_13', name: 'Spin the Wheel', emoji: '🎡', cat: 'scream1984' },
  { id: 'nat_scream1984_14', name: 'Carriage Return', emoji: '📃', cat: 'scream1984' },
  { id: 'nat_scream1984_15', name: 'Change the Channel', emoji: '🎛️', cat: 'scream1984' },
  { id: 'nat_scream1984_16', name: "Fill 'Er Up", emoji: '🎞️', cat: 'scream1984' },
  { id: 'nat_scream1984_17', name: 'Must-See Listings', emoji: '📋', cat: 'scream1984' },
  { id: 'nat_scream1984_18', name: 'Totally Rad', emoji: '🔺', cat: 'scream1984' },

  // ── 1984 Mall Culture (20) ──
  { id: 'nat_mall_1', name: 'Grab a Tray', emoji: '🥨', cat: 'mall' },
  { id: 'nat_mall_2', name: 'Frothy and Cold', emoji: '🥤', cat: 'mall' },
  { id: 'nat_mall_3', name: 'Browse the Racks', emoji: '👕', cat: 'mall' },
  { id: 'nat_mall_4', name: 'The Weird Store', emoji: '👻', cat: 'mall' },
  { id: 'nat_mall_5', name: 'Flip Through the Bins', emoji: '🎰', cat: 'mall' },
  { id: 'nat_mall_6', name: 'Quarter on the Machine', emoji: '🪙', cat: 'mall' },
  { id: 'nat_mall_7', name: 'Free Sample', emoji: '🍦', cat: 'mall' },
  { id: 'nat_mall_8', name: 'Ride the Escalator', emoji: '🏗️', cat: 'mall' },
  { id: 'nat_mall_9', name: 'Stonewashed', emoji: '👖', cat: 'mall' },
  { id: 'nat_mall_10', name: "Lace 'Em Up", emoji: '👟', cat: 'mall' },
  { id: 'nat_mall_11', name: 'Twist and Salt', emoji: '🥨', cat: 'mall' },
  { id: 'nat_mall_12', name: 'Four Poses', emoji: '📸', cat: 'mall' },
  { id: 'nat_mall_13', name: 'Make a Wish', emoji: '🌟', cat: 'mall' },
  { id: 'nat_mall_14', name: 'Puppy in the Window', emoji: '🐶', cat: 'mall' },
  { id: 'nat_mall_15', name: 'By the Scoop', emoji: '🍨', cat: 'mall' },
  { id: 'nat_mall_16', name: 'Pick a Card', emoji: '💌', cat: 'mall' },
  { id: 'nat_mall_17', name: 'Gadgets & Gizmos', emoji: '🎮', cat: 'mall' },
  { id: 'nat_mall_18', name: 'Catch a Flick', emoji: '🎥', cat: 'mall' },
  { id: 'nat_mall_19', name: 'Picture with Santa', emoji: '🌲', cat: 'mall' },
  { id: 'nat_mall_20', name: 'Mall Rat', emoji: '🐀', cat: 'mall' },

  // ── Home Video Format Wars (12) ──
  { id: 'nat_formatWars_1', name: 'Pick a Side', emoji: '⚔️', cat: 'formatWars' },
  { id: 'nat_formatWars_2', name: 'Team VHS', emoji: '📼', cat: 'formatWars' },
  { id: 'nat_formatWars_3', name: 'Team Beta', emoji: '🅱️', cat: 'formatWars' },
  { id: 'nat_formatWars_4', name: 'Flip the Disc', emoji: '💿', cat: 'formatWars' },
  { id: 'nat_formatWars_5', name: 'Set the Timer', emoji: '⏱️', cat: 'formatWars' },
  { id: 'nat_formatWars_6', name: 'Blinking 12:00', emoji: '🕛', cat: 'formatWars' },
  { id: 'nat_formatWars_7', name: 'Tape Over It', emoji: '📼', cat: 'formatWars' },
  { id: 'nat_formatWars_8', name: 'Be Kind, Rewind', emoji: '🎥', cat: 'formatWars' },
  { id: 'nat_formatWars_9', name: 'Adjust the Tracking', emoji: '📈', cat: 'formatWars' },
  { id: 'nat_formatWars_10', name: 'Fast-Forward the Previews', emoji: '⏭️', cat: 'formatWars' },
  { id: 'nat_formatWars_11', name: 'Ka-Chunk', emoji: '💥', cat: 'formatWars' },
  { id: 'nat_formatWars_12', name: 'Movie Night', emoji: '🎬', cat: 'formatWars' },

  // ── County Fairs & Americana (14) ──
  { id: 'nat_countyFair_1', name: 'Top of the Wheel', emoji: '🎡', cat: 'countyFair' },
  { id: 'nat_countyFair_2', name: 'Win the Big Prize', emoji: '🎟️', cat: 'countyFair' },
  { id: 'nat_countyFair_3', name: 'Powdered Sugar', emoji: '🍩', cat: 'countyFair' },
  { id: 'nat_countyFair_4', name: 'Spun Sugar', emoji: '🍭', cat: 'countyFair' },
  { id: 'nat_countyFair_5', name: 'Blue Ribbon', emoji: '🎗️', cat: 'countyFair' },
  { id: 'nat_countyFair_6', name: 'Best in Show', emoji: '🥇', cat: 'countyFair' },
  { id: 'nat_countyFair_7', name: 'Prize Pumpkin', emoji: '🎃', cat: 'countyFair' },
  { id: 'nat_countyFair_8', name: 'Last Car Running', emoji: '🚗', cat: 'countyFair' },
  { id: 'nat_countyFair_9', name: 'Full Pull', emoji: '🕹️', cat: 'countyFair' },
  { id: 'nat_countyFair_10', name: 'Feed the Goats', emoji: '🐐', cat: 'countyFair' },
  { id: 'nat_countyFair_11', name: 'Here Comes the Band', emoji: '🎷', cat: 'countyFair' },
  { id: 'nat_countyFair_12', name: 'Crowned', emoji: '👑', cat: 'countyFair' },
  { id: 'nat_countyFair_13', name: 'Midway Lights', emoji: '🎢', cat: 'countyFair' },
  { id: 'nat_countyFair_14', name: 'Sleepy Drive Home', emoji: '😴', cat: 'countyFair' },

  // ── Music & MTV (23) ──
  { id: 'nat_music_1', name: 'Video Killed the Radio Star', emoji: '📺', cat: 'music' },
  { id: 'nat_music_2', name: 'One Glove', emoji: '🧤', cat: 'music' },
  { id: 'nat_music_3', name: 'Purple Reign', emoji: '💜', cat: 'music' },
  { id: 'nat_music_4', name: 'Like a Star', emoji: '⭐', cat: 'music' },
  { id: 'nat_music_5', name: 'The Boss', emoji: '🕶️', cat: 'music' },
  { id: 'nat_music_6', name: 'Jump', emoji: '🤸', cat: 'music' },
  { id: 'nat_music_7', name: 'True Colors', emoji: '🌈', cat: 'music' },
  { id: 'nat_music_8', name: 'Press Play', emoji: '🎧', cat: 'music' },
  { id: 'nat_music_9', name: 'Hit Record', emoji: '💿', cat: 'music' },
  { id: 'nat_music_10', name: 'Number One', emoji: '🥇', cat: 'music' },
  { id: 'nat_music_11', name: 'Pump Up the Volume', emoji: '🔊', cat: 'music' },
  { id: 'nat_music_12', name: 'On the Mic', emoji: '🎙️', cat: 'music' },
  { id: 'nat_music_13', name: 'Synthesize', emoji: '🎹', cat: 'music' },
  { id: 'nat_music_14', name: 'Simply the Best', emoji: '🎸', cat: 'music' },
  { id: 'nat_music_15', name: 'Second Invasion', emoji: '🛸', cat: 'music' },
  { id: 'nat_music_16', name: 'Lighters Up', emoji: '🔦', cat: 'music' },
  { id: 'nat_music_17', name: 'Side A, Side B', emoji: '📻', cat: 'music' },
  { id: 'nat_music_18', name: 'Tour Tee', emoji: '👕', cat: 'music' },
  { id: 'nat_music_19', name: 'World Premiere', emoji: '🎥', cat: 'music' },
  { id: 'nat_music_20', name: 'Sweep the Awards', emoji: '🧹', cat: 'music' },
  { id: 'nat_music_21', name: 'Hit the Floor', emoji: '💃', cat: 'music' },
  { id: 'nat_music_22', name: 'One and Done', emoji: '✨', cat: 'music' },
  { id: 'nat_music_23', name: 'Greatest Year', emoji: '🌍', cat: 'music' },

  // ── Cars & the Road (13) ──
  { id: 'nat_cars_1', name: 'Sliding Door', emoji: '🚗', cat: 'cars' },
  { id: 'nat_cars_2', name: 'Pop-Up Headlights', emoji: '🚘', cat: 'cars' },
  { id: 'nat_cars_3', name: 'Thrifty Miles', emoji: '⛽', cat: 'cars' },
  { id: 'nat_cars_4', name: 'V8 Rumble', emoji: '🏎️', cat: 'cars' },
  { id: 'nat_cars_5', name: 'Calling from the Car', emoji: '📱', cat: 'cars' },
  { id: 'nat_cars_6', name: 'Order at the Speaker', emoji: '🗣️', cat: 'cars' },
  { id: 'nat_cars_7', name: 'Are We There Yet?', emoji: '🛣️', cat: 'cars' },
  { id: 'nat_cars_8', name: 'Windows Down', emoji: '🪟', cat: 'cars' },
  { id: 'nat_cars_9', name: 'Top Off the Tank', emoji: '⛽', cat: 'cars' },
  { id: 'nat_cars_10', name: 'Load the Bed', emoji: '📦', cat: 'cars' },
  { id: 'nat_cars_11', name: 'Murals & Shag', emoji: '🌈', cat: 'cars' },
  { id: 'nat_cars_12', name: 'Roll Down the Window', emoji: '👐', cat: 'cars' },
  { id: 'nat_cars_13', name: 'Just Drive', emoji: '🏁', cat: 'cars' },

  // ── Saturday Morning Cartoons (25) ──
  { id: 'nat_cartoons_1', name: 'Bowl in Hand', emoji: '🥣', cat: 'cartoons' },
  { id: 'nat_cartoons_2', name: 'Transform!', emoji: '👑', cat: 'cartoons' },
  { id: 'nat_cartoons_3', name: 'Knowing Is Half the Battle', emoji: '🛡️', cat: 'cartoons' },
  { id: 'nat_cartoons_4', name: 'Raise the Sword', emoji: '⚔️', cat: 'cartoons' },
  { id: 'nat_cartoons_5', name: 'Caring Stare', emoji: '🌈', cat: 'cartoons' },
  { id: 'nat_cartoons_6', name: 'Pint-Sized', emoji: '✂️', cat: 'cartoons' },
  { id: 'nat_cartoons_7', name: "That's All Folks", emoji: '🎬', cat: 'cartoons' },
  { id: 'nat_cartoons_8', name: 'Unmask the Villain', emoji: '🎭', cat: 'cartoons' },
  { id: 'nat_cartoons_9', name: 'Three Apples High', emoji: '🔵', cat: 'cartoons' },
  { id: 'nat_cartoons_10', name: 'Game On', emoji: '🎮', cat: 'cartoons' },
  { id: 'nat_cartoons_11', name: 'Schoolhouse Smarts', emoji: '🏫', cat: 'cartoons' },
  { id: 'nat_cartoons_12', name: 'Heroes Assemble', emoji: '🦸', cat: 'cartoons' },
  { id: 'nat_cartoons_13', name: 'Wacky Antics', emoji: '🐒', cat: 'cartoons' },
  { id: 'nat_cartoons_14', name: 'Collect Them All', emoji: '📦', cat: 'cartoons' },
  { id: 'nat_cartoons_15', name: 'I Want That One', emoji: '🦖', cat: 'cartoons' },
  { id: 'nat_cartoons_16', name: 'Puppet Show', emoji: '🎭', cat: 'cartoons' },
  { id: 'nat_cartoons_17', name: 'Yabba Fun', emoji: '🤡', cat: 'cartoons' },
  { id: 'nat_cartoons_18', name: 'Blast Off', emoji: '🚀', cat: 'cartoons' },
  { id: 'nat_cartoons_19', name: 'Checkered Flag', emoji: '🏁', cat: 'cartoons' },
  { id: 'nat_cartoons_20', name: 'Boo!', emoji: '👻', cat: 'cartoons' },
  { id: 'nat_cartoons_21', name: 'Stay Tuned', emoji: '💼', cat: 'cartoons' },
  { id: 'nat_cartoons_22', name: 'Toon on the Box', emoji: '📦', cat: 'cartoons' },
  { id: 'nat_cartoons_23', name: 'Go Outside and Play', emoji: '☀️', cat: 'cartoons' },
  { id: 'nat_cartoons_24', name: 'Show It Off', emoji: '✨', cat: 'cartoons' },
  { id: 'nat_cartoons_25', name: 'Saturday Magic', emoji: '📺', cat: 'cartoons' },

  // ── Cereal & Their Mascots (15) ──
  { id: 'nat_cereal_1', name: 'Pick a Box', emoji: '🛒', cat: 'cereal' },
  { id: 'nat_cereal_2', name: 'Prize at the Bottom', emoji: '🎁', cat: 'cereal' },
  { id: 'nat_cereal_3', name: 'Grrreat', emoji: '😋', cat: 'cereal' },
  { id: 'nat_cereal_4', name: 'Monster Mash', emoji: '👹', cat: 'cereal' },
  { id: 'nat_cereal_5', name: 'Catch the Charms', emoji: '🥣', cat: 'cereal' },
  { id: 'nat_cereal_6', name: 'Follow Your Nose', emoji: '👃', cat: 'cereal' },
  { id: 'nat_cereal_7', name: 'Sugar Rush', emoji: '🍬', cat: 'cereal' },
  { id: 'nat_cereal_8', name: 'Balanced Breakfast', emoji: '🔍', cat: 'cereal' },
  { id: 'nat_cereal_9', name: 'Solve the Maze', emoji: '🧩', cat: 'cereal' },
  { id: 'nat_cereal_10', name: '6 to 8 Weeks', emoji: '📅', cat: 'cereal' },
  { id: 'nat_cereal_11', name: 'On the Box', emoji: '📦', cat: 'cereal' },
  { id: 'nat_cereal_12', name: 'Eat Your Bran', emoji: '🌾', cat: 'cereal' },
  { id: 'nat_cereal_13', name: 'Bowl on the Knees', emoji: '🥣', cat: 'cereal' },
  { id: 'nat_cereal_14', name: 'Drink the Milk', emoji: '🥛', cat: 'cereal' },
  { id: 'nat_cereal_15', name: 'Breakfast of Champions', emoji: '🥣', cat: 'cereal' },

  // ── Ballpark Promo Nights & Giveaways (25) ──
  { id: 'nat_promoNights_1', name: 'Free Bat', emoji: '🏏', cat: 'promoNights' },
  { id: 'nat_promoNights_2', name: 'Light Up the Sky', emoji: '🎆', cat: 'promoNights' },
  { id: 'nat_promoNights_3', name: 'Lid for Everyone', emoji: '🧢', cat: 'promoNights' },
  { id: 'nat_promoNights_4', name: 'Lucky Seat Number', emoji: '🎫', cat: 'promoNights' },
  { id: 'nat_promoNights_5', name: 'The Legends Return', emoji: '🔙', cat: 'promoNights' },
  { id: 'nat_promoNights_6', name: 'Buck a Dog', emoji: '🌭', cat: 'promoNights' },
  { id: 'nat_promoNights_7', name: 'Play Ball', emoji: '⚾', cat: 'promoNights' },
  { id: 'nat_promoNights_8', name: 'Up Close', emoji: '📷', cat: 'promoNights' },
  { id: 'nat_promoNights_9', name: 'Helmet On', emoji: '⛑️', cat: 'promoNights' },
  { id: 'nat_promoNights_10', name: 'Suit Up', emoji: '👔', cat: 'promoNights' },
  { id: 'nat_promoNights_11', name: 'Spin and Stagger', emoji: '🌀', cat: 'promoNights' },
  { id: 'nat_promoNights_12', name: 'Take Me Out', emoji: '💨', cat: 'promoNights' },
  { id: 'nat_promoNights_13', name: 'Free Baseball', emoji: '🆓', cat: 'promoNights' },
  { id: 'nat_promoNights_14', name: 'Bark in the Park', emoji: '🌳', cat: 'promoNights' },
  { id: 'nat_promoNights_15', name: 'Goldfish in the Stands', emoji: '🐠', cat: 'promoNights' },
  { id: 'nat_promoNights_16', name: 'May the Force', emoji: '🚀', cat: 'promoNights' },
  { id: 'nat_promoNights_17', name: 'Wave the Towel', emoji: '🧣', cat: 'promoNights' },
  { id: 'nat_promoNights_18', name: 'Tacky and Proud', emoji: '🎀', cat: 'promoNights' },
  { id: 'nat_promoNights_19', name: 'Dregs of Humanity Live', emoji: '🧬', cat: 'promoNights' },
  { id: 'nat_promoNights_20', name: 'Fresh Socks', emoji: '🧦', cat: 'promoNights' },
  { id: 'nat_promoNights_21', name: 'Cape Crusader', emoji: '🧥', cat: 'promoNights' },
  { id: 'nat_promoNights_22', name: 'Jammies On', emoji: '🌙', cat: 'promoNights' },
  { id: 'nat_promoNights_23', name: 'Party in the Back', emoji: '🥳', cat: 'promoNights' },
  { id: 'nat_promoNights_24', name: "We're Number One", emoji: '☝️', cat: 'promoNights' },
  { id: 'nat_promoNights_25', name: 'Mascot Mayhem', emoji: '🎭', cat: 'promoNights' },
];

// Build hidden category achievements (16 total — categories that have a "collect whole category" hidden achievement)
export const NATIONAL_HIDDEN_ACHIEVEMENTS = Object.entries(NATIONAL_CATEGORIES)
  .filter(([, info]) => info.hiddenName)
  .map(([slug, info]) => ({
    id: `nat_hidden_${slug}`,
    name: info.hiddenName,
    desc: `Collect all ${NATIONAL_CATEGORIES[slug].name} window achievements`,
    icon: '🏆',
    category: 'bannerHidden',
    hiddenForCategory: slug,
  }));

// Full export: all 370 national achievements (354 window + 16 hidden)
export const NATIONAL_BANNER_ACHIEVEMENTS = [
  ...NATIONAL_WINDOW_ACHIEVEMENTS.map(a => ({
    id: a.id,
    name: a.name,
    desc: `${NATIONAL_CATEGORIES[a.cat].name}: ${a.name}`,
    icon: a.emoji,
    category: 'bannerNational',
    catSlug: a.cat,
  })),
  ...NATIONAL_HIDDEN_ACHIEVEMENTS,
];

// Map: category slug → array of window achievement IDs in that category
export const NATIONAL_CATEGORY_ACH_IDS = NATIONAL_WINDOW_ACHIEVEMENTS.reduce((acc, a) => {
  if (!acc[a.cat]) acc[a.cat] = [];
  acc[a.cat].push(a.id);
  return acc;
}, {});

// Map: category slug → hidden achievement ID
export const NATIONAL_HIDDEN_ACH_ID = Object.fromEntries(
  Object.entries(NATIONAL_CATEGORIES)
    .filter(([, info]) => info.hiddenName)
    .map(([slug]) => [slug, `nat_hidden_${slug}`])
);

/**
 * Check if any hidden category achievements should unlock based on collected window achievements.
 * @param {function} unlockFn - The unlockAchievement function
 */
export function checkNationalCategoryAchievements(unlockFn) {
  if (!unlockFn) return;
  const stored = JSON.parse(localStorage.getItem('bb84_achievements') || '{}');
  for (const [slug, windowIds] of Object.entries(NATIONAL_CATEGORY_ACH_IDS)) {
    const hiddenId = NATIONAL_HIDDEN_ACH_ID[slug];
    if (hiddenId && !stored[hiddenId] && windowIds.every(id => stored[id])) {
      unlockFn(hiddenId);
    }
  }
}