// Newspapers & Classified Ads Interactive Museum Exhibits (801-825)
// 25 entries celebrating 1984-era print media

const ENTRIES = [
  {
    id: 'nyt',
    exhibit: 'The New York Times',
    icon: '📰',
    matchText: 'Founded in 1851 as the New-York Daily Times, the newspaper entered a crowded market by promising measured reporting rather than the wild sensationalism common among some rival papers.',
    tagline: 'All the News That\'s Fit to Print',
    year: '1851',
    description: 'Founded in 1851 as the New-York Daily Times, the newspaper entered a crowded market by promising measured reporting rather than the wild sensationalism common among some rival papers. Over the years, The Times built an international reputation for political coverage, foreign correspondence, cultural criticism, and investigative journalism. Times Square was renamed for the newspaper after it moved its headquarters there in 1904. By 1984, a thick Sunday edition could supply a family with news, sports, reviews, puzzles, advertisements, and enough paper to occupy the breakfast table for hours.',
    founded: '1851',
    reputation: 'International journalism',
    iconic: true,
    category: 'newspaper',
    funFact: 'Times Square was named after the newspaper when it moved its headquarters there in 1904.',
  },
  {
    id: 'wapo',
    exhibit: 'The Washington Post',
    icon: '🏛️',
    matchText: 'Founded in 1877, The Washington Post grew from a local capital-city newspaper into one of America\'s most influential news organizations.',
    tagline: 'Democracy Dies in Darkness',
    year: '1877',
    description: 'Founded in 1877, The Washington Post grew from a local capital-city newspaper into one of America\'s most influential news organizations. Its reporters became nationally famous for investigating the Watergate scandal, while the paper also joined The New York Times in publishing material from the Pentagon Papers. In 1984, The Post reported record circulation levels as readers turned to it for politics, government, national affairs, and extensive coverage of life around Washington. For politicians, lobbyists, and federal employees, the morning paper could be considered required reading.',
    founded: '1877',
    famousFor: 'Watergate investigation',
    iconic: true,
    category: 'newspaper',
    funFact: 'The Post\'s Watergate reporting helped bring down a presidency.',
  },
  {
    id: 'wsj',
    exhibit: 'The Wall Street Journal',
    icon: '📈',
    matchText: 'First published in 1889, The Wall Street Journal became America\'s leading newspaper for business, finance, and economic reporting.',
    tagline: 'The Daily Diary of the American Dream',
    year: '1889',
    description: 'First published in 1889, The Wall Street Journal became America\'s leading newspaper for business, finance, and economic reporting. Its densely packed pages offered company news, commodity prices, bond information, stock tables, and analysis of events affecting the marketplace. Before electronic trading systems and online quotes, investors might wait for the morning paper to discover how companies and markets had performed. The Journal\'s distinctive illustrated portraits and serious gray appearance made it look unlike almost anything else on the newsstand.',
    founded: '1889',
    specialty: 'Business & finance',
    distinctive: 'Hedcut portraits',
    iconic: true,
    category: 'newspaper',
    funFact: 'The Journal\'s distinctive dot-portraits are called "hedcuts."',
  },
  {
    id: 'usatoday',
    exhibit: 'USA Today',
    icon: '🇺🇸',
    matchText: 'Launched by Gannett executive Allen Neuharth in 1982, USA Today looked radically different from traditional newspapers.',
    tagline: 'The Nation\'s Newspaper',
    year: '1982',
    description: 'Launched by Gannett executive Allen Neuharth in 1982, USA Today looked radically different from traditional newspapers. It featured bright color, national weather maps, short articles, charts, sports statistics, and sections designed for travelers and busy readers. Critics occasionally dismissed its compact stories as "news McNuggets," but the public responded quickly: circulation reached one million copies within roughly a year. In 1984, the young newspaper still felt like an experiment from the future-one that could be found at airports, hotels, vending boxes, and newsstands across the country.',
    founded: '1982',
    innovation: 'Color, weather maps, short articles',
    circulation: '1 million in first year',
    iconic: true,
    category: 'newspaper',
    funFact: 'Critics called USA Today\'s short stories "news McNuggets."',
  },
  {
    id: 'latimes',
    exhibit: 'Los Angeles Times',
    icon: '🌴',
    matchText: 'Founded in 1881, the Los Angeles Times grew alongside Southern California.',
    tagline: 'West Coast News Powerhouse',
    year: '1881',
    description: 'Founded in 1881, the Los Angeles Times grew alongside Southern California. What began as a regional paper eventually developed into a major national and international news organization, particularly during the decades after World War II. By 1984, its pages reflected a region at the center of entertainment, aerospace, immigration, politics, and the approaching Summer Olympics. Readers could move from serious foreign reporting to Dodgers coverage, movie-industry news, freeway traffic, and advertisements for homes that were already becoming alarmingly expensive.',
    founded: '1881',
    coverage: 'Entertainment, aerospace, Olympics',
    iconic: true,
    category: 'newspaper',
    funFact: 'The LA Times covered the 1984 Olympics in its own backyard.',
  },
  {
    id: 'chicagotribune',
    exhibit: 'Chicago Tribune',
    icon: '🏙️',
    matchText: 'The Chicago Tribune was founded in 1847, long before Chicago became the giant industrial and transportation center known in 1984.',
    tagline: 'World\'s Greatest Newspaper',
    year: '1847',
    description: 'The Chicago Tribune was founded in 1847, long before Chicago became the giant industrial and transportation center known in 1984. Under editor Joseph Medill, it developed into an influential Midwestern voice and a major supporter of the new Republican Party during the 1850s. The Tribune later described itself as the "World\'s Greatest Newspaper," the phrase behind the call letters WGN. For generations of Chicago families, the paper delivered city politics, neighborhood news, weather, Cubs and White Sox coverage, and arguments over which baseball team was causing more suffering that summer.',
    founded: '1847',
    callLetters: 'WGN = World\'s Greatest Newspaper',
    iconic: true,
    category: 'newspaper',
    funFact: 'WGN radio/TV call letters stand for "World\'s Greatest Newspaper."',
  },
  {
    id: 'bostonglobe',
    exhibit: 'The Boston Globe',
    icon: '⚾',
    matchText: 'The Boston Globe was founded in 1872 by six Boston businessmen and began publishing a Sunday edition in 1877.',
    tagline: 'New England\'s Voice',
    year: '1872',
    description: 'The Boston Globe was founded in 1872 by six Boston businessmen and began publishing a Sunday edition in 1877. The paper became an important New England institution, reporting on politics, education, local communities, and the region\'s unusually intense relationship with sports. By 1984, readers could open the Globe to follow Wade Boggs, Jim Rice, the Celtics, the Patriots, and every disagreement occurring at Boston City Hall. For many fans, the sports section was read first and the rest of the paper was handled only after the box scores had been examined.',
    founded: '1872',
    sportsFocus: 'Boggs, Rice, Celtics, Patriots',
    iconic: true,
    category: 'newspaper',
    funFact: 'Boston sports fans read the Globe\'s box scores before anything else.',
  },
  {
    id: 'philainquirer',
    exhibit: 'The Philadelphia Inquirer',
    icon: '📜',
    matchText: 'The first edition of what was then called The Pennsylvania Inquirer appeared on June 1, 1829.',
    tagline: 'Nearly Two Centuries of News',
    year: '1829',
    description: 'The first edition of what was then called The Pennsylvania Inquirer appeared on June 1, 1829. That original paper contained only four pages arranged in six columns, and an annual subscription cost eight dollars. News arrived by mail, ship, conversation, and whatever information reporters could gather while walking around Philadelphia. By 1984, The Inquirer had completed a dramatic journalistic revival and was being recognized among the country\'s leading metropolitan newspapers. Nearly every major chapter of American history had passed through its pages by then.',
    founded: '1829',
    originalCost: '$8 per year',
    pages: '4 pages, 6 columns',
    iconic: true,
    category: 'newspaper',
    funFact: 'The Inquirer\'s first subscription cost just $8 per year.',
  },
  {
    id: 'classifieds',
    exhibit: 'Classified Advertising',
    icon: '📋',
    matchText: 'Before websites, smartphone apps, and online marketplaces, Americans placed small newspaper advertisements to buy, sell, trade, rent, hire, and occasionally beg someone to take an unwanted sofa.',
    tagline: 'The Original Marketplace',
    description: 'Before websites, smartphone apps, and online marketplaces, Americans placed small newspaper advertisements to buy, sell, trade, rent, hire, and occasionally beg someone to take an unwanted sofa. Classified sections could stretch across dozens of tightly printed pages, organized under headings such as Automobiles, Employment, Real Estate, Pets, Merchandise, and Personals. Readers circled possibilities with a pen, called from a home telephone, and hoped the item had not already been sold. A good Sunday classified section could occupy an entire morning and produce at least three questionable purchasing decisions.',
    sections: ['Automobiles', 'Employment', 'Real Estate', 'Pets', 'Merchandise', 'Personals'],
    method: 'Pen, phone, hope',
    category: 'classified',
    iconic: true,
    funFact: 'A good Sunday classifieds section could cause three questionable purchases.',
  },
  {
    id: 'personal_ads',
    exhibit: 'Personal Ads',
    icon: '💌',
    matchText: 'SINGLE WHITE MALE, 32, enjoys bowling, science-fiction movies, microwave dinners, and maintaining detailed National League statistics.',
    tagline: 'Seeking Companionship',
    description: 'SINGLE WHITE MALE, 32, enjoys bowling, science-fiction movies, microwave dinners, and maintaining detailed National League statistics. Seeking pleasant woman who appreciates quiet evenings, understands that baseball games may enter extra innings, and will not rearrange record collection without permission. DIVORCED FEMALE, 29, enjoys dancing, travel, and men who own reliable automobiles. Must have steady employment and no unexplained collection of CB radios. Replies must include photograph and self-addressed stamped envelope. Serious inquiries only. No collect calls after 10 p.m.',
    sampleAds: ['SWM 32: bowling, sci-fi, baseball stats', 'DF 29: dancing, travel, reliable cars'],
    requirements: 'Photo + SASE',
    category: 'classified',
    funFact: 'Personal ads required a self-addressed stamped envelope for replies.',
  },
  {
    id: 'employment_classifieds',
    exhibit: 'Employment Classifieds',
    icon: '💼',
    matchText: 'WORD PROCESSOR OPERATOR WANTED. Must type 60 words per minute and know the difference between a floppy disk and a drink coaster.',
    tagline: 'Help Wanted',
    description: 'WORD PROCESSOR OPERATOR WANTED. Must type 60 words per minute and know the difference between a floppy disk and a drink coaster. VIDEO STORE CLERK. Evenings and weekends. Must alphabetize correctly, recommend action movies, and politely remind customers to rewind. COMPUTER PROGRAMMER. Experience with COBOL preferred. Employer confidently predicts computers will remain a small but promising field. NEWSPAPER CARRIER. Early mornings, all weather. Bicycle and strong throwing arm helpful. Dog-negotiation experience considered a plus.',
    listings: ['Word processor operator', 'Video store clerk', 'COBOL programmer', 'Newspaper carrier'],
    category: 'classified',
    funFact: '1984 job listings predicted computers would remain "a small but promising field."',
  },
  {
    id: 'real_estate',
    exhibit: 'Real Estate Listings',
    icon: '🏠',
    matchText: 'CHARMING THREE-BEDROOM RANCH - $72,900. Attached garage, finished basement, wall-to-wall carpeting, wood-paneled recreation room, and modern avocado-green appliances.',
    tagline: 'For Sale by Owner',
    price: '$72,900',
    description: 'CHARMING THREE-BEDROOM RANCH - $72,900. Attached garage, finished basement, wall-to-wall carpeting, wood-paneled recreation room, and modern avocado-green appliances. Spacious backyard includes metal swing set and unidentified patch where grass refuses to grow. Convenient to schools, shopping, and the new four-lane highway residents were promised would remain quiet. Seller will leave drapes, ceiling fan, and enormous television antenna. Motivated owner relocating after discovering how much interest is charged over a 30-year mortgage.',
    features: ['3 bedrooms', 'Attached garage', 'Finished basement', 'Wood-paneled rec room', 'Avocado-green appliances'],
    category: 'classified',
    funFact: 'A 3-bedroom ranch in 1984 cost just $72,900.',
  },
  {
    id: 'automotive',
    exhibit: 'Automotive Classifieds',
    icon: '🚗',
    matchText: '1978 CHEVROLET MALIBU - $1,350. Runs well except when cold, hot, damp, dry, or facing uphill.',
    tagline: 'Used Cars for Sale',
    description: '1978 CHEVROLET MALIBU - $1,350. Runs well except when cold, hot, damp, dry, or facing uphill. New radio. Nearly new tires. Owner says knocking sound "adds character." 1981 FORD ESCORT - $2,900. Excellent fuel economy. Manual transmission. Interior smells faintly of french fries. 1973 PINTO - BEST OFFER. Previous owner insists fuel tank has "never personally caused him a problem." 1979 CAMARO - $4,700. T-tops, cassette deck, louvers, and enough attitude to lower property values throughout the neighborhood.',
    listings: ['1978 Chevy Malibu - $1,350', '1981 Ford Escort - $2,900', '1973 Pinto - Best Offer', '1979 Camaro - $4,700'],
    category: 'classified',
    funFact: 'The Pinto\'s seller insisted the fuel tank "never personally caused him a problem."',
  },
  {
    id: 'business_listings',
    exhibit: 'Business Listings',
    icon: '🔍',
    matchText: 'CLARK & BEHB DETECTIVE AGENCY. Missing persons, suspicious neighbors, misplaced pets, and mysteries local police have politely declined to investigate.',
    tagline: 'Professional Services',
    description: 'CLARK & BEHB DETECTIVE AGENCY - Missing persons, suspicious neighbors, misplaced pets, and mysteries local police have politely declined to investigate. Discretion promised. Results vary. CARMIE\'S BOOKKEEPING SERVICE - Accurate accounts, organized ledgers, and calm professional service. Please submit receipts in orderly fashion. Repeatedly delivering shoeboxes filled with unexplained paperwork may result in Carmie becoming Carmage. Management assumes no responsibility for the resulting rampage. ACE TV REPAIR - We make house calls and know exactly which side of the television to hit.',
    businesses: ['Clark & Behb Detective Agency', 'Carmie\'s Bookkeeping Service', 'Ace TV Repair'],
    category: 'classified',
    iconic: true,
    funFact: 'Clark & Behb Detective Agency handles mysteries the police have politely declined.',
  },
  {
    id: 'for_sale',
    exhibit: 'For Sale Ads',
    icon: '🏷️',
    matchText: 'EXERCISE BICYCLE - $45. Purchased January 2. Used January 3. Excellent clothes-hanging capacity.',
    tagline: 'Merchandise for Sale',
    description: 'EXERCISE BICYCLE - $45. Purchased January 2. Used January 3. Excellent clothes-hanging capacity. ATARI 2600 WITH 14 GAMES - $85. Includes joysticks, paddles, and three cartridges whose labels fell off years ago. QUEEN-SIZE WATERBED - $100. Buyer removes. Upstairs location. Bring several strong friends and a deep understanding of fluid dynamics. COMPLETE ENCYCLOPEDIA SET - $75. Everything mankind knew as of 1976. Several volumes never opened.',
    listings: ['Exercise bicycle - $45', 'Atari 2600 + 14 games - $85', 'Queen waterbed - $100', 'Encyclopedia set - $75'],
    category: 'classified',
    funFact: 'The exercise bicycle had "excellent clothes-hanging capacity."',
  },
  {
    id: 'apartment_rentals',
    exhibit: 'Apartment Rentals',
    icon: '🔑',
    matchText: 'ONE-BEDROOM APARTMENT - $325 MONTHLY. Heat included. Quiet building except for upstairs tenant who practices trumpet between midnight and 2 a.m.',
    tagline: 'For Rent',
    description: 'ONE-BEDROOM APARTMENT - $325 MONTHLY. Heat included. Quiet building except for upstairs tenant who practices trumpet between midnight and 2 a.m. EFFICIENCY NEAR DOWNTOWN - $240. Kitchen, sleeping area, and living room are technically the same room. Ideal for person who dislikes unnecessary walking. TWO-BEDROOM DUPLEX - $410. Off-street parking, washer hookup, and landlord who promises to repair the bathroom ceiling "as soon as materials arrive." No pets, motorcycles, waterbeds, loud music, or relatives staying longer than three days.',
    listings: ['1BR - $325/mo', 'Efficiency - $240/mo', '2BR duplex - $410/mo'],
    restrictions: 'No pets, motorcycles, waterbeds, or long-staying relatives',
    category: 'classified',
    funFact: 'One apartment listing warned of a trumpet-playing upstairs tenant.',
  },
  {
    id: 'help_wanted',
    exhibit: 'Help Wanted Section',
    icon: '👷',
    matchText: 'ARCADE ATTENDANT: Make change, clear coin jams, and explain to angry teenagers that kicking the Galaga machine will not improve their score.',
    tagline: 'Now Hiring',
    description: 'ARCADE ATTENDANT: Make change, clear coin jams, and explain to angry teenagers that kicking the Galaga machine will not improve their score. RESTAURANT DISHWASHER: Immediate opening. Free meal included. Applicant should be comfortable with steam, noise, and plates that reproduce faster than they can be washed. DEPARTMENT STORE SALES ASSOCIATE: Must wear tie, remain polite, and know that every customer asking for the manager has already rejected your correct answer. BALLPARK VENDOR: Strong voice and stronger legs required.',
    listings: ['Arcade attendant', 'Restaurant dishwasher', 'Department store associate', 'Ballpark vendor'],
    category: 'classified',
    funFact: 'Arcade attendants had to explain that kicking Galaga wouldn\'t help.',
  },
  {
    id: 'property_sale',
    exhibit: 'Property for Sale',
    icon: '🌳',
    matchText: 'FORTY ACRES OUTSIDE TOWN - $38,000. Rolling land, mature trees, small creek, and abandoned shed that may contain farming equipment or raccoons with legal ownership claims.',
    tagline: 'Land for Sale',
    price: '$38,000',
    description: 'FORTY ACRES OUTSIDE TOWN - $38,000. Rolling land, mature trees, small creek, and abandoned shed that may contain farming equipment or raccoons with legal ownership claims. Electric service nearby. Well required. Seller says area is certain to grow once the proposed shopping center, interstate exit, and amusement park receive final approval. Perfect for farming, investment, retirement, or telling friends you own forty acres while continuing to live somewhere with indoor plumbing.',
    acreage: '40 acres',
    features: ['Rolling land', 'Mature trees', 'Small creek', 'Abandoned shed'],
    category: 'classified',
    funFact: 'The shed may contain farming equipment or raccoons with legal claims.',
  },
  {
    id: 'used_car_market',
    exhibit: 'Used Car Market',
    icon: '🔧',
    matchText: 'The 1984 used-car shopper faces an important choice: purchase from a dealer offering financing and a limited warranty, or answer a classified ad placed by a stranger named "Bud" who insists cash be brought behind the bowling alley.',
    tagline: 'Buyer Beware',
    description: 'The 1984 used-car shopper faces an important choice: purchase from a dealer offering financing and a limited warranty, or answer a classified ad placed by a stranger named "Bud" who insists cash be brought behind the bowling alley. Every used vehicle has supposedly belonged to a careful older driver, received regular maintenance, and spent most winters safely indoors. Mysteriously, each also has 137,000 miles, one mismatched door, and a glove compartment containing six expired inspection receipts. Bring a mechanic-or at least someone willing to crawl underneath.',
    dilemma: 'Dealer vs. stranger named Bud',
    redFlags: ['137,000 miles', 'Mismatched door', 'Expired inspection receipts'],
    advice: 'Bring a mechanic',
    category: 'classified',
    funFact: 'Every used car supposedly belonged to "a careful older driver."',
  },
  {
    id: 'business_opportunities',
    exhibit: 'Business Opportunities',
    icon: '💰',
    matchText: 'EARN $1,000 A WEEK FROM HOME! Stuff envelopes during your spare time. Send $39.95 for complete instructions explaining how to place advertisements telling other people to send you $39.95.',
    tagline: 'Get Rich Quick?',
    description: 'EARN $1,000 A WEEK FROM HOME! Stuff envelopes during your spare time. Send $39.95 for complete instructions explaining how to place advertisements telling other people to send you $39.95. OWN A VIDEO RENTAL STORE! Industry experts predict Americans will always rent physical tapes from neighborhood shops. START YOUR OWN COMPUTER CONSULTING BUSINESS! No computer required. Most customers do not understand them either. VENDING ROUTE AVAILABLE. Seller retiring after discovering machines do not refill themselves.',
    opportunities: ['Envelope stuffing scheme', 'Video rental store', 'Computer consulting', 'Vending route'],
    category: 'classified',
    funFact: 'The envelope-stuffing "opportunity" was a classic pyramid scheme.',
  },
  {
    id: 'newspaper_circulation',
    exhibit: 'Newspaper Circulation',
    icon: '📊',
    matchText: 'American newspapers were near their peak reach in 1984. Total weekday circulation was approximately 63.3 million copies.',
    tagline: 'Peak Print Era',
    year: '1984',
    description: 'American newspapers were near their peak reach in 1984. Total weekday circulation was approximately 63.3 million copies, meaning newspapers landed on porches, appeared in break rooms, filled vending boxes, and waited at nearly every diner counter in the country. The morning paper delivered yesterday\'s scores, today\'s weather, political news, television listings, grocery coupons, and the daily comic strips in one folded package. Missing delivery could prompt a household emergency and an angry telephone call before breakfast.',
    circulation: '63.3 million (weekday)',
    delivered: ['Scores', 'Weather', 'News', 'TV listings', 'Coupons', 'Comics'],
    iconic: true,
    category: 'newspaper',
    funFact: 'In 1984, 63.3 million newspapers were delivered every weekday.',
  },
  {
    id: 'sunday_edition',
    exhibit: 'Sunday Edition Ads',
    icon: '🗞️',
    matchText: 'The Sunday paper was less a newspaper than a weekly endurance test. Sections arrived devoted to news, sports, business, travel, entertainment, real estate, automobiles, comics, and classified advertising.',
    tagline: 'The Weekly Endurance Test',
    description: 'The Sunday paper was less a newspaper than a weekly endurance test. Sections arrived devoted to news, sports, business, travel, entertainment, real estate, automobiles, comics, and classified advertising. Inside were glossy inserts from department stores, supermarkets, electronics dealers, furniture warehouses, tire shops, and every restaurant offering a coupon. Families divided the package immediately: sports for Dad, coupons for Mom, comics for the children, and employment listings for whichever relative had recently announced he was "considering new opportunities."',
    sections: ['News', 'Sports', 'Business', 'Travel', 'Entertainment', 'Real Estate', 'Automobiles', 'Comics', 'Classifieds'],
    inserts: ['Department stores', 'Supermarkets', 'Electronics', 'Furniture', 'Tire shops', 'Restaurant coupons'],
    category: 'newspaper',
    funFact: 'The Sunday paper was divided: sports for Dad, coupons for Mom, comics for kids.',
  },
  {
    id: 'classified_display',
    exhibit: 'Classified Display Ads',
    icon: '❗',
    matchText: 'Not every classified advertisement was a tiny block of compressed words. Businesses willing to spend more could purchase a display ad with thick borders, oversized headlines, logos, drawings, photographs, and enough exclamation points to suggest a genuine retail emergency.',
    tagline: 'GOING OUT OF BUSINESS!',
    description: 'Not every classified advertisement was a tiny block of compressed words. Businesses willing to spend more could purchase a display ad with thick borders, oversized headlines, logos, drawings, photographs, and enough exclamation points to suggest a genuine retail emergency. GOING OUT OF BUSINESS! EVERYTHING MUST GO! FINAL THREE DAYS! Longtime readers sometimes noticed that the same store had apparently been going out of business every weekend since 1979. Management declined to explain its remarkable survival.',
    features: ['Thick borders', 'Oversized headlines', 'Logos', 'Drawings', 'Photographs'],
    category: 'classified',
    funFact: 'Some stores had been "going out of business" every weekend since 1979.',
  },
  {
    id: 'newspaper_tech',
    exhibit: 'Newspaper Technology',
    icon: '⚙️',
    matchText: 'Producing a 1984 newspaper required reporters, photographers, copy editors, typesetters, press operators, delivery drivers, and an unforgiving deadline.',
    tagline: 'From Press to Porch',
    description: 'Producing a 1984 newspaper required reporters, photographers, copy editors, typesetters, press operators, delivery drivers, and an unforgiving deadline. Stories arrived from local reporters and distant wire services, were edited and arranged into pages, transferred to printing plates, and run through enormous high-speed presses. Some major papers were building satellite printing plants so later news could be included while copies were produced closer to suburban readers. By dawn, thousands of bundles had to be loaded, routed, and delivered before the news became old.',
    roles: ['Reporters', 'Photographers', 'Copy editors', 'Typesetters', 'Press operators', 'Delivery drivers'],
    innovation: 'Satellite printing plants',
    category: 'newspaper',
    funFact: 'Major papers built satellite printing plants to reach suburban readers faster.',
  },
  {
    id: 'power_of_print',
    exhibit: 'The Power of Print',
    icon: '✊',
    matchText: 'In 1984, the newspaper was a shared daily record of American life. Presidents and ballplayers, wars and weddings, stock prices and supermarket sales all appeared on the same pages.',
    tagline: 'One Day, One Record',
    description: 'In 1984, the newspaper was a shared daily record of American life. Presidents and ballplayers, wars and weddings, stock prices and supermarket sales all appeared on the same pages. A headline could influence an election, expose corruption, announce a championship, or tell a neighborhood that someone\'s missing lawn mower had finally been recovered. The paper might be read at breakfast, carried to work, clipped for a scrapbook, used beneath a birdcage, and wrapped around tomorrow\'s garbage-but for one day, it told millions of readers what mattered.',
    impact: 'Influence elections, expose corruption, announce championships',
    uses: ['Read at breakfast', 'Carried to work', 'Clipped for scrapbook', 'Birdcage liner', 'Garbage wrapping'],
    iconic: true,
    inspirational: true,
    category: 'newspaper',
    funFact: 'The newspaper served as birdcage liner, scrapbook source, and garbage wrapper.',
  },
];

const VIEWED_EXHIBITS = new Set();
const EXHIBIT_VIEW_COUNTS = {};

export function findNewspapersClassifiedsEntry(adText) {
  return ENTRIES.find(e => e.matchText === adText) || null;
}

export function trackNewspapersClassifiedsView(entryId) {
  VIEWED_EXHIBITS.add(entryId);
  EXHIBIT_VIEW_COUNTS[entryId] = (EXHIBIT_VIEW_COUNTS[entryId] || 0) + 1;
  const unlocked = [];

  if (VIEWED_EXHIBITS.size >= 5) unlocked.push('news_reader');
  if (VIEWED_EXHIBITS.size >= 15) unlocked.push('news_junkie');
  if (VIEWED_EXHIBITS.size >= 25) unlocked.push('print_historian');

  return unlocked;
}

export function getNewspapersClassifiedsViewCount() {
  return VIEWED_EXHIBITS.size;
}