// 1984 Los Angeles Olympics Athletes & Iconic Moments
// 25 entries celebrating legendary performances and athletes

const ENTRIES = [
  {
    id: 'mary_lou_retton',
    exhibit: 'Mary Lou Retton',
    icon: '🏅',
    matchText: 'At just 16 years old, West Virginia gymnast Mary Lou Retton became America\'s sweetheart during the 1984 Los Angeles Olympics.',
    tagline: 'Perfect 10 Perfection',
    sport: 'Gymnastics',
    description: 'At just 16, Mary Lou Retton became America\'s sweetheart. Entering her final event, she needed a perfect 10 on vault to win all-around gold. She delivered exactly that, becoming the first American woman to win Olympic all-around gold with five total medals.',
    achievement: 'First American Woman All-Around Champion',
    medals: 5,
    category: 'gymnastics',
    iconic: true,
    funFact: 'Mary Lou Retton\'s perfect 10 vault performance remains one of the most iconic moments in Olympic gymnastics history.',
  },
  {
    id: 'carl_lewis',
    exhibit: 'Carl Lewis',
    icon: '🏃',
    matchText: 'Track star Carl Lewis arrived in Los Angeles with enormous expectations.',
    tagline: 'Four Gold Medals',
    sport: 'Track & Field',
    description: 'Carl Lewis won four gold medals in the 100m, 200m, long jump, and 4x100 relay. His achievement matched Jesse Owens\' legendary 1936 performance and cemented Lewis as one of the greatest athletes of his generation.',
    achievement: 'Matched Jesse Owens\' Four Golds',
    medals: 4,
    category: 'track',
    iconic: true,
    funFact: 'Carl Lewis\'s four-gold performance was one of the greatest athletic achievements at any Olympic Games.',
  },
  {
    id: 'greg_louganis',
    exhibit: 'Greg Louganis',
    icon: '🤸',
    matchText: 'Few athletes dominated their sport like American diver Greg Louganis.',
    tagline: 'Diving Dominance',
    sport: 'Diving',
    description: 'Greg Louganis captured gold medals in both springboard and platform diving. His graceful style and nearly flawless execution made him one of the undisputed stars of the 1984 Olympics.',
    achievement: 'Double Diving Gold',
    medals: 2,
    category: 'diving',
    iconic: true,
    funFact: 'Greg Louganis was renowned for his technical perfection and artistic grace in diving.',
  },
  {
    id: 'joan_benoit',
    exhibit: 'Joan Benoit',
    icon: '🏃‍♀️',
    matchText: 'The 1984 Olympics featured the first women\'s marathon in Olympic history.',
    tagline: 'Historic First',
    sport: 'Marathon',
    description: 'Joan Benoit took an early lead in the first Olympic women\'s marathon and never looked back, winning gold before a cheering Los Angeles crowd. Her victory changed perceptions about women\'s distance running worldwide.',
    achievement: 'First Olympic Women\'s Marathon Champion',
    medals: 1,
    category: 'track',
    historic: true,
    funFact: 'Joan Benoit\'s gold medal was a watershed moment for women\'s distance running in the Olympics.',
  },
  {
    id: 'edwin_moses',
    exhibit: 'Edwin Moses',
    icon: '🏃',
    matchText: 'By 1984, Edwin Moses had become nearly unbeatable in the 400-meter hurdles.',
    tagline: 'Dominance Continued',
    sport: 'Track & Field',
    description: 'Edwin Moses captured another Olympic gold in the 400m hurdles and extended one of the longest winning streaks in sports history. At one point, Moses went nearly ten years without losing a race.',
    achievement: 'Unbeatable Hurdler',
    medals: 1,
    winStreak: 'Nearly 10 years undefeated',
    category: 'track',
    iconic: true,
    funFact: 'Edwin Moses\'s dominance in the 400m hurdles was unparalleled in Olympic history.',
  },
  {
    id: 'team_usa_basketball',
    exhibit: 'Team USA Basketball',
    icon: '🏀',
    matchText: 'Before they became NBA legends, several young stars represented the United States in Los Angeles.',
    tagline: 'Future Legends',
    sport: 'Basketball',
    description: 'Team USA went undefeated on the way to Olympic gold, led by Michael Jordan, Patrick Ewing, Chris Mullin, and Sam Perkins. Many consider it one of the greatest amateur basketball teams ever assembled.',
    achievement: 'Perfect Gold Medal Run',
    medals: 1,
    stars: ['Michael Jordan', 'Patrick Ewing', 'Chris Mullin', 'Sam Perkins'],
    category: 'basketball',
    iconic: true,
    funFact: 'The 1984 Team USA basketball roster featured multiple future NBA Hall of Famers.',
  },
  {
    id: 'michael_jordan',
    exhibit: 'Michael Jordan',
    icon: '🐐',
    matchText: 'Most basketball fans remember Michael Jordan for his NBA championships with the Chicago Bulls.',
    tagline: 'Before the Legend',
    sport: 'Basketball',
    description: 'At 21 years old, Michael Jordan helped lead Team USA to Olympic gold. His speed, athleticism, and competitiveness gave fans an early glimpse of the greatness still to come.',
    achievement: 'Olympic Gold Before NBA Stardom',
    medals: 1,
    age: 21,
    category: 'basketball',
    iconic: true,
    funFact: 'Michael Jordan\'s Olympic gold was just the beginning of his legendary career.',
  },
  {
    id: 'patrick_ewing',
    exhibit: 'Patrick Ewing',
    icon: '🏀',
    matchText: 'Fresh off a standout college career at Georgetown, Patrick Ewing anchored Team USA\'s defense during the Olympics.',
    tagline: 'Paint Dominance',
    sport: 'Basketball',
    description: 'The future Hall of Famer dominated the paint and helped the Americans cruise to the gold medal. Within a year, he would become the top pick in the NBA Draft.',
    achievement: 'Olympic Gold, Future Hall of Famer',
    medals: 1,
    college: 'Georgetown',
    category: 'basketball',
    iconic: true,
    funFact: 'Patrick Ewing\'s Olympic performance showcased the skills that would define his Hall of Fame NBA career.',
  },
  {
    id: 'cheryl_miller',
    exhibit: 'Cheryl Miller',
    icon: '🏀',
    matchText: 'Long before the WNBA existed, Cheryl Miller was already one of the greatest women\'s basketball players in the world.',
    tagline: 'Women\'s Basketball Pioneer',
    sport: 'Basketball',
    description: 'The California native helped lead Team USA to the gold medal in Los Angeles and became one of the faces of women\'s sports during the 1980s.',
    achievement: 'Women\'s Basketball Leader',
    medals: 1,
    hometown: 'California',
    category: 'basketball',
    iconic: true,
    funFact: 'Cheryl Miller was a pioneer in women\'s basketball during an era before the WNBA.',
  },
  {
    id: 'team_usa_baseball',
    exhibit: 'Team USA Baseball',
    icon: '⚾',
    matchText: 'Baseball appeared as a demonstration sport during the 1984 Olympics.',
    tagline: 'Diamond Demo',
    sport: 'Baseball',
    description: 'Playing before large crowds at Dodger Stadium, Team USA captured the silver medal while showcasing some of the game\'s brightest young stars. Many would later enjoy successful Major League careers.',
    achievement: 'Silver Medal with Future MLB Stars',
    medals: 1,
    venue: 'Dodger Stadium',
    category: 'baseball',
    funFact: 'The 1984 Olympic baseball demonstration featured many future Major League stars.',
  },
  {
    id: 'mark_mcguire',
    exhibit: 'Mark McGwire',
    icon: '🔨',
    matchText: 'Before becoming one of baseball\'s most feared sluggers, Mark McGwire represented the United States during the 1984 Olympics.',
    tagline: 'Power Prospect',
    sport: 'Baseball',
    description: 'The Southern California native impressed scouts with tremendous power and helped Team USA reach the baseball final. His major league future looked bright.',
    achievement: 'Olympic Recognition of Future Star',
    hometown: 'Southern California',
    category: 'baseball',
    iconic: true,
    funFact: 'Mark McGwire\'s Olympic appearance was an early sign of his future baseball dominance.',
  },
  {
    id: 'barry_larkin',
    exhibit: 'Barry Larkin',
    icon: '⚾',
    matchText: 'Future Hall of Fame shortstop Barry Larkin also wore the red, white, and blue during the 1984 Olympics.',
    tagline: 'Future Hall of Famer',
    sport: 'Baseball',
    description: 'Known for speed, defense, and leadership, Larkin represented the U.S. and would become one of the most respected players of his generation and cornerstone of the Cincinnati Reds.',
    achievement: 'Olympic Star, Future Hall of Famer',
    team: 'Cincinnati Reds',
    category: 'baseball',
    iconic: true,
    funFact: 'Barry Larkin\'s Olympic participation preceded his Hall of Fame MLB career.',
  },
  {
    id: 'will_clark',
    exhibit: 'Will Clark',
    icon: '⚾',
    matchText: 'One of Team USA\'s rising baseball stars was first baseman Will Clark.',
    tagline: 'Smooth Swing',
    sport: 'Baseball',
    description: 'His smooth swing and outstanding defense helped establish him as one of the country\'s top amateur players. A few years later, he would become a star with the San Francisco Giants.',
    achievement: 'Olympic Star, Future MLB Star',
    team: 'San Francisco Giants',
    category: 'baseball',
    funFact: 'Will Clark\'s Olympic performance foreshadowed his successful San Francisco Giants career.',
  },
  {
    id: 'sam_eagle_mascot',
    exhibit: 'Sam the Olympic Eagle',
    icon: '🦅',
    matchText: 'The official mascot of the 1984 Olympics was Sam the Olympic Eagle.',
    tagline: 'Patriotic Symbol',
    official: true,
    description: 'Dressed in patriotic red, white, and blue, Sam became one of the most recognizable symbols of the Games. Olympic merchandise featuring the mascot could be found in stores throughout America.',
    significance: 'Official Olympic Symbol',
    merchandise: true,
    category: 'culture',
    funFact: 'Sam the Eagle mascot became an iconic symbol of the 1984 Los Angeles Olympics.',
  },
  {
    id: 'la_coliseum',
    exhibit: 'Los Angeles Memorial Coliseum',
    icon: '🏟️',
    matchText: 'The historic Los Angeles Memorial Coliseum served as the centerpiece of the 1984 Olympics.',
    tagline: 'Olympic Heart',
    official: true,
    description: 'More than 90,000 spectators packed the stadium for the opening and closing ceremonies. The Coliseum remains one of the most famous Olympic venues in history.',
    capacity: '90,000+',
    events: ['Opening Ceremony', 'Closing Ceremony'],
    category: 'venue',
    iconic: true,
    funFact: 'The LA Coliseum\'s 90,000+ capacity made it the centerpiece of the 1984 Olympic Games.',
  },
  {
    id: 'torch_relay',
    exhibit: 'The Torch Relay',
    icon: '🔥',
    matchText: 'The Olympic torch traveled thousands of miles across the United States before arriving in Los Angeles.',
    tagline: 'Journey Across America',
    official: true,
    description: 'Millions of Americans lined streets and highways to watch the relay pass. For many, it was their first personal connection to the Olympic Games.',
    reach: 'Millions witnessed',
    significance: 'National connection',
    category: 'ceremony',
    iconic: true,
    funFact: 'The 1984 torch relay created a personal connection to the Olympics across America.',
  },
  {
    id: 'americas_olympics',
    exhibit: 'America\'s Olympics',
    icon: '🇺🇸',
    matchText: 'The United States dominated the medal standings at the 1984 Summer Olympics.',
    tagline: 'Dominance Demonstrated',
    description: 'American athletes won 83 gold medals and 174 total medals, the highest totals of any participating nation. It was one of the most successful Olympic performances in U.S. history.',
    goldMedals: 83,
    totalMedals: 174,
    ranking: '1st',
    category: 'national',
    historic: true,
    funFact: 'The United States won more medals than any other nation at the 1984 Olympics.',
  },
  {
    id: 'opening_ceremonies',
    exhibit: 'The Opening Ceremony',
    icon: '🎭',
    matchText: 'The opening ceremonies dazzled audiences around the world with music, pageantry, and unforgettable moments.',
    tagline: 'Hollywood Spectacle',
    official: true,
    description: 'More than two billion viewers watched as Los Angeles officially welcomed the Olympic Games. It remains one of the most memorable Olympic openings ever staged.',
    viewers: '2+ billion',
    significance: 'Unforgettable spectacle',
    category: 'ceremony',
    iconic: true,
    funFact: 'The 1984 opening ceremony reached more than 2 billion viewers worldwide.',
  },
  {
    id: 'world_record_summer',
    exhibit: 'A World Record Summer',
    icon: '📈',
    matchText: 'Athletes set numerous Olympic and world records during the 1984 Games.',
    tagline: 'Record-Breaking Performance',
    description: 'From the track to the swimming pool, spectators witnessed performances remembered for decades. Los Angeles proved the perfect stage for athletic greatness.',
    records: 'Numerous',
    sports: ['Track & Field', 'Swimming'],
    category: 'records',
    funFact: 'The 1984 Olympics saw record-breaking performances across multiple sports.',
  },
  {
    id: 'team_usa_swimming',
    exhibit: 'Team USA Swimming',
    icon: '🏊',
    matchText: 'American swimmers delivered an outstanding performance in Los Angeles.',
    tagline: 'Pool Dominance',
    sport: 'Swimming',
    description: 'Led by stars such as Rowdy Gaines, the United States captured numerous gold medals and thrilled home crowds. Swimming became one of the most popular events.',
    medals: 'Multiple gold',
    stars: ['Rowdy Gaines'],
    category: 'swimming',
    iconic: true,
    funFact: 'American swimmers dominated the pool at the 1984 Los Angeles Olympics.',
  },
  {
    id: 'rowdy_gaines',
    exhibit: 'Rowdy Gaines',
    icon: '🏊',
    matchText: 'After missing the 1980 Olympics because of the U.S. boycott, swimmer Rowdy Gaines finally got his Olympic moment in Los Angeles.',
    tagline: 'Second Chance Gold',
    sport: 'Swimming',
    description: 'He won three gold medals and became one of the most popular athletes of the Games. His perseverance inspired millions of Americans.',
    medals: 3,
    story: 'Returned from 1980 boycott',
    category: 'swimming',
    iconic: true,
    funFact: 'Rowdy Gaines\' three gold medals after missing 1980 Olympics inspired millions.',
  },
  {
    id: 'boycott_games',
    exhibit: 'The Boycott Games',
    icon: '⚠️',
    matchText: 'Several Eastern Bloc nations chose not to participate in the 1984 Olympics.',
    tagline: 'Cold War Echo',
    description: 'Despite the boycott, athletes from 140 countries competed in Los Angeles, creating one of the largest Olympic gatherings. The Games remained a major international success.',
    participation: '140 nations',
    significance: 'Largest gathering despite boycott',
    category: 'history',
    funFact: 'Despite Cold War boycotts, the 1984 Olympics had strong international participation.',
  },
  {
    id: 'olympic_fever',
    exhibit: 'Olympic Fever',
    icon: '🔥',
    matchText: 'Olympic fever swept across the United States during the summer of 1984.',
    tagline: 'National Excitement',
    description: 'Television ratings soared, souvenir sales exploded, and millions followed the action daily. For many Americans, it was the sporting event of the decade.',
    impact: 'Record television ratings',
    sales: 'Souvenir explosion',
    category: 'culture',
    iconic: true,
    funFact: 'The 1984 Olympics sparked unprecedented Olympic fever across America.',
  },
  {
    id: 'dreams_of_gold',
    exhibit: 'Dreams of Gold',
    icon: '💭',
    matchText: 'Every Olympic athlete arrives with the same goal: standing atop the medal podium.',
    tagline: 'Quest for Glory',
    description: 'In Los Angeles, countless dreams became reality as athletes competed for glory. For some, a single moment would define a lifetime of work.',
    universal: 'Every athlete\'s goal',
    significance: 'Dreams realized',
    category: 'values',
    inspirational: true,
    funFact: 'The 1984 Olympics saw countless lifelong dreams realized on the medal podium.',
  },
  {
    id: 'see_history_unfold',
    exhibit: 'See History Unfold',
    icon: '📜',
    matchText: 'The 1984 Los Angeles Olympics produced unforgettable champions, memorable moments, and lasting memories.',
    tagline: 'Legacy Lives On',
    description: 'From Mary Lou Retton\'s perfect 10 to Carl Lewis\'s four gold medals, the Games showcased the very best of sport. More than forty years later, America still remembers that magical summer.',
    legendary: 'Unforgettable champions',
    legacy: 'Still remembered',
    category: 'legacy',
    iconic: true,
    funFact: 'The 1984 Los Angeles Olympics remain one of the most memorable Olympic Games in history.',
  },
];

const VIEWED_EXHIBITS = new Set();
const EXHIBIT_VIEW_COUNTS = {};

export function findOlympicsAthletes1984Entry(adText) {
  return ENTRIES.find(e => e.matchText === adText) || null;
}

export function trackOlympicsAthletes1984View(entryId) {
  VIEWED_EXHIBITS.add(entryId);
  EXHIBIT_VIEW_COUNTS[entryId] = (EXHIBIT_VIEW_COUNTS[entryId] || 0) + 1;
  const unlocked = [];

  if (VIEWED_EXHIBITS.size >= 5) unlocked.push('athlete_watcher');
  if (VIEWED_EXHIBITS.size >= 15) unlocked.push('olympic_historian');
  if (VIEWED_EXHIBITS.size >= 25) unlocked.push('1984_legend');

  return unlocked;
}

export function getOlympicsAthletes1984ViewCount() {
  return VIEWED_EXHIBITS.size;
}