// Philadelphia Phillies Broadcast Lines — 1984
// Harry Kalas & Richie Ashburn — Voice of the Phillies at Veterans Stadium

export function pickPhilliesLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, p) => sum + p.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickPhilliesPlayerLine(playerName) {
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive — base hit.\"",
    "\"Long drive to left — way back — gone. Home run!\"",
    "\"Ground ball to short — over to first — in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"The Phillies have some very dangerous hitters in this lineup.\"",
    "\"Hard to believe, Harry — this ballclub can explode for runs at any moment.\"",
    "\"Philadelphia baseball at its finest tonight at Veterans Stadium.\"",
    "\"This is a deep, experienced ballclub. They've been here before.\"",
    "\"The Phillies are never out of it. That's what experience does for a ball team.\"",
    "\"A battle-tested lineup — Michael Jack Schmidt leading the way.\"",
    "\"Talent up and down this roster. The Phillies are a dangerous team.\"",
    "\"South Philadelphia is rocking tonight — good crowd for good baseball.\"",
    "\"This is a proud franchise with a proud history.\"",
    "\"Philadelphia fans bring the energy. This crowd is into it tonight.\"",
    "\"Hard to believe, Harry — the Phillies simply do not quit.\"",
    "\"A fine ballclub in every respect. The Phillies are playing good baseball.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Schmidt may be the finest third baseman who ever played the game.\"",
    "\"Steve Carlton has been doing this for fifteen years — pure mastery.\"",
    "\"Juan Samuel gives this team a completely different dimension with his speed.\"",
    "\"The Phanatic is fired up — that's always a good sign for the Phillies.\"",
    "\"This pitching staff has the pedigree to keep the Phillies in any game.\"",
    "\"Hard to believe, Harry — what Michael Jack Schmidt has meant to this franchise.\"",
    "\"Garry Maddox covers that outfield like no one else in baseball.\"",
    "\"Carlton's slider — you simply cannot hit it when it's working.\"",
    "\"Two-thirds of the world is covered by water, Harry. The rest is covered by Garry Maddox.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful night here at Veterans Stadium in South Philadelphia.\"",
    "\"The lights are on at The Vet — that always means business.\"",
    "\"Veterans Stadium — the home of Phillies baseball since 1971.\"",
    "\"A fine crowd in South Philadelphia. These fans know the game.\"",
    "\"Hard to believe, Harry — you couldn't ask for a better night for baseball.\"",
    "\"The Phanatic is at it again — always keeping the crowd entertained.\"",
    "\"The artificial turf is quick here at The Vet — everything happens fast.\"",
    "\"A warm summer evening in Philadelphia — perfect for baseball.\"",
    "\"Veterans Stadium — a great place to watch a ballgame.\"",
    "\"The old ballpark on Broad Street, and the Phillies are playing tonight.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd at Veterans Stadium is into this ballgame.\"",
    "\"Philadelphia fans are knowledgeable — they appreciate fine play.\"",
    "\"South Philly fans are not shy about letting you know how they feel.\"",
    "\"The upper deck is making some noise tonight.\"",
    "\"Hard to believe, Harry — listen to this crowd!\"",
    "\"The Phillies fans gave that a fine ovation.\"",
    "\"Nobody roars like a Philadelphia crowd when the home team delivers.\"",
    "\"This crowd is wound up. You can feel it.\"",
    "\"The Phillies faithful are behind their team tonight.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Veterans Stadium, everyone. A wonderful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"Baseball at its best, right here in the City of Brotherly Love.\"",
    "\"Hard to believe, Harry — what a game this has been.\"",
    "\"A great game of baseball — that's what South Philadelphia is all about.\"",
    "\"Harry Kalas here alongside Richie Ashburn — the best seat in the house.\"",
    "\"There's something special about baseball at The Vet on a summer night.\"",
    "\"Take care of yourselves, everybody. Enjoy the ballgame.\"",
    "\"The great thing about baseball is you never know what's coming next.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"Watch that baby — OUTTA HERE! Michael Jack Schmidt has done it again!\"",
    "\"He crushed it — that ball is outta here, and the Phillies lead!\"",
    "\"Hard to believe, Harry — did you see how far that one went?\"",
    "\"A magnificent piece of hitting. Simply magnificent.\"",
    "\"The Phillies are making their move here at The Vet.\"",
    "\"Absolutely nobody does it like Michael Jack Schmidt.\"",
    "\"That ball is long gone. Harry Kalas calls it a home run for Philadelphia!\"",
  ]},
};

const PLAYER_TIDBITS = {
  "Mike Schmidt": {
    lines: [
      "Mike Schmidt entered professional baseball in 1971 as Philadelphia's second-round draft choice.",
      "Schmidt grew up in Dayton, Ohio and attended Ohio University.",
      "Michael Jack Schmidt has won eight consecutive Gold Gloves at third base.",
      "Schmidt had already led the National League in home runs six times entering this season.",
      "Mike Schmidt won consecutive NL Most Valuable Player Awards in 1980 and 1981.",
      "Schmidt was named the Most Valuable Player of the 1980 World Series.",
      "Michael Jack hit 48 home runs and drove in 121 during his 1980 MVP season.",
      "Schmidt led the league with 40 home runs during the 1983 pennant season.",
      "Mike Schmidt drew 128 walks in 1983 — hitters simply do not want to face him.",
      "Schmidt reached base at a .399 clip in 1983. That is extraordinary.",
      "Michael Jack Schmidt hit the only home run in Philadelphia's 1–0 victory in Game One of the 1983 NLCS.",
      "Schmidt's first-inning homer stood up for the entire afternoon. That's what he can do.",
      "Few players in the history of this game combine offensive and defensive excellence the way Schmidt does.",
      "Hard to believe, Harry — what Michael Jack has accomplished in a Phillies uniform.",
      "Michael Jack drives in runs. That is what he does.",
      "Schmidt provides both exceptional power and outstanding defense. He does everything.",
      "You simply cannot give Schmidt a pitch he can handle. He will not miss it.",
      "Schmidt is the cornerstone of this franchise. Has been for over a decade.",
      "Schmidt's power is most dangerous when he gets his arms fully extended.",
      "Schmidt enters 1984 as one of the most feared right-handed hitters in the entire game.",
    ],
  },
  "Steve Carlton": {
    lines: [
      "Steve Carlton won the Cy Young Award in 1972, 1977, 1980, and 1982 — four times, Harry.",
      "Carlton became the first pitcher in baseball history to win four Cy Young Awards.",
      "Lefty won 27 games for a Philadelphia club that won only 59 in 1972. Hard to believe.",
      "Carlton posted a 1.97 ERA with 310 strikeouts in 1972 — one of the finest seasons in modern history.",
      "Steve Carlton won his 300th major-league game on September 23rd, 1983, striking out 12 Cardinals.",
      "Carlton finished 1983 with 275 strikeouts — he led the National League.",
      "He also led the league with 283 and two-thirds innings pitched. The man is a workhorse.",
      "Lefty doesn't talk to the press. He prefers to let his performances do the speaking.",
      "Carlton's slider remains one of the most difficult pitches in baseball to hit.",
      "Steve Carlton can bury that slider beneath the hands of a right-handed hitter.",
      "Lefty's slider can look like a strike until it disappears beneath the bat.",
      "Carlton became the first left-handed pitcher to reach 3,000 career strikeouts, back in 1981.",
      "Steve Carlton enters 1984 with four Cy Young Awards, 300 victories, and more than 3,000 strikeouts.",
      "Hard to believe, Harry — what Lefty has accomplished in a Phillies uniform.",
      "Carlton came to Philadelphia from St. Louis in a controversial trade — and became a legend.",
      "Carlton's silence with the press has made him one of baseball's most mysterious figures.",
      "Steve Carlton is a workout fanatic — still in magnificent condition at this stage of his career.",
      "Carlton remains capable of finishing what he starts. He has completed eight games this year.",
      "The slider is the great equalizer for Carlton — it neutralizes right-handed and left-handed hitters alike.",
    ],
  },
  "Juan Samuel": {
    lines: [
      "Juan Samuel was signed by Philadelphia as an amateur free agent in April of 1980.",
      "Samuel came to the Phillies organization from the Dominican Republic.",
      "Juan Samuel reached the major leagues late in the 1983 pennant race.",
      "He collected 18 hits in 65 at-bats during his first major-league trial — and scored 14 runs in only 18 games.",
      "Samuel appeared in three games during the 1983 World Series.",
      "Juan Samuel gives this club a dangerous combination of speed and power.",
      "The speed of Juan Samuel on the basepaths is something to behold.",
      "Samuel's bat speed alone would make him a prospect — the legs make him special.",
      "He can turn an ordinary ground ball into a close play at first base.",
      "Juan Samuel is still one of the youngest players on this Philadelphia roster.",
      "Hard to believe, Harry — the season this young man is having.",
    ],
  },
  "Ivan DeJesus": {
    lines: [
      "Iván DeJesus is a veteran shortstop from Puerto Rico.",
      "DeJesus came to Philadelphia in the 1982 trade involving Larry Bowa — and a young Ryne Sandberg.",
      "Iván DeJesus led the National League with 104 runs scored back in 1978.",
      "He played 160 games for the Cubs in both 1978 and 1979 — the definition of durability.",
      "DeJesus played 158 games for the Phillies in the 1983 pennant season.",
      "He scored 60 runs and drove in 45 during 1983 — solid contributions up the middle.",
      "Iván DeJesus stole 11 bases and drew 53 walks in 1983.",
      "DeJesus brings extensive experience to this middle infield — he has played in both leagues.",
      "Hard to believe, Harry — Iván DeJesus is capable of taking an extra base when the opportunity presents itself.",
    ],
  },
  "Von Hayes": {
    lines: [
      "Von Hayes was part of the famous five-for-one trade with Cleveland.",
      "Philadelphia gave up five players for Hayes — Manny Trillo, Julio Franco, and three others.",
      "He was quickly nicknamed 'Five-for-One' after that trade, Harry.",
      "Von Hayes can play first base or the outfield without forcing a major lineup change.",
      "Hayes hit .265 during his first season with the Phillies and stole 20 bases.",
      "He is at his best driving the ball into the right-center-field gap.",
      "Von Hayes gives the lineup an unusual combination of size and speed.",
      "He is still young enough to become a central figure in this Philadelphia lineup.",
      "Hard to believe, Harry — Von Hayes is developing into exactly the kind of run-producer the Phillies envisioned.",
    ],
  },
  "Glenn Wilson": {
    lines: [
      "Glenn Wilson was selected 18th overall by Detroit in the first round of the 1980 draft.",
      "Wilson hit .292 with 12 home runs in 84 games during his 1982 rookie season with the Tigers.",
      "Detroit named him their team Rookie of the Year in 1982.",
      "Wilson and John Wockenfuss came to Philadelphia for Willie Hernández and Dave Bergman.",
      "Glenn Wilson was only 25 years old entering this season.",
      "Few outfielders can match Glenn Wilson's throwing arm — runners must respect it.",
      "Wilson's arm can change a runner's decision before the ball is even hit.",
      "Glenn Wilson can drive the ball to the gaps as well as over the fence.",
      "Hard to believe, Harry — what a find Glenn Wilson has been for this ballclub.",
    ],
  },
  "Garry Maddox": {
    lines: [
      "Two-thirds of the world is covered by water, Harry. The other third is covered by Garry Maddox.",
      "Maddox is known throughout baseball as the Secretary of Defense.",
      "He won eight consecutive Gold Gloves in center field — every year from 1975 through 1982.",
      "Garry Maddox served in the United States Army during the Vietnam War.",
      "Maddox drove home the winning run in the tenth inning of Game Five of the 1980 NLCS.",
      "That hit sent Philadelphia to its first World Series since 1950.",
      "Maddox homered in the eighth inning of Game One of the 1983 World Series — supplied the winning margin.",
      "Garry Maddox makes difficult catches look routine. He takes efficient routes and rarely appears hurried.",
      "He can play shallow because he gets back on the ball so well.",
      "Hard to believe, Harry — how Garry Maddox covers that outfield.",
      "Maddox has saved countless extra-base hits throughout his Philadelphia career.",
    ],
  },
  "Ozzie Virgil Jr.": {
    lines: [
      "Ozzie Virgil Jr. was born in Puerto Rico and comes from a historic baseball family.",
      "His father, Ozzie Virgil Sr., was the first Dominican-born player in major-league history.",
      "Virgil produced a game-winning grand slam during Philadelphia's 1983 pennant season.",
      "He hit six home runs in only 140 at-bats during 1983 — that is real power for a catcher.",
      "Ozzie Virgil gives the Phillies another catcher with genuine home-run capability.",
      "He is strong enough to drive an outside pitch to the opposite field.",
      "Hard to believe, Harry — young Virgil is only 27 years old entering this campaign.",
    ],
  },
  "Jeff Stone": {
    lines: [
      "Jeff Stone was one of fifteen children growing up in Missouri.",
      "Stone stole 123 bases for Class A Spartanburg in 1981 — a short-lived minor-league record.",
      "He stole another 90 bases for Reading in 1983 and was named the Eastern League's Most Valuable Player.",
      "Stone collected three hits in his first four major-league at-bats — including two triples.",
      "Jeff Stone may be the fastest player on this Philadelphia roster.",
      "He can turn an ordinary ground ball into a close play at first base.",
      "Stone's speed can force an infielder to rush an otherwise routine throw.",
      "Jeff Stone is dangerous the moment he reaches base.",
      "Hard to believe, Harry — the numbers Jeff Stone has put up since joining this club.",
    ],
  },
  "Tug McGraw": {
    lines: [
      "Tug McGraw's given name is Frank Edwin McGraw Jr. He became Tug a long time ago.",
      "McGraw began his career with the New York Mets in 1965 — he was a member of the 1969 Miracle Mets.",
      "Tug coined the phrase 'Ya Gotta Believe' during the 1973 pennant race, Harry. This city took it to heart.",
      "He helped the Mets come from last place to win the 1973 National League pennant.",
      "McGraw went 5–4 with a 1.46 ERA and 20 saves during Philadelphia's 1980 championship season.",
      "He allowed only 62 hits in 92 and a third innings that year. Extraordinary.",
      "Tug McGraw was on the mound for the final out of the 1980 World Series.",
      "He struck out Willie Wilson to give Philadelphia its first world championship. The city erupted.",
      "Tug leaped into the air after that strikeout. Hard to believe — one of the great moments in this franchise's history.",
      "McGraw's screwball — the scroogie — moves away from right-handed hitters.",
      "He combines movement, deception, and pure emotion on the mound.",
      "Tug McGraw remains one of the most popular players in the history of this franchise.",
      "He has pitched in four World Series entering this season.",
      "McGraw's energy can lift a crowd before he throws his first pitch.",
    ],
  },
  "Bill Campbell": {
    lines: [
      "Bill Campbell's nickname is 'Soup' — a natural reference to Campbell's Soup.",
      "Campbell served with the 101st Airborne Division during the Vietnam War — rose to the rank of sergeant.",
      "He won the very first American League Rolaids Relief Man Award back in 1976.",
      "Campbell went 17–5 in 78 relief appearances in 1976 and threw 167 and two-thirds innings without starting a game.",
      "Bill Campbell led the American League with 31 saves for Boston in 1977.",
      "He became one of the first players to benefit from baseball's new free-agent system.",
      "Campbell led the National League with 82 appearances in 1983 — working 122 innings for the Cubs.",
      "His screwball can be particularly difficult for left-handed hitters to handle.",
      "Hard to believe, Harry — the innings Bill Campbell has accumulated over his career.",
      "Campbell gives Philadelphia another veteran capable of handling almost any relief assignment.",
    ],
  },
  "Al Holland": {
    lines: [
      "Al Holland grew up in Roanoke, Virginia.",
      "Holland led the country with 143 strikeouts and a 0.54 ERA during the 1972 college season.",
      "He once threw a college no-hitter with 25 strikeouts — 25 strikeouts, Harry.",
      "Al Holland went 8–4 with 25 saves and a 2.26 ERA during the 1983 pennant season.",
      "His 25 saves established a Philadelphia club record at the time.",
      "Holland struck out 100 hitters in only 91 and two-thirds innings in 1983.",
      "Al Holland recorded the final out of Steve Carlton's 300th victory.",
      "He also recorded the final out of the 1983 National League Championship Series — striking out Bill Russell.",
      "Holland allowed only one hit in three and two-thirds World Series innings.",
      "He won the 1983 National League Rolaids Relief Man Award.",
      "Holland goes by 'Mr. T' — a reference that will not be lost on anyone who has seen him.",
      "Hard to believe, Harry — Al Holland is one of the National League's leading late-inning relievers.",
    ],
  },
  "Larry Andersen": {
    lines: [
      "Larry Andersen began his major-league career with Cleveland in 1975.",
      "He came to the Phillies during the 1983 season and immediately contributed.",
      "Andersen allowed only 19 hits in 26 and a third innings during his first Philadelphia season.",
      "His slider is his most important finishing pitch, Harry.",
      "Andersen can be used for one difficult hitter or several complete innings.",
      "Larry Andersen gives the manager a veteran bridge to the back of the bullpen.",
    ],
  },
  "Don Carman": {
    lines: [
      "Don Carman is a left-handed pitcher from Oklahoma City.",
      "He attended Seminole State College and the University of Oklahoma.",
      "Carman made his major-league debut on the final weekend of the 1983 pennant season.",
      "He enters 1984 with only a brief taste of major-league competition — but he has the talent.",
      "Carman gives the bullpen another possible left-handed option.",
    ],
  },
  "John Denny": {
    lines: [
      "John Denny is the reigning National League Cy Young Award winner.",
      "Denny went 19–6 during his first year in Philadelphia with a 2.37 ERA.",
      "He walked only 53 hitters in more than 242 innings. That is exceptional control, Harry.",
      "Denny allowed only nine home runs during the entire 1983 regular season.",
      "John Denny started Game One of the 1983 World Series for Philadelphia.",
      "His sinking pitches give the infield opportunities to turn double plays.",
      "Denny is most effective when hitters pound the ball into the ground.",
      "Hard to believe, Harry — John Denny's 1983 season was one of the finest by a Philadelphia right-hander.",
    ],
  },
  "Kevin Gross": {
    lines: [
      "Kevin Gross attended Oxnard College in California.",
      "He was selected by Philadelphia in the first round of the January 1981 secondary draft.",
      "Gross was only 22 years old when he joined Philadelphia's rotation last season.",
      "He went 4–6 with a 3.56 ERA as a rookie — gaining valuable experience during a pennant race.",
      "Kevin Gross completed one game and threw one shutout in 1983.",
      "He has the size and arm strength teams look for in a starting pitcher.",
      "Kevin Gross gives the Phillies a power arm for the future.",
    ],
  },
  "Charles Hudson": {
    lines: [
      "Charles Hudson was born in Ennis, Texas and pitched at Prairie View A&M.",
      "Hudson was drafted by Philadelphia in the 12th round in 1981.",
      "He went 8–8 with a 3.35 ERA in his rookie season, throwing 169 and a third innings.",
      "Charles Hudson struck out 101 hitters as a rookie — and completed three games.",
      "Hudson was the winning pitcher in Game Three of the 1983 NLCS.",
      "He helped Philadelphia defeat Los Angeles and reach the World Series — showing considerable poise for a rookie.",
      "Hard to believe, Harry — Charles Hudson has already pitched in a pennant race and a World Series.",
      "Hudson attacks hitters rather than nibbling around the strike zone.",
    ],
  },
  "Len Matuszek": {
    lines: [
      "Len Matuszek attended the University of Toledo and earned four varsity letters in baseball.",
      "Matuszek led the American Association in batting average, home runs, and RBI in 1981.",
      "He hit .275 for Philadelphia during his 1983 call-up — six doubles and four home runs in only 80 at-bats.",
      "Matuszek slugged .525 during the pennant race. That's a dangerous bat off the bench.",
      "He can play first base, third base, and the corner outfield.",
      "Len Matuszek gives this bench another dangerous left-handed bat.",
    ],
  },
  "Greg Gross": {
    lines: [
      "Greg Gross was named The Sporting News' National League Rookie of the Year back in 1974.",
      "He hit .314 with 185 hits during his first full season.",
      "Gross developed into one of baseball's finest professional pinch-hitters.",
      "He hit .302 with a .385 on-base percentage during the 1983 pennant season.",
      "Greg Gross struck out only 16 times in 245 at-bats. He simply does not give away at-bats.",
      "He is one of the first names a manager considers when a pinch-hitter is needed.",
      "Gross can serve a pitch into left field when a home run is not required.",
    ],
  },
  "Derrel Thomas": {
    lines: [
      "Derrel Thomas is a switch-hitting utility player who has played virtually every position on the field.",
      "Thomas was a member of the Los Angeles Dodgers' 1981 world championship team.",
      "He gives a manager unusual freedom when making double switches.",
      "Derrel Thomas can enter a game almost anywhere on the field.",
      "He can switch-hit and play nearly every position except catcher — a rare talent.",
    ],
  },
  "Bo Diaz": {
    lines: [
      "Bo Díaz was born in Venezuela and developed into one of baseball's strongest-throwing catchers.",
      "Díaz represented Cleveland in the 1981 All-Star Game.",
      "He established career highs with 18 home runs and 85 RBI during his outstanding 1982 season.",
      "Bo Díaz hit an ultimate grand slam on April 13th, 1983 — turned a three-run ninth-inning deficit into a victory.",
      "He caught Steve Carlton, John Denny, and the rest of Philadelphia's veteran staff throughout the pennant race.",
      "Bo Díaz has a strong throwing arm from behind the plate.",
      "He is not afraid to block the plate with the tying run charging home.",
    ],
  },
  "Sixto Lezcano": {
    lines: [
      "Sixto Lezcano won an American League Gold Glove in right field in 1979.",
      "He hit .321 with 28 home runs and 101 RBI during that excellent 1979 season.",
      "Lezcano became the first major leaguer to hit two Opening Day grand slams — in 1978 and 1980.",
      "Sixto Lezcano is known for an especially powerful throwing arm from right field.",
      "He remains dangerous against left-handed pitching.",
      "Lezcano can change a game with one swing or one throw.",
    ],
  },
  "Paul Owens": {
    lines: [
      "Paul Owens — 'The Pope' — has been a fixture in the Philadelphia organization for decades.",
      "Paul Owens managed this team to the 1983 pennant.",
      "Owens took over the managerial duties from Pat Corrales in 1983 and guided the club to the World Series.",
    ],
  },
};