// Pittsburgh Pirates Broadcast - 1984
// Radio: Lanny Frattare & Milo Hamilton (KDKA)
// Three Rivers Stadium - home of the Pirates since 1970
// All stats cutoff: end of 1983 season

export function pickPiratesLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickPiratesPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Lee Lacy": {
    lines: [
      "Lee Lacy's full name is Leondaus Lacy.",
      "Lacy was born in Longview, Texas.",
      "Lee Lacy grew up in Oakland, California.",
      "Lacy attended McClymonds High School in Oakland.",
      "Lee Lacy later played baseball at Laney College.",
      "The Los Angeles Dodgers selected Lacy in the second round of the January 1969 amateur draft.",
      "Lacy was originally developed primarily as a second baseman.",
      "Lee Lacy made his major-league debut with the Dodgers on June 30, 1972.",
      "Lacy's speed and versatility allowed him to play both the infield and outfield.",
      "Lee Lacy appeared in the 1974 World Series with Los Angeles.",
      "Lacy joined Pittsburgh before the 1979 season.",
      "Lee Lacy was a member of the Pirates' 1979 World Series championship team.",
      "Lacy appeared in all seven games of the 1979 World Series.",
      "Lee Lacy gradually developed from a utility player into a productive everyday outfielder.",
      "Lacy appeared in 108 games during the 1983 season.",
      "Lee Lacy collected 87 hits in 288 official at-bats.",
      "Lacy batted .302.",
      "Lee Lacy recorded 12 doubles, three triples and four home runs.",
      "Lacy stole 31 bases, the highest total on the Pirates.",
      "Lee Lacy scored 40 runs despite receiving fewer than 300 at-bats.",
      "Lacy recorded a .352 on-base percentage.",
      "Lee Lacy remains capable of filling in at second base when the Pirates rearrange their defense.",
      "His combination of contact hitting and speed makes him dangerous whenever he reaches first base.",
      "Lacy's veteran experience allows him to remain productive whether he starts or enters later in the game.",
    ],
  },
  "Johnny Ray": {
    lines: [
      "Johnny Ray's full name is John Cornelius Ray.",
      "Ray was born in Chouteau, Oklahoma.",
      "Johnny Ray attended Chouteau High School.",
      "Ray competed in baseball, basketball and football during high school.",
      "Johnny Ray later attended the University of Arkansas.",
      "Ray earned All-Southwest Conference recognition twice while playing for the Razorbacks.",
      "The Houston Astros selected Johnny Ray in the 12th round of the 1979 amateur draft.",
      "Pittsburgh acquired Ray from Houston on August 31, 1981.",
      "The principal established player sent to Houston was infielder Phil Garner.",
      "Johnny Ray made his major-league debut with Pittsburgh on September 2, 1981.",
      "Ray immediately established himself as the Pirates' regular second baseman.",
      "Johnny Ray appeared in all 162 games during the 1982 season.",
      "Ray batted .281 with 182 hits as a rookie.",
      "Johnny Ray collected 30 doubles, seven triples and seven home runs in 1982.",
      "Ray finished second in the 1982 National League Rookie of the Year voting.",
      "Johnny Ray appeared in 151 games during the 1983 season.",
      "Ray batted .283 with 163 hits.",
      "Johnny Ray collected 38 doubles, the highest total on the Pirates.",
      "Ray also recorded seven triples and five home runs.",
      "Johnny Ray drove in 53 runs and scored 68 times.",
      "Ray stole 18 bases.",
      "Johnny Ray struck out only 26 times in 576 official at-bats.",
      "Ray received the 1983 National League Silver Slugger Award at second base.",
      "As a switch-hitter with excellent contact ability, Ray is difficult to neutralize with a pitching change.",
      "His line-drive swing is especially well suited for finding the artificial-turf gaps at Three Rivers Stadium.",
    ],
  },
  "Bill Madlock": {
    lines: [
      "Bill Madlock was born in Memphis, Tennessee.",
      "Madlock grew up in Decatur, Illinois.",
      "Bill Madlock attended Eisenhower High School in Decatur.",
      "Madlock became widely known by the nickname \"Mad Dog.\"",
      "The Washington Senators selected Bill Madlock in the fifth round of the 1970 amateur draft.",
      "Madlock made his major-league debut with the Texas Rangers on September 7, 1973.",
      "Bill Madlock was traded to the Chicago Cubs before the 1974 season.",
      "Madlock won the National League batting championship with a .354 average in 1975.",
      "Bill Madlock repeated as batting champion by hitting .339 in 1976.",
      "Madlock later played for the San Francisco Giants.",
      "Pittsburgh acquired Bill Madlock during the 1979 season.",
      "Madlock batted .328 in 88 regular-season games after joining the Pirates.",
      "Bill Madlock helped Pittsburgh win the 1979 World Series.",
      "Madlock collected nine hits during the seven-game Series against Baltimore.",
      "Bill Madlock won his third National League batting championship by hitting .341 in 1981.",
      "Madlock appeared in 130 games during the 1983 season.",
      "Bill Madlock collected 153 hits in 473 official at-bats.",
      "Madlock batted .323 to win his fourth National League batting championship.",
      "Bill Madlock recorded 21 doubles and 12 home runs.",
      "Madlock drove in 68 runs and scored 68 times.",
      "Bill Madlock drew 49 walks.",
      "Madlock struck out only 24 times.",
      "Bill Madlock was selected to the 1983 National League All-Star team.",
      "His compact swing and extraordinary bat-to-ball ability make him extremely difficult to strike out.",
      "Madlock is comfortable hitting to every part of the field rather than relying solely upon pulling the ball.",
      "With four batting titles already to his credit, Madlock is the most accomplished pure hitter in the Pittsburgh lineup.",
    ],
  },
  "Jason Thompson": {
    lines: [
      "Jason Thompson's full name is Jason Dolph Thompson.",
      "Thompson was born in Hollywood, California.",
      "Jason Thompson attended Apple Valley High School.",
      "Thompson later attended California State University, Northridge.",
      "The Los Angeles Dodgers selected Thompson during the 1972 draft, but he did not sign.",
      "Detroit selected Jason Thompson in the fourth round of the 1975 amateur draft.",
      "Thompson made his major-league debut with the Tigers on April 23, 1976.",
      "Jason Thompson quickly established himself as a left-handed power hitter.",
      "Thompson hit 31 home runs and drove in 105 runs during the 1977 season.",
      "Jason Thompson was selected to the American League All-Star team in both 1977 and 1978.",
      "Thompson later played briefly for the California Angels.",
      "Pittsburgh acquired Jason Thompson before the 1981 season.",
      "Thompson was sometimes known by the nickname \"Rooftop\" because of his ability to drive pitches high and deep.",
      "Jason Thompson produced one of his finest seasons in 1982.",
      "Thompson batted .284 with 31 home runs and 101 RBI.",
      "Jason Thompson also drew 101 walks during the 1982 season.",
      "Thompson was selected to the 1982 National League All-Star team.",
      "Jason Thompson appeared in 152 games during 1983.",
      "Thompson batted .259 with 134 hits.",
      "Jason Thompson led Pittsburgh with 18 home runs.",
      "Thompson drove in a team-high 76 runs.",
      "Jason Thompson drew 99 walks and posted a .376 on-base percentage.",
      "Thompson's willingness to take a walk prevents pitchers from simply working around the middle of Pittsburgh's order.",
      "His left-handed power is especially important in a lineup containing several prominent right-handed hitters.",
      "Thompson can change a game with one swing, but he is equally valuable when he refuses to chase pitches outside the strike zone.",
    ],
  },
  "Tony Pena": {
    lines: [
      "Tony Pena's full name is Antonio Francisco Pena Padilla.",
      "Pena was born in Monte Cristi in the Dominican Republic.",
      "Pittsburgh signed Tony Pena as an amateur free agent during the 1975 season.",
      "Longtime Pirates scout Howie Haak played an important role in Pena's development.",
      "Tony Pena spent several seasons learning the position in the Pittsburgh farm system.",
      "Pena made his major-league debut on September 1, 1980.",
      "Tony Pena batted .300 during his first full major-league season in 1981.",
      "Pena became Pittsburgh's primary catcher.",
      "Tony Pena was selected to the National League All-Star team in 1982.",
      "Pena became famous for setting an unusually low target behind the plate.",
      "Tony Pena sometimes catches with one leg extended almost straight to the side.",
      "The unusual stance helps Pena remain low while presenting a clear target to the pitcher.",
      "Pena possesses an exceptionally quick throwing release.",
      "Tony Pena appeared in 151 games during the 1983 season.",
      "Pena collected 163 hits in 542 official at-bats.",
      "Tony Pena batted .301.",
      "Pena recorded 22 doubles, three triples and 15 home runs.",
      "Tony Pena drove in 70 runs.",
      "Pena scored 51 times and stole six bases.",
      "Tony Pena received his first National League Gold Glove Award in 1983.",
      "Pena finished 12th in the National League Most Valuable Player voting.",
      "Tony Pena's durability allows the Pirates to keep their best defensive catcher in the lineup almost every day.",
      "His arm can discourage runners from attempting to steal before the pitch is even delivered.",
      "Pena's aggressive hitting style gives Pittsburgh an unusually dangerous offensive player at catcher.",
      "Few catchers combine his athleticism, throwing ability and power at the plate.",
    ],
  },
  "Marvell Wynne": {
    lines: [
      "Marvell Wynne was born in Chicago, Illinois.",
      "Wynne bats and throws left-handed.",
      "Marvell Wynne was not selected during the amateur draft.",
      "The Kansas City Royals signed Wynne as an amateur free agent in 1978.",
      "Wynne later entered the New York Mets organization.",
      "Pittsburgh acquired Marvell Wynne from the Mets on June 14, 1983.",
      "Wynne made his major-league debut one day later, on June 15.",
      "Marvell Wynne quickly took over much of the playing time in center field.",
      "Wynne appeared in 103 games during his rookie season.",
      "Marvell Wynne accumulated 366 official at-bats despite arriving during June.",
      "Wynne collected 89 hits.",
      "Marvell Wynne recorded 16 doubles and two triples.",
      "Wynne hit seven home runs and drove in 26 runs.",
      "Marvell Wynne scored 66 times.",
      "Wynne stole 12 bases.",
      "Marvell Wynne drew 38 walks and posted a .319 on-base percentage.",
      "Wynne's speed enables him to cover considerable territory in center field.",
      "His left-handed bat helps balance a lineup containing Madlock, Pena and Berra.",
      "Marvell Wynne is still inexperienced enough that opposing pitchers are developing their scouting reports against him.",
      "Wynne's combination of speed and occasional power makes him more than a purely defensive center fielder.",
      "He can take an extra base whenever an outfielder is slow returning the ball to the infield.",
      "Marvell Wynne enters 1984 with an opportunity to establish himself as Pittsburgh's long-term answer in center field.",
    ],
  },
  "Doug Frobel": {
    lines: [
      "Doug Frobel's full name is Douglas Steven Frobel.",
      "Frobel was born in Ottawa, Ontario, Canada.",
      "Doug Frobel grew up in the Ottawa suburb of Nepean.",
      "Frobel attended Merivale High School.",
      "Doug Frobel was not selected during the amateur draft.",
      "Frobel attended a Pittsburgh Pirates tryout camp in Utica, New York.",
      "Pittsburgh signed Doug Frobel as a free agent on August 18, 1977.",
      "Frobel developed gradually through the Pirates' minor-league system.",
      "Doug Frobel made his major-league debut on September 5, 1982.",
      "Frobel entered 1983 as one of Pittsburgh's better power-hitting outfield prospects.",
      "Doug Frobel spent most of the 1983 season with Triple-A Hawaii.",
      "Frobel batted .304 for the Hawaii Islanders.",
      "Doug Frobel hit 24 home runs and drove in 80 runs at Triple-A.",
      "His performance earned him another promotion to Pittsburgh.",
      "Doug Frobel appeared in 32 major-league games during 1983.",
      "Frobel collected 17 hits in 60 official at-bats.",
      "Doug Frobel batted .283.",
      "Frobel recorded four doubles, one triple and three home runs.",
      "Doug Frobel drove in 11 runs and posted a .533 slugging percentage.",
      "Frobel possesses considerably more power than his limited major-league experience might suggest.",
      "His left-handed swing makes him a natural candidate to replace some of the power Pittsburgh lost from right field.",
      "Frobel remains vulnerable to strikeouts, but a mistake over the plate can travel a very long distance.",
    ],
  },
  "Dale Berra": {
    lines: [
      "Dale Berra's full name is Dale Anthony Berra.",
      "Berra was born in Ridgewood, New Jersey.",
      "Dale Berra is the son of New York Yankees legend Yogi Berra.",
      "Berra attended Montclair High School in New Jersey.",
      "Pittsburgh selected Dale Berra in the first round of the 1975 amateur draft.",
      "Berra was the 20th overall player selected.",
      "Dale Berra made his major-league debut on August 22, 1977.",
      "Berra developed into a shortstop and third baseman.",
      "Dale Berra was a member of Pittsburgh's 1979 championship club.",
      "Berra did not appear during the World Series itself.",
      "Dale Berra gradually became Pittsburgh's regular shortstop.",
      "Berra appeared in 161 games during the 1983 season.",
      "Dale Berra accumulated 537 official at-bats.",
      "Berra collected 135 hits.",
      "Dale Berra recorded 25 doubles and one triple.",
      "Berra hit 10 home runs and drove in 52 runs.",
      "Dale Berra scored 51 times.",
      "Berra drew 61 walks.",
      "Dale Berra reached first base seven times on catcher's interference during 1983, establishing a major-league record.",
      "Berra's 161 appearances demonstrate his unusual durability for a middle infielder.",
      "Dale Berra has enough power to punish a pitcher who treats the bottom of the lineup casually.",
      "His experience at third base gives Pittsburgh another option when Bill Madlock requires a rest.",
      "Berra's surname brings considerable attention, but he has earned regular playing time through his own versatility and durability.",
    ],
  },
  "Lee Mazzilli": {
    lines: [
      "Lee Mazzilli's full name is Lee Louis Mazzilli.",
      "Mazzilli was born and raised in New York City.",
      "Lee Mazzilli attended Abraham Lincoln High School in Brooklyn.",
      "The New York Mets selected Mazzilli in the first round of the 1973 amateur draft.",
      "Lee Mazzilli made his major-league debut on September 7, 1976.",
      "Mazzilli developed into a switch-hitting center fielder and leadoff hitter.",
      "Lee Mazzilli represented the Mets in the 1979 All-Star Game.",
      "Mazzilli hit a game-tying home run during the eighth inning of that game.",
      "Lee Mazzilli then drew a bases-loaded walk that forced home the winning run in the ninth inning.",
      "Mazzilli later played for Texas and the New York Yankees before joining Pittsburgh.",
      "Lee Mazzilli appeared in 109 games for the Pirates during 1983.",
      "Mazzilli collected 59 hits in 246 official at-bats.",
      "Lee Mazzilli hit five home runs and drove in 24 runs.",
      "Mazzilli stole 15 bases.",
      "Lee Mazzilli drew 49 walks and posted a .365 on-base percentage.",
      "His switch-hitting allows him to pinch-hit against either right-handed or left-handed pitching.",
      "Mazzilli can play all three outfield positions and provide emergency help at first base.",
      "His patience, speed and experience make him one of Pittsburgh's most useful late-game bench options.",
      "Mazzilli can enter as a pinch-hitter, remain as a defensive replacement and still become a stolen-base threat.",
    ],
  },
  "Brian Harper": {
    lines: [
      "Brian Harper's full name is Brian David Harper.",
      "Harper was born in Los Angeles, California.",
      "Brian Harper attended San Pedro High School.",
      "The California Angels selected Harper in the fourth round of the 1977 amateur draft.",
      "Brian Harper made his major-league debut with the Angels on September 29, 1979.",
      "Harper developed as both a catcher and outfielder.",
      "Pittsburgh acquired Brian Harper from California after the 1981 season.",
      "Veteran shortstop Tim Foli went to the Angels in the transaction.",
      "The Pirates used Harper primarily as an outfielder and pinch-hitter during his early Pittsburgh appearances.",
      "Brian Harper appeared in 61 games during the 1983 season.",
      "Harper collected 29 hits in 131 official at-bats.",
      "Brian Harper recorded four doubles and one triple.",
      "Harper hit seven home runs.",
      "Brian Harper drove in 20 runs.",
      "His seven home runs in only 131 at-bats demonstrate legitimate power.",
      "Harper's ability to catch gives the Pirates flexibility when constructing a compact exhibition roster.",
      "His outfield experience allows Pittsburgh to carry him without using a roster position solely for a reserve catcher.",
      "Harper is an aggressive hitter who is more likely to attack a strike than wait for a walk.",
      "He can be particularly useful when the Pirates need right-handed power from the bench.",
    ],
  },
  "Benny Distefano": {
    lines: [
      "Benny Distefano's full name is Benito James Distefano.",
      "Distefano was born in Brooklyn, New York.",
      "Benny Distefano bats and throws left-handed.",
      "Distefano attended Alvin Community College in Texas.",
      "The Los Angeles Dodgers selected Distefano in the 16th round of the January 1981 draft.",
      "Benny Distefano did not sign with Los Angeles.",
      "Toronto selected him in the second round of the June 1981 secondary draft.",
      "Pittsburgh later selected Benny Distefano in the second round of the January 1982 secondary draft.",
      "Distefano developed as a first baseman and corner outfielder.",
      "Benny Distefano played for Double-A Lynn during the 1983 season.",
      "Distefano appeared in 137 games.",
      "Benny Distefano collected 130 hits in 480 official at-bats.",
      "Distefano batted .271.",
      "Benny Distefano recorded 19 doubles and seven triples.",
      "Distefano hit 25 home runs and drove in 92 runs.",
      "Benny Distefano drew 63 walks while striking out only 40 times.",
      "Distefano posted a .357 on-base percentage and a .496 slugging percentage.",
      "Benny Distefano had not yet appeared in a major-league game entering 1984.",
      "Opposing pitchers therefore possess no firsthand major-league scouting history against him.",
      "His left-handed power makes him an intriguing pinch-hitting option despite his inexperience.",
    ],
  },
  "Jim Morrison": {
    lines: [
      "Jim Morrison's full name is James Forrest Morrison.",
      "Morrison was born in Pensacola, Florida.",
      "Jim Morrison attended South Georgia College.",
      "Morrison later played baseball at Georgia Southern University.",
      "Jim Morrison was selected several times during the amateur draft process.",
      "Philadelphia ultimately selected Morrison in the fifth round of the 1974 amateur draft.",
      "Jim Morrison made his major-league debut with the Phillies on September 18, 1977.",
      "Morrison later became a regular infielder with the Chicago White Sox.",
      "Jim Morrison can play both second base and third base.",
      "Morrison eventually joined the Pittsburgh organization.",
      "Jim Morrison appeared in 66 games during the 1983 season.",
      "Morrison collected 48 hits in 158 official at-bats.",
      "Jim Morrison batted .304.",
      "Morrison recorded seven doubles and two triples.",
      "Jim Morrison hit six home runs and drove in 25 runs.",
      "Morrison posted a .347 on-base percentage and a .487 slugging percentage.",
      "His six home runs in limited playing time demonstrate useful right-handed power.",
      "Morrison can replace either Johnny Ray or Bill Madlock without forcing Pittsburgh to move another starter.",
      "He is especially useful when a left-handed pitcher makes a right-handed pinch-hitter desirable.",
      "Morrison's ability to play several infield positions makes him a natural fit for an exhibition bench.",
    ],
  },
  "Joe Orsulak": {
    lines: [
      "Joe Orsulak's full name is Joseph Michael Orsulak.",
      "Orsulak was born in Glen Ridge, New Jersey.",
      "Joe Orsulak attended Parsippany Hills High School.",
      "Orsulak was a multi-sport athlete.",
      "Joe Orsulak earned all-state recognition as a soccer goalkeeper.",
      "He also played basketball and baseball.",
      "Pittsburgh selected Joe Orsulak in the sixth round of the 1980 amateur draft.",
      "Orsulak developed as a left-handed-hitting outfielder.",
      "Joe Orsulak spent most of the 1983 season with Triple-A Hawaii.",
      "Orsulak appeared in 139 games for the Islanders.",
      "Joe Orsulak batted .286 with 154 hits.",
      "Orsulak recorded 12 doubles and 13 triples.",
      "Joe Orsulak hit 10 home runs and drove in 58 runs.",
      "Orsulak stole 38 bases while being caught only eight times.",
      "Joe Orsulak made his major-league debut on September 1, 1983.",
      "Orsulak appeared in seven games for Pittsburgh.",
      "Joe Orsulak collected two hits and drove in one run.",
      "His speed makes him immediately useful as a pinch-runner.",
      "Orsulak's left-handed bat provides another option against right-handed relief pitching.",
      "His Triple-A combination of triples and stolen bases indicates a player capable of creating runs without relying upon home runs.",
    ],
  },
  "Rick Rhoden": {
    lines: [
      "Rick Rhoden's full name is Richard Alan Rhoden.",
      "Rhoden was born in Boynton Beach, Florida.",
      "Rick Rhoden suffered a serious bone infection in his leg during childhood.",
      "Doctors once considered amputating the leg.",
      "Rhoden recovered sufficiently to become an outstanding athlete.",
      "Rick Rhoden attended Atlantic Community High School.",
      "The Los Angeles Dodgers selected Rhoden with the 20th overall pick of the 1971 amateur draft.",
      "Rick Rhoden made his major-league debut on July 5, 1974.",
      "Rhoden became a regular member of the Dodgers' starting rotation.",
      "Rick Rhoden was selected to the National League All-Star team in 1976.",
      "Rhoden later joined the Pittsburgh Pirates.",
      "Rick Rhoden developed a reputation as one of baseball's best-hitting pitchers.",
      "Rhoden won the 1983 National League Silver Slugger Award for pitchers.",
      "Rick Rhoden batted .278 with one home run and 10 RBI during the season.",
      "Rhoden made 35 starts and one relief appearance in 1983.",
      "Rick Rhoden finished with a 13-13 record.",
      "Rhoden posted a 3.09 ERA.",
      "Rick Rhoden worked 244 and a third innings.",
      "Rhoden completed seven games and recorded two shutouts.",
      "Rick Rhoden struck out 153 batters while walking only 68.",
      "Rhoden surrendered only 13 home runs.",
      "Rick Rhoden also recorded the only save of his major-league career during 1983.",
      "Rhoden is an accomplished golfer in addition to being a pitcher.",
      "His athleticism helps him field his position and contribute offensively.",
      "Rhoden combines durability, control and competitive toughness, making him a logical opening-day-quality starter for this staff.",
    ],
  },
  "John Candelaria": {
    lines: [
      "John Candelaria's full name is John Robert Candelaria.",
      "Candelaria was born in Brooklyn, New York.",
      "John Candelaria is the son of Puerto Rican parents.",
      "Candelaria stands approximately six feet seven inches tall.",
      "John Candelaria is commonly known by the nickname \"The Candy Man.\"",
      "Pittsburgh selected Candelaria in the second round of the 1972 amateur draft.",
      "John Candelaria made his major-league debut on June 8, 1975.",
      "Candelaria immediately gave Pittsburgh a tall, hard-throwing left-handed starter.",
      "On August 9, 1976, John Candelaria threw a no-hitter against the Los Angeles Dodgers.",
      "The game was played at Three Rivers Stadium.",
      "Candelaria became the first Pirates pitcher since 1907 to throw a home no-hitter.",
      "John Candelaria enjoyed an exceptional season in 1977.",
      "Candelaria finished 20-5.",
      "John Candelaria led the National League with a 2.34 ERA.",
      "Candelaria was selected to the 1977 National League All-Star team.",
      "John Candelaria helped the Pirates win the 1979 World Series.",
      "Candelaria made 32 starts and one relief appearance during the 1983 season.",
      "John Candelaria finished 15-8.",
      "Candelaria posted a 3.23 ERA.",
      "John Candelaria worked 197 and two-thirds innings.",
      "Candelaria struck out 157 hitters while walking only 45.",
      "John Candelaria allowed only 15 home runs.",
      "His height creates a steep downward angle that can make pitches difficult to lift.",
      "Candelaria's left-handed power pitching provides a sharp contrast to the right-handed Rick Rhoden.",
      "When his control is sharp, Candelaria can dominate without allowing hitters to reach comfortable counts.",
    ],
  },
  "John Tudor": {
    lines: [
      "John Tudor's full name is John Thomas Tudor.",
      "Tudor was born in Schenectady, New York.",
      "John Tudor is a left-handed pitcher.",
      "The New York Mets selected Tudor during the 1975 amateur draft, but he did not sign.",
      "Boston selected John Tudor in the third round of the January 1976 secondary draft.",
      "Tudor developed in the Red Sox farm system.",
      "John Tudor made his major-league debut on August 16, 1979.",
      "Tudor gradually established himself in Boston's starting rotation.",
      "John Tudor won 13 games during the 1982 season.",
      "Tudor again made 34 starts in 1983.",
      "John Tudor went 13-12.",
      "Tudor posted a 4.09 ERA.",
      "John Tudor led the Red Sox with 242 innings pitched.",
      "Tudor completed seven games.",
      "John Tudor recorded two shutouts.",
      "Tudor struck out 136 batters.",
      "John Tudor walked 81.",
      "Tudor surrendered 32 home runs while pitching half his games at Fenway Park.",
      "Pittsburgh acquired John Tudor from Boston on December 6, 1983.",
      "The Pirates sent outfielder Mike Easler to the Red Sox.",
      "His control, change of speeds and deceptive delivery are more important than overwhelming velocity.",
      "Tudor's changeup can cause a hitter to swing before the ball reaches the plate.",
      "His arrival gives Pittsburgh a second established left-handed starter alongside Candelaria.",
    ],
  },
  "Jose DeLeon": {
    lines: [
      "Jose DeLeon was born in Rancho Viejo in the Dominican Republic.",
      "DeLeon is a right-handed pitcher.",
      "Pittsburgh selected Jose DeLeon in the third round of the 1979 amateur draft.",
      "DeLeon developed into one of the organization's most promising power pitchers.",
      "Jose DeLeon made his major-league debut on July 23, 1983.",
      "His first start came against the San Francisco Giants.",
      "Jose DeLeon pitched eight innings and earned the victory.",
      "DeLeon struck out nine hitters during his debut.",
      "Jose DeLeon remained in Pittsburgh's rotation for the rest of the season.",
      "DeLeon made 15 starts.",
      "Jose DeLeon finished with a 7-3 record.",
      "DeLeon posted a 2.83 ERA.",
      "Jose DeLeon worked 108 innings.",
      "DeLeon allowed only 75 hits.",
      "Jose DeLeon struck out 118 batters.",
      "His strikeout rate exceeded one batter per inning.",
      "Jose DeLeon completed three games.",
      "DeLeon recorded two shutouts.",
      "Jose DeLeon surrendered only five home runs.",
      "DeLeon finished seventh in the National League Rookie of the Year voting.",
      "His fastball gives the Pirates a genuine strikeout pitcher at the back of the rotation.",
      "DeLeon's relative unfamiliarity can make him particularly dangerous in an exhibition game.",
      "Opposing hitters have only 15 major-league starts from which to build their scouting reports.",
      "When DeLeon controls the strike zone, his combination of velocity and deception can be overpowering.",
    ],
  },
  "Kent Tekulve": {
    lines: [
      "Kent Tekulve's full name is Kenton Charles Tekulve.",
      "Tekulve was born in Cincinnati, Ohio.",
      "Kent Tekulve attended Marietta College.",
      "Tekulve was not selected during the amateur draft.",
      "Pittsburgh signed Kent Tekulve as a free agent in 1969.",
      "Tekulve made his major-league debut on May 20, 1974.",
      "Kent Tekulve is commonly known by the nickname \"Teke.\"",
      "Tekulve uses one of baseball's most distinctive submarine deliveries.",
      "Kent Tekulve releases the ball from a point close to the ground.",
      "His long, slender frame makes the delivery appear even more unusual.",
      "Tekulve's primary weapon is a sinking fastball delivered from the low arm angle.",
      "Kent Tekulve also uses a sweeping slider against right-handed hitters.",
      "Tekulve recorded 31 saves in both 1978 and 1979.",
      "Kent Tekulve helped Pittsburgh win the 1979 World Series.",
      "Tekulve recorded three saves during the seven-game Series.",
      "Kent Tekulve secured the final out of Game Seven in Baltimore.",
      "Tekulve made the National League All-Star team in 1980.",
      "Kent Tekulve appeared in 76 games during the 1983 season.",
      "Tekulve finished with a 7-5 record.",
      "Kent Tekulve posted an outstanding 1.64 ERA.",
      "Tekulve recorded 18 saves.",
      "Kent Tekulve worked 99 innings and finished 56 games.",
      "Tekulve allowed only 78 hits.",
      "Kent Tekulve surrendered just one home run during the entire season.",
      "Tekulve had accumulated 145 major-league saves through 1983.",
      "Kent Tekulve had never started a major-league game.",
      "Right-handed hitters can find it especially difficult to track a ball emerging from his low release point.",
      "Ground balls are a natural result when Tekulve's sinker drops beneath the hitter's barrel.",
    ],
  },
  "Don Robinson": {
    lines: [
      "Don Robinson's full name is Don Allen Robinson.",
      "Robinson was born in Ashland, Kentucky.",
      "Don Robinson attended Ceredo-Kenova High School in West Virginia.",
      "Pittsburgh selected Robinson in the third round of the 1975 amateur draft.",
      "Don Robinson made his major-league debut on April 10, 1978.",
      "Robinson immediately entered the Pirates' starting rotation.",
      "Don Robinson won 14 games during his rookie season.",
      "Robinson finished third in the 1978 National League Rookie of the Year voting.",
      "Don Robinson was the youngest member of Pittsburgh's 1979 World Series championship pitching staff.",
      "Robinson has worked primarily as a starter but is capable of pitching from the bullpen.",
      "Don Robinson is also an excellent hitter for a pitcher.",
      "Robinson received the 1982 National League Silver Slugger Award for pitchers.",
      "Don Robinson batted .282 with two home runs and 16 RBI during that season.",
      "Robinson was limited by physical problems during 1983.",
      "Don Robinson appeared in nine games.",
      "Robinson made six starts.",
      "Don Robinson finished 2-2 with a 4.46 ERA.",
      "Robinson worked 36 and a third innings and struck out 28 hitters.",
      "His starting background allows him to pitch several innings when a starter leaves early.",
      "Robinson can also be used as a pinch-hitter in an emergency.",
      "His right-handed power arm provides a useful contrast to the left-handed Rod Scurry.",
      "Robinson's ability to start, relieve and hit makes him one of the most versatile pitchers on the roster.",
    ],
  },
  "Rod Scurry": {
    lines: [
      "Rod Scurry's full name is Rodney Grant Scurry.",
      "Scurry was born in Sacramento, California.",
      "Rod Scurry attended Procter R. Hug High School in Reno, Nevada.",
      "Pittsburgh selected Scurry with the 11th overall pick of the 1974 amateur draft.",
      "Scurry spent approximately six seasons developing in the minor leagues.",
      "Rod Scurry made his major-league debut on April 17, 1980.",
      "Scurry is a left-handed pitcher.",
      "Rod Scurry possesses a sharp breaking ball capable of producing strikeouts.",
      "Scurry enjoyed his strongest season to that point in 1982.",
      "Rod Scurry recorded 14 saves with a 1.74 ERA.",
      "Scurry appeared in 61 games during the 1983 season.",
      "Rod Scurry finished 4-9.",
      "Scurry recorded seven saves.",
      "Rod Scurry worked 68 innings.",
      "Scurry struck out 67 hitters.",
      "Rod Scurry allowed 63 hits.",
      "Scurry also issued 53 walks.",
      "Rod Scurry posted a 5.56 ERA.",
      "His nearly one-strikeout-per-inning rate demonstrates the quality of his pitches.",
      "His walk total shows that command can disappear when he attempts to be too precise.",
      "Scurry is a natural matchup reliever against dangerous left-handed hitters.",
      "When he throws strikes, his breaking ball can make even accomplished hitters look uncomfortable.",
    ],
  },
  "Cecilio Guante": {
    lines: [
      "Cecilio Guante was born in Villa Mella in the Dominican Republic.",
      "Guante is a right-handed pitcher.",
      "Cecilio Guante represented the Dominican Republic during the 1979 Pan American Games.",
      "Guante helped his country earn a silver medal.",
      "Pittsburgh signed Cecilio Guante as an amateur free agent later in 1979.",
      "Guante developed as a hard-throwing pitcher in the Pirates' minor-league system.",
      "Cecilio Guante made his major-league debut on May 1, 1982.",
      "Guante appeared in 10 games during his first major-league trial.",
      "Cecilio Guante posted a 3.33 ERA in 27 innings during 1982.",
      "Guante became a full-time member of the Pittsburgh bullpen in 1983.",
      "Cecilio Guante appeared in 49 games.",
      "Guante finished 2-6.",
      "Cecilio Guante recorded nine saves.",
      "Guante worked 100 and a third innings without making a start.",
      "Cecilio Guante allowed 90 hits.",
      "Guante struck out 82 hitters.",
      "Cecilio Guante posted a 3.32 ERA.",
      "Guante's workload demonstrates that he is capable of pitching more than one inning at a time.",
      "His power repertoire gives Pittsburgh another strikeout option before Tekulve enters.",
      "Guante can bridge the middle innings, finish a game when Tekulve is unavailable or remain on the mound through several lineup rotations.",
      "His intense mound presence matches the velocity and movement of his pitches.",
    ],
  },
  "Lee Tunnell": {
    lines: [
      "Lee Tunnell's full name is Byron Lee Tunnell.",
      "Tunnell was born in Tyler, Texas.",
      "Lee Tunnell is a right-handed pitcher.",
      "Tunnell attended Baylor University.",
      "Pittsburgh selected Lee Tunnell in the second round of the 1981 amateur draft.",
      "Tunnell advanced quickly through the Pirates' farm system.",
      "Lee Tunnell made his major-league debut on September 4, 1982.",
      "Tunnell appeared in five games during his first major-league trial.",
      "Lee Tunnell entered Pittsburgh's starting rotation during 1983.",
      "Tunnell appeared in 35 games.",
      "Lee Tunnell made 25 starts.",
      "Tunnell finished with an 11-6 record.",
      "Lee Tunnell posted a 3.65 ERA.",
      "Tunnell worked 177 and two-thirds innings.",
      "Lee Tunnell completed five games.",
      "Tunnell recorded three shutouts.",
      "Lee Tunnell allowed 167 hits.",
      "Tunnell struck out 95 batters while walking 58.",
      "Lee Tunnell finished ninth in the National League Rookie of the Year voting.",
      "Although placed in your bullpen, Tunnell possesses the stamina of a full-time starter.",
      "He is an ideal long reliever when an exhibition starter is removed during the early innings.",
      "Tunnell can also make an emergency start without requiring any adjustment to his normal preparation.",
      "His presence gives Pittsburgh one of the deepest and most flexible pitching staffs in the game.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive - base hit.\"",
    "\"Long drive to left field - way back - gone. Home run!\"",
    "\"Ground ball to short - over to first - in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub has some real talent - Madlock, Pena, Thompson - the Pirates can play with anybody.\"",
    "\"Pittsburgh baseball is alive and well - the fans here at Three Rivers love their Bucs.\"",
    "\"This team has hitting and pitching - Bill Madlock won his fourth batting title last year.\"",
    "\"Three Rivers Stadium is home - and the Pirates are ready to make some noise in the NL East.\"",
    "\"Bill Madlock is one of the greatest pure hitters in baseball - four batting titles.\"",
    "\"Tony Pena is the best defensive catcher in the National League - Gold Glove.\"",
    "\"Kent Tekulve and that submarine delivery - there's nothing else like it in baseball.\"",
    "\"There's talent everywhere you look in this lineup - the Pirates can hurt you.\"",
    "\"This club is building something - Pittsburgh believes it can contend in the East.\"",
    "\"The fans in Pittsburgh have been waiting for another winner - they got one in '79.\"",
    "\"There's a buzz around the Pirates this year - people can feel something building.\"",
    "\"From Mad Dog to The Candy Man to Teke - the Pirates have characters at every position.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Bill Madlock has won four batting titles - that's extraordinary. Mad Dog can flat-out hit.\"",
    "\"Tony Pena is the best defensive catcher in the league - Gold Glove, great arm, and he can hit too.\"",
    "\"Johnny Ray is one of the toughest outs in the National League - Silver Slugger at second base.\"",
    "\"Rick Rhoden is one of the best-hitting pitchers in baseball - he won the Silver Slugger last year.\"",
    "\"Kent Tekulve and that submarine sinker - right-handed hitters don't have a chance.\"",
    "\"Jose DeLeon struck out 118 hitters in 108 innings as a rookie - that's electric stuff.\"",
    "\"John Candelaria threw a no-hitter right here at Three Rivers - The Candy Man can deal.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Three Rivers Stadium.\"",
    "\"The lights are on at Three Rivers - Pirates baseball tonight.\"",
    "Three Rivers Stadium - home of the Pirates since 1970.",
    "\"The artificial turf plays fast tonight - ground balls will scoot through the infield.\"",
    "\"You can see the Allegheny River beyond the outfield - Pittsburgh at its finest.\"",
    "\"The stands are filling up nicely - Pittsburgh loves its Pirates.\"",
    "\"The confluence of the Allegheny and Monongahela rivers - this city was built on baseball.\"",
    "\"Three Rivers is rocking tonight - the fans are into this one.\"",
    "\"The Steel City is buzzing tonight - Pittsburgh loves its Bucs.\"",
    "\"The Roberto Clemente gate - this franchise honors its legends.\"",
    "\"A perfect evening for baseball at Three Rivers.\"",
    "\"The cavernous dimensions here make it tough on home-run hitters.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here at Three Rivers is into this ballgame.\"",
    "\"Pirates fans are making some noise tonight.\"",
    "\"The fans in Pittsburgh bleed black and gold - they're fired up tonight.\"",
    "\"Three Rivers Stadium is rocking tonight.\"",
    "\"Pittsburgh fans are among the most loyal in baseball - they've been through a lot.\"",
    "\"The crowd is on its feet - they can feel something building here.\"",
    "\"A great turnout at Three Rivers tonight.\"",
    "\"These fans love their Bucs - from Mad Dog to The Candy Man to Teke.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Three Rivers Stadium, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball in Pittsburgh.\"",
    "\"From all of us here in the Steel City, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story - that's the beauty of this sport.\"",
    "\"Baseball in Pittsburgh - it's a tradition that runs deep in this city.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone - into the night at Three Rivers!\"",
    "\"Touch 'em all, Mad Dog!\"",
    "\"The Pirates are making their move here at Three Rivers.\"",
    "\"And the Bucs win it - what a finish!\"",
    "\"You won't see many better than that one.\"",
    "\"Holy cow, what a ballgame!\"",
  ]},
};