// Texas Rangers Broadcast - 1984
// Radio: Eric Nadel & Bill Mercer (KRLD) / TV: Steve Busby & Mark Holtz (KXAS)
// Arlington Stadium - home of the Rangers since 1972
// All stats cutoff: end of 1983 season

export function pickRangersLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickRangersPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Buddy Bell": {
    lines: [
      "Buddy Bell's full name is David Gus Bell.",
      "Buddy Bell was born in Pittsburgh, Pennsylvania.",
      "Bell is the son of former major-league outfielder Gus Bell.",
      "Buddy grew up around professional baseball because of his father's career.",
      "Cleveland selected Bell in the 16th round of the 1969 amateur draft.",
      "Buddy Bell reached the major leagues with Cleveland during the 1972 season.",
      "Bell was selected to his first American League All-Star team in 1973.",
      "Texas acquired Buddy Bell after the 1978 season.",
      "The Rangers sent Toby Harrah to Cleveland in the one-for-one trade.",
      "Bell and Harrah were both established infielders with similar offensive reputations at the time.",
      "Buddy Bell won five consecutive Gold Glove Awards from 1979 through 1983.",
      "Bell was selected to three consecutive All-Star teams from 1980 through 1982.",
      "Buddy Bell appeared in 156 games during the 1983 season.",
      "Bell batted .277 with 171 hits in 1983.",
      "Buddy Bell recorded 35 doubles, three triples and 14 home runs.",
      "Bell drove in 66 runs and scored 75 times.",
      "Buddy Bell drew 50 walks while striking out only 48 times.",
      "Bell received another Gold Glove for his defensive performance in 1983.",
      "Buddy Bell combines quick reactions with an exceptionally accurate throwing arm at third base.",
      "Bell's ability to move the baseball around the field makes him difficult to defend with a fixed alignment.",
      "Buddy Bell is one of the most dependable two-way third basemen in the American League entering 1984.",
    ],
  },
  "George Wright": {
    lines: [
      "George Wright's full name is George DeWitt Wright.",
      "Wright was born in Oklahoma City, Oklahoma.",
      "Texas selected George Wright in the fourth round of the 1977 amateur draft.",
      "Wright was drafted out of Capitol Hill High School in Oklahoma City.",
      "George Wright bats and throws right-handed.",
      "Wright developed as an outfielder, not a shortstop.",
      "George Wright's primary defensive position is center field.",
      "Wright reached the major leagues with Texas during the 1982 season.",
      "George Wright established himself as an everyday player during the 1983 season.",
      "Wright appeared in all 162 of Texas' games in 1983.",
      "George Wright collected a team-leading 175 hits.",
      "Wright batted .276 with a .321 on-base percentage.",
      "George Wright recorded 28 doubles and six triples.",
      "Wright hit 18 home runs and drove in 80 runs.",
      "George Wright scored 79 times and stole eight bases.",
      "Wright started 160 games in center field during the 1983 season.",
      "George Wright recorded seven outfield assists.",
      "Wright's mixture of speed and power made him one of the Rangers' most productive young players.",
      "George Wright enters 1984 after completing an unusually durable first full major-league season.",
    ],
  },
  "Pete O'Brien": {
    lines: [
      "Pete O'Brien's full name is Peter William O'Brien.",
      "O'Brien is a left-handed hitter and thrower.",
      "Pete O'Brien played college baseball at the University of Nebraska.",
      "Texas selected O'Brien in the 15th round of the 1979 amateur draft.",
      "Pete O'Brien developed primarily as a first baseman.",
      "O'Brien made his major-league debut on September 3, 1982.",
      "Pete O'Brien received only a brief major-league trial during the 1982 season.",
      "O'Brien became Texas' regular first baseman as a rookie in 1983.",
      "Pete O'Brien appeared in 154 games.",
      "O'Brien collected 124 hits in 524 official at-bats.",
      "Pete O'Brien batted .237 with a .313 on-base percentage.",
      "O'Brien recorded 24 doubles and five triples.",
      "Pete O'Brien hit eight home runs and drove in 53 runs.",
      "O'Brien scored 53 times during the 1983 season.",
      "Pete O'Brien drew 58 walks while striking out 62 times.",
      "O'Brien stole five bases and was caught four times.",
      "Pete O'Brien is regarded as a fundamentally sound defensive first baseman.",
      "O'Brien's willingness to take a walk gives him value even when his batting average is low.",
      "Pete O'Brien enters 1984 with one complete major-league season behind him.",
    ],
  },
  "Larry Parrish": {
    lines: [
      "Larry Parrish's full name is Larry Alton Parrish.",
      "Parrish was born in Winter Haven, Florida.",
      "Larry Parrish began his professional career in the Montreal organization.",
      "Parrish made his major-league debut with the Expos during the 1974 season.",
      "Larry Parrish developed into a power-hitting third baseman in Montreal.",
      "Parrish could also play either corner-outfield position.",
      "Larry Parrish hit 30 home runs during the 1979 season.",
      "Parrish was selected to the National League All-Star team that year.",
      "Larry Parrish joined Texas shortly before the 1982 season.",
      "The Rangers acquired Parrish and Dave Hostetler from Montreal for Al Oliver.",
      "Parrish supplied Texas with a proven right-handed power hitter.",
      "Larry Parrish appeared in 145 games during the 1983 season.",
      "Parrish batted .272 with 151 hits.",
      "Larry Parrish collected 26 doubles and four triples.",
      "Parrish led Texas with 26 home runs.",
      "Larry Parrish also led the Rangers with 88 RBI.",
      "Parrish scored 76 runs and drew 46 walks.",
      "Larry Parrish slugged .474 during the 1983 season.",
      "Parrish can play third base, the outfield or serve as the designated hitter.",
      "Larry Parrish's ability to drive a mistake over the fence makes him dangerous in any count.",
      "Parrish enters 1984 as Texas' most established home-run threat.",
    ],
  },
  "Billy Sample": {
    lines: [
      "Billy Sample's full name is William Amos Sample.",
      "Sample was born in Roanoke, Virginia.",
      "Billy Sample grew up in nearby Salem, Virginia.",
      "Sample was a standout in football, basketball and baseball during high school.",
      "Billy Sample played college baseball at James Madison University.",
      "Texas first selected Sample in the 28th round of the 1973 amateur draft.",
      "Sample did not sign at that time.",
      "Texas selected Billy Sample again in the 10th round of the 1976 draft.",
      "Sample made his major-league debut with the Rangers during the 1978 season.",
      "Billy Sample can play all three outfield positions.",
      "Sample enjoyed the most productive season of his career in 1983.",
      "Billy Sample appeared in 147 games.",
      "Sample batted .274 with 152 hits.",
      "Billy Sample recorded 28 doubles, three triples and 12 home runs.",
      "Sample drove in 57 runs and scored 80 times.",
      "Billy Sample stole 44 bases while being caught only eight times.",
      "Sample's 44 stolen bases ranked fifth in the American League.",
      "Billy Sample drew 44 walks and struck out only 46 times.",
      "Sample recorded a .331 on-base percentage and a .401 slugging percentage.",
      "Billy Sample combines speed with enough power to prevent the outfield from playing shallow.",
      "Sample's ability to play several positions makes him useful in numerous lineup combinations.",
    ],
  },
  "Gary Ward": {
    lines: [
      "Gary Ward's full name is Gary Lamell Ward.",
      "Ward is a right-handed hitter and thrower.",
      "Gary Ward began his major-league career with the Minnesota Twins.",
      "Ward developed into Minnesota's regular left fielder.",
      "Gary Ward hit for the cycle against Milwaukee on September 18, 1980.",
      "Ward established himself as a combination of batting-average ability and right-handed power.",
      "Gary Ward appeared in 157 games during the 1983 season.",
      "Ward represented Minnesota in the 1983 American League All-Star Game.",
      "Gary Ward batted .278 with 173 hits.",
      "Ward recorded 34 doubles and five triples.",
      "Gary Ward hit 19 home runs and drove in 88 runs.",
      "Ward scored 76 times during the season.",
      "Gary Ward stole eight bases.",
      "Ward recorded a .326 on-base percentage and a .440 slugging percentage.",
      "Gary Ward was Minnesota's only All-Star representative in 1983.",
      "Texas acquired Ward from Minnesota during the offseason.",
      "The Rangers sent pitchers Mike Smithson and John Butcher to the Twins.",
      "Ward gives Texas another proven run producer for the middle of the lineup.",
      "Gary Ward can play either corner-outfield position or serve as the designated hitter.",
    ],
  },
  "Toby Harrah": {
    lines: [
      "Toby Harrah's full name is Colbert Dale Harrah.",
      "Harrah was born in Sissonville, West Virginia.",
      "Toby Harrah began his major-league career with the Washington Senators.",
      "Harrah remained with the franchise when it moved to Texas in 1972.",
      "Toby Harrah became the first Rangers player selected to an All-Star team.",
      "Harrah played shortstop during the early part of his Texas career.",
      "Toby Harrah later moved to third base.",
      "Harrah was selected to the All-Star team in 1972, 1975 and 1976 as a Ranger.",
      "Toby Harrah hit 20 home runs and stole 20 bases during the 1975 season.",
      "Harrah hit a career-high 27 home runs in 1977.",
      "Toby Harrah led the American League with 109 walks that season.",
      "Harrah and teammate Bump Wills hit consecutive inside-the-park home runs in 1977.",
      "Toby Harrah once reached base in 41 consecutive games, establishing a Rangers club record.",
      "Texas traded Harrah to Cleveland for Buddy Bell after the 1978 season.",
      "Toby Harrah was selected to another All-Star team with Cleveland in 1982.",
      "Harrah appeared in 138 games for Cleveland during the 1983 season.",
      "Toby Harrah batted .266 with 140 hits.",
      "Harrah recorded 23 doubles, nine home runs and 53 RBI.",
      "Toby Harrah scored 81 runs and stole 16 bases.",
      "Harrah drew 75 walks and posted a .363 on-base percentage.",
      "Toby Harrah can play shortstop, third base and second base.",
      "His plate discipline makes him valuable even when he is not hitting for power.",
    ],
  },
  "Ned Yost": {
    lines: [
      "Ned Yost's full name is Edgar Frederick Yost III.",
      "Yost is a right-handed catcher.",
      "Ned Yost reached the major leagues with Milwaukee during the 1980 season.",
      "Yost served primarily as a reserve behind Ted Simmons and Charlie Moore.",
      "Ned Yost was part of Milwaukee's postseason club in 1981.",
      "Yost remained with the Brewers during their 1982 pennant-winning season.",
      "Ned Yost appeared in the 1982 World Series against St. Louis.",
      "Yost appeared in 61 games for Milwaukee during the 1983 season.",
      "Ned Yost collected 44 hits in 196 official at-bats.",
      "Yost batted .224 with five doubles and one triple.",
      "Ned Yost hit six home runs and drove in 28 runs.",
      "Yost scored 21 times during the season.",
      "Ned Yost possesses considerably more power than speed.",
      "Milwaukee traded Yost and minor-leaguer Dan Scarpetta to Texas on December 8, 1983.",
      "The Brewers received longtime Rangers catcher Jim Sundberg.",
      "Yost gives Texas a catcher with recent postseason experience.",
      "Ned Yost is accustomed to preparing for games despite irregular playing time.",
      "Yost can also make an occasional appearance at another corner position when necessary.",
    ],
  },
  "Curtis Wilkerson": {
    lines: [
      "Curtis Wilkerson is a switch-hitting middle infielder.",
      "Wilkerson developed within the Rangers organization.",
      "Curtis Wilkerson can play both shortstop and second base.",
      "Wilkerson appeared in 115 games during the 1983 season.",
      "Curtis Wilkerson collected 95 hits in 402 at-bats.",
      "Wilkerson batted .236 with a .299 on-base percentage.",
      "Curtis Wilkerson recorded 15 doubles and three triples.",
      "Wilkerson hit one home run and drove in 30 runs.",
      "Curtis Wilkerson scored 48 times and stole 10 bases.",
      "Wilkerson drew 38 walks while striking out 43 times.",
      "Curtis Wilkerson's defensive versatility makes him valuable in late-game situations.",
      "Wilkerson can enter as a defensive replacement without disrupting the batting order.",
    ],
  },
  "Dave Hostetler": {
    lines: [
      "Dave Hostetler's full name is David Alan Hostetler.",
      "Hostetler is commonly known by the nickname \"Hoss.\"",
      "Dave Hostetler stands approximately 6-foot-4.",
      "Hostetler played college baseball at the University of Southern California.",
      "Dave Hostetler was selected five times during various phases of the amateur draft.",
      "Montreal finally signed Hostetler after selecting him in the fourth round in 1978.",
      "Dave Hostetler reached the major leagues with the Expos during the 1981 season.",
      "Texas acquired Hostetler and Larry Parrish from Montreal before the 1982 season.",
      "Hostetler immediately became a major source of excitement in Arlington.",
      "\"Hoss-steria\" swept the Rangers during Hostetler's powerful start in 1982.",
      "Dave Hostetler hit 10 home runs during June 1982.",
      "Hostetler led Texas with 22 home runs that season.",
      "Dave Hostetler drove in 67 runs in 1982.",
      "Hostetler appeared in 94 games during the 1983 season.",
      "Dave Hostetler batted .220 with a .323 on-base percentage.",
      "Hostetler hit 11 home runs and drove in 46 runs.",
      "Dave Hostetler drew 42 walks but struck out 103 times.",
      "Hostetler can play first base or serve as the designated hitter.",
      "His approach produces both long home runs and high strikeout totals.",
      "Hoss remains capable of changing a game with one mistake from a pitcher.",
    ],
  },
  "Donnie Scott": {
    lines: [
      "Donnie Scott is a switch-hitting catcher.",
      "Scott developed within the Texas Rangers organization.",
      "Donnie Scott made his major-league debut during the 1983 season.",
      "Scott appeared in 75 games for Texas as a rookie.",
      "Donnie Scott collected 42 hits in 183 at-bats.",
      "Scott batted .229 with four home runs and 18 RBI.",
      "Donnie Scott recorded 10 doubles during his rookie season.",
      "Scott drew 17 walks and posted a .295 on-base percentage.",
      "Donnie Scott is valued for his defensive work behind the plate.",
      "Scott gives Texas a young catcher who can share duties with Ned Yost.",
      "Donnie Scott's throwing arm has shown improvement as he gains experience.",
      "Scott is still learning the tendencies of American League baserunners.",
    ],
  },
  "Mickey Rivers": {
    lines: [
      "Mickey Rivers is commonly known by the nickname \"Mick the Quick.\"",
      "Rivers was born in Miami, Florida.",
      "Mickey Rivers is one of the fastest players of his era.",
      "Rivers began his major-league career with the California Angels.",
      "Mickey Rivers was traded to the New York Yankees during the 1975 season.",
      "Rivers helped the Yankees win consecutive World Series in 1977 and 1978.",
      "Mickey Rivers led the American League in stolen bases in 1974.",
      "Rivers stole 70 or more bases in three separate seasons.",
      "Mickey Rivers joined Texas before the 1980 season.",
      "Rivers appeared in 108 games during the 1983 season.",
      "Mickey Rivers batted .279 with 51 hits in 184 at-bats.",
      "Rivers stole 15 bases and scored 30 runs.",
      "Mickey Rivers serves as a designated hitter and occasional outfielder entering 1984.",
      "Even in a reduced role, Rivers remains a capable pinch-runner and contact hitter.",
      "Mick the Quick's smile and personality make him a favorite in the Texas clubhouse.",
    ],
  },
  "Wayne Tolleson": {
    lines: [
      "Wayne Tolleson is a switch-hitting second baseman.",
      "Tolleson attended Dillon High School in South Carolina.",
      "Wayne Tolleson played college baseball at Clemson University.",
      "Tolleson can play second base, shortstop and third base.",
      "Wayne Tolleson appeared in 102 games during the 1983 season.",
      "Tolleson collected 64 hits in 306 at-bats.",
      "Wayne Tolleson batted .213 with one home run and 23 RBI.",
      "Tolleson recorded 13 doubles and scored 36 runs.",
      "Wayne Tolleson stole 12 bases during the 1983 season.",
      "Tolleson's defensive versatility makes him a useful utility player.",
      "Wayne Tolleson can enter late in a game to improve the infield defense.",
    ],
  },
  "Charlie Hough": {
    lines: [
      "Charlie Hough's full name is Charles Oliver Hough.",
      "Hough was born in Hilo, Hawaii.",
      "Charlie Hough is a right-handed knuckleball pitcher.",
      "Hough began his professional career in the Los Angeles Dodgers organization.",
      "Charlie Hough made his major-league debut during the 1970 season.",
      "Hough spent most of his Dodgers career working from the bullpen.",
      "Charlie Hough learned the knuckleball while trying to revive a stalled minor-league career.",
      "The unpredictable pitch eventually became his primary weapon.",
      "Texas purchased Hough's contract from Los Angeles during the 1980 season.",
      "The Rangers gradually converted Hough from reliever into a starting pitcher.",
      "Charlie Hough did not become a full-time major-league starter until his thirties.",
      "Hough's knuckleball allows him to work frequently without the same strain created by repeated maximum-effort fastballs.",
      "Charlie Hough appeared in 34 games during the 1983 season.",
      "Hough made 33 starts.",
      "Charlie Hough went 15-13 with a 3.18 ERA.",
      "Hough led Texas with 15 victories.",
      "Charlie Hough threw 252 innings.",
      "Hough completed 11 games and recorded three shutouts.",
      "Charlie Hough struck out 152 hitters.",
      "Hough allowed only 219 hits despite his unpredictable pitch.",
      "Charlie Hough led the Rangers in innings, victories, complete games and strikeouts.",
      "Catchers must wait as long as possible before attempting to receive Hough's knuckleball.",
      "Passed balls and wild pitches can occur even when Hough throws exactly the pitch he intended.",
      "Facing Hough can disrupt a hitter's timing for the remainder of a series.",
    ],
  },
  "Frank Tanana": {
    lines: [
      "Frank Tanana's full name is Frank Daryl Tanana.",
      "Tanana was born in Detroit, Michigan.",
      "Frank Tanana is a left-handed pitcher.",
      "California selected Tanana in the second round of the 1971 amateur draft.",
      "Frank Tanana reached the major leagues with the Angels during the 1973 season.",
      "Tanana and teammate Nolan Ryan formed one of baseball's most feared left-right combinations.",
      "Frank Tanana led the American League with 269 strikeouts in 1975.",
      "Tanana won 19 games in both 1974 and 1975.",
      "Frank Tanana was selected to three consecutive All-Star teams from 1975 through 1977.",
      "Tanana later developed arm problems that altered his pitching style.",
      "Frank Tanana traded his blazing fastball for command, off-speed pitches and deception.",
      "Tanana joined Boston during the 1981 season.",
      "Frank Tanana later signed with Texas as a free agent before the 1983 season.",
      "Tanana appeared in 33 games for the Rangers during the 1983 season.",
      "Frank Tanana made 32 starts and threw 201 innings.",
      "Tanana went 10-12 with a 4.01 ERA.",
      "Frank Tanana struck out 103 hitters while walking 88.",
      "Tanana completed four games during the 1983 season.",
      "Frank Tanana's curveball and changeup remain effective even without his former velocity.",
      "Tanana gives Texas an experienced left-handed starter behind Charlie Hough.",
    ],
  },
  "Danny Darwin": {
    lines: [
      "Danny Darwin's full name is Danny Wayne Darwin.",
      "Darwin was born in Bonham, Texas.",
      "Danny Darwin is commonly known as the \"Bonham Bullet.\"",
      "Darwin is a right-handed pitcher.",
      "Danny Darwin reached the major leagues with the Texas Rangers.",
      "Darwin has worked both as a starter and reliever.",
      "Danny Darwin eventually became a valuable multi-role pitcher for Texas.",
      "Darwin enjoyed an outstanding relief season in 1980.",
      "Danny Darwin went 13-4 with a 2.63 ERA in 1980.",
      "Darwin also recorded eight saves that season.",
      "Danny Darwin later moved into the starting rotation.",
      "Darwin appeared in 28 games during the 1983 season.",
      "Danny Darwin made 26 starts.",
      "Darwin went 8-13 with a 3.49 ERA.",
      "Danny Darwin threw 183 innings.",
      "Darwin completed nine games and recorded two shutouts.",
      "Danny Darwin allowed only nine home runs in 183 innings.",
      "Darwin struck out 92 hitters while walking 62.",
      "His starting and relief experience allows him to adapt to almost any pitching assignment.",
      "The Bonham Bullet's nickname reflects both his Texas roots and the fastball that first carried him to the majors.",
    ],
  },
  "Mike Mason": {
    lines: [
      "Mike Mason is a left-handed pitcher.",
      "Mike Mason was born in Omaha, Nebraska.",
      "Mason made his major-league debut with Texas during the 1983 season.",
      "Mike Mason appeared in 25 games as a rookie.",
      "Mason made 21 starts during the 1983 season.",
      "Mike Mason went 6-7 with a 4.56 ERA.",
      "Mason threw 108 and a third innings.",
      "Mike Mason struck out 54 hitters while walking 48.",
      "Mason completed one game during his rookie season.",
      "Mike Mason enters 1984 as a young left-hander attempting to establish himself in the rotation.",
      "Mason's curveball is his best pitch, and it improves when he gets ahead in the count.",
    ],
  },
  "Dave Schmidt": {
    lines: [
      "Dave Schmidt is a right-handed pitcher.",
      "Texas selected Schmidt in the 26th round of the 1979 amateur draft.",
      "Dave Schmidt made his major-league debut on May 1, 1981.",
      "Schmidt worked primarily from the bullpen during his early seasons.",
      "Dave Schmidt appeared in 14 games during the 1981 season.",
      "Schmidt posted a 3.13 ERA in 31 and two-thirds innings.",
      "Dave Schmidt can remain in a game for multiple innings.",
      "Schmidt appeared in 31 games during the 1983 season.",
      "Dave Schmidt worked exclusively in relief.",
      "Schmidt went 3-3 with a 3.88 ERA.",
      "Dave Schmidt threw 46 and a third innings.",
      "Schmidt allowed 42 hits.",
      "Dave Schmidt struck out 29 hitters while walking only 14.",
      "Schmidt recorded two saves.",
      "Dave Schmidt finished 20 games.",
      "Schmidt's control makes him useful when entering with runners already on base.",
      "Dave Schmidt can bridge the gap between an early departing starter and the late-inning relievers.",
    ],
  },
  "Dave Stewart": {
    lines: [
      "Dave Stewart's full name is David Lee Stewart.",
      "Stewart was born in Oakland, California.",
      "Dave Stewart is a right-handed pitcher with an overpowering fastball.",
      "The Los Angeles Dodgers selected Stewart in the 16th round of the 1975 amateur draft.",
      "Dave Stewart reached the major leagues with Los Angeles during the 1978 season.",
      "Stewart worked primarily from the bullpen during his Dodgers career.",
      "Dave Stewart appeared in 45 games for Los Angeles during the 1981 season.",
      "Stewart recorded eight saves and posted a 2.49 ERA that year.",
      "Texas acquired Dave Stewart from the Dodgers on August 19, 1983.",
      "The Rangers received Stewart in the trade that sent Rick Honeycutt to Los Angeles.",
      "Dave Stewart appeared in 11 games for Texas after the 1983 trade.",
      "Stewart posted a 2.84 ERA in 19 innings for the Rangers.",
      "Dave Stewart struck out 17 hitters in those 19 innings.",
      "Stewart's fastball and slider combination can overwhelm hitters when his control is sharp.",
      "Dave Stewart enters 1984 as a hard-throwing right-hander with late-inning potential.",
    ],
  },
  "Odell Jones": {
    lines: [
      "Odell Jones is a right-handed pitcher.",
      "Jones began his professional career in the Pittsburgh Pirates organization.",
      "Odell Jones made his major-league debut with Pittsburgh during the 1982 season.",
      "Jones later joined the Texas Rangers.",
      "Odell Jones appeared in 36 games during the 1983 season.",
      "Jones worked primarily in relief.",
      "Odell Jones posted a 4.45 ERA in 56 and two-thirds innings.",
      "Jones struck out 27 hitters while walking 29.",
      "Odell Jones can work multiple innings from the bullpen.",
      "Jones' pitching background includes both starting and relieving experience.",
      "Odell Jones provides Texas with a durable right-handed arm in the middle innings.",
    ],
  },
  "Dave Tobik": {
    lines: [
      "Dave Tobik is a right-handed pitcher.",
      "Tobik was born in Detroit, Michigan.",
      "Dave Tobik attended Eastern Michigan University.",
      "Tobik reached the major leagues with the Detroit Tigers during the 1978 season.",
      "Dave Tobik later joined the Texas Rangers.",
      "Tobik appeared in 30 games during the 1983 season.",
      "Dave Tobik worked exclusively in relief.",
      "Tobik posted a 3.86 ERA in 49 innings.",
      "Dave Tobik struck out 21 hitters while walking 19.",
      "Tobik finished 12 games during the 1983 season.",
      "Dave Tobik's sidearm delivery creates a difficult angle for right-handed hitters.",
      "Tobik can be especially effective when used strategically against specific batters.",
    ],
  },
  "Tom Henke": {
    lines: [
      "Tom Henke's full name is Thomas Anthony Henke.",
      "Henke is commonly known by the nickname \"The Terminator.\"",
      "Tom Henke was born in Kansas City, Missouri.",
      "Henke is a right-handed pitcher with exceptional velocity.",
      "Texas selected Tom Henke in the fourth round of the 1980 amateur draft.",
      "Henke made his major-league debut during the 1982 season.",
      "Tom Henke appeared in 36 games during the 1983 season.",
      "Henke recorded 11 saves and posted a 2.69 ERA.",
      "Tom Henke struck out 60 hitters in only 47 innings.",
      "Henke allowed only 30 hits during those 47 innings.",
      "Tom Henke's strikeout rate demonstrates his overpowering arsenal.",
      "The Terminator's fastball and forkball combination can devastate opposing hitters.",
      "Tom Henke enters 1984 as one of the most exciting young relief pitchers in the American League.",
      "When Henke is available, the Rangers have a genuine late-inning weapon.",
    ],
  },
  "Cecilio Guante": {
    lines: [
      "Cecilio Guante's full name is Cecilio Guante Magallanes.",
      "Guante was born in Villa Mella in the Dominican Republic.",
      "Cecilio Guante is a right-handed pitcher.",
      "Pittsburgh signed Guante as an amateur free agent.",
      "Guante reached the major leagues with the Pirates during the 1982 season.",
      "Cecilio Guante worked primarily in relief.",
      "Guante appeared in 49 games during the 1983 season.",
      "Cecilio Guante went 2-6 with a 3.32 ERA.",
      "Guante recorded nine saves.",
      "Cecilio Guante worked 100 and a third innings without making a start.",
      "Guante allowed 90 hits in those innings.",
      "Cecilio Guante struck out 82 hitters while walking 46.",
      "Guante surrendered only five home runs.",
      "Cecilio Guante could remain in a game for several innings rather than working as a one-inning specialist.",
      "Guante's durable arm makes him valuable during stretches of consecutive games.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive - base hit.\"",
    "\"Long drive to left field - way back - gone. Home run!\"",
    "\"Ground ball to short - over to first - in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub has some real talent - Buddy Bell, Larry Parrish, Charlie Hough - the Rangers can play.\"",
    "\"Texas baseball is alive and well - the fans here at Arlington Stadium love their Rangers.\"",
    "\"This team has power and experience - Gary Ward and Larry Parrish give Texas a dangerous middle of the order.\"",
    "\"Arlington Stadium is home - and the Rangers are ready to make some noise in the AL West.\"",
    "\"Buddy Bell has won five straight Gold Gloves - he's the best third baseman in baseball.\"",
    "\"There's talent everywhere you look in this lineup - the Rangers can hurt you.\"",
    "\"This club is building something - the Rangers believe they can contend in the West.\"",
    "\"Texas has one of the most productive lineups in the American League.\"",
    "\"The fans in Arlington have been waiting for a winner - they're fired up about this club.\"",
    "\"There's a buzz around the Rangers this year - people can feel something building.\"",
    "\"This is a team with power, speed and a knuckleballer - that's a dangerous combination.\"",
    "\"Arlington Stadium - there's nothing quite like a night under the lights in Texas.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Buddy Bell is one of the greatest defensive third basemen in baseball history - five straight Gold Gloves.\"",
    "\"Charlie Hough and that knuckleball - there's nothing quite like it in the American League.\"",
    "\"Larry Parrish can hit the ball out of any part of this ballpark - he's the Rangers' home-run leader.\"",
    "\"Gary Ward was an All-Star last year - he gives Texas a proven run producer.\"",
    "\"George Wright played in all 162 games last year - that's durability you can't teach.\"",
    "\"Billy Sample stole 44 bases last year - he's a threat every time he reaches base.\"",
    "\"Tom Henke - The Terminator - has one of the best fastballs in the American League.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Arlington Stadium.\"",
    "\"The lights are on at the old ballpark - Rangers baseball tonight.\"",
    "Arlington Stadium - home of the Rangers since 1972.",
    "\"The warm Texas air is perfect for baseball tonight.\"",
    "\"The artificial turf plays fast tonight - ground balls will scoot through the infield.\"",
    "\"The stands are filling up nicely - the fans in Arlington are excited about this club.\"",
    "\"You can feel the Texas heat radiating off the turf - it's a warm one tonight.\"",
    "\"The old ballpark has character - you can feel it the moment you walk through the gates.\"",
    "\"The faithful at Arlington Stadium are some of the most passionate fans in baseball.\"",
    "\"A crisp evening in Texas - there's nothing better than baseball at Arlington Stadium.\"",
    "\"The Dallas-Fort Worth metroplex is buzzing tonight - the fans here love their Rangers.\"",
    "\"The Texas flag is flying high above the outfield wall - God bless Texas.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here at Arlington Stadium is into this ballgame.\"",
    "\"Rangers fans are making some noise tonight.\"",
    "\"The fans in Texas have been waiting for a winner - they're fired up tonight.\"",
    "\"Arlington Stadium is rocking tonight.\"",
    "\"Texas fans are among the most passionate in baseball - they show up in this heat every night.\"",
    "\"The crowd is on its feet - they can feel something building here.\"",
    "\"A great turnout at Arlington Stadium tonight.\"",
    "\"These fans love their Rangers - through the heat and everything else.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Arlington Stadium, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball on a Texas evening.\"",
    "\"From all of us in the Dallas-Fort Worth area, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story - that's the beauty of this sport.\"",
    "\"Baseball in Texas - it's a way of life down here.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone - into the Arlington night!\"",
    "\"Howdy, baseball fans - what a ballgame!\"",
    "\"The Rangers are making their move here at Arlington Stadium.\"",
    "\"That one is long gone - everything's bigger in Texas!\"",
    "\"You won't see many better than that one.\"",
    "\"And Texas goes crazy - what a finish!\"",
  ]},
};