// Things That Scream 1984 Interactive Museum Exhibits (876-900)
// 25 entries celebrating the iconic things that defined 1984

const ENTRIES = [
  {
    id: 'sony_walkman',
    exhibit: 'Sony Walkman',
    icon: '🎧',
    matchText: 'The Sony Walkman changed music from something people played in a room into something they carried through life.',
    tagline: 'Music on the Move',
    year: '1979 (iconic 1984)',
    description: 'Introduced in 1979, the Sony Walkman changed music from something people played in a room into something they carried through life. By 1984, joggers, students, commuters, and travelers seemed to have headphones everywhere. A favorite cassette could move from the home stereo to the car and then straight into a Walkman. The machine did not record, provide booming speakers, or do anything except play tapes—but that personal simplicity was precisely what made it revolutionary.',
    producer: 'Sony',
    introduced: '1979',
    function: 'Portable cassette playback',
    impact: 'Made music personal and portable',
    iconic: true,
    category: 'technology',
    funFact: 'The Walkman was originally called the "Soundabout" in the US before Sony standardized the name.',
  },
  {
    id: 'rubiks_cube',
    exhibit: 'Rubik\'s Cube',
    icon: '🧊',
    matchText: 'Hungarian professor Ernő Rubik invented his twisting puzzle in 1974, and it reached American stores as the Rubik\'s Cube in 1980.',
    tagline: 'The Puzzle Everyone Owned',
    year: '1980 (peak 1984)',
    description: 'Hungarian professor Ernő Rubik invented his twisting puzzle in 1974, and it reached American stores as the Rubik\'s Cube in 1980. Within two years, consumers had purchased roughly 100 million of them. By 1984, partially scrambled cubes rested on desks, coffee tables, and bedroom shelves everywhere. Owners commonly peeled off the colored stickers, took the cube apart, or quietly claimed they had once solved it. Very few witnesses were ever available to confirm those claims.',
    inventor: 'Ernő Rubik',
    sold: '~100 million by 1982',
    behavior: 'Peeling stickers, disassembling, false claims',
    iconic: true,
    category: 'culture',
    funFact: 'Many cube owners secretly peeled off stickers to "solve" the puzzle rather than learning the algorithm.',
  },
  {
    id: 'cabbage_patch_kids',
    exhibit: 'Cabbage Patch Kids',
    icon: '🥬',
    matchText: 'The great Cabbage Patch Kids panic began during the 1983 Christmas season and remained a national obsession in 1984.',
    tagline: 'Adopt, Don\'t Buy',
    year: '1983-1984',
    description: 'The great Cabbage Patch Kids panic began during the 1983 Christmas season and remained a national obsession in 1984. Each doll came with a name, birth certificate, and adoption papers, making children feel as though they were welcoming a family member rather than buying a toy. Demand became so intense that shoppers waited for hours, pushed through stores, and occasionally fought over new shipments. Parents who successfully found one were treated like victorious hunters returning from the wilderness.',
    feature: 'Adoption papers and birth certificate',
    demand: 'Riots in toy aisles',
    perception: 'Parents treated as heroes',
    iconic: true,
    category: 'culture',
    funFact: 'Cabbage Patch Kids sparked actual physical fights among parents in toy stores during the 1983 holiday season.',
  },
  {
    id: 'mtv',
    exhibit: 'MTV',
    icon: '📺',
    matchText: 'MTV began broadcasting on August 1, 1981, opening with the Buggles\' "Video Killed the Radio Star."',
    tagline: 'I Want My MTV',
    year: '1981 (cultural peak 1984)',
    description: 'MTV began broadcasting on August 1, 1981, opening with the Buggles\' "Video Killed the Radio Star." By 1984, the channel was reshaping music, fashion, advertising, and teenage culture. A performer could no longer rely only on a good record; appearance, choreography, personality, and video concepts suddenly mattered. Michael Jackson, Madonna, Prince, Cyndi Lauper, Duran Duran, and countless others became visual personalities as well as recording artists. Teenagers watched for hours while insisting they were waiting for one particular video.',
    launched: 'August 1, 1981',
    first_video: '"Video Killed the Radio Star" by the Buggles',
    impact: 'Reshaped music, fashion, and culture',
    iconic: true,
    category: 'media',
    funFact: 'MTV\'s first hour featured only a handful of videos, many by obscure artists.',
  },
  {
    id: 'apple_macintosh',
    exhibit: 'Apple Macintosh',
    icon: '🖥️',
    matchText: 'Apple introduced the Macintosh on January 24, 1984, two days after its famous Super Bowl commercial challenged the gray, controlled world of George Orwell\'s 1984.',
    tagline: 'Think Different',
    year: '1984',
    description: 'Apple introduced the Macintosh on January 24, 1984, two days after its famous Super Bowl commercial challenged the gray, controlled world of George Orwell\'s 1984. The original Macintosh cost $2,495 and included 128 kilobytes of memory, a nine-inch black-and-white screen, a 3.5-inch floppy drive, and something many home users had never touched: a mouse. Its windows, icons, menus, and pointer helped make operating a computer feel visual rather than purely technical.',
    price: '$2,495',
    memory: '128 KB',
    features: ['9-inch B&W screen', '3.5-inch floppy', 'Mouse', 'GUI'],
    iconic: true,
    category: 'technology',
    funFact: 'The Macintosh launch ad was directed by Ridley Scott and aired only once nationally.',
  },
  {
    id: 'pac_man',
    exhibit: 'Pac-Man',
    icon: '🟡',
    matchText: 'Pac-Man first entered arcades in 1980, but its influence was still everywhere in 1984.',
    tagline: 'Waka Waka Waka',
    year: '1980 (ubiquitous 1984)',
    description: 'Pac-Man first entered arcades in 1980, but its influence was still everywhere in 1984. The yellow maze-runner appeared on lunch boxes, clothing, board games, cartoons, records, and nearly every home-video system capable of displaying something vaguely circular. Pac-Man broadened arcade gaming beyond spaceships and military combat, giving players recognizable characters with names and personalities. Blinky, Pinky, Inky, and Clyde became famous despite spending nearly all their time chasing a hungry yellow circle through the same blue maze.',
    ghosts: ['Blinky', 'Pinky', 'Inky', 'Clyde'],
    merchandise: 'Lunch boxes, clothing, cartoons, records',
    significance: 'Broadened gaming beyond spaceships',
    iconic: true,
    category: 'culture',
    funFact: 'Pac-Man was originally called "Puck-Man" before the name was changed for obvious reasons.',
  },
  {
    id: 'trivial_pursuit',
    exhibit: 'Trivial Pursuit',
    icon: '🎯',
    matchText: 'Trivial Pursuit turned living rooms into competitive examinations.',
    tagline: 'Do You Know the Answer?',
    year: '1984',
    description: 'Trivial Pursuit turned living rooms into competitive examinations. Players moved around a circular board collecting colored wedges by answering questions about geography, entertainment, history, literature, science, sports, and leisure. The game became so popular that reports credited it with selling roughly 22 million sets during 1984 alone. Dinner guests who thought they were arriving for a pleasant evening could suddenly find themselves publicly unable to remember the capital of Uruguay or the name of a supporting actor from a 1957 western.',
    sold: '~22 million sets in 1984',
    categories: ['Geography', 'Entertainment', 'History', 'Literature', 'Science', 'Sports', 'Leisure'],
    dynamic: 'Competitive trivia pressure',
    iconic: true,
    category: 'culture',
    funFact: 'Trivial Pursuit was created by two Canadian journalists who couldn\'t find missing Scrabble pieces.',
  },
  {
    id: 'miami_vice',
    exhibit: 'Miami Vice',
    icon: '🌴',
    matchText: 'Miami Vice premiered on NBC in September 1984 and immediately made an ordinary police drama look old-fashioned.',
    tagline: 'Pastel Suits, No Socks',
    year: '1984',
    description: 'Miami Vice premiered on NBC in September 1984 and immediately made an ordinary police drama look old-fashioned. Detectives Sonny Crockett and Ricardo Tubbs pursued drug smugglers through a world of speedboats, sports cars, nightclubs, pastel jackets, designer stubble, and expensive popular music. The series often looked and sounded more like a feature-length music video than weekly television. Don Johnson and Philip Michael Thomas became fashion icons, while viewers debated whether wearing a suit without socks could possibly work outside Florida.',
    network: 'NBC',
    premiered: 'September 1984',
    style: 'Pastel jackets, no socks, designer stubble',
    stars: ['Don Johnson', 'Philip Michael Thomas'],
    iconic: true,
    category: 'media',
    funFact: 'Miami Vice\'s fashion influence was so strong that men\'s sock sales reportedly declined.',
  },
  {
    id: 'breakdancing',
    exhibit: 'Breakdancing',
    icon: '🤸',
    matchText: 'Breaking began in New York\'s hip-hop culture before spreading into movies, television programs, music videos, shopping malls, and school talent shows.',
    tagline: 'Cardboard and Boom Boxes',
    year: '1984',
    description: 'Breaking began in New York\'s hip-hop culture before spreading into movies, television programs, music videos, shopping malls, and school talent shows. By 1984, the style had entered mainstream American consciousness. Cardboard became an improvised dance floor, boom boxes supplied the beat, and youngsters attempted windmills, backspins, freezes, and headspins with widely varying results. The movies Breakin\' and Beat Street helped carry the culture nationwide, though emergency rooms probably encountered several dancers whose ambition exceeded their upper-body strength.',
    moves: ['Windmills', 'Backspins', 'Freezes', 'Headspins'],
    movies: ['Breakin\'', 'Beat Street'],
    equipment: 'Cardboard, boom boxes',
    iconic: true,
    category: 'culture',
    funFact: 'Cardboard boxes became the unofficial dance floors of breakdancing culture.',
  },
  {
    id: 'ghostbusters',
    exhibit: 'Ghostbusters',
    icon: '👻',
    matchText: 'Released on June 8, 1984, Ghostbusters combined comedy, supernatural adventure, special effects, New York attitude, and one of the decade\'s most infectious theme songs.',
    tagline: 'Who Ya Gonna Call?',
    year: '1984',
    description: 'Released on June 8, 1984, Ghostbusters combined comedy, supernatural adventure, special effects, New York attitude, and one of the decade\'s most infectious theme songs. Bill Murray, Dan Aykroyd, Harold Ramis, and Ernie Hudson played an unlikely team of paranormal exterminators operating from a converted firehouse. The film earned about $229 million in North America and became the second-highest-grossing movie of 1984. Soon, almost everyone knew whom they were supposed to call—even though no practical telephone number was provided.',
    released: 'June 8, 1984',
    earnings: '~$229 million (North America)',
    cast: ['Bill Murray', 'Dan Aykroyd', 'Harold Ramis', 'Ernie Hudson'],
    iconic: true,
    category: 'media',
    funFact: 'Ghostbusters was the second-highest-grossing movie of 1984, behind only Beverly Hills Cop.',
  },
  {
    id: 'transformers',
    exhibit: 'Transformers',
    icon: '🤖',
    matchText: 'Hasbro introduced the Transformers brand in 1984 with 28 toys adapted from Japanese transforming-robot lines.',
    tagline: 'Robots in Disguise',
    year: '1984',
    description: 'Hasbro introduced the Transformers brand in 1984 with 28 toys adapted from Japanese transforming-robot lines. Marvel Comics helped create a larger story about heroic Autobots and villainous Decepticons fighting an ancient war that had reached Earth. The animated television series turned Optimus Prime, Megatron, Bumblebee, Soundwave, and Starscream into instant characters rather than mere plastic vehicles. Children quickly learned that transforming some figures required patience, instructions, and at least one adult willing to admit the arms were not supposed to bend that way.',
    producer: 'Hasbro',
    count: '28 initial toys',
    factions: ['Autobots (heroes)', 'Decepticons (villains)'],
    characters: ['Optimus Prime', 'Megatron', 'Bumblebee', 'Soundwave', 'Starscream'],
    iconic: true,
    category: 'culture',
    funFact: 'Transformers toys were adapted from several different Japanese toylines and unified under one story.',
  },
  {
    id: 'the_terminator',
    exhibit: 'The Terminator',
    icon: '🦾',
    matchText: 'Released on October 26, 1984, The Terminator sent an unstoppable cyborg from the future into present-day Los Angeles to kill Sarah Connor.',
    tagline: 'I\'ll Be Back',
    year: '1984',
    description: 'Released on October 26, 1984, The Terminator sent an unstoppable cyborg from the future into present-day Los Angeles to kill Sarah Connor. Directed by James Cameron, the relatively modestly budgeted film mixed science fiction, horror, and relentless action. Arnold Schwarzenegger spoke few lines, but "I\'ll be back" became one of cinema\'s most famous promises. The movie also transformed Sarah from an ordinary waitress into the key figure in humanity\'s future battle against the machines—an especially unsettling story for a year filled with enthusiasm about computers.',
    released: 'October 26, 1984',
    director: 'James Cameron',
    star: 'Arnold Schwarzenegger',
    catchphrase: '"I\'ll be back"',
    iconic: true,
    category: 'media',
    funFact: '"I\'ll be back" became one of the most famous movie quotes in cinema history.',
  },
  {
    id: 'purple_rain',
    exhibit: 'Purple Rain',
    icon: '🟣',
    matchText: 'Prince released the Purple Rain album in June 1984, followed by the film in July.',
    tagline: 'Purple Rain, Purple Everything',
    year: '1984',
    description: 'Prince released the Purple Rain album in June 1984, followed by the film in July. Together they transformed him from a successful musician into an international superstar. The album blended rock, funk, pop, R&B, and emotional ballads, while the movie presented a partly fictionalized version of Minneapolis club life. Purple Rain remained atop the album chart for 24 weeks and eventually sold more than 25 million copies worldwide. Purple motorcycles, ruffled shirts, and dramatic guitar solos suddenly seemed completely reasonable.',
    album_released: 'June 1984',
    film_released: 'July 1984',
    chart_topped: '24 weeks at #1',
    sold: '25+ million copies worldwide',
    iconic: true,
    category: 'media',
    funFact: 'Purple Rain spent 24 consecutive weeks at #1 on the Billboard album chart.',
  },
  {
    id: 'born_in_the_usa',
    exhibit: 'Born in the U.S.A.',
    icon: '🇺🇸',
    matchText: 'Bruce Springsteen released Born in the U.S.A. on June 4, 1984.',
    tagline: 'The Boss Goes Global',
    year: '1984',
    description: 'Bruce Springsteen released Born in the U.S.A. on June 4, 1984. Its huge drums, synthesizers, working-class stories, and American-flag cover made Springsteen a global stadium star. The album eventually produced seven Top 10 singles, including "Dancing in the Dark," "Glory Days," and "My Hometown." Although the title track was often treated as a simple patriotic anthem, its verses told the much darker story of a Vietnam veteran returning to hardship and limited opportunity at home.',
    released: 'June 4, 1984',
    singles: '7 Top 10 hits',
    hits: ['Dancing in the Dark', 'Glory Days', 'My Hometown'],
    misconception: 'Title track often misread as simple patriotism',
    iconic: true,
    category: 'media',
    funFact: 'The title track was often mistaken for a patriotic anthem despite its dark Vietnam veteran story.',
  },
  {
    id: 'thriller',
    exhibit: 'Thriller',
    icon: '🧟',
    matchText: 'Michael Jackson released Thriller in late 1982, but the phenomenon reached an extraordinary level during 1983 and 1984.',
    tagline: 'The Best-Selling Album Ever',
    year: '1982 (peak 1983-1984)',
    description: 'Michael Jackson released Thriller in late 1982, but the phenomenon reached an extraordinary level during 1983 and 1984. Seven songs from the album became U.S. Top 10 singles, and its music videos turned album promotion into major television events. In February 1984, Thriller officially surpassed previous contenders to become the world\'s best-selling album. Jackson\'s moonwalk, red leather jacket, white glove, and zombie choreography became instantly recognizable—even among people who claimed they did not listen to pop music.',
    released: 'Late 1982',
    milestone: 'World\'s best-selling album (February 1984)',
    top_singles: '7 U.S. Top 10 singles',
    iconic_looks: ['Moonwalk', 'Red leather jacket', 'White glove', 'Zombie choreography'],
    iconic: true,
    category: 'media',
    funFact: 'Thriller became the best-selling album of all time in February 1984.',
  },
  {
    id: 'la_olympics',
    exhibit: 'Los Angeles Olympics',
    icon: '🏅',
    matchText: 'Nearly 6,800 athletes representing 140 nations competed in the 1984 Los Angeles Summer Olympics.',
    tagline: 'Gold, Glamour, and Corporate Sponsorship',
    year: '1984',
    description: 'Nearly 6,800 athletes representing 140 nations competed in the 1984 Los Angeles Summer Olympics. The Soviet Union and several allies boycotted, but the Games still produced unforgettable American stars such as Mary Lou Retton, Carl Lewis, Greg Louganis, Joan Benoit, Edwin Moses, and Cheryl Miller. Team USA won 83 gold medals and 174 overall. Corporate sponsorship, existing venues, enthusiastic crowds, and massive television audiences helped make the Los Angeles Games an organizational and financial success.',
    athletes: '~6,800',
    nations: '140',
    usa_gold: '83 gold medals',
    usa_total: '174 overall medals',
    stars: ['Mary Lou Retton', 'Carl Lewis', 'Greg Louganis', 'Joan Benoit', 'Edwin Moses', 'Cheryl Miller'],
    iconic: true,
    category: 'milestone',
    funFact: 'The 1984 LA Olympics were the first to be funded primarily by corporate sponsorship.',
  },
  {
    id: 'reagan_landslide',
    exhibit: 'Reagan Landslide',
    icon: '🗳️',
    matchText: 'President Ronald Reagan won reelection on November 6, 1984, defeating former Vice President Walter Mondale in one of the largest electoral victories in American history.',
    tagline: '49 States Red',
    year: '1984',
    description: 'President Ronald Reagan won reelection on November 6, 1984, defeating former Vice President Walter Mondale in one of the largest electoral victories in American history. Reagan carried 49 states and received 525 electoral votes, while Mondale earned 13 by winning Minnesota and the District of Columbia. The result produced a nearly solid red electoral map and became a defining political image of the decade. Whatever Americans thought of Reagan\'s policies, the size of the victory was impossible to overlook.',
    date: 'November 6, 1984',
    reagan_electoral: '525 electoral votes',
    mondale_electoral: '13 electoral votes',
    reagan_states: '49 states',
    mondale_states: 'Minnesota + DC',
    iconic: true,
    category: 'milestone',
    funFact: 'Reagan won 49 of 50 states—the only state he lost was Mondale\'s home state of Minnesota.',
  },
  {
    id: 'wheres_the_beef',
    exhibit: '"Where\'s the Beef?"',
    icon: '🍔',
    matchText: 'In January 1984, Wendy\'s introduced television viewers to Clara Peller, an elderly woman examining an enormous hamburger bun containing a disappointingly small patty.',
    tagline: 'Three Words That Conquered Culture',
    year: '1984',
    description: 'In January 1984, Wendy\'s introduced television viewers to Clara Peller, an elderly woman examining an enormous hamburger bun containing a disappointingly small patty. Her irritated demand—"Where\'s the beef?"—escaped the commercial almost immediately. The phrase appeared in everyday conversation, comedy routines, merchandise, and even the Democratic presidential campaign, where Walter Mondale used it to question Gary Hart\'s policy proposals. Peller became an overnight celebrity, proving that three carefully delivered words could briefly conquer American culture.',
    brand: 'Wendy\'s',
    star: 'Clara Peller',
    phrase: '"Where\'s the beef?"',
    impact: 'Conquered American culture',
    political_use: 'Mondale used it against Gary Hart',
    iconic: true,
    category: 'culture',
    funFact: 'Clara Peller was 81 years old when she became an overnight celebrity from the Wendy\'s ad.',
  },
  {
    id: 'the_cosby_show',
    exhibit: 'The Cosby Show',
    icon: '📺',
    matchText: 'The Cosby Show premiered on NBC in September 1984 and centered on the Huxtables, an affluent Brooklyn family led by physician Cliff and attorney Clair.',
    tagline: 'Thursday Night Institution',
    year: '1984',
    description: 'The Cosby Show premiered on NBC in September 1984 and centered on the Huxtables, an affluent Brooklyn family led by physician Cliff and attorney Clair. Its mix of family comedy, parental authority, music, education, and everyday household problems helped revive the network sitcom. The series quickly became one of television\'s highest-rated programs and influenced an entire generation of family comedies. In 1984, viewers simply saw a polished new Thursday-night hit; the program\'s legacy would become far more complicated many years later.',
    network: 'NBC',
    premiered: 'September 1984',
    family: 'The Huxtables',
    parents: 'Cliff (physician) and Clair (attorney)',
    impact: 'Revived the network sitcom',
    iconic: true,
    category: 'media',
    funFact: 'The Cosby Show was the #1 show in America for five consecutive seasons.',
  },
  {
    id: 'vhs_vs_betamax',
    exhibit: 'VHS vs. Betamax',
    icon: '📼',
    matchText: 'The great home-video format war forced families to choose between two incompatible systems.',
    tagline: 'Choose Your Format',
    year: '1984',
    description: 'The great home-video format war forced families to choose between two incompatible systems. Sony\'s Betamax generally offered strong picture quality, while VHS machines offered longer recording times and were produced by a wider range of manufacturers. By 1984, VHS was pulling ahead in homes and rental stores. Choosing incorrectly could leave a family with a machine that would not play the neighbors\' tapes—or the only available copy of the movie everyone wanted to rent on Friday night.',
    betamax: 'Sony, better picture quality',
    vhs: 'Longer recording, more manufacturers',
    winner: 'VHS by 1984',
    risk: 'Incompatible with neighbors\' tapes',
    iconic: true,
    category: 'technology',
    funFact: 'Betamax had better picture quality, but VHS won by offering longer recording times.',
  },
  {
    id: 'cd_players',
    exhibit: 'CD Players',
    icon: '💿',
    matchText: 'Compact disc players first reached consumers in Japan and Europe in 1982 and the United States in 1983, so the technology was already available by 1984—but still seemed expensive and futuristic.',
    tagline: 'Perfect Sound Forever',
    year: '1982-1984',
    description: 'Compact disc players first reached consumers in Japan and Europe in 1982 and the United States in 1983, so the technology was already available by 1984—but still seemed expensive and futuristic. The major 1984 milestone was Sony\'s D-50, the first portable CD player. CDs promised instant track selection, low background noise, and freedom from tape hiss, although early buyers faced costly machines and a relatively small album selection. Many record collectors confidently predicted the shiny discs would never replace vinyl.',
    introduced: '1982 (Japan/Europe), 1983 (US)',
    milestone: 'Sony D-50 portable CD player (1984)',
    advantages: ['Instant track selection', 'Low noise', 'No tape hiss'],
    drawbacks: ['Expensive machines', 'Small album selection'],
    iconic: true,
    category: 'technology',
    funFact: 'Many record collectors confidently predicted CDs would never replace vinyl.',
  },
  {
    id: 'swatch_watches',
    exhibit: 'Swatch Watches',
    icon: '⌚',
    matchText: 'Founded in 1983, Swatch helped turn an ordinary wristwatch into an affordable fashion accessory.',
    tagline: 'Wear Two at Once',
    year: '1983 (peak 1984)',
    description: 'Founded in 1983, Swatch helped turn an ordinary wristwatch into an affordable fashion accessory. The Swiss-made quartz watches used simplified construction, plastic cases, bright colors, and playful designs. Instead of purchasing one serious watch for decades, buyers could own several and match them to different outfits or moods. By 1984, the styles were becoming bolder and unmistakably \'80s. Wearing two Swatches at once was unnecessary, impractical, and therefore entirely possible.',
    founded: '1983',
    origin: 'Switzerland',
    features: ['Plastic cases', 'Bright colors', 'Playful designs', 'Affordable'],
    trend: 'Wearing multiple watches',
    iconic: true,
    category: 'culture',
    funFact: 'Wearing two Swatches at once became an unnecessary but popular 1980s fashion statement.',
  },
  {
    id: 'members_only_jackets',
    exhibit: 'Members Only Jackets',
    icon: '🧥',
    matchText: 'The Members Only racer jacket debuted in 1980 and became one of the defining pieces of early-1980s men\'s fashion.',
    tagline: 'Membership Has Its Privileges',
    year: '1980 (iconic 1984)',
    description: 'The Members Only racer jacket debuted in 1980 and became one of the defining pieces of early-1980s men\'s fashion. Its narrow collar strap, ribbed waistband, shoulder epaulets, and small chest logo made the wearer appear ready for either a casual office meeting or a minor undercover assignment. The original jacket sold for about $55 and became a major commercial success. Despite the exclusive-sounding name, membership required nothing more complicated than finding the correct size and paying the cashier.',
    debuted: '1980',
    price: '~$55',
    features: ['Narrow collar strap', 'Ribbed waistband', 'Shoulder epaulets', 'Chest logo'],
    appeal: 'Office-ready or undercover-ready',
    iconic: true,
    category: 'culture',
    funFact: 'Despite the exclusive name, "membership" just meant buying the jacket at the store.',
  },
  {
    id: 'leg_warmers',
    exhibit: 'Leg Warmers',
    icon: '🧦',
    matchText: 'Leg warmers began as practical garments used by dancers to keep their muscles warm during rehearsals.',
    tagline: 'Aerobics Ready at All Times',
    year: '1984',
    description: 'Leg warmers began as practical garments used by dancers to keep their muscles warm during rehearsals. During the early 1980s, aerobics culture, dance movies, music videos, and Jane Fonda\'s enormously successful workout programs carried them far beyond the studio. Women paired slouchy knitted warmers with tights, leotards, headbands, and athletic shoes—even when no exercise was planned. By 1984, simply dressing as though an aerobics class might break out at any moment was an accepted fashion strategy.',
    origin: 'Dance rehearsal garments',
    popularized_by: 'Aerobics culture, Jane Fonda',
    paired_with: ['Tights', 'Leotards', 'Headbands', 'Athletic shoes'],
    strategy: 'Dress as if aerobics might break out',
    iconic: true,
    category: 'culture',
    funFact: 'Leg warmers were originally for dancers, not fashion—Jane Fonda\'s workouts changed that.',
  },
  {
    id: 'big_hair',
    exhibit: 'Big Hair',
    icon: '💇',
    matchText: 'In 1984, subtlety was rarely the objective. Hair was teased, feathered, curled, sprayed, moussed, crimped, and lifted until it achieved structural independence.',
    tagline: 'The Higher, the Better',
    year: '1984',
    description: 'In 1984, subtlety was rarely the objective. Hair was teased, feathered, curled, sprayed, moussed, crimped, and lifted until it achieved structural independence. Rock musicians, television stars, models, and high-school students all contributed to an unofficial competition for maximum volume. The style crossed gender lines, with men and women alike relying on blow dryers, brushes, and heroic amounts of hairspray. Doorways generally remained passable, but automobile headrests became increasingly inconvenient.',
    techniques: ['Teased', 'Feathered', 'Curled', 'Sprayed', 'Moussed', 'Crimped', 'Lifted'],
    participants: ['Rock musicians', 'TV stars', 'Models', 'High-school students'],
    gender: 'Crossed gender lines',
    obstacle: 'Automobile headrests',
    iconic: true,
    category: 'culture',
    funFact: 'Hairspray sales boomed in 1984 as everyone reached for maximum hair volume.',
  },
];

const VIEWED_EXHIBITS = new Set();
const EXHIBIT_VIEW_COUNTS = {};

export function findThingsThatScream1984Entry(adText) {
  return ENTRIES.find(e => e.matchText === adText) || null;
}

export function trackThingsThatScream1984View(entryId) {
  VIEWED_EXHIBITS.add(entryId);
  EXHIBIT_VIEW_COUNTS[entryId] = (EXHIBIT_VIEW_COUNTS[entryId] || 0) + 1;
  const unlocked = [];

  if (VIEWED_EXHIBITS.size >= 5) unlocked.push('scream_1984_fan');
  if (VIEWED_EXHIBITS.size >= 15) unlocked.push('scream_1984_enthusiast');
  if (VIEWED_EXHIBITS.size >= 25) unlocked.push('scream_1984_historian');

  return unlocked;
}

export function getThingsThatScream1984ViewCount() {
  return VIEWED_EXHIBITS.size;
}