// Minnesota Twins Broadcast — 1984
// Radio: Herb Carneal & John Gordon (WCCO) / TV: Ray Scott & Bob Kurtz
// Hubert H. Humphrey Metrodome — home of the Twins since 1982
// All stats cutoff: end of 1983 season

export function pickTwinsLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickTwinsPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Kirby Puckett": {
    lines: [
      "Kirby Puckett grew up as the youngest of nine children on Chicago's South Side.",
      "Kirby Puckett attended Bradley University briefly before continuing his career at Triton College.",
      "Kirby Puckett batted .472 with 16 home runs during the spring of 1982 at Triton College.",
      "Kirby Puckett hit four home runs in one college game.",
      "Kirby Puckett was named the 1982 Region IV Junior College Player of the Year.",
      "Kirby Puckett was selected by Minnesota with the third overall choice in the January 1982 draft.",
      "Kirby Puckett began his professional career with the Elizabethton Twins in 1982.",
      "Kirby Puckett batted .382 with 105 hits in only 65 games for Elizabethton.",
      "Kirby Puckett scored 65 runs and stole 43 bases during his first professional season.",
      "Kirby Puckett led the Appalachian League in batting average, runs, hits, total bases and stolen bases.",
      "Kirby Puckett was named the Appalachian League Player of the Year in 1982.",
      "Kirby Puckett advanced to the Visalia Oaks for the 1983 season.",
      "Kirby Puckett began the 1983 season with a 16-game hitting streak.",
      "Kirby Puckett batted .314 with 172 hits in 138 games for Visalia.",
      "Kirby Puckett recorded 29 doubles, seven triples and nine home runs in 1983.",
      "Kirby Puckett drove in 97 runs and scored 105 times for Visalia.",
      "Kirby Puckett stole 48 bases during the 1983 season.",
      "Kirby Puckett led California League outfielders in assists.",
      "Kirby Puckett was named the California League Player of the Year in 1983.",
      "Kirby Puckett has won his league's Player of the Year award in each of his first two professional seasons.",
      "Kirby Puckett has not yet appeared in a major-league regular-season game entering 1984.",
      "Kirby Puckett's compact build produces more power than many pitchers expect.",
      "Kirby Puckett combines a strong throwing arm with the speed required to cover center field.",
      "Kirby Puckett enters 1984 as one of the most exciting young players in Minnesota's organization.",
    ],
  },
  "Mickey Hatcher": {
    lines: [
      "Mickey Hatcher's full name is Michael Vaughn Hatcher.",
      "Mickey Hatcher was selected in three different amateur drafts before signing professionally.",
      "Mickey Hatcher was drafted by Houston in 1974 and by the New York Mets in 1976.",
      "Mickey Hatcher signed with Los Angeles after the Dodgers selected him in the fifth round of the 1977 draft.",
      "Mickey Hatcher played both baseball and football at the University of Oklahoma.",
      "Mickey Hatcher served as a wide receiver and punter for the Oklahoma football team.",
      "Mickey Hatcher was part of an Oklahoma squad that appeared in the Fiesta Bowl.",
      "Mickey Hatcher reached the major leagues with the Dodgers in 1979.",
      "Mickey Hatcher was traded to Minnesota shortly before the 1981 season.",
      "Mickey Hatcher came to Minnesota in the deal that sent Ken Landreaux to Los Angeles.",
      "Mickey Hatcher can play third base, first base, designated hitter and all three outfield positions.",
      "Mickey Hatcher appeared in 106 games for Minnesota during the 1983 season.",
      "Mickey Hatcher led the Twins with a .317 batting average in 1983.",
      "Mickey Hatcher collected 119 hits in 375 at-bats during the 1983 season.",
      "Mickey Hatcher recorded 15 doubles, three triples and nine home runs in 1983.",
      "Mickey Hatcher drove in 47 runs and scored 50 times during the 1983 season.",
      "Mickey Hatcher struck out only 19 times in 395 plate appearances in 1983.",
      "Mickey Hatcher is an aggressive hitter who is difficult to strike out.",
      "Mickey Hatcher's versatility allows him to remain in the lineup when another player changes positions.",
      "Mickey Hatcher brings the same all-out energy to an ordinary ground ball that he brings to an extra-base hit.",
    ],
  },
  "Kent Hrbek": {
    lines: [
      "Kent Hrbek was born and raised in the Minneapolis-St. Paul area.",
      "Kent Hrbek attended Kennedy High School in Bloomington, Minnesota.",
      "Kent Hrbek grew up only a short distance from Metropolitan Stadium.",
      "Kent Hrbek was selected by Minnesota in the 17th round of the 1978 amateur draft.",
      "Kent Hrbek was chosen 16 rounds after Minnesota selected shortstop Lenny Faedo.",
      "Kent Hrbek initially received only limited attention from professional scouts.",
      "Kent Hrbek played American Legion baseball before beginning his professional career.",
      "Kent Hrbek reached the major leagues in August 1981 at the age of 21.",
      "Kent Hrbek hit a home run in his first major-league game.",
      "Kent Hrbek became Minnesota's regular first baseman during the 1982 season.",
      "Kent Hrbek batted .301 with 23 home runs and 92 RBI in 1982.",
      "Kent Hrbek was selected to the American League All-Star team as a rookie.",
      "Kent Hrbek finished second in the 1982 American League Rookie of the Year voting.",
      "Kent Hrbek appeared in 141 games during the 1983 season.",
      "Kent Hrbek batted .297 with a .366 on-base percentage in 1983.",
      "Kent Hrbek led Minnesota with 41 doubles during the 1983 season.",
      "Kent Hrbek also recorded five triples, 16 home runs and 84 RBI in 1983.",
      "Kent Hrbek slugged .489 during the 1983 season.",
      "Kent Hrbek hit 10 of his 16 home runs after the 1983 All-Star break.",
      "Kent Hrbek has a smooth left-handed swing designed for line drives and power.",
      "Kent Hrbek moves surprisingly well around first base for a player of his size.",
      "Kent Hrbek is already one of the most popular Minnesota-born players in Twins history.",
      "Kent Hrbek gives the young Twins a hometown star in the middle of the batting order.",
    ],
  },
  "Tom Brunansky": {
    lines: [
      "Tom Brunansky's full name is Thomas Andrew Brunansky.",
      "Tom Brunansky attended West Covina High School in California.",
      "Tom Brunansky was selected by California with the 14th overall choice in the 1978 amateur draft.",
      "Tom Brunansky reached the major leagues with the Angels in 1981.",
      "Tom Brunansky was traded to Minnesota early in the 1982 season.",
      "Minnesota acquired Tom Brunansky in exchange for Doug Corbett and Rob Wilfong.",
      "Tom Brunansky immediately became Minnesota's regular right fielder.",
      "Tom Brunansky collected hits in each of his first five games after joining the Twins.",
      "Tom Brunansky played in every Minnesota game after the 1982 trade.",
      "Tom Brunansky batted .272 with 20 home runs during the 1982 season.",
      "Tom Brunansky drew 71 walks and produced a .377 on-base percentage in 1982.",
      "Tom Brunansky hit an inside-the-park grand slam against Milwaukee on July 19, 1982.",
      "Tom Brunansky appeared in 151 games during the 1983 season.",
      "Tom Brunansky led the Twins with 28 home runs in 1983.",
      "Tom Brunansky drove in 82 runs and scored 70 times during the 1983 season.",
      "Tom Brunansky collected 24 doubles and five triples in 1983.",
      "Tom Brunansky's strong throwing arm makes runners think twice before challenging him in right field.",
      "Tom Brunansky is capable of reaching the seats in any part of the ballpark.",
      "Tom Brunansky will accept a walk when pitchers refuse to challenge him.",
      "Tom Brunansky and Kent Hrbek give Minnesota two young power hitters who have already established themselves in the major leagues.",
    ],
  },
  "Gary Gaetti": {
    lines: [
      "Gary Gaetti was born in Centralia, Illinois.",
      "Gary Gaetti's father worked for the railroad and regularly hit ground balls to him after work.",
      "Gary Gaetti attended Lincoln Land Community College before transferring to Northwest Missouri State.",
      "Gary Gaetti was drafted by St. Louis and the Chicago White Sox but did not sign with either club.",
      "Gary Gaetti was selected by Minnesota with the 11th overall choice in the 1979 amateur draft.",
      "Gary Gaetti had barely heard of the Minnesota Twins before the club drafted him.",
      "Gary Gaetti hit 14 home runs in 66 games during his first professional season.",
      "Gary Gaetti led the Midwest League with 22 home runs in 1980.",
      "Gary Gaetti hit 30 home runs for Double-A Orlando in 1981.",
      "Gary Gaetti hit a home run in his first major-league at-bat.",
      "Gary Gaetti's first major-league home run came against Charlie Hough.",
      "Gary Gaetti hit two home runs on Opening Day in 1982.",
      "Gary Gaetti was also thrown out on Opening Day attempting to turn a triple into an inside-the-park home run.",
      "Gary Gaetti recorded 25 doubles, 25 home runs and 84 RBI during his first full season.",
      "Gary Gaetti finished fifth in the 1982 American League Rookie of the Year voting.",
      "Gary Gaetti played 157 games during the 1983 season.",
      "Gary Gaetti collected 30 doubles and hit 21 home runs in 1983.",
      "Gary Gaetti drove in 78 runs and scored 81 times during the 1983 season.",
      "Gary Gaetti possesses one of the strongest throwing arms among American League third basemen.",
      "Gary Gaetti is willing to attempt a difficult throw from well behind third base.",
      "Gary Gaetti's power allows Minnesota to receive middle-of-the-order production from third base.",
      "Gary Gaetti has never returned to the minor leagues after reaching Minnesota in September 1981.",
    ],
  },
  "Randy Bush": {
    lines: [
      "Randy Bush's full name is Robert Randall Bush.",
      "Randy Bush was born in Dover, Delaware.",
      "Randy Bush played college baseball at the University of New Orleans.",
      "Minnesota selected Randy Bush in the second round of the 1979 amateur draft.",
      "Randy Bush developed alongside several future Twins at Double-A Orlando.",
      "Randy Bush was part of an Orlando lineup that also included Gary Gaetti, Tim Laudner and Tim Teufel.",
      "Randy Bush made his major-league debut during the 1982 season.",
      "Randy Bush appeared in 55 games during his first major-league season.",
      "Randy Bush batted .244 with four home runs and 13 RBI in 1982.",
      "Randy Bush received a much larger role during the 1983 season.",
      "Randy Bush appeared in 124 games for Minnesota in 1983.",
      "Randy Bush collected 93 hits, including 24 doubles and three triples, in 1983.",
      "Randy Bush hit 11 home runs and drove in 56 runs during the 1983 season.",
      "Randy Bush produced a .418 slugging percentage in 1983.",
      "Randy Bush can serve as a designated hitter, first baseman or corner outfielder.",
      "Randy Bush gives Minnesota another left-handed bat behind Kent Hrbek.",
      "Randy Bush is capable of delivering a home run or a difficult late-inning pinch-hit.",
      "Randy Bush's versatility makes him useful even when he is not listed in the starting lineup.",
    ],
  },
  "Tim Teufel": {
    lines: [
      "Tim Teufel's full name is Timothy Shawn Teufel.",
      "Tim Teufel was born in Greenwich, Connecticut.",
      "Tim Teufel attended St. Petersburg Junior College before transferring to Clemson University.",
      "Tim Teufel was selected in amateur drafts by St. Louis and the Chicago White Sox but did not sign.",
      "Minnesota selected Tim Teufel in the second round of the 1980 amateur draft.",
      "Tim Teufel played alongside Gary Gaetti, Randy Bush and Tim Laudner at Double-A Orlando.",
      "Tim Teufel developed primarily as a second baseman.",
      "Tim Teufel can also fill in at third base.",
      "Tim Teufel spent most of the 1983 season with Triple-A Toledo.",
      "Tim Teufel made his major-league debut on September 3, 1983.",
      "Tim Teufel appeared in 21 games during his first major-league trial.",
      "Tim Teufel batted .308 with 24 hits in 78 at-bats in 1983.",
      "Tim Teufel collected seven doubles, one triple and three home runs during that trial.",
      "Tim Teufel slugged .538 during his first major-league month.",
      "Tim Teufel scored 11 runs and drove in six during the 1983 season.",
      "Tim Teufel gives Minnesota a young right-handed hitter at second base.",
      "Tim Teufel showed immediate extra-base ability during his September opportunity.",
      "Tim Teufel enters 1984 attempting to turn a successful trial into a permanent starting position.",
    ],
  },
  "Dave Engle": {
    lines: [
      "Dave Engle's full name is Ralph David Engle.",
      "Dave Engle played college baseball at the University of Southern California.",
      "Dave Engle was selected by the California Angels in the third round of the 1978 amateur draft.",
      "Dave Engle was traded to Minnesota before ever appearing in a major-league game for California.",
      "Dave Engle came to Minnesota with Ken Landreaux, Paul Hartzell and Brad Havens.",
      "Dave Engle was one of the four players exchanged for Rod Carew.",
      "Dave Engle reached the major leagues with Minnesota during the 1981 season.",
      "Dave Engle originally played primarily in the outfield and at first base.",
      "Dave Engle moved behind the plate during the 1983 season.",
      "A childhood eye injury made the dark roof of the Metrodome a difficult background for Dave Engle when tracking fly balls.",
      "Dave Engle appeared in 120 games during the 1983 season.",
      "Dave Engle batted .305 with a .350 on-base percentage in 1983.",
      "Dave Engle collected 114 hits, including 22 doubles and four triples, in 1983.",
      "Dave Engle hit eight home runs and drove in 43 runs during the 1983 season.",
      "Dave Engle struck out only 39 times in 408 plate appearances in 1983.",
      "Dave Engle gives Minnesota considerably more offensive production than the average catcher.",
      "Dave Engle can catch, play first base, work in the outfield or serve as designated hitter.",
      "Dave Engle's position flexibility allows the manager to change catchers without necessarily removing his bat from the lineup.",
    ],
  },
  "Houston Jimenez": {
    lines: [
      "Houston Jimenez's full name is Alfonso Houston Jimenez Gonzalez.",
      "Houston Jimenez was born in Mexico City.",
      "Houston Jimenez played professionally in the Mexican League before joining the Twins organization.",
      "Houston Jimenez spent time with the Puebla club in Mexico.",
      "Houston Jimenez signed with Minnesota before the 1981 season.",
      "Houston Jimenez developed as a shortstop and second baseman.",
      "Houston Jimenez made his major-league debut on June 13, 1983.",
      "Houston Jimenez appeared in 36 games during his first major-league season.",
      "Houston Jimenez collected 15 hits in 86 at-bats in 1983.",
      "Houston Jimenez recorded five doubles and one triple during his rookie season.",
      "Houston Jimenez drove in nine runs in 1983.",
      "Houston Jimenez is a compactly built middle infielder.",
      "Houston Jimenez relies more upon contact and defense than home-run power.",
      "Houston Jimenez can fill in on either side of second base.",
      "Houston Jimenez enters 1984 with an opportunity to become Minnesota's regular shortstop.",
    ],
  },
  "Tim Laudner": {
    lines: [
      "Tim Laudner was born in Mason City, Iowa.",
      "Tim Laudner moved to Brooklyn Center, Minnesota, at the age of seven.",
      "Tim Laudner played baseball, football and hockey while growing up.",
      "Tim Laudner was an all-state tight end at Park Center High School.",
      "Tim Laudner played in a high-school football all-star game at Metropolitan Stadium.",
      "Tim Laudner originally used his strong throwing arm as a pitcher.",
      "Tim Laudner pitched a no-hitter during a high-school district tournament.",
      "Tim Laudner struck out 15 hitters in a one-hit tournament victory.",
      "Tim Laudner switched from pitching to catching during the summer of 1976.",
      "Tim Laudner played college baseball at the University of Missouri.",
      "Minnesota selected Tim Laudner in the third round of the 1979 amateur draft.",
      "Tim Laudner hit 42 home runs for Double-A Orlando in 1981.",
      "Tim Laudner's 42 home runs broke the Southern League's single-season record.",
      "Tim Laudner led all of organized professional baseball in home runs during the 1981 season.",
      "Tim Laudner hit a home run in his first major-league game.",
      "Tim Laudner homered again in his second major-league game.",
      "Tim Laudner batted .255 with seven home runs in 93 games during the 1982 season.",
      "Tim Laudner was named to a major-league All-Rookie team at catcher in 1982.",
      "Tim Laudner appeared in 62 games during the 1983 season.",
      "Tim Laudner hit six home runs in only 168 at-bats in 1983.",
      "Tim Laudner is regarded as Minnesota's stronger defensive catcher.",
      "Tim Laudner takes particular pride in handling the pitching staff.",
      "Tim Laudner's strong arm can discourage opponents from attempting to steal.",
      "Tim Laudner provides right-handed power from the catching position.",
    ],
  },
  "Ron Washington": {
    lines: [
      "Ron Washington's full name is Ronald Washington.",
      "Ron Washington was born in New Orleans, Louisiana.",
      "Ron Washington reached the major leagues with the Los Angeles Dodgers in 1977.",
      "Ron Washington appeared in 10 games during his original major-league opportunity.",
      "Ron Washington returned to the major leagues with Minnesota during the 1981 season.",
      "Ron Washington can play shortstop, second base and third base.",
      "Ron Washington appeared in 99 games during the 1983 season.",
      "Ron Washington collected 78 hits in 317 at-bats in 1983.",
      "Ron Washington recorded seven doubles, three triples and four home runs in 1983.",
      "Ron Washington drove in 26 runs and scored 28 times during the 1983 season.",
      "Ron Washington stole 10 bases in 1983.",
      "Ron Washington started 73 games at shortstop during the 1983 season.",
      "Ron Washington gives Minnesota an experienced alternative at several infield positions.",
      "Ron Washington can enter as a pinch-runner, defensive replacement or spot starter.",
      "Ron Washington's quick hands are useful when beginning or completing a double play.",
    ],
  },
  "Jim Eisenreich": {
    lines: [
      "Jim Eisenreich's full name is James Michael Eisenreich.",
      "Jim Eisenreich grew up in St. Cloud, Minnesota.",
      "Jim Eisenreich attended St. Cloud State University.",
      "Minnesota selected Jim Eisenreich in the 16th round of the 1980 amateur draft.",
      "Jim Eisenreich jumped from Class A baseball directly to the major leagues in 1982.",
      "Jim Eisenreich was Minnesota's Opening Day center fielder during his rookie season.",
      "Jim Eisenreich led off for the Twins in the first regular-season game played at the Metrodome.",
      "Jim Eisenreich showed promising contact ability during his original major-league opportunity.",
      "Jim Eisenreich's first two seasons were interrupted by involuntary physical symptoms that became more severe in large, noisy crowds.",
      "Jim Eisenreich temporarily left the club during the 1982 season.",
      "Jim Eisenreich returned briefly to Minnesota during the 1983 season.",
      "Jim Eisenreich appeared in two games and collected two hits in seven at-bats in 1983.",
      "One of Jim Eisenreich's two 1983 hits was a double.",
      "Jim Eisenreich bats and throws left-handed.",
      "Jim Eisenreich can play center field or either corner-outfield position.",
      "Jim Eisenreich's natural ability remains evident whenever he is comfortable enough to play.",
    ],
  },
  "Lenny Faedo": {
    lines: [
      "Lenny Faedo's full name is Leonard Edward Faedo.",
      "Lenny Faedo was born in Tampa, Florida.",
      "Lenny Faedo was selected by Minnesota in the first round of the 1978 amateur draft.",
      "Lenny Faedo was the 16th overall selection in that draft.",
      "Lenny Faedo was selected two choices after future teammate Tom Brunansky.",
      "Lenny Faedo was chosen 16 rounds before Minnesota selected Kent Hrbek.",
      "Lenny Faedo reached the major leagues in September 1980 at the age of 20.",
      "Lenny Faedo developed primarily as a shortstop.",
      "Lenny Faedo appeared in 51 games during the 1983 season.",
      "Lenny Faedo batted .277 with 48 hits in 173 at-bats in 1983.",
      "Lenny Faedo recorded seven doubles, one home run and 18 RBI during the 1983 season.",
      "Lenny Faedo struck out only 19 times in 182 plate appearances in 1983.",
      "Lenny Faedo started all 51 of his defensive appearances at shortstop in 1983.",
      "Lenny Faedo gives Minnesota a contact-oriented alternative at shortstop.",
      "Lenny Faedo is still only 23 years old entering the 1984 season.",
    ],
  },
  "Greg Gagne": {
    lines: [
      "Greg Gagne was born in Fall River, Massachusetts.",
      "Greg Gagne was selected by the New York Yankees in the fifth round of the 1979 amateur draft.",
      "Greg Gagne spent three seasons developing in the Yankees farm system.",
      "Greg Gagne was traded to Minnesota before the 1982 season.",
      "Greg Gagne came to the Twins with Ron Davis and pitcher Paul Boris.",
      "New York received shortstop Roy Smalley in the trade.",
      "Greg Gagne developed primarily as a shortstop.",
      "Greg Gagne received his first major-league opportunity during the 1983 season.",
      "Greg Gagne appeared in 10 games for Minnesota in 1983.",
      "Greg Gagne collected three hits, including one double, in 27 at-bats.",
      "Greg Gagne drove in three runs during his first major-league trial.",
      "Greg Gagne started all 10 of his 1983 defensive appearances at shortstop.",
      "Greg Gagne is only 22 years old entering the 1984 season.",
      "Greg Gagne gives Minnesota another young candidate for the shortstop position.",
      "Greg Gagne's defense and mobility may earn him opportunities even while his hitting continues to develop.",
    ],
  },
  "Frank Viola": {
    lines: [
      "Frank Viola's full name is Frank John Viola.",
      "Frank Viola is a left-handed pitcher from East Meadow, New York.",
      "Frank Viola is commonly known by the nickname \"Sweet Music.\"",
      "Frank Viola was selected by Kansas City in the 16th round of the 1978 draft but did not sign.",
      "Frank Viola attended St. John's University in New York.",
      "Frank Viola compiled a 26-2 collegiate record with a 1.67 ERA at St. John's.",
      "Frank Viola faced Yale's Ron Darling in a famous 1981 NCAA tournament pitching duel.",
      "Frank Viola and Darling kept the game scoreless deep into extra innings.",
      "Minnesota selected Frank Viola in the second round of the 1981 amateur draft.",
      "Frank Viola reached the major leagues during the 1982 season.",
      "Frank Viola made 22 starts and threw 126 innings during his rookie season.",
      "Frank Viola went 4-10 with a 5.21 ERA in 1982.",
      "Frank Viola struck out 84 hitters during his rookie season.",
      "Frank Viola made 34 starts during the 1983 season.",
      "Frank Viola threw 210 innings and completed four games in 1983.",
      "Frank Viola struck out a team-leading 127 hitters during the 1983 season.",
      "Frank Viola finished 1983 with a 7-15 record and a 5.49 ERA.",
      "Frank Viola's record does not reflect the quality of his natural left-handed arsenal.",
      "Frank Viola changes speeds rather than attempting to overpower every hitter.",
      "Frank Viola is still only 23 years old entering the 1984 season.",
      "Frank Viola is being given an opportunity to develop through regular major-league starts.",
      "Frank Viola's smooth delivery helped inspire one of baseball's most appropriate nicknames.",
    ],
  },
  "Mike Smithson": {
    lines: [
      "Mike Smithson's full name is Billy Mike Smithson.",
      "Mike Smithson was born in Centerville, Tennessee.",
      "Mike Smithson is a six-foot-eight-inch right-handed pitcher.",
      "Mike Smithson is among the tallest pitchers in the major leagues.",
      "Mike Smithson bats left-handed despite throwing right-handed.",
      "Mike Smithson reached the major leagues with Texas during the 1982 season.",
      "Mike Smithson made eight starts for the Rangers during his rookie season.",
      "Mike Smithson went 3-4 with a 5.01 ERA in 1982.",
      "Mike Smithson became a full-time starting pitcher during the 1983 season.",
      "Mike Smithson made 33 starts for Texas in 1983.",
      "Mike Smithson went 10-14 with a 3.91 ERA during the 1983 season.",
      "Mike Smithson threw 223 and a third innings and completed 10 games in 1983.",
      "Mike Smithson struck out 135 hitters during the 1983 season.",
      "Mike Smithson walked only 71 hitters in more than 223 innings in 1983.",
      "Minnesota acquired Mike Smithson from Texas on December 7, 1983.",
      "Mike Smithson came to Minnesota with John Butcher and Sam Sorce.",
      "Texas received outfielder Gary Ward in the trade.",
      "Mike Smithson's height creates a steep downward angle on his pitches.",
      "Mike Smithson gives Minnesota a durable right-hander with recent experience pitching more than 200 innings.",
    ],
  },
  "Ken Schrom": {
    lines: [
      "Ken Schrom's full name is Kenneth Marvin Schrom.",
      "Ken Schrom was born in Grangeville, Idaho.",
      "Minnesota originally selected Ken Schrom in the 10th round of the 1973 amateur draft.",
      "Ken Schrom chose not to sign with the Twins after that draft.",
      "Ken Schrom later attended the University of Idaho.",
      "California selected Ken Schrom in the 17th round of the 1976 amateur draft.",
      "Ken Schrom reached the major leagues with the Angels in 1980.",
      "Ken Schrom joined Minnesota before the 1983 season.",
      "Ken Schrom appeared in 33 games and made 28 starts during the 1983 season.",
      "Ken Schrom led the Twins with 15 victories in 1983.",
      "Ken Schrom finished the season with a 15-8 record.",
      "Ken Schrom posted a 3.71 ERA over 196 and a third innings.",
      "Ken Schrom completed six games during the 1983 season.",
      "Ken Schrom recorded one shutout in 1983.",
      "Ken Schrom allowed only 14 home runs during the 1983 season.",
      "Ken Schrom relies more upon location and movement than overpowering velocity.",
      "Ken Schrom's 15 victories were more than twice as many as any other Minnesota starter recorded in 1983.",
      "Ken Schrom enters 1984 after the strongest major-league season of his career.",
    ],
  },
  "John Butcher": {
    lines: [
      "John Butcher's full name is John Daniel Butcher.",
      "John Butcher was born in Glendale, California.",
      "John Butcher is a six-foot-four-inch right-handed pitcher.",
      "John Butcher reached the major leagues with Texas during the 1980 season.",
      "John Butcher has worked as both a starting pitcher and a reliever.",
      "John Butcher made 13 starts for Texas during the 1982 season.",
      "John Butcher appeared in 38 games during the 1983 season.",
      "John Butcher made six starts and worked 123 innings in 1983.",
      "John Butcher went 6-6 with a 3.51 ERA during the 1983 season.",
      "John Butcher completed one game and recorded one shutout in 1983.",
      "John Butcher also recorded five saves during the 1983 season.",
      "John Butcher's combination of starts and saves demonstrates his versatility.",
      "Minnesota acquired John Butcher from Texas on December 7, 1983.",
      "John Butcher came to Minnesota with Mike Smithson and Sam Sorce.",
      "John Butcher can start, relieve a struggling pitcher early or protect a lead late in the game.",
      "John Butcher's 1983 performance suggests he can succeed in almost any pitching role.",
    ],
  },
  "Ron Davis": {
    lines: [
      "Ron Davis' full name is Ronald Gene Davis.",
      "Ron Davis was born in Houston, Texas.",
      "Ron Davis reached the major leagues with the New York Yankees in 1978.",
      "Ron Davis became an important late-inning reliever behind closer Goose Gossage.",
      "Ron Davis appeared in the postseason with the Yankees.",
      "Ron Davis posted a 2.71 ERA in 43 appearances during the 1981 season.",
      "Ron Davis struck out 83 hitters in only 73 innings in 1981.",
      "Minnesota acquired Ron Davis from New York before the 1982 season.",
      "Ron Davis came to Minnesota with Greg Gagne and Paul Boris.",
      "The Yankees received shortstop Roy Smalley in that trade.",
      "Ron Davis became Minnesota's primary closer.",
      "Ron Davis appeared in 66 games during the 1983 season.",
      "Ron Davis recorded 30 saves in 1983.",
      "Ron Davis posted a 3.34 ERA over 89 innings during the 1983 season.",
      "Ron Davis struck out 84 hitters in 1983.",
      "Ron Davis can enter before the ninth inning and remain long enough to earn a multi-inning save.",
      "Ron Davis attacks hitters with a hard fastball and breaking pitches.",
      "Ron Davis' 30 saves were more than all other Minnesota pitchers combined.",
      "Ron Davis gives the young Twins an experienced late-inning pitcher.",
    ],
  },
  "Pete Filson": {
    lines: [
      "Pete Filson's full name is William Peter Filson.",
      "Pete Filson was born in Portland, Maine.",
      "Pete Filson is a left-handed pitcher who can bat from either side of the plate.",
      "Pete Filson began his professional career in the New York Yankees organization.",
      "Pete Filson was traded from New York to Minnesota during the 1982 season.",
      "Pete Filson came to the Twins with Larry Milbourne and John Pacella.",
      "New York received catcher Butch Wynegar and pitcher Roger Erickson.",
      "Pete Filson made his major-league debut with Minnesota in 1982.",
      "Pete Filson appeared in 26 games during the 1983 season.",
      "Pete Filson made eight starts and also worked in relief during 1983.",
      "Pete Filson went 4-1 with a 3.40 ERA.",
      "Pete Filson pitched exactly 90 innings during the 1983 season.",
      "Pete Filson struck out 49 hitters and walked only 29 in 1983.",
      "Pete Filson recorded one save during the 1983 season.",
      "Pete Filson can face one difficult left-handed hitter or remain for several innings.",
      "Pete Filson's starting experience makes him useful when an early call to the bullpen is necessary.",
    ],
  },
  "Rick Lysander": {
    lines: [
      "Rick Lysander's full name is Richard Eugene Lysander.",
      "Rick Lysander was born in Manteca, California.",
      "Rick Lysander is a right-handed pitcher.",
      "Rick Lysander reached the major leagues with Oakland during the 1980 season.",
      "Rick Lysander later joined the Houston organization.",
      "Minnesota acquired Rick Lysander from Houston in January 1983.",
      "The Twins sent pitcher Bob Veselic to Houston in the transaction.",
      "Rick Lysander appeared in 61 games during his first Minnesota season.",
      "Rick Lysander pitched 125 innings despite making only four starts in 1983.",
      "Rick Lysander finished 1983 with a 3.38 ERA.",
      "Rick Lysander recorded three saves during the 1983 season.",
      "Rick Lysander completed one of his four starts.",
      "Rick Lysander's complete game was also a shutout.",
      "Rick Lysander is one of the rare pitchers capable of recording both a complete-game shutout and several saves in the same season.",
      "Rick Lysander can enter in the middle innings and finish the game.",
      "Rick Lysander's 125 innings were an unusually large workload for a pitcher used primarily in relief.",
    ],
  },
  "Curt Wardle": {
    lines: [
      "Curt Wardle's full name is Curtis Allen Wardle.",
      "Curt Wardle was born in Downey, California.",
      "Curt Wardle was selected in four different amateur drafts.",
      "St. Louis selected Curt Wardle in the 45th round of the 1978 draft.",
      "California selected Curt Wardle in the third round of the January 1979 secondary draft.",
      "San Diego selected Curt Wardle in the second round of the January 1980 draft.",
      "Curt Wardle continued his amateur career rather than signing with those clubs.",
      "Curt Wardle attended San Bernardino Valley College.",
      "Curt Wardle later pitched for the University of California, Riverside.",
      "Minnesota selected Curt Wardle in the third round of the 1981 amateur draft.",
      "Curt Wardle was the 56th overall selection in the 1981 draft.",
      "Curt Wardle signed with Minnesota after being drafted for the fourth time.",
      "Curt Wardle is a right-handed pitcher.",
      "Curt Wardle developed in the Twins farm system as both a starter and reliever.",
      "Curt Wardle has not yet appeared in a major-league regular-season game entering 1984.",
      "Curt Wardle's persistence through four drafts has finally brought him close to a major-league opportunity.",
    ],
  },
  "Len Whitehouse": {
    lines: [
      "Len Whitehouse's full name is Leonard Joseph Whitehouse.",
      "Len Whitehouse was born in Burlington, Vermont.",
      "Len Whitehouse is a left-handed pitcher.",
      "Len Whitehouse gives Minnesota a bullpen contrast to right-handed closer Ron Davis.",
      "Len Whitehouse established himself as a full-time major-league reliever during the 1983 season.",
      "Len Whitehouse appeared in 60 games for Minnesota in 1983.",
      "Only Ron Davis made more appearances for the Twins during the 1983 season.",
      "Len Whitehouse went 7-1 during the 1983 season.",
      "Len Whitehouse posted a 4.15 ERA over 73 and two-thirds innings.",
      "Len Whitehouse recorded two saves in 1983.",
      "Len Whitehouse struck out 44 hitters during the 1983 season.",
      "Len Whitehouse worked exclusively in relief during 1983.",
      "Len Whitehouse can be used against a dangerous left-handed batter.",
      "Len Whitehouse can also remain in the game to face right-handed hitters.",
      "Len Whitehouse's seven relief victories were the highest total among Minnesota bullpen pitchers in 1983.",
      "Len Whitehouse provides manager Billy Gardner with an experienced left-handed option during the middle and late innings.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive — base hit.\"",
    "\"Long drive to left field — way back — gone. Home run!\"",
    "\"Ground ball to short — over to first — in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This is a young ballclub on the rise — the Twins have some real talent here.\"",
    "\"Minnesota baseball is alive and well — the fans here in the Twin Cities love their Twins.\"",
    "\"This team has power and youth — Kent Hrbek, Tom Brunansky, Gary Gaetti — that's a foundation.\"",
    "\"The Metrodome is home now — and the Twins are putting down roots indoors.\"",
    "\"Kirby Puckett is one of the most exciting young players to come along in years.\"",
    "\"There's talent everywhere you look in this lineup — the Twins can hurt you.\"",
    "\"This club is building something — the young players are starting to come together.\"",
    "\"Minnesota has one of the most exciting young cores in the American League.\"",
    "\"The fans in Minnesota have been waiting for a winner — and this team is getting closer.\"",
    "\"There's a buzz around the Twins this year — people can feel something building.\"",
    "\"This is a team that's been through some lean years — but the future is bright.\"",
    "\"Minnesota baseball — there's nothing quite like a night at the Metrodome.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Kirby Puckett is one of the most exciting young players in baseball — just watch him play.\"",
    "\"Kent Hrbek is a hometown kid making good — the fans here love Herbie.\"",
    "\"Gary Gaetti has one of the strongest arms you'll see at third base.\"",
    "\"Tom Brunansky can hit the ball out of any part of this ballpark.\"",
    "\"Frank Viola is going to win a lot of games in this league — Sweet Music is the real deal.\"",
    "\"Ron Davis has been a tremendous acquisition — he's the closer this team needed.\"",
    "\"Mickey Hatcher is as aggressive a hitter as you'll find — he never takes a pitch off.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening indoors at the Hubert H. Humphrey Metrodome.\"",
    "\"The lights are on at the Dome — Twins baseball tonight.\"",
    "The Metrodome — home of the Twins since 1982 — baseball under the Teflon roof.",
    "\"The air conditioning is humming tonight — always 72 degrees inside the Dome.\"",
    "\"The white Teflon roof stretched above the field — there's nothing else like it in baseball.\"",
    "\"The artificial turf plays fast tonight — ground balls will scoot through the infield.\"",
    "\"The seats are filling up nicely — Minnesota fans are excited about this young team.\"",
    "\"You can hear the ballgame echoing off the roof tonight — the Dome has its own sound.\"",
    "\"The baggy in right field — that's the Hank Aaron Lou Gehrig wall — it's a unique target.\"",
    "\"A comfortable evening inside the Metrodome — no rain delays here, ever.\"",
    "\"This is still a new ballpark — the fans are still getting used to baseball indoors.\"",
    "\"The Dome is hopping tonight — the crowd is into this one.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here in Minnesota is into this ballgame.\"",
    "\"Twins fans are making some noise tonight at the Dome.\"",
    "\"The fans in Minnesota have waited a long time for a winner — they're fired up tonight.\"",
    "\"The Metrodome is rocking tonight.\"",
    "\"Minnesota fans are among the most loyal in baseball — they've been through some lean years.\"",
    "\"The crowd is on its feet — they can feel something building here.\"",
    "\"A great turnout at the Metrodome tonight.\"",
    "\"These fans can see the talent on this young club — they're excited about the future.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to the Metrodome, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball on a Minnesota summer night.\"",
    "\"From all of us here in the Twin Cities, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story — that's the beauty of this sport.\"",
    "\"Baseball in Minnesota — it's a tradition that runs deep in this state.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone — into the seats at the Dome!\"",
    "\"A magnificent piece of hitting. Simply magnificent.\"",
    "\"The Twins are making their move here at the Metrodome.\"",
    "\"That one is long gone — off the baggy in right!\"",
    "\"You won't see many better than that one.\"",
    "\"Holy cow, what a ballgame!\"",
  ]},
};