// Universal Pitch-to-the-Plate Calls — 1984 Announcer Commentary
// Organized by pitch type to ensure category-appropriate calls
// Multi-line combos encouraged for narrative storytelling

function c(text, rarity = 'common') { return { text, rarity }; }

// =========== DELIVERY & SETUP (pitch-agnostic) ===========
export const DELIVERY_SETUP = [
  c("The pitcher comes set."),
  c("He checks the runner."),
  c("He looks toward first."),
  c("He glances back at second."),
  c("He takes a long look toward home."),
  c("He works from the stretch."),
  c("He begins his delivery."),
  c("He rocks and fires."),
  c("He lifts the leg and comes home."),
  c("He turns and delivers."),
  c("He winds and throws."),
  c("He kicks and fires."),
  c("He brings it to the plate."),
  c("Here comes the pitch."),
  c("The pitch is on the way."),
  c("He deals."),
  c("He fires home."),
  c("He comes over the top."),
  c("He drops down and delivers."),
  c("He reaches back and throws."),
  c("He gathers himself and comes home."),
  c("He pauses at the belt."),
  c("He takes a breath and delivers."),
  c("He comes set at the letters."),
  c("He steps toward the plate."),
  c("He drives off the rubber."),
  c("He works quickly and fires."),
  c("He wastes little time."),
  c("He holds the ball a moment longer."),
  c("He finally comes home."),
];

// =========== FASTBALLS (any fastball variant) ===========
export const FASTBALLS = [
  c("Fastball over the plate."),
  c("A fastball at the knees."),
  c("A heater on the outside corner."),
  c("A fastball up and away."),
  c("A fastball down and in."),
  c("A high fastball."),
  c("A low fastball."),
  c("A fastball just off the plate."),
  c("A heater at the letters."),
  c("A fastball on the black."),
  c("A fastball catches the corner."),
  c("A fastball misses outside."),
  c("A fastball runs inside."),
  c("A fastball sails high."),
  c("A fastball drops below the zone."),
  c("A straight fastball down the middle."),
  c("A fastball at the belt."),
  c("A heater beneath the hands."),
  c("A fastball near the chin."),
  c("A fastball on the inner half."),
  c("A fastball on the outer half."),
  c("A rising fastball above the zone."),
  c("A fastball with late life."),
  c("A lively fastball at the knees."),
  c("A hard fastball away."),
  c("A firm fastball inside."),
  c("A fastball that tails away."),
  c("A fastball that runs back over the plate."),
  c("A fastball that stays high."),
  c("A fastball that misses by inches."),
  c("A heater on the lower edge."),
  c("A fastball painted on the outside corner."),
  c("A fastball buried beneath the zone."),
  c("A fastball that rides up and in."),
  c("A fastball at the top of the zone."),
  c("A fastball near the outside edge."),
  c("A fastball that catches too much plate."),
  c("A fastball right where the catcher wanted it."),
  c("A fastball that misses the target."),
  c("A fastball with plenty behind it."),
];

// =========== CURVEBALLS ===========
export const CURVEBALLS = [
  c("A curveball drops in for a strike."),
  c("A breaking ball at the knees."),
  c("A curveball bends outside."),
  c("A curveball misses low."),
  c("A sharp curve over the plate."),
  c("A slow curveball taken for a strike."),
  c("A curveball that hangs."),
  c("A breaking ball that dives below the zone."),
  c("A curveball sweeps across the plate."),
  c("A big breaking ball outside."),
  c("A curveball that catches the corner."),
  c("A slow breaker inside."),
  c("A curveball that starts high and drops."),
  c("A breaking pitch at the bottom of the zone."),
  c("A curveball buried in the dirt."),
  c("A curveball that never breaks."),
  c("A hanging curve over the middle."),
  c("A curveball that freezes the hitter."),
  c("A slow curve that steals a strike."),
  c("A sharp breaker under the hands."),
  c("A curveball that sweeps away."),
  c("A breaking ball that backs up."),
  c("A curveball that slips off the plate."),
  c("A big looping curve."),
  c("A tight-breaking curveball."),
  c("A curveball with plenty of depth."),
  c("A breaking pitch that falls off the table."),
  c("A curveball that drops beneath the bat."),
  c("A slow breaker just outside."),
  c("A curveball that clips the lower corner."),
];

// =========== SLIDERS ===========
export const SLIDERS = [
  c("A slider down and away."),
  c("A slider on the outside corner."),
  c("A slider misses off the plate."),
  c("A slider beneath the zone."),
  c("A sharp slider at the knees."),
  c("A slider that sweeps away."),
  c("A slider that backs up inside."),
  c("A hanging slider over the plate."),
  c("A slider near the back foot."),
  c("A slider that catches the corner."),
  c("A slider that just misses."),
  c("A slider with late movement."),
  c("A slider buried in the dirt."),
  c("A slider that runs beneath the bat."),
  c("A tight slider outside."),
  c("A slider on the lower edge."),
  c("A slider that stays up."),
  c("A slider that spins over the middle."),
  c("A slider that starts in and breaks away."),
  c("A slider that freezes him."),
  c("A slider that gets too much plate."),
  c("A sweeping slider across the zone."),
  c("A slider that dives at the last moment."),
  c("A slider that never reaches the plate."),
  c("A slider off the end of the plate."),
  c("A hard slider beneath the hands."),
  c("A slider that moves sharply to the glove side."),
  c("A slider that breaks into the hitter."),
  c("A slider that misses low and away."),
  c("A slider perfectly located."),
];

// =========== CHANGEUPS ===========
export const CHANGEUPS = [
  c("A changeup down and away."),
  c("A changeup taken for a strike."),
  c("A slow change beneath the zone."),
  c("A changeup that fades outside."),
  c("A changeup at the knees."),
  c("A changeup that stays high."),
  c("A changeup over the middle."),
  c("A changeup that dies before the plate."),
  c("A changeup that fools him badly."),
  c("A changeup on the outer half."),
  c("A changeup near the bottom edge."),
  c("A changeup that slips beneath the bat."),
  c("A soft change outside."),
  c("A changeup with late fade."),
  c("A changeup that runs away from the hitter."),
  c("A changeup left up in the zone."),
  c("A changeup that catches too much plate."),
  c("A changeup just off the corner."),
  c("A changeup buried low."),
  c("A changeup that pulls the hitter forward."),
  c("A changeup that looks like a fastball early."),
  c("A changeup that arrives much later."),
  c("A changeup that floats over the plate."),
  c("A changeup beneath the hands."),
  c("A changeup perfectly spotted away."),
];

// =========== SINKERS & TWO-SEAMERS ===========
export const SINKERS = [
  c("A sinker at the knees."),
  c("A sinking fastball down and in."),
  c("A two-seamer on the outside corner."),
  c("A sinker that runs beneath the zone."),
  c("A fastball with heavy sink."),
  c("A two-seamer that tails inside."),
  c("A sinker that runs off the plate."),
  c("A sinking fastball over the inner half."),
  c("A two-seamer that catches the corner."),
  c("A sinker that dives late."),
  c("A fastball with arm-side run."),
  c("A sinker below the knees."),
  c("A two-seamer that stays up."),
  c("A sinker right at the bottom edge."),
  c("A running fastball away."),
  c("A sinker that bores in on the hands."),
  c("A two-seamer that moves back over the plate."),
  c("A sinker that misses low."),
  c("A sinking fastball that clips the zone."),
  c("A heavy fastball near the bottom."),
];

// =========== SPLITTERS & FORKBALLS ===========
export const SPLITTERS = [
  c("A splitter drops beneath the zone."),
  c("A forkball buried in the dirt."),
  c("A split-finger fastball that dives late."),
  c("A splitter beneath the bat."),
  c("A forkball at the knees."),
  c("A splitter that falls off the table."),
  c("A split-finger pitch outside."),
  c("A splitter that starts in the zone."),
  c("A forkball that disappears."),
  c("A splitter that bounces in front of the plate."),
  c("A splitter taken for a low strike."),
  c("A forkball that hangs."),
  c("A splitter that stays too high."),
  c("A split-finger pitch with sharp drop."),
  c("A forkball that pulls the hitter forward."),
  c("A splitter that never reaches the catcher cleanly."),
  c("A split-finger fastball just below the zone."),
  c("A forkball with late tumble."),
  c("A splitter that catches the bottom corner."),
  c("A split-finger pitch over the heart of the plate."),
];

// =========== SCREWBALLS ===========
export const SCREWBALLS = [
  c("A screwball that runs inside."),
  c("A screwball fading away."),
  c("A screwball at the knees."),
  c("A screwball beneath the zone."),
  c("A screwball that breaks the wrong way."),
  c("A screwball on the outside corner."),
  c("A screwball buried low."),
  c("A screwball that moves sharply inside."),
  c("A screwball that catches too much plate."),
  c("A screwball that fools the hitter."),
  c("A screwball with late movement."),
  c("A screwball that backs up."),
  c("A screwball just off the corner."),
  c("A screwball that drops below the bat."),
  c("A screwball near the back foot."),
];

// =========== KNUCKLEBALLS ===========
export const KNUCKLEBALLS = [
  c("A knuckleball floating toward the plate."),
  c("A knuckler that dances outside."),
  c("A knuckleball drops in for a strike."),
  c("A knuckler tumbles low."),
  c("A knuckleball with no visible spin."),
  c("A knuckler that darts inside."),
  c("A knuckleball that changes direction twice."),
  c("A knuckler that dives at the last second."),
  c("A knuckleball up and away."),
  c("A knuckler that misses below the zone."),
  c("A floating knuckleball over the plate."),
  c("A knuckler the catcher barely handles."),
  c("A knuckleball that stays high."),
  c("A knuckler with a sudden drop."),
  c("A dancing pitch at the knees."),
  c("A knuckleball that catches the corner."),
  c("A knuckler that nearly gets away."),
  c("A floating pitch that freezes the hitter."),
  c("A knuckleball with a mind of its own."),
  c("A knuckler that moves after it reaches the plate."),
];

// =========== TAKEN FOR STRIKES ===========
export const TAKEN_STRIKES = [
  c("Taken for a strike."),
  c("He watches it cross the plate."),
  c("A called strike on the outside corner."),
  c("A called strike at the knees."),
  c("He takes a fastball for strike one."),
  c("The breaking ball drops in for a strike."),
  c("He takes it right down the middle."),
  c("A strike on the inner half."),
  c("That catches the bottom of the zone."),
  c("The umpire rings up a strike."),
  c("He watches a good pitch go by."),
  c("A strike at the belt."),
  c("The pitch clips the outside edge."),
  c("The umpire gives him the corner."),
  c("A called strike on a close pitch."),
  c("The pitcher steals a strike."),
  c("He freezes on the breaking ball."),
  c("The hitter never offered."),
  c("A strike on the lower edge."),
  c("The count begins with a strike."),
  c("A well-placed pitch for strike one."),
  c("The catcher holds the glove and gets the call."),
  c("A strike just beneath the hands."),
  c("He takes a pitch he may have wanted back."),
  c("The pitcher gets ahead."),
];

// =========== CALLED BALLS ===========
export const CALLED_BALLS = [
  c("Low for ball one."),
  c("Outside for a ball."),
  c("The pitch misses inside."),
  c("High and away."),
  c("The fastball sails high."),
  c("The breaking ball stays outside."),
  c("The pitch drops beneath the zone."),
  c("A little too far inside."),
  c("That misses just off the corner."),
  c("The catcher reaches outside."),
  c("The pitch is nowhere close."),
  c("Ball one, well below the knees."),
  c("The fastball runs off the plate."),
  c("The pitch misses high."),
  c("The curveball bounces in."),
  c("A slider off the outside edge."),
  c("The pitch nearly clips him."),
  c("The catcher has to move his glove."),
  c("The pitch is just a bit low."),
  c("That one misses by inches."),
  c("The umpire does not give him the corner."),
  c("The count begins with a ball."),
  c("The pitch never threatened the strike zone."),
  c("A close pitch called outside."),
  c("The hitter lays off."),
];

// =========== SWINGING STRIKES ===========
export const SWINGING_STRIKES = [
  c("He swings through it."),
  c("A swing and a miss."),
  c("He comes up empty."),
  c("The fastball blows past him."),
  c("He chases the slider."),
  c("The breaking ball fools him."),
  c("He swings over the changeup."),
  c("He cannot catch up to the heater."),
  c("A big swing and nothing there."),
  c("He offers at a pitch in the dirt."),
  c("He reaches and misses."),
  c("The slider disappears beneath the bat."),
  c("He is late on the fastball."),
  c("He is out in front of the changeup."),
  c("The curveball gets him swinging."),
  c("He chases one off the plate."),
  c("The splitter falls beneath his swing."),
  c("He swings beneath the high fastball."),
  c("He waves at the outside pitch."),
  c("The knuckleball dances past him."),
  c("He misses badly."),
  c("The hitter was fooled from the start."),
  c("He could not hold back."),
  c("A defensive swing comes up empty."),
  c("The pitcher changes speeds beautifully."),
];

// =========== FOUL TIPS ===========
export const FOUL_TIPS = [
  c("A foul tip into the catcher's glove."),
  c("He barely gets a piece."),
  c("A sharp foul tip."),
  c("The catcher hangs onto it."),
  c("A foul tip straight back."),
  c("He nicks the fastball."),
  c("The pitch catches the edge of the bat."),
  c("A foul tip off the mask."),
  c("The ball glances off the catcher."),
  c("He just stays alive."),
  c("A tiny piece of the slider."),
  c("A foul tip on a high fastball."),
  c("He gets enough bat to avoid strike three."),
  c("The catcher cannot hold the foul tip."),
  c("A sharp tip rattles the glove."),
  c("The ball goes directly off the bat and back."),
  c("A foul tip with two strikes."),
  c("He brushes the ball into the mitt."),
  c("The pitch barely finds wood."),
  c("A tip that nearly ends the at-bat."),
];

// =========== CHECKED SWINGS ===========
export const CHECKED_SWINGS = [
  c("He checks his swing."),
  c("He holds up in time."),
  c("The appeal goes to first."),
  c("The first-base umpire says no swing."),
  c("The umpire says he went around."),
  c("He could not stop the bat."),
  c("A late check on the breaking ball."),
  c("He starts and holds."),
  c("He nearly chases the slider."),
  c("The bat comes halfway around."),
  c("He asks for an appeal."),
  c("The third-base umpire says he held up."),
  c("The third-base umpire rings him up."),
  c("A close check-swing decision."),
  c("He pulls the bat back just in time."),
  c("The hitter disagrees with the appeal."),
  c("He starts toward the pitch and stops."),
  c("The breaking ball nearly gets him to commit."),
  c("He holds off on a pitch in the dirt."),
  c("The umpire says the wrists broke."),
];

// =========== PITCHES IN THE DIRT ===========
export const DIRT_PITCHES = [
  c("The pitch bounces in front of the plate."),
  c("A breaking ball in the dirt."),
  c("The catcher blocks it."),
  c("The catcher keeps it in front."),
  c("The ball kicks away from the catcher."),
  c("A slider buried in the dirt."),
  c("The pitch skips beneath the glove."),
  c("A curveball bounces to the backstop."),
  c("The catcher drops to both knees."),
  c("The pitch is smothered behind the plate."),
  c("The ball rolls a few feet away."),
  c("The catcher recovers quickly."),
  c("A splitter bounces near home plate."),
  c("The pitch strikes the dirt and changes direction."),
  c("The catcher cannot find it immediately."),
  c("The ball kicks toward the first-base side."),
  c("The pitch bounces toward the third-base side."),
  c("A low pitch handled cleanly."),
  c("The catcher saves a possible wild pitch."),
  c("The runner watches closely from third."),
];

// =========== WILD PITCHES ===========
export const WILD_PITCHES = [
  c("The pitch gets away."),
  c("The ball rolls to the backstop."),
  c("A wild pitch sends the runner ahead."),
  c("The catcher cannot block it."),
  c("The pitch skips past the catcher."),
  c("The runner breaks for second."),
  c("The runner races home."),
  c("The catcher retrieves it near the screen."),
  c("That pitch was far beyond his reach."),
  c("The ball caroms away."),
  c("The runner advances easily."),
  c("The catcher never had a chance."),
  c("The pitch bounces over the catcher."),
  c("A passed ball opens the base."),
  c("The ball slips through the catcher's legs."),
  c("The pitcher and catcher cross signals."),
  c("The runner takes third."),
  c("The tying run moves ninety feet closer."),
  c("A costly pitch gets away."),
  c("The catcher chases the ball toward the dugout."),
];

// =========== BRUSHBACKS & INSIDE PITCHES ===========
export const BRUSHBACKS = [
  c("The pitch drives him off the plate."),
  c("A fastball beneath the chin."),
  c("He leans away from the inside pitch."),
  c("The pitch sends him sprawling backward."),
  c("A heater near the ribs."),
  c("The fastball buzzes him inside."),
  c("He jumps away from the plate."),
  c("A pitch near the hands."),
  c("The catcher sets up inside."),
  c("The pitcher moves him off the plate."),
  c("A fastball up and in."),
  c("The hitter takes a long look toward the mound."),
  c("That pitch was uncomfortably close."),
  c("A hard pitch near the shoulder."),
  c("The batter spins out of the way."),
  c("A warning pitch inside."),
  c("The crowd reacts to that one."),
  c("The umpire steps between them."),
  c("That pitch sends a message."),
  c("The hitter digs back in."),
];

// =========== HIT BY PITCH ===========
export const HIT_BY_PITCH = [
  c("The pitch hits him."),
  c("He is struck on the arm."),
  c("The fastball catches him in the back."),
  c("A breaking ball hits his foot."),
  c("He takes one off the elbow."),
  c("The pitch clips his uniform."),
  c("He is awarded first base."),
  c("The ball catches him near the shoulder."),
  c("He turns and takes it on the hip."),
  c("The pitch hits the protective guard."),
  c("The batter is slow getting up."),
  c("The trainer comes out."),
  c("He tries to shake it off."),
  c("The umpire signals hit by pitch."),
  c("The pitch catches him near the hands."),
  c("He is hit on the lower leg."),
  c("The ball strikes him as he turns away."),
  c("That one will leave a mark."),
  c("He heads toward first base."),
  c("The crowd voices its displeasure."),
];

// =========== PICKOFF LOOKS ===========
export const PICKOFF_LOOKS = [
  c("He checks the runner at first."),
  c("A quick look toward second."),
  c("The runner dives back."),
  c("The pitcher steps off."),
  c("He holds the ball."),
  c("The runner shortens his lead."),
  c("The pitcher stares him back toward the bag."),
  c("A long pause with the runner moving around."),
  c("The catcher flashes a new set of signs."),
  c("The pitcher turns toward first."),
  c("No throw this time."),
  c("The runner edges another step away."),
  c("The pitcher appears concerned with the lead."),
  c("The middle infielders move toward the bag."),
  c("The runner freezes."),
];

// =========== INTENTIONAL WALKS ===========
export const INTENTIONAL_WALKS = [
  c("The catcher stands outside."),
  c("The first intentional ball is delivered."),
  c("The pitcher sends it well off the plate."),
  c("The hitter is being put on intentionally."),
  c("Four wide ones are coming."),
  c("The catcher steps into the opposite batter's box."),
  c("The defense chooses the next hitter."),
  c("The crowd does not approve."),
  c("The batter takes his free pass."),
  c("The pitcher wants no part of him."),
  c("They will set up the force play."),
  c("The winning run is being walked."),
  c("The cleanup hitter is intentionally passed."),
  c("The pitcher completes the intentional walk."),
  c("Now the bases are loaded."),
];

// =========== FOOL THE HITTER ===========
export const FOOL_HITTER = [
  c("He was looking fastball."),
  c("He was far out in front."),
  c("He was late from the beginning."),
  c("The change of speed fooled him."),
  c("The pitch tied him in knots."),
  c("He never recognized the breaking ball."),
  c("He froze on the slider."),
  c("He guessed incorrectly."),
  c("The hitter was completely fooled."),
  c("The pitcher changed speeds beautifully."),
  c("He had no chance on that pitch."),
  c("The breaking ball started in the middle."),
  c("The pitch looked hittable until the final moment."),
  c("He was committed before the ball arrived."),
  c("The pitcher disrupted his timing."),
  c("The hitter's weight was already forward."),
  c("The pitch vanished beneath the swing."),
  c("The fastball arrived sooner than expected."),
  c("The hitter was caught between pitches."),
  c("He could only wave at it."),
];

// =========== MISS THE TARGET ===========
export const MISS_TARGET = [
  c("The catcher wanted it outside."),
  c("The pitch leaks back over the plate."),
  c("The catcher reaches across his body."),
  c("The pitch misses the glove badly."),
  c("That was not the intended location."),
  c("The fastball runs to the wrong side."),
  c("The breaking ball backs up."),
  c("The catcher was set low."),
  c("The pitch remains high."),
  c("The pitcher yanks it inside."),
  c("The ball slips from his hand."),
  c("The catcher has to lunge."),
  c("The pitch sails to the backstop."),
  c("The pitcher misses arm-side."),
  c("The breaking ball hangs over the plate."),
  c("The catcher was set in the dirt."),
  c("The pitch stays in the strike zone."),
  c("The pitcher got away with a mistake."),
  c("The location was poor, but the result was good."),
  c("That pitch nearly became trouble."),
];

// =========== PERFECT LOCATION ===========
export const PERFECT_LOCATION = [
  c("Right on the corner."),
  c("Exactly where the catcher set up."),
  c("A perfectly placed fastball."),
  c("The pitch catches the lower edge."),
  c("He paints the outside corner."),
  c("The ball clips the black."),
  c("A beautiful breaking ball at the knees."),
  c("The pitcher hits his spot."),
  c("The catcher barely moves the glove."),
  c("That is excellent location."),
  c("A fastball under the hands."),
  c("A slider just off the edge."),
  c("The pitch starts in the zone and disappears."),
  c("A changeup at the bottom corner."),
  c("The hitter could do little with that pitch."),
  c("A quality pitch in a dangerous count."),
  c("The pitcher executes perfectly."),
  c("That is difficult to hit even when expected."),
  c("A strike in the smallest possible area."),
  c("The pitch could not have been placed better."),
];

// =========== CROWD & COLOR ===========
export const CROWD_COLOR = [
  c("The crowd wanted that pitch."),
  c("The fans thought it was a strike."),
  c("The hitter disagrees with the call."),
  c("The catcher asks where it missed."),
  c("The pitcher walks behind the mound."),
  c("The umpire remains unmoved."),
  c("The dugout voices its opinion."),
  c("The crowd begins to rumble."),
  c("That was a close pitch."),
  c("The hitter turns away in frustration."),
  c("The pitcher thought he had strike three."),
  c("The catcher holds the glove in place."),
  c("The umpire gives no explanation."),
  c("The fans have seen enough."),
  c("That call will be discussed for a while."),
];

// Master export
export const ALL_PITCH_CALLS = {
  DELIVERY_SETUP,
  FASTBALLS,
  CURVEBALLS,
  SLIDERS,
  CHANGEUPS,
  SINKERS,
  SPLITTERS,
  SCREWBALLS,
  KNUCKLEBALLS,
  TAKEN_STRIKES,
  CALLED_BALLS,
  SWINGING_STRIKES,
  FOUL_TIPS,
  CHECKED_SWINGS,
  DIRT_PITCHES,
  WILD_PITCHES,
  BRUSHBACKS,
  HIT_BY_PITCH,
  PICKOFF_LOOKS,
  INTENTIONAL_WALKS,
  FOOL_HITTER,
  MISS_TARGET,
  PERFECT_LOCATION,
  CROWD_COLOR,
};

// Helper: pick from category (ensures correct call for pitch type)
export function pickPitchCall(category) {
  const pool = ALL_PITCH_CALLS[category];
  if (!pool || pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)].text;
}

// Helper: get multi-line combo for storytelling
export function getPitchCombo(primaryCategory, secondaryCategories = []) {
  const lines = [];
  lines.push(pickPitchCall(primaryCategory));
  for (const cat of secondaryCategories) {
    if (ALL_PITCH_CALLS[cat]) {
      lines.push(pickPitchCall(cat));
    }
  }
  return lines.filter(l => l).join(" ");
}