// Universal batted-ball announcer calls - mixed by contact type and outcome

export const WEAK_CONTACT = [
  'A little dribbler toward third.',
  'A slow roller up the first-base line.',
  'A weak tapper in front of the plate.',
  'A little nubber toward the mound.',
  'A swinging bunt down the third-base side.',
  'A slow trickler toward shortstop.',
  'A soft roller to the right side.',
  'A little tap off the end of the bat.',
  'A weak ground ball toward second.',
  'A dribbler that may stay fair.',
  'A tiny roller near the line.',
  'A softly hit ball in front of home plate.',
  'A little squibber toward first.',
  'A weak tap back to the pitcher.',
  'A ball barely struck off the bat.',
];

export const GROUND_BALLS = [
  'A ground ball to shortstop.',
  'A routine roller to second base.',
  'A grounder toward third.',
  'A two-hopper to the first baseman.',
  'A ground ball right at the shortstop.',
  'A routine play on the left side.',
  'A grounder hit directly to second.',
  'A steady roller toward first.',
  'A ground ball near the bag.',
  'A routine chance for the third baseman.',
  'A ball hit on the ground toward short.',
  'A grounder that should be handled.',
  'A firm two-hopper to second.',
  'A routine roller across the infield.',
  'A ground ball directly at the pitcher.',
  'A ball hit right to the first baseman.',
  'A manageable grounder toward third.',
  'A routine ground ball up the middle.',
  'A slow two-hopper to shortstop.',
  'A ball hit sharply but directly at someone.',
];

export const HARD_GROUND_BALLS = [
  'A screaming ground ball toward third.',
  'A hard smash through the left side.',
  'A sharply hit grounder to short.',
  'A rocket along the ground toward first.',
  'A hard one-hopper to second.',
  'A sizzling ground ball up the middle.',
  'A bullet off the bat toward third base.',
  'A sharply hit ball toward the hole.',
  'A hard grounder that eats up the infielder.',
  'A shot past the pitcher.',
  'A hot smash down the line.',
  'A hard-hit ball toward the right side.',
  'A ground ball struck with authority.',
  'A rocket that stays on the ground.',
  'A sharply hit one-hopper near the bag.',
  'A hard shot that takes a wicked hop.',
  'A ground ball that gets on the infielder quickly.',
  'A scorching smash toward shortstop.',
  'A hot grounder through the middle.',
  'A hard-hit ball that may find the outfield.',
];

export const LINE_DRIVES = [
  'A scorching line drive toward shortstop.',
  'A low liner to second base.',
  'A hard line drive right at the third baseman.',
  'A bullet toward first.',
  'A sinking liner over the mound.',
  'A line shot toward the left side.',
  'A sharp liner headed for short.',
  'A low missile toward second.',
  'A frozen rope at the first baseman.',
  'A hard liner just above the infield.',
  'A screaming line drive through the box.',
  'A line shot near the third-base bag.',
  'A low liner that may carry through.',
  'A sharp drive toward the middle.',
  'A bullet off the bat toward the mound.',
  'A line drive that gets on the fielder quickly.',
  'A hard liner with almost no reaction time.',
  'A rope toward the shortstop.',
  'A vicious line drive toward third.',
  'A low shot at the second baseman.',
];

export const FLY_BALLS_SHALLOW = [
  'A short fly ball into center.',
  'A shallow fly toward left.',
  'A soft fly ball into right.',
  'A little fly ball behind second base.',
  'A fly ball dropping in front of the outfielder.',
  'A shallow drive toward left-center.',
  'A short fly that may fall safely.',
  'A ball lifted into shallow right.',
  'A fly ball caught between the infield and outfield.',
  'A short pop fly toward center.',
  'A shallow fly drifting toward the line.',
  'A little fly ball that forces the outfielder in.',
];

export const FLY_BALLS_ROUTINE = [
  'A fly ball to center field.',
  'A routine fly toward left.',
  'A medium fly ball into right.',
  'A fly ball hit directly at the center fielder.',
  'A routine chance in left field.',
  'A high fly toward straightaway right.',
  'A fly ball with ordinary depth.',
  'A routine outfield play.',
  'A ball lifted toward the warning track.',
  'A medium-depth fly to center.',
];

export const FLY_BALLS_DEEP = [
  'A deep fly ball toward left field.',
  'A towering drive to center.',
  'A high fly headed toward the warning track.',
  'A deep ball toward right-center.',
  'A fly ball carrying toward the wall.',
  'A high drive deep into left.',
  'A long fly ball toward straightaway center.',
  'A deep fly drifting toward the line.',
  'A towering ball headed for the track.',
  'A high fly with the outfielder going back.',
];

export const BLOOPERS_FLARES = [
  'A little blooper into shallow right.',
  'A soft fly ball toward left.',
  'A flare over the second baseman.',
  'A bloop single waiting to happen.',
  'A soft liner into shallow center.',
  'A little parachute behind shortstop.',
  'A dying quail toward right field.',
  'A flare into no-man\'s-land.',
  'A softly hit ball beyond the infield.',
  'A blooper that may fall between three fielders.',
];

export const POP_UPS = [
  'A towering pop-up over the infield.',
  'A light-pole-high pop-up near second.',
  'A high pop fly toward shortstop.',
  'A towering ball straight above home plate.',
  'A mile-high pop-up on the left side.',
  'A high pop that stays in the infield.',
  'A towering infield fly near first base.',
  'A straight-up pop behind the plate.',
  'A high fly ball near the pitcher\'s mound.',
  'A pop-up drifting toward third.',
];

export const GAP_SHOTS = [
  'A drive toward the left-center-field gap.',
  'A shot headed for right-center.',
  'A ball driven between the outfielders.',
  'A hard liner into the alley.',
  'A fly ball splitting the gap.',
  'A line drive headed for open grass.',
  'A drive toward the deepest part of the gap.',
  'A ball hit where neither outfielder may reach it.',
  'A sharp drive between left and center.',
  'A hard liner toward the right-center-field wall.',
];

export const DOWN_THE_LINE = [
  'A hard shot down the third-base line.',
  'A ground ball hugging the first-base line.',
  'A drive headed toward the left-field corner.',
  'A ball sliced down the right-field line.',
  'A sharp grounder inside the bag.',
  'A liner headed for the corner.',
  'A ball pulled hard toward the line.',
  'A drive that may stay fair.',
  'A shot just inside the chalk.',
  'A ground ball racing toward the corner.',
];

export const SINGLES = [
  // Infield hits
  'A slow roller, and he beats the throw to first.',
  'He chops one into the ground and legs it out.',
  'A little tapper turns into an infield hit.',
  'He sends a slow bouncer across the dirt and reaches safely.',
  'The ball dies on the infield, and there is no play.',
  'He beats out a softly hit ground ball.',
  'A high chopper gives him enough time to reach first.',
  'He hustles down the line and turns a routine-looking grounder into a hit.',
  'A weak roller finds just the right spot.',
  'He sends a swinging bunt into open space and reaches safely.',
  'The defense makes the play, but not quickly enough.',
  'He gets jammed, but the ball rolls too slowly for an out.',
  'A soft grounder and good speed produce an infield single.',
  'He chops it off the plate and wins the race to first.',
  'The throw is late, and he has himself an infield hit.',
  'A dribbler stays fair, and he reaches without a throw.',
  'He places a slow roller where no quick play can be made.',
  'The ball takes a difficult hop, and the batter is safe.',
  'He gets down the line in a hurry and beats it out.',
  'A perfectly placed tapper becomes a base hit.',
  'He barely gets the ball out of the dirt, but it is enough.',
  'The defense charges, throws, and still cannot get him.',
  'A little squibber turns into a single.',
  'He catches the defense back and reaches on a slow roller.',
  'The ball stays on the infield, but the batter does not.',
  // Grounders through the infield
  'A ground ball finds its way through for a single.',
  'He shoots a grounder through the infield.',
  'A sharp bouncer gets into the outfield.',
  'He sends one through the open side for a base hit.',
  'The ground ball sneaks between the defenders.',
  'He rolls it through the infield and reaches first.',
  'A clean ground-ball single into the outfield.',
  'He finds a hole with a hard grounder.',
  'The ball skips through before anyone can cut it off.',
  'He pulls a ground ball through for a hit.',
  'A bouncer finds open grass.',
  'He sends a grounder back through the middle.',
  'The ball gets past the infield and into the outfield.',
  'A well-placed ground ball produces a single.',
  'He stays on the pitch and rolls it through.',
  'The defense cannot close the gap in time.',
  'A hard one-hopper finds its way through.',
  'He punches a ground ball into an opening.',
  'The ball hugs the ground and gets into the outfield.',
  'He turns on the pitch and sends it through the infield.',
  'A crisp grounder slips past the reach of the defense.',
  'He finds the seam with a low shot.',
  'The ground ball is just out of reach and rolls through.',
  'He threads one between the defenders for a single.',
  'A sharply hit grounder becomes a clean base hit.',
  // Liners through the infield
  'A line drive shoots through the infield for a single.',
  'He ropes one into the outfield.',
  'A sharp liner finds open grass.',
  'He punches a line drive through for a base hit.',
  'The ball comes off the bat hard and gets through.',
  'He sends a low liner into the outfield.',
  'A clean line-drive single.',
  'He rifles one through the infield.',
  'A hard shot skips into the outfield.',
  'He squares it up and lines it through.',
  'A crisp liner gets past the defense.',
  'He shoots a line drive into an opening.',
  'The ball flashes through before anyone can react.',
  'He sends a frozen rope into the outfield.',
  'A sharp liner finds the gap in the infield.',
  'He drives the pitch on a line for a single.',
  'The ball is hit too hard to be handled.',
  'He lashes one through for a base hit.',
  'A low line drive gets into open space.',
  'He stays inside the pitch and lines it into the outfield.',
  'The defense has no chance on that sharply hit ball.',
  'He sends a bullet through the infield.',
  'A firm line drive produces a clean single.',
  'He barrels it and finds a hole.',
  'A hard liner carries safely into the outfield.',
  // Bloops between the infield and outfield
  'A soft blooper drops in for a single.',
  'He lifts a little flare into open grass.',
  'The ball falls between the converging defenders.',
  'A shallow bloop lands safely.',
  'He drops a soft single just beyond the infield.',
  'A little parachute falls in for a hit.',
  'The ball hangs up, then drops where nobody can reach it.',
  'He gets just enough of it to find open space.',
  'A soft flare lands untouched.',
  'The blooper falls between the defense for a single.',
  'He fights off the pitch and drops it into shallow territory.',
  'A gentle loop finds the grass.',
  'The ball floats beyond one defender and in front of another.',
  'He places a soft single into no-man\'s-land.',
  'A little humpback liner falls safely.',
  'The defense closes in, but the ball drops first.',
  'He flips a soft hit into shallow outfield territory.',
  'A blooping shot lands just out of reach.',
  'He gets jammed, but the ball finds an opening.',
  'A softly hit ball falls between the layers of the defense.',
  'The ball drops in front of the outfield for a base hit.',
  'He serves a little flare into open space.',
  'A weakly hit ball lands in exactly the right spot.',
  'The defense cannot decide who can reach it, and it falls safely.',
  'He drops one over the infield for a single.',
  // Harder-hit balls between the infield and outfield
  'A firm shot lands in front of the outfield for a single.',
  'He drives a low ball into shallow outfield territory.',
  'A hard sinking liner drops safely.',
  'The ball falls in front of the defense and stays a single.',
  'He sends a sharply hit ball into the open grass.',
  'A low drive lands before it can be caught.',
  'He rifles a shot that drops in for a base hit.',
  'A firm liner falls just beyond the infield.',
  'The ball sinks quickly and lands safely.',
  'He drives one into the gap between the defense.',
  'A sharp shot reaches the grass before anyone can close.',
  'He hits it firmly, but low enough to fall in front.',
  'A sinking line drive produces a single.',
  'The ball is hit too sharply to catch, but not far enough for extra bases.',
  'He sends a low laser into shallow territory.',
  'A hard shot drops in front of the outfield.',
  'He lines one into open space and stops at first.',
  'A firm drive gets down quickly for a hit.',
  'The ball carries over the infield and lands safely.',
  'He smokes one into the shallow outfield.',
  'A sharply struck ball finds the grass before the catch can be made.',
  'He drives it through the open space for a single.',
  'A low, hard liner falls safely.',
  'The defense reacts quickly, but the ball is already down.',
  'He hits it on the nose and settles for one base.',
  // Balls near the line or between outfielders - held to a single
  'He sends it toward the gap, but the defense cuts it off quickly.',
  'The ball gets between the outfielders, but not far enough for two.',
  'A shot near the line is played quickly, holding him at first.',
  'He finds open grass, but the ball is returned in a hurry.',
  'A well-placed hit toward the gap produces only a single.',
  'The ball reaches the line, but the defense gets there quickly.',
  'He drives one between the outfielders and has to stop at first.',
  'A sharp hit into the gap is cut off before he can think about second.',
  'The ball lands safely near the line, but the quick recovery holds him.',
  'He sends it into open territory, but the defense closes fast.',
  'A hard single toward the gap, and he stays at first.',
  'The ball gets down between the outfielders, but the return throw is immediate.',
  'He drives one near the line and is held to a single.',
  'A well-hit ball reaches the outfield, but not deeply enough for an extra base.',
  'The defense cuts it off before the batter can make the turn.',
  'He finds the gap, but the ball is played too quickly for two bases.',
  'A sharp shot lands near the line and is returned without delay.',
  'The ball rolls into open grass, but the defense prevents the extra base.',
  'He sends a firm hit between the outfielders and stops at first.',
  'A single into the gap, but no chance to stretch it.',
  'The ball lands safely, and the quick pickup keeps him at first.',
  'He hits it toward the corner, but the defense gets there in time.',
  'A solid shot reaches the outfield, but the runner wisely holds.',
  'The ball finds open space near the line, though the defense limits the damage.',
  'He places it between the outfielders, but the play is made quickly enough to hold him to one.',
];

export const DOUBLES = [
  // Batter stretching a single into a double
  'He rounds first aggressively and beats the throw into second.',
  'He turns the single into a double with an aggressive sprint.',
  'He never slows at first and slides safely into second.',
  'The defense is slow getting the ball back, and he takes the extra base.',
  'He sees an opening and stretches the hit into two bases.',
  'A wide turn at first becomes a hustle double.',
  'He challenges the throw and wins the race to second.',
  'He keeps running and reaches second just ahead of the tag.',
  'What looked like a single becomes a double through pure hustle.',
  'He catches the defense relaxing and takes another ninety feet.',
  'He puts his head down, races for second and makes it safely.',
  'The ball is returned quickly, but not quickly enough.',
  'He takes an aggressive turn and slides in with a double.',
  'He forces the issue and converts the hit into two bases.',
  'The throw is close, but he beats it into second.',
  'He refuses to settle for one base and reaches second safely.',
  'A quick burst out of the box allows him to stretch the play.',
  'He sees the chance for two and takes it.',
  'The defense nearly cuts him down, but he arrives safely.',
  'He races out of the batter\'s box and earns himself a double.',
  'The hit is fielded quickly, but his speed creates the extra base.',
  'He presses the defense and wins a close play at second.',
  'He rounds first at full speed and dives in ahead of the throw.',
  'A routine single becomes an extra-base hit because of aggressive running.',
  'He takes advantage of the slow recovery and reaches second standing.',
  // Hit down the line
  'He shoots the ball down the line for a double.',
  'A sharp drive hugs the line and rolls into the corner.',
  'He pulls it inside the line and cruises into second.',
  'The ball skips past the defense and races down the line.',
  'He sends a hard shot into the corner for two bases.',
  'A fair ball down the line produces an easy double.',
  'He turns on the pitch and drives it inside the chalk.',
  'The ball lands fair and rattles toward the corner.',
  'He slices one down the line and reaches second comfortably.',
  'A line drive stays fair and rolls deep into the outfield.',
  'He drops one just inside the line for extra bases.',
  'The ball kicks away near the corner, and he takes second.',
  'He drills the pitch down the line for a stand-up double.',
  'A sharp shot finds the chalk and keeps rolling.',
  'He hooks one inside the line and into the corner.',
  'The ball stays fair by a narrow margin and results in two bases.',
  'He rips it down the line and races into second.',
  'A hard grounder gets past the defense and heads for the corner.',
  'He places the ball perfectly inside the line.',
  'The hit skips along the line and gives him plenty of time for second.',
  'He lashes one fair down the side for a double.',
  'The ball lands near the line and continues into deep territory.',
  'He turns on the inside pitch and drives it into the corner.',
  'A fair ball just inside the line becomes an extra-base hit.',
  'He sends it down the chalk and pulls into second with a double.',
  // Hit between outfielders - does not reach the wall
  'He drives it between the outfielders for a double.',
  'The ball lands in the gap, and he races into second.',
  'A well-placed shot splits the defense.',
  'He finds open grass between the outfielders for two bases.',
  'The ball drops into the gap but is cut off before the wall.',
  'He drives one into open space and reaches second standing.',
  'A sharp hit lands between the converging defenders.',
  'The ball gets down in the gap and rolls far enough for a double.',
  'He threads one between the outfielders for extra bases.',
  'A firm drive finds the open part of the outfield.',
  'The defense closes quickly, but he has time to reach second.',
  'He sends one into the alley and takes two bases.',
  'A low drive splits the outfielders and results in a double.',
  'The ball lands safely in the gap and is recovered before reaching the wall.',
  'He drives it where nobody can make the catch.',
  'A shot into open territory gives him an easy two-base hit.',
  'He finds the seam between the outfielders.',
  'The ball gets through the gap, but the defense cuts it off quickly.',
  'He lines one into the alley and cruises into second.',
  'A clean gapper produces two bases.',
  'He drives it between the defenders and beats the return throw.',
  'The ball lands in open grass and rolls long enough for a double.',
  'A hard shot splits the defense without reaching the fence.',
  'He finds the gap and takes second without a play.',
  'The ball lands between the outfielders, and he settles for two.',
  // Hit between outfielders - reaches the wall
  'He drives it between the outfielders and all the way to the wall.',
  'The ball splits the defense and rolls to the fence.',
  'He sends one deep into the gap for a double.',
  'The ball reaches the wall before anyone can cut it off.',
  'He drives it into the alley and cruises into second.',
  'A hard gapper rolls all the way to the fence.',
  'The ball gets between the outfielders and keeps going.',
  'He finds the deepest part of the gap for two bases.',
  'A sharp drive splits the defense and reaches the wall.',
  'He sends it racing through open territory and into the fence.',
  'The ball rolls untouched to the wall, and he reaches second easily.',
  'He drives one into the gap and has time to admire the double.',
  'A well-struck shot reaches the fence between the outfielders.',
  'The defense cannot cut it off before it reaches the wall.',
  'He drills it into the alley for a stand-up double.',
  'The ball gets all the way to the wall before being retrieved.',
  'He splits the outfielders with a hard two-base hit.',
  'A deep drive into the gap gives him an easy double.',
  'The ball races toward the wall, and he rounds first without hesitation.',
  'He sends a gap shot to the fence and pulls into second.',
  'The ball lands between the defenders and rolls deep into the outfield.',
  'He finds open space, and the ball carries all the way to the wall.',
  'A deep gapper leaves the defense chasing it to the fence.',
  'He drives it where the outfielders cannot reach it, and it rolls to the wall.',
  'The ball splits the defense cleanly and produces a comfortable double.',
  // Hit over an outfielder\'s head - reaches the wall
  'He drives it over the outfielder\'s head and to the wall.',
  'The ball sails beyond the defender and bounces against the fence.',
  'He gets it over the defense for a double.',
  'A deep drive clears the outfielder and reaches the wall.',
  'The ball carries beyond the defender\'s reach and rolls to the fence.',
  'He sends one over the outfielder\'s head for two bases.',
  'The defender retreats, but the ball gets over him.',
  'A long drive lands behind the outfielder and reaches the wall.',
  'He lifts it over the defense and races into second.',
  'The ball clears the outfielder by a few feet and keeps rolling.',
  'He drives one deep enough to get beyond the defense.',
  'The outfielder turns and runs, but the ball lands behind him.',
  'A well-hit drive sails overhead and reaches the fence.',
  'He sends the defense racing back, but the ball gets past.',
  'The ball lands beyond the outfielder and rolls to the wall.',
  'He drives it over the defense for a stand-up double.',
  'A deep shot carries farther than the outfielder expected.',
  'The ball gets over the outfielder\'s glove and reaches the fence.',
  'He sends one well over the defender and into deep territory.',
  'The outfielder misjudges the carry, and the ball sails overhead.',
  'A long drive gets beyond the defense and rolls to the wall.',
  'He lifts one over the outfielder for an extra-base hit.',
  'The ball clears the defense and gives him plenty of time for second.',
  'He drives it farther than the outfielder can retreat.',
  'The ball sails overhead, reaches the wall and produces a double.',
  // Ball hits the wall on the fly or line drive
  'He drives it off the wall for a double.',
  'The ball slams against the fence and stays in play.',
  'A hard drive hits the wall on the fly.',
  'He sends a line drive ringing off the fence.',
  'The ball crashes into the wall, and he races into second.',
  'He nearly gets it out, but settles for a double off the wall.',
  'A deep drive strikes the fence and caroms back into play.',
  'He drills one off the wall for extra bases.',
  'The ball hits high off the fence and stays in the park.',
  'He sends a rocket into the wall and reaches second standing.',
  'A long line drive bangs off the fence.',
  'He puts a charge into it, but the wall keeps it in the park.',
  'The ball strikes the wall on the fly and kicks back toward the field.',
  'He drives it deep, and the fence turns it into a double.',
  'A hard shot rattles off the wall.',
  'He comes within a few feet of a home run and settles for two.',
  'The ball smacks against the fence and drops into play.',
  'He sends a screaming drive off the wall.',
  'A deep liner reaches the fence before touching the ground.',
  'The ball caroms sharply off the wall, but he stops at second.',
  'He hits it about as far as possible without leaving the park.',
  'A towering drive bangs off the fence for a double.',
  'The wall denies the home run but cannot prevent the extra-base hit.',
  'He crushes it off the fence and cruises into second.',
  'The ball strikes the wall with authority, and he has himself a double.',
];

export const TRIPLES = [
  // Batter stretching a double into a triple
  'He rounds second aggressively and races safely into third.',
  'He turns the double into a triple with pure hustle.',
  'He never slows at second and beats the throw to third.',
  'The defense is slow getting the ball back, and he takes the extra base.',
  'He sees a chance for three and takes it.',
  'A wide turn around second becomes a hustle triple.',
  'He challenges the throw and wins the race to third.',
  'He keeps running and slides in just ahead of the tag.',
  'What looked like a double becomes a triple through aggressive baserunning.',
  'He catches the defense relaxing and takes another ninety feet.',
  'He puts his head down, races for third and makes it safely.',
  'The relay is close, but not close enough.',
  'He takes an aggressive turn and dives into third with a triple.',
  'He forces the issue and converts the hit into three bases.',
  'The throw arrives late, and he is safely into third.',
  'He refuses to settle for two and takes the extra base.',
  'A quick burst around second gives him the triple.',
  'He sees the opening and never hesitates.',
  'The defense nearly cuts him down, but he beats the tag.',
  'He races out of second and earns himself a triple.',
  'The ball is retrieved quickly, but his speed creates the extra base.',
  'He presses the defense and wins a close play at third.',
  'He rounds second at full speed and slides in safely.',
  'A routine double becomes a triple because of aggressive running.',
  'He takes advantage of the slow recovery and reaches third standing.',
  // Ball splits the outfielders and reaches the wall
  'He drives it between the outfielders and all the way to the wall.',
  'The ball splits the defense and rolls to the fence.',
  'He sends one deep into the gap and races for third.',
  'The ball reaches the wall before anyone can cut it off.',
  'He drives it into the alley and keeps running.',
  'A hard gapper rolls all the way to the fence.',
  'The ball gets between the outfielders and keeps going.',
  'He finds the deepest part of the gap and takes three bases.',
  'A sharp drive splits the defense and reaches the wall.',
  'He sends it racing through open territory and into the fence.',
  'The ball rolls untouched to the wall, and he heads for third.',
  'He drives one into the gap and never considers stopping at second.',
  'A well-struck shot reaches the fence between the outfielders.',
  'The defense cannot cut it off before it reaches the wall.',
  'He drills it into the alley and cruises into third.',
  'The ball gets all the way to the wall before being retrieved.',
  'He splits the outfielders with a three-base hit.',
  'A deep drive into the gap gives him plenty of time for third.',
  'The ball races toward the wall, and he rounds second without hesitation.',
  'He sends a gap shot to the fence and pulls into third.',
  'The ball lands between the defenders and rolls deep into the outfield.',
  'He finds open space, and the ball carries all the way to the wall.',
  'A deep gapper leaves the defense chasing it to the fence.',
  'He drives it where nobody can reach it and races into third.',
  'The ball splits the defense cleanly and produces a stand-up triple.',
  // Ball over an outfielder\'s head and to the wall
  'He drives it over the outfielder\'s head and all the way to the wall.',
  'The ball sails beyond the defender and bounces toward the fence.',
  'He gets it over the defense and races into third.',
  'A deep drive clears the outfielder and reaches the wall.',
  'The ball carries beyond the defender\'s reach and rolls to the fence.',
  'He sends one over the outfielder\'s head for three bases.',
  'The defender retreats, but the ball gets over him.',
  'A long drive lands behind the outfielder and reaches the wall.',
  'He lifts it over the defense and never slows around second.',
  'The ball clears the outfielder by a few feet and keeps rolling.',
  'He drives one deep enough to get beyond the defense.',
  'The outfielder turns and runs, but the ball lands behind him.',
  'A well-hit drive sails overhead and reaches the fence.',
  'He sends the defense racing back, but the ball gets past.',
  'The ball lands beyond the outfielder and rolls to the wall.',
  'He drives it over the defense for a stand-up triple.',
  'A deep shot carries farther than the outfielder expected.',
  'The ball gets over the glove and reaches the fence.',
  'He sends one well over the defender and into deep territory.',
  'The outfielder misjudges the carry, and the ball sails overhead.',
  'A long drive gets beyond the defense and rolls to the wall.',
  'He lifts one over the outfielder and races into third.',
  'The ball clears the defense and gives him time for three.',
  'He drives it farther than the outfielder can retreat.',
  'The ball sails overhead, reaches the wall and produces a triple.',
  // Ball bounces off the wall and back past the outfielder
  'The ball hits the wall and kicks back past the outfielder.',
  'It caroms off the fence and rolls away from the defense.',
  'The ball strikes the wall, takes a wild bounce and gets away.',
  'He drives it off the fence, and the rebound skips past the outfielder.',
  'The ball bangs off the wall and shoots back toward the field.',
  'A strange carom sends the ball rolling away, and he races for third.',
  'The wall gives the defense a bad bounce, and the runner takes advantage.',
  'The ball strikes the fence and ricochets past the outfielder.',
  'He gets a fortunate carom and never slows around second.',
  'The rebound off the wall turns the play into a triple.',
  'The ball bounces off the fence and skips into open space.',
  'A hard carom leaves the defense chasing it back toward the field.',
  'The ball hits the wall and takes off in the opposite direction.',
  'He drives it deep, and the rebound carries past the outfielder.',
  'The fence sends the ball bouncing away, and he heads for third.',
  'A wicked carom off the wall gives him three bases.',
  'The ball strikes the wall and rolls beyond the defense\'s reach.',
  'The outfielder plays the wall, but the rebound gets past.',
  'He benefits from a wild bounce and races safely into third.',
  'The ball ricochets sharply off the fence and away from the play.',
  'A tricky rebound off the wall turns extra bases into a triple.',
  'The ball bangs off the fence and skips beyond the outfielder.',
  'The wall sends it back toward the infield, but away from the defense.',
  'He keeps running as the carom rolls into open territory.',
  'The ball takes a wild bounce off the wall, and he arrives at third standing.',
];

export const HOME_RUNS = [
  // Harry Caray (Cubs) signature
  'It might be! It could be! It is! Holy cow!',
  'There\'s a drive! Way back! It might be! It could be! It is!',
  'Holy cow! What a shot!',
  'That ball is gone!',
  'A home run for the Cubs!',
  // Vin Scully (Dodgers) signature
  'She is gone!',
  'A high drive into deep left field-she is gone!',
  'He hit it a mile.',
  'Gone-and the Dodgers take the lead.',
  'That ball is carrying, carrying-and gone.',
  'Forget it. That one is out of here.',
  // Ernie Harwell (Tigers) signature
  'That ball is long gone!',
  'There\'s a long drive! That ball is long gone!',
  'He stood there like the house by the side of the road and watched it go by.',
  'That one is headed for the upper deck!',
  'A two-run homer, and the Tigers have the lead.',
  'He hit that one where nobody could catch it.',
  // Bob Uecker (Brewers) signature
  'Get up! Get up! Get outta here! Gone!',
  'Get up! Get outta here-and gone!',
  'That one is back-and it is gone!',
  'He got all of that one!',
  'Way back! Goodbye!',
  'That ball will not be coming back.',
  // Harry Kalas (Phillies) signature
  'That ball is outta here!',
  'Long drive! That ball is outta here!',
  'It is gone! A home run!',
  'Deep to left field-outta here!',
  'He has just tied this ballgame!',
  'That ball is well hit, and it is outta here!',
  // Dave Niehaus (Mariners) signature
  'Fly, fly away!',
  'That ball will fly, fly away!',
  'A deep drive-and goodbye baseball!',
  'That one is gone!',
  'My, oh my! What a shot!',
  'He sends it into the seats!',
  // Ken Harrelson (White Sox) signature
  'You can put it on the board-yes!',
  'You can put it on the booooard-yes!',
  'Stretch! Stretch! Get on back there!',
  'Mercy!',
  'He absolutely crushed it!',
  // Jerry Coleman (Padres) signature
  'Oh, Doctor!',
  'Ball going! Ball gone!',
  'Oh, Doctor! What a drive!',
  'You can hang a star on that baby!',
  'That one is headed out of here!',
  'A tremendous home run!',
  // Phil Rizzuto (Yankees) signature
  'Holy cow!',
  'There it goes! Deep to left!',
  'Holy cow, did he hit that one!',
  'Unbelievable! A home run!',
  // Chuck Thompson (Orioles) signature
  'Ain\'t the beer cold!',
  'Go to war, Miss Agnes!',
  'That ball is out of here!',
  'He hit that one a country mile!',
  'The Orioles have themselves a home run!',
  // Denny Matthews (Royals) signature
  'That ball is gone.',
  'A home run for George Brett.',
  'He hit it well, and it is out of here.',
  'The Royals have the lead.',
  'That one clears the wall.',
  'A two-run home run, and Kansas City moves in front.',
];

export function getRandomCall(arr) {
  if (!arr || arr.length === 0) return 'A ball is put in play.';
  return arr[Math.floor(Math.random() * arr.length)];
}

export function getBattedBallCallByType(resultType) {
   const type = resultType?.toLowerCase() || 'single';

   if (type === 'homerun') return getRandomCall(HOME_RUNS);
   if (type === 'triple') return getRandomCall(TRIPLES);
   if (type === 'double') return getRandomCall(DOUBLES);
   if (type === 'single') return getRandomCall(SINGLES);
   if (type === 'flyout' || type === 'lineout') return getRandomCall(LINE_DRIVES);
   if (type === 'popout') return getRandomCall(POP_UPS);
   if (type === 'groundout') return getRandomCall(GROUND_BALLS);

   return getRandomCall(GROUND_BALLS); // fallback
}