// Universal pitch-to-the-plate calls - varied, non-repetitive announcer language
// Mixed by pitch type, result, and location

export const PITCH_DELIVERY = [
  'The pitcher comes set.',
  'He checks the runner.',
  'He looks toward first.',
  'He glances back at second.',
  'He takes a long look toward home.',
  'He works from the stretch.',
  'He begins his delivery.',
  'He rocks and fires.',
  'He lifts the leg and comes home.',
  'He turns and delivers.',
  'He winds and throws.',
  'He kicks and fires.',
  'He brings it to the plate.',
  'Here comes the pitch.',
  'The pitch is on the way.',
  'He deals.',
  'He fires home.',
  'He comes over the top.',
  'He drops down and delivers.',
  'He reaches back and throws.',
  'He gathers himself and comes home.',
  'He pauses at the belt.',
  'He takes a breath and delivers.',
  'He comes set at the letters.',
  'He steps toward the plate.',
  'He drives off the rubber.',
  'He works quickly and fires.',
  'He wastes little time.',
  'He holds the ball a moment longer.',
  'He finally comes home.',
];

export const FASTBALLS = [
  'Fastball over the plate.',
  'A fastball at the knees.',
  'A heater on the outside corner.',
  'A fastball up and away.',
  'A fastball down and in.',
  'A high fastball.',
  'A low fastball.',
  'A fastball just off the plate.',
  'A heater at the letters.',
  'A fastball on the black.',
  'A fastball catches the corner.',
  'A fastball misses outside.',
  'A fastball runs inside.',
  'A fastball sails high.',
  'A fastball drops below the zone.',
  'A straight fastball down the middle.',
  'A fastball at the belt.',
  'A heater beneath the hands.',
  'A fastball near the chin.',
  'A fastball on the inner half.',
  'A fastball on the outer half.',
  'A rising fastball above the zone.',
  'A fastball with late life.',
  'A lively fastball at the knees.',
  'A hard fastball away.',
  'A firm fastball inside.',
  'A fastball that tails away.',
  'A fastball that runs back over the plate.',
  'A fastball that stays high.',
  'A fastball that misses by inches.',
  'A heater on the lower edge.',
  'A fastball painted on the outside corner.',
  'A fastball buried beneath the zone.',
  'A fastball that rides up and in.',
  'A fastball at the top of the zone.',
  'A fastball near the outside edge.',
  'A fastball that catches too much plate.',
  'A fastball right where the catcher wanted it.',
  'A fastball that misses the target.',
  'A fastball with plenty behind it.',
];

export const CURVEBALLS = [
  'A curveball drops in for a strike.',
  'A breaking ball at the knees.',
  'A curveball bends outside.',
  'A curveball misses low.',
  'A sharp curve over the plate.',
  'A slow curveball taken for a strike.',
  'A curveball that hangs.',
  'A breaking ball that dives below the zone.',
  'A curveball sweeps across the plate.',
  'A big breaking ball outside.',
  'A curveball that catches the corner.',
  'A slow breaker inside.',
  'A curveball that starts high and drops.',
  'A breaking pitch at the bottom of the zone.',
  'A curveball buried in the dirt.',
  'A curveball that never breaks.',
  'A hanging curve over the middle.',
  'A curveball that freezes the hitter.',
  'A slow curve that steals a strike.',
  'A sharp breaker under the hands.',
  'A curveball that sweeps away.',
  'A breaking ball that backs up.',
  'A curveball that slips off the plate.',
  'A big looping curve.',
  'A tight-breaking curveball.',
  'A curveball with plenty of depth.',
  'A breaking pitch that falls off the table.',
  'A curveball that drops beneath the bat.',
  'A slow breaker just outside.',
  'A curveball that clips the lower corner.',
];

export const SLIDERS = [
  'A slider down and away.',
  'A slider on the outside corner.',
  'A slider misses off the plate.',
  'A slider beneath the zone.',
  'A sharp slider at the knees.',
  'A slider that sweeps away.',
  'A slider that backs up inside.',
  'A hanging slider over the plate.',
  'A slider near the back foot.',
  'A slider that catches the corner.',
  'A slider that just misses.',
  'A slider with late movement.',
  'A slider buried in the dirt.',
  'A slider that runs beneath the bat.',
  'A tight slider outside.',
  'A slider on the lower edge.',
  'A slider that stays up.',
  'A slider that spins over the middle.',
  'A slider that starts in and breaks away.',
  'A slider that freezes him.',
  'A slider that gets too much plate.',
  'A sweeping slider across the zone.',
  'A slider that dives at the last moment.',
  'A slider that never reaches the plate.',
  'A slider off the end of the plate.',
  'A hard slider beneath the hands.',
  'A slider that moves sharply to the glove side.',
  'A slider that breaks into the hitter.',
  'A slider that misses low and away.',
  'A slider perfectly located.',
];

export const CHANGEUPS = [
  'A changeup down and away.',
  'A changeup taken for a strike.',
  'A slow change beneath the zone.',
  'A changeup that fades outside.',
  'A changeup at the knees.',
  'A changeup that stays high.',
  'A changeup over the middle.',
  'A changeup that dies before the plate.',
  'A changeup that fools him badly.',
  'A changeup on the outer half.',
  'A changeup near the bottom edge.',
  'A changeup that slips beneath the bat.',
  'A soft change outside.',
  'A changeup with late fade.',
  'A changeup that runs away from the hitter.',
  'A changeup left up in the zone.',
  'A changeup that catches too much plate.',
  'A changeup just off the corner.',
  'A changeup buried low.',
  'A changeup that pulls the hitter forward.',
  'A changeup that looks like a fastball early.',
  'A changeup that arrives much later.',
  'A changeup that floats over the plate.',
  'A changeup beneath the hands.',
  'A changeup perfectly spotted away.',
];

export const SWINGING_STRIKES = [
  'He swings through it.',
  'A swing and a miss.',
  'He comes up empty.',
  'The fastball blows past him.',
  'He chases the slider.',
  'The breaking ball fools him.',
  'He swings over the changeup.',
  'He cannot catch up to the heater.',
  'A big swing and nothing there.',
  'He offers at a pitch in the dirt.',
  'He reaches and misses.',
  'The slider disappears beneath the bat.',
  'He is late on the fastball.',
  'He is out in front of the changeup.',
  'The curveball gets him swinging.',
  'He chases one off the plate.',
  'The splitter falls beneath his swing.',
  'He swings beneath the high fastball.',
  'He waves at the outside pitch.',
  'The knuckleball dances past him.',
  'He misses badly.',
  'The hitter was fooled from the start.',
  'He could not hold back.',
  'A defensive swing comes up empty.',
  'The pitcher changes speeds beautifully.',
];

export const CALLED_STRIKES = [
  'Taken for a strike.',
  'He watches it cross the plate.',
  'A called strike on the outside corner.',
  'A called strike at the knees.',
  'He takes a fastball for strike one.',
  'The breaking ball drops in for a strike.',
  'He takes it right down the middle.',
  'A strike on the inner half.',
  'That catches the bottom of the zone.',
  'The umpire rings up a strike.',
  'He watches a good pitch go by.',
  'A strike at the belt.',
  'The pitch clips the outside edge.',
  'The umpire gives him the corner.',
  'A called strike on a close pitch.',
  'The pitcher steals a strike.',
  'He freezes on the breaking ball.',
  'The hitter never offered.',
  'A strike on the lower edge.',
  'The count begins with a strike.',
  'A well-placed pitch for strike one.',
  'The catcher holds the glove and gets the call.',
  'A strike just beneath the hands.',
  'He takes a pitch he may have wanted back.',
  'The pitcher gets ahead.',
];

export const CALLED_BALLS = [
  'Low for ball one.',
  'Outside for a ball.',
  'The pitch misses inside.',
  'High and away.',
  'The fastball sails high.',
  'The breaking ball stays outside.',
  'The pitch drops beneath the zone.',
  'A little too far inside.',
  'That misses just off the corner.',
  'The catcher reaches outside.',
  'The pitch is nowhere close.',
  'Ball one, well below the knees.',
  'The fastball runs off the plate.',
  'The pitch misses high.',
  'The curveball bounces in.',
  'A slider off the outside edge.',
  'The pitch nearly clips him.',
  'The catcher has to move his glove.',
  'The pitch is just a bit low.',
  'That one misses by inches.',
  'The umpire does not give him the corner.',
  'The count begins with a ball.',
  'The pitch never threatened the strike zone.',
  'A close pitch called outside.',
  'The hitter lays off.',
];

export const HIT_BY_PITCH = [
  'The pitch hits him.',
  'He is struck on the arm.',
  'The fastball catches him in the back.',
  'A breaking ball hits his foot.',
  'He takes one off the elbow.',
  'The pitch clips his uniform.',
  'He is awarded first base.',
  'The ball catches him near the shoulder.',
  'He turns and takes it on the hip.',
  'The pitch hits the protective guard.',
  'The batter is slow getting up.',
  'The trainer comes out.',
  'He tries to shake it off.',
  'The umpire signals hit by pitch.',
  'The pitch catches him near the hands.',
  'He is hit on the lower leg.',
  'The ball strikes him as he turns away.',
  'That one will leave a mark.',
  'He heads toward first base.',
  'The crowd voices its displeasure.',
];

export function getRandomCall(arr) {
  if (!arr || arr.length === 0) return 'The pitch is thrown.';
  return arr[Math.floor(Math.random() * arr.length)];
}

export function getPitchCallsByType(pitchType) {
  const name = pitchType?.name?.toLowerCase() || 'fastball';
  
  if (name.includes('fastball') || name.includes('heater') || name.includes('four-seam')) return FASTBALLS;
  if (name.includes('curve')) return CURVEBALLS;
  if (name.includes('slider')) return SLIDERS;
  if (name.includes('change')) return CHANGEUPS;
  if (name.includes('sinker') || name.includes('two-seam')) return FASTBALLS;
  if (name.includes('split') || name.includes('fork')) return CURVEBALLS;
  
  return FASTBALLS; // fallback
}