// Universal batted-ball announcer calls — mixed by contact type and outcome

export const WEAK_CONTACT = [
  'A little dribbler toward third.',
  'A slow roller up the first-base line.',
  'A weak tapper in front of the plate.',
  'A little nubber toward the mound.',
  'A swinging bunt down the third-base side.',
  'A slow trickler toward shortstop.',
  'A soft roller to the right side.',
  'A little tap off the end of the bat.',
  'A weak ground ball toward second.',
  'A dribbler that may stay fair.',
  'A tiny roller near the line.',
  'A softly hit ball in front of home plate.',
  'A little squibber toward first.',
  'A weak tap back to the pitcher.',
  'A ball barely struck off the bat.',
];

export const GROUND_BALLS = [
  'A ground ball to shortstop.',
  'A routine roller to second base.',
  'A grounder toward third.',
  'A two-hopper to the first baseman.',
  'A ground ball right at the shortstop.',
  'A routine play on the left side.',
  'A grounder hit directly to second.',
  'A steady roller toward first.',
  'A ground ball near the bag.',
  'A routine chance for the third baseman.',
  'A ball hit on the ground toward short.',
  'A grounder that should be handled.',
  'A firm two-hopper to second.',
  'A routine roller across the infield.',
  'A ground ball directly at the pitcher.',
  'A ball hit right to the first baseman.',
  'A manageable grounder toward third.',
  'A routine ground ball up the middle.',
  'A slow two-hopper to shortstop.',
  'A ball hit sharply but directly at someone.',
];

export const HARD_GROUND_BALLS = [
  'A screaming ground ball toward third.',
  'A hard smash through the left side.',
  'A sharply hit grounder to short.',
  'A rocket along the ground toward first.',
  'A hard one-hopper to second.',
  'A sizzling ground ball up the middle.',
  'A bullet off the bat toward third base.',
  'A sharply hit ball toward the hole.',
  'A hard grounder that eats up the infielder.',
  'A shot past the pitcher.',
  'A hot smash down the line.',
  'A hard-hit ball toward the right side.',
  'A ground ball struck with authority.',
  'A rocket that stays on the ground.',
  'A sharply hit one-hopper near the bag.',
  'A hard shot that takes a wicked hop.',
  'A ground ball that gets on the infielder quickly.',
  'A scorching smash toward shortstop.',
  'A hot grounder through the middle.',
  'A hard-hit ball that may find the outfield.',
];

export const LINE_DRIVES = [
  'A scorching line drive toward shortstop.',
  'A low liner to second base.',
  'A hard line drive right at the third baseman.',
  'A bullet toward first.',
  'A sinking liner over the mound.',
  'A line shot toward the left side.',
  'A sharp liner headed for short.',
  'A low missile toward second.',
  'A frozen rope at the first baseman.',
  'A hard liner just above the infield.',
  'A screaming line drive through the box.',
  'A line shot near the third-base bag.',
  'A low liner that may carry through.',
  'A sharp drive toward the middle.',
  'A bullet off the bat toward the mound.',
  'A line drive that gets on the fielder quickly.',
  'A hard liner with almost no reaction time.',
  'A rope toward the shortstop.',
  'A vicious line drive toward third.',
  'A low shot at the second baseman.',
];

export const FLY_BALLS_SHALLOW = [
  'A short fly ball into center.',
  'A shallow fly toward left.',
  'A soft fly ball into right.',
  'A little fly ball behind second base.',
  'A fly ball dropping in front of the outfielder.',
  'A shallow drive toward left-center.',
  'A short fly that may fall safely.',
  'A ball lifted into shallow right.',
  'A fly ball caught between the infield and outfield.',
  'A short pop fly toward center.',
  'A shallow fly drifting toward the line.',
  'A little fly ball that forces the outfielder in.',
];

export const FLY_BALLS_ROUTINE = [
  'A fly ball to center field.',
  'A routine fly toward left.',
  'A medium fly ball into right.',
  'A fly ball hit directly at the center fielder.',
  'A routine chance in left field.',
  'A high fly toward straightaway right.',
  'A fly ball with ordinary depth.',
  'A routine outfield play.',
  'A ball lifted toward the warning track.',
  'A medium-depth fly to center.',
];

export const FLY_BALLS_DEEP = [
  'A deep fly ball toward left field.',
  'A towering drive to center.',
  'A high fly headed toward the warning track.',
  'A deep ball toward right-center.',
  'A fly ball carrying toward the wall.',
  'A high drive deep into left.',
  'A long fly ball toward straightaway center.',
  'A deep fly drifting toward the line.',
  'A towering ball headed for the track.',
  'A high fly with the outfielder going back.',
];

export const BLOOPERS_FLARES = [
  'A little blooper into shallow right.',
  'A soft fly ball toward left.',
  'A flare over the second baseman.',
  'A bloop single waiting to happen.',
  'A soft liner into shallow center.',
  'A little parachute behind shortstop.',
  'A dying quail toward right field.',
  'A flare into no-man\'s-land.',
  'A softly hit ball beyond the infield.',
  'A blooper that may fall between three fielders.',
];

export const POP_UPS = [
  'A towering pop-up over the infield.',
  'A light-pole-high pop-up near second.',
  'A high pop fly toward shortstop.',
  'A towering ball straight above home plate.',
  'A mile-high pop-up on the left side.',
  'A high pop that stays in the infield.',
  'A towering infield fly near first base.',
  'A straight-up pop behind the plate.',
  'A high fly ball near the pitcher\'s mound.',
  'A pop-up drifting toward third.',
];

export const GAP_SHOTS = [
  'A drive toward the left-center-field gap.',
  'A shot headed for right-center.',
  'A ball driven between the outfielders.',
  'A hard liner into the alley.',
  'A fly ball splitting the gap.',
  'A line drive headed for open grass.',
  'A drive toward the deepest part of the gap.',
  'A ball hit where neither outfielder may reach it.',
  'A sharp drive between left and center.',
  'A hard liner toward the right-center-field wall.',
];

export const DOWN_THE_LINE = [
  'A hard shot down the third-base line.',
  'A ground ball hugging the first-base line.',
  'A drive headed toward the left-field corner.',
  'A ball sliced down the right-field line.',
  'A sharp grounder inside the bag.',
  'A liner headed for the corner.',
  'A ball pulled hard toward the line.',
  'A drive that may stay fair.',
  'A shot just inside the chalk.',
  'A ground ball racing toward the corner.',
];

export const TRIPLES = [
  // Batter stretching a double into a triple
  'He rounds second aggressively and races safely into third.',
  'He turns the double into a triple with pure hustle.',
  'He never slows at second and beats the throw to third.',
  'The defense is slow getting the ball back, and he takes the extra base.',
  'He sees a chance for three and takes it.',
  'A wide turn around second becomes a hustle triple.',
  'He challenges the throw and wins the race to third.',
  'He keeps running and slides in just ahead of the tag.',
  'What looked like a double becomes a triple through aggressive baserunning.',
  'He catches the defense relaxing and takes another ninety feet.',
  'He puts his head down, races for third and makes it safely.',
  'The relay is close, but not close enough.',
  'He takes an aggressive turn and dives into third with a triple.',
  'He forces the issue and converts the hit into three bases.',
  'The throw arrives late, and he is safely into third.',
  'He refuses to settle for two and takes the extra base.',
  'A quick burst around second gives him the triple.',
  'He sees the opening and never hesitates.',
  'The defense nearly cuts him down, but he beats the tag.',
  'He races out of second and earns himself a triple.',
  'The ball is retrieved quickly, but his speed creates the extra base.',
  'He presses the defense and wins a close play at third.',
  'He rounds second at full speed and slides in safely.',
  'A routine double becomes a triple because of aggressive running.',
  'He takes advantage of the slow recovery and reaches third standing.',
  // Ball splits the outfielders and reaches the wall
  'He drives it between the outfielders and all the way to the wall.',
  'The ball splits the defense and rolls to the fence.',
  'He sends one deep into the gap and races for third.',
  'The ball reaches the wall before anyone can cut it off.',
  'He drives it into the alley and keeps running.',
  'A hard gapper rolls all the way to the fence.',
  'The ball gets between the outfielders and keeps going.',
  'He finds the deepest part of the gap and takes three bases.',
  'A sharp drive splits the defense and reaches the wall.',
  'He sends it racing through open territory and into the fence.',
  'The ball rolls untouched to the wall, and he heads for third.',
  'He drives one into the gap and never considers stopping at second.',
  'A well-struck shot reaches the fence between the outfielders.',
  'The defense cannot cut it off before it reaches the wall.',
  'He drills it into the alley and cruises into third.',
  'The ball gets all the way to the wall before being retrieved.',
  'He splits the outfielders with a three-base hit.',
  'A deep drive into the gap gives him plenty of time for third.',
  'The ball races toward the wall, and he rounds second without hesitation.',
  'He sends a gap shot to the fence and pulls into third.',
  'The ball lands between the defenders and rolls deep into the outfield.',
  'He finds open space, and the ball carries all the way to the wall.',
  'A deep gapper leaves the defense chasing it to the fence.',
  'He drives it where nobody can reach it and races into third.',
  'The ball splits the defense cleanly and produces a stand-up triple.',
  // Ball over an outfielder\'s head and to the wall
  'He drives it over the outfielder\'s head and all the way to the wall.',
  'The ball sails beyond the defender and bounces toward the fence.',
  'He gets it over the defense and races into third.',
  'A deep drive clears the outfielder and reaches the wall.',
  'The ball carries beyond the defender\'s reach and rolls to the fence.',
  'He sends one over the outfielder\'s head for three bases.',
  'The defender retreats, but the ball gets over him.',
  'A long drive lands behind the outfielder and reaches the wall.',
  'He lifts it over the defense and never slows around second.',
  'The ball clears the outfielder by a few feet and keeps rolling.',
  'He drives one deep enough to get beyond the defense.',
  'The outfielder turns and runs, but the ball lands behind him.',
  'A well-hit drive sails overhead and reaches the fence.',
  'He sends the defense racing back, but the ball gets past.',
  'The ball lands beyond the outfielder and rolls to the wall.',
  'He drives it over the defense for a stand-up triple.',
  'A deep shot carries farther than the outfielder expected.',
  'The ball gets over the glove and reaches the fence.',
  'He sends one well over the defender and into deep territory.',
  'The outfielder misjudges the carry, and the ball sails overhead.',
  'A long drive gets beyond the defense and rolls to the wall.',
  'He lifts one over the outfielder and races into third.',
  'The ball clears the defense and gives him time for three.',
  'He drives it farther than the outfielder can retreat.',
  'The ball sails overhead, reaches the wall and produces a triple.',
  // Ball bounces off the wall and back past the outfielder
  'The ball hits the wall and kicks back past the outfielder.',
  'It caroms off the fence and rolls away from the defense.',
  'The ball strikes the wall, takes a wild bounce and gets away.',
  'He drives it off the fence, and the rebound skips past the outfielder.',
  'The ball bangs off the wall and shoots back toward the field.',
  'A strange carom sends the ball rolling away, and he races for third.',
  'The wall gives the defense a bad bounce, and the runner takes advantage.',
  'The ball strikes the fence and ricochets past the outfielder.',
  'He gets a fortunate carom and never slows around second.',
  'The rebound off the wall turns the play into a triple.',
  'The ball bounces off the fence and skips into open space.',
  'A hard carom leaves the defense chasing it back toward the field.',
  'The ball hits the wall and takes off in the opposite direction.',
  'He drives it deep, and the rebound carries past the outfielder.',
  'The fence sends the ball bouncing away, and he heads for third.',
  'A wicked carom off the wall gives him three bases.',
  'The ball strikes the wall and rolls beyond the defense\'s reach.',
  'The outfielder plays the wall, but the rebound gets past.',
  'He benefits from a wild bounce and races safely into third.',
  'The ball ricochets sharply off the fence and away from the play.',
  'A tricky rebound off the wall turns extra bases into a triple.',
  'The ball bangs off the fence and skips beyond the outfielder.',
  'The wall sends it back toward the infield, but away from the defense.',
  'He keeps running as the carom rolls into open territory.',
  'The ball takes a wild bounce off the wall, and he arrives at third standing.',
];

export const HOME_RUNS = [
  'Deep to left field!',
  'Sending a shot to right!',
  'That ball is CRUSHED!',
  'High fly into left-center...that\'s GONE!',
  'A rocket toward the wall...over it goes!',
  'Deep to right field...that\'s outta here!',
  'Long drive toward the left-field wall...HOME RUN!',
  'A towering shot to the deepest part of the park...it\'s gone!',
  'That ball is carrying toward the seats...and it\'s OUTTA HERE!',
  'Into the night sky...and GONE!',
];

export function getRandomCall(arr) {
  if (!arr || arr.length === 0) return 'A ball is put in play.';
  return arr[Math.floor(Math.random() * arr.length)];
}

export function getBattedBallCallByType(resultType) {
  const type = resultType?.toLowerCase() || 'single';
  
  if (type === 'homerun') return HOME_RUNS;
  if (type === 'triple') return TRIPLES;
  if (type === 'double') return GAP_SHOTS;
  if (type === 'single') return LINE_DRIVES;
  if (type === 'flyout' || type === 'lineout') return LINE_DRIVES;
  if (type === 'popout') return POP_UPS;
  if (type === 'groundout') return GROUND_BALLS;
  
  return GROUND_BALLS; // fallback
}