// Chicago White Sox Broadcast — 1984
// Radio: Harry Caray & Jimmy Piersall (WMAQ) / TV: Don Drysdale & Ken Harrelson (WSNS)
// Comiskey Park — home of the White Sox
// All stats cutoff: end of 1983 season

export function pickWhiteSoxLine() {
  const totalWeight = Object.values(POOLS).reduce((sum, pool) => sum + pool.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const [category, pool] of Object.entries(POOLS)) {
    roll -= pool.weight;
    if (roll <= 0) return pool.lines[Math.floor(Math.random() * pool.lines.length)];
  }
  return POOLS.teamPraise.lines[0];
}

export function pickWhiteSoxPlayerLine(playerName) {
  if (!playerName) return null;
  const entry = PLAYER_TIDBITS[playerName];
  if (!entry || !entry.lines || entry.lines.length === 0) return null;
  return entry.lines[Math.floor(Math.random() * entry.lines.length)];
}

const PLAYER_TIDBITS = {
  "Rudy Law": {
    lines: [
      "Rudy Law's full name is Rudy Karl Law.",
      "Rudy Law bats and throws left-handed.",
      "Rudy Law began his professional career in the Los Angeles Dodgers organization.",
      "Rudy Law made his major-league debut with Los Angeles during the 1978 season.",
      "Rudy Law appeared in 11 games during his first major-league trial.",
      "Rudy Law spent the entire 1981 season in the minor leagues.",
      "Rudy Law batted .335 and stole 56 bases in the minors during that 1981 season.",
      "Chicago acquired Rudy Law from the Dodgers shortly before the 1982 season.",
      "Rudy Law batted .318 during his first season with the White Sox.",
      "Rudy Law established himself as Chicago's leadoff hitter and primary base-stealing threat.",
      "Rudy Law appeared in 141 games during the 1983 season.",
      "Rudy Law batted .283 with 142 hits in 1983.",
      "Rudy Law recorded 20 doubles and seven triples during the 1983 season.",
      "Rudy Law scored 95 runs in 1983.",
      "Rudy Law stole a White Sox-record 77 bases during the 1983 season.",
      "Law broke Luis Aparicio's previous club record of 56 stolen bases.",
      "Rudy Law was caught stealing only 12 times in 1983.",
      "His 77 stolen bases ranked behind only Rickey Henderson and Tim Raines in the major leagues.",
      "Rudy Law's speed helped Chicago lead the American League with 165 stolen bases.",
      "Law gives the White Sox an immediate scoring threat whenever he reaches first base.",
      "Rudy Law and Vance Law are not related despite playing together on the same team.",
    ],
  },
  "Julio Cruz": {
    lines: [
      "Julio Cruz's full name is Julio Luis Cruz.",
      "Julio Cruz is commonly known by the nickname \"Juice.\"",
      "Julio Cruz was born in Brooklyn, New York.",
      "Cruz grew up in Brooklyn's Williamsburg neighborhood.",
      "Julio Cruz is a switch-hitter who throws right-handed.",
      "Julio Cruz began his major-league career with the expansion Seattle Mariners.",
      "Cruz made his major-league debut during Seattle's first season in 1977.",
      "Julio Cruz developed into one of the American League's fastest second basemen.",
      "Cruz stole at least 40 bases in five consecutive seasons from 1978 through 1982.",
      "Chicago acquired Julio Cruz from Seattle on June 15, 1983.",
      "The White Sox sent second baseman Tony Bernazard to Seattle in the trade.",
      "Chicago was 28-32 when Cruz joined the club.",
      "The White Sox finished the regular season 71-31 after acquiring him.",
      "Chicago went 69-30 in games in which Cruz appeared after the trade.",
      "Julio Cruz played 99 games for the White Sox during the 1983 season.",
      "Cruz collected 84 hits, nine doubles and four triples for Chicago.",
      "Julio Cruz scored 47 runs and drove in 40.",
      "Cruz stole 24 bases after joining the White Sox.",
      "Julio Cruz recorded seven game-winning hits for Chicago in 1983.",
      "Cruz scored the run that clinched the American League West against his former Seattle teammates.",
      "Julio Cruz stole two bases during the 1983 American League Championship Series.",
      "His speed, defense and energy helped change the personality of Chicago's lineup.",
      "Cruz can pressure a defense even when batting near the bottom of the order.",
    ],
  },
  "Harold Baines": {
    lines: [
      "Harold Baines' full name is Harold Douglas Baines.",
      "Harold Baines was born in Easton, Maryland.",
      "Baines grew up in the nearby community of St. Michaels, Maryland.",
      "White Sox owner Bill Veeck first noticed Baines playing baseball when Baines was approximately 12 years old.",
      "Chicago selected Harold Baines with the first overall pick of the 1977 amateur draft.",
      "Baines was drafted directly out of St. Michaels High School.",
      "Harold Baines bats left-handed and throws left-handed.",
      "Baines made his major-league debut during the 1980 season at age 21.",
      "Harold Baines quickly became Chicago's regular right fielder.",
      "Baines hit 25 home runs and drove in 105 runs during the 1982 season.",
      "Harold Baines appeared in 156 games during the 1983 season.",
      "Baines batted .280 with 167 hits in 1983.",
      "Harold Baines collected 33 doubles during the 1983 season.",
      "Baines hit 20 home runs and drove in 99 runs.",
      "Harold Baines scored 76 runs in 1983.",
      "Baines finished tenth in the 1983 American League Most Valuable Player voting.",
      "Harold Baines produced two separate three-home-run games during the 1983 season.",
      "Baines became the first White Sox player to have more than one three-home-run game.",
      "Harold Baines uses a smooth, compact left-handed swing.",
      "Baines is capable of driving an outside pitch over the left fielder's head.",
      "His quiet personality contrasts with his importance in the middle of the Chicago lineup.",
      "Harold Baines enters 1984 at only 25 years old despite already completing four major-league seasons.",
    ],
  },
  "Greg Luzinski": {
    lines: [
      "Greg Luzinski's full name is Gregory Michael Luzinski.",
      "Greg Luzinski is commonly known by the nickname \"The Bull.\"",
      "Luzinski was born in Chicago.",
      "Greg Luzinski attended Notre Dame High School in Niles, Illinois.",
      "Philadelphia selected Luzinski in the first round of the 1968 amateur draft.",
      "Greg Luzinski reached the major leagues with the Phillies during the 1970 season.",
      "Luzinski developed into one of the National League's most feared power hitters.",
      "Greg Luzinski led the National League with 120 RBI during the 1975 season.",
      "Luzinski finished second in the National League Most Valuable Player voting in both 1975 and 1977.",
      "Greg Luzinski was selected to four consecutive All-Star teams from 1975 through 1978.",
      "Luzinski hit at least 30 home runs in three of the four seasons from 1975 through 1978.",
      "Greg Luzinski helped Philadelphia win the 1980 World Series.",
      "Luzinski returned to his hometown when he joined the White Sox before the 1981 season.",
      "The designated-hitter rule allowed Luzinski to concentrate upon his strongest skill: hitting.",
      "Greg Luzinski was named the league's outstanding designated hitter in 1981.",
      "Luzinski appeared in 144 games during the 1983 season.",
      "Greg Luzinski hit 32 home runs and drove in 95 runs in 1983.",
      "Luzinski collected 26 doubles and scored 73 runs.",
      "Greg Luzinski drew 70 walks and recorded a .352 on-base percentage.",
      "Luzinski slugged .502 during the 1983 season.",
      "His 32 home runs established a record at the time for a full-time designated hitter.",
      "Greg Luzinski hit three home runs onto the roof of old Comiskey Park during 1983.",
      "Luzinski was again honored as the American League's outstanding designated hitter.",
      "The Bull does not need to run quickly when he can drive the baseball completely out of the stadium.",
    ],
  },
  "Carlton Fisk": {
    lines: [
      "Carlton Fisk's full name is Carlton Ernest Fisk.",
      "Carlton Fisk is commonly known by the nickname \"Pudge.\"",
      "Fisk was born in Bellows Falls, Vermont, and grew up in Charlestown, New Hampshire.",
      "Carlton Fisk was an outstanding baseball and basketball player during his youth.",
      "Boston selected Fisk in the first round of the 1967 amateur draft.",
      "Carlton Fisk became Boston's regular catcher during the 1972 season.",
      "Fisk was the unanimous American League Rookie of the Year in 1972.",
      "Carlton Fisk also won a Gold Glove Award during his rookie season.",
      "Fisk became one of baseball's most recognizable players during the 1975 World Series.",
      "Carlton Fisk hit the game-winning home run during the 12th inning of Game Six.",
      "Fisk waved the baseball fair as it traveled toward Fenway Park's left-field foul pole.",
      "Carlton Fisk joined the White Sox as a free agent shortly before the 1981 season.",
      "Boston had failed to mail Fisk's contract by the required deadline, making him eligible to negotiate with other teams.",
      "Carlton Fisk appeared in 138 games during the 1983 season.",
      "Fisk batted .289 with 141 hits.",
      "Carlton Fisk recorded 26 doubles, four triples and 26 home runs.",
      "Fisk drove in 86 runs and scored 85 times.",
      "Carlton Fisk stole nine bases, an unusually high total for a veteran catcher.",
      "Fisk recorded a .355 on-base percentage and a .518 slugging percentage.",
      "Carlton Fisk finished third in the 1983 American League Most Valuable Player voting.",
      "Fisk was credited with helping guide a pitching staff led by LaMarr Hoyt, Richard Dotson and Floyd Bannister.",
      "Carlton Fisk combines power hitting with extensive knowledge of opposing batters.",
      "Fisk plays the game with unusual intensity and expects the same commitment from his teammates.",
      "At age 36 entering 1984, Carlton Fisk remains one of the most productive catchers in baseball.",
    ],
  },
  "Ron Kittle": {
    lines: [
      "Ron Kittle's full name is Ronald Dale Kittle.",
      "Ron Kittle is commonly called \"Kitty.\"",
      "Kittle was born and raised in Gary, Indiana.",
      "Ron Kittle bats and throws right-handed.",
      "Kittle is approximately 6-foot-4 and wears glasses while playing.",
      "Ron Kittle overcame serious physical problems early in his professional career.",
      "Kittle spent several years developing in the White Sox minor-league system.",
      "Ron Kittle and Greg Walker became close friends while advancing through the organization together.",
      "Kittle produced an extraordinary season for Triple-A Edmonton in 1982.",
      "Ron Kittle batted .345 with 50 home runs and 144 RBI for Edmonton.",
      "Kittle was named Minor League Player of the Year for that performance.",
      "Ron Kittle became Chicago's regular left fielder during the 1983 season.",
      "Kittle appeared in 145 games as a major-league rookie.",
      "Ron Kittle hit 35 home runs and drove in 100 runs.",
      "Kittle's 35 home runs established a White Sox rookie record.",
      "Ron Kittle scored 75 runs and collected 19 doubles.",
      "Kittle hit one home run for approximately every 15 official at-bats.",
      "That was the best home-run rate in the American League during 1983.",
      "Ron Kittle was selected to the American League All-Star team.",
      "Kittle won the 1983 American League Rookie of the Year Award.",
      "Ron Kittle also struck out 150 times, the highest total in the major leagues.",
      "Kittle's defense can be uncertain, but his power makes it difficult to remove him from the lineup.",
      "Few rookies have ever arrived with a more immediate ability to change a game with one swing.",
    ],
  },
  "Greg Walker": {
    lines: [
      "Greg Walker's full name is Gregory Lee Walker.",
      "Greg Walker was born in Douglas, Georgia.",
      "Walker bats and throws left-handed.",
      "Greg Walker developed primarily as a first baseman.",
      "Walker advanced through the White Sox organization alongside Ron Kittle.",
      "Greg Walker and Kittle became close friends during their minor-league careers.",
      "Walker made his major-league debut during the 1982 season.",
      "Greg Walker appeared in 11 games during his first major-league trial.",
      "Walker collected seven hits in 17 at-bats during the 1982 season.",
      "Greg Walker batted .412 and hit two home runs during that brief opportunity.",
      "Walker received extensive playing time for Chicago during the 1983 season.",
      "Greg Walker appeared in 118 games.",
      "Walker batted .270 with 83 hits.",
      "Greg Walker recorded 16 doubles and three triples.",
      "Walker hit 10 home runs and drove in 55 runs.",
      "Greg Walker recorded a .332 on-base percentage and a .440 slugging percentage.",
      "Walker provides left-handed power to balance the right-handed Kittle and Luzinski.",
      "Greg Walker can share first base with Tom Paciorek or enter as a left-handed pinch-hitter.",
      "Walker is only 24 years old entering the 1984 season.",
      "Chicago believes Walker's power will continue to develop as he gains experience against major-league pitching.",
    ],
  },
  "Vance Law": {
    lines: [
      "Vance Law's full name is Vance Aaron Law.",
      "Vance Law was born in Boise, Idaho.",
      "Vance Law is the son of former major-league pitcher Vern \"Deacon\" Law.",
      "Vern Law won the 1960 National League Cy Young Award with Pittsburgh.",
      "Vance Law played college baseball at Brigham Young University.",
      "Law began his professional career in the Pittsburgh Pirates organization.",
      "Vance Law made his major-league debut during the 1980 season.",
      "Chicago acquired Law from Pittsburgh shortly before the 1982 season.",
      "The White Sox received Law and Ernie Camacho for Ross Baumgarten and Butch Edge.",
      "Vance Law played primarily at shortstop during his first season with Chicago.",
      "Law shifted almost entirely to third base during the 1983 season.",
      "Vance Law appeared in 145 games in 1983.",
      "Law collected 99 hits, including 21 doubles and five triples.",
      "Vance Law hit four home runs and drove in 42 runs.",
      "Law scored 55 times during the 1983 season.",
      "Vance Law drew 51 walks and recorded a .325 on-base percentage.",
      "Law can play third base, shortstop and second base.",
      "His versatility allows Chicago to make late-inning changes without rebuilding the entire infield.",
      "Vance Law is not related to teammate Rudy Law.",
      "The two Laws give announcers an easy opportunity for wordplay whenever they participate in the same play.",
    ],
  },
  "Scott Fletcher": {
    lines: [
      "Scott Fletcher's full name is Scott Brian Fletcher.",
      "Fletcher bats and throws right-handed.",
      "Scott Fletcher can play both shortstop and second base.",
      "Fletcher began his major-league career with the Chicago Cubs.",
      "Scott Fletcher made his major-league debut during the 1981 season.",
      "The Cubs traded Fletcher to the White Sox before the 1983 season.",
      "Fletcher came to the South Side in the large transaction that sent Steve Trout and Warren Brusstar to the Cubs.",
      "The White Sox also received Dick Tidrow, Pat Tabler and Randy Martz in the deal.",
      "Scott Fletcher appeared in 114 games during the 1983 season.",
      "Fletcher collected 62 hits.",
      "Scott Fletcher recorded 16 doubles and five triples.",
      "Fletcher hit three home runs and drove in 31 runs.",
      "Scott Fletcher scored 42 times and stole five bases.",
      "Fletcher drew 29 walks while striking out only 22 times.",
      "Scott Fletcher recorded a .315 on-base percentage.",
      "Fletcher's low strikeout total reflects his ability to make contact.",
      "Scott Fletcher provides sound middle-infield defense behind Chicago's power hitters.",
      "Fletcher can start at shortstop or move to second base when Julio Cruz is unavailable.",
      "He is still only 25 years old entering the 1984 season.",
      "Fletcher's game emphasizes contact, positioning and defensive reliability rather than home-run power.",
    ],
  },
  "Tom Paciorek": {
    lines: [
      "Tom Paciorek's full name is Thomas Marian Paciorek.",
      "Tom Paciorek is commonly known by the nickname \"Wimpy.\"",
      "Paciorek was born in Detroit, Michigan.",
      "Tom Paciorek played baseball and football at the University of Houston.",
      "The Miami Dolphins selected Paciorek during the 1968 professional football draft.",
      "The Los Angeles Dodgers also selected Paciorek in the 1968 baseball draft.",
      "Paciorek chose baseball after the Dodgers offered the larger signing bonus.",
      "Tom Paciorek reached the major leagues with Los Angeles during the 1970 season.",
      "Paciorek appeared in the 1974 World Series with the Dodgers.",
      "Tom Paciorek later played for Atlanta and Seattle.",
      "Paciorek enjoyed a career breakthrough with Seattle in 1981.",
      "Tom Paciorek batted .326 and was selected to the American League All-Star team.",
      "Paciorek finished tenth in the 1981 American League Most Valuable Player voting.",
      "Chicago acquired Tom Paciorek from Seattle before the 1982 season.",
      "Paciorek batted .312 with 27 doubles and 11 home runs in 1982.",
      "Tom Paciorek led Chicago's regular players with a .307 average during the 1983 season.",
      "Paciorek collected 129 hits and a team-high 32 doubles.",
      "Tom Paciorek hit nine home runs and drove in 63 runs.",
      "Paciorek scored 65 times and slugged .462.",
      "Tom Paciorek can play first base and all three outfield positions.",
      "Paciorek's ability to hit right-handed pitching and left-handed pitching makes him valuable in nearly any matchup.",
      "At age 37 entering 1984, Paciorek remains one of Chicago's most dependable contact hitters.",
    ],
  },
  "Jerry Hairston": {
    lines: [
      "Jerry Hairston's full name is Jerry Wayne Hairston.",
      "Jerry Hairston was born in Birmingham, Alabama.",
      "Hairston is a switch-hitter who throws right-handed.",
      "Chicago selected Jerry Hairston in the third round of the 1970 amateur draft.",
      "Hairston was drafted out of Gardendale High School in Alabama.",
      "Jerry Hairston made his major-league debut with the White Sox during the 1973 season.",
      "Hairston is the son of former Negro League and White Sox player Sam Hairston.",
      "Sam Hairston was the first Black player signed by the White Sox organization.",
      "Jerry Hairston's brother Johnny also reached the major leagues.",
      "Hairston has developed into one of Chicago's most reliable pinch-hitters.",
      "On October 4, 1981, Hairston hit a grand slam and later delivered a walk-off single in a remarkable comeback against Minnesota.",
      "Jerry Hairston appeared in 101 games during the 1983 season.",
      "Hairston received only 126 official at-bats but collected 37 hits.",
      "Jerry Hairston batted .294 with nine doubles and five home runs.",
      "Hairston drove in 22 runs and drew 23 walks.",
      "Jerry Hairston recorded a .397 on-base percentage and a .500 slugging percentage.",
      "On April 15, 1983, Hairston came to the plate with two outs in the ninth inning against Detroit's Milt Wilcox.",
      "Wilcox had retired all 26 previous White Sox hitters.",
      "Jerry Hairston singled cleanly to center field, breaking up the perfect game with one out remaining.",
      "Hairston can serve as a pinch-hitter, designated hitter or reserve outfielder.",
      "His ability to remain productive without regular playing time makes him unusually valuable from the bench.",
    ],
  },
  "Marc Hill": {
    lines: [
      "Marc Hill's full name is Marc Kevin Hill.",
      "Marc Hill is commonly known by the nickname \"Booter.\"",
      "Hill is a right-handed catcher.",
      "St. Louis selected Marc Hill during the 1970 amateur draft.",
      "Hill made his major-league debut with the Cardinals during the 1973 season.",
      "Marc Hill's opportunities in St. Louis were limited by the presence of Ted Simmons.",
      "Hill later joined San Francisco and became a regular catcher for the Giants.",
      "Marc Hill also played briefly for Seattle.",
      "Hill signed with the White Sox before the 1981 season.",
      "Chicago signed Hill shortly before adding Carlton Fisk.",
      "Fisk's arrival moved Hill into a reserve role.",
      "Marc Hill appeared in 58 games during the 1983 season.",
      "Hill collected 30 hits, including six doubles and one home run.",
      "Marc Hill drove in 11 runs and scored 11 times.",
      "Hill gives Carlton Fisk important days away from catching.",
      "Marc Hill is valued for his preparation, defense and ability to handle pitchers.",
      "Hill threw out opposing runners at a slightly above-average rate during 1983.",
      "On May 15, 1983, the slow-footed Hill scored from second base on a sacrifice fly.",
      "Hill provides experience behind the plate when Chicago uses a younger pitcher.",
      "The Booter's value is more apparent in the confidence of his pitchers than in his batting statistics.",
    ],
  },
  "Luis Salazar": {
    lines: [
      "Luis Salazar's full name is Luis Ernesto Salazar Garcia.",
      "Luis Salazar was born in Venezuela.",
      "Salazar bats and throws right-handed.",
      "Luis Salazar made his major-league debut with San Diego during the 1980 season.",
      "Salazar batted .337 during his 44-game rookie trial.",
      "Luis Salazar became San Diego's regular third baseman during the 1981 season.",
      "Salazar batted .303 with 121 hits during 1981.",
      "Luis Salazar recorded 19 doubles and six triples that season.",
      "Salazar can play third base, shortstop and several outfield positions.",
      "Luis Salazar's versatility makes him useful as both a starter and reserve.",
      "Salazar appeared in 134 games for San Diego during the 1983 season.",
      "Luis Salazar batted .258 with 124 hits.",
      "Salazar collected 16 doubles and two triples.",
      "Luis Salazar established a career high with 14 home runs in 1983.",
      "Salazar drove in 45 runs and scored 52 times.",
      "Luis Salazar stole 24 bases during the 1983 season.",
      "Salazar was caught stealing nine times.",
      "His combination of speed, occasional power and defensive flexibility gives the roster several substitution options.",
      "Luis Salazar can enter for defense without becoming an automatic out at the plate.",
      "Salazar enters 1984 with four seasons of major-league experience despite being only 27 years old.",
    ],
  },
  "Joel Skinner": {
    lines: [
      "Joel Skinner's full name is Joel Patrick Skinner.",
      "Joel Skinner is a right-handed catcher.",
      "Pittsburgh selected Skinner in the 37th round of the 1979 amateur draft.",
      "Chicago obtained Joel Skinner through the free-agent compensation system before the 1982 season.",
      "The White Sox received the compensation selection after losing pitcher Ed Farmer.",
      "Skinner developed in Chicago's minor-league system.",
      "Joel Skinner made his major-league debut on June 12, 1983.",
      "Skinner was 22 years old at the time of his debut.",
      "Joel Skinner entered his first game as a ninth-inning defensive replacement against Oakland.",
      "Skinner appeared in six major-league games during the 1983 season.",
      "Joel Skinner received 11 official at-bats.",
      "Skinner collected three hits and batted .273.",
      "Joel Skinner scored two runs and drove in one.",
      "Skinner has considerably less major-league experience than Carlton Fisk or Marc Hill.",
      "Joel Skinner's principal role is learning the pitching staff and developing his receiving skills.",
      "Skinner gives Chicago a young catcher who can be used without forcing Fisk into every game.",
      "Entering 1984, opposing teams possess very little major-league scouting information on him.",
    ],
  },
  "LaMarr Hoyt": {
    lines: [
      "LaMarr Hoyt's full name is Dewey LaMarr Hoyt.",
      "Hoyt was born in Columbia, South Carolina.",
      "The New York Yankees selected LaMarr Hoyt in the fifth round of the 1973 amateur draft.",
      "Hoyt attended Keenan High School in Columbia.",
      "The White Sox acquired Hoyt as part of the 1977 trade that sent Bucky Dent to the Yankees.",
      "LaMarr Hoyt made his major-league debut during the 1979 season.",
      "Hoyt initially worked primarily from the Chicago bullpen.",
      "LaMarr Hoyt gradually moved into the starting rotation.",
      "Hoyt won his final nine decisions of the 1981 season.",
      "LaMarr Hoyt went 19-15 during the 1982 season.",
      "Hoyt led the American League in victories in 1982.",
      "LaMarr Hoyt made 36 starts during the 1983 season.",
      "Hoyt went 24-10 and again led the American League in victories.",
      "LaMarr Hoyt recorded a 3.66 ERA.",
      "Hoyt threw 260 and two-thirds innings during the 1983 season.",
      "LaMarr Hoyt completed 11 games and recorded one shutout.",
      "Hoyt struck out 148 hitters while walking only 31.",
      "LaMarr Hoyt's ratio of nearly five strikeouts for every walk demonstrated exceptional control.",
      "Hoyt won 15 of his final 16 decisions during Chicago's second-half surge.",
      "LaMarr Hoyt won Game One of the 1983 American League Championship Series against Baltimore.",
      "Hoyt allowed one run in a complete-game, five-hit victory.",
      "LaMarr Hoyt won the 1983 American League Cy Young Award.",
      "Hoyt relies upon control, movement and changing speeds more than overwhelming velocity.",
      "Chicago's ace is willing to challenge hitters because he rarely defeats himself with walks.",
    ],
  },
  "Richard Dotson": {
    lines: [
      "Richard Dotson's full name is Richard Elliott Dotson.",
      "Dotson is a right-handed pitcher.",
      "Richard Dotson was born in Cincinnati, Ohio.",
      "California selected Dotson during the first round of the 1977 amateur draft.",
      "Chicago acquired Richard Dotson while he was still a minor-league prospect.",
      "Dotson made his major-league debut on September 4, 1979.",
      "Richard Dotson was only 20 years old during his first major-league start.",
      "Dotson struggled in that debut and left with an earned-run average of 33.75.",
      "Richard Dotson remained in the Chicago rotation and gradually developed.",
      "Dotson won 12 games in both 1980 and 1982.",
      "Richard Dotson made 35 starts during the 1983 season.",
      "Dotson went 22-7 with a 3.23 ERA.",
      "Richard Dotson's 22 victories ranked second in the American League behind LaMarr Hoyt.",
      "Dotson threw exactly 240 innings.",
      "Richard Dotson completed eight games.",
      "Dotson recorded one shutout during the 1983 season.",
      "Richard Dotson allowed 209 hits and struck out 137.",
      "Dotson and Hoyt combined for 46 victories.",
      "Their combined total gave Chicago one of baseball's most productive starting-pitching combinations.",
      "Richard Dotson pitched a five-hit shutout immediately after Chicago clinched the division.",
      "Dotson's only 1983 postseason appearance came in Game Three of the American League Championship Series.",
      "Richard Dotson enters 1984 at only 25 years old.",
      "Dotson has already demonstrated that he can handle the workload of a traditional staff ace.",
    ],
  },
  "Floyd Bannister": {
    lines: [
      "Floyd Bannister's full name is Floyd Franklin Bannister.",
      "Bannister was born in Pierre, South Dakota.",
      "Floyd Bannister attended Kennedy High School in Seattle.",
      "Oakland selected Bannister during the 1973 amateur draft, but he did not sign.",
      "Floyd Bannister chose to attend Arizona State University.",
      "Bannister became one of the leading amateur pitchers in the country.",
      "Houston selected Floyd Bannister with the first overall pick of the 1976 amateur draft.",
      "Bannister reached the major leagues with Houston during the 1977 season.",
      "Floyd Bannister later pitched for Seattle.",
      "Bannister was selected to the 1982 American League All-Star team.",
      "Floyd Bannister led the American League with 209 strikeouts in 1982.",
      "Chicago signed Bannister as a free agent before the 1983 season.",
      "The White Sox outbid numerous other clubs for the left-hander.",
      "Floyd Bannister started his first Chicago season slowly.",
      "Bannister fell to 3-9 before turning his season around.",
      "Floyd Bannister went 13-1 after July 12.",
      "Bannister finished the 1983 season with a 16-10 record and a career-best 3.35 ERA.",
      "Floyd Bannister made 34 starts and threw 217 and a third innings.",
      "Bannister completed five games and recorded two shutouts.",
      "Floyd Bannister struck out 193 hitters.",
      "He averaged eight strikeouts for every nine innings.",
      "Bannister gives Chicago a power left-hander between the right-handed Hoyt and Dotson.",
      "When Bannister controls the strike zone, opposing hitters have difficulty making solid contact.",
    ],
  },
  "Tom Seaver": {
    lines: [
      "Tom Seaver's full name is George Thomas Seaver.",
      "Seaver is commonly known by the nicknames \"Tom Terrific\" and \"The Franchise.\"",
      "Tom Seaver was born in Fresno, California.",
      "Seaver served in the United States Marine Corps Reserve before beginning his professional career.",
      "Tom Seaver played college baseball at the University of Southern California.",
      "Seaver joined the New York Mets after an unusual lottery resolved a disputed signing.",
      "Tom Seaver made his major-league debut during the 1967 season.",
      "Seaver won the 1967 National League Rookie of the Year Award.",
      "Tom Seaver helped transform the Mets from an expansion team into a champion.",
      "Seaver went 25-7 with a 2.21 ERA during the 1969 season.",
      "Tom Seaver won the 1969 National League Cy Young Award.",
      "Seaver helped the \"Miracle Mets\" win the 1969 World Series.",
      "Tom Seaver won additional Cy Young Awards in 1973 and 1975.",
      "Seaver led the National League in strikeouts five times before joining Chicago.",
      "Tom Seaver threw a no-hitter for Cincinnati against St. Louis on June 16, 1978.",
      "Seaver returned to the Mets for the 1983 season.",
      "Tom Seaver made 34 starts for New York in 1983.",
      "Seaver went 9-14 despite recording a respectable 3.55 ERA.",
      "Tom Seaver threw 231 innings and completed five games.",
      "Seaver recorded two shutouts and struck out 135 hitters.",
      "Tom Seaver entered the 1983-84 offseason with 273 career victories.",
      "Seaver also entered with more than 3,500 career strikeouts.",
      "The Mets left Seaver unprotected during the free-agent compensation draft.",
      "Chicago selected Tom Seaver in January 1984 without surrendering a player in a conventional trade.",
      "Seaver brings three Cy Young Awards, a World Series championship and nearly two decades of experience to Chicago's rotation.",
      "Few fourth starters in baseball history have arrived with a resume comparable to Tom Seaver's.",
    ],
  },
  "Ron Reed": {
    lines: [
      "Ron Reed's full name is Ronald Lee Reed.",
      "Ron Reed was born in LaPorte, Indiana.",
      "Reed played both baseball and basketball at the University of Notre Dame.",
      "Ron Reed was one of Notre Dame's leading rebounders.",
      "Reed played professional basketball before establishing himself as a major-league pitcher.",
      "Ron Reed appeared in the National Basketball Association with the Detroit Pistons.",
      "Reed is one of the relatively few athletes to play in both the NBA and Major League Baseball.",
      "Ron Reed began his major-league baseball career with the Atlanta Braves.",
      "Reed originally worked primarily as a starting pitcher.",
      "Ron Reed later pitched for St. Louis before joining Philadelphia.",
      "Reed became one of the Phillies' most dependable relief pitchers.",
      "Ron Reed frequently worked as the primary right-handed setup man for Tug McGraw.",
      "Reed helped Philadelphia win the 1980 World Series.",
      "Ron Reed recorded a save during Game Two of that World Series.",
      "Reed appeared in 61 games for Philadelphia during the 1983 season.",
      "Ron Reed went 9-1 with a 3.48 ERA.",
      "Reed recorded eight saves and worked 95 and two-thirds innings.",
      "Ron Reed struck out 73 hitters while walking 34.",
      "Reed pitched in the 1983 World Series after helping Philadelphia win the National League pennant.",
      "Chicago acquired the veteran following the 1983 season.",
      "Ron Reed can work multiple innings rather than waiting exclusively for the ninth.",
      "His size, durability and championship experience give Chicago a highly experienced bullpen leader.",
      "Reed enters 1984 at age 41 but is coming off a productive season for a pennant winner.",
    ],
  },
  "Salome Barojas": {
    lines: [
      "Salome Barojas' full name is Salome Barojas Romero.",
      "Barojas was born in Cordoba, Veracruz, Mexico.",
      "Salome Barojas began his professional career in Mexican baseball.",
      "Barojas pitched for his hometown Cordoba club as a teenager.",
      "Salome Barojas attracted the attention of Chicago manager Tony La Russa.",
      "Chicago signed Barojas after La Russa watched him pitch during the 1981 major-league strike.",
      "Salome Barojas made his major-league debut on April 11, 1982.",
      "Barojas was already 24 years old when he reached the major leagues.",
      "Salome Barojas recorded saves in each of his first five major-league appearances.",
      "Several of those saves required Barojas to pitch more than one inning.",
      "Salome Barojas was named American League Player of the Week during his first week in the majors.",
      "Barojas became the first player to earn that honor during his first major-league week.",
      "Salome Barojas recorded 21 saves as a rookie in 1982.",
      "Barojas appeared in 52 games during the 1983 season.",
      "Salome Barojas went 3-3 with a 2.47 ERA.",
      "Barojas recorded 12 saves.",
      "Salome Barojas worked 87 and two-thirds innings without making a start.",
      "Barojas allowed only 70 hits.",
      "Salome Barojas finished 29 games during the 1983 season.",
      "Barojas can enter during the seventh or eighth inning and remain until the game is over.",
      "His experience with extended saves makes him especially appropriate for early-1980s bullpen strategy.",
    ],
  },
  "Juan Agosto": {
    lines: [
      "Juan Agosto's full name is Juan Roberto Agosto Gonzalez.",
      "Agosto was born in Rio Piedras, Puerto Rico.",
      "Juan Agosto bats and throws left-handed.",
      "Agosto developed as both a starter and reliever in the White Sox organization.",
      "Juan Agosto made his major-league debut during the 1981 season.",
      "Agosto appeared in two games during his first major-league trial.",
      "Juan Agosto spent much of the 1982 season in the minor leagues.",
      "Agosto returned to Chicago's bullpen during the 1983 season.",
      "Juan Agosto appeared in 39 games.",
      "Agosto went 2-2 with a 4.10 ERA.",
      "Juan Agosto recorded seven saves during the 1983 season.",
      "Agosto worked 41 and two-thirds innings.",
      "Juan Agosto allowed 41 hits.",
      "Agosto struck out 29 hitters while walking only 11.",
      "Juan Agosto finished 13 games.",
      "Agosto allowed only two home runs during the season.",
      "Juan Agosto gives the bullpen a left-handed contrast to Ron Reed and Salome Barojas.",
      "Agosto can be used for one difficult left-handed hitter or remain for a complete inning.",
      "Chicago fans have sometimes referred to him by the joking nickname \"Juan Disgusto.\"",
      "Agosto's improving control increases his value in situations with runners already on base.",
    ],
  },
  "Gene Nelson": {
    lines: [
      "Gene Nelson's full name is Wayland Eugene Nelson II.",
      "Nelson was born in Tampa, Florida.",
      "Gene Nelson is a right-handed pitcher.",
      "Nelson made his major-league debut with the New York Yankees during the 1981 season.",
      "Gene Nelson was only 20 years old when he first reached the majors.",
      "Nelson joined the Seattle organization before the 1982 season.",
      "Gene Nelson worked primarily as a starting pitcher during his early career.",
      "On June 7, 1982, Nelson pitched a two-hit complete game for Seattle against Texas.",
      "Gene Nelson went 12-13 in 28 starts during the 1982 season.",
      "Nelson threw more than 180 innings during his first extended major-league opportunity.",
      "Gene Nelson spent much of the 1983 season in the minor leagues.",
      "Nelson made 10 major-league appearances for Seattle in 1983.",
      "Gene Nelson made five starts and worked 32 innings.",
      "Nelson went 0-3 with a 7.88 ERA.",
      "Gene Nelson struck out 11 hitters while walking 21.",
      "Nelson was one of three unrelated players named Nelson on Seattle's roster.",
      "The other two were outfielder Ricky Nelson and catcher Jamie Nelson.",
      "Gene Nelson enters 1984 as a young pitcher whose role has not yet been firmly established.",
      "His starting background allows him to provide several innings of relief.",
      "At only 23 years old, Nelson remains a developmental pitcher rather than a finished product.",
    ],
  },
  "Dan Spillner": {
    lines: [
      "Dan Spillner's full name is Daniel Ray Spillner.",
      "Spillner was born in Casper, Wyoming.",
      "Dan Spillner is a right-handed pitcher.",
      "San Diego selected Spillner during the 1970 amateur draft.",
      "Dan Spillner made his major-league debut with the Padres during the 1974 season.",
      "Spillner began his career primarily as a starting pitcher.",
      "Dan Spillner later joined Cleveland.",
      "Spillner became Cleveland's Opening Day starter during the 1980 season.",
      "Dan Spillner won 16 games in 1980.",
      "On August 20, 1980, Spillner carried a no-hitter into the ninth inning against the White Sox.",
      "Rookie Leo Sutherland broke up the no-hit attempt with one out remaining.",
      "Dan Spillner completed the one-hit, 3-0 shutout.",
      "Spillner successfully shifted from the rotation into relief.",
      "Dan Spillner enjoyed his best relief season in 1982.",
      "Spillner went 12-10 with a 2.49 ERA and 21 saves.",
      "Dan Spillner appeared in 60 games for Cleveland during the 1983 season.",
      "Spillner went 2-9 with a 5.07 ERA.",
      "Dan Spillner recorded eight saves and worked 92 and a third innings.",
      "Spillner struck out 48 hitters and finished 41 games.",
      "His starting background allows him to work multiple innings from the bullpen.",
      "Spillner enters 1984 attempting to regain the form that made him one of the American League's better relievers in 1982.",
    ],
  },
};

const POOLS = {
  gameAction: { weight: 0, lines: [
    "\"Strike three called.\"", "\"Got him looking.\"", "\"A line drive — base hit.\"",
    "\"Long drive to left field — way back — gone. Home run!\"",
    "\"Ground ball to short — over to first — in time.\"",
  ]},
  teamPraise: { weight: 20, lines: [
    "\"This ballclub won 99 games last year — the White Sox are the defending American League West champions.\"",
    "\"Chicago baseball is alive and well on the South Side — the fans here at Comiskey love their White Sox.\"",
    "\"This team has power, speed and pitching — the White Sox are built to win.\"",
    "\"LaMarr Hoyt won 24 games and the Cy Young last year — that's your ace.\"",
    "\"Carlton Fisk, Greg Luzinski, Harold Baines — that's a murderer's row right there.\"",
    "\"There's talent everywhere you look in this lineup — the White Sox can hurt you in so many ways.\"",
    "\"This club plays hard for nine innings — that's the White Sox way.\"",
    "\"Chicago has one of the most dangerous lineups in the American League.\"",
    "\"The fans on the South Side have been waiting for a winner — and they got one last year.\"",
    "\"There's a buzz around the White Sox this year — the defending champs are hungry for more.\"",
    "\"This is a team with championship pedigree — they won the West going away last year.\"",
    "\"Comiskey Park — there's nothing quite like a night at the old ballpark.\"",
  ]},
  players: { weight: 15, lines: [
    "\"Carlton Fisk is one of the greatest catchers in baseball history — and he's still going strong.\"",
    "\"LaMarr Hoyt is the reigning Cy Young winner — 24 victories, 31 walks — that's extraordinary control.\"",
    "\"Harold Baines has one of the sweetest left-handed swings you'll ever see.\"",
    "\"Greg Luzinski — The Bull — can hit the ball onto the roof of this ballpark.\"",
    "\"Ron Kittle hit 35 home runs as a rookie — that's raw power.\"",
    "\"Rudy Law stole 77 bases last year — he's a threat every time he reaches base.\"",
    "\"Tom Seaver is a Hall of Famer — three Cy Youngs, a no-hitter — and now he's a White Sox.\"",
  ]},
  atmosphere: { weight: 15, lines: [
    "\"A beautiful evening here at Comiskey Park.\"",
    "\"The lights are on at the old ballpark — White Sox baseball tonight.\"",
    "Comiskey Park — home of the White Sox since 1910.",
    "\"The warm Midwestern air is perfect for baseball tonight.\"",
    "\"The stands are filling up nicely — the fans on the South Side are excited about this club.\"",
    "\"You can see the Chicago skyline beyond the outfield — a beautiful backdrop on a clear night.\"",
    "\"Comiskey Park has been home to some of baseball's greatest moments — the Black Sox, the Go-Go Sox — history lives here.\"",
    "\"The old ballpark has character — you can feel it the moment you walk through the gates.\"",
    "\"The upper deck at Comiskey is one of the steepest in baseball — great view from up there.\"",
    "\"The faithful at Comiskey are some of the most passionate fans in baseball.\"",
    "\"A crisp evening in Chicago — there's nothing better than baseball at Comiskey Park.\"",
    "\"The South Side is buzzing tonight — the fans here love their White Sox.\"",
  ]},
  crowd: { weight: 10, lines: [
    "\"The crowd here at Comiskey is into this ballgame.\"",
    "\"White Sox fans are making some noise tonight.\"",
    "\"The fans on the South Side have been waiting for a winner — they're fired up tonight.\"",
    "\"Comiskey Park is rocking tonight.\"",
    "\"Chicago fans are among the most passionate in baseball — they show up every night.\"",
    "\"The crowd is on its feet — they can feel something building here.\"",
    "\"A great turnout at Comiskey tonight.\"",
    "\"These fans watched their team win the West last year — they expect more of the same.\"",
  ]},
  folksy: { weight: 6, lines: [
    "\"Welcome to Comiskey Park, everyone. A beautiful evening for baseball.\"",
    "\"Good to have you with us tonight. We appreciate you spending time with us.\"",
    "\"There's nothing quite like baseball on a Chicago summer night.\"",
    "\"From all of us on the South Side, thanks for joining us at the ballpark.\"",
    "\"The great thing about baseball is you never know what you might see.\"",
    "\"Every game tells its own story — that's the beauty of this sport.\"",
    "\"Baseball in Chicago — it's a tradition that runs deep on the South Side.\"",
  ]},
  signature: { weight: 1, lines: [
    "\"That ball is gone — onto the roof at Comiskey!\"",
    "\"Holy cow — what a ballgame!\"",
    "\"The White Sox are making their move here at Comiskey Park.\"",
    "\"That one is long gone — souvenir for a fan in the upper deck.\"",
    "\"You won't see many better than that one.\"",
    "\"And the South Side goes crazy — what a finish!\"",
  ]},
};