// National Cars & The Road (1984) Banner (#1001-1025) — 13 windows, mixed into ALL 26 ballparks
// Chrome-and-open-road nostalgia + gearhead pride + retrospective wink
// All models and brands are real; all descriptive copy is original. No reproduced slogans, jingles, or ad copy.
// Hidden achievement: "Full Tank, Open Road" — open all 13 cars & road windows

export const CARS_ROAD_BANNER = {
  id: 'carsroadbanner_1001',
  title: '🚗 "Start your engines — hit the road!"',
  subtitle: '(chrome-and-open-road nostalgia meets gearhead pride)',
  icon: '🚗',
  hiddenAchievement: '🚗 "Full Tank, Open Road"',
  popups: [
    {
      num: 1,
        achievementId: 'nat_cars_1',
      emoji: '🚐',
      title: 'THE MINIVAN',
      tagline: 'The family car of the future',
      whatItWas: 'A brand-new kind of vehicle — taller and roomier than a wagon, with sliding doors and seats for the whole crew. Chrysler\'s new minivans launched for 1984 and instantly redefined what a family car could be.',
      howChanged: 'The minivan was the genuine new thing on the road in \'84 — practical, novel, and about to take over suburban driveways everywhere.',
      craze: 'Created a whole vehicle category and became the definitive family hauler for a generation.',
      howAged: 'The minivan ruled for decades before the SUV muscled in — a true \'84 milestone. 🚐',
      achievement: '🚐 *Sliding Door*',
    },
    {
      num: 2,
        achievementId: 'nat_cars_2',
      emoji: '🏎️',
      title: 'THE PONTIAC FIERO',
      tagline: 'A mid-engine sports car for the masses',
      whatItWas: 'A sleek, affordable two-seater with its engine in the middle (exotic-car style) and pop-up headlights — a genuinely exciting, futuristic-looking sporty compact launched for the era.',
      howChanged: 'The Fiero was a fresh, stylish, attainable sports car that turned heads in \'84 — pop-up lights and wedge shape and all.',
      craze: 'A cult-favorite \'80s sports car, beloved for its looks and ambition.',
      howAged: 'A nostalgic gearhead favorite; the pop-up headlights are pure \'80s. 🏎️',
      achievement: '🏎️ *Pop-Up Headlights*',
    },
    {
      num: 3,
        achievementId: 'nat_cars_3',
      emoji: '🚙',
      title: 'THE K-CAR',
      tagline: 'Boxy, thrifty, and everywhere',
      whatItWas: 'The practical, fuel-sipping compact sedans and their many spinoffs — boxy, sensible, affordable cars that helped a struggling industry get back on its feet and filled miles of driveways.',
      howChanged: 'The thrifty compact was the sensible-shoes car of the moment in \'84 — not flashy, but dependable and easy on the gas.',
      craze: 'A symbol of the era\'s practical, recover-and-rebuild auto industry.',
      howAged: 'Unglamorous but historically important; a quiet \'80s workhorse. 🚙',
      achievement: '🚙 *Thrifty Miles*',
    },
    {
      num: 4,
        achievementId: 'nat_cars_4',
      emoji: '🔥',
      title: 'THE PONY & MUSCLE CARS',
      tagline: 'V8 rumble and T-tops',
      whatItWas: 'The sporty rear-drive coupes still roaring down Main Street — Camaros, Mustangs, and Trans Ams with their growling engines, T-top roofs, and screaming-eagle hood decals.',
      howChanged: 'These cars were the cool-kid cruisers in \'84 — loud, fast-looking, and the dream ride for many a teenager.',
      craze: 'A defining image of \'80s street cool and American muscle.',
      howAged: 'Iconic — the T-top coupe is forever \'80s. 🔥',
      achievement: '🔥 *V8 Rumble*',
    },
    {
      num: 5,
        achievementId: 'nat_cars_5',
      emoji: '📱',
      title: 'THE CAR PHONE',
      tagline: 'Making calls from the road?!',
      whatItWas: 'The brick-sized telephone wired into a car — an extraordinarily expensive, rare status symbol that let a select few make calls while driving, antenna on the trunk and all.',
      howChanged: 'The car phone was the ultimate "look how successful I am" gadget in \'84 — futuristic, pricey, and something most people had only seen on TV.',
      craze: 'The forerunner of the mobile phone, and a perfect \'80s status symbol.',
      howAged: 'Quaint now that everyone has a phone — but in \'84 it screamed money. 📱',
      achievement: '📱 *Calling From the Car*',
    },
    {
      num: 6,
        achievementId: 'nat_cars_6',
      emoji: '🍔',
      title: 'DRIVE-IN CULTURE',
      tagline: 'Eat, watch, and order from your car',
      whatItWas: 'Car-centric life — the drive-thru window where you ordered into a crackly speaker, the drive-in restaurant with carhops, and the drive-in movie theater under the stars (still hanging on in \'84).',
      howChanged: 'So much happened from the driver\'s seat in \'84 — burgers, milkshakes, and movies all without leaving the car.',
      craze: 'A quintessential slice of American car culture.',
      howAged: 'The drive-thru thrived; the drive-in movie became precious nostalgia. 🍔',
      achievement: '🍔 *Order at the Speaker*',
    },
    {
      num: 7,
        achievementId: 'nat_cars_7',
      emoji: '🗺️',
      title: 'THE FAMILY ROAD TRIP',
      tagline: 'Are we there yet?',
      whatItWas: 'The great American road trip — a paper map unfolded on the dash (impossible to refold), license-plate games, gas-station bathroom stops, and "are we there yet?" from the back seat.',
      howChanged: 'With cheap gas and the interstate calling in \'84, the family road trip was the summer vacation — packed car, cooler in the trunk, and miles of highway.',
      craze: 'The paper-map road trip is a beloved, slightly chaotic ritual.',
      howAged: 'GPS replaced the map, but the road-trip spirit endures. 🗺️',
      achievement: '🗺️ *Are We There Yet?*',
    },
    {
      num: 8,
        achievementId: 'nat_cars_8',
      emoji: '🎶',
      title: 'THE CAR STEREO',
      tagline: 'Crank the tunes on the highway',
      whatItWas: 'The car\'s sound system — the fading 8-track giving way to the cassette deck, the AM/FM dial, and the aftermarket speakers in the back, with a shoebox of tapes on the seat.',
      howChanged: 'A good car stereo and a stack of cassettes were essential road gear in \'84 — windows down, music up.',
      craze: 'The car-stereo-and-cassette combo is core driving nostalgia.',
      howAged: 'Formats changed, but cranking tunes on the highway is eternal. 🎶',
      achievement: '🎶 *Windows Down*',
    },
    {
      num: 9,
        achievementId: 'nat_cars_9',
      emoji: '⛽',
      title: 'DOLLAR-A-GALLON GAS',
      tagline: 'Fill the tank for a few bucks',
      whatItWas: 'Gas around a dollar a gallon — filling the tank cheaply, the rotating-number pump dial spinning, and a few stations still offering an attendant to pump it for you.',
      howChanged: 'Cheap fuel kept everyone on the road in \'84; a twenty filled the tank with change to spare.',
      craze: 'A nostalgic benchmark — "gas used to cost *what*?"',
      howAged: 'A wistful memory every time prices climb. ⛽',
      achievement: '⛽ *Top Off the Tank*',
    },
    {
      num: 10,
        achievementId: 'nat_cars_10',
      emoji: '🛻',
      title: 'THE PICKUP TRUCK',
      tagline: 'Work hard, haul anything',
      whatItWas: 'The trusty pickup — the workhorse of farms, job sites, and weekend projects, with a bench seat, an AM radio, and a bed that hauled everything from hay to a couch to a load of kids.',
      howChanged: 'The pickup was a backbone of American life in \'84, equal parts tool and pride.',
      craze: 'A timeless symbol of work, utility, and the open road.',
      howAged: 'Trucks only grew more popular — the \'84 workhorse is a classic. 🛻',
      achievement: '🛻 *Load the Bed*',
    },
    {
      num: 11,
        achievementId: 'nat_cars_11',
      emoji: '🌈',
      title: 'THE CUSTOM VAN',
      tagline: 'Shag carpet and a mural on the side',
      whatItWas: 'The customized van scene — wild airbrushed murals on the side panels, shag carpet and captain\'s chairs inside, porthole windows, and a vibe all its own. The "party on wheels."',
      howChanged: 'The custom van (and the conversion van) was peak personalized cool in \'84, rolling self-expression on four wheels.',
      craze: 'A gloriously \'70s-into-\'80s subculture, fondly remembered.',
      howAged: 'Pure retro kitsch in the best way — the airbrushed van is legendary. 🌈',
      achievement: '🌈 *Murals & Shag*',
    },
    {
      num: 12,
        achievementId: 'nat_cars_12',
      emoji: '🎛️',
      title: 'THE DASHBOARD',
      tagline: 'Bench seat, AM radio, no seatbelt fuss',
      whatItWas: 'The car interior of the era — the wide bench seat, the simple analog gauges, the cigarette lighter and ashtray standard, the new digital dashboards just appearing, and the hand-crank windows.',
      howChanged: 'The car\'s cabin was analog and roomy in \'84 — roll-down windows, a bench seat the whole front row shared, and a radio with real knobs.',
      craze: 'The analog dashboard is a tactile, beloved memory.',
      howAged: 'Replaced by screens and sensors — the knob-and-crank era is nostalgic. 🎛️',
      achievement: '🎛️ *Roll Down the Window*',
    },
    {
      num: 13,
        achievementId: 'nat_cars_13',
      emoji: '🛣️',
      title: 'THE OPEN ROAD',
      tagline: 'Just drive',
      whatItWas: 'The pure feeling of it — an open highway ahead, the windows down, the radio up, no particular place to be, and the freedom of the American road stretching to the horizon.',
      howChanged: 'With cheap gas and endless highway in \'84, the open road was freedom itself — the great American drive.',
      craze: 'The open road is one of the country\'s most enduring romantic ideals.',
      howAged: 'Timeless — the call of the open road never fades. 🛣️',
      achievement: '🛣️ *Just Drive*',
    },
  ],
};