// National Cereal & Their Mascots (1984) Banner (#1051-1075) — 15 windows, mixed into ALL 26 ballparks
// Cereal-and-pajamas nostalgia meets breakfast-aisle iconography
// All cereal brands and mascot names are real 1984-era references in ORIGINAL wording. No reproduced slogans, jingles, or catchphrases verbatim. Mascots described generically but recognizably.
// Hidden achievement: "Cleaned the Bowl" — open all 15 cereal & mascot windows

export const CEREAL_BANNER = {
  id: 'cerealbanner_1051',
  title: '🥣 "Pour a bowl — breakfast of champions!"',
  subtitle: '(cereal-aisle nostalgia meets mascot magic)',
  icon: '🥣',
  hiddenAchievement: '🦁 "Cleaned the Bowl"',
  popups: [
    {
      num: 1,
      emoji: '🥣',
      title: 'THE CEREAL AISLE',
      tagline: 'A wall of cartoon color',
      whatItWas: 'The supermarket cereal aisle in 1984 — a towering wall of brightly colored boxes, each one fronted by a cartoon mascot beckoning you in, the sweet smell of sugar and cardboard. The most exciting aisle in the whole store for a kid.',
      howChanged: 'The cereal aisle in \'84 was pure sensory overload — a kaleidoscope of mascots, colors, and prizes that made choosing a box a weekly event.',
      craze: 'The cereal aisle was a defining retail experience of \'80s childhood.',
      howAged: 'Toned down over the years — the neon \'80s aisle glows in memory. 🥣',
      achievement: '🥣 *Aisle of Sugar*',
    },
    {
      num: 2,
      emoji: '🎁',
      title: 'THE PRIZE INSIDE',
      tagline: 'Buried at the bottom of the box',
      whatItWas: 'The toy, sticker, or trinket buried at the bottom of the cereal box — the reason you begged for that particular box, then dug through the whole thing with your arm up to the elbow before the first bowl.',
      howChanged: 'The prize inside was the great cereal motivator in \'84 — kids picked boxes by the toy, not the flakes.',
      craze: 'The in-box prize was a beloved ritual of the cereal era.',
      howAged: 'Phased out and mourned — the buried prize is peak nostalgia. 🎁',
      achievement: '🎁 *Dig for the Prize*',
    },
    {
      num: 3,
      emoji: '🦁',
      title: 'THE FROSTED-FLAKES TIGER',
      tagline: 'They\'re great',
      whatItWas: 'The cheerful, confident cartoon tiger fronting the sugar-frosted corn flakes — one of the most recognizable cereal mascots of them all, all enthusiasm and stripes.',
      howChanged: 'The big friendly tiger was breakfast-aisle royalty in \'84, his frosted flakes a staple bowl.',
      craze: 'An all-time-great cereal mascot, instantly recognizable.',
      howAged: 'Still going strong — a true icon of the aisle. 🦁',
      achievement: '🦁 *Grrreat*',
    },
    {
      num: 4,
      emoji: '🧛',
      title: 'THE CEREAL MONSTERS',
      tagline: 'Spooky, sweet, and silly',
      whatItWas: 'The lovable monster mascots fronting the chocolate and strawberry "monster" cereals — a friendly vampire, a goofy ghost, and a shaggy berry beast, more giggles than frights.',
      howChanged: 'The monster cereals were a fun, slightly spooky aisle favorite in \'84, big around the fall especially.',
      craze: 'Beloved cult-classic cereals with devoted fans.',
      howAged: 'Still adored — the monster mascots are nostalgia gold. 🧛',
      achievement: '🧛 *Monster Mash*',
    },
    {
      num: 5,
      emoji: '🍀',
      title: 'THE MARSHMALLOW LEPRECHAUN',
      tagline: 'Always after the marshmallows',
      whatItWas: 'The mischievous cartoon leprechaun guarding his marshmallow-studded oat cereal — pink hearts, yellow moons, green clovers, and a kid-chase premise.',
      howChanged: 'The marshmallow cereal and its leprechaun were a sweet aisle staple in \'84, the colorful marbits the whole appeal.',
      craze: 'An iconic mascot-and-cereal pairing.',
      howAged: 'Still beloved — the marshmallow shapes are legendary. 🍀',
      achievement: '🍀 *Catch the Charms*',
    },
    {
      num: 6,
      emoji: '🐝',
      title: 'THE FRIENDLY MASCOTS',
      tagline: 'Buzzing and chirping for breakfast',
      whatItWas: 'The wholesome animal mascots — the honey-loving bee, the cheerful toucan with the fruity beak, the cuckoo bird wild for chocolate — each one married to its signature cereal.',
      howChanged: 'These bright animal mascots were aisle mainstays in \'84, each instantly tied to its flavor.',
      craze: 'Classic mascot-and-cereal pairings burned into memory.',
      howAged: 'Enduring icons of the breakfast table. 🐝',
      achievement: '🐝 *Follow Your Nose*',
    },
    {
      num: 7,
      emoji: '🍬',
      title: 'THE SUGAR CEREALS',
      tagline: 'Dessert for breakfast',
      whatItWas: 'The whole category of brightly colored, heavily sweetened kid cereals — fruit rings, cocoa puffs, sugar-coated everything — that turned the morning bowl into a sugar rush.',
      howChanged: 'Sugar cereals dominated the kid aisle in \'84, the sweeter and more colorful the better.',
      craze: 'The sugar-cereal boom defined \'80s breakfast (and a lot of dentist visits).',
      howAged: 'Health trends pared them back — making the sugary \'80s bowl nostalgic. 🍬',
      achievement: '🍬 *Sugar Rush*',
    },
    {
      num: 8,
      emoji: '🥣',
      title: 'THE BALANCED BREAKFAST',
      tagline: '…with toast, juice, and milk',
      whatItWas: 'The ubiquitous ad framing — a bowl of sugary cereal shown beside toast, eggs, juice, and fruit, so it could be called "part of a complete breakfast" (the cereal being maybe 5% of it).',
      howChanged: 'Every kid-cereal ad in \'84 ended with the spread-out "balanced breakfast" shot, a wink-worthy bit of marketing.',
      craze: '"Part of a balanced breakfast" became a knowing cultural catchphrase.',
      howAged: 'A fondly-mocked relic of \'80s ad framing. 🥣',
      achievement: '🥣 *Balanced Breakfast*',
    },
    {
      num: 9,
      emoji: '📦',
      title: 'THE BACK OF THE BOX',
      tagline: 'Read it ten times over breakfast',
      whatItWas: 'The cereal box back — mazes, word searches, games, comics, cut-out masks, and mail-away offers — the captive breakfast reading every kid stared at while crunching away.',
      howChanged: 'The box back was prime breakfast entertainment in \'84, read front to back (and back again) over every bowl.',
      craze: 'The cereal-box game is a universal, beloved breakfast memory.',
      howAged: 'A simple pleasure mostly lost — warm nostalgia. 📦',
      achievement: '📦 *Solve the Maze*',
    },
    {
      num: 10,
      emoji: '✉️',
      title: 'THE BOX-TOP MAIL-AWAY',
      tagline: 'Send 2 box tops and $1.99',
      whatItWas: 'The mail-in promotion — clip the box tops, mail them with a little cash, and wait weeks (and weeks) for a toy, patch, or premium to arrive in the mailbox.',
      howChanged: 'Saving box tops for a mail-away prize in \'84 taught kids the agony of waiting "6 to 8 weeks for delivery."',
      craze: 'A quintessential \'80s kid ritual of patience and reward.',
      howAged: 'Vanished with online ordering — peak slow-mail nostalgia. ✉️',
      achievement: '✉️ *6 to 8 Weeks*',
    },
    {
      num: 11,
      emoji: '🏅',
      title: 'THE CHAMPIONS\' CEREAL',
      tagline: 'Breakfast of champions',
      whatItWas: 'The wholesome wheat-flake cereal famous for putting sports champions on its box — an honor athletes coveted and kids recognized at the breakfast table.',
      howChanged: 'Landing on the champions\' cereal box in \'84 was a mark of sporting glory; the orange box was an aisle institution.',
      craze: '"On the box" became shorthand for athletic achievement. (Fits a baseball game especially well.)',
      howAged: 'Still iconic — the champions\' box endures. 🏅',
      achievement: '🏅 *On the Box*',
    },
    {
      num: 12,
      emoji: '🌾',
      title: 'THE HEALTHY CEREALS',
      tagline: 'For the grown-ups',
      whatItWas: 'The other end of the aisle — the bran flakes, granola, and fiber cereals aimed at health-conscious adults, the boxes a sea of beige amid the kid-cereal rainbow.',
      howChanged: 'The health-cereal trend was rising in \'84, the "good for you" boxes a grown-up counterpoint to the sugar bombs.',
      craze: 'The start of the health-cereal wave that reshaped the aisle.',
      howAged: 'Health cereals only grew — the \'80s split is a fun contrast. 🌾',
      achievement: '🌾 *Eat Your Bran*',
    },
    {
      num: 13,
      emoji: '📺',
      title: 'CEREAL & CARTOONS',
      tagline: 'The perfect pairing',
      whatItWas: 'The sacred combo — a giant bowl of sugary cereal balanced on your knees in front of the Saturday-morning cartoons, refilling between shows until the box (or the morning) ran out.',
      howChanged: 'Cereal and cartoons were inseparable in \'84 — the defining Saturday-morning kid experience. (The cartoons get their own set; this is the breakfast side.)',
      craze: 'One of the most beloved kid rituals of the era.',
      howAged: 'Gone with appointment TV — golden nostalgia. 📺',
      achievement: '📺 *Bowl on the Knees*',
    },
    {
      num: 14,
      emoji: '🥛',
      title: 'THE BOTTOM OF THE BOX',
      tagline: 'Sweet milk and crumbs',
      whatItWas: 'The end of the box — the sugary cereal dust and crumbs at the bottom, and the leftover sweetened milk you tipped the bowl back to drink down to the last drop.',
      howChanged: 'Drinking the sweet, colorful leftover milk was the secret best part of the bowl in \'84.',
      craze: 'A small, universal, beloved cereal ritual.',
      howAged: 'Timeless — the sweet-milk finish never gets old. 🥛',
      achievement: '🥛 *Drink the Milk*',
    },
    {
      num: 15,
      emoji: '🥣',
      title: 'THE CEREAL EXPERIENCE',
      tagline: 'Color, sugar, and a cartoon friend',
      whatItWas: 'The complete thing — the colorful boxes, the cartoon mascots, the prize inside, the box-back games, the sweet bowl, and the cartoons playing alongside. A small, perfect pillar of \'80s childhood.',
      howChanged: 'Cereal wasn\'t just breakfast in \'84 — it was an entire kid experience, marketing and magic combined.',
      craze: 'The cereal-and-mascot world is one of the most evocative pieces of \'80s childhood.',
      howAged: 'Pared down over the years — which makes the full \'80s version glow. 🥣',
      achievement: '🥣 *Breakfast of Champions*',
    },
  ],
};