// National 1984 Mall Culture Banner (#901-925) — 20 windows, mixed into ALL 26 ballparks
// Saturday-at-the-mall nostalgia + teenage-hangout warmth + retrospective wink
// All store/brand names are real 1984 references; all descriptive copy is original.
// Hidden achievement: "Closing Time at the Mall" — open all 20 mall culture windows

export const MALL_CULTURE_BANNER = {
  id: 'mallculturebanner_901',
  title: '🛍️ "Meet you at the mall!"',
  subtitle: '(Saturday-at-the-mall nostalgia meets teenage-hangout warmth)',
  icon: '🛍️',
  hiddenAchievement: '🛍️ "Closing Time at the Mall"',
  popups: [
    // ── WINDOW 01: THE FOOD COURT ──
    {
      num: 1,
        achievementId: 'nat_mall_1',
      emoji: '🍕',
      title: 'THE FOOD COURT',
      tagline: 'Grab a tray and find a table',
      whatItWas: 'The central concourse of cuisines — pizza, Chinese, corn dogs, and ice cream ringing a sea of tables and plastic trays, where everyone converged to eat, refuel, and scope the crowd.',
      howChanged: 'The food court was the social hub of the mall in \'84 — the natural meeting point, the resting spot, and the place to be seen between stores.',
      craze: 'A defining feature of the mall experience; the communal eating-and-people-watching zone.',
      howAged: 'Still around but diminished — the bustling food court is peak \'80s mall nostalgia. 🍕',
      achievement: '🍕 *Grab a Tray*',
    },
    // ── WINDOW 02: ORANGE JULIUS ──
    {
      num: 2,
        achievementId: 'nat_mall_2',
      emoji: '🥤',
      title: 'ORANGE JULIUS',
      tagline: 'That frothy orange drink',
      whatItWas: 'The cream-and-orange smoothie from the chain with the little stand — frothy, cold, vaguely orange-creamsicle in flavor, served in a paper cup you carried around the mall.',
      howChanged: 'Orange Julius was a mall institution in \'84; the signature drink was as essential to the trip as the shopping itself.',
      craze: 'A beloved mall-beverage ritual; the frothy orange cup was a status symbol for mall-goers.',
      howAged: 'Mostly faded from malls — the frothy orange memory is pure time-travel. 🥤',
      achievement: '🥤 *Frothy and Cold*',
    },
    // ── WINDOW 03: WALDENBOOKS / B. DALTON ──
    {
      num: 3,
        achievementId: 'nat_mall_3',
      emoji: '📚',
      title: 'THE MALL BOOKSTORE',
      tagline: 'Browse the racks',
      whatItWas: 'The cozy mall bookstore — wall-to-wall paperbacks, spinning racks of bestsellers, magazines up front, and that quiet-ish corner where you could browse for an hour.',
      howChanged: 'The mall bookstore was where you grabbed the latest paperback, a magazine, or a calendar in \'84 — a beloved browsing stop on every mall trip.',
      craze: 'A staple of the mall and many a reader\'s happy place.',
      howAged: 'The mall chains faded with the rise of big-box and online — wistful nostalgia now. 📚',
      achievement: '📚 *Browse the Racks*',
    },
    // ── WINDOW 04: SPENCER GIFTS ──
    {
      num: 4,
        achievementId: 'nat_mall_4',
      emoji: '🔮',
      title: 'SPENCER GIFTS',
      tagline: 'The weird store in the back',
      whatItWas: 'The novelty shop full of gag gifts, lava lamps, black-light posters, risqué cards, and assorted oddities — the slightly edgy store teens dared each other to wander into.',
      howChanged: 'Spencer\'s was the mall\'s resident den of novelties and gags in \'84 — lava lamps glowing, posters in the back, and stuff that made you snicker.',
      craze: 'The quintessential "weird mall store," a rite of passage for curious teens.',
      howAged: 'A beloved oddball mall institution. 🔮',
      achievement: '🔮 *The Weird Store*',
    },
    // ── WINDOW 05: THE RECORD STORE ──
    {
      num: 5,
        achievementId: 'nat_mall_5',
      emoji: '💿',
      title: 'THE MALL RECORD STORE',
      tagline: 'Flip through the bins',
      whatItWas: 'The music shop where you flipped through bins of vinyl LPs and the new cassette racks, posters on the walls, the latest hits playing overhead, and a listening station if you were lucky.',
      howChanged: 'With music huge in \'84, the mall record store was a magnet — flipping through albums, eyeing the wall of cassettes, saving up for the new release.',
      craze: 'Where a generation discovered and bought their music.',
      howAged: 'Faded with digital music — a revered relic for music lovers. 💿',
      achievement: '💿 *Flip Through the Bins*',
    },
    // ── WINDOW 06: THE ARCADE ──
    {
      num: 6,
        achievementId: 'nat_mall_6',
      emoji: '🕹️',
      title: 'THE MALL ARCADE',
      tagline: 'Dark room, glowing screens',
      whatItWas: 'The dim, neon-lit arcade tucked into the mall — rows of cabinets blinking and beeping, a change machine on the wall, and a crowd around whoever was on a hot streak.',
      howChanged: 'The mall arcade was teen headquarters in \'84 — a pocket of quarters, the latest games, and the social scene of the high-score board.',
      craze: 'A core piece of mall teen life; the arcade-as-hangout angle defined the era.',
      howAged: 'The standalone mall arcade mostly vanished — pure nostalgia. 🕹️',
      achievement: '🕹️ *Quarter on the Machine*',
    },
    // ── WINDOW 07: THE COOKIE STAND ──
    {
      num: 7,
        achievementId: 'nat_mall_7',
      emoji: '🍪',
      title: 'THE COOKIE STAND',
      tagline: 'Follow your nose',
      whatItWas: 'The little counter pumping out the smell of warm, fresh-baked cookies that drifted halfway down the concourse — giant chocolate chip cookies, free-sample bites on a tray, and a cookie cake for special occasions.',
      howChanged: 'The cookie stand\'s aroma was an irresistible mall siren song in \'84; the free sample was a beloved tactic.',
      craze: 'One of the mall\'s most evocative smells and treats.',
      howAged: 'Still around — and that warm-cookie smell is instant time travel. 🍪',
      achievement: '🍪 *Free Sample*',
    },
    // ── WINDOW 08: THE ANCHOR DEPARTMENT STORE ──
    {
      num: 8,
        achievementId: 'nat_mall_8',
      emoji: '🏢',
      title: 'THE ANCHOR STORE',
      tagline: 'Through the perfume counter',
      whatItWas: 'The big multi-floor department store at each end of the mall — escalators, the ground-floor cosmetics-and-perfume counter you had to walk through, racks of clothes, and the catalog-pickup desk.',
      howChanged: 'The anchors were the mall\'s gravity in \'84 — you entered through the spritz of the fragrance counter and rode the escalator up to whatever you needed.',
      craze: 'The anchor department store defined the mall\'s layout and shopping experience.',
      howAged: 'Many anchors closed as malls declined — a poignant symbol of the era. 🏢',
      achievement: '🏢 *Ride the Escalator*',
    },
    // ── WINDOW 09: THE CLOTHING CHAINS ──
    {
      num: 9,
        achievementId: 'nat_mall_9',
      emoji: '👖',
      title: 'THE MALL FASHION SHOPS',
      tagline: 'Stonewashed and ready',
      whatItWas: 'The teen-and-young-adult clothing chains — racks of stonewashed denim, trendy tops, and whatever was hot that season, with loud music and a try-it-on energy.',
      howChanged: 'These shops were where mall fashion happened in \'84 — the latest jeans, the going-out tops, the look everyone wanted.',
      craze: 'The engine of \'80s mall style for a generation of teens.',
      howAged: 'Many chains are long gone, fondly remembered by their shoppers. 👖',
      achievement: '👖 *Stonewashed*',
    },
    // ── WINDOW 10: THE SHOE STORES ──
    {
      num: 10,
        achievementId: 'nat_mall_10',
      emoji: '👟',
      title: 'THE SHOE STORE',
      tagline: 'What\'s your size?',
      whatItWas: 'The mall shoe shops — walls of sneakers and dress shoes, the metal foot-measure gadget, the salesperson disappearing into the back for your size, and the new athletic-shoe craze in full swing.',
      howChanged: 'Sneakers were exploding as fashion in \'84, and the mall shoe store (especially the striped-referee-shirt athletic shop) was where you got the fresh pair.',
      craze: 'The mall shoe store fueled the booming sneaker culture.',
      howAged: 'Athletic shoe shops thrived; the measuring gadget is a tactile memory. 👟',
      achievement: '👟 *Lace \'Em Up*',
    },
    // ── WINDOW 11: THE PRETZEL & SNACK STANDS ──
    {
      num: 11,
        achievementId: 'nat_mall_11',
      emoji: '🥨',
      title: 'THE PRETZEL STAND',
      tagline: 'Soft, warm, and salty',
      whatItWas: 'The kiosk twisting out warm soft pretzels, plus the popcorn, nachos, and fountain-drink stands dotting the concourse — grab-and-go snacks to fuel the shopping marathon.',
      howChanged: 'The pretzel stand was a concourse staple in \'84, handing out warm, salty twists in a paper sleeve to shoppers on the move.',
      craze: 'A quintessential mall snack; the warm-pretzel smell is burned into the memory.',
      howAged: 'Still around — the soft pretzel remains a mall classic. 🥨',
      achievement: '🥨 *Twist and Salt*',
    },
    // ── WINDOW 12: THE PHOTO BOOTH ──
    {
      num: 12,
        achievementId: 'nat_mall_12',
      emoji: '📷',
      title: 'THE PHOTO BOOTH',
      tagline: 'Squeeze in — four poses!',
      whatItWas: 'The curtained booth where you and your friends crammed onto the little seat, fed in quarters, and posed through four flashes — then waited for the strip of photos to slide out wet and develop before your eyes.',
      howChanged: 'The photo booth was a beloved mall ritual in \'84 — squeeze in, make faces, and split the strip of photos four ways.',
      craze: 'A communal souvenir factory; the photo strip was a keepsake of every mall trip.',
      howAged: 'Still around but rarer — the curtained booth is a warm, analog memory. 📷',
      achievement: '📷 *Four Poses*',
    },
    // ── WINDOW 13: THE FOUNTAIN ──
    {
      num: 13,
        achievementId: 'nat_mall_13',
      emoji: '⛲',
      title: 'THE MALL FOUNTAIN',
      tagline: 'Make a wish, toss a penny',
      whatItWas: 'The ornamental fountain in the concourse — tiers of cascading water, coins glinting at the bottom from decades of wishes, and a popular meeting-and-resting spot.',
      howChanged: 'The fountain was the mall\'s centerpiece in \'84 — the designated meeting spot, the resting bench, and the wish-tossing destination for kids of all ages.',
      craze: 'A beloved communal landmark; "meet you at the fountain" was a universal phrase.',
      howAged: 'Many were removed as malls modernized — the wishing fountain is a bittersweet memory. ⛲',
      achievement: '⛲ *Make a Wish*',
    },
    // ── WINDOW 14: THE PET STORE ──
    {
      num: 14,
        achievementId: 'nat_mall_14',
      emoji: '🐶',
      title: 'THE MALL PET STORE',
      tagline: 'Just looking at the puppies',
      whatItWas: 'The pet shop with puppies and kittens in the front window — the smell of cedar shavings, the chirping birds, the tanks of fish, and the line of kids pressing their faces to the glass.',
      howChanged: 'The mall pet store was a magnet for kids in \'84 — "just looking at the puppies" was a legitimate reason to linger and dream.',
      craze: 'A guaranteed kid-pleaser; the puppy-in-the-window was a mall highlight.',
      howAged: 'Mostly gone from malls now — a warm, if complicated, nostalgia. 🐶',
      achievement: '🐶 *Puppy in the Window*',
    },
    // ── WINDOW 15: THE CANDY & NUT SHOP ──
    {
      num: 15,
        achievementId: 'nat_mall_15',
      emoji: '🍬',
      title: 'THE CANDY SHOP',
      tagline: 'By the quarter pound',
      whatItWas: 'The glass-jar candy and nut shop — rows of bins filled with chocolates, gummies, roasted nuts, and bridge mix, scooped into paper bags and weighed on a little scale.',
      howChanged: 'The candy-by-the-pound shop was a sweet-tooth\'s paradise in \'84 — the glass bins and the scoop were a tactile, irresistible ritual.',
      craze: 'A delightful mall stop; the paper bag of mixed candy was a treat in itself.',
      howAged: 'Rarer now, but the glass-jar candy shop is instant nostalgia. 🍬',
      achievement: '🍬 *By the Scoop*',
    },
    // ── WINDOW 16: THE CARD & GIFT SHOP ──
    {
      num: 16,
        achievementId: 'nat_mall_16',
      emoji: '💌',
      title: 'THE CARD SHOP',
      tagline: 'A card for every occasion',
      whatItWas: 'The greeting-card and gift store — aisles of cards for every occasion, plus knickknacks, candles, ornaments, and collectible figurines, smelling faintly of potpourri.',
      howChanged: 'The card shop was the go-to in \'84 for a birthday card, a little gift, or seasonal decorations — a tidy, pleasant mall stop.',
      craze: 'A reliable mall fixture for sentiment and small gifts.',
      howAged: 'Still around, though greeting cards faded with digital messages. 💌',
      achievement: '💌 *Pick a Card*',
    },
    // ── WINDOW 17: THE ELECTRONICS / RADIO SHOP ──
    {
      num: 17,
        achievementId: 'nat_mall_17',
      emoji: '🔊',
      title: 'THE ELECTRONICS STORE',
      tagline: 'Gadgets and gizmos',
      whatItWas: 'The mall electronics shop — wall of stereos and speakers, the latest gadgets behind glass, batteries and cables in the aisles, and a demo unit or two blasting a tune.',
      howChanged: 'With home tech booming in \'84, the mall electronics store was a magnet for gadget lovers eyeing the newest gear.',
      craze: 'Where you went to ogle (and occasionally buy) the latest tech.',
      howAged: 'The mall gadget shop gave way to big-box and online. 🔊',
      achievement: '🔊 *Gadgets & Gizmos*',
    },
    // ── WINDOW 18: THE MALL CINEMA ──
    {
      num: 18,
        achievementId: 'nat_mall_18',
      emoji: '🎞️',
      title: 'THE MALL CINEMA',
      tagline: 'Catch a flick after shopping',
      whatItWas: 'The multiplex attached to or inside the mall — a few screens, a glowing marquee, a popcorn-scented lobby, and the perfect cap to a day of shopping.',
      howChanged: 'Catching a movie at the mall theater was a complete Saturday plan in \'84 — shop, eat, then a film.',
      craze: 'The mall-and-a-movie combo defined a generation\'s outings.',
      howAged: 'Many mall theaters closed, but the combo is a warm memory. 🎞️',
      achievement: '🎞️ *Catch a Flick*',
    },
    // ── WINDOW 19: HOLIDAY AT THE MALL ──
    {
      num: 19,
        achievementId: 'nat_mall_19',
      emoji: '🎄',
      title: 'HOLIDAY AT THE MALL',
      tagline: 'Santa\'s village and the rush',
      whatItWas: 'The mall transformed for the holidays — twinkling decorations down the concourse, Santa\'s village with a line of kids for a photo, carols overhead, and the packed, festive crush of holiday shoppers.',
      howChanged: 'The holiday mall was a destination in itself in \'84 — the decorations, the Santa photo, and the buzz of the season\'s biggest shopping rush.',
      craze: 'The decked-out holiday mall is one of the warmest memories of the era.',
      howAged: 'Still magical, but the \'80s holiday-mall bustle is special nostalgia. 🎄',
      achievement: '🎄 *Picture with Santa*',
    },
    // ── WINDOW 20: JUST HANGING OUT ──
    {
      num: 20,
        achievementId: 'nat_mall_20',
      emoji: '😎',
      title: 'HANGING AT THE MALL',
      tagline: 'No money, all day',
      whatItWas: 'The pure teenage art of just being at the mall — no agenda, no cash, just walking the loop with friends, people-watching, window shopping, and killing a whole Saturday in the climate-controlled wonderland.',
      howChanged: 'For teens in \'84, the mall was the hangout — the place to see and be seen, with or without a dollar in your pocket.',
      craze: '"Mall rat" became a whole identity; the aimless mall hangout defined \'80s adolescence.',
      howAged: 'A vanished rite of passage — the mall-as-hangout is deeply missed. 😎',
      achievement: '😎 *Mall Rat*',
    },
  ],
};