// National Music & MTV (1984) Banner (#976-1000) — 23 windows, mixed into ALL 26 ballparks
// Turn-it-up music-video-era hype + golden-year reverence + retrospective wink
// All artist/album names and facts are real; all descriptive copy is original. ZERO lyrics reproduced.
// Hidden achievement: "I Want My MTV" — open all 23 music windows

export const MUSIC_MTV_BANNER = {
  id: 'musicmtvbanner_976',
  title: '🎵 "Crank it up — the hits are playing!"',
  subtitle: '(music-video-era hype meets golden-year reverence)',
  icon: '🎵',
  hiddenAchievement: '🎵 "I Want My MTV"',
  popups: [
    // ── WINDOW 01: MTV ──
    {
      num: 1,
      emoji: '📺',
      title: 'MTV',
      tagline: 'The channel that played the videos',
      whatItWas: 'Music Television — the cable channel that ran music videos around the clock, hosted by "VJs," and turned songs into must-see visual events. By 1984 it had reshaped the entire music business.',
      howChanged: 'MTV was a cultural juggernaut in \'84 — making and breaking artists on the strength of their videos, and turning "did you see that video?" into the question of the day.',
      craze: 'Changed how music was sold, consumed, and imagined — the video became as important as the song.',
      howAged: 'A defining force of \'80s culture; "I want my MTV" is an era unto itself. 📺',
      achievement: '📺 *Video Killed the Radio Star*',
    },
    // ── WINDOW 02: MICHAEL JACKSON & THRILLER ──
    {
      num: 2,
      emoji: '🧤',
      title: 'MICHAEL JACKSON',
      tagline: 'The King of Pop at his peak',
      whatItWas: 'The biggest star on the planet, riding Thriller — the best-selling album in history — to a level of fame pop music had never seen, complete with the single sequined glove, the moonwalk, and groundbreaking videos.',
      howChanged: 'Thriller was still throwing off hit after hit in \'84, Jackson swept the Grammys, and his every move was a global event.',
      craze: 'The definitive pop superstar; Thriller set a bar that may never be matched.',
      howAged: 'Immortal — the album, the moonwalk, and the glove are eternal pop iconography. 🧤',
      achievement: '🧤 *One Glove*',
    },
    // ── WINDOW 03: PRINCE & PURPLE RAIN ──
    {
      num: 3,
      emoji: '💜',
      title: 'PRINCE',
      tagline: 'Purple Rain takes over',
      whatItWas: 'The boundary-shattering musical genius who in 1984 released Purple Rain — both a chart-dominating album and a hit film — cementing him as one of the most original artists of his generation.',
      howChanged: 'Purple Rain was everywhere in \'84 — the album topped the charts, the movie packed theaters, and Prince became a phenomenon.',
      craze: 'A landmark album-and-film moment; Prince\'s purple era is one of music\'s great peaks.',
      howAged: 'Legendary — Purple Rain is considered one of the greatest albums ever made. 💜',
      achievement: '💜 *Purple Reign*',
    },
    // ── WINDOW 04: MADONNA ──
    {
      num: 4,
      emoji: '🎤',
      title: 'MADONNA',
      tagline: 'The new queen of pop',
      whatItWas: 'The breakout superstar who ascended in 1984 — stacked bangles, lace, and a string of irresistible dance-pop hits that made her the defining new female voice of the decade.',
      howChanged: 'Madonna\'s rise in \'84 was unstoppable — MTV exposure, a blockbuster debut album, and a bold image that set trends overnight.',
      craze: 'A cultural force who redefined pop stardom for women; the look was copied in every mall.',
      howAged: 'A pop icon for the ages; the early-Madonna look is permanent \'80s iconography. 🎤',
      achievement: '🎤 *Like a Star*',
    },
    // ── WINDOW 05: BRUCE SPRINGSTEEN & BORN IN THE U.S.A. ──
    {
      num: 5,
      emoji: '🇺🇸',
      title: 'BRUCE SPRINGSTEEN',
      tagline: 'The Boss and a record-breaking album',
      whatItWas: 'The Boss releasing Born in the U.S.A. — a blockbuster album with seven top-ten hits, an iconic red-cap-and-white-tee cover, and stadium-sized anthems that made him a global superstar.',
      howChanged: 'Born in the U.S.A. was a juggernaut in \'84, its title track and videos inescapable, Springsteen playing the biggest venues in the country.',
      craze: 'One of the best-selling albums of all time; the red bandana and rolled sleeves are burned into the era.',
      howAged: 'A cornerstone of American rock; the album only grows in stature. 🇺🇸',
      achievement: '🇺🇸 *The Boss*',
    },
    // ── WINDOW 06: VAN HALEN & 1984 ──
    {
      num: 6,
      emoji: '🎹',
      title: 'VAN HALEN',
      tagline: 'The album literally called 1984',
      whatItWas: 'The hard-rock titans who released the album titled 1984 — synth-driven, guitar-shredding, and featuring the blockbuster keyboard-anthem single that became one of the year\'s signature songs.',
      howChanged: '1984 was Van Halen\'s commercial peak in \'84, the synthesizer intro to the lead single on every radio and video channel.',
      craze: 'A landmark of arena rock and the moment synth met shred; the album defined the year.',
      howAged: 'A beloved hard-rock classic; the keyboard riff is instantly recognizable forever. 🎹',
      achievement: '🎹 *Jump*',
    },
    // ── WINDOW 07: CYNTHIA LAUPER ──
    {
      num: 7,
      emoji: '🌈',
      title: 'CYNDI LAUPER',
      tagline: 'Technicolor hair and huge hits',
      whatItWas: 'The technicolor pop star with the rainbow hair and the powerhouse voice — a debut album packed with hits and an image that was pure, joyful, New York new-wave attitude.',
      howChanged: 'Cyndi Lauper was one of \'84\'s biggest new stars — MTV-dominating videos, chart-topping singles, and a look copied across the decade (and a key player in the Rock \'n\' Wrestling crossover).',
      craze: 'A defining voice and look of the era; her hits remain anthems.',
      howAged: 'Beloved — the songs and the rainbow style are pure \'80s joy. 🌈',
      achievement: '🌈 *True Colors*',
    },
    // ── WINDOW 08: THE WALKMAN GENERATION ──
    {
      num: 8,
      emoji: '🎧',
      title: 'MUSIC ON THE GO',
      tagline: 'Your own private soundtrack',
      whatItWas: 'The cassette-and-headphones revolution — for the first time, you could carry your music with you, walking around in your own private world of sound. (The device itself is in the Electronics set; this is the music-culture angle.)',
      howChanged: 'Making the perfect mixtape and walking around plugged into your favorite album was a brand-new kind of freedom in \'84.',
      craze: 'Personal, portable music changed how a generation listened.',
      howAged: 'The format changed, but "your own soundtrack" never went away. 🎧',
      achievement: '🎧 *Press Play*',
    },
    // ── WINDOW 09: THE MIXTAPE ──
    {
      num: 9,
      emoji: '📼',
      title: 'THE MIXTAPE',
      tagline: 'Recorded straight off the radio',
      whatItWas: 'The lovingly assembled cassette of favorite songs — taped off the radio (racing to hit record before the DJ talked over the intro), or dubbed track by track, then given to a crush or a friend as a labor of love.',
      howChanged: 'Making a mixtape was an art form and a love language in \'84 — handwritten track lists and all.',
      craze: 'The mixtape is one of the most beloved rituals of the cassette era.',
      howAged: 'The playlist replaced it, but the mixtape\'s heart is legendary. 📼',
      achievement: '📼 *Hit Record*',
    },
    // ── WINDOW 10: THE TOP 40 RADIO COUNTDOWN ──
    {
      num: 10,
      emoji: '📻',
      title: 'THE WEEKLY COUNTDOWN',
      tagline: 'And the number one song is...',
      whatItWas: 'The Sunday radio ritual — the nationally syndicated countdown of the week\'s biggest hits, building suspense all the way to number one, with listeners taping their favorites and rooting for their songs to climb.',
      howChanged: 'The weekly Top 40 countdown was appointment radio in \'84, the chart race a genuine national pastime.',
      craze: 'The countdown made the charts feel like a sport.',
      howAged: 'Streaming charts replaced the suspense — nostalgic for radio fans. 📻',
      achievement: '📻 *Number One*',
    },
    // ── WINDOW 11: THE BOOMBOX & STREET MUSIC ──
    {
      num: 11,
      emoji: '🔈',
      title: 'THE BOOMBOX CULTURE',
      tagline: 'Carry the party with you',
      whatItWas: 'The shoulder-mounted boombox blasting on the sidewalk, the soundtrack to breakdancing on a flattened cardboard box, the music spilling out into the street. (The device is in the Electronics set; this is the street-music-culture angle.)',
      howChanged: 'Hip-hop and breakdancing were surging in \'84, the boombox their portable, defiant heartbeat.',
      craze: 'A foundational image of \'80s street and music culture.',
      howAged: 'Iconic — the boombox-and-breakdancing image is permanent \'80s shorthand. 🔈',
      achievement: '🔈 *Pump Up the Volume*',
    },
    // ── WINDOW 12: THE RISE OF HIP-HOP ──
    {
      num: 12,
      emoji: '🎤',
      title: 'EARLY HIP-HOP',
      tagline: 'A brand-new sound from the block',
      whatItWas: 'The young, electrifying genre breaking out of the boroughs — DJs scratching, MCs rhyming, beats built from breakbeats — pushing into the mainstream and about to change music forever.',
      howChanged: 'Hip-hop was crossing over in \'84 — early stars hitting MTV and the charts, the culture (rapping, DJing, breakdancing, graffiti) bursting into national view.',
      craze: 'The ground floor of what would become the most dominant genre in music.',
      howAged: 'Historic — 1984 caught hip-hop at its thrilling, world-changing dawn. 🎤',
      achievement: '🎤 *On the Mic*',
    },
    // ── WINDOW 13: SYNTH-POP & NEW WAVE ──
    {
      num: 13,
      emoji: '🎹',
      title: 'SYNTH-POP & NEW WAVE',
      tagline: 'The sound of the future',
      whatItWas: 'The wave of synthesizer-driven bands — sleek, electronic, often British — whose shimmering keyboards and stylish videos were perfect for the MTV age.',
      howChanged: 'New wave and synth-pop ruled the charts and the video channel in \'84, their futuristic sound the height of cool.',
      craze: 'Defined a huge swath of the \'80s sound and look.',
      howAged: 'Endlessly revived; the synth shimmer is pure \'80s. 🎹',
      achievement: '🎹 *Synthesize*',
    },
    // ── WINDOW 14: TINA TURNER'S COMEBACK ──
    {
      num: 14,
      emoji: '🔥',
      title: 'TINA TURNER',
      tagline: 'The comeback of the year',
      whatItWas: 'The powerhouse vocalist who staged one of the greatest comebacks in music history in 1984 — a blockbuster solo album, a signature hit, and a triumphant return to the very top.',
      howChanged: 'Her comeback album was a smash in \'84, the lead single a chart-topper, and Tina once again a global superstar.',
      craze: 'A legendary comeback story and a defining voice of the era.',
      howAged: 'Iconic — the comeback is the stuff of music legend. 🔥',
      achievement: '🔥 *Simply the Best*',
    },
    // ── WINDOW 15: THE BRITISH INVASION (SECOND WAVE) ──
    {
      num: 15,
      emoji: '🇬🇧',
      title: 'THE BRITS ON MTV',
      tagline: 'London takes the video channel',
      whatItWas: 'The wave of stylish British bands who dominated MTV in the early-to-mid \'80s — sharp looks, big hooks, and videos tailor-made for the channel, a "second British Invasion" powered by video.',
      howChanged: 'British acts were all over the American charts and MTV in \'84, their image-conscious style setting trends.',
      craze: 'A defining force of the MTV era\'s sound and look.',
      howAged: 'A beloved chapter of \'80s pop. 🇬🇧',
      achievement: '🇬🇧 *Second Invasion*',
    },
    // ── WINDOW 16: THE POWER BALLAD ──
    {
      num: 16,
      emoji: '🤘',
      title: 'THE POWER BALLAD',
      tagline: 'Lighters up',
      whatItWas: 'The arena-rock slow burner — soft verses building to a soaring, guitar-drenched climax, the kind of song that filled stadiums with raised lighters swaying in the dark.',
      howChanged: 'The power ballad was a radio and concert staple in \'84, every big rock band reaching for that lighters-up moment.',
      craze: 'A quintessential \'80s rock form.',
      howAged: 'Beloved and a little cheesy in the best way — eternal singalong fuel. 🤘',
      achievement: '🤘 *Lighters Up*',
    },
    // ── WINDOW 17: THE ALBUM & THE LINER NOTES ──
    {
      num: 17,
      emoji: '💿',
      title: 'THE VINYL ALBUM',
      tagline: 'Drop the needle, read the sleeve',
      whatItWas: 'The full-album experience — the big cardboard sleeve, the gatefold art, the lyric sheet and liner notes you pored over while the record played, side A then flip to side B. (The CD is in the Electronics set; this is the vinyl-album-as-experience angle.)',
      howChanged: 'Buying the record, studying the cover art, and listening front to back was how you fell in love with an album in \'84.',
      craze: 'The album as a complete artistic object — art, notes, and all.',
      howAged: 'Vinyl roared back; the album-art ritual never lost its magic. 💿',
      achievement: '💿 *Side A, Side B*',
    },
    // ── WINDOW 18: THE CONCERT & THE TOUR TEE ──
    {
      num: 18,
      emoji: '🎫',
      title: 'THE LIVE SHOW',
      tagline: 'Stub in your pocket, shirt on your back',
      whatItWas: 'The arena and stadium concert — ears ringing, the roar of the crowd, the encore, and the merch table where you grabbed the tour T-shirt you\'d wear proudly for years.',
      howChanged: 'With superstars touring huge in \'84, the concert was a major event, and the tour tee a badge of honor.',
      craze: 'Live music and the tour shirt are timeless rites of fandom.',
      howAged: 'Eternal — the concert tee never went out of style. 🎫',
      achievement: '🎫 *Tour Tee*',
    },
    // ── WINDOW 19: THE MUSIC VIDEO AS EVENT ──
    {
      num: 19,
      emoji: '🎬',
      title: 'THE BLOCKBUSTER VIDEO',
      tagline: 'A short film, not just a clip',
      whatItWas: 'The big-budget, mini-movie music video — elaborate storylines, choreography, and special effects that turned the world premiere of a video into a genuine television event.',
      howChanged: 'The era\'s biggest videos in \'84 were lavish productions that audiences gathered to watch like a TV special.',
      craze: 'The video became an art form and a marketing juggernaut.',
      howAged: 'Foundational to how music and image fused forever after. 🎬',
      achievement: '🎬 *World Premiere*',
    },
    // ── WINDOW 20: THE GRAMMYS & AWARDS SHOWS ──
    {
      num: 20,
      emoji: '🏆',
      title: 'THE GRAMMYS & AWARDS SHOWS',
      tagline: 'And the award goes to...',
      whatItWas: 'The glittering awards shows — the Grammys and the brand-new MTV awards — where the year\'s biggest stars gathered, performed, and took home the trophies, all broadcast to millions.',
      howChanged: 'Award season in \'84 was a showcase of the year\'s dominant artists, with record-sweeping wins making headlines.',
      craze: 'The awards crowned the era\'s giants and created iconic live moments.',
      howAged: 'Still music\'s big nights — the \'80s ceremonies are legendary. 🏆',
      achievement: '🏆 *Sweep the Awards*',
    },
    // ── WINDOW 21: DANCE & THE CLUB ──
    {
      num: 21,
      emoji: '💃',
      title: 'DANCE & THE CLUB',
      tagline: 'Lights, beat, and a packed floor',
      whatItWas: 'The clubs and dance floors pulsing with the era\'s beat — synth and dance hits, flashing lights, and a crowd moving as one under the glow.',
      howChanged: 'Dance music and club culture were thriving in \'84, the floor packed for the year\'s biggest grooves.',
      craze: 'The \'80s dance floor is a defining cultural image.',
      howAged: 'Timeless — the era\'s dance hits still fill floors. 💃',
      achievement: '💃 *Hit the Floor*',
    },
    // ── WINDOW 22: THE ONE-HIT WONDERS ──
    {
      num: 22,
      emoji: '✨',
      title: 'THE ONE-HIT WONDERS',
      tagline: 'That song you can\'t forget',
      whatItWas: 'The artists who caught lightning once — a single inescapable smash that defined a summer, then faded, leaving behind a song burned permanently into everyone\'s memory.',
      howChanged: 'The year was full of irresistible one-off hits in \'84 that ruled the radio for a few glorious weeks.',
      craze: 'One-hit wonders are some of the most fondly remembered songs of the era.',
      howAged: 'Pure nostalgic gold — instant singalongs decades later. ✨',
      achievement: '✨ *One and Done*',
    },
    // ── WINDOW 23: THE WHOLE GOLDEN YEAR ──
    {
      num: 23,
      emoji: '🎶',
      title: 'THE WHOLE GOLDEN YEAR',
      tagline: 'Maybe the best year pop ever had',
      whatItWas: 'The big picture — a single year when Thriller, Purple Rain, Born in the U.S.A., 1984, Madonna\'s rise, Tina\'s comeback, and the MTV revolution were all happening at once. An almost impossibly stacked moment in music history.',
      howChanged: 'Turn on the radio or the video channel in \'84 and you\'d hit an all-timer — the hits were absurdly deep that year.',
      craze: 'Frequently cited as one of the greatest single years in pop-music history.',
      howAged: 'Only looks more legendary with time. 🎶',
      achievement: '🎶 *Greatest Year*',
    },
  ],
};