// National TV Show Banners (25 shows × 5 popup listings each = 125 total popups)
// Mixed into all 26 ballparks — prime-time 1983–84 television guide
// Batch 1 of 4: Miami Vice, Dallas, Dynasty, Simon & Simon

export const NATIONAL_TV_BANNERS = [
  // ── #001 MIAMI VICE ──
  {
    id: 'tvbanner_001',
    title: '📺 Don\'t miss this week\'s all-new episode of *Miami Vice* — Friday on NBC!',
    subtitle: '(neon-pink-and-teal Art Deco glow; pastel suit, no socks)',
    icon: '📺',
    popups: [
      {
        num: 1,
        emoji: '🔫',
        day: 'Friday',
        time: '9:00/8:00c',
        network: 'NBC',
        plot: 'Crockett and Tubbs go undercover at a Bayside marina to unmask a smuggler known only as "the Tarpon," but a stolen Ferrari and a wired informant turn the sting into a shootout by sundown.',
        stars: '**Don Johnson** and **Philip Michael Thomas**',
        guests: '**Charo**, **Scott Baio**, and **Lucille Ball**',
        location: 'Coconut Grove art dealer',
        slogan: '*NBC — "Be There."*',
      },
      {
        num: 2,
        emoji: '🔫',
        day: 'Friday',
        time: '9:00/8:00c',
        network: 'NBC',
        plot: 'A pop star\'s bodyguard turns up dead in the Glades, and the trail leads to a recording studio laundering cash through platinum records.',
        stars: '**Don Johnson** and **Philip Michael Thomas**',
        guests: '**Mr. T**, **Morgan Fairchild**, and **Rip Taylor**',
        location: 'flamboyant club promoter',
        slogan: '*NBC — "Be There."*',
      },
      {
        num: 3,
        emoji: '🔫',
        day: 'Friday',
        time: '9:00/8:00c',
        network: 'NBC',
        plot: 'When a federal witness vanishes from a South Beach high-rise, Castillo orders his detectives to trust no one inside the department.',
        stars: '**Don Johnson** and **Philip Michael Thomas**',
        guests: '**Edward James Olmos** as Lt. Castillo, **Grace Jones**, **Robert Goulet**, and **Gary Coleman**',
        location: 'street kid who saw too much',
        slogan: '*NBC — "Be There."*',
      },
      {
        num: 4,
        emoji: '🔫',
        day: 'Friday',
        time: '9:00/8:00c',
        network: 'NBC',
        plot: 'A diamond heist at a Brickell Avenue gala goes sideways when the getaway boat belongs to one of Crockett\'s old Navy buddies.',
        stars: '**Don Johnson** and **Philip Michael Thomas**',
        guests: '**Joan Collins**, **Wayne Newton** as a casino fixer, and **Charo** (she gets around)',
        location: 'nightclub owner',
        slogan: '*NBC — "Be There."*',
      },
      {
        num: 5,
        emoji: '🔫',
        day: 'Friday',
        time: '9:00/8:00c',
        network: 'NBC',
        plot: 'Tubbs falls for a nightclub singer who\'s the only witness to a cartel hit, and Crockett has 48 hours to keep her alive through Miami\'s neon underworld.',
        stars: '**Don Johnson** and **Philip Michael Thomas**',
        guests: '**Apollonia**, **Jack Klugman**, and **Abe Vigoda**',
        location: 'retired hitman',
        slogan: '*NBC — "Be There."*',
      },
    ],
    achievementId: 'tvbanner_miamiavice',
  },

  // ── #002 DALLAS ──
  {
    id: 'tvbanner_002',
    title: '📺 Who\'s scheming now? An all-new *Dallas* — Friday on CBS!',
    subtitle: '(oil derrick; ten-gallon hat; Southfork at sunset)',
    icon: '📺',
    popups: [
      {
        num: 1,
        emoji: '💰',
        day: 'Friday',
        time: '10:00/9:00c',
        network: 'CBS',
        plot: 'J.R. quietly buys up the notes on a rival\'s offshore leases, but Bobby uncovers the paper trail before the ink is dry.',
        stars: '**Larry Hagman**, **Patrick Duffy**, and **Linda Gray**',
        guests: '**Robert Goulet** as a Gulf Coast wildcatter and **Eva Gaborr** as his sharp-tongued wife',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
      {
        num: 2,
        emoji: '💰',
        day: 'Friday',
        time: '10:00/9:00c',
        network: 'CBS',
        plot: 'Sue Ellen checks into a clinic under a false name, and J.R. spends the hour making sure no one at Ewing Oil finds out why.',
        stars: '**Larry Hagman** and **Linda Gray**',
        guests: '**Morgan Fairchild** as a society reporter and **George Kennedy** as a family doctor with loose lips',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
      {
        num: 3,
        emoji: '💰',
        day: 'Friday',
        time: '10:00/9:00c',
        network: 'CBS',
        plot: 'A long-lost Ewing cousin arrives at Southfork claiming a stake in the ranch, and Miss Ellie demands the truth before the will is read.',
        stars: '**Larry Hagman**, **Patrick Duffy**, and **Barbara Bel Geddes**',
        guests: '**Lana Turner** as a glamorous houseguest who knows the family\'s oldest secret',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
      {
        num: 4,
        emoji: '💰',
        day: 'Friday',
        time: '10:00/9:00c',
        network: 'CBS',
        plot: 'J.R.\'s latest power play collapses when a senator he\'s bankruptrolled gets cold feet on the courthouse steps.',
        stars: '**Larry Hagman** and **Ken Kercheval**',
        guests: '**Robert Stack** as the wavering senator and **Dyan Cannon** as a lobbyist playing both sides',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
      {
        num: 5,
        emoji: '💰',
        day: 'Friday',
        time: '10:00/9:00c',
        network: 'CBS',
        plot: 'A fire at an Ewing refinery may be sabotage, and Bobby races to find the truth before the insurance men — and J.R. — rewrite the story.',
        stars: '**Patrick Duffy** and **Victoria Principal**',
        guests: '**Ernest Borgnine** as a fire marshal and **Stella Stevens** as a refinery foreman\'s widow',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
    ],
    achievementId: 'tvbanner_dallas',
  },

  // ── #003 DYNASTY ──
  {
    id: 'tvbanner_003',
    title: '📺 The Carringtons are back! An all-new *Dynasty* — Wednesday on ABC!',
    subtitle: '(shoulder pads; champagne flute; a slammed limousine door)',
    icon: '📺',
    popups: [
      {
        num: 1,
        emoji: '💎',
        day: 'Wednesday',
        time: '10:00/9:00c',
        network: 'ABC',
        plot: 'Alexis maneuvers to seize a controlling block of Denver-Carrington stock, and Blake fights back with a secret weapon of his own.',
        stars: '**Linda Evans** and **John Forsythe**',
        guests: '**Ricardo Montalbán** as an oil minister and **Zsa Zsa Gaborr** as a rival socialite',
        slogan: '*ABC — "That Special Feeling, on ABC."*',
      },
      {
        num: 2,
        emoji: '💎',
        day: 'Wednesday',
        time: '10:00/9:00c',
        network: 'ABC',
        plot: 'Krystle plans a charity gala while Alexis plots to ruin it in front of all Denver. Starring **Linda Evans** and **Joan Collins**.',
        guests: '**Robert Goulet** as the evening\'s entertainment and **Joan Rivers** as a gossip columnist who knows where the bodies are buried',
        slogan: '*ABC — "That Special Feeling, on ABC."*',
      },
      {
        num: 3,
        emoji: '💎',
        day: 'Wednesday',
        time: '10:00/9:00c',
        network: 'ABC',
        plot: 'A mysterious European arrives claiming to be Alexis\'s first husband — and he hasn\'t aged a day. Or has he been dead all along?',
        stars: '**Joan Collins** and **John Forsythe**',
        guests: '**Roger Moore**-styled charmer **George Hamilton** and **Eartha Kitt** as a fortune teller',
        slogan: '*ABC — "That Special Feeling, on ABC."*',
      },
      {
        num: 4,
        emoji: '💎',
        day: 'Wednesday',
        time: '10:00/9:00c',
        network: 'ABC',
        plot: 'Blake\'s offshore deal hangs on one signature, and Alexis owns the pen. Starring **John Forsythe** and **Joan Collins**.',
        guests: '**Lloyd Bridges** as a maritime tycoon and **Dyan Evans** as the woman he never forgot',
        slogan: '*ABC — "That Special Feeling, on ABC."*',
      },
      {
        num: 5,
        emoji: '💎',
        day: 'Wednesday',
        time: '10:00/9:00c',
        network: 'ABC',
        plot: 'A film crew takes over the lobby, and the leading lady refuses to leave her suite until her ex-husband checks out.',
        stars: '**Connie Sellecca** and **James Brolin**',
        guests: '**Joan Collins** as the diva and **George Hamilton** as the ex who booked the room on purpose',
        slogan: '*ABC — "That Special Feeling, on ABC."*',
      },
    ],
    achievementId: 'tvbanner_dynasty',
  },

  // ── #006 SIMON & SIMON ──
  {
    id: 'tvbanner_006',
    title: '📺 Two brothers, one case — an all-new *Simon & Simon* on CBS!',
    subtitle: '(beat-up pickup and a sports car; San Diego palms)',
    icon: '📺',
    popups: [
      {
        num: 1,
        emoji: '🔍',
        day: 'Thursday',
        time: '9:00/8:00c',
        network: 'CBS',
        plot: 'A.J. goes undercover at a yacht club while Rick works the docks, both chasing the same insurance fraud from opposite ends of San Diego Bay.',
        stars: '**Gerald McRaney** and **Jameson Parker**',
        guests: '**Robert Loggia** as the marina owner and **Markie Post**-styled underwriter',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
      {
        num: 2,
        emoji: '🔍',
        day: 'Thursday',
        time: '9:00/8:00c',
        network: 'CBS',
        plot: 'A country singer hires the brothers to find out who\'s been sabotaging her tour bus before opening night at the county fair.',
        stars: '**Gerald McRaney** and **Jameson Parker**',
        guests: '**Tammy Wynette** as the singer and **Slim Pickens** as a rival promoter',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
      {
        num: 3,
        emoji: '🔍',
        day: 'Thursday',
        time: '9:00/8:00c',
        network: 'CBS',
        plot: 'Rick\'s poker buddy turns up missing along with a briefcase that several very serious men would like back.',
        stars: '**Gerald McRaney** and **Jameson Parker**',
        guests: '**Robert Conrad** as a casino boss and **Stella Stevens** as the buddy\'s worried sister',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
      {
        num: 4,
        emoji: '🔍',
        day: 'Thursday',
        time: '9:00/8:00c',
        network: 'CBS',
        plot: 'When a rival firm — the **Clark & Behh Detective Agency** — keeps beating the Simons to every client in town, Rick and A.J. set a trap to find out who\'s tipping them off. Turns out the competition isn\'t playing fair, and the brothers turn the tables in the last act.',
        stars: '**Gerald McRaney** and **Jameson Parker**',
        guests: '**Tom Bosley** as a rumpled rival P.I. and **Audrey Landers** as the double-dealing receptionist',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
      {
        num: 5,
        emoji: '🔍',
        day: 'Thursday',
        time: '9:00/8:00c',
        network: 'CBS',
        plot: 'Mom Simon insists on tagging along to a stakeout, and promptly cracks the case the boys have been blowing for a week.',
        stars: '**Gerald McRaney**, **Jameson Parker**, and **Mary Carver**',
        guests: '**Eve Arden** as Mom\'s bridge partner and **Abe Vigoda** as a suspect who folds under her questioning',
        slogan: '*CBS — "We\'ve Got the Touch."*',
      },
    ],
    easterEgg: '🔍 Hidden Easter egg in popup #4 — the **Clark & Behh Detective Agency** appears (a reference)',
    achievementId: 'tvbanner_simonsimon',
  },
];