// National Ballpark Promo Nights & Giveaways Banner (#1076-1100) - 25 windows, mixed into ALL 26 ballparks
// 13 realistic promo days/nights + 12 silly/invented theme nights
// All descriptive copy is original. Real promo traditions described in original wording; silly nights are original inventions.
// NO bobblehead night (already a dedicated in-game ballpark event).
// Band name "Dregs of Humanity" (Window 19) kept exactly as specified.
// Hidden achievement: "Promo Night Regular" - open all 25 promo-night windows

export const PROMO_NIGHTS_BANNER = {
  id: 'promonightsbanner_1076',
  title: '🎟️ "Tonight only - promo night at the ballpark!"',
  subtitle: '(giveaways, theme nights, and post-game shows)',
  icon: '🎟️',
  hiddenAchievement: '🎨 "Promo Night Regular"',
  popups: [
    // ── REALISTIC PROMO DAYS / NIGHTS (13) ──
    {
      num: 1,
        achievementId: 'nat_promoNights_1',
      emoji: '🏏',
      title: 'BAT DAY',
      tagline: 'A free bat for every kid!',
      whatItIs: 'A free miniature bat handed to every kid at the gate - the clack of wood in little hands all afternoon, a souvenir that ended up in bedrooms across the city.',
      theFun: 'Kids walking out clutching a bat almost as tall as they are.',
      theNote: 'Somewhere, a kid is using it as a sword against his sibling in the backseat.',
      howItLands: 'A classic, beloved giveaway. 🏏',
      achievement: '🏏 *Free Bat*',
    },
    {
      num: 2,
        achievementId: 'nat_promoNights_2',
      emoji: '🎆',
      title: 'FIREWORKS NIGHT',
      tagline: 'Stick around after the final out!',
      whatItIs: 'The post-game fireworks show - once the last out is recorded, the lights go down and the sky lights up over the stadium, fans sprawled on the outfield grass or craning from the seats.',
      theFun: 'A ballgame AND a fireworks show on the same ticket.',
      theNote: 'The outfield grass fills up with blankets faster than you\'d believe.',
      howItLands: 'The biggest draw of the summer. 🎆',
      achievement: '🎆 *Light Up the Sky*',
    },
    {
      num: 3,
        achievementId: 'nat_promoNights_3',
      emoji: '🧢',
      title: 'CAP DAY',
      tagline: 'Free team cap at the gate!',
      whatItIs: 'A free team ball cap for fans walking in - an instant sea of matching caps filling the stands, the most wearable giveaway of them all.',
      theFun: 'Everybody loves a free hat, and it turns the crowd into a unified wall of team colors.',
      theNote: 'Spot the one guy wearing it backwards on the jumbotron.',
      howItLands: 'A reliably popular giveaway. 🧢',
      achievement: '🧢 *Lid for Everyone*',
    },
    {
      num: 4,
        achievementId: 'nat_promoNights_4',
      emoji: '💙',
      title: 'FAN APPRECIATION NIGHT',
      tagline: 'This one\'s for you, fans!',
      whatItIs: 'The season\'s thank-you to the faithful - prize giveaways, raffles for big-ticket items (a car, a trip, season tickets), and players tipping their caps to the crowd that showed up all year.',
      theFun: 'Your seat number might just win you something huge.',
      theNote: 'Keep that ticket stub handy - they\'re drawing numbers.',
      howItLands: 'A heartfelt season-capper. 💙',
      achievement: '💙 *Lucky Seat Number*',
    },
    {
      num: 5,
        achievementId: 'nat_promoNights_5',
      emoji: '👴',
      title: 'OLD-TIMERS\' DAY',
      tagline: 'The legends take the field once more',
      whatItIs: 'The beloved tradition where retired greats don the old uniforms for an exhibition inning or two - slower, rounder, grayer, but still drawing the loudest cheers of the year.',
      theFun: 'Seeing the heroes of yesterday tip their caps one more time.',
      theNote: 'The legends\' bellies have grown, but the ovations are bigger than ever.',
      howItLands: 'A genuinely emotional fan favorite. 👴',
      achievement: '👴 *The Legends Return*',
    },
    {
      num: 6,
        achievementId: 'nat_promoNights_6',
      emoji: '🌭',
      title: 'DOLLAR DOG NIGHT',
      tagline: 'Hot dogs, just a buck!',
      whatItIs: 'The glorious promotion where hot dogs drop to a dollar, and fans eat a frankly unwise number of them over nine innings.',
      theFun: 'Cheap eats and the personal challenge of "how many can I put away?"',
      theNote: 'Somewhere in section 104, a man is on his eleventh.',
      howItLands: 'A wildly popular (and slightly dangerous) draw. 🌭',
      achievement: '🌭 *Buck a Dog*',
    },
    {
      num: 7,
        achievementId: 'nat_promoNights_7',
      emoji: '🎍',
      title: 'OPENING DAY',
      tagline: 'Baseball is back!',
      whatItIs: 'The grandest day on the calendar - bunting draped on the railings, the lineups announced one by one, a ceremonial first pitch, and the whole season\'s hope packed into one electric afternoon.',
      theFun: 'Every team\'s in first place, and everything feels possible.',
      theNote: 'Somehow it\'s a sellout, even when it\'s 40 degrees and drizzling.',
      howItLands: 'The most hopeful day in sports. 🎍',
      achievement: '🎍 *Play Ball*',
    },
    {
      num: 8,
        achievementId: 'nat_promoNights_8',
      emoji: '📸',
      title: 'PHOTO DAY',
      tagline: 'Get up close with the players!',
      whatItIs: 'The pre-game promotion where fans line the field to snap photos of the players up close - autographs if you\'re lucky, and a roll of film full of your heroes.',
      theFun: 'A rare chance to get right next to the stars.',
      theNote: 'Hope you brought enough film - and that your shots come out.',
      howItLands: 'A cherished fan tradition. 📸',
      achievement: '📸 *Up Close*',
    },
    {
      num: 9,
        achievementId: 'nat_promoNights_9',
      emoji: '⛑️',
      title: 'HELMET DAY',
      tagline: 'Free batting helmet for the kids!',
      whatItIs: 'The giveaway of a real mini batting helmet in team colors - kids wearing them around the concourse, the stands, and probably the rest of the week at home.',
      theFun: 'A sturdy, genuinely cool souvenir kids actually keep.',
      theNote: 'The youth-league fields next week will have these helmets in the dugout.',
      howItLands: 'A durable classic giveaway. ⛑️',
      achievement: '⛑️ *Helmet On*',
    },
    {
      num: 10,
        achievementId: 'nat_promoNights_10',
      emoji: '👕',
      title: 'JERSEY NIGHT',
      tagline: 'Free team jersey at the gate!',
      whatItIs: 'A replica jersey or team T-shirt handed out at the turnstiles - the whole crowd suiting up in matching colors for a wall-of-team-pride look.',
      theFun: 'Instant team gear, no gift-shop markup.',
      theNote: 'Everyone checks the size at the gate, hoping it\'s not a kids\' XS.',
      howItLands: 'Always a big-draw giveaway. 👕',
      achievement: '👕 *Suit Up*',
    },
    {
      num: 11,
        achievementId: 'nat_promoNights_11',
      emoji: '🏁',
      title: 'THE DIZZY BAT RACE',
      tagline: 'Spin, stagger, and stumble to the finish!',
      whatItIs: 'The between-innings on-field contest - fans (or kids) spin around a bat with their forehead down, then try to run a wobbly, hilarious race to the finish while the whole stadium laughs.',
      theFun: 'Pure slapstick; nobody runs straight.',
      theNote: 'The dizzy-bat racer veering into the camera crew is a stadium classic.',
      howItLands: 'A reliable crowd-pleaser. 🏁',
      achievement: '🏁 *Spin and Stagger*',
    },
    {
      num: 12,
        achievementId: 'nat_promoNights_12',
      emoji: '🎶',
      title: 'SEVENTH-INNING STRETCH',
      tagline: 'Everybody up - stretch those legs!',
      whatItIs: 'The cherished mid-seventh ritual - the whole ballpark rising to its feet to stretch and sing along to the timeless ballpark singalong, swaying together for a moment of pure tradition.',
      theFun: 'A century-old custom that still gives everyone goosebumps.',
      theNote: 'Buy me some peanuts and... well, you know the rest.',
      howItLands: 'The most beloved ritual in the sport. 🎶',
      achievement: '🎶 *Take Me Out*',
    },
    {
      num: 13,
        achievementId: 'nat_promoNights_13',
      emoji: '⚾',
      title: 'BALL DAY',
      tagline: 'A free baseball for every fan!',
      whatItIs: 'A real, official-style baseball handed out at the gate - the most fitting souvenir of all, perfect for a backyard catch or chasing an autograph.',
      theFun: 'Everybody leaves with an actual baseball in hand.',
      theNote: 'Stadium security politely reminds fans NOT to throw them onto the field.',
      howItLands: 'A perfect, simple giveaway. ⚾',
      achievement: '⚾ *Free Baseball*',
    },
    // ── SILLY / INVENTED THEME NIGHTS (12) ──
    {
      num: 14,
        achievementId: 'nat_promoNights_14',
      emoji: '🐶',
      title: 'BARK IN THE PARK',
      tagline: 'Bring your best friend to the ballgame!',
      whatItIs: 'The night fans bring their dogs to the stadium - a sea of leashes, a chorus of barks at every big play, and a between-innings parade of pups around the warning track.',
      theFun: 'Hundreds of dogs reacting to the crack of the bat is pure joy.',
      theNote: 'At least three dogs will try to field a foul ball.',
      howItLands: 'An adorable, chaotic favorite. 🐶',
      achievement: '🐶 *Bark in the Park*',
    },
    {
      num: 15,
        achievementId: 'nat_promoNights_15',
      emoji: '🐠',
      title: 'GOLDFISH NIGHT',
      tagline: 'Bring your goldfish to the ballgame!',
      whatItIs: 'The gloriously absurd promotion where fans are invited to bring their pet goldfish - bowls sloshing in laps, tiny fish "watching" the action, and a jumbotron cam panning across a row of fishbowls.',
      theFun: 'It makes no sense, and that\'s exactly why it\'s wonderful.',
      theNote: 'The goldfish, frankly, seem unimpressed by the double play.',
      howItLands: 'Peak silly-promo comedy. 🐠',
      achievement: '🐠 *Goldfish in the Stands*',
    },
    {
      num: 16,
        achievementId: 'nat_promoNights_16',
      emoji: '🚀',
      title: 'SPACE SAGA NIGHT',
      tagline: 'The force is strong at the ballpark!',
      whatItIs: 'The sci-fi theme night - fans in homemade space-hero and robot costumes, laser-sword giveaways, a between-innings "lightsaber" duel on the field, and the mascot dressed as a galactic warrior.',
      theFun: 'Costumes everywhere and a goofy space battle at the seventh-inning stretch.',
      theNote: 'The mascot\'s robe keeps getting caught in the dugout railing.',
      howItLands: 'A nerdy, good-time costume party. 🚀',
      achievement: '🚀 *May the Force*',
    },
    {
      num: 17,
        achievementId: 'nat_promoNights_17',
      emoji: '🏖️',
      title: 'BEACH TOWEL NIGHT',
      tagline: 'Free towel - wave for the rally!',
      whatItIs: 'A team-colored beach towel handed out at the gate, instantly repurposed as a "rally towel" the whole crowd whips over their heads during a big inning.',
      theFun: 'Forty thousand towels spinning at once is a genuinely electric sight.',
      theNote: 'Also handy for the inevitable spilled-soda situation.',
      howItLands: 'A giveaway and a rally tool. 🏖️',
      achievement: '🏖️ *Wave the Towel*',
    },
    {
      num: 18,
        achievementId: 'nat_promoNights_18',
      emoji: '🧶',
      title: 'UGLY SWEATER NIGHT',
      tagline: 'The tackier, the better!',
      whatItIs: 'The mid-season "Christmas in July"-style theme - fans wear the loudest, tackiest holiday sweaters they own, with a prize for the most gloriously hideous one on the jumbotron.',
      theFun: 'Garish knitwear as far as the eye can see, in the summer heat.',
      theNote: 'Someone is wearing a sweater with working battery-powered lights.',
      howItLands: 'Delightfully ridiculous. 🧶',
      achievement: '🧶 *Tacky and Proud*',
    },
    {
      num: 19,
        achievementId: 'nat_promoNights_19',
      emoji: '🎸',
      title: 'POSTGAME CONCERT: DREGS OF HUMANITY',
      tagline: 'Stick around - the show\'s just starting!',
      whatItIs: 'The post-game concert night - once the final out is recorded, a stage rolls onto the infield and the legendary Dregs of Humanity take the field for a full live set under the lights, the crowd streaming down toward the grass.',
      theFun: 'A ballgame AND a concert on one ticket - and Dregs of Humanity absolutely bring the house down.',
      theNote: 'Dregs of Humanity reportedly requested the entire stadium\'s supply of dollar dogs in their dressing room.',
      howItLands: 'The hottest ticket on the promo calendar. 🎸',
      achievement: '🎸 *Dregs of Humanity Live*',
    },
    {
      num: 20,
        achievementId: 'nat_promoNights_20',
      emoji: '🧦',
      title: 'SOCK NIGHT',
      tagline: 'Free team socks - knock your socks ON!',
      whatItIs: 'The giveaway of a pair of team-colored socks - a practical, slightly goofy souvenir that ends up in the laundry rotation for years.',
      theFun: 'A genuinely useful piece of team gear you\'ll actually wear.',
      theNote: 'The only giveaway that shows up in your sock drawer a decade later.',
      howItLands: 'Quirky, practical, and surprisingly popular. 🧦',
      achievement: '🧦 *Fresh Socks*',
    },
    {
      num: 21,
        achievementId: 'nat_promoNights_21',
      emoji: '🦸',
      title: 'SUPERHERO NIGHT',
      tagline: 'Capes welcome at the ballpark!',
      whatItIs: 'The come-in-costume theme night - fans dressed as original caped crusaders and masked heroes, the mascot in a cape, and a between-innings "save the day" skit on the field.',
      theFun: 'A stadium full of homemade superheroes of every kind.',
      theNote: 'One fan\'s cape keeps blowing into the nachos of the row behind.',
      howItLands: 'A colorful, family-friendly hit. 🦸',
      achievement: '🦸 *Cape Crusader*',
    },
    {
      num: 22,
        achievementId: 'nat_promoNights_22',
      emoji: '🌙',
      title: 'PAJAMA NIGHT',
      tagline: 'Come to the game in your jammies!',
      whatItIs: 'The cozy theme night where fans show up in pajamas, robes, and slippers - perfect for a getaway-day game or a late one the kids will sleep through by the seventh.',
      theFun: 'A whole stadium dressed for bed, blankets and all.',
      theNote: 'At least one fan brought a full pillow and is using it.',
      howItLands: 'Cozy, funny, family-friendly. 🌙',
      achievement: '🌙 *Jammies On*',
    },
    {
      num: 23,
        achievementId: 'nat_promoNights_23',
      emoji: '💇',
      title: 'MULLET NIGHT',
      tagline: 'Business up front, party in the back!',
      whatItIs: 'The very-1984 theme night celebrating the glorious mullet - fans sporting real ones (or wig giveaways), with a contest for the finest flow on the jumbotron.',
      theFun: 'A perfectly era-appropriate celebration of questionable hair.',
      theNote: 'The winner\'s mullet reportedly has its own ZIP code.',
      howItLands: 'Peak \'80s ballpark fun. 💇',
      achievement: '💇 *Party in the Back*',
    },
    {
      num: 24,
        achievementId: 'nat_promoNights_24',
      emoji: '👆',
      title: 'FOAM FINGER NIGHT',
      tagline: 'We\'re number one!',
      whatItIs: 'The giveaway of the giant foam "#1" finger, instantly thrust skyward by the entire crowd in a forest of oversized foam hands.',
      theFun: 'Everybody pointing "we\'re #1" in unison, regardless of the standings.',
      theNote: 'Surprisingly difficult to eat a hot dog while wearing one.',
      howItLands: 'A goofy, iconic ballpark staple. 👆',
      achievement: '👆 *We\'re Number One*',
    },
    {
      num: 25,
        achievementId: 'nat_promoNights_25',
      emoji: '🤹',
      title: 'MASCOT MAYHEM NIGHT',
      tagline: 'Every mascot in one place!',
      whatItIs: 'The chaotic theme night where mascots from all over gather for between-innings races, dance-offs, and good-natured tomfoolery - a furry, foam-headed circus of silliness.',
      theFun: 'Mascots tripping over each other in a relay race never gets old.',
      theNote: 'The home mascot definitely cheated to win the dizzy-bat race.',
      howItLands: 'Chaotic, joyful crowd fun. 🤹',
      achievement: '🤹 *Mascot Mayhem*',
    },
  ],
};