// National Pro Wrestling Banner (#676–700) — 25 windows, mixed into ALL 26 ballparks
// 1984 territory-era hype + golden-age reverence + retrospective wink
// All names and facts are real 1984 references; all descriptive copy is original.
// Hidden achievement: open all 25 wrestling windows

export const WRESTLING_BANNER = {
  id: 'wrestlingbanner_676',
  title: '🤼 "Step right up — it\'s wrestling night! Gold belts and grudge matches at the squared circle!"',
  subtitle: '(territory-era hype meets golden-age reverence)',
  icon: '🤼',
  hiddenAchievement: '📢 "And That\'s the Bottom Line in \'84"',
  popups: [
    // ── WINDOW 01: RIC FLAIR ──
    {
      num: 1,
        achievementId: 'nat_wrestling_1',
      emoji: '🌟',
      title: 'RIC FLAIR',
      tagline: 'The measuring stick of the whole business',
      whatItWas: 'The NWA World Heavyweight Champion and, by wide agreement, the finest all-around performer on the planet — limousine-riding, jet-flying, custom-robe-wearing arrogance backed up by the ability to carry anyone to a great match for an hour straight.',
      howChanged: 'Trading the NWA World title with Harley Race and Kerry Von Erich and defending it night after night across every territory — the champion the whole map chased.',
      craze: 'The gold standard. The wrestler other wrestlers measured themselves against, and the blueprint for the cocky-but-deliverable main-eventer.',
      howAged: 'Immortal. Sixteen-time world champion lore, the strut, the robes — the definition of "the man." 💃',
      achievement: '🌟 The Nature Boy',
    },
    // ── WINDOW 02: HARLEY RACE ──
    {
      num: 2,
        achievementId: 'nat_wrestling_2',
      emoji: '👑',
      title: 'HARLEY RACE',
      tagline: 'The toughest man in the territory',
      whatItWas: 'A multi-time NWA World Champion and the genuinely feared, no-nonsense veteran — the kind of legitimately tough wrestler who commanded respect in any locker room in the country.',
      howChanged: 'Still trading the NWA crown and grizzled-veteran main events with Flair, the old lion against the flashy young champion.',
      craze: 'A wrestler\'s wrestler — respected as one of the hardest, most credible champions the business ever produced.',
      howAged: 'A legend\'s legend; the term "Handsome Harley" and his reputation for toughness outlived the era. 👑',
      achievement: '👑 King of the Territories',
    },
    // ── WINDOW 03: DUSTY RHODES ──
    {
      num: 3,
        achievementId: 'nat_wrestling_3',
      emoji: '💙',
      title: 'DUSTY RHODES',
      tagline: 'The son of a plumber',
      whatItWas: 'The American Dream — a barrel-chested, gap-toothed, supremely charismatic everyman who could talk a building into a frenzy and bleed buckets in a brawl. The beating heart of the NWA\'s babyface side.',
      howChanged: 'A top NWA draw and booker-in-the-making, feuding through the territories as the people\'s champion the working man loved.',
      craze: 'One of the greatest talkers in wrestling history; the common-man hero archetype perfected.',
      howAged: 'Beloved forever — the polka dots come later, the promos are eternal. 💙',
      achievement: '💙 The American Dream',
    },
    // ── WINDOW 04: ARN ANDERSON ──
    {
      num: 4,
        achievementId: 'nat_wrestling_4',
      emoji: '🪚',
      title: 'ARN ANDERSON',
      tagline: 'The Enforcer',
      whatItWas: 'A rugged, brilliant in-ring craftsman and one of the best pure tag-team and tactical wrestlers alive — the guy who made everything look snug, mean, and real.',
      howChanged: 'Building his name on the territory circuit, already showing the savvy and toughness that would make him the cornerstone enforcer of the most famous faction in wrestling.',
      craze: 'The ultimate "wrestler\'s wrestler" — respected by every peer for ring IQ and credibility.',
      howAged: 'A future Horseman and one of the most respected minds in the sport. 🪚',
      achievement: '🪚 The Enforcer',
    },
    // ── WINDOW 05: TULLY BLANCHARD ──
    {
      num: 5,
        achievementId: 'nat_wrestling_5',
      emoji: '💼',
      title: 'TULLY BLANCHARD',
      tagline: 'Perfect, in his own mind',
      whatItWas: 'A polished, intense heel with a chip on his shoulder and the in-ring ability to back up every arrogant word — a tremendous worker in the Mid-Atlantic and World Class scenes.',
      howChanged: 'Carving out a reputation as one of the best heels in the NWA, the kind of cocky technician audiences loved to hate.',
      craze: 'Half of one of the greatest tag teams ever (with Arn) and a future Horseman; a master of heel psychology.',
      howAged: 'A respected legend, name-checked whenever great heels are discussed. 💼',
      achievement: '💼 Slamming It',
    },
    // ── WINDOW 06: OLE ANDERSON ──
    {
      num: 6,
        achievementId: 'nat_wrestling_6',
      emoji: '🪨',
      title: 'OLE ANDERSON',
      tagline: 'Old-school and mean about it',
      whatItWas: 'A gruff, hard-nosed veteran of the famous Anderson "brothers" act — a stiff, no-frills brawler and one of the canniest ring minds in the business.',
      howChanged: 'A grizzled territory mainstay, the kind of tough veteran who anchored tag matches and made younger stars earn everything.',
      craze: 'A piece of the assembling puzzle that would become the most feared group in wrestling.',
      howAged: 'A respected old-guard name and a future founding Horseman. 🪨',
      achievement: '🪨 Minnesota Wrecking Crew',
    },
    // ── WINDOW 07: THE HORSEMEN ARE COMING (forward-wink) ──
    {
      num: 7,
        achievementId: 'nat_wrestling_7',
      emoji: '🐎',
      title: 'FOUR OF A KIND',
      tagline: 'The pieces are starting to assemble...',
      whatItWas: 'Look around the NWA in 1984 and the parts are all right there — Flair on top with the gold, Arn and Tully tearing up the tag ranks, Ole anchoring the old guard. They aren\'t a unit yet...',
      howChanged: '...but within a couple of years, four men and a manager will lock arms, throw up four fingers, and form the most copied, most feared faction in the history of the business. You\'re watching the raw materials.',
      craze: 'The greatest faction in wrestling history, assembled from parts already on the board in \'84.',
      howAged: 'Imitated forever — every four-man heel group since owes them everything. 🐎',
      achievement: '🐎 Four Fingers in the Air',
    },
    // ── WINDOW 08: THE VON ERICHS ──
    {
      num: 8,
        achievementId: 'nat_wrestling_8',
      emoji: '⭐',
      title: 'THE VON ERICHS',
      tagline: 'Texas royalty',
      whatItWas: 'The handsome, athletic, beloved sons of Fritz Von Erich — Kevin (the barefoot high-flyer), Kerry (the muscular star with movie-idol looks), David, and the younger brothers — the crown jewels of World Class Championship Wrestling out of Dallas.',
      howChanged: 'The hottest babyface act in the country, packing the Sportatorium and Texas Stadium, feuding with the Freebirds in a war that drew enormous houses. Kerry would even hold the NWA World title briefly in \'84.',
      craze: 'World Class\'s slick TV production and the brothers\' star power made them a national sensation and a template for the modern wrestling broadcast.',
      howAged: 'Genuine icons of the era — Texas wrestling royalty whose matches and charisma are still celebrated. ⭐',
      achievement: '⭐ Texas Heroes',
    },
    // ── WINDOW 09: THE FABULOUS FREEBIRDS ──
    {
      num: 9,
        achievementId: 'nat_wrestling_9',
      emoji: '🎸',
      title: 'THE FABULOUS FREEBIRDS',
      tagline: 'Bad Street\'s finest',
      whatItWas: 'Michael "P.S." Hayes, Terry "Bam Bam" Gordy, and Buddy Roberts — a swaggering, rock-\'n\'-roll heel trio who came to the ring with attitude, music, and chaos, and who defined the entrance-with-a-theme spectacle.',
      howChanged: 'Locked in their legendary, blood-soaked, money-drawing war with the Von Erichs in World Class — one of the hottest feuds in all of wrestling.',
      craze: 'Pioneers of the music-and-attitude entrance and the "cool heel" trio; a massive influence on everything that followed.',
      howAged: 'A legendary act, remembered as one of the great heel teams and innovators of presentation. 🎸',
      achievement: '🎸 Bad Street Brawlers',
    },
    // ── WINDOW 10: THE ROAD WARRIORS ──
    {
      num: 10,
        achievementId: 'nat_wrestling_10',
      emoji: '💀',
      title: 'THE ROAD WARRIORS',
      tagline: 'Ohhh, what a rush',
      whatItWas: 'Hawk and Animal — face-painted, spike-shouldered, impossibly jacked powerhouses managed by Paul Ellering. They didn\'t wrestle so much as demolish, and audiences had never seen anything like them.',
      howChanged: 'Exploding across the AWA and NWA as the most intimidating, instantly iconic tag team in the world — a genuine revolution in look and presentation.',
      craze: 'The most influential tag team ever in terms of image; every monster-powerhouse duo since owes them.',
      howAged: 'Legends. The look, the intensity, the legacy — unmistakable and endlessly imitated. 💀',
      achievement: '💀 Legion of Doom',
    },
    // ── WINDOW 11: MAGNUM T.A. ──
    {
      num: 11,
        achievementId: 'nat_wrestling_11',
      emoji: '🫵',
      title: 'MAGNUM T.A.',
      tagline: 'The next big thing',
      whatItWas: 'A charismatic, mustachioed young star with matinee-idol looks and a rocketing trajectory — the NWA\'s bet on the future, often compared to a certain Hollywood action star.',
      howChanged: 'Rising fast as one of the most popular up-and-coming babyfaces in the NCA, on a clear path toward the top of the card.',
      craze: 'A star whose ceiling looked limitless before a car accident ended his career — one of wrestling\'s great "what ifs."',
      howAged: 'Remembered with deep affection and a tinge of sadness for the legend he was becoming. 🫵',
      achievement: '🫵 The Natural',
    },
    // ── WINDOW 12: HULK HOGAN ──
    {
      num: 12,
        achievementId: 'nat_wrestling_12',
      emoji: '💛',
      title: 'HULK HOGAN',
      tagline: 'Hulkamania is running wild',
      whatItWas: 'The 6-foot-7, sun-tanned, bandana-and-handlebar phenomenon who became the face that took professional wrestling to the mainstream stratosphere.',
      howChanged: 'THE moment of the year — in January 1984 he beat the Iron Sheik for the WWF title at Madison Square Garden, and "Hulkamania" detonated into a national craze almost overnight.',
      craze: 'The single biggest star of the wrestling boom; the red-and-yellow merchandise engine that helped wrestling conquer mainstream America.',
      howAged: 'The defining icon of \'80s wrestling to the general public — say "wrestler" to anyone from the era and they picture him. 💛',
      achievement: '💛 Whatcha Gonna Do',
    },
    // ── WINDOW 13: "ROWDY" RODDY PIPER ──
    {
      num: 13,
        achievementId: 'nat_wrestling_13',
      emoji: '🎤',
      title: 'RODDY PIPER',
      tagline: 'The man you loved to hate',
      whatItWas: 'A kilted, motor-mouthed, utterly fearless heel — the best talker in the WWF and the perfect foil for Hogan\'s all-American hero. His interview segment was must-watch chaos.',
      howChanged: 'The white-hot top villain of the WWF\'s national expansion, his talk-show segment becoming the most unpredictable few minutes on wrestling TV.',
      craze: 'Arguably the greatest heel of the boom — proof that a villain who never won the big belt could still be the most important act on the show.',
      howAged: 'A beloved legend; the gold standard for the wrestler who makes the hero matter. 🎤',
      achievement: '🎤 Hot Rod',
    },
    // ── WINDOW 14: ANDRE THE GIANT ──
    {
      num: 14,
        achievementId: 'nat_wrestling_14',
      emoji: '🏔️',
      title: 'ANDRE THE GIANT',
      tagline: 'The Eighth Wonder of the World',
      whatItWas: 'The genuinely awe-inspiring near-7-foot, 500-pound French colossus — billed as undefeated, marveled as a real-life giant, and one of the most famous athletes on Earth.',
      howChanged: 'A massive special attraction touring the WWF\'s expanding national territory, drawing crowds who just wanted to see a man that size.',
      craze: 'A worldwide phenomenon whose fame transcended wrestling entirely — a pop-culture giant in every sense.',
      howAged: 'Immortal and singular; there has never been another like him. 🏔️',
      achievement: '🏔️ Eighth Wonder',
    },
    // ── WINDOW 15: THE IRON SHEIK ──
    {
      num: 15,
        achievementId: 'nat_wrestling_15',
      emoji: '🏅',
      title: 'THE IRON SHEIK',
      tagline: 'The man who made Hulkamania possible',
      whatItWas: 'A legitimately credentialed amateur wrestler turned hated foreign menace, with the Camel Clutch finish and a genuine air of danger.',
      howChanged: 'He took the WWF title off Bob Backlund in December \'83 — then dropped it to Hogan in January \'84, the transfer of power that lit the entire boom. Without him, no Hulkamania.',
      craze: 'One of the most important transitional champions ever; the perfect monster for the new hero to slay.',
      howAged: 'A beloved legend whose larger-than-life personality made him a cult icon for decades. 🏅',
      achievement: '🏅 Camel Clutch',
    },
    // ── WINDOW 16: JIMMY "SUPERFLY" SNUKA ──
    {
      num: 16,
        achievementId: 'nat_wrestling_16',
      emoji: '🦅',
      title: 'JIMMY "SUPERFLY" SNUKA',
      tagline: 'Off the top of the cage',
      whatItWas: 'A barefoot, leopard-print, impossibly athletic high-flyer whose leaps off the top rope — and especially off the top of the steel cage — were unlike anything audiences had seen.',
      howChanged: 'A wildly popular attraction whose aerial offense thrilled crowds and inspired a generation of future stars who\'d cite his cage leap as the moment they fell in love with wrestling.',
      craze: 'A pioneer of the high-flying style; that cage dive became one of the most replayed images of the era.',
      howAged: 'Remembered as an innovator whose athleticism was ahead of its time. 🦅',
      achievement: '🦅 Superfly Splash',
    },
    // ── WINDOW 17: JUNKYARD DOG ──
    {
      num: 17,
        achievementId: 'nat_wrestling_17',
      emoji: '🐕',
      title: 'JUNKYARD DOG',
      tagline: 'Thump',
      whatItWas: 'A powerhouse, supremely charismatic fan favorite — one of the biggest babyface draws in the country, beloved especially in the Mid-South territory before the WWF brought him national.',
      howChanged: 'A massive crowd-pleaser whose chain, dance, and headbutts made him one of wrestling\'s most bankable good guys.',
      craze: 'A trailblazing top babyface and one of the most genuinely loved performers of his time.',
      howAged: 'Fondly remembered as one of the era\'s great connectors with a crowd. 🐕',
      achievement: '🐕 Grab Them Cakes',
    },
    // ── WINDOW 18: RICKY "THE DRAGON" STEAMBOAT ──
    {
      num: 18,
        achievementId: 'nat_wrestling_18',
      emoji: '🐉',
      title: 'RICKY STEAMBOAT',
      tagline: 'The perfect babyface',
      whatItWas: 'A clean-cut, endlessly likable, and technically brilliant fan favorite — maybe the best pure babyface worker in the business, capable of all-time classic matches.',
      howChanged: 'A top NWA/Mid-Atlantic star whose athletic, sympathetic style made him the ideal hero against the era\'s great heels.',
      craze: 'His matches (especially the ones still to come with Flair) are studied as the gold standard of babyface-vs-heel storytelling.',
      howAged: 'A revered legend; "Steamboat match" is shorthand for in-ring perfection. 🐉',
      achievement: '🐉 The Dragon',
    },
    // ── WINDOW 19: SGT. SLAUGHTER ──
    {
      num: 19,
        achievementId: 'nat_wrestling_19',
      emoji: '🎖️',
      title: 'SGT. SLAUGHTER',
      tagline: 'Cobra Clutch and a Cadence',
      whatItWas: 'A drill-instructor character who made a remarkable turn from hated heel to flag-waving fan favorite, complete with a boot-camp gimmick that connected hugely with crowds.',
      howChanged: 'Riding a wave of patriotic popularity, his cobra-clutch challenges and G.I. persona making him one of the WWF\'s most over acts.',
      craze: 'One of the most successful heel-to-face turns of the era, and a character so iconic he became an actual action figure in a famous toy line.',
      howAged: 'A beloved character of the boom, instantly recognizable. 🎖️',
      achievement: '🎖️ Cobra Clutch',
    },
    // ── WINDOW 20: THE MANAGERS ──
    {
      num: 20,
        achievementId: 'nat_wrestling_20',
      emoji: '🎩',
      title: 'THE MOUTHPIECES',
      tagline: 'Every monster needs a manager',
      whatItWas: 'The talkers who did the dirty work outside the ropes — Captain Lou Albano with his rubber-band beard and rambling genius, "The Brain" Bobby Heenan (the funniest, sharpest heel manager alive), J.J. Dillon, Jim Cornette with his tennis racket, and more.',
      howChanged: 'The golden age of the manager — when a great mouthpiece could make a silent monster into a main-event draw and out-talk any babyface on the microphone.',
      craze: 'The manager as art form; Heenan in particular is remembered as one of the funniest, most brilliant performers wrestling ever had.',
      howAged: 'A lost art, fondly revered — the era when the guy in the corner was often the best talker in the building. 🎩',
      achievement: '🎩 The Brain Trust',
    },
    // ── WINDOW 21: THE ROCK 'N' WRESTLING CONNECTION ──
    {
      num: 21,
        achievementId: 'nat_wrestling_21',
      emoji: '🎸',
      title: 'ROCK \'N\' WRESTLING',
      tagline: 'When wrestling crashed MTV',
      whatItWas: 'The wild 1984 crossover when pop star Cyndi Lauper got entangled in a WWF storyline (with Captain Lou Albano) and suddenly wrestling was all over MTV, drawing in a brand-new mainstream audience.',
      howChanged: 'It blew wrestling\'s reach wide open — music-video fans, casual viewers, and the press all started paying attention, fueling the national boom that would lead straight to the first WrestleMania.',
      craze: 'The bridge that took wrestling from regional curiosity to mainstream pop-culture juggernaut.',
      howAged: 'A pivotal, beloved moment — the instant wrestling and pop music officially collided. 🎸',
      achievement: '🎸 MTV Mania',
    },
    // ── WINDOW 22: THE TERRITORIES vs. THE NATIONAL TAKEOVER ──
    {
      num: 22,
        achievementId: 'nat_wrestling_22',
      emoji: '🗺️',
      title: 'THE TERRITORY SYSTEM',
      tagline: 'The map is being redrawn',
      whatItWas: 'For decades, wrestling was a patchwork of regional territories — World Class in Texas, Mid-South, the AWA up north, the Mid-Atlantic NWA, and dozens more, each with its own champion and TV.',
      howChanged: 'The year the WWF began aggressively going national — raiding talent, buying TV slots, and breaking the old gentlemen\'s agreements between territories. The local promotions are about to be swallowed.',
      craze: 'The end of an era and the birth of national, cable-driven wrestling — a seismic business shift happening in real time.',
      howAged: 'Mourned and mythologized — the territory days are remembered as a golden, lost age of regional flavor. 🗺️',
      achievement: '🗺️ Drawing the Map',
    },
    // ── WINDOW 23: SATURDAY MORNING WRESTLING ──
    {
      num: 23,
        achievementId: 'nat_wrestling_23',
      emoji: '📺',
      title: 'WRESTLING ON THE TUBE',
      tagline: 'Channel surfing into a headlock',
      whatItWas: 'Before pay-per-view ruled, wrestling lived on weekend syndicated TV — squash matches, wild interviews, and hype for the house shows coming to your local arena, all shot in those unmistakable studio sets.',
      howChanged: 'The TV product was the engine of the boom — the place where characters got over and feuds got sold, week after week, in living rooms across the country.',
      craze: 'The format that built the stars; the studio-wrestling aesthetic is pure 1984 nostalgia.',
      howAged: 'Beloved by anyone who grew up taping it — the cozy, chaotic heart of territory-era fandom. 📺',
      achievement: '📺 Saturday Night\'s Main Event',
    },
    // ── WINDOW 24: THE ACTION FIGURES & THE MERCH CRAZE ──
    {
      num: 24,
        achievementId: 'nat_wrestling_24',
      emoji: '🧸',
      title: 'WRESTLING MERCH',
      tagline: 'From the ring to the toy aisle',
      whatItWas: 'As the boom hit, wrestling exploded off the screen and onto store shelves — big rubber action figures of the stars, foam championship belts, T-shirts, posters, and lunchboxes, all flying out of toy aisles.',
      howChanged: 'With Hulkamania surging, wrestling merchandise became huge business — kids could finally own a (rubbery, slightly stiff) version of their favorite hero.',
      craze: 'The merchandising gold rush that proved wrestling was a mainstream entertainment brand, not just a live event.',
      howAged: 'Those rubber figures are prized collector\'s items now, dripping with \'80s nostalgia. 🧸',
      achievement: '🧸 Action Figure Army',
    },
    // ── WINDOW 25: WRESTLEMANIA IS COMING (forward-wink) ──
    {
      num: 25,
        achievementId: 'nat_wrestling_25',
      emoji: '🎪',
      title: 'THE BIGGEST SHOW OF THEM ALL',
      tagline: 'They\'re betting the whole company on it...',
      whatItWas: 'All this momentum — Hogan, Piper, the MTV crossover, the national expansion — is building toward something unprecedented...',
      howChanged: 'In March 1985, the WWF will roll the dice on a star-studded super-card at Madison Square Garden, beamed out on closed-circuit and crammed with celebrities. It\'s a gamble that could sink the company — or change wrestling forever.',
      craze: 'It changes everything — the birth of the wrestling supercard and the pay-per-view era, all seeded by what\'s happening right now in \'84.',
      howAged: 'It becomes the Super Bowl of wrestling, an annual institution. (Wink: that\'s March 1985.) 🎪',
      achievement: '🎪 The Showcase of the Immortals',
    },
  ],
};