// National Saturday Morning Cartoons & Kids' TV (1984) Banner (#1026-1050) — 25 windows, mixed into ALL 26 ballparks
// Cereal-and-pajamas nostalgia + Saturday-morning magic + retrospective wink
// All show titles and characters are real-era references in ORIGINAL wording. NO reproduced lyrics, scripts, or trademarked catchphrases verbatim.
// Hidden achievement: "Kids, Don't Try This at Home" — open all 25 Saturday-morning windows

export const SATURDAY_CARTOONS_BANNER = {
  id: 'saturdaycartoons_1026',
  title: '📺 "It\'s Saturday morning — grab your cereal!"',
  subtitle: '(cereal-and-pajamas nostalgia meets Saturday-morning magic)',
  icon: '📺',
  hiddenAchievement: '💼 "Kids, Don\'t Try This at Home"',
  popups: [
    {
      num: 1,
        achievementId: 'nat_cartoons_1',
      emoji: '📺',
      title: 'THE SATURDAY MORNING RITUAL',
      tagline: 'Up at dawn, bowl in hand',
      whatItWas: 'The weekly ritual — waking up absurdly early, pouring a bowl of sugary cereal, and planting yourself on the living-room floor in pajamas for hours of cartoons that existed only in that one Saturday-morning block.',
      howChanged: 'In \'84, Saturday morning was a sacred appointment — if you missed the block, you missed it entirely until next week.',
      craze: 'A defining shared childhood experience of the era.',
      howAged: 'Gone as TV fragmented — the ritual glows warmer every year. 📺',
      achievement: '📺 *Bowl in Hand*',
    },
    {
      num: 2,
        achievementId: 'nat_cartoons_2',
      emoji: '🤖',
      title: 'TRANSFORMING ROBOT HEROES',
      tagline: 'More than meets the eye',
      whatItWas: 'The cartoons about heroic and villainous robots that transformed into vehicles and machines — sprawling epics of warring factions, each with a massive toy line kids had to collect.',
      howChanged: 'The transforming-robot cartoon was a blockbuster in \'84, the toys flying off shelves and the show appointment viewing.',
      craze: 'A cornerstone of \'80s action cartoons and the toy-tie-in boom.',
      howAged: 'A beloved franchise with a devoted following across generations. 🤖',
      achievement: '🤖 *Transform!*',
    },
    {
      num: 3,
        achievementId: 'nat_cartoons_3',
      emoji: '🎖️',
      title: 'THE ELITE MILITARY TEAM',
      tagline: 'A real American hero',
      whatItWas: 'The cartoon about an elite commando team battling a hooded villain and his shadowy organization — gadgets, vehicles, and codenames, with an action-figure line that filled every toy aisle.',
      howChanged: 'The military-team cartoon was a Saturday and weekday-afternoon staple in \'84, its action figures everywhere.',
      craze: 'A cornerstone of \'80s action cartoons and the toy-tie-in boom.',
      howAged: 'A beloved franchise with a devoted following. 🎖️',
      achievement: '🎖️ *Knowing Is Half the Battle*',
    },
    {
      num: 4,
        achievementId: 'nat_cartoons_4',
      emoji: '⚔️',
      title: 'THE SWORD-AND-SORCERY HERO',
      tagline: 'By the power of the castle',
      whatItWas: 'The fantasy cartoon about a mighty warrior hero who raised his sword to transform and defend a magical world from a skull-faced villain — pure sword-and-sorcery, with a beloved action-figure line.',
      howChanged: 'The fantasy-hero cartoon was a huge afternoon and weekend hit in \'84, the toys flying off shelves.',
      craze: 'A defining fantasy franchise of the era.',
      howAged: 'A nostalgic favorite, revived for new generations. ⚔️',
      achievement: '⚔️ *Raise the Sword*',
    },
    {
      num: 5,
        achievementId: 'nat_cartoons_5',
      emoji: '🌈',
      title: 'THE RAINBOW CUDDLY BEARS',
      tagline: 'Caring is their superpower',
      whatItWas: 'The gentle, pastel cartoon about caring cuddly characters who lived in the clouds and spread kindness, defeating gloom with the power of feelings — and a runaway plush-toy line.',
      howChanged: 'The sweet, soft-hearted cartoon (and its plush toys) was a sensation in \'84, especially as a wholesome counter to the action shows.',
      craze: 'A beloved gentle franchise and a merchandising giant.',
      howAged: 'A warm nostalgia favorite. 🌈',
      achievement: '🌈 *Caring Stare*',
    },
    {
      num: 6,
        achievementId: 'nat_cartoons_6',
      emoji: '👶',
      title: 'THE TINY VERSIONS',
      tagline: 'Your favorite characters, as kids',
      whatItWas: 'The trend of reimagining famous cartoon characters as adorable toddlers in a nursery — a clever, heart-tugging format that spun classic stars into cute pint-sized adventures.',
      howChanged: 'The "baby versions" idea was a fresh, irresistible hook in \'84 that became a Saturday-morning staple.',
      craze: 'A hugely successful format that spawned many imitators.',
      howAged: 'A fondly remembered clever twist on beloved characters. 👶',
      achievement: '👶 *Pint-Sized*',
    },
    {
      num: 7,
        achievementId: 'nat_cartoons_7',
      emoji: '🐰',
      title: 'THE CLASSIC CARTOON GANG',
      tagline: 'That\'s all, folks',
      whatItWas: 'The timeless theatrical shorts — the wisecracking rabbit, the lisping hunter, the speedy roadrunner — packaged into Saturday-morning blocks for a new generation of kids.',
      howChanged: 'These golden-age cartoons were Saturday-morning royalty in \'84, as funny as ever.',
      craze: 'Some of the greatest cartoons ever made, beloved across generations.',
      howAged: 'Eternal — the classic shorts never stop being funny. 🐰',
      achievement: '🐰 *That\'s All Folks*',
    },
    {
      num: 8,
        achievementId: 'nat_cartoons_8',
      emoji: '🐕',
      title: 'THE MYSTERY GANG & THEIR DOG',
      tagline: 'Those meddling kids',
      whatItWas: 'The long-running cartoon about a group of teens and their cowardly Great Dane solving spooky mysteries in a groovy van, unmasking a "ghost" as a crook every episode.',
      howChanged: 'The mystery-solving-dog cartoon was a Saturday-morning institution in \'84, comfort-watching for every kid.',
      craze: 'One of the most enduring cartoon franchises of all time.',
      howAged: 'Timeless — still running in some form to this day. 🐕',
      achievement: '🐕 *Unmask the Villain*',
    },
    {
      num: 9,
        achievementId: 'nat_cartoons_9',
      emoji: '🔵',
      title: 'THE LITTLE BLUE VILLAGE',
      tagline: 'Three apples high',
      whatItWas: 'The cartoon about a village of tiny blue creatures living in mushroom houses, outwitting a bumbling evil wizard and his cat — a massive Saturday-morning hit with its own merchandise empire.',
      howChanged: 'The little-blue-creatures cartoon was a ratings juggernaut and a merchandising sensation in \'84.',
      craze: 'A defining \'80s cartoon and a pop-culture fixture.',
      howAged: 'A nostalgic favorite, revived in films and reboots. 🔵',
      achievement: '🔵 *Three Apples High*',
    },
    {
      num: 10,
        achievementId: 'nat_cartoons_10',
      emoji: '🕹️',
      title: 'THE ARCADE-HERO CARTOONS',
      tagline: 'From the arcade to the TV',
      whatItWas: 'Cartoons built around the era\'s hottest video-game characters — the maze-chomping hero and others — bringing arcade stars to Saturday morning as the games\' popularity peaked. (The games themselves are in the Arcade set.)',
      howChanged: 'Video-game cartoons capitalized on arcade mania in \'84, putting beloved game characters into weekly adventures.',
      craze: 'An early, telling fusion of gaming and TV.',
      howAged: 'A charming curio of the arcade craze. 🕹️',
      achievement: '🕹️ *Game On*',
    },
    {
      num: 11,
        achievementId: 'nat_cartoons_11',
      emoji: '📚',
      title: 'THE LEARNING SHORTS',
      tagline: 'A little lesson between the toons',
      whatItWas: 'The short animated educational segments slipped between cartoons — catchy bite-sized lessons on grammar, math, history, and science that taught a generation more than they realized.',
      howChanged: 'These clever shorts were a beloved part of the morning in \'84, sneaking learning into the fun.',
      craze: 'Genuinely effective — kids remember these lessons for life.',
      howAged: 'Revered as some of the best edutainment ever made. 📚',
      achievement: '📚 *Schoolhouse Smarts*',
    },
    {
      num: 12,
        achievementId: 'nat_cartoons_12',
      emoji: '🦹',
      title: 'THE SUPER-FRIENDS',
      tagline: 'Heroes assemble',
      whatItWas: 'The cartoon teaming up famous comic-book superheroes to battle villains from their satellite headquarters — capes, powers, and weekly world-saving for the Saturday crowd.',
      howChanged: 'The superhero-team cartoon was a Saturday staple in \'84, every kid picking a favorite hero.',
      craze: 'A foundational superhero-cartoon experience for a generation.',
      howAged: 'Beloved, and the seed of today\'s superhero-everything culture. 🦹',
      achievement: '🦹 *Heroes Assemble*',
    },
    {
      num: 13,
        achievementId: 'nat_cartoons_13',
      emoji: '🦆',
      title: 'THE FUNNY-ANIMAL TOWN',
      tagline: 'Wacky critters and big laughs',
      whatItWas: 'The slapstick cartoons full of anthropomorphic animal characters getting into comedic scrapes — pure goofy fun with no lesson required.',
      howChanged: 'The funny-animal comedies were dependable laughs in the \'84 Saturday lineup.',
      craze: 'A timeless cartoon comfort-food format.',
      howAged: 'The goofy-animal comedy never goes out of style. 🦆',
      achievement: '🦆 *Wacky Antics*',
    },
    {
      num: 14,
        achievementId: 'nat_cartoons_14',
      emoji: '🧸',
      title: 'CARTOONS AS COMMERCIALS',
      tagline: 'Buy the toy, watch the show',
      whatItWas: 'The era\'s defining business model — cartoons designed hand-in-hand with toy lines, so the show was effectively a half-hour ad and the toy aisle was full of its characters.',
      howChanged: 'The toy-tie-in cartoon was everywhere in \'84, blurring the line between entertainment and advertising (and selling a LOT of toys).',
      craze: 'A massively influential (and controversial) shift in kids\' TV.',
      howAged: 'A defining, much-discussed feature of \'80s childhood. 🧸',
      achievement: '🧸 *Collect Them All*',
    },
    {
      num: 15,
        achievementId: 'nat_cartoons_15',
      emoji: '⛵',
      title: 'THE SATURDAY COMMERCIALS',
      tagline: 'Sugar, toys, and a public-service tip',
      whatItWas: 'The ad breaks themselves — a barrage of sugary-cereal spots, must-have toy ads, and the occasional earnest public-service message, all aimed squarely at the cross-legged kid audience.',
      howChanged: 'The commercials were practically part of the show in \'84 — kids memorized the jingles and circled toys in their heads.',
      craze: 'The Saturday-morning ad break is a nostalgia trip all its own.',
      howAged: 'Those ads are time capsules of \'80s kid culture. ⛵',
      achievement: '⛵ *I Want That One*',
    },
    {
      num: 16,
        achievementId: 'nat_cartoons_16',
      emoji: '🎪',
      title: 'THE LIVE-ACTION KIDS\' SHOWS',
      tagline: 'Puppets, sketches, and zaniness',
      whatItWas: 'The live-action corners of kids\' TV — puppet shows, sketch comedy, costumed characters, and zany variety, mixed in among the cartoons.',
      howChanged: 'Live-action kids\' shows added a different flavor of chaos to the \'84 morning.',
      craze: 'A beloved, slightly surreal piece of kids\'-TV history.',
      howAged: 'Fondly (and sometimes bizarrely) remembered. 🎪',
      achievement: '🎪 *Puppet Show*',
    },
    {
      num: 17,
        achievementId: 'nat_cartoons_17',
      emoji: '🦖',
      title: 'THE PREHISTORIC FAMILIES',
      tagline: 'Modern stone-age fun',
      whatItWas: 'The cartoons set in cave-dweller times — stone-age families with dinosaur pets and rock-powered gadgets, plus their many kid-friendly spinoffs.',
      howChanged: 'The prehistoric cartoons were Saturday comfort viewing in \'84, full of rock-pun gadgets and dino sidekicks.',
      craze: 'A classic cartoon setting that never gets old.',
      howAged: 'Timeless — the stone-age comedy endures. 🦖',
      achievement: '🦖 *Yabba Fun*',
    },
    {
      num: 18,
        achievementId: 'nat_cartoons_18',
      emoji: '🚀',
      title: 'THE SPACE ADVENTURE TOONS',
      tagline: 'To the stars and beyond',
      whatItWas: 'The futuristic cartoons — space-faring families, robot helpers, flying cars, and galactic heroes — feeding kids\' love of the future and outer space.',
      howChanged: 'Space cartoons captured the era\'s sci-fi optimism in \'84, all jetpacks and ray guns.',
      craze: 'A beloved vision of the cartoon future.',
      howAged: 'Nostalgic and charming — the retro-future never disappoints. 🚀',
      achievement: '🚀 *Blast Off*',
    },
    {
      num: 19,
        achievementId: 'nat_cartoons_19',
      emoji: '🏁',
      title: 'THE RACING & SPORTS TOONS',
      tagline: 'Wacky races and big games',
      whatItWas: 'The cartoons built around competition — outrageous car races, sports teams, and athletic hijinks, full of rivalry and slapstick.',
      howChanged: 'Racing and sports cartoons brought competitive thrills to the \'84 Saturday block.',
      craze: 'A fun, energetic cartoon staple.',
      howAged: 'Goofy competitive fun that holds up. 🏁',
      achievement: '🏁 *Checkered Flag*',
    },
    {
      num: 20,
        achievementId: 'nat_cartoons_20',
      emoji: '👻',
      title: 'THE FRIENDLY MONSTERS',
      tagline: 'Spooky but silly',
      whatItWas: 'The lighthearted spooky cartoons — friendly ghosts, goofy monsters, and haunted-house hijinks that were more giggles than scares.',
      howChanged: 'The friendly-monster cartoons were a fun, slightly spooky corner of the \'84 lineup.',
      craze: 'A charming, kid-safe brush with the spooky.',
      howAged: 'A wholesome nostalgic delight. 👻',
      achievement: '👻 *Boo!*',
    },
    {
      num: 21,
        achievementId: 'nat_cartoons_21',
      emoji: '💻',
      title: 'THE NETWORK BUMPERS',
      tagline: 'We\'ll be right back!',
      whatItWas: 'The little animated network logos and "stay tuned" bumpers between shows — the colorful station IDs and "and now back to our show" cards that stitched the morning together.',
      howChanged: 'Each network branded its Saturday block in \'84 with catchy animated bumpers kids knew by heart.',
      craze: 'A small but deeply nostalgic piece of the morning\'s texture.',
      howAged: 'Pure deep-cut nostalgia for those who lived it. 💻',
      achievement: '💻 *Stay Tuned*',
    },
    {
      num: 22,
        achievementId: 'nat_cartoons_22',
      emoji: '🥣',
      title: 'CARTOON CEREAL TIE-INS',
      tagline: 'Your favorite toon, now a breakfast',
      whatItWas: 'The cereals built around cartoon and movie characters — the box with your favorite hero on it, sometimes with a prize or a sticker inside, blurring breakfast and Saturday TV. (Cereal mascots get their own set; this is the cartoon-crossover angle.)',
      howChanged: 'Character cereals tied the \'84 Saturday-morning toons right to the breakfast table.',
      craze: 'A perfect loop of kid marketing — cartoon to cereal to toy.',
      howAged: 'A nostalgic emblem of \'80s kid culture. 🥣',
      achievement: '🥣 *Toon on the Box*',
    },
    {
      num: 23,
        achievementId: 'nat_cartoons_23',
      emoji: '🌟',
      title: 'WHEN IT\'S OVER',
      tagline: 'Now go outside and play',
      whatItWas: 'The bittersweet end — the cartoons giving way to boring afternoon programming (sports, news, infomercials), and a parent\'s inevitable "okay, that\'s enough TV, go play outside."',
      howChanged: 'The magic had a hard stop in \'84 — once the block ended, Saturday morning was over until next week.',
      craze: 'That "go outside" moment is a universal childhood memory.',
      howAged: 'Wistful — the end of the cartoons was the end of the magic. 🌟',
      achievement: '🌟 *Go Outside and Play*',
    },
    {
      num: 24,
        achievementId: 'nat_cartoons_24',
      emoji: '🎒',
      title: 'CHARACTERS ON EVERYTHING',
      tagline: 'Your toon on your lunchbox',
      whatItWas: 'The wave of character merchandise beyond toys — lunchboxes, backpacks, bedsheets, pajamas, and notebooks splashed with your favorite cartoon stars.',
      howChanged: 'Kids carried their favorite shows to school in \'84 on a metal lunchbox and a Trapper Keeper, identity broadcast loud.',
      craze: 'Character merchandise was a core part of \'80s kid life.',
      howAged: 'Those character lunchboxes are prized collectibles now. 🎒',
      achievement: '🎒 *Show It Off*',
    },
    {
      num: 25,
        achievementId: 'nat_cartoons_25',
      emoji: '✨',
      title: 'THE WHOLE MAGICAL MORNING',
      tagline: 'The best few hours of the week',
      whatItWas: 'The complete experience — the early wake-up, the cereal, the pajamas, the floor, the hours of cartoons, the commercials, the bumpers, and the sleepy-happy feeling of a Saturday morning all to yourself.',
      howChanged: 'For an \'80s kid in \'84, this was the highlight of the week — a few perfect, unhurried hours that belonged entirely to them.',
      craze: 'One of the most beloved and specific childhood memories of the era.',
      howAged: 'Gone forever as TV changed — which is exactly why it glows so warm. ✨',
      achievement: '✨ *Saturday Magic*',
    },
  ],
};