// National Space Shuttle, NASA & Aviation Banner (#776-800) - 18 windows mixed into ALL 26 ballparks
// ~70% space / ~30% aviation · Wide-eyed space-age wonder + American can-do + retrospective awe
// All names and facts are real 1984-era references; all descriptive copy is original. No post-1984 events.
// Hidden achievement: "The Final Frontier" - open all space & aviation windows

export const SPACE_AVIATION_BANNER = {
  id: 'spaceaviation_776',
  title: '🚀 "Reach for the stars - it\'s the space age!"',
  subtitle: '(wide-eyed space-age wonder meets American can-do)',
  icon: '🚀',
  hiddenAchievement: '🚀 "The Final Frontier"',
  popups: [
    // ── WINDOW 01: THE UNTETHERED SPACEWALK ──
    {
      num: 1,
        achievementId: 'nat_space_1',
      emoji: '🧑‍🚀',
      title: 'BRUCE McCANDLESS - THE HUMAN SATELLITE',
      tagline: 'Floating free, no rope at all',
      whatItWas: 'Astronaut Bruce McCandless II strapped on a nitrogen-jet backpack (the Manned Maneuvering Unit) and flew away from the shuttle - the first human ever to spacewalk completely untethered, a tiny figure alone against the black of space and the curve of the Earth.',
      howChanged: 'In February 1984 he drifted more than 300 feet from the orbiter - and the photograph of him hanging there, no lifeline, became one of the most iconic images in the history of spaceflight.',
      craze: 'That picture - a lone human floating free above the planet - is pure space-age awe, reprinted everywhere.',
      howAged: 'Immortal; still one of the most breathtaking photographs ever taken. 🧑‍🚀',
      achievement: '🧑‍🚀 *The Human Satellite*',
    },
    // ── WINDOW 02: THE MMU JETPACK ──
    {
      num: 2,
        achievementId: 'nat_space_2',
      emoji: '🎒',
      title: 'THE MMU JETPACK',
      tagline: 'A spaceship you wear',
      whatItWas: 'The Manned Maneuvering Unit - the bulky white nitrogen-thruster backpack that turned an astronaut into a one-person spacecraft, controlled with hand grips like something out of science fiction.',
      howChanged: 'It made the untethered spacewalks and satellite rescues possible - the coolest piece of hardware in orbit, and every kid\'s dream backpack.',
      craze: 'The ultimate "the future is here" gadget of the shuttle era.',
      howAged: 'A beloved icon of \'80s spaceflight, retired but unforgettable. 🎒',
      achievement: '🎒 *Strap In*',
    },
    // ── WINDOW 03: DISCOVERY'S MAIDEN VOYAGE ──
    {
      num: 3,
        achievementId: 'nat_space_3',
      emoji: '🛸',
      title: 'SPACE SHUTTLE DISCOVERY',
      tagline: 'A new bird takes flight',
      whatItWas: 'Discovery, the newest orbiter in the fleet, rolled to the pad and flew its first mission in 1984 - joining its sister ships as America\'s reusable spaceplane.',
      howChanged: 'Its maiden launch added a fresh workhorse to the shuttle program just as missions were ramping up in ambition and frequency.',
      craze: 'Discovery would go on to become the most-flown orbiter of the entire fleet.',
      howAged: 'A legendary spacecraft, eventually honored in a museum for the ages. 🛸',
      achievement: '🛸 *Maiden Voyage*',
    },
    // ── WINDOW 04: FIRST AMERICAN WOMAN TO SPACEWALK ──
    {
      num: 4,
        achievementId: 'nat_space_4',
      emoji: '👩‍🚀',
      title: 'KATHRYN SULLIVAN',
      tagline: 'Stepping out into the void',
      whatItWas: 'Astronaut Kathryn Sullivan, who in October 1984 became the first American woman to perform a spacewalk, working outside the orbiter in the vacuum of space.',
      howChanged: 'A landmark for women in the space program, accomplished on a mission that also carried the first flight with two women aboard at once.',
      craze: 'A barrier broken and an inspiration to a generation looking up at the stars.',
      howAged: 'Celebrated as a milestone in the story of American spaceflight. 👩‍🚀',
      achievement: '👩‍🚀 *Out the Airlock*',
    },
    // ── WINDOW 05: SATELLITE RESCUE MISSIONS ──
    {
      num: 5,
        achievementId: 'nat_space_5',
      emoji: '🛰️',
      title: 'CATCHING SATELLITES',
      tagline: 'The orbital tow truck',
      whatItWas: 'Shuttle crews in 1984 pulled off astonishing feats - repairing a satellite in orbit and, on a later mission, actually capturing two stranded satellites and hauling them back to Earth in the cargo bay.',
      howChanged: 'Spacewalking astronauts grabbed drifting satellites by hand using the jetpack - part rescue mission, part space-age salvage operation.',
      craze: 'Proof the shuttle could do things no spacecraft ever had - fix and retrieve hardware in orbit.',
      howAged: 'Remembered as some of the most daring and ingenious missions of the whole program. 🛰️',
      achievement: '🛰️ *Orbital Tow Truck*',
    },
    // ── WINDOW 06: THE ORBITER ITSELF ──
    {
      num: 6,
        achievementId: 'nat_space_6',
      emoji: '🚀',
      title: 'THE SPACE SHUTTLE',
      tagline: 'A spaceship that lands like a plane',
      whatItWas: 'The Space Transportation System - a reusable spaceplane that launched like a rocket, worked in orbit, and glided home to a runway landing. Nothing like it had ever flown.',
      howChanged: 'With multiple flights a year now, the shuttle was becoming America\'s space workhorse - launching satellites, running experiments, and capturing the public\'s imagination.',
      craze: 'The defining spacecraft of its era and a symbol of the reusable-spaceflight dream.',
      howAged: 'An icon of the space age, beloved despite its complexity. 🚀',
      achievement: '🚀 *Wheels Down*',
    },
    // ── WINDOW 07: MISSION CONTROL ──
    {
      num: 7,
        achievementId: 'nat_space_7',
      emoji: '🎧',
      title: 'HOUSTON, MISSION CONTROL',
      tagline: 'Go for launch',
      whatItWas: 'The rows of headset-wearing flight controllers in Houston who ran every mission - the calm voices and glowing consoles that guided astronauts from liftoff to landing.',
      howChanged: 'As shuttle flights grew busier, Mission Control was the nerve center coordinating launches, spacewalks, and satellite ops with split-second precision.',
      craze: '"Houston" became cultural shorthand for steady hands under pressure.',
      howAged: 'An enduring symbol of meticulous American engineering and teamwork. 🎧',
      achievement: '🎧 *Go for Launch*',
    },
    // ── WINDOW 08: THE ASTRONAUT CORPS ──
    {
      num: 8,
        achievementId: 'nat_space_8',
      emoji: '⭐',
      title: 'THE ASTRONAUTS',
      tagline: 'America\'s spacefarers',
      whatItWas: 'The growing corps of shuttle-era astronauts - pilots, scientists, engineers, and mission specialists - a more diverse group than ever, trained to live and work in orbit.',
      howChanged: 'The shuttle\'s roomy crews opened spaceflight to specialists of all kinds, and astronauts became household heroes for a new generation.',
      craze: 'The astronaut as the ultimate American role model - brave, brilliant, and reaching for the stars.',
      howAged: 'Timeless; "astronaut" remains the dream job of countless kids. ⭐',
      achievement: '⭐ *Right Stuff*',
    },
    // ── WINDOW 09: THE LAUNCH ──
    {
      num: 9,
        achievementId: 'nat_space_9',
      emoji: '🔥',
      title: 'LIFTOFF!',
      tagline: 'Five, four, three, one...',
      whatItWas: 'The shuttle launch itself - the ground-shaking roar of the main engines and solid rocket boosters, the tower of fire and smoke, the slow majestic climb off the pad.',
      howChanged: 'Each launch was an event - crowds gathered, TVs tuned in, and the countdown gripped the nation.',
      craze: 'The launch sequence is one of the most thrilling spectacles humans have ever staged.',
      howAged: 'Still spine-tingling; the countdown is universal shorthand for anticipation. 🔥',
      achievement: '🔥 *We Have Liftoff*',
    },
    // ── WINDOW 10: SPACELAB & SCIENCE IN ORBIT ──
    {
      num: 10,
        achievementId: 'nat_space_10',
      emoji: '🔬',
      title: 'SPACELAB',
      tagline: 'A laboratory in the sky',
      whatItWas: 'The reusable science laboratory that rode in the shuttle\'s cargo bay, letting astronauts run experiments in microgravity - from physics to materials science.',
      howChanged: 'The shuttle was becoming an orbiting research lab, with crews conducting real science high above the Earth.',
      craze: 'It turned the shuttle into a working laboratory and expanded what astronauts could accomplish in orbit.',
      howAged: 'A foundation for decades of space-based research to come. 🔬',
      achievement: '🔬 *Microgravity Lab*',
    },
    // ── WINDOW 11: THE VIEW FROM ORBIT ──
    {
      num: 11,
        achievementId: 'nat_space_11',
      emoji: '🌍',
      title: 'THE BLUE MARBLE',
      tagline: 'Looking back home',
      whatItWas: 'The astronaut\'s-eye view - the whole curved Earth glowing blue and white against the black, the sight that left every spacefarer changed.',
      howChanged: 'Shuttle crews brought back stunning photographs and descriptions of the planet from orbit, feeding the public\'s wonder.',
      craze: 'The "overview effect" - seeing Earth whole, borderless, and fragile - became one of spaceflight\'s most profound gifts.',
      howAged: 'Eternal; that view still reframes how we see ourselves. 🌍',
      achievement: '🌍 *Overview Effect*',
    },
    // ── WINDOW 12: THE SPACE-AGE CRAZE ──
    {
      num: 12,
        achievementId: 'nat_space_12',
      emoji: '🪐',
      title: 'SPACE FEVER',
      tagline: 'Every kid wanted to be an astronaut',
      whatItWas: 'The merchandise and imagination boom the shuttle inspired - model kits, posters, freeze-dried "astronaut ice cream," lunchboxes, and a whole generation of kids gluing together orbiter models on the kitchen table.',
      howChanged: 'With the shuttle flying regularly, space was cool again - classrooms, toy shelves, and bedroom ceilings filled with glow-in-the-dark stars.',
      craze: 'The space program as everyday inspiration, woven into childhood across the country.',
      howAged: 'Pure nostalgia; that astronaut-dream optimism is quintessentially \'80s. 🪐',
      achievement: '🪐 *Space Fever*',
    },
    // ── WINDOW 13: VOYAGER & ROBOTIC EXPLORERS ──
    {
      num: 13,
        achievementId: 'nat_space_13',
      emoji: '📡',
      title: 'THE DEEP-SPACE PROBES',
      tagline: 'Robots at the edge of the solar system',
      whatItWas: 'The uncrewed explorers - probes launched years earlier now sailing past the outer planets, beaming back images of distant worlds no human had ever seen up close.',
      howChanged: 'While the shuttle worked in Earth orbit, robotic explorers were deep in the solar system, expanding the map of the planets.',
      craze: 'These probes delivered humanity\'s first close-up looks at the giant outer worlds and their moons.',
      howAged: 'Legendary; some of these explorers would eventually leave the solar system entirely. 📡',
      achievement: '📡 *Deep Space Signal*',
    },
    // ── WINDOW 14: THE CONCORDE ──
    {
      num: 14,
        achievementId: 'nat_space_14',
      emoji: '✈️',
      title: 'THE CONCORDE',
      tagline: 'Faster than a speeding bullet',
      whatItWas: 'The needle-nosed, droop-snooted supersonic airliner that crossed the Atlantic at twice the speed of sound, carrying passengers from New York to London in a few short hours.',
      howChanged: 'The height of luxury and speed in the air - a champagne-and-supersonic experience for those who could afford the ticket.',
      craze: 'The most glamorous, futuristic airliner ever to fly; a symbol of jet-set elegance.',
      howAged: 'An icon of aviation history, beloved and unmatched in its niche. ✈️',
      achievement: '✈️ *Mach 2*',
    },
    // ── WINDOW 15: MILITARY JETS ──
    {
      num: 15,
        achievementId: 'nat_space_15',
      emoji: '✈️',
      title: 'THE FIGHTER JETS',
      tagline: 'Top of the sky',
      whatItWas: 'The sleek, powerful military aircraft of the era - supersonic fighters and interceptors that screamed across the sky, the cutting edge of aviation technology.',
      howChanged: 'Military aviation was at a peak of public fascination, with airshows drawing huge crowds and fighter jets the stuff of poster-on-the-wall dreams.',
      craze: 'The fighter pilot as a symbol of speed, skill, and the thrill of flight.',
      howAged: 'Timeless aviation cool; the jet-fighter mystique never faded. ✈️',
      achievement: '✈️ *Afterburner*',
    },
    // ── WINDOW 16: COMMERCIAL FLIGHT ──
    {
      num: 16,
        achievementId: 'nat_space_16',
      emoji: '🛫',
      title: 'THE JET AGE',
      tagline: 'The friendly skies',
      whatItWas: 'The everyday miracle of commercial air travel - wide-body jumbo jets packed with travelers, crisscrossing the country and the world at the press of a ticket.',
      howChanged: 'Flying was woven into modern life - family vacations, business trips, the whole country newly connected by the jet.',
      craze: 'Air travel reshaped how people lived, worked, and saw the world.',
      howAged: 'The backbone of modern mobility; the jumbo jet remains an icon. 🛫',
      achievement: '🛫 *Cleared for Takeoff*',
    },
    // ── WINDOW 17: THE AVIATION PIONEERS ──
    {
      num: 17,
        achievementId: 'nat_space_17',
      emoji: '🛩️',
      title: 'THE PIONEERS OF FLIGHT',
      tagline: 'Standing on the shoulders of dreamers',
      whatItWas: 'A nod to the legends who got humanity into the air and beyond - the barnstormers, record-breakers, and test pilots whose courage paved the way from the first powered flights to the edge of space.',
      howChanged: 'Eight decades after the first powered flight, the shuttle astronauts were the latest link in an unbroken chain of aviation daring.',
      craze: 'The pioneering spirit that carried humanity from canvas-and-wood biplanes to reusable spaceplanes.',
      howAged: 'Eternal; every astronaut stands on that legacy. 🛩️',
      achievement: '🛩️ *Pioneer Spirit*',
    },
    // ── WINDOW 18: THE NIGHT SKY & THE DREAM ──
    {
      num: 18,
        achievementId: 'nat_space_18',
      emoji: '🌌',
      title: 'REACH FOR THE STARS',
      tagline: 'Look up',
      whatItWas: 'The simple, timeless pull of the night sky - the dream that drove the whole enterprise, the reason kids pressed their faces to bedroom windows and pointed telescopes at the moon.',
      howChanged: 'With astronauts flying free in orbit and probes sailing past distant planets, the sky felt closer than ever - and the future felt limitless.',
      craze: 'The dream of space as humanity\'s great shared adventure.',
      howAged: 'Eternal; we\'re still looking up. 🌌',
      achievement: '🌌 *Reach for the Stars*',
    },
  ],
};